### PR TITLE
Add support for SLE 12 SP4 in create_hdd_hpc_textmode

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@okurz - here is result of our discussion . WDYT ? 
@alice-suse solving of same problem that you have in a cheap way 
@czerw  please take a look if this will break something in QAM ? How can I filter out QAM cases ?

**Comment by asmorodskyi** [comment]
proof run - http://kimball.arch.suse.de/tests/1269

**Comment by okurz** [comment]
+1

**Comment by alice-suse** [comment]
@asmorodskyi  Yes, we take similar ways to handle, difference is in virtualization jobs, we need to handle quite a number of testsuites settings which are used when calling underlying test scripts, in such a way that the settings are set correctly for all test products accordingly, for example sle15, sle12sp4.

**Comment by czerw** [comment]
Not sure if it is correct approach, you are basically setting input variables based on combination of another input variables. Why don't you make a difference at media level? You can check it for SP3 https://openqa.suse.de/tests/1781213 with medium definition Server-DVD-Incidents-HPC.

**Comment by asmorodskyi** [comment]
@czerw I can't introduce this changes to medium which I am currently using because it can break some other things . I don't want to introduce another medium because I don't want to care triggering in all cases when it happens for SLE Functional tests ( support in rsync.pl + all cases of manual trigger with whatever reason )

**Comment by czerw** [comment]
@asmorodskyi ok, if it is not possible to use different medium, do as you suggest.

**Comment by asmorodskyi** [comment]
Merging based on 2 LGTMs from @okurz and @czerw

**Comment by czerw** [comment]
@asmorodskyi so this cheap hardcoded solution is causing more troubles than it should. Proper solution would be independent medium as it was already suggested.
Anton could you please check my solution which is workaround for workaround and later revise whole scenario and possible remove workaround  in the future?

**Pull request merged**
