### PR TITLE
Make sure that autoyast2 is installed before clone_system

### PR DESCRIPTION
**Pull request by b10n1k**
Call zypper in on /autoyast2/ package which provides the clone_system yast
feature. This makes the module autonomous and self-contained. In case the
package is already installed, this addition would not cause any destructions
and the flow will continue as expected. I added a timeout because i encounter
some issues on aarch64. no needed for x86_64.

The missing package seems to affect only SLE.

Signed-off-by: Ioannis Bonatakis <ybonatakis@suse.com>

- Verification run: http://aquarius.suse.cz/tests/11366
[latest](http://aquarius.suse.cz/tests/11413)

### CODE REVIEW

**Review by ge0r — COMMENTED** [review]
Shouldn't you also add the line `zypper_call('in autoyast2')` given that the previous commit that had this line got reverted?
Also from your verification run link, it does not look like this branch's changes have been applied to the run's [tests/autoyast/clone.pm](http://aquarius.suse.cz/tests/11366/modules/clone/steps/1/src.txt)

**Comment by b10n1k** [comment]
> Shouldn't you also add the line `zypper_call('in autoyast2')` given that the previous commit that had this line got reverted?
> Also from your verification run link, it does not look like this branch's changes have been applied to the run's [tests/autoyast/clone.pm](http://aquarius.suse.cz/tests/11366/modules/clone/steps/1/src.txt)

ofc and i feel stupid. I though it was there somehow. 

> Shouldn't you also add the line `zypper_call('in autoyast2')` given that the previous commit that had this line got reverted? Also from your verification run link, it does not look like this branch's changes have been applied to the run's [tests/autoyast/clone.pm](http://aquarius.suse.cz/tests/11366/modules/clone/steps/1/src.txt)

ofc. i forgot to rebase from master so it took only this changed. fixed

**Comment by ge0r** [comment]
Thanks! Could you also update the VR link just to be sure?

**Review by ge0r — APPROVED** [review]
Nice thanks!

**Pull request merged**
