### PR TITLE
Permit root ssh for system with CC system role

### PR DESCRIPTION
**Pull request by rfan1**
In "Common Criteria System Role" system, root ssh login
is disabled by default, we need enable it on 390x to fit openQA
tests. btw, Enhance the code to locate the root disk rather than
hardcode the disk name

- Related ticket: https://progress.opensuse.org/issues/98715
- Verification run: 
x86_64: https://openqa.suse.de/tests/7200097#
arm:       https://openqa.suse.de/tests/7200098#
s390x:   https://openqa.suse.de/tests/7200087#

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
LGTM

**Comment by jouyingbin** [comment]
@rfan1 Look good to me :) BTW, can you also provide a link in the PR description if we did not apply the patch, it will have a softfail result, right?

**Review by jouyingbin — APPROVED** [review]
LGTM

**Review by Amrysliu — APPROVED** [review]
LGTM

**Pull request merged**
