### PR TITLE
Query complex command line with quotes

### PR DESCRIPTION
**Pull request by waynechen55**
* **Enclose** with queried command line with quotes to ensure correct query result.
* **Verification run:**
  * [Verification run](http://10.67.129.106/tests/1325#step/uefi_guest_installation/454)

### CODE REVIEW

**Comment by waynechen55** [comment]
@alice-suse @Julie-CAO @guoxuguang @nanzhg

**Comment by nanzhg** [comment]
LGTM

**Comment by guoxuguang** [comment]
LGTM

**Comment by Julie-CAO** [comment]
LGTM

**Pull request merged**
