### PR TITLE
Create autoyast profiles for HPC 12SP5 maint job group

### PR DESCRIPTION
**Pull request by b10n1k**
AUTOYAST variable will move to the job settings of kernel-openqa-yaml to distiguish the ones used on SLE12 and SLE15

- Related ticket: https://progress.opensuse.org/issues/136253
- Verification run: 
https://aquarius.suse.cz/tests/19175
https://openqa.suse.de/tests/overview?distri=sle&version=12-SP5&build=b10n1k%2Fos-autoinst-distri-opensuse%2317843

### CODE REVIEW

**Comment by b10n1k** [comment]
Also https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/-/merge_requests/370

**Comment by czerw** [comment]
I would use as description in commit message: "Add autoyast profiles for SLE HPC 12-SP5" 
And content: "AUTOYAST variable will be moved to the job group configuration to make difference between  SLE12 and SLE15."

**Review by schlad — CHANGES_REQUESTED** [review]
"AUTOYAST variable will be moved "
The above isn't optimal. git commit message should not be written with future tense. Ideally it would be written in such way:
"AUTOYAST variable is being moved...."

**Review by schlad — APPROVED** [review]

**Comment by schlad** [comment]
> I would use as description in commit message: "Add autoyast profiles for SLE HPC 12-SP5" And content: "AUTOYAST variable will be moved to the job group configuration to make difference between SLE12 and SLE15."

I agree. I also wish we don't use words like: maint but rather use the full version. In short: I wish openqa is a project where git is used as it was intended :-) so git commit messages are nice and explanatory :-)

**Review by czerw — APPROVED** [review]

**Pull request merged**
