### PR TITLE
 Solve the problem of SUT installation failure.

### PR DESCRIPTION
**Pull request by museQi**
SUT installation failure due to sending cmd too quick to get respond from installer. So solve the problem.
- Verification run: http://10.67.129.7/tests/1822

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @zyuhu please help me review.

**Comment by XGWang0** [comment]
LGTM

**Comment by zyuhu** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse Please help me review and merge.

**Comment by alice-suse** [comment]
@museQi  Hi Qi, a minor request, would you please update the commit msg a little bit? Capitalize first character and make it shorter, for best practice?

**Comment by museQi** [comment]
@alice-suse Thank you for your advice. I have updated the commit msg.

**Comment by alice-suse** [comment]
> @alice-suse Thank you for your advice. I have updated the commit msg.

I saw PR title updated. 
The commit msg for git is in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16487/commits.

**Comment by museQi** [comment]
@alice-suse Please check.

**Comment by JoyceNa** [comment]
LGTM

**Pull request merged**
