### PR TITLE
Use virtio console without needles on HPC mrsh test

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: #11262 
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1458/diffs
- Verification run:  http://10.100.12.155/tests/16849

### CODE REVIEW

**Comment by schlad** [comment]
@dzedro do you ever sleep? :D

**Review by schlad — APPROVED** [review]
ah I see. You just sleep(1) ;-)

**Review by ggkioulis — APPROVED** [review]

**Comment by dzedro** [comment]
works nice https://openqa.suse.de/tests/4876504

**Comment by schlad** [comment]
> works nice https://openqa.suse.de/tests/4876504

yupi. thx again!

**Pull request merged**
