### PR TITLE
hpc: Add libsolv installcheck scenario

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
I think you are re-implementing https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/installcheck.pm

@coolo?

**Comment by asmorodskyi** [comment]
@okurz can't agree with you. Only thing which is in common is the fact of using installcheck.

**Comment by coolo** [comment]
the installcheck.pm module is purely for a base product, not for modules. It would be a good to make this a little more generic though

**Comment by asmorodskyi** [comment]
proof run - http://kimball.arch.suse.de/tests/1474

**Pull request merged**
