### PR TITLE
sudo: Stop trying to read from /proc/sys/vm/drop_caches

### PR DESCRIPTION
**Pull request by DimStar77**
In newer kernels (>= 5.4), the drop_caches proc file has been turned into a
write-only file. As such, reading from it is no longer permitted.

https://github.com/torvalds/linux/commit/204cb79ad42f015312a5bbd7012d09c93d9b46fb

- Related ticket: https://progress.opensuse.org/issues/62168
- Needles: N/A
- Verification run: https://openqa.opensuse.org/tests/1158750 (passed)

### CODE REVIEW

**Comment by Vogtinator** [comment]
Why not just redirect to some file in `/run` or `/etc`?

**Comment by DimStar77** [comment]
> Why not just redirect to some file in /run or /etc?

redirect what and when?

**Comment by Vogtinator** [comment]
The `tests/ha/remove_node.pm` change looks unrelated, probably needs a rebase.

It might be useful to remove the file again afterwards, but as it's just one byte in size...

So LGTM after rebase.

**Comment by DimStar77** [comment]
> The `tests/ha/remove_node.pm` change looks unrelated, probably needs a rebase.
Yap, seen that already.. rebased

**Comment by DimStar77** [comment]
VR passed: https://openqa.opensuse.org/tests/1158750#step/sudo/86

**Pull request merged**
