### PR TITLE
Add baseline-lynis for 15-sp2

### PR DESCRIPTION
**Pull request by paolostivanin**
Add data files for 15-SP2 needed by https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/247

Related poo:
- https://progress.opensuse.org/issues/93769
- https://progress.opensuse.org/issues/93766

### CODE REVIEW

**Comment by lilyeyes** [comment]
Are there any openQA verification runs? It could be easier or good references for baseline review.
For the baselines I usually ask developer jsegitz@suse.de to help to check as there are some permitted status such as "EXPOSED/UNSAFE/..."

**Comment by rfan1** [comment]
Minor comment :
Change the title to:
Add baseline-lynis for 15-sp2

**Comment by lilyeyes** [comment]
FYI, I found out a lynis "2.6.1" version (same lynis version on 15sp2) verification runs on sle15sp4 for reference: https://openqa.suse.de/tests/7716986#step/lynis_setup/10

We can compare the baselines with paolo's

**Comment by lilyeyes** [comment]
I only have compared "baseline-lynis-audit-system-nocolors-15-SP2-x86_64-textmode" with https://openqa.suse.de/tests/7716987#
Only 1 minor issue found on your baseline:     `- Minimal of 2 responsive nameservers                     [ WARNING ]` only exist 
But it is OK for me, if you have concerns on this minor issue you can ask developer to confirm.
So for other baselines please ask others to check or check by yourself.


FYI:
[+] Networking
------------------------------------
  - Checking IPv6 configuration                               [ ENABLED ]
      Configuration method                                    [ AUTO ]
      IPv6 only                                               [ NO ]
  - Checking configured nameservers
    - Testing nameservers
        Nameserver: 10.100.192.1                              [ OK ]
    - Minimal of 2 responsive nameservers                     [ WARNING ]

**Comment by paolostivanin** [comment]
Verification runs also for textmode: https://openqa.suse.de/group_overview/431

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by tjyrinki** [comment]
Nice, verification runs are looking really great!

**Pull request merged**
