### PR TITLE
Run desktop tests when installing we via ftp or http

### PR DESCRIPTION
**Pull request by sysrich**

### CODE REVIEW

**Comment by coolo** [comment]
this will match if ADDONURL starts with http://ourserwer :)

**Comment by coolo** [comment]
ok, ADDONURL is not really a URL. What a cleverly named variable .)

**Comment by dzedro** [comment]
ADONURL has to be url not just we ...

**Comment by dzedro** [comment]
ye ADDONURL_"addon" is url ><

**Comment by sysrich** [comment]
@dzedro then explain https://openqa.suse.de/tests/381375 and https://openqa.suse.de/tests/381376 please? :) ADDONURL = 'we' for both of them...

**Comment by dzedro** [comment]
explanation came first :D

**Pull request merged**
