### PR TITLE
Test changes for kubevirt v1.1.0

### PR DESCRIPTION
**Pull request by nanzhg**
1. bsc#1217658 - add config file to enable `device_ownership_from_security_context` CRI option
2. bsc#1217660 - skip test case "hugepages-2Mi with passt enabled" & "virtiofs VirtIO-FS with multiple PVCs should be successfully started and accessible with passt enabled"
3. Create a tmpfs mount point '/var/provision/kubevirt.io/tests' for kubevirt agent test module

- Related ticket: https://progress.opensuse.org/issues/133598
- Verification run: http://10.67.129.96/tests/2696

### CODE REVIEW

**Comment by nanzhg** [comment]
In current verification run, there are still 4 test failures.
- The test failure [test_id:3190] in datavolume_test refers to bsc#1218174.
- Other 3 test failures in vmi_configuration_test are known issue as the node list related hard code([link](https://github.com/kubevirt/kubevirt/blob/e8e638edc22587ec7be2cc3d983b61763e33f973/tests/vmi_configuration_test.go#L2800)) in current test.

**Comment by nanzhg** [comment]
@alice-suse @xguo @waynechen55 @Julie-CAO @tbaev @RoyCai7 please help to review this PR. Thanks

**Comment by waynechen55** [comment]
I think you can add tests/templates by release/version, so does your test.

**Comment by nanzhg** [comment]
> I think you can add tests/templates by release/version, so does your test.

Hi @waynechen55,
Could you explain how to do it? Or any instruction I can follow?
Thanks

**Comment by waynechen55** [comment]
> > I think you can add tests/templates by release/version, so does your test.
> 
> Hi @waynechen55, Could you explain how to do it? Or any instruction I can follow? Thanks

I noticed that you need to update config file each time there is change. So I think you can create config based on realease/version and also load these configs based release/version:
KUBEVIRT_VERSION=xxxxx
sub load_kubevirt_config {
     load_config("config_file_$KUBEVIRT_VERSION");
}
So you can also give KUBEVIRT_VERSION=debugging;

**Comment by nanzhg** [comment]
@waynechen55 Actually, we expected to maintain only one config file for latest version, so its test list will keep updated which depends on latest changes for kubevirt tests.

**Comment by waynechen55** [comment]
> @waynechen55 Actually, we expected to maintain only one config file for latest version, so its test list will keep updated which depends on latest changes for kubevirt tests.

OK.

**Comment by alice-suse** [comment]
> @waynechen55 Actually, we expected to maintain only one config file for latest version, so its test list will keep updated which depends on latest changes for kubevirt tests.

@nanzhg  Hi Nan, I think this would be a valid suggestion when we automate kubevirt test for MU incident  in https://progress.opensuse.org/issues/154015, then we will need to maintain different versions on different product versions. 
So, let's merge it this way at the moment. Please consider this later :) .

**Comment by nanzhg** [comment]
> @nanzhg Hi Nan, I think this would be a valid suggestion when we automate kubevirt test for MU incident in https://progress.opensuse.org/issues/154015, then we will need to maintain different versions on different product versions. So, let's merge it this way at the moment. Please consider this later :) .

OK, currently it doesn't support MU incident, and also some code support for kubevirt older version has been removed.

**Comment by alice-suse** [comment]
> > @nanzhg Hi Nan, I think this would be a valid suggestion when we automate kubevirt test for MU incident in https://progress.opensuse.org/issues/154015, then we will need to maintain different versions on different product versions. So, let's merge it this way at the moment. Please consider this later :) .
> 
> OK, currently it doesn't support MU incident, and also related code support for kubevirt older version has been removed. Probably we need to recover it back for MU tests.

Yes, this is newly confirmed requirement. BTW, the MU kubevirt versions are updating too, which may differ from our abandoned  older version. Let's see and take reasonable decisions then.

**Comment by nanzhg** [comment]
> > > @nanzhg Hi Nan, I think this would be a valid suggestion when we automate kubevirt test for MU incident in https://progress.opensuse.org/issues/154015, then we will need to maintain different versions on different product versions. So, let's merge it this way at the moment. Please consider this later :) .
> > 
> > 
> > OK, currently it doesn't support MU incident, and also related code support for kubevirt older version has been removed. Probably we need to recover it back for MU tests.
> 
> Yes, this is newly confirmed requirement. BTW, the MU kubevirt versions are updating too, which may differ from our abandoned older version. Let's see and take reasonable decisions then.

OK, let's wait and see.:)

**Pull request merged**
