### PR TITLE
Fix the issue for spectre_v2 on skylake machine

### PR DESCRIPTION
**Pull request by museQi**
Fix the issue for spectre_v2 on skylake machine

- Related ticket: https://progress.opensuse.org/issues/136091
- Verification run:http://10.67.129.4/tests/62267 (sle15sp5 maintain update)

### CODE REVIEW

**Comment by museQi** [comment]
@zyuhu Please help me review.

**Comment by zyuhu** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse please help me merge.

**Comment by alice-suse** [comment]
@museQi  Hi Qi, will it be good to merge the 3 commits into 1 before merge? `git rebase -i HEAD~3` will help you do this.

**Comment by museQi** [comment]
> @alice-suse please help me merge.
Thank you alice. I have updated it. Please check it and merge.

**Pull request merged**
