### PR TITLE
Fix nvmftests

### PR DESCRIPTION
**Pull request by frankenmichl**
Small changes to fix nvmftests
- reduce timeout. increasing it was not solving any issues.
- install packages without recommended packages.

### CODE REVIEW

**Comment by ldevulder** [comment]
Changes look good, but can you add a verification run to be sure?

**Comment by okurz** [comment]
Please start each git commit message subject line with a capital letter and let the git message describe the "why", not the how

**Comment by rwx788** [comment]
I do not see major risks here, so let's try it out ;)

**Comment by okurz** [comment]
No risk but it's good to keep a clean git log

**Pull request merged**
