### PR TITLE
Revisit wrong settings for HA migrations

### PR DESCRIPTION
**Pull request by tinawang123**
Revisit wrong settings for HA migrations

- Related ticket: https://progress.opensuse.org/issues/120444
- Verification run: https://openqa.suse.de/tests/10291139
  http://openqa.suse.de/t10307585
https://openqa.suse.de/tests/10307721
aarch 15sp3
 http://openqa.suse.de/t10307586
 https://openqa.suse.de/tests/10307632
s390x 15sp2

### CODE REVIEW

**Review by b10n1k — COMMENTED** [review]
i wonder if those xmls are used on other arches! if so it would be reasonable to run a few more VR. What do you think?

**Comment by rakoenig** [comment]
LGTM

**Comment by tinawang123** [comment]
> i wonder if those xmls are used on other arches! if so it would be reasonable to run a few more VR. What do you think?

Updated, Thanks

**Review by b10n1k — APPROVED** [review]
thanks for VRs

**Pull request merged**
