### PR TITLE
Accept package retry workaround boo1018262

### PR DESCRIPTION
**Pull request by michelmno**
assume related needle is available from
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/208

Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sysrich** [comment]
As this is a workaround for a bug, I'd expect to see the use of `record_soft_failure` Inside the if statement so we still know when we hit the issue and when it's been fixed (or not)

**Comment by michelmno** [comment]
I missed the requirement for the "record_soft_failure" call, I will change my patch, I thought

**Comment by michelmno** [comment]
I added the "record_soft_failure" call in above commit

**Comment by sysrich** [comment]
Thanks

For reference, the rule regarding 'workaround tag' vs 'record_soft_failure' is pretty simple

1) If the test logic does not need to change, but the bug can be worked around by just adding a new needle - use a workaround tag

2) if the test logic needs to change, record_soft_failure. If the new logic needs a specific needle also, a specific tag and a workaround tag are good ideas also.

Thanks!

**Pull request merged**
