### PR TITLE
Add rsync tests for sles 15 functional

### PR DESCRIPTION
**Pull request by Zaoliang**
update rsync_server.pm for switching to yaml schedule.
remove job group from sle/main.pm so that qam-rsync tests can use yaml
schedule later.

see https://progress.opensuse.org/issues/92911
verification runs:
http://10.160.64.152/tests/2660#dependencies

### CODE REVIEW

**Comment by asdil12** [comment]
Remember to guard the barriers with a mutex when you create them in the test module.

**Comment by Zaoliang** [comment]
> Remember to guard the barriers with a mutex when you create them in the test module.

mutex_create 'barrier_setup_done' is already there under # setup of rsync server done.

Should this be moved to after the last barrier_create ?

**Comment by asdil12** [comment]
Yes - otherwise the client can't do it's setup in parallel (depending on the position of the corresponding mutex line there).
I wonder why this is already the second file where it is already there, even though the barriers used to be created outside (hence being not needed yet at that time) and also not at the beginning of the file.

**Comment by Zaoliang** [comment]
@asdil12 Talked to dzedro about the issue with setup_multimachine, he is going to fix the issue now.
So my PR got updated now, thanks!

**Comment by Zaoliang** [comment]
the issue with setup_mulitmachine got fixed now: 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12600

**Review by asdil12 — APPROVED** [review]
LGTM

**Comment by dzedro** [comment]
https://openqa.suse.de/tests/6116984

**Pull request merged**
