### PR TITLE
Enable sqlite3 and postgresql_server tests on ALP

### PR DESCRIPTION
**Pull request by DeepthiYV**
- Related ticket:https://progress.opensuse.org/issues/116057
- Needles: No
- Verification run: 
   [alp-0.1-kvm-x86_64](http://deepthi-openqa.qam.suse.de/tests/4014#step/sqlite3/1)

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
I think it would be better to extract that concept of `just install package` elsewhere and reuse in test modules. On the other hand, a reboot in every single test module sounds quite expensive. Isn't the idea of ALP to run the workload in containers? That would apply here in particular for databases

**Comment by DeepthiYV** [comment]
> I think it would be better to extract that concept of `just install package` elsewhere and reuse in test modules. On the other hand, a reboot in every single test module sounds quite expensive. Isn't the idea of ALP to run the workload in containers? That would apply here in particular for databases

I think installation of the package is handled in single function `trup_call` and as suggested in the ticket - https://progress.opensuse.org/issues/115196#note-20, I just called the trup_call  function in root-console for the transactional update. I will take a note on the reboot after every module installation.
As I understood we are doing smoke test of ALP and so we are making changes. @foursixnine, please correct me if I'm wrong

**Comment by foursixnine** [comment]
> > I think it would be better to extract that concept of `just install package` elsewhere and reuse in test modules. On the other hand, a reboot in every single test module sounds quite expensive. Isn't the idea of ALP to run the workload in containers? That would apply here in particular for databases
> 
> I think installation of the package is handled in single function `trup_call` and as suggested in the ticket - https://progress.opensuse.org/issues/115196#note-20, I just called the trup_call function in root-console for the transactional update. I will take a note on the reboot after every module installation. As I understood we are doing smoke test of ALP and so we are making changes. @foursixnine, please correct me if I'm wrong

Indeed, the intent has been even shared on the irc channel: https://matrix.to/#/!lCErltlTrMqnzHmKMf:opensuse.org/$4eGIlHWmO6VACZvQpw4sjFOYPw5T2JEU1nGqR7mKs9M?via=libera.chat&via=opensuse.org&via=matrix.org

This will be even more valid after the switch away from TW for containers. As for the boot and reboot of the system, there's little to do/discuss for now

**Comment by okurz** [comment]
> As for the boot and reboot of the system, there's little to do/discuss for now

what do you mean by that?

**Comment by foursixnine** [comment]
> > As for the boot and reboot of the system, there's little to do/discuss for now
> 
> what do you mean by that?

for now we can rely on rebooting the system 2 or 3 times per test, and likely finding a solution for [115196#note-20](https://progress.opensuse.org/issues/115196#note-20) should also help to reduce how expensive transactional systems would be

**Comment by okurz** [comment]
> > > As for the boot and reboot of the system, there's little to do/discuss for now
> > 
> > 
> > what do you mean by that?
> 
> for now we can rely on rebooting the system 2 or 3 times per test, and likely finding a solution for [115196#note-20](https://progress.opensuse.org/issues/115196#note-20) should also help to reduce how expensive transactional systems would be

Yes, we could. But it is quite likely that as soon as code like this is in people add to the mess and the chance to clean it up and do it properly never comes. So I would say do it properly from the beginning to find a concept how to test multiple services on transactional servers though I am arguing that this isn't even required and we should use containers right away from the beginning.

**Review by okurz — CHANGES_REQUESTED** [review]
> > > As for the boot and reboot of the system, there's little to do/discuss for now
> > 
> > 
> > what do you mean by that?
> 
> for now we can rely on rebooting the system 2 or 3 times per test, and likely finding a solution for [115196#note-20](https://progress.opensuse.org/issues/115196#note-20) should also help to reduce how expensive transactional systems would be

Yes, we could. But it is quite likely that as soon as code like this is in people add to the mess and the chance to clean it up and do it properly never comes. So I would say do it properly from the beginning to find a concept how to test multiple services on transactional servers though I am arguing that this isn't even required and we should use containers right away from the beginning.

**Comment by foursixnine** [comment]
@DeepthiYV I think for now, we can close this PR and come back later, once these workloads are already available

**Pull request closed without merging**
