### PR TITLE
Avoid rare fails with higher timeout

### PR DESCRIPTION
**Pull request by dzedro**
Should fix http://openqa.suse.de/tests/409978/modules/curl_https/steps/5

### CODE REVIEW

**Comment by okurz** [comment]
I don't think so. The screen shows nothing has been transferred at all so I think the situation does not change just by waiting longer. Please reproduce locally first before trying to fix.

**Comment by dzedro** [comment]
I was not able to reproduce this with two parallel jobs (which is high load on my desktop) and 65 tries of curl_https in a row.
previous wait_serial, steps of validate_script_output have default timeout 90 seconds

http://10.100.98.90/tests/1948/modules/curl_https/steps/1

```
08:33:04.4258 Debug: /var/lib/openqa/share/tests/sle/tests/console/curl_https.pm:18 called testapi::validate_script_output
08:33:04.4261 <<< wait_serial(regex='JgRME', timeout=90)
08:33:05.5003 >>> wait_serial: JgRME: ok
08:33:05.5005 Debug: /var/lib/openqa/share/tests/sle/tests/console/curl_https.pm:18 called testapi::validate_script_output
08:33:05.5006 <<< type_string(string='(/bin/bash -ex /tmp/scriptWglCT.sh ; echo SCRIPT_FINISHEDWglCT-$?- )| tee /dev/ttyS0
', max_interval=250)
08:33:11.4858 Debug: /var/lib/openqa/share/tests/sle/tests/console/curl_https.pm:18 called testapi::validate_script_output
08:33:11.4860 <<< wait_serial(regex='SCRIPT_FINISHEDWglCT-\\d+-', timeout=30)
08:33:42.5713 >>> wait_serial: SCRIPT_FINISHEDWglCT-\d+-: fail
```

**Comment by okurz** [comment]
hm, ok. I guess you might only be able to reproduce it when you run much much more, maybe while 100 other jobs are running and in the same network as osd. So let's try this and see what happens. Please keep an eye on this issue and update the progress issue accordingly. I am not sure we are done here after all :-/

**Comment by dzedro** [comment]
I don't say we are done :) I will track this issue.

**Pull request merged**
