### PR TITLE
Enable virtio/serial console on console filesystem tests

### PR DESCRIPTION
**Pull request by dzedro**
- Verification run:
https://openqa.suse.de/tests/5391179 12-SP5 x86_64
https://openqa.suse.de/tests/5391180 12-SP5 aarch64
https://openqa.suse.de/tests/5390859 15-SP2 x86_64
https://openqa.suse.de/tests/5390860 15-SP2 aarch64
https://openqa.suse.de/tests/5390862 15-SP3 x86_64
https://openqa.suse.de/tests/5390862 15-SP3 ppc64le
https://openqa.opensuse.org/tests/1612345 TW jeos
https://openqa.opensuse.org/tests/1612344 TW x86_64
https://openqa.opensuse.org/tests/1612404 TW ppc64le
https://openqa.opensuse.org/tests/1612373 TW aarch64 failures https://openqa.opensuse.org/tests/1609548

### CODE REVIEW

**Comment by asdil12** [comment]
Please correct the typo in your commit description.

**Comment by asdil12** [comment]
The rest looks good.

**Comment by dzedro** [comment]
Fixed typos

**Review by asdil12 — APPROVED** [review]
LGTM

**Pull request merged**
