### PR TITLE
Also ensure SCC_EMAIL is not typing nothing

### PR DESCRIPTION
**Pull request by okurz**
See https://openqa.suse.de/tests/1129995#step/scc_registration/2

Related progress issue: https://progress.opensuse.org/issues/23506

### CODE REVIEW

**Comment by okurz** [comment]
Nah, I was wrong. Also SLE 12 SP3 works fine with no email address: https://openqa.suse.de/tests/1058778#step/scc_registration/2

**Comment by DrMullings** [comment]
LGTM

**Comment by okurz** [comment]
@rwx788 I updated the commit to just prevent perl warnings when trying to call `type_string` on an undef value. We now still allow empty values for the test variable so that we could also test explicitly empty values.

**Comment by rwx788** [comment]
We could have used get_var('SCC_EMAIL', '') then. But fine, doesn't hurt much.

**Comment by okurz** [comment]
@rwx788 so call type_string with an empty string? Not much better IMHO

**Pull request merged**
