### PR TITLE
[qa_automation] Remove apache testsuite temporarily

### PR DESCRIPTION
**Pull request by jtzhao**
Remove qa_automation/userspace_apache.pm temporarily due to bug 907452

### CODE REVIEW

**Comment by sysrich** [comment]
Please do not merge, want to discuss this first

**Comment by sysrich** [comment]
Merged reluctantly - do not like the fact that this test case was left broken for over a year

**Comment by coolo** [comment]
you also need to remove the job group entry - in case you didn't already

**Comment by SeroSun** [comment]
@coolo OK, I removed it from job group

**Pull request merged**
