### PR TITLE
Merge yaml file of skip_registration and releasenotes_origin+unregistered

### PR DESCRIPTION
**Pull request by lemon-suse**
Create single scenario where we skip registration and check the release notes origin.  This PR  fixed partially of the ticket, pending part is to have single test suite yaml file under schedule/yam/test_cases/ used in all architectures.

- Related ticket: https://progress.opensuse.org/issues/153067
- Related MR: https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/35 (Merge MR first so won't have files conflict)
- Needles: N/A
- Verification run: 
  http://openqa.nue.suse.com/tests/13239298#
   http://openqa.nue.suse.com/tests/13239299

### CODE REVIEW

**Comment by hjluo** [comment]
LGTM.

**Comment by jknphy** [comment]
Please mention in PR that they resolve partially the ticket, otherwise we might get confused that is the whole solution.
Pending part is to have single test suite yaml file under `schedule/yam/test_cases/` used in all architectures.
Additionally tickets in this epic suggest to clean-up vars and any other things as much as possible.

**Comment by lemon-suse** [comment]
> Please mention in PR that they resolve partially the ticket, otherwise we might get confused that is the whole solution. Pending part is to have single test suite yaml file under `schedule/yam/test_cases/` used in all architectures. Additionally tickets in this epic suggest to clean-up vars and any other things as much as possible.

Ok, updated the PR description. So you mean we should have a single test yaml file for all arches, then do we still need the yaml files for each arches any more?
I will have a look to clean-up vars and something else such as description.

**Comment by jknphy** [comment]
> > Please mention in PR that they resolve partially the ticket, otherwise we might get confused that is the whole solution. Pending part is to have single test suite yaml file under `schedule/yam/test_cases/` used in all architectures. Additionally tickets in this epic suggest to clean-up vars and any other things as much as possible.
> 
> Ok, updated the PR description. So you mean we should have a single test yaml file for all arches, then do we still need the yaml files for each arches any more? I will have a look to clean-up vars and something else such as description.

we need to unify those yaml, we created several yaml to make the problem 'solvable' but now we can attempt to clean up. Check the epic, basically we want to have 1 single yaml representing the test suite and then each job in its specific architecture will use a different default base yaml.

**Comment by lemon-suse** [comment]
> > > Please mention in PR that they resolve partially the ticket, otherwise we might get confused that is the whole solution. Pending part is to have single test suite yaml file under `schedule/yam/test_cases/` used in all architectures. Additionally tickets in this epic suggest to clean-up vars and any other things as much as possible.
> > 
> > 
> > Ok, updated the PR description. So you mean we should have a single test yaml file for all arches, then do we still need the yaml files for each arches any more? I will have a look to clean-up vars and something else such as description.
> 
> we need to unify those yaml, we created several yaml to make the problem 'solvable' but now we can attempt to clean up on test suite at a time. Check the epic, basically we want to have 1 single yaml representing the test suite and then each job in its specific architecture will use a different default base yaml.

Created the single yaml file, please have a look. Currently there existing default_x86_64.yaml, but no default_aarch64.yaml, how do you think to copy the default_x86_64.yaml named as default_aarch64.yaml since they are same in context?

**Comment by jknphy** [comment]
> > > > Please mention in PR that they resolve partially the ticket, otherwise we might get confused that is the whole solution. Pending part is to have single test suite yaml file under `schedule/yam/test_cases/` used in all architectures. Additionally tickets in this epic suggest to clean-up vars and any other things as much as possible.
> > > 
> > > 
> > > Ok, updated the PR description. So you mean we should have a single test yaml file for all arches, then do we still need the yaml files for each arches any more? I will have a look to clean-up vars and something else such as description.
> > 
> > 
> > we need to unify those yaml, we created several yaml to make the problem 'solvable' but now we can attempt to clean up on test suite at a time. Check the epic, basically we want to have 1 single yaml representing the test suite and then each job in its specific architecture will use a different default base yaml.
> 
> Created the single yaml file, please have a look. Currently there existing default_x86_64.yaml, but no default_aarch64.yaml, how do you think to copy the default_x86_64.yaml named as default_aarch64.yaml since they are same in context?

the idea is to have the minimum number of files, so if the files doesn't exist, then it is not needed, the problem is the name I guess, we could use `schedule/yast/sle/flows/default.yaml` but someone duplicated this having `schedule/yast/sle/flows/default_x86_64.yaml` so you need to check the difference between both to use that common name.

**Pull request merged**
