### PR TITLE
Small improvements for MicroOS SelfInstall

### PR DESCRIPTION
**Pull request by Vogtinator**
See individual commits.

- Verification run: https://openqa.opensuse.org/tests/3586636

### CODE REVIEW

**Review by jlausuch — APPROVED** [review]

**Comment by jlausuch** [comment]
Could you please run also a VR for SLEMicro 5.5 SelfInstall test?

**Comment by Vogtinator** [comment]
> Could you please run also a VR for SLEMicro 5.5 SelfInstall test?

Doesn't that use the YAML schedule instead of `main_micro_alp.pm`?

**Comment by jlausuch** [comment]
> > Could you please run also a VR for SLEMicro 5.5 SelfInstall test?
> 
> Doesn't that use the YAML schedule instead of `main_micro_alp.pm`?

Nope, it uses same schedule, that was the idea of this file. Maybe there is some specific test using yaml... but in general, everything goes through the same schedule. e.g. https://openqa.suse.de/tests/12141821

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by Vogtinator** [comment]
> > > Could you please run also a VR for SLEMicro 5.5 SelfInstall test?
> > 
> > 
> > Doesn't that use the YAML schedule instead of `main_micro_alp.pm`?
> 
> Nope, it uses same schedule, that was the idea of this file. Maybe there is some specific test using yaml... but in general, everything goes through the same schedule. e.g. https://openqa.suse.de/tests/12141821

Ok, in that case I wonder why schedule/sle-micro/selfinstall.yaml still exists.

VR: http://10.168.4.192/tests/1337 (running, but schedule looks good)

**Comment by mloviska** [comment]
> > Ok, in that case I wonder why schedule/sle-micro/selfinstall.yaml still exists.
> 
> Looks like left-overs from old schedule... @mloviska do you remember?

oh, seems like!

**Pull request merged**
