### PR TITLE
Fix main.pm so it runs RAID0 when RAIDLEVEL is 0

### PR DESCRIPTION
**Pull request by sysrich**

### CODE REVIEW

**Comment by sysrich** [comment]
doesn't seem to actually work..get_var things RAIDLEVEL is not set when value = 0

**Comment by coolo** [comment]
but this seems to be a really, really old bug

**Comment by lnussel** [comment]
the fix is correct if we apply this:
https://github.com/os-autoinst/os-autoinst/pull/188

**Comment by coolo** [comment]
but we need the same in all branches, I will cherry pick

**Comment by coolo** [comment]
master and sle12 had it correct - but didn't work due to get_var. so all fine there

**Pull request merged**
