### PR TITLE
hpc: Make product test capable to run on same image twice

### PR DESCRIPTION
**Pull request by asmorodskyi**
1. renaming hpc_migration to hpc_product to remove confusion with migration process 
2. former version of the test expected to work with registered image only. This cause failures when re-run same test twice. New version of code will workaround this by detecting that SCC not happy with current image and re-register it again

### CODE REVIEW

**Comment by asmorodskyi** [comment]
prove run - http://kimball.arch.suse.de/tests/1789. 

Note : current version of script_output has a bug which will be fixed by https://github.com/os-autoinst/os-autoinst/pull/1030 but before this PR will get merged and deployed to osd no point to merge this one

**Comment by asmorodskyi** [comment]
Still waiting for https://github.com/os-autoinst/os-autoinst/pull/1030 to be deployed to osd , as far as I know there was no deploy since it was merged. Without this it won't fly

**Comment by okurz** [comment]
I see, sorry I have overlooked your comment explaining that

**Comment by asmorodskyi** [comment]
@okurz , osd updated and conflicts are solved , please take a look

**Pull request merged**
