### PR TITLE
Fix and stabilize RAID test with storage NG

### PR DESCRIPTION
**Pull request by rwx788**
Based on [PR#3666](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3666). 
Functionality was implemented. 

Please, merge [NEEDLES](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/529) and more [NEEDLES](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/530), includes needles from original PR by @DrMullings.
[Verification run SLE15](http://g226.suse.de/tests/2271).
[Verification run SLE12SP3](http://g226.suse.de/tests/2273)
Missing verification run on sle 12 sp3.

### CODE REVIEW

**Comment by okurz** [comment]
You managed in 219 steps a full raid configuration within less than 7 minutes. This is way better then in before. As soon as you proofed pre-storage-ng still running we should be ready to merge

**Comment by rwx788** [comment]
@SergioAtSUSE please, review

**Comment by okurz** [comment]
LGTM, @SergioAtSUSE can merge

**Comment by rwx788** [comment]
LGTMed by @SergioAtSUSE

**Comment by DimStar77** [comment]
As discussed on IRC: this breaks all TW Product and Staging tests for Raid

e.g. https://openqa.opensuse.org/tests/505640#step/partitioning_raid/1

**Comment by rwx788** [comment]
@DimStar77 the point here is that test isn't working fine also, so it's good that we've found it. Fix is progress.

**Pull request merged**
