### PR TITLE
Sle12sp5 guests enter LTSS

### PR DESCRIPTION
**Pull request by Julie-CAO**
Related ticket: https://progress.opensuse.org/issues/166187

Related PRs:
https://github.com/SUSE/qa-automation/pull/843
https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/212

Verification run: 
[uefi-gi-guest_sles12sp5-on-host_developing-kvm](https://10.145.10.207/tests/15755206)
[uefi-gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/15754988)
[uefi-gi-guest_sles12sp5-on-host_developing-xen](https://10.145.10.207/tests/15757184)   
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-xen](https://10.145.10.207/tests/15754985)
[prj4_guest_upgrade_sles12sp5_on_sles12sp5-kvm](https://10.145.10.207/tests/15756628)  
[gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/15754962)
[gi-guest_developing-on-host_sles12sp5-kvm](https://10.145.10.207/tests/15754958)   //non-autoyast installl
[gi-guest_sles12sp5-on-host_developing-xen](https://10.145.10.207/tests/15745442)
[prj2_host_upgrade_sles12sp5_to_developing_kvm](https://10.145.10.207/tests/15756778)

### CODE REVIEW

**Comment by Julie-CAO** [comment]
@alice-suse @guoxuguang @RoyCai7 @waynechen55 and others, welcome review!

**Comment by alice-suse** [comment]
Hi Julie,
It seems HOST autoyast update is missing?

**Comment by alice-suse** [comment]
> Hi Julie, It seems HOST autoyast update is missing?

Find it in job group yaml settings which enables ltss.

**Comment by guoxuguang** [comment]
LGTM

**Comment by alice-suse** [comment]
@Julie-CAO  I won't check VRs one by one. When they all finish, please do me a favor to drop a comment if all are good. Thanks.

**Comment by Julie-CAO** [comment]
> @Julie-CAO I won't check VRs one by one. When they all finish, please do me a favor to drop a comment if all are good. Thanks.

@alice-suse All runs finised. Please help merge. thanks.

**Pull request merged**
