### PR TITLE
Insert support for HPC system roles

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by asmorodskyi** [comment]
Related ticket - https://progress.opensuse.org/issues/35365
Needles : https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/830

**Comment by asmorodskyi** [comment]
http://kimball.arch.suse.de/tests/1218 - SYSTEM_ROLE=hpc-node
http://kimball.arch.suse.de/tests/1213 - SYSTEM_ROLE=hpc-server ( failing due to known bug ) 

hpc-dev on the way

**Comment by ldevulder** [comment]
LGTM, just one remark on the needles (see GitLab).

**Comment by asmorodskyi** [comment]
and last piece - http://kimball.arch.suse.de/tests/1223 - SYSTEM_ROLE=hpc-dev

**Comment by ldevulder** [comment]
Looks good, I think you can merge.

**Pull request merged**
