### PR TITLE
Bash autocompletion for btrfs

### PR DESCRIPTION
**Pull request by kravciak**
https://progress.opensuse.org/issues/11448

### CODE REVIEW

**Comment by okurz** [comment]
Do you have a link to a local verification run?

As a follow-up after this PR, do you want to try to extract common code from the both main.pm?

**Comment by kravciak** [comment]
Local runs:
TW: http://dhcp91.suse.cz/tests/1504
SLES: http://dhcp91.suse.cz/tests/1506

I noticed both main.pm could use some cleanup, but I want to finish some of my progress issues first

**Comment by DimStar77** [comment]
A quick check: it's even worse: minimalX installs don't have bash-completion installed - and thus the feature is not enabled... btrfs does not require the package - hence relying on it being there is an invalid test.

**Comment by okurz** [comment]
ok, good to know. So we understand the product better :-) So what can you recommend?

1. explicitly skip in staging and not TW? (does it make sense from product perspective to have this TW/Leap difference?)
2. dynamically detect if the corresponding package exists?
3. change package dependencies to install the btrfs bash completions if we have btrfs?

**Comment by DimStar77** [comment]
for 1): won't be sufficient, as there are also MinimalX tests in TW - they will suffer from the same issue
for 2): Sounds like an interesting idea - but is the package absence a fail/softfail/success?
for 3) Many packages split the -bash-completion stuff out by now and have that new subpackage require bash-completion as well as suplement bash-completion and the package bringing the binaries. Having a requires on bash-completiong from btrfs (unsplit) sounds wrong.

3 alone won't solve it - even when splitting the package, we will end up with other cases where bash-completion is missing

**Comment by kravciak** [comment]
Minimal-X tests work outside of stagins:
TW - http://dhcp91.suse.cz/tests/1507
42.2 - https://openqa.opensuse.org/tests/214436

**Comment by okurz** [comment]
@kravciak as staging is still ill-affected, could you please either remove it from staging or just successfully pass over the test module if the corresponding package can not be found? E.g.
if bash-completion not installed, set `$self->result('ok')` and `return 1` from the test module.

**Pull request merged**
