### PR TITLE
Fix addons_sle by only looking at the device

### PR DESCRIPTION
**Pull request by coolo**
We no longer have a long list of addons, but ADDONS=foo,bar expects
foo in ISO_1 and bar in ISO_2

### CODE REVIEW

**Comment by coolo** [comment]
the commit is a bit noisy as tidy decided to move all comments - but it's just whitespace

**Comment by dzedro** [comment]
does the sr$number make still sense ?
Now e.g. sr0 can be any add-on based on test if I understand the idea

**Comment by dzedro** [comment]
I mean the tag specific name

**Comment by coolo** [comment]
sr0 is always the product - and the ADDONS are in sr1, sr2, ... exactly as listed in ADDONS

**Comment by dzedro** [comment]
LGTM
I'm just getting crazy and write nonsense :)

**Pull request merged**
