### PR TITLE
wicked: add ifreload tests

### PR DESCRIPTION
**Pull request by asmorodskyi**
This patch bring coverage for functionality introduced in wicked 0.6.64
so prior this version this tests will fail

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@cfconrad  this is your code actually :) but please double check anyway

**Comment by asmorodskyi** [comment]
VR : http://autobot.qa.suse.de/tests/2022

**Comment by jlausuch** [comment]
I guess the reason why executing a bash script instead of writing the code in perl logic is due to high amount of bash commands, am I right? How have you come up with those bash scripts? Are they taken from developers?

Are those 4 new test cases any of the missing in the [startstop legacy test suite](https://progress.opensuse.org/issues/42506)?

**Comment by asmorodskyi** [comment]
> I guess the reason why executing a bash script instead of writing the code in perl logic is due to high amount of bash commands, am I right? How have you come up with those bash scripts? Are they taken from developers?

scripts are from developers ( Marius wrote them ) and this is actually main reason why it is in bash ( obviously he don't want to mess up with perl test code ) 

> 
> Are those 4 new test cases any of the missing in the [startstop legacy test suite](https://progress.opensuse.org/issues/42506)?


none of this test cases presented in legacy test suite because they covering functionality introduced in 0.6.64 ( latest for today ) version of wicked

**Comment by mloviska** [comment]
Off topic (sorry!)

Martin has created a nice shell runner for openQA. I would like to share it with you as there so many scripts, thus it might be useful in the future.

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9219

**Comment by asmorodskyi** [comment]
> Off topic (sorry!)
> 
> Martin has created a nice shell runner for openQA. I would like to share it with you as there so many scripts, thus it might be useful in the future.
> 
> #9219

thanks for the hint ! I really like this idea ! and I think it will be right thing to move this scripts to use this shell runner. On the other side I notice that to use this approach you need to modify existing bash scripts to met some requirements while this PR already contain fully workable approach already used by wicked developers for some time in their internal openQA instance . So I would prefer to merge this PR as it is and come up with another one to refactor /test approach which you suggesting

**Comment by mloviska** [comment]
> 
> thanks for the hint ! I really like this idea ! and I think it will be right thing to move this scripts to use this shell runner. On the other side I notice that to use this approach you need to modify existing bash scripts to met some requirements while this PR already contain fully workable approach already used by wicked developers for some time in their internal openQA instance . So I would prefer to merge this PR as it is and come up with another one to refactor /test approach which you suggesting

I haven't checked the details, yet. Thanks for going deeper! Yup, it was just an idea whether we can use it. Eventually, it might not be so much helpful for us. Let's see in the future :)

**Review by jlausuch — APPROVED** [review]

**Comment by cfconrad** [comment]
@asmorodskyi thx for moving the tests to osd. 

Regarding shell runner, I don't see the benefit of converting the scripts, I would avoid dependencies when just running _one_ script. The cool thing is, that they split stdout and stderr, but if this is really needed, we can add a redirect in our version too.

**Pull request merged**
