### PR TITLE
Stop package-kit before zypper calls

### PR DESCRIPTION
**Pull request by rwx788**
See [poo#39539](https://progress.opensuse.org/issues/39539).

- [Verification run](http://g226.suse.de/tests/2210)

### CODE REVIEW

**Comment by dzedro** [comment]
could mostly work, but now we stop/mask packagekit here and also in consoletes_setup anslo consoletest summary is not updated
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/console/consoletest_setup.pm#L39 ?

**Comment by rwx788** [comment]
@good point, will update consoletest_setup summary in this PR

**Comment by dzedro** [comment]
@rwx788 not sure what you mean with revert consoletest_finish, but if in system_prepare are permanent changes then it should be scheduled after consoletest_setup after packagekit is masked, of course if there is nothing else colliding with this solution

**Comment by rwx788** [comment]
@dzedro so idea of original PR is that we do some actions which are then already in qcow and we don't have to repeat them when we boot into the image. So reordering test modules won't help here. Moving it system_prepare will work, but in qcow we don't won't to see packagekit service masked. So I see your point, but I consider this solution least harmful as of now. Of course we also can put all zypper calls to consoletest_setup too, but curl and tar are essential and will be required everywhere...

**Pull request merged**
