### PR TITLE
Fix tag name for PolicyKit-authenticate

### PR DESCRIPTION
**Pull request by DimStar77**
Fixup previously merged commit

VR https://openqa.opensuse.org/tests/1271685 (pending)

### CODE REVIEW

**Comment by DimStar77** [comment]
@okurz

This should be the fix for #10286

**Comment by okurz** [comment]
The differing casing is unfortunate. There is another "Policykit-..." needle as well with small "k". Your VR seems to still on the old tag name

**Comment by DimStar77** [comment]
> The differing casing is unfortunate. There is another "Policykit-..." needle as well with small "k". Your VR seems to still on the old tag name

The clue is that the VR that was my original one as also the one running by @dzedro were done with PolicyKit - before the rewrite to your propose variant 3 when the case got switched (as I only appendedto the existing name)

The needle used in that VR that succeeded (old code variant) was https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/da8e4685658aa34243fe809ca3762a94e9566ea1#diff-f70e981b847f97baaccd5432e83dffd7R31

Which is why, besides actually fixing the codeto match the right needle, I decided to also go with the case style that was used then to do the testing

The Logfile fromhttps://openqa.suse.de/tests/4248544#downloads (SLE VR) contains:
```
[2020-05-16T03:38:42.814 CEST] [debug] <<< testapi::assert_screen(mustmatch="PolicyKit-authenticate", timeout=30)
[2020-05-16T03:38:42.889 CEST] [debug] >>> testapi::_handle_found_needle: found Policykit-20200130, similarity 1.00 @ 639/511
```

e.g, same casing as used in this PR

**Comment by dzedro** [comment]
I noticed the difference, SLE needles have both tags I will update them with whatever tag it ends :wink:

**Comment by DimStar77** [comment]
FTR - https://openqa.opensuse.org/tests/1271685#step/gnome_music/15 passed (with this VR - needle from the previous PR has been used)

**Pull request merged**
