### PR TITLE
Improve qa-automation, support QA_TESTSUITE for 15sp1

### PR DESCRIPTION
**Pull request by okurz**
Verification runs:

* Example of a failing job, showing the logs on fails: https://openqa.suse.de/t2492919
* Passing job: https://openqa.suse.de/t2492921

### CODE REVIEW

**Comment by okurz** [comment]
For verification:

```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6879 https://openqa.suse.de/tests/2492722
```

Created job #2492919: sle-12-SP4-Server-DVD-Updates-x86_64-Build20190224-1-mau-qa_userspace_apparmor@64bit -> https://openqa.suse.de/t2492919

**Comment by okurz** [comment]
@czerw @mimi1vx maybe?

**Comment by czerw** [comment]
Seems like fails https://openqa.suse.de/tests/2515296#step/kernel_multipath/70  and https://openqa.suse.de/tests/2515318#step/kernel_kexec/70 started just after this PR was merged.

```
# Test died: command '/usr/share/qa/qaset/bin/junit_xml_gen.py -n 'regression' -d -o /tmp/junit.xml /var/log/qaset' failed at /var/lib/openqa/cache/openqa.suse.de/tests/sle/tests/qa_automation/qa_run.pm line 146.
```
Do you you have overview how similar tests run on 15SP1?(was away few days, not sure if there is poo for it or not).

**Comment by okurz** [comment]
@czerw I understood now that kernel_multipath and kernel_kexec are two special candidates.

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6954 should handle that. I will test there.

**Pull request merged**
