### PR TITLE
Move ibtests barrier creation to a separate test module

### PR DESCRIPTION
**Pull request by frankenmichl**
Move ibtests barrier creation to a separate test module in preparation to move the ibtests to a declarative schedule

### CODE REVIEW

**Comment by frankenmichl** [comment]
Right now, a job is running. I think I should take care of this as soon as we have merged this, so we will not run into conflicts here.

**Comment by jlausuch** [comment]
Travis complains because ibtests_barriers.pm doesn´t exist yet in master. So, fastest solution would be to split this PR into 2. 1) Create ibtests_barriers.pm and merge 2) hold this PR and rebase after merge 1)

**Comment by frankenmichl** [comment]
While I agree with you, this kind of PR is stereotypical for 'moving stuff from main.pm to a declarative schedule' - let me think about how to make travis happy without splitting the PR.

**Comment by jlausuch** [comment]
> While I agree with you, this kind of PR is stereotypical for 'moving stuff from main.pm to a declarative schedule' - let me think about how to make travis happy without splitting the PR.

Yeah, Travis logic should be smarter and take into account new files in the commit.

**Pull request merged**
