### PR TITLE
add test control for evince and gedit

### PR DESCRIPTION
**Pull request by mitiao**

### CODE REVIEW

**Comment by nilxam** [comment]
just a remind: I assume openqa.s.d already enabled regression test, if so, please make sure new os-autoinst is deployed for mouse_tclick()

**Comment by mitiao** [comment]
currently regression tests are not run on openqa.s.d
anyway be sure that new os-autoinst is deployed for mouse_tclick() is right. :)

**Comment by coolo** [comment]
they fail - but run: https://openqa.suse.de/tests/110840

**Comment by mitiao** [comment]
i see, the run didn't load load_boot_tests first. will add it to main.pm

**Comment by mitiao** [comment]
combined into 1 commit

**Comment by coolo** [comment]
I wanted to merge it, but it's a bit beyond me - perhaps you guys should create merge points in the code :)

**Comment by mitiao** [comment]
Done

**Comment by nilxam** [comment]
hmm...weird

**Pull request merged**
