### PR TITLE
Renew expired certificates for samba tests

### PR DESCRIPTION
**Pull request by JRivrain**
Those certificates need to be replaced, as they've expired.

- Related ticket: https://progress.opensuse.org/issues/61780#note-15

### CODE REVIEW

**Comment by jknphy** [comment]
May I ask you to describe somewhere how you generated? it would be really useful for next time.

**Comment by JRivrain** [comment]
> May I ask you to describe somewhere how you generated? it would be really useful for next time.

Normally there should not be a next time before ten years, but okay, who knows :)

**Comment by b10n1k** [comment]
> > May I ask you to describe somewhere how you generated? it would be really useful for next time.
> 
> Normally there should not be a next time before ten years, but okay, who knows :)

Actually we cant validate the PR without knowing how you end up with it. Also the files have different postfix. `pem` versus `pem.p12`. Why is that?

**Comment by JRivrain** [comment]
> > > May I ask you to describe somewhere how you generated? it would be really useful for next time.
> > 
> > 
> > Normally there should not be a next time before ten years, but okay, who knows :)
> 
> Actually we cant validate the PR without knowing how you end up with it. Also the files have different postfix. `pem` versus `pem.p12`. Why is that?

That test is broken for multiple reasons, one is this expired certificate, so I cannot present a working VR. This being said, you have all the needed info in the ticket, but you will need to do quite a lot of reading... or you can just trust me.
Regarding the names of the files, I kept the original names. I don't know why they were named this way years ago, but I don't see anything wrong with it (and there is no `.pem.p12` file actually)
We need this change before we can fix anything else in those samba tests.

**Comment by b10n1k** [comment]
> > > > May I ask you to describe somewhere how you generated? it would be really useful for next time.
> > > 
> > > 
> > > Normally there should not be a next time before ten years, but okay, who knows :)
> > 
> > 
> > Actually we cant validate the PR without knowing how you end up with it. Also the files have different postfix. `pem` versus `pem.p12`. Why is that?
> 
> That test is broken for multiple reasons, one is this expired certificate, so I cannot present a working VR. This being said, you have all the needed info in the ticket, but you will need to do quite a lot of reading... or you can just trust me.
> Regarding the names of the files, I kept the original names. I don't know why they were named this way years ago, but I don't see anything wrong with it (and there is no `.pem.p12` file actually)
> We need this change before we can fix anything else in those samba tests.

to be honest the `data/console/samba_server_cert.p12` looks like the Private RSA Key. or the signature. I dont know how is it used from the module. But i dont see why it should be removed. it might be also just replaced. 
Having said that, i have only to trust you if you say that this is not needed at all, as i dont know what is it its play. i can trust you about pem totally, but i would like only to know how it was created to figure out the used encoding(AES-128,des,etc) for it. i just think it would be helpful to know.

**Comment by JRivrain** [comment]
> > > > > May I ask you to describe somewhere how you generated? it would be really useful for next time.
> > > > 
> > > > 
> > > > Normally there should not be a next time before ten years, but okay, who knows :)
> > > 
> > > 
> > > Actually we cant validate the PR without knowing how you end up with it. Also the files have different postfix. `pem` versus `pem.p12`. Why is that?
> > 
> > 
> > That test is broken for multiple reasons, one is this expired certificate, so I cannot present a working VR. This being said, you have all the needed info in the ticket, but you will need to do quite a lot of reading... or you can just trust me.
> > Regarding the names of the files, I kept the original names. I don't know why they were named this way years ago, but I don't see anything wrong with it (and there is no `.pem.p12` file actually)
> > We need this change before we can fix anything else in those samba tests.
> 
> to be honest the `data/console/samba_server_cert.p12` looks like the Private RSA Key. or the signature. I dont know how is it used from the module. But i dont see why it should be removed. it might be also just replaced.
> Having said that, i have only to trust you if you say that this is not needed at all, as i dont know what is it its play. i can trust you about pem totally, but i would like only to know how it was created to figure out the used encoding(AES-128,des,etc) for it. i just think it would be helpful to know.

the p12 file is not removed, just shorter. feel free to inspect it. it is a p12 file see here https://en.wikipedia.org/wiki/PKCS_12

**Comment by jknphy** [comment]
Feel free to write some step how you made it for example in the progress ticket, I guess it would be interesting for the team. We trust you that we are in the right direction. Thanks for the investigation.

**Pull request merged**
