### PR TITLE
Support MicroOS-SelfInstall images

### PR DESCRIPTION
**Pull request by Vogtinator**
Needs just some small changes.

- Needles: Already created on o3
- Verification run: https://openqa.opensuse.org/tests/3584904

VR is still running but already past the critical installation parts.

### CODE REVIEW

**Review by jlausuch — APPROVED** [review]
Nice!

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by mloviska** [comment]
I think we are ejecting the cd too late https://openqa.suse.de/tests/12203565#step/selfinstall/7

**Comment by Vogtinator** [comment]
> I think we are ejecting the cd too late https://openqa.suse.de/tests/12203565#step/selfinstall/7

I'm surprised that the "Install" option is the selected one and there's no automatic boot. On MicroOS this would've booted the installed system after 10s. Do you know whether this is intentional?

I'll restore the old place for `eject_cd` in the SLEM case.

**Comment by Vogtinator** [comment]
> I'll restore the old place for `eject_cd` in the SLEM case.

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17814

**Comment by mloviska** [comment]
> > I think we are ejecting the cd too late https://openqa.suse.de/tests/12203565#step/selfinstall/7
> 
> I'm surprised that the "Install" option is the selected one and there's no automatic boot. On MicroOS this would've booted the installed system after 10s. Do you know whether this is intentional?
> 
Yeah, this is super annoying, Idk whether this can be anyhow fixed in the kiwi, if yes, I guess Jiri was not really aware of it as his suggestion was to select the boot drive manually.

> I'll restore the old place for `eject_cd` in the SLEM case.

**Pull request merged**
