### PR TITLE
Add schedules for SLES+HA installation scenarios

### PR DESCRIPTION
**Pull request by alvarocarvajald**
Add YaML schedules for the SLES+HA installation scenarios currently defined in openqa.suse.de.

This is intended to work with a job group configuration similar to this:

```
...
    sle-15-SP3-Full-x86_64:
    - textmode+skip_registration_ha:
        testsuite: null
        settings: &textmode_install_full_medium
          ADDONS: ha
          HDDMODEL: scsi-hd
          SCC_REGISTER: never
          SYSTEM_ROLE: textmode
          VIDEOMODE: text
          YAML_SCHEDULE: schedule/ha/bv/sles_ha_installation.yaml
    - textmode+skip_registration_minimal_base+ha:
        testsuite: null
        settings:
          <<: *textmode_install_full_medium
          SYSTEM_ROLE: minimal
    sle-15-SP3-Online-x86_64:
    - ha_textmode_extended:
        testsuite: null
        settings: &ha_textmode_extended
          VIDEOMODE: text
          YAML_SCHEDULE: schedule/ha/bv/ha_textmode_extended.yaml
    - textmode_ha:
        testsuite: null
        settings: &textmode_install_online_medium
          CHECK_ISO_MAXSIZE: '1'
          SCC_REGISTER: installation
          SYSTEM_ROLE: textmode
          VIDEOMODE: text
          YAML_SCHEDULE: schedule/ha/bv/sles_ha_installation.yaml
    - textmode_minimal_base+ha:
        testsuite: null
        settings:
          <<: *textmode_install_online_medium
          SYSTEM_ROLE: minimal
    - create_hdd_ha_textmode:
        testsuite: null
        settings: &create_hdd_settings
          <<: *textmode_install_online_medium
          CREATE_HDD: '1'
          HDDMODEL: scsi-hd
          PUBLISH_HDD_1: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV.qcow2'
          SYSTEM_ROLE: default
...
    sle-15-SP3-Full-aarch64:
    - textmode+skip_registration_ha:
        testsuite: null
        settings:
          <<: *textmode_install_full_medium
    - textmode+skip_registration_minimal_base+ha:
        testsuite: null
        settings:
          <<: *textmode_install_full_medium
          SYSTEM_ROLE: minimal
    sle-15-SP3-Online-aarch64:
    - ha_textmode_extended:
        testsuite: null
        settings:
          <<: *ha_textmode_extended
    - textmode_ha:
        testsuite: null
        settings:
          <<: *textmode_install_online_medium
    - textmode_minimal_base+ha:
        testsuite: null
        settings:
          <<: *textmode_install_online_medium
          SYSTEM_ROLE: minimal
    - create_hdd_ha_textmode:
        testsuite: null
        settings:
          <<: *create_hdd_settings
          PUBLISH_PFLASH_VARS: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV-uefi-vars.qcow2'
...
```

- Job group configuration Merge Request: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/259
- Related ticket: https://jira.suse.com/browse/TEAM-3582
- Needles: N/A
- Verification runs:

create_hdd_ha_textmode (Online Medium, SCC Registration, HA system role): [aarch64](http://mango.qa.suse.de/tests/3763), [x86_64](http://mango.qa.suse.de/tests/3752)
Full Medium, Skip Registration, textmode system role: [aarch64](http://mango.qa.suse.de/tests/3756), [x86_64](http://mango.qa.suse.de/tests/3750)
Full Medium, Skip Registration, minimal system role: [aarch64](http://mango.qa.suse.de/tests/3757), [x86_64](http://mango.qa.suse.de/tests/3751)
Online Medium, SCC Registration, textmode system role: [aarch64](http://mango.qa.suse.de/tests/3762), [x86_64](http://mango.qa.suse.de/tests/3754)
Online Medium, SCC Registration, minimal system role: [aarch64](http://mango.qa.suse.de/tests/3761), [x86_64](http://mango.qa.suse.de/tests/3755)
Online Medium, SCC Registration, HA system role, extended checks: [aarch64](http://mango.qa.suse.de/tests/3759), [x86_64](http://mango.qa.suse.de/tests/3753)

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by juadk — APPROVED** [review]
LGTM, Will you include s390x and ppc64le later? maybe in another PR?
Because I can see conditional schedule on s390x whereas it misses `bootloader_zkvm`.

**Comment by alvarocarvajald** [comment]
> LGTM, just one small comment, will you include s390x and ppc64le later? maybe in another PR?
> Because I can see conditional schedule on s390x whereas it misses `bootloader_zkvm`.

`bootloader_start` should work for all architectures, but I did forget to include ppc64le and s390x in the MR so we can trigger tests on all four architectures and confirm this is working as is. I will add this tomorrow morning to the MR.

**Comment by alvarocarvajald** [comment]
Removing WIP tag. The linked MR now includes tests for all architectures.

**Pull request merged**
