### PR TITLE
Create yaml scheduler for qam-mininal(+sle15) tests

### PR DESCRIPTION
**Pull request by dzedro**
Publish updated image, image will be used by grub2 minimal tests

- Fail: https://openqa.suse.de/tests/3965495 created image is not updated
- Verification run:

https://openqa.suse.de/tests/3984796 12sp5 x86_64
https://openqa.suse.de/tests/3984797 12sp5 s390x
https://openqa.suse.de/tests/3984798 12sp5 ppc64le
https://openqa.suse.de/tests/3984799 12sp5 aarch64

https://openqa.suse.de/tests/3984800 15 x86_64
https://openqa.suse.de/tests/3984801 15 s390x
https://openqa.suse.de/tests/3984802 15 ppc64le
https://openqa.suse.de/tests/3984803 15 aarch64

### CODE REVIEW

**Comment by okurz** [comment]
s/mininam/minimal/ ?

**Comment by dzedro** [comment]
merging when verification tests pass

**Comment by okurz** [comment]
No, minimal, not mininal :D

**Comment by dzedro** [comment]
> No, minimal, not mininal :D

fixed

**Pull request merged**
