### PR TITLE
Fix sporadic krunner slowness in x11_start_program

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@asdil12

**Comment by asdil12** [comment]
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/359

**Comment by asdil12** [comment]
Seems to work: http://artemis.suse.de/tests/237

**Comment by asdil12** [comment]
But I don't have a verification run that was slow enough to trigger the `desktop-runner-plasma-suggestions` needle.

**Comment by asdil12** [comment]
@okurz I think, we can remove the `[WIP]`

**Pull request merged**
