### PR TITLE
Split extratests, update testsuite requiring phub

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://progress.opensuse.org/issues/88477
- Verification run: 
https://openqa.suse.de/tests/5471804 phub 15-SP3 x86_64 https://bugzilla.suse.com/show_bug.cgi?id=1180120
https://openqa.suse.de/tests/5471805 phub 15-SP3 s390x https://bugzilla.suse.com/show_bug.cgi?id=1180120
https://openqa.suse.de/tests/5471806 phub 15-SP3 ppc64le https://bugzilla.suse.com/show_bug.cgi?id=1180120
https://openqa.suse.de/tests/5471807 phub 15-SP3 aarch64 https://bugzilla.suse.com/show_bug.cgi?id=1180120
https://openqa.suse.de/tests/5472283 extra_tests_textmode 15-SP3 x86_64
https://openqa.suse.de/tests/5472284 extra_tests_textmode 15-SP3 s390x
https://openqa.suse.de/tests/5472285 extra_tests_textmode 15-SP3 ppc64le
https://openqa.suse.de/tests/5472286 extra_tests_textmode 15-SP3 aarch64
[QEM extratests[1,2] all versions](https://openqa.suse.de/tests/overview?groupid=293&flavor=Server-DVD-Incidents&build=12sp2&build=12sp3&build=12sp4&build=12sp5&build=15&build=15sp1&build=15sp1&build=15sp2)

### CODE REVIEW

**Comment by michaelgrifalconi** [comment]
Hey, thanks for working on this! Looking forward for a faster mau-extratest run :)

I would have a few quick questions:
- The poo linked is about a gdb failure. Is there an issue that is tracking this mau-extratest big refactoring?
- Is there some logic on why something is in mau-1 or mau-2?
- Considering that they both take a similar amount of time, how do we handle new tests? Do we add only on mau-2 until a threshold? Do we start with mau-3? Does it make sense to document some rule to avoid the need of another split in future?

**Comment by dzedro** [comment]
I want to keep the poo# open until are aarch64 extratests improved/fixed. This split is just one step to make it better/faster with extratests. It would have to be done soon or later.
There is no logic, I just split the tests into half and moved few tests up and down to have approx. same run duration and count of tests. Idea of better naming of groups or way how to split it is welcome.
New tests add/move into group to keep the duration of 1 .. 9 .. all groups under 1 hour run time (ignoring aarch64 as it's slower).
I was thinking about some better way of splitting it or naming the groups, like some network, base or whatever. But there are always some exceptions and overlaps and I just decided to split it just to keep the extratests fast.

**Review by michaelgrifalconi — APPROVED** [review]

**Comment by okurz** [comment]
"testsure" is likely a typo. Should it be "testsuite"?

**Comment by SergioAtSUSE** [comment]
@dzedro, could you take a look? I think this failure is caused by this PR: https://openqa.suse.de/tests/5485463#step/libvorbis/3

**Comment by dzedro** [comment]
> @dzedro, could you take a look? I think this failure is caused by this PR: https://openqa.suse.de/tests/5485463#step/libvorbis/3

Sorry, thought it's part of extra_tests_textmode and missed it. Created PR to fix it.

**Pull request merged**
