### PR TITLE
Check related hmac packages when FIPS installation

### PR DESCRIPTION
**Pull request by wangqianzou**
Progress issue: https://progress.opensuse.org/issues/110707
Check if related hmac packages are installed when installing FIPS.

- Related ticket: https://progress.opensuse.org/issues/110707
- Needles:  None
- Verification run
   -Env mode test:  https://openqa.suse.de/tests/8702841#step/fips_setup/76
   -Kernel mode test: http://openqa.suse.de/tests/8702834#step/fips_setup/73

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
lgtm

**Comment by rfan1** [comment]
Check if related hmac packages is installed when installing FIPS.

typo?
Suggest changes:
Check if hmac related packages are installed in FIPS mode

**Comment by wangqianzou** [comment]
> Check if related hmac packages is installed when installing FIPS.
> 
> typo? Suggest changes: Check if hmac related packages are installed in FIPS mode

Corrected it

**Review by rfan1 — APPROVED** [review]

**Review by Amrysliu — APPROVED** [review]

**Comment by michaelgrifalconi** [comment]
https://progress.opensuse.org/issues/110896

**Pull request merged**
