### PR TITLE
pynfs: Show failed and skipped tests

### PR DESCRIPTION
**Pull request by pevik**
Generate list of failed and skipped tests at the end of testing from test output. This helps easier to track failed and skipped ests.

NOTE: we don't print passed tests, because total number is really high (currently 677).

Use JSON format for results for easier parsing. This requires pynfs with commits from May 2021:
* 92c13d7 ("server: Allow to print JSON format")
* 107c1e5 ("server: Add test code to JSON and XML output")

Signed-off-by: Petr Vorel <pvorel@suse.cz>

Verification run:
- single failure: http://quasar.suse.cz/tests/7811#step/LOCK24/2 http://quasar.suse.cz/tests/7812#step/LOCK24/2
- more failures (older release): http://quasar.suse.cz/tests/7851
- no failures: http://quasar.suse.cz/tests/7814 http://quasar.suse.cz/tests/7813

NOTE: I also had version which showed also skipped: http://quasar.suse.cz/tests/7793, but that's IMHO useless (there is a list just before testing).

**UPDATE**: not merging, because there is alternative implementation from @lansuse: **https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13801**

### CODE REVIEW

**Comment by czerw** [comment]
@lansuse please check as well

**Review by SeroSun — APPROVED** [review]
LGTM, very pretty result!

**Comment by pevik** [comment]
@czerw @SeroSun @lansuse @acerv FYI Lan did another implementation which uses XUnit http://10.67.133.102/tests/474. He will open PR and we can decide which one to merge.

**Comment by lansuse** [comment]
LGTM, This is the result what I want

**Comment by pevik** [comment]
> LGTM, This is the result what I want

I guess we'll have to decide whether accept this PR or yours (https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13801). Because although I could rewrite this to use XML instead of JSON I'm not sure if we can have both "virtual modules" implementation (this PR) and xunit (your PR). BTW LTP tests have virtual modules and "External results" https://openqa.suse.de/tests/7758716#external, not sure how they're implemented, but IIMHO not via xunit.

**Comment by SeroSun** [comment]
@pevik Long share his opinion with me, we both like your PR, and it has more clear results to show which sub-tests fail on the build result page. Feel free to merge it.

**Review by czerw — APPROVED** [review]

**Pull request merged**
