### PR TITLE
Containers: skip UBI images for Public Cloud ARM images

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/94768

### CODE REVIEW

**Comment by jlausuch** [comment]
VR (in progress): https://openqa.suse.de/tests/6344354

**Review by b10n1k — APPROVED** [review]
+1

**Review by pdostal — APPROVED** [review]

**Review by grisu48 — APPROVED** [review]
LGTM

**Comment by jlausuch** [comment]
Finally VR executed and green.

**Pull request merged**
