### PR TITLE
[WIP][DISCUSSION] Refactor containers code

### PR DESCRIPTION
**Pull request by asmorodskyi**
Up to now 0 VRs was done , so code in raw state and probably still need a lot of fixes . Obviously I don't plan to merge it before **all** possible use cases will be verified ( osd and o3 ) . For now I open PR to get feedback if there is overall disagreement with direction which I choose. 
At some extent suggested changes may look like useless juggling with moving entities from one place to another . Keep in mind that this is just preparation step for bigger changes which are not doable in one shot. Final goal to ease maintenance and extensibility  of containers code

### CODE REVIEW

**Comment by Vogtinator** [comment]
Cleanup is definitely needed, but I don't quite see the advantage of passing `$runtime` as object around. Those only work with runtimes which are compatible with the docker CLI syntax.There's not really much value in abstracting that anyway, as it is very leaky and many places have to use `$runtime->engine` directly.

Apparently that got introduced in some older PRs I wasn't involved in, but `_rt_assert_script_run` should be renamed before it gains more widespread use IMO.

**Comment by asmorodskyi** [comment]
> Those only work with runtimes which are compatible with the docker CLI syntax.

majority of changes which I did look like this : 

```
-        assert_script_run("$runtime container create --name 'testing' '$image' /bin/sh -c '$smoketest'");
-        assert_script_run("$runtime container start 'testing'");
-        assert_script_run("$runtime wait 'testing'", 90);
-        assert_script_run("$runtime container logs 'testing' | tee '$logfile'");
-        assert_script_run("$runtime container rm 'testing'");
+        $runtime->_rt_assert_script_run("container create --name 'testing' '$image' /bin/sh -c '$smoketest'");
+       $runtime->_rt_assert_script_run("container start 'testing'");
+       $runtime->_rt_assert_script_run("wait 'testing'", timeout => 90);
+        $runtime->_rt_assert_script_run("container logs 'testing' | tee '$logfile'");
+       $runtime->_rt_assert_script_run("container rm 'testing'");
```
and I would say this code is tied to docker-compatible CLI syntax even before my change 



> There's not really much value in abstracting that anyway, as it is very leaky and many places have to use `$runtime->engine` directly.

abstracting this into object open opportunities to remove a lot of boilerplate code which we repeating with tiny differences through container tests. All this will come in next PRs if this one will be accepted and merged. It was unreal to put everything into single PR . So yes currently it looks like jumping from one approach to another without real value but this value will come later. And yes currently it looks leaky but I am sure that I will be able solve **most** of this leaks in next PRs and some which will survive will be "the price "   :)



> Apparently that got introduced in some older PRs I wasn't involved in, but `_rt_assert_script_run` should be renamed before it gains more widespread use IMO.

agree and open for suggestions which name will suites better

**Comment by Vogtinator** [comment]
> > Those only work with runtimes which are compatible with the docker CLI syntax.
> 
> majority of changes which I did look like this :
> 
> ```
> -        assert_script_run("$runtime container create --name 'testing' '$image' /bin/sh -c '$smoketest'");
> -        assert_script_run("$runtime container start 'testing'");
> -        assert_script_run("$runtime wait 'testing'", 90);
> -        assert_script_run("$runtime container logs 'testing' | tee '$logfile'");
> -        assert_script_run("$runtime container rm 'testing'");
> +        $runtime->_rt_assert_script_run("container create --name 'testing' '$image' /bin/sh -c '$smoketest'");
> +       $runtime->_rt_assert_script_run("container start 'testing'");
> +       $runtime->_rt_assert_script_run("wait 'testing'", timeout => 90);
> +        $runtime->_rt_assert_script_run("container logs 'testing' | tee '$logfile'");
> +       $runtime->_rt_assert_script_run("container rm 'testing'");
> ```
> 
> and I would say this code is tied to docker-compatible CLI syntax even before my change

Yes. There's nothing wrong with the docker CLI syntax being needed here (and there's no way around that, other than more unneeded abstractions).

> > There's not really much value in abstracting that anyway, as it is very leaky and many places have to use `$runtime->engine` directly.
> 
> abstracting this into object open opportunities to remove a lot of boilerplate code which we repeating with tiny differences through container tests. All this will come in next PRs if this one will be accepted and merged. It was unreal to put everything into single PR . So yes currently it looks like jumping from one approach to another without real value but this value will come later. And yes currently it looks leaky but I am sure that I will be able solve **most** of this leaks in next PRs and some which will survive will be "the price " :)

What I mean is that abstracting something which doesn't need to be abstracted just makes it harder to read:

```
assert_script_run("$runtime wait 'testing'", 90);
$runtime->_rt_assert_script_run("container start 'testing'");
```

While both have identical behaviour, the former:
- Doesn't need a special method
- Is shorter
- Is recognizable by every openQA test developer already, without having looked at the container lib

So unless there's some need for this abstraction, I don't see much value here. Maybe you're planning to use it for something specific? If so, please outline that in the description.

> > Apparently that got introduced in some older PRs I wasn't involved in, but `_rt_assert_script_run` should be renamed before it gains more widespread use IMO.
> 
> agree and open for suggestions which name will suites better

Maybe `$container_rt->assert_script_run`?

**Comment by asmorodskyi** [comment]
> So unless there's some need for this abstraction, I don't see much value here. Maybe you're planning to use it for something specific? If so, please outline that in the description.

well like I said this abstraction is just first step and next step is not super clear yet I need to play with the code to see how to do it better , but my ideas is around to abstract things even more , move more logic within this runtime object . Get rid of majority of `$runtime->_rt_assert_script_run("container start 'testing'");` and replace it with something like `$runtime->container("start 'testing'");` maybe even shrink some repeating patterns where we doing some "1. build  container, 2. run the command 3. check output" into something like `$runtime->check_image()` but there nothing certain yet and it is hard to come up with something from the current state of the master ...

> Maybe `$container_rt->assert_script_run`?

fine for me , but I apply this suggestion after/if  we will find common ground about overall approach :)

**Comment by Vogtinator** [comment]
Some more detailed plan would help, currently there's not much we could give our opinion on.

It does sound a bit like the next PR would replace everything this PR did again, with some other function calls...

**Comment by asmorodskyi** [comment]
> Some more detailed plan would help, currently there's not much we could give our opinion on.

I already gave you very brief description of my ideas , if you want we can meet and have more extended live chat where I will try to explain and prove my ideas . Other than that only thing which comes to my mind how "to show" it to you is actually provide a patch where everything is done, but this is what I am trying to avoid , because I am trying to break into pieces ...


> It does sound a bit like the next PR would replace everything this PR did again, with some other function calls...

disagree . this PR provide a common base after it got merged we would have infrastructure setup done - in all relevant places we creating expected runtime objects and passing them in all places where it is needed . I will not touch this part in next PR(s) but yes I will need to replace all (almost)  `_rt_assert_script_run` with some "other function calls" but this is the price which we paying to have ability to do this in several stages .

**Review by pdostal — APPROVED** [review]
I like it! It loks very universal. Just please @asmorodskyi let us know when ready for verification runs.

**Comment by pdostal** [comment]
> Would this actually make sense? And what would we gain? Maybe it is better to write test-modules for that specific runtimes, to have them separated. (Thinking loud)

But our routines are runtime agnostic and you pass the routine to the as the first argument.

**Comment by asmorodskyi** [comment]
> This is just pseudo code, I don't even know if CONTAINER_RUNTIME exists

> Would this actually make sense? And what would we gain? Maybe it is better to write test-modules for that specific runtimes, to have them separated. (Thinking loud)


this was my initial idea , fully agree with you here ( I even gave exactly same name to a variable :) )  . Unfortunately it is not possible :( To achieve this we need to have separate job for each runtime, but currently we run all things together in one shot ( docker , podman , buildah etc. ) .
Another option will be to introduce new feature in openQA allowing to define variable with module scope :)

**Comment by cfconrad** [comment]
> @cfconrad But our routines are runtime agnostic and you pass the routine to the as the first argument.

@pdostal I see and I think I read that somewhere, that podman is cli compatible with docker. But what about the others?
If they all CLI compatible and there are no special cases instead of replacing the executable. Then I also don't see a need of abstraction!

> Another option will be to introduce new feature in openQA allowing to define variable with module scope :)

What about arguments to `run()` ?

**Comment by pdostal** [comment]
> @pdostal I see and I think I read that somewhere, that podman is cli compatible with docker. But what about the others?
> If they all CLI compatible and there are no special cases instead of replacing the executable. Then I also don't see a need of abstraction!

@cfconrad no, podman is not fully cli compatible with docker but partially.

**Comment by asmorodskyi** [comment]
1. At current stage I didn't get much of positive feedback . 
2. I did some VRs which showed me that there is still a lot of work to do. 

Summing up this 2 facts I must close this PR to not waste even more time on something which will be thrown anyway.   I will try to come up with smaller PR with some things from this big one which I still think are valid beside idea of moving to "runtime object "  .
@b10n1k  , @Vogtinator  - I think we need to give clear **YES/NO** answer on question - "Do we need runtime object abstraction or not ? ". If answer is NO I would suggest open another PR which will delete https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/containers/runtime.pm and remove usage of it. I can not find stronger arguments why we need it , but I am 100% that worst thing ever is to have it only for part of the code ...

**Comment by Vogtinator** [comment]
> I think we need to give clear YES/NO answer on question - "Do we need runtime object abstraction or not ? "

Something like that can usually only be answered after the fact, when it's visible whether that was the right or wrong decision...

AFAICT we have runtimes which behave similarly enough that they can just use the same code and we have runtimes that are so different that they need to use completely different code. IMO unneeded abstractions just make it harder to tell what's actually happening, which is particularly important for openQA tests, but that's highly subjective.

**Pull request closed without merging**
