### PR TITLE
Update systemd_testsuite

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Superseeds: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9709
- Verification run:
  - [aarch64](https://openqa.opensuse.org/tests/1207617)
  - [x86_64](https://openqa.opensuse.org/tests/1207618)

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@eliroca, @tblume, WDYT?

**Comment by tblume** [comment]
Fine for me, but the referenced verification runs seem to fail.

**Comment by SergioAtSUSE** [comment]
> Fine for me, but the referenced verification runs seem to fail.

Not because of this PR. binary_tests needs adaptions. That should be fix in another PR in my opinion.

**Comment by eliroca** [comment]
LGTM

**Comment by eliroca** [comment]
> > Fine for me, but the referenced verification runs seem to fail.
> 
> Not because of this PR. binary_tests needs adaptions. That should be fix in another PR in my opinion.
binary_tests ran on my tests: http://emerson.suse.de/tests/2102

**Comment by SergioAtSUSE** [comment]
> binary_tests ran on my tests: http://emerson.suse.de/tests/2102

The something change in between. I just rebased your two commits onto origin/master

**Comment by vpelcak** [comment]
Hello.

When preparing verification runs, please make sure that also supported versions of SLE are not impacted.

We are working on the automation together.
Therefore we need to be careful to not to break each others work.

Please note, while I fully approve and appreciate the support of Tumbleweed (I use it as primary system), there is also Leap and most of all, our work is centered around SLE as our core business. We earn most of the money by supporting SLE for our customers. Please bear it in mind.

**Comment by SergioAtSUSE** [comment]
> When preparing verification runs, please make sure that also supported versions of SLE are not impacted.

You don't see verification runs here, but I did verify on SLE15-SP2+, which are the version I commited to cover with this test suite.
And tests for SLE15-SP2 are also fixed with this PR.

Please, paste the link of affected tests so we can take a look.

Also, take in mind that this test suite was only created with the purpose so that the system team within SUSE can test patches before staging, so it was never intended to be used as a de-facto systemd integration test, for that we had another test suite. But, for some reason people started to use it and then started to ask us to make the test suite work for older versions.
I didn't wanted to commit to that.

Now, @tblume seems to want to maintain it also for older versions after we received complaints when this PR got merged.

So, I suppose from now on, you will be able to rely on this test suite too as a de-facto integration test in openQA.

**Comment by tblume** [comment]
Thanks for clarification Sergio.
Since we need the testsuite for testing systemd patches anyway, I guess I could maintain it the same way for openQA.
However, this task doesn't belong to the main set of my duties.
If I'm very busy with my main tasks, a fix for openQA tests might take some time.
Otherwise, it needs to be discussed with my manager about how to prioritize work for openQA.

**Pull request merged**
