### PR TITLE
main.pm for rt tests

### PR DESCRIPTION
**Pull request by kravciak**

### CODE REVIEW

**Comment by coolo** [comment]
please don't merge - it will break #1153, which is the more important fix atm

**Comment by coolo** [comment]
other than that: :+1

**Comment by coolo** [comment]
now please rebase

**Comment by coolo** [comment]
or wait - I'll mege this into my other PR - otherwise we rebase to death

**Comment by kravciak** [comment]
already rebased, but as u wish :)

**Comment by coolo** [comment]
ok, I won't merge this. You have is_rt, but you're not RT - you only have an addon to what else. So put your function in line and behind we_is_applicable

**Pull request merged**
