### PR TITLE
Correct name of the "sle12_online_migration" folder

### PR DESCRIPTION
**Pull request by okurz**
The test modules of tests/migration/sle12_online_migration are used for
other product versions as well, e.g. SLE15, so we should use a more
generic name that fits.

Renamed with

```
mkdir -p tests/migration/online_migration; for i in $(git ls-files tests/migration/sle12_online_migration/*); do git mv $i ${i/sle12_/}; done
```

### CODE REVIEW

**Comment by coolgw** [comment]
I am afraid this change will lead lots of error for migration test. I suppose we also need change following files, also we need try run some test cases make sure everything is still ok after update. 
 
grep -risn sle12_online_migration *
lib/main_common.pm:1781:        loadtest "migration/sle12_online_migration/snapper_rollback";
products/sle/main.pm:448:    loadtest "migration/sle12_online_migration/online_migration_setup";
products/sle/main.pm:453:    loadtest "migration/sle12_online_migration/register_system";
products/sle/main.pm:456:        loadtest "migration/sle12_online_migration/zypper_patch";
products/sle/main.pm:459:        loadtest "migration/sle12_online_migration/minimal_patch";
products/sle/main.pm:462:        loadtest "migration/sle12_online_migration/register_without_ltss";
products/sle/main.pm:466:    loadtest "migration/sle12_online_migration/pre_migration";
products/sle/main.pm:471:        loadtest "migration/sle12_online_migration/yast2_migration";
products/sle/main.pm:474:        loadtest "migration/sle12_online_migration/zypper_migration";
products/sle/main.pm:476:    loadtest "migration/sle12_online_migration/post_migration";

**Comment by okurz** [comment]
Yes, I forgot the mentions on the schedule. Fixed that. I don't see other things that would rely on the filenames unless any production tests use EXCLUDE_MODULES or INCLUDE_MODULES with full names or SCHEDULE. I doubt we are able to find these easily. IMHO this PR is good to merge

**Comment by tinawang123** [comment]
Verified: yast online migration https://10.160.0.207/tests/4376028
zypper online migration https://10.160.0.207/tests/4376032#

**Comment by okurz** [comment]
thank you!

**Pull request merged**
