### PR TITLE
test

### PR DESCRIPTION
**Pull request by coolgw**
[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/xyz
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

### CODE REVIEW

**Comment by foursixnine** [comment]
@coolgw I guess this pr was a mistake? or just a test as the title states? :)

**Comment by asmorodskyi** [comment]
I think this PR don't have chances to be merged anyway :D closing . @coolgw you can reopen it but I really like to hear reasoning why :))))

**Comment by coolgw** [comment]
> @coolgw I guess this pr was a mistake? or just a test as the title states? :)

Not a mistake, i made this to validate a great feature of OPENQA

**Comment by coolgw** [comment]
> I think this PR don't have chances to be merged anyway :D closing . @coolgw you can reopen it but I really like to hear reasoning why :))))
For sure can close now, i just using this validate openqa-clone-custom-git-refspe:)

**Comment by asmorodskyi** [comment]
ah sorry if I ruin something for you . I think I know which feature you meant - ability to execute your own branch in openqa.suse.de / openqa.opensuse.org, right ? 
Just in case you miss this there is ability to use this feature by simply specifying a branch without PR creation

**Comment by coolgw** [comment]
> ah sorry if I ruin something for you . I think I know which feature you meant - ability to execute your own branch in openqa.suse.de / openqa.opensuse.org, right ?
> Just in case you miss this there is ability to use this feature by simply specifying a branch without PR creation

Thanks for your suggestion. I will try to using my branch next time:)

**Pull request closed without merging**
