### PR TITLE
Reorder Post fail hooks calls for first_boot test

### PR DESCRIPTION
**Pull request by foursixnine**
Bring back and call again save_memory_dump when needed, and don't die if it's not implemented.

This ensures that we really get the logs, that should be needed for further investigation (if needed)

Verification run: 

 * https://openqa.suse.de/tests/3393456
 * https://openqa.suse.de/tests/3393481
Progress ticket: https://progress.opensuse.org/issues/42683
Related tests: https://openqa.suse.de/tests/overview?arch=&machine=&modules=first_boot&modules_result=failed&distri=sle&version=15-SP2&build=38.6&groupid=110#

### CODE REVIEW

**Comment by foursixnine** [comment]
Side note: commits with funny names will be rewritten ;)

**Comment by foursixnine** [comment]
@DrMullings you created the bootbasetest module, care to give a look here? :)

**Comment by DrMullings** [comment]
LGTM

**Comment by foursixnine** [comment]
Ok, now it's ready, ready :)

**Pull request merged**
