### PR TITLE
sshd: Ensure 'sudo' is installed

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by foursixnine** [comment]
@Soulofdestiny, @ggardet Please see #7440 :) Whichever is merged I'm fine :)

**Comment by coolo** [comment]
this is only about calling a command as a user, no? Use runuser instead of installing additional packages?

**Comment by coolo** [comment]
(or su as in 7440)

**Comment by Soulofdestiny** [comment]
superseded by #7440

**Pull request closed without merging**
