### PR TITLE
workaround: Record soft fail on SLE15 only

### PR DESCRIPTION
**Pull request by dzedro**
#11566 https://bugzilla.suse.com/show_bug.cgi?id=1179654

### CODE REVIEW

**Review by ldevulder — APPROVED** [review]
Thanks!

**Comment by dzedro** [comment]
> Thanks!

Thank you! :wink:

**Comment by Vogtinator** [comment]
Why not just make `expired-gpg-key` a workaround needle for SLE 15?

**Comment by dzedro** [comment]
> Why not just make `expired-gpg-key` a workaround needle for SLE 15?

Would be better, I believe I will remove this workaround soon when the bug is fixed.

**Pull request merged**
