### PR TITLE
Improve zfs test

### PR DESCRIPTION
**Pull request by grisu48**
Add handling for `.zfs/snapshot` directory to zfs test

- Related ticket: https://progress.opensuse.org/issues/81266 and https://progress.opensuse.org/issues/70981
- Needles: -
- Verification run: http://phoenix-openqa.qam.suse.de/t4389

Two commits, because there were two distinct features to be implemented.

### CODE REVIEW

**Comment by grisu48** [comment]
@jankohoutek would you be up for review? I've incorporates the latest discussed improvements from [poo#70981](https://progress.opensuse.org/issues/70981) except the NFS automount. This one will be tackled in a later PR.

**Comment by grisu48** [comment]
I've made two commits, because there were two distinct features to be implemented:
* Improved error handling output
* Inclusion of the `.zfs/snapshot` handling.

**Review by jankohoutek — APPROVED** [review]
Seems sane.

**Review by jankohoutek — APPROVED** [review]
Seems sane.

**Review by pdostal — APPROVED** [review]

**Pull request merged**
