### PR TITLE
Maintenance: map ADDONS to SCC_ADDONS

### PR DESCRIPTION
**Pull request by coolo**
This way we get released updates for the addons. Otherwise we can't
test test updates

### CODE REVIEW

**Comment by coolo** [comment]
can I merge if I put "pair programmed with coolo" here? :)

**Comment by coolo** [comment]
https://progress.opensuse.org/issues/15068 is related

**Comment by okurz** [comment]
Start with capital letter after colon in commit message.

You have a tendendency to stating the benefit or reason of a change in only the second line of a commit message. I propose to turn that around.

> can I merge if I put "pair programmed with coolo" here? :)

No

**Comment by coolo** [comment]
Sorry, no. http://chris.beams.io/posts/git-commit/ says "Begin all subject lines with a capital letter" - there is no mention of colons. And I didn't want to hear about your personal preferences about commit logs, but if there is a problem with the commit

**Comment by okurz** [comment]
then it's LGTM

**Comment by okurz** [comment]
You were right that http://chris.beams.io/posts/git-commit/ did not state something about colon. The whole article is not mentioning the word "english" at all.

http://data.grammarbook.com/blog/commas/capitalization-with-colons/ is giving interesting insight, it's not mandatory to start with capital letter after the colon, I was wrong. So I guess I will adjust my rules then.

**Pull request merged**
