### PR TITLE
[WIP] Fix reboot phase of autoyast test for s390

### PR DESCRIPTION
**Pull request by kravciak**

### CODE REVIEW

**Comment by okurz** [comment]
Sorry to annoy again or something but this `if (<backend>) ...` really smells like it should be in the specific backends.

**Comment by Soulofdestiny** [comment]
@okurz can you explain this in more detail?
you're talking about the xml modifying part?

**Comment by coolo** [comment]
Put 'check_var('BACKEND', 'svirt') and check_var('ARCH', 's390x')' into a is_zkvm function and okurz will be pleased

**Comment by okurz** [comment]
a bit, yes

**Pull request closed without merging**
