### PR TITLE
Install wicked before enable it for publish tw supportserver qcow

### PR DESCRIPTION
**Pull request by coolgw**
Install wicked before enable it for publish tw supportserver qcow

- Related ticket: https://progress.opensuse.org/issues/112775
- Needles: na
- Verification run: https://openqa.opensuse.org/tests/2482758

### CODE REVIEW

**Review by ge0r — COMMENTED** [review]
looks good. One question on the verification run, how did you apply the code changes? Is the verification run on development using your branch's changes?

**Comment by coolgw** [comment]
> the



> looks good. One question on the verification run, how did you apply the code changes? Is the verification run on development using your branch's changes?

Yes VR use my branch

**Comment by coolgw** [comment]
> looks good. One question on the verification run, how did you apply the code changes? Is the verification run on development using your branch's changes?

Yes

**Review by ge0r — APPROVED** [review]
LGTM!

**Comment by BillAnastasiadis** [comment]
LGTM too. Merging.

**Pull request merged**
