### PR TITLE
curl,wget: Replace not working url with working local url

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://openqa.suse.de/tests/4234163#step/curl_ipv6/4
- Verification run:
https://openqa.opensuse.org/tests/1267051 TW
https://openqa.suse.de/tests/4236143 12sp1
http://10.100.12.155/tests/15595 15.2
http://10.100.12.155/tests/15594 15sp1
https://openqa.suse.de/tests/4300091#step/wget_ipv6/7 PC

### CODE REVIEW

**Comment by Vogtinator** [comment]
> At least from the outside, `openqa.opensuse.org` has a valid IPv6 address, which means that there is no fallback being tested. Or maybe I'm missing something?

I assume it's testing that curl falls back from trying a IPv6 address to a IPv4 address after DNS lookup, but a previously successful run doesn't have any logs about that, so I can't tell for sure.

**Comment by dzedro** [comment]
Do we know how was `www3.zq1.de/test.txt` resolved before ?
If we want to be sure ipv4 is resolved -4 should be used, then I'm not sure how it is _ipv6 test ? 

> though there is no verification that there was actually a fallback

exactly :roll_eyes:

**Comment by Vogtinator** [comment]
> Do we know how was `www3.zq1.de/test.txt` resolved before ?

@bmwiedemann should know

> If we want to be sure ipv4 is resolved -4 should be used, then I'm not sure how it is _ipv6 test ?

I found https://sourceforge.net/p/curl/bugs/917/, maybe it's supposed to catch that?

> > though there is no verification that there was actually a fallback
> 
> exactly

**Comment by dzedro** [comment]
> > Do we know how was `www3.zq1.de/test.txt` resolved before ?
> 
> @bmwiedemann should know
> 
> > If we want to be sure ipv4 is resolved -4 should be used, then I'm not sure how it is _ipv6 test ?
> 
> I found https://sourceforge.net/p/curl/bugs/917/, maybe it's supposed to catch that?

I guess for that we need host with unresolvable ipv6 to reproduce the fallback to ipv4

**Comment by bmwiedemann** [comment]
At least for the last years, I had `www3 CNAME golf46.zq1.de.` so it resolved to both IPv4 and 6.

I forgot that I used it here and dropped it in a recent server move. I quickly added it back.

Do test VMs even have ipv6 connectivity?

**Comment by dzedro** [comment]
I don't think there are VMs with ipv6.

**Pull request closed without merging**
