### PR TITLE
add schedule for systemd-testsuite tests

### PR DESCRIPTION
**Pull request by tblume**
see communication in pr 14144

### CODE REVIEW

**Comment by pevik** [comment]
```
'systemd_testsuite/test_02_unittests' test module in 'schedule/systemd/suse_patches-systemd_testsuite.yaml' schedule file.
'systemd_testsuite/test_17_udev' test module in 'schedule/systemd/suse_patches-systemd_testsuite.yaml' schedule file.
'systemd_testsuite/test_24_cryptsetup' test module in 'schedule/systemd/suse_patches-systemd_testsuite.yaml' schedule file.
'systemd_testsuite/test_29_portable' test module in 'schedule/systemd/suse_patches-systemd_testsuite.yaml' schedule file.
'systemd_testsuite/test_17_udev' test module in 'schedule/systemd/suse_patches-systemd_testsuite.yaml' schedule file.
```
Names are really wrong, e.g `tests/systemd_testsuite/test_02_unittests.pm` is missing, there is no `tests/systemd_testsuite/test_24_cryptsetup.pm` but `tests/systemd_testsuite/test_24_unit_tests.pm` (added in 95b7b6277010c3f1c1a05809dbe2cfbbe573d56e by `root <root@mcbrain-2.arch.suse.de>` hm :)) and `tests/systemd_testsuite/test_02_cryptsetup.pm`. Please could you please double check the files?

**Comment by pevik** [comment]
@tblume I test it with some changes (because you used modules which does not exist:
https://github.com/pevik/os-autoinst-distri-opensuse/commit/3eeb9eff5c3bd8eda91088366495c431e8dfe517

but it is obviously missing some variables therefore `zypper_call in systemd-qa-testsuite` dies:
http://quasar.suse.cz/tests/8448#step/prepare_systemd_and_testsuite/23

You also test only Tumbleweed and 15.3, how about 15.4? Are you sure you don't want to run on every Tumbleweed and 15.4 build?

Or just point me to the your internal openQA worker where it was worked last time and give access to the sources, so that I can finish upstreaming of it.

**Comment by tblume** [comment]
> @tblume I test it with some changes (because you used modules which does not exist: [pevik@3eeb9ef](https://github.com/pevik/os-autoinst-distri-opensuse/commit/3eeb9eff5c3bd8eda91088366495c431e8dfe517)
> 
> but it is obviously missing some variables therefore `zypper_call in systemd-qa-testsuite` dies: http://quasar.suse.cz/tests/8448#step/prepare_systemd_and_testsuite/23

Yeah, the code is obsolete, the testsuite package has changed the name to systemd-testsuite.
I have a number of patches that will update this.

> You also test only Tumbleweed and 15.3, how about 15.4? Are you sure you don't want to run on every Tumbleweed and 15.4 build?

At the time when ran my last SLE test there was no 15.4, I will update the schedule.
 
> Or just point me to the your internal openQA worker where it was worked last time and give access to the sources, so that I can finish upstreaming of it.

Unfortunately, I deleted most of the testresults when I updated our internal openQA instance. :(
The one I still have is: 

http://moore.arch.suse.de/tests/96

I guess it is better when I push my patches with this PR.
I did a new test run with my updated patches yesterday.
Unfortunately it fails now in boot_to_desktop:

http://moore.arch.suse.de/tests/320

because it seems that wait_boot got a new variable $textmode, that need to be set when running from a textmode installation.
Would already be a great help if you can tell me how I can set this.
I'd really like to run a test myself before pushing my patches.

**Comment by pevik** [comment]
@tblume sure, thanks for working on this.

**Pull request closed without merging**
