### PR TITLE
Autoyast profiles for opensuse

### PR DESCRIPTION
**Pull request by kravciak**
Local runs:
gnome: http://dhcp91.suse.cz/tests/2838
minimal: http://dhcp91.suse.cz/tests/2839

Needles:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/120

### CODE REVIEW

**Comment by okurz** [comment]
Can you state the related progress item or a failed test run to fix in the commit message and/or PR?

**Comment by okurz** [comment]
needle PR merged

**Comment by kravciak** [comment]
Failing test: https://openqa.opensuse.org/tests/284028
No progress item, but requirement for poo#9574

**Comment by okurz** [comment]
great, thx

**Pull request merged**
