### PR TITLE
Enable several test modules in main

### PR DESCRIPTION
**Pull request by waynechen55**
They are:
        loadtest "virt_autotest/set_config_as_glue";
        loadtest "virt_autotest/virsh_internal_snapshot";
        loadtest "virt_autotest/virsh_external_snapshot";

### CODE REVIEW

**Comment by waynechen55** [comment]
I am not sure whether they are only these ones or not. @alice-suse

**Comment by alice-suse** [comment]
Let's include these 3 P1 tests first, as your verification run validated.

**Comment by alice-suse** [comment]
Please help take care of the test results on osd after merge.

**Comment by alice-suse** [comment]
@waynechen55 Seems only 2 P1 tests are enabled, but hotplugging  is still missing. Adaption to suit to junit is already done in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8241/files#diff-661c685bdce75aad58aa29f85cb482b3, as virsh_internal_snapshot.pm and virsh_external_snapshot.pm have been done. Please help to make  a PR to enable hotplugging.pm too.

**Pull request merged**
