### PR TITLE
Extend yast2_hostnames

### PR DESCRIPTION
**Pull request by Zaoliang**
Please see my reference test at:
http://e13.suse.de/tests/2955#step/yast2_hostnames/

### CODE REVIEW

**Comment by okurz** [comment]
needles rebase. Also you mixed up branches. It's mixed with yast2_datetime and yast2_bootloader

**Comment by asmorodskyi** [comment]
please solve conflicts

**Comment by Zaoliang** [comment]
but I got alreasy "Merged #189" notification from okurz...

**Comment by okurz** [comment]
On Monday, 15 May 2017 00:43:34 CEST Zaoliang Luo wrote:
> but I got alreasy "Merged #189" notification from okurz...

#189 is not that PR :-)

**Pull request closed without merging**
