### PR TITLE
Cleanup obsolete test code using old terraform deployment

### PR DESCRIPTION
**Pull request by Amrysliu**
All the tests for SLES for SAP cloud images are nowadays performed using the qe-sap-deloyment.  The old deployment https://github.com/SUSE/ha-sap-terraform-deployment is no longer used. So we could cleanup the un-useful code.

Related: https://jira.suse.com/browse/TEAM-9434

VRs:
https://openqa.suse.de/tests/15817410 (Passed)
https://openqa.suse.de/tests/15817411# (Passed)
https://openqa.suse.de/tests/15817412# (Passed)

### CODE REVIEW

**Review by mpagot — APPROVED** [review]
LGTM

**Review by asmorodskyi — APPROVED** [review]
LGTM

**Comment by asmorodskyi** [comment]
Thanks !

**Review by alvarocarvajald — APPROVED** [review]

**Comment by Amrysliu** [comment]
> LGTM. But let's not merge until we run several verification runs with a CASEDIR pointing to this branch.

I run some publiccloud VRs which calls `create_instances` in provider.pm related to my modification.

**Pull request merged**
