### PR TITLE
Send string to serial in the same command

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Related ticket: https://progress.opensuse.org/issues/57008
- Verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/1655#step/docker/74

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@Vogtinator,

If I understood that step properly, it starts a container without terminal nor standard input attached, so that the shell will be blocked until the process finishes, and there is no possibility to stop the process sending signals with the keyboard (or that is expected).

How are my changes breaking that test?
The string **ctrlc_timeout** is still sent after the docker container exits. The only difference is that the shell will handle it, instead of waiting for the shell to receive the following commands.

**Comment by Vogtinator** [comment]
I just did some experiments:

* It appears like even `docker run --rm` without either `-i` or `-t` swallows input. This means that currently it verifies that directly after Ctrl-C the input ends up in bash and does not get swallowed. This is not the case anymore
* The test failure actually looks like a product issue to me. Currently Ctrl-C does not actually work here.

Ctrl-C does work if pressed before the container process is actually launched, which takes roughly half a second. So this might be a race condition which your verification run just wins.

So I'm against this PR as it is currently, as it appears to mask a product issue and is in the best case a no-op.

**Comment by Vogtinator** [comment]
Actually, it's a confirmed product issue as a comment on the poo ticket states.

**Comment by SergioAtSUSE** [comment]
I know that it is a bug. My PR was not trying to fix the bug. With my proposal I find more easy to understand the purpose of this tests than the current approach, typing something in a "limbo" state.

I still don't see how my PR hides anything. It performs the same action.

**Pull request closed without merging**
