### PR TITLE
NETFILTER_PKT test fix in ip_eb_tables

### PR DESCRIPTION
**Pull request by vtrubovics**
Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1188851, https://progress.opensuse.org/issues/97076
Gitlab merge request https://gitlab.suse.de/security/audit-test-sle15/-/merge_requests/25
Successfull test run: https://openqa.suse.de/tests/7030292#details

### CODE REVIEW

**Comment by rfan1** [comment]
Viktor,

Minor comment, "POO97076 NETFILTER_PKT test fix in ip_eb_tables" to "NETFILTER_PKT test fix in ip_eb_tables"

**Comment by lilyeyes** [comment]
> Viktor,
> 
> Minor comment, "POO97076 NETFILTER_PKT test fix in ip_eb_tables" to "NETFILTER_PKT test fix in ip_eb_tables"

@vtrubovics  FYI: https://chris.beams.io/posts/git-commit/

**Comment by vtrubovics** [comment]
> 
> 
> > Viktor,
> > Minor comment, "POO97076 NETFILTER_PKT test fix in ip_eb_tables" to "NETFILTER_PKT test fix in ip_eb_tables"
> 
> @vtrubovics FYI: https://chris.beams.io/posts/git-commit/

Fixed

**Review by rfan1 — APPROVED** [review]
LGTM

Thanks for the fix

**Comment by jouyingbin** [comment]
> > > Viktor,
> > > Minor comment, "POO97076 NETFILTER_PKT test fix in ip_eb_tables" to "NETFILTER_PKT test fix in ip_eb_tables"
> > 
> > 
> > @vtrubovics FYI: https://chris.beams.io/posts/git-commit/
> 
> Fixed


Hi @vtrubovics 

I think you should also modify the git commit message correspondingly too. 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13203/commits

Thanks.

Others are LGTM.

**Review by Amrysliu — APPROVED** [review]
LGTM

**Review by lilyeyes — APPROVED** [review]
LGTM. Thanks for the changes.

**Review by jouyingbin — APPROVED** [review]
LGTM. Thanks for the patch. :)

**Pull request merged**
