### PR TITLE
chromium: Type each character as the screen changes

### PR DESCRIPTION
**Pull request by kalikiana**
See: https://progress.opensuse.org/issues/109737

### CODE REVIEW

**Comment by kalikiana** [comment]
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15173 https://openqa.opensuse.org/tests/2443233 
Created job #2449803: opensuse-15.3-DVD-Updates-x86_64-Build20220701-1-install_with_updates_gnome@64bit-2G -> https://openqa.opensuse.org/t2449803

**Review by perlpunk — APPROVED** [review]

**Review by okurz — CHANGES_REQUESTED** [review]
https://openqa.opensuse.org/tests/2449613 took 2m26s for the chromium test module. Your verification run took 3m44s. I don't think the test should be slowed down that significantly. Please check runtime of the module.

**Comment by kalikiana** [comment]
> https://openqa.opensuse.org/tests/2449613 took 2m26s for the chromium test module. Your verification run took 3m44s. I don't think the test should be slowed down that significantly. Please check runtime of the module.

Any suggestions on how to avoid that while still verifying every typed character? I didn't change anything else.

**Comment by okurz** [comment]
> > https://openqa.opensuse.org/tests/2449613 took 2m26s for the chromium test module. Your verification run took 3m44s. I don't think the test should be slowed down that significantly. Please check runtime of the module.
> 
> Any suggestions on how to avoid that while still verifying every typed character? I didn't change anything else.

I am not sure if my observation really shows a problem. So to be sure that your changes actually cause this slow-down can you try to run multiple tests with just the "chromium" test module included to check? E.g. call `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15173 https://openqa.opensuse.org/tests/2450411 SCHEDULE=tests/boot/boot_to_desktop,tests/x11/chromium` with https://openqa.opensuse.org/tests/2450411 being "opensuse-Tumbleweed-DVD-x86_64-extra_tests_gnome@64bit" which uses one of the latest Tumbleweed pre-installed qcow files.

The option `wait_screen_change` seems to be a sensible approach, maybe we just need to tweak it a bit.

**Comment by kalikiana** [comment]
Waiting on the results of #2109 for now to confirm how to continue

**Comment by okurz** [comment]
> Waiting on the results of #2109 for now to confirm how to continue

You don't mean pull request `#2109` in this repo, what are you waiting for?

**Comment by kalikiana** [comment]
Apparently looking into optimizing the underlying code is far from trivial, so I'd like to wrap this up as-is. We know it works. See also [my comment on the ticket](https://progress.opensuse.org/issues/109737#note-38).

**Review by okurz — APPROVED** [review]
As https://progress.opensuse.org/issues/109737 still doesn't have auto-review or anything let's approve as is despite the slow-down. Created a new ticket https://progress.opensuse.org/issues/114412 to optimize the performance.

**Pull request merged**
