### PR TITLE
Add java into migration regression check

### PR DESCRIPTION
**Pull request by coolgw**
Add java into migration regression check

- Related ticket: https://progress.opensuse.org/issues/104472
- Needles: na
- Verification run: 
http://openqa.suse.de/t7918620
http://openqa.suse.de/t7918475
http://openqa.suse.de/t7918474
http://openqa.suse.de/t7918473

### CODE REVIEW

**Review by tinawang123 — APPROVED** [review]
LGTM

**Comment by hjluo** [comment]
LGTM

**Review by chcao — APPROVED** [review]
LGTM

**Review by rfan1 — APPROVED** [review]

**Review by lemon-suse — APPROVED** [review]

**Comment by lemon-suse** [comment]
Please have a look on this failure, http://openqa.suse.de/tests/7918473#step/java/28

**Comment by lemon-suse** [comment]
The VRs are for sles15+, could you run one/two VRs on sles12+ such as 12SP5 to have a look the test results on sles 12+? Thanks.

**Comment by coolgw** [comment]
> Please have a look on this failure, http://openqa.suse.de/tests/7918473#step/java/28

rerun: https://openqa.suse.de/tests/7919405

**Comment by coolgw** [comment]
> 



> The VRs are for sles15+, could you run one/two VRs on sles12+ such as 12SP5 to have a look the test results on sles 12+? Thanks.
The x86 power aarch already blocked by issue so only can run s390 case:
http://openqa.suse.de/t7919407 for 390 slse12

**Comment by coolgw** [comment]
> > Please have a look on this failure, http://openqa.suse.de/tests/7918473#step/java/28
> 
> rerun: https://openqa.suse.de/tests/7919405

https://openqa.suse.de/tests/7919798

**Comment by coolgw** [comment]
More validation on function and maintenance job, detail you can check progress ticket.

**Pull request merged**
