### PR TITLE
WIP: Remove record_soft_failure 'bsc#1081584' from updates_packagekit_gpk.pm

### PR DESCRIPTION
**Pull request by Zaoliang**
- remove workaround bsc#108154
https://openqa.suse.de/tests/1729469#step/updates_packagekit_gpk/11

### CODE REVIEW

**Comment by okurz** [comment]
Wasn't the bug about gnome-packagekit not being installed?

**Comment by Zaoliang** [comment]
@okurz yes, that is excatly your request
--

--- Comment #14 from Oliver Kurz <okurz@suse.com> ---
@zluo you added the soft-fail in os-autoinst-distri-opensuse. Could you please
make sure the workaround is removed again?

**Comment by okurz** [comment]
I said "make sure the workaround is removed". Simply removing a line is something that I could have done as well. If the bug was about gnome-packagekit not being installed then I assume we do not need the test code to install it explicitly so that should be removed along with the soft fail reference, right?

**Comment by Zaoliang** [comment]
please don't merge, need resolve https://progress.opensuse.org/issues/36991 at first

**Comment by rwx788** [comment]
Included in #5198

**Comment by foursixnine** [comment]
Related pr was closed too... closing this one

**Pull request closed without merging**
