### PR TITLE
Add YaST2 GUI test for openSUSE TW yast2_control_center_qt.pm

### PR DESCRIPTION
**Pull request by Zaoliang**
Create a new YaST GUI test for openSUSE TW. 
Please check my reference test at:
http://e13.suse.de/tests/2497#step/yast2_control_center/

### CODE REVIEW

**Comment by Zaoliang** [comment]
Update reference test at: http://e13.suse.de/tests/2507#

**Comment by okurz** [comment]
@Zaoliang the code of yast2_control_center_qt.pm vs. yast2_control_center.pm looks like an updated version and some Tumbleweed specific changes so I recommend to use the code from yast2_control_center_qt.pm as yast2_control_center.pm and put where needed specific code, e.g. for openSUSE as well as SLE based on e.g. `check_var('DISTRI', 'sle')` and `check_var('DISTRI', 'opensuse')` so that we can reduce the amount of duplicated code.

**Comment by okurz** [comment]
see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2733 for my proposal

**Comment by Zaoliang** [comment]
Please see reference test at: http://e13.suse.de/tests/2586#step/yast2_control_center

**Comment by okurz** [comment]
please squash the two commits together. Looking at the number of lines the file grew to about 700 lines and is therefore by far the biggest test module (next one is tests/support_server/setup.pm with 374 lines) and eventually we should revisit and rework that file.

**Comment by okurz** [comment]
merged locally

**Pull request closed without merging**
