### PR TITLE
Simplify support_server

### PR DESCRIPTION
**Pull request by okurz**
* support_server: Simplify creation of mutexes
* support_server: Delete unused variables and method
* Optimize masking/disabling getty and packagekit

### CODE REVIEW

**Comment by okurz** [comment]
@schlad minor first step. Afterwards either you or me can continue. Just created the PR so that we are not running into a conflict.

**Comment by schlad** [comment]
@asmorodskyi Please see: 10.160.66.198/tests/3631

**Comment by okurz** [comment]
@schlad should I do something with your information? Did you try out my changes?

**Comment by schlad** [comment]
@okurz sorry I copied an url in the wrong PR.

As for this commit: I would split it in 2 commits, One containing: support_server: Simplify creation of mutexes and Optimize masking/disabling getty and packagekit.

In a separate one we could talk about support_server: Delete unused variables and method. How about that?
Overall I already use nfs support config, so I would not remove it. I would also not call it "unused code". More of a stub function to be implemented. So removing it to just add it with implementations... I would personally prefer to just working on this function instead.

**Comment by asmorodskyi** [comment]
@thehejik , @kravciak WDYT ?

**Comment by asmorodskyi** [comment]
Generally in my understanding concept of support_server is broken . it provides what should be actually provided by os-autoinst out of the box. So I find more effective to invest into os-autinst code base to provide functionality which we currently getting from support_server.
But no doubt this patch improving  existing code base so worth to merge it

**Comment by thehejik** [comment]
I didn't test but LGTM.

**Comment by okurz** [comment]
@czerw @schlad sorry about the "getty/packagekit" commit which I included by error, had nothing to do with this PR. Ok so I understood you are fine with these most trivial changes. Rest what had been mentioned by @schlad should go into any potential, future proper implementation for NFS support *or* the alternative what @asmorodskyi proposed for os-autoinst.

**Pull request merged**
