### PR TITLE
Fix kernel_kexec not waiting for the login-prompt ending up in wrong tty

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/33307

Verification run: http://lord.arch/tests/659

### CODE REVIEW

**Comment by okurz** [comment]
Replaces https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4683#pullrequestreview-106312148

**Comment by okurz** [comment]
*critsit* as @kravciak already deleted the former workaround needle so I want to make sure QAM tests do not fail in kernel_kexec.

**Comment by kravciak** [comment]
I checked your local run - http://lord.arch/tests/659#step/kernel_kexec/20 - needle matches BEFORE reboot. You should to `cls` before asserting...

**Comment by okurz** [comment]
Ah, geez. I think I need to rethink, thx

**Pull request merged**
