### PR TITLE
Adapt salt.tar.gz to the latest yast2-configuration-management changes

### PR DESCRIPTION
**Pull request by imobachgs**
This PR updates the salt.tar.gz (which, btw, it is a TAR but it is not gzipped besides its name) to the latest changes we introduced in yast2-configuration-management 4.2.5. The main change is that now the formulas directory is composed of `states` and `metadata` directories in order to follow the same structure as [SUMA Formulas](https://documentation.suse.com/external-tree/en-us/suma/3.2/susemanager-best-practices/single-html/book.suma.best.practices/book.suma.best.practices.html#best.practice.salt.formulas.filedir).

- Related ticket: https://progress.opensuse.org/issues/67285

### CODE REVIEW

**Comment by b10n1k** [comment]
https://openqa.suse.de/tests/4284267 VR for the PR above. and looks good

**Comment by b10n1k** [comment]
@imobachgs there is another defect in the execution. the "Running Provission" popup does not close automatically as it was happening before. is something that you can take care of should we adjust the test?

**Comment by imobachgs** [comment]
You are right, sorry. One of the [changes we introduced](https://github.com/yast/yast-configuration-management/blob/master/package/yast2-configuration-management.changes#L8) in version 4.2.5 is that we honor now the `report` settings. So we need to set a timeout for `messages`. As a side note, if an error happens, the module will stick to the `report` settings for `errors` instead.

I have updated the PR. Let's see whether it is enough to make it work.

Thanks!

**Comment by b10n1k** [comment]
https://openqa.suse.de/tests/4288172#details done. All good
@rwx788 can you review and merge?

**Comment by b10n1k** [comment]
https://openqa.suse.de/tests/4288212 pass

**Comment by rwx788** [comment]
@imobachgs Thanks a lot for the patch!

**Comment by imobachgs** [comment]
> @imobachgs Thanks a lot for the patch!

You are welcome!

**Pull request merged**
