### PR TITLE
Simplify loadtest helper by adding the extension

### PR DESCRIPTION
**Pull request by okurz**
We are already using a helper method to load each test module so we can also
easily save ourselves the extension and add this in the helper.

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
please rebase ;)

**Comment by okurz** [comment]
would you merge after I rebased or should we get feedback from someone else first?

**Comment by Soulofdestiny** [comment]
Well, I don't see how it should break things - but sure, we can wait for more feedback

**Comment by coolo** [comment]
rebase and push

**Comment by okurz** [comment]
done: rebased, pushed, merged

**Pull request merged**
