### PR TITLE
Install additional cockpit modules

### PR DESCRIPTION
**Pull request by mloviska**
There are additional cockpit modules we need to make sure are
installable but are not pulled as deps when installing `cockpit`
package.

```
cockpit-machines | Cockpit user interface for virtual machines
cockpit-tukit    | Cockpit module for Transactional Update
```

The cockpit-{wicked,nm} is pre-installed in the images depending on
used network backend.

- ticket: [Extend cockpit smoke test to install the different
  modules](https://progress.opensuse.org/issues/115010)

### CODE REVIEW

**Comment by mloviska** [comment]
VRs:

* [AY slem5.3 + wicked](http://kepler.suse.cz/tests/18539#step/cockpit_service/4)
* [sle-micro-5.2-MicroOS-Image](http://kepler.suse.cz/tests/18536#step/cockpit_service/14)
* [sle-micro-5.1-MicroOS-Image - missing additional cockpit modules](http://kepler.suse.cz/tests/18537#step/cockpit_service/10)
* [microos-Tumbleweed-MicroOS-Image](http://kepler.suse.cz/tests/18527#step/cockpit_service/15)
* [leap-micro-5.2-MicroOS-Image-x86_64-Build23.2-microos_image_default@64bit](http://kepler.suse.cz/tests/18532#step/cockpit_service/14)
* [leap-micro-5.3-MicroOS-Image](http://kepler.suse.cz/tests/18533#step/cockpit_service/14)

Leaps differ from SLEM, I assume we are dealing with a bug that `cockpit-tukit` is missing within the project.

**Review by grisu48 — APPROVED** [review]
LGTM! But what's with the test issues? :thinking:

**Comment by mloviska** [comment]
> LGTM! But what's with the test issues? thinking

`cockpit-tukit` is apparently missing in Leap but still present in SLEM, as they should be comparable we need to talk to Lubos whether this is intended or the package should be added into the projects later on.

**Comment by DimStar77** [comment]
> VRs (Updated):
> 
> **MICROOS**
> 
>     * [microos-Tumbleweed-MicroOS-Image](http://kepler.suse.cz/tests/18564#)

Maybe a very stupid question: but why are we merging stuff that fails on the VRs? There is not even a bug report filed to claim that the MR would identify a new prod bug that pre-existed prior to the test.

**Comment by DimStar77** [comment]
> > VRs (Updated):
> > **MICROOS**
> > ```
> > * [microos-Tumbleweed-MicroOS-Image](http://kepler.suse.cz/tests/18564#)
> > ```
> 
> Maybe a very stupid question: but why are we merging stuff that fails on the VRs? There is not even a bug report filed to claim that the MR would identify a new prod bug that pre-existed prior to the test - or was that journalcheck pre-existing?

After checking further, it was not pre-existing.

The service that fails is create-dirs-from-rpmdb.service, installed by tukit.

tukit was installed as part of the transaction of the new test module in the VR:
  http://kepler.suse.cz/tests/18564#step/cockpit_service/16

`(102/335) Installing: tukitd-4.0.0-1.1.x86_64 [.......done]`

**Comment by DimStar77** [comment]
The same error shows up on the SLE Micro Verification run:
  http://kepler.suse.cz/tests/18566#step/journal_check/21

**Comment by mloviska** [comment]
> The same error shows up on the SLE Micro Verification run: http://kepler.suse.cz/tests/18566#step/journal_check/21

I thought that we have uncovered this one in MicroOS
https://bugzilla.opensuse.org/show_bug.cgi?id=1188215

**Comment by DimStar77** [comment]
> > The same error shows up on the SLE Micro Verification run: http://kepler.suse.cz/tests/18566#step/journal_check/21
> 
> I thought that we have uncovered this one in MicroOS https://bugzilla.opensuse.org/show_bug.cgi?id=1188215

Wow - that bug is 1 year old and unfixed#15374 
going through the logs of the failed TW/MicroOS tests, it is 'slightly' different apparently

`Aug 19 13:27:47.020936 localhost create_dirs_from_rpmdb[623]: Failed to get default context for directory '/var/lib/nfs/rpc_pipefs': No such file or directory`

/var/lib/tpm is not mentioned as failed to create in our logs. I'll add that info to the bug report (maybe we can 'softfail' that one as ignored issue in journal_check)

**Comment by mloviska** [comment]
> > > The same error shows up on the SLE Micro Verification run: http://kepler.suse.cz/tests/18566#step/journal_check/21
> > 
> > 
> > I thought that we have uncovered this one in MicroOS https://bugzilla.opensuse.org/show_bug.cgi?id=1188215
> 
> Wow - that bug is 1 year old and unfixed#15374 going through the logs of the failed TW/MicroOS tests, it is 'slightly' different apparently
> 
> `Aug 19 13:27:47.020936 localhost create_dirs_from_rpmdb[623]: Failed to get default context for directory '/var/lib/nfs/rpc_pipefs': No such file or directory`

I was hoping that it would get more attention, as it clearly appears across of our products. 
> 
> /var/lib/tpm is not mentioned as failed to create in our logs. I'll add that info to the bug report (maybe we can 'softfail' that one as ignored issue in journal_check)

I will add it there. Thanks

**Comment by mloviska** [comment]
> Just for reference: this PR resulted in 12 new failed test runs on Tumbleweed (4x cockpit_service, aka boo#1202569, 8x journal_check, aka boo#1188215)

Sorry, I should have added the `boo#1188215` as known bugs before merging this PR

Honestly, I haven't anticipated that boo#1202569 would appear in DVD.

Once https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15386 is merged, I will restart the jobs.

**Pull request merged**
