### PR TITLE
Add SSH serial terminal

### PR DESCRIPTION
**Pull request by mdoucha**
Initialize SSH serial terminal implemented in os-autoinst/os-autoinst#1599 and use it as the primary serial terminal for all backends where the SUT is reachable over network (including localhost).

This PR is blocked until os-autoinst/os-autoinst#1599 gets merged and deployed into production. Otherwise it'll break all tests.

Experimental run with slight changes and terminal backend code copied to os-autoinst-distri-opensuse: https://openqa.suse.de/tests/5175184
Job cloned from: https://openqa.suse.de/tests/5173600

- Related ticket: https://progress.opensuse.org/issues/80996
- Needles: N/A
- Verification runs:
  - ZKVM: https://openqa.suse.de/tests/5243478
  - SPVM: https://openqa.suse.de/tests/5246420
  - IPMI: http://openqa.qam.suse.cz/tests/16110

### CODE REVIEW

**Review by grisu48 — APPROVED** [review]
Nice work Martin!

**Comment by mdoucha** [comment]
O3 appears to be updated as well. This PR is ready for review and merge.

**Comment by mloviska** [comment]
Hi @mdoucha, could you please have a look on xen runs ? Seems like there is a problem with the svirt tests (especially both xens and hyperv).

https://openqa.suse.de/tests/5248532#step/consoletest_setup/21
https://openqa.suse.de/tests/5248518#step/consoletest_setup/24

Thanks!

**Comment by mdoucha** [comment]
Yep, it appears to be broken by this PR. First question: Does `VIRSH_GUEST` point directly to the SUT as it does on ZKVM? If not, why not?

**Comment by mloviska** [comment]
> Yep, it appears to be broken by this PR. First question: Does `VIRSH_GUEST` point directly to the SUT as it does on ZKVM? If not, why not?

No, it is not. 
In case of hyperv it points to openQA-hyperv-intermediary (10.162.0.22) domain which wraps RDP into VNC.
In case of xens it points to the xen hypervisor directly (openqaw5-xen.qa.suse.de). I guess again due to vnc.

**Comment by mdoucha** [comment]
OK, in that case you can choose between merging #11693 or setting explicit `SUT_IP` in the job settings. If both `VIRSH_GUEST` and `SUT_IP` are set, the SSH terminal will prefer `SUT_IP`.

**Comment by DimStar77** [comment]
> is this fallout related to this change?
> 
> https://openqa.opensuse.org/tests/1543885#step/sshd/1
> 
> (see similar such errors showing up in the current snapshot

Red herring; nothing related to ssh is responsible for the sshd module failure. Turned out to be a regression introduced by #11685

**Comment by ggardet** [comment]
This breaks `generalhw` backend, see: https://progress.opensuse.org/issues/81835

**Pull request merged**
