### PR TITLE
Select mirror from INSTALL_SOURCE variable

### PR DESCRIPTION
**Pull request by kravciak**
Depend on rsync.pl changes https://gitlab.suse.de/openqa/scripts/merge_requests/25

### CODE REVIEW

**Comment by kravciak** [comment]
Depend on rsync.pl changes https://gitlab.suse.de/openqa/scripts/merge_requests/25

**Comment by coolo** [comment]
please note that the same code is in bootloader_uefi - you want to refactor that part into a function

**Comment by kravciak** [comment]
Maybe it is better like this - or should I rather create find_netboot_mirror sub in utils.pm? (returning mirror url..)

**Comment by coolo** [comment]
I'm torn here myself - objectively it's ok, but it feels dirty ;)

**Comment by kravciak** [comment]
Do not merge then, I see bootloader and bootloader_uefi are quite similar, I will try to find better solution

**Comment by kravciak** [comment]
Ok, tried something different, does it look better to you?

**Comment by coolo** [comment]
this is now far beyond sanity :)

**Pull request closed without merging**
