### PR TITLE
yast2_apparmor: use ncurses instead of qt

### PR DESCRIPTION
**Pull request by paolostivanin**
- Related ticket: https://progress.opensuse.org/issues/116872
- Verification runs:
  - 15-SP5:
    - x86_64: https://openqa.suse.de/tests/9627981
    - ppc64le: https://openqa.suse.de/tests/9627906
  - 15-SP4: https://openqa.suse.de/tests/9627905
  - 15-SP3: https://openqa.suse.de/tests/9627905

### CODE REVIEW

**Review by punkioudi — APPROVED** [review]
Super, lgtm!

**Comment by paolostivanin** [comment]
thank you Anna!

**Review by jouyingbin — COMMENTED** [review]
LGTM. :)

**Comment by DimStar77** [comment]
Fallout: https://openqa.opensuse.org/tests/2766124

**Comment by paolostivanin** [comment]
arg, forgot o3! Sorry, I'll fix it right now

**Pull request merged**
