### PR TITLE
Update Lynis baseline for Tumbleweed aarch64

### PR DESCRIPTION
**Pull request by ggardet**
Some kernel modules are now blacklisted as on x86_64

### CODE REVIEW

**Comment by Vogtinator** [comment]
Looks good, just audit has a regression:

```
  * Audit daemon is enabled with an empty ruleset. Disable the daemon or define rules [ACCT-9630] 
      https://cisofy.com/lynis/controls/ACCT-9630/
```

Do you know what caused that?

**Comment by ggardet** [comment]
> Looks good, just audit has a regression:
> 
> ```
>   * Audit daemon is enabled with an empty ruleset. Disable the daemon or define rules [ACCT-9630] 
>       https://cisofy.com/lynis/controls/ACCT-9630/
> ```
> 
> Do you know what caused that?

Could be `/usr` merge?

**Comment by Vogtinator** [comment]
> > Looks good, just audit has a regression:
> > ```
> >   * Audit daemon is enabled with an empty ruleset. Disable the daemon or define rules [ACCT-9630] 
> >       https://cisofy.com/lynis/controls/ACCT-9630/
> > ```
> >
> > Do you know what caused that?
> 
> Could be `/usr` merge?

If so, would be a product bug: https://github.com/CISOfy/lynis/blob/4cfd59d60cd6f746a16ec3d6cb1e8f0c5b763508/include/tests_accounting#L183

**Comment by Vogtinator** [comment]
> > > Looks good, just audit has a regression:
> > > ```
> > >   * Audit daemon is enabled with an empty ruleset. Disable the daemon or define rules [ACCT-9630] 
> > >       https://cisofy.com/lynis/controls/ACCT-9630/
> > > ```
> > >
> > > Do you know what caused that?
> > 
> > 
> > Could be `/usr` merge?
> 
> If so, would be a product bug: https://github.com/CISOfy/lynis/blob/4cfd59d60cd6f746a16ec3d6cb1e8f0c5b763508/include/tests_accounting#L183

Reported as https://bugzilla.opensuse.org/show_bug.cgi?id=1191614#c2

**Comment by Vogtinator** [comment]
Audit issue got fixed and ignored by the openQA test anyway, so we can accept this.

CC @lilyeyes

**Pull request merged**
