### PR TITLE
PC-tool image dependecies update

### PR DESCRIPTION
**Pull request by m-dati**
The Public-cloud-tools image, used for PC testing, shall be updated with the last versions of the tools and dependecies needed by the cloud management CLIs. Here are the new resources list of the application installed with `pip for python3.6.`

- Related ticket in Progress site: [Upgrade all our tools to the latest version of PC tools image](https://progress.opensuse.org/issues/106658)
 
- Needles: none

- Verification run: TBD [will be provided soon]

### CODE REVIEW

**Comment by asmorodskyi** [comment]
LGTM

**Comment by m-dati** [comment]
To generate those 4 pip resources.txt dependecies files, a BCI pyhton:3.6 **container** has been used, built with a proper Dockerfile where in separated virtualenvs each of the 4 cloud-CLI has been installed using pip and finally the` pip freeze` list collected.

**Comment by pdostal** [comment]
> To generate those 4 pip resources.txt dependecies files, a BCI pyhton:3.6 **container** has been used, built with a proper Dockerfile where in separated virtualenvs each of the 4 cloud-CLI has been installed using pip and finally the` pip freeze` list collected.
This sounds cool! Do you want to document it? So the next time we don't need to invent it again?

I'd just put the Dockerfile and some instructions on the bottom of `prepare_tools.pm`

**Comment by m-dati** [comment]
> > To generate those 4 pip resources.txt dependecies files, a BCI pyhton:3.6 **container** has been used, built with a proper Dockerfile where in separated virtualenvs each of the 4 cloud-CLI has been installed using pip and finally the` pip freeze` list collected.
> > This sounds cool! Do you want to document it? So the next time we don't need to invent it again?
> 
> I'd just put the Dockerfile and some instructions on the bottom of `prepare_tools.pm`

Sure, if ok, I could put the Dockerfile in a proper new subfolder `pctools` in   `/var/lib/openqa/share/tests/opensuse/test_data/`: is it ok?

**Comment by pdostal** [comment]
I would put it to `/var/lib/openqa/share/tests/opensuse/data/publiccloud/venv/` and mention it in comment in `tests/publiccloud/prepare_tools.pm` :smile:

**Comment by m-dati** [comment]
Dockerfile and script added, still to do a better documentation

**Comment by m-dati** [comment]
Results of 10 Test executed as proof:

Test 			executed: | cloned 				from:
-- | --
1.http://marvin5.arch.suse.cz/tests/1122 				2.http://marvin5.arch.suse.cz/tests/1118 				3.http://marvin5.arch.suse.cz/tests/1114 				4.http://marvin5.arch.suse.cz/tests/1115 				5.http://marvin5.arch.suse.cz/tests/1116 				6.http://marvin5.arch.suse.cz/tests/1124 				7.http://marvin5.arch.suse.cz/tests/1123 				8.http://marvin5.arch.suse.cz/tests/1120 				9.http://marvin5.arch.suse.cz/tests/1121 				10.http://marvin5.arch.suse.cz/tests/1112 | https://openqa.suse.de/tests/9198148 				https://openqa.suse.de/tests/9198167 				https://openqa.suse.de/tests/9198176 				https://openqa.suse.de/tests/9198199 				https://openqa.suse.de/tests/9208340 				https://openqa.suse.de/tests/9244254 				https://openqa.suse.de/tests/9244258 				https://openqa.suse.de/tests/9246739 				https://openqa.suse.de/tests/9246751 				https://openqa.suse.de/tests/9246776
n.1 			FAIL in same *inotify11* 			part as cloned test, but not related to the pctools image update. 			Test repeated 2 times,same error |  
n.6 			and n.7 test needed build update,from build 1.73 of cloned test to 			this run in 1.79. Both tests PASS. |  
All 			other tests PASS or SOFT FAIL, same as the related cloned one. |

**Review by pdostal — APPROVED** [review]
Good job 🚀

**Comment by asmorodskyi** [comment]
From one side I don't have any questions to requirements update part it can be merged right away ( after I check the job which created the image ) . On other side Dockerfile and bash script raising quite some questions . What if we will split this two topics in separate PRs and merge one with requirements updates and will keep discussion about Dockerfile/bash script ?

Just to name a few questions : 
1. `data` folder is actually the place for files which uploaded to VM not some scripts which you meant to use on your local machine 
2. Looks like docker file not actually using requirements files directly but just listing same set of packages instead , which creates point of failure because you never sure if this lists is in sync

**Comment by m-dati** [comment]
The PR is updated with the only new updated resource files and is ready for merge

**Pull request merged**
