### PR TITLE
Set grub2 timeout to infinite

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://progress.opensuse.org/issues/129056
- Verification run: https://openqa.suse.de/tests/overview?build=grub2_timeout&distri=sle

### CODE REVIEW

**Comment by dzedro** [comment]
> Will it cover also SLE 12 installation ?

Ye, I noticed it when I was looking for VRs to run.

**Review by czerw — APPROVED** [review]
LGTM based on

- SLE 15 https://openqa.suse.de/tests/11087063#step/boot_to_desktop/1
- SLE 12 https://openqa.suse.de/tests/11087230#step/boot_to_desktop/1

**Review by rfan1 — COMMENTED** [review]
lgtm

**Comment by rfan1** [comment]
Thanks much for your quick fix!

**Pull request merged**
