### PR TITLE
Fix test for java 10, since the release date was added behind the ver…

### PR DESCRIPTION
**Pull request by DimStar77**
…sion number

Addresses https://bugzilla.opensuse.org/show_bug.cgi?id=1074036

### CODE REVIEW

**Comment by DimStar77** [comment]
It was filed as a bug as it was not clear if java exposes an invalid version or if the test needs to be updated - turned out, the test needed updating

As for java 9: yes; TW contains Java 8, Java 9 and Java 10, and the test runs all three versions in sequence, see : https://openqa.opensuse.org/tests/576405#step/java/14
( you see the various versions of java tested in sequence)

**Comment by drpaneas** [comment]
the tests is now passing

```
java-10-openjdk:
update-alternatives: using /usr/lib64/jvm/jre-10-openjdk/bin/java to provide /usr/bin/java (java) in manual mode
update-alternatives: using /usr/lib64/jvm/java-10-openjdk/bin/javac to provide /usr/bin/javac (javac) in manual mode
dot_verion=10-openjdk
dot_version_short=10
check linked java version: OK -> linked java is: 10-internal and language level is 10
dot_verion=10-openjdk
dot_version_short=10
check linked javac version: PASS
Java Compiler: PASS
Java runtime: PASS
```

LGTM

**Comment by rwx788** [comment]
@DimStar77 could you please shorten commit and PR title, e.g. "Fix java 10 version number parsing" and put current sentence to the description? I guess we also can resolve the bug. Thanks!

**Comment by DimStar77** [comment]
@rwx788 PR updated; once merged, I'll close the bug as fixed

**Pull request merged**
