### PR TITLE
Support public images on Azure: BYOS + PAYG

### PR DESCRIPTION
**Pull request by lilyeyes**
Support public images on Azure for mr_test: BYOS + PAYG
TEAM-7023 - Modify mr_test maintenance tests in ow15 to use Public OS Images - Azure

- Related ticket: https://jira.suse.com/browse/TEAM-7023
- Needles: NA
- Verification run:
Maintenance: SLE 15 SP4 SAP Incidents (all passed):
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP4&build=%3A27019%3Alibzypp&groupid=21
Maintenance: SLE 15 SP3 SAP Incidents (all passed):
     https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP3&build=%3A27019%3Alibzypp&groupid=22
Maintenance: SLE 15 SP2 SAP Incidents (all passed):
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP2&build=%3A27019%3Alibzypp&groupid=23
Maintenance: SLE 15 SP1 SAP Incidents (all passed):
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15-SP1&build=%3A27019%3Alibzypp&groupid=24
Maintenance: SLE 15 GA SAP Incidents (all failed on https://jira.suse.com/browse/TEAM-6949)
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=15&build=%3A27019%3Alibzypp&groupid=25
Maintenance: SLE 12 SP5 SAP Incidents (falied cases are as expected):
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=12-SP5&build=%3A27019%3Alibzypp&groupid=28
Maintenance: SLE 12 SP4 SAP Incidents (all failed on https://jira.suse.com/browse/TEAM-6949)	  
    https://openqaworker15.qa.suse.cz/tests/overview?distri=sle&version=12-SP4&build=%3A27019%3Alibzypp&groupid=29

### CODE REVIEW

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by lpalovsky** [comment]
Are the test using the PAYG images? I am not sure how to verify it.

**Comment by lilyeyes** [comment]
> Are the test using the PAYG images? I am not sure how to verify it.

Good question. 
Take 15sp4 for example: 

  for using BYOS public images I set:
            PUBLIC_CLOUD_AZURE_OFFER: 'sles-sap-15-sp4-byos'
            PUBLIC_CLOUD_AZURE_SKU: 'gen2'
            QESAP_CLUSTER_OS_VER: 'suse:sles-sap-15-sp4-byos:gen2:latest'

  for using PAYG public images I set (without the `byos`) :
            PUBLIC_CLOUD_AZURE_OFFER: 'sles-sap-15-sp4'
            PUBLIC_CLOUD_AZURE_SKU: 'gen2'
            QESAP_CLUSTER_OS_VER: 'suse:sles-sap-15-sp4:gen2:latest'

**Comment by lilyeyes** [comment]
> tfvars

If the image name contains keyword "byos" means it is a "BYOS" image, otherwise it is a "PAYG" image.
Am I right?

**Comment by alvarocarvajald** [comment]
> > tfvars
> 
> If the image name contains keyword "byos" means it is a "BYOS" image, otherwise it is a "PAYG" image. Am I right?

Exactly.

**Comment by lpalovsky** [comment]
@lilyeyes @alvarocarvajald AH ok I understand. Thanks for explanation and LGTM.

**Review by lpalovsky — APPROVED** [review]

**Comment by lilyeyes** [comment]
@lpalovsky It seems no more comments, please help to merge, thanks.

**Pull request merged**
