### PR TITLE
Rename cryptlvm+activate_existing* to activate_encrypted_volume

### PR DESCRIPTION
**Pull request by JRivrain**
See https://progress.opensuse.org/issues/77251

TODO: rename the test suites in openqa, update jobgroup (https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/329/diffs)

### CODE REVIEW

**Comment by jknphy** [comment]
we should consider some modification to console/validate_activation_encrypted_partition.pm as well in order to avoid this confusion with the used encrypted partition.

**Comment by JRivrain** [comment]
> we should consider some modification to console/validate_activation_encrypted_partition.pm as well in order to avoid this confusion with the used encrypted partition.

Renamed to validate_encrypted_volume_activation

**Review by rwx788 — APPROVED** [review]
LGTM

**Comment by rwx788** [comment]
I've checked openSUSE and we don't execute this test suite there, so it's safe.

**Comment by jknphy** [comment]
LGTM

**Pull request merged**
