### PR TITLE
Remove addon_products_via_SCC_yast2 and addon_products_yast2 modules which be used in the old installer

### PR DESCRIPTION
**Pull request by tinawang123**
Unify handling of addon proxy in the old installer

- Related ticket:  https://progress.opensuse.org/issues/136943
- Verification run:

### CODE REVIEW

**Review by rakoenig — APPROVED** [review]
LGTM

**Review by foursixnine — APPROVED** [review]
I have the feeling that these two are never used, but I'm not entirely sure... (@aaannz do you guys depend on either of these?)

**Comment by aaannz** [comment]
I checked the latest tests and it does not seem so. So feel free to remove if that is why you are asking.

**Review by lemon-suse — APPROVED** [review]

**Comment by lemon-suse** [comment]
Fingers in cross.

**Pull request merged**
