### PR TITLE
No need to type username in SLE11 KDE

### PR DESCRIPTION
**Pull request by dzedro**
Tested on SLE11
kde http://10.100.98.90/tests/328
gnome http://10.100.98.90/tests/329
SLE12
gnome http://10.100.98.90/tests/331

### CODE REVIEW

**Comment by coolo** [comment]
I just figure we don't have NOAUTOLOGIN tests for opensuse at all.
@nilxam are you aware of one?

**Comment by nilxam** [comment]
isnn't minimalx a NOAUTOLOGIN test?

**Comment by nilxam** [comment]
NOAUTOLOGIN still work, but in SLE11 it was always set_var("NOAUTOLOGIN", 1);, maybe you need the same thing like https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/main.pm#L130 for SLE11

**Comment by lnussel** [comment]
compare tests/installation/first_boot.pm. You need to check DM_NEEDS_USERNAME instead of GNOME.

**Pull request closed without merging**
