### PR TITLE
Rework yaml schedules for qdevice/qnetd tests

### PR DESCRIPTION
**Pull request by alvarocarvajald**
... so they do not depend on settings imported from a test suite.

Also add description for these schedules.

This will require changes on the job group configuration file. Configuration used in the development group was:

```
  x86_64:
    - ha_qdevice_node1:
        machine: x86_64
        testsuite: '-'
        settings: &qdevice_node
            CLUSTER_NAME: qdevice
            HA_CLUSTER_SETUP: init
            HA_CLUSTER_INIT: '1'
            HDD_1: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV.qcow2'
            HOSTNAME: '%CLUSTER_NAME%-node01'
            NICTYPE: tap
            PARALLEL_WITH: ha_supportserver_qdevice
            UEFI_PFLASH_VARS: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV-uefi-vars.qcow2'
            WORKER_CLASS: tap
            YAML_SCHEDULE: schedule/ha/bv/ha_qdevice_node.yaml
    - ha_qdevice_node2:
        machine: x86_64
        testsuite: '-'
        settings:
            <<: *qdevice_node
            HA_CLUSTER_SETUP: join
            HA_CLUSTER_INIT: '0'
            HA_CLUSTER_JOIN: '%CLUSTER_NAME%-node01'
            HOSTNAME: '%CLUSTER_NAME%-node02'
    - ha_qnetd_server:
        machine: x86_64
        testsuite: '-'
        settings: &qnetd_server
            CLUSTER_NAME: qdevice
            HDD_1: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV.qcow2'
            NICTYPE: tap
            PARALLEL_WITH: ha_supportserver_qdevice
            UEFI_PFLASH_VARS: '%DISTRI%-%VERSION%-%ARCH%-Build%BUILD%-HA-BV-uefi-vars.qcow2'
            WORKER_CLASS: tap
            YAML_SCHEDULE: schedule/ha/bv/ha_qnetd_server.yaml
    - ha_supportserver_qdevice:
        machine: x86_64
        testsuite: '-'
        settings: &qdevice_ss
            CLUSTER_INFOS: 'qdevice:%NUMDISKS%:%NUMLUNS%'
            HDD_1: 'openqa_support_server_sles12sp3.%ARCH%.qcow2'
            HDDMODEL: scsi-hd
            HDDSIZEGB_2: '6'
            NICTYPE: tap
            NUMDISKS: '2'
            NUMLUNS: '5'
            START_AFTER_TEST: create_hdd_ha_textmode
            SUPPORT_SERVER_ROLES: dhcp,dns,ntp,ssh,iscsi
            UEFI_PFLASH_VARS: 'openqa_support_server_sles12sp3.%ARCH%-uefi-vars.qcow2'
            WORKER_CLASS: tap
            YAML_SCHEDULE: schedule/ha/bv/ha_supportserver.yaml
    - ha_diskless_sbd_qdevice_node1:
        machine: x86_64
        testsuite: '-'
        settings: &qdevice_diskless_sbd_node
            <<: *qdevice_node
            CLUSTER_NAME: epsilon
            PARALLEL_WITH: ha_supportserver_qdevice_diskless_sbd
            TIMEOUT_SCALE: '2'
            USE_DISKLESS_SBD: '1'
    - ha_diskless_sbd_qdevice_node2:
        machine: x86_64
        testsuite: '-'
        settings:
            <<: *qdevice_diskless_sbd_node
            HA_CLUSTER_SETUP: join
            HA_CLUSTER_INIT: '0'
            HA_CLUSTER_JOIN: '%CLUSTER_NAME%-node01'
            HOSTNAME: '%CLUSTER_NAME%-node02'
    - ha_diskless_sbd_qnetd_server:
        machine: x86_64
        testsuite: '-'
        settings:
            <<: *qnetd_server
            CLUSTER_NAME: epsilon
            PARALLEL_WITH: ha_supportserver_qdevice_diskless_sbd
            TIMEOUT_SCALE: '2'
    - ha_supportserver_qdevice_diskless_sbd:
        machine: x86_64
        testsuite: '-'
        settings:
            <<: *qdevice_ss
            CLUSTER_INFOS: 'epsilon:%NUMDISKS%:%NUMLUNS%'
  aarch64:
    sle-15-SP3-Online-aarch64:
    - ha_qdevice_node1:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_node
    - ha_qdevice_node2:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_node
            HA_CLUSTER_SETUP: join
            HA_CLUSTER_INIT: '0'
            HA_CLUSTER_JOIN: '%CLUSTER_NAME%-node01'
            HOSTNAME: '%CLUSTER_NAME%-node02'
    - ha_qnetd_server:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qnetd_server
    - ha_supportserver_qdevice:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_ss
    - ha_diskless_sbd_qdevice_node1:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_diskless_sbd_node
    - ha_diskless_sbd_qdevice_node2:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_diskless_sbd_node
            HA_CLUSTER_SETUP: join
            HA_CLUSTER_INIT: '0'
            HA_CLUSTER_JOIN: '%CLUSTER_NAME%-node01'
            HOSTNAME: '%CLUSTER_NAME%-node02'
    - ha_diskless_sbd_qnetd_server:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qnetd_server
            CLUSTER_NAME: epsilon
            PARALLEL_WITH: ha_supportserver_qdevice_diskless_sbd
            TIMEOUT_SCALE: '2'
    - ha_supportserver_qdevice_diskless_sbd:
        machine: aarch64
        testsuite: '-'
        settings:
            <<: *qdevice_ss
            CLUSTER_INFOS: 'epsilon:%NUMDISKS%:%NUMLUNS%'
```

- Yaml Group Merge Request: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/255
- Related ticket: https://jira.suse.com/browse/TEAM-3446
- Needles: N/A
- Verification runs:

1. qdevice/qnetd on x86_64: http://mango.qa.suse.de/tests/3531, http://mango.qa.suse.de/tests/3532, http://mango.qa.suse.de/tests/3533, http://mango.qa.suse.de/tests/3534
2. diskless qdevice/qnetd on x86_64: http://mango.qa.suse.de/tests/3535, http://mango.qa.suse.de/tests/3536, http://mango.qa.suse.de/tests/3537, http://mango.qa.suse.de/tests/3538 (test failing due to bsc#1181415, not related to this PR)
3. qdevice/qnetd on aarch64: http://mango.qa.suse.de/tests/3539, http://mango.qa.suse.de/tests/3540, http://mango.qa.suse.de/tests/3541, http://mango.qa.suse.de/tests/3542
4. diskless qdevice/qnetd on aarch64: http://mango.qa.suse.de/tests/3543, http://mango.qa.suse.de/tests/3544, http://mango.qa.suse.de/tests/3545, http://mango.qa.suse.de/tests/3546 (test failing due to bsc#1181415, not related to this PR)

### CODE REVIEW

**Comment by juadk** [comment]
@ldevulder Good to know that we can share macros across arches.

**Review by juadk — COMMENTED** [review]
I think `ha_qdevice_node1.yaml `and `ha_qdevice_node2.yaml` can be merged in only one file but on the other hand, it will add complexity and some variables will have to be moved in the job group. So I'm fine with two files :smile:

**Comment by alvarocarvajald** [comment]
> I think `ha_qdevice_node1.yaml `and `ha_qdevice_node2.yaml` can be merged in only one file but on the other hand, it will add complexity and some variables will have to be moved in the job group. So I'm fine with two files

Yes, thought about it as well, but I think we can

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by juadk — APPROVED** [review]
LGTM

**Comment by alvarocarvajald** [comment]
> > I think `ha_qdevice_node1.yaml `and `ha_qdevice_node2.yaml` can be merged in only one file but on the other hand, it will add complexity and some variables will have to be moved in the job group. So I'm fine with two files
> 
> Yes, is matter of deciding where we would like to have the more complex configuration, in the schedule or in the yaml group. Since we have time, I'll try to see how complex it would be merging both schedules.

Consolidated both schedules for the cluster node in a single schedule.

Verification runs in:

qdevice@x86_64: http://mango.qa.suse.de/tests/3596, http://mango.qa.suse.de/tests/3597, http://mango.qa.suse.de/tests/3598 & http://mango.qa.suse.de/tests/3599
qdevice@aarch64: http://mango.qa.suse.de/tests/3592, http://mango.qa.suse.de/tests/3593, http://mango.qa.suse.de/tests/3594 & http://mango.qa.suse.de/tests/3595
diskless sbd/qdevice@x86_64: http://mango.qa.suse.de/tests/3584, http://mango.qa.suse.de/tests/3585, http://mango.qa.suse.de/tests/3586 & http://mango.qa.suse.de/tests/3587
diskless sbd/qdevice@aarch64: http://mango.qa.suse.de/tests/3588, http://mango.qa.suse.de/tests/3589, http://mango.qa.suse.de/tests/3590 & http://mango.qa.suse.de/tests/3591

As before, diskless sbd qdevice tests failures are due to bsc#1181415, not related to this PR.

Will push changes and update the description shortly.

**Review by ldevulder — APPROVED** [review]

**Pull request merged**
