### PR TITLE
Add module name to the upload file to avoid overwritten

### PR DESCRIPTION
**Pull request by nilxam**
main goal is add module name to the upload file to avoid overwritten.

### CODE REVIEW

**Comment by coolo** [comment]
LGTM

**Comment by aaannz** [comment]
I'm wondering, can't we do something like this on openqa side? Only instead of adding suffixes add prefix? Or introduce subdirs for uploaded logs?

**Comment by coolo** [comment]
subdirs appear overkill to me - but we could catch duplicated uploads and prefix then.

**Comment by nilxam** [comment]
yes and no. yes, we can doing that on server side. no, not just doing that against *duplicated" uploads but every uploads, otherwise you don't know where is the first file is generated from.

**Comment by nilxam** [comment]
hmm...I've rethink about this, it have to *made the change* in worker side than openqa side, since the uploaded files need to add prefix while uploading it to pooldir.

**Comment by coolo** [comment]
IMO it belongs here:

https://github.com/os-autoinst/os-autoinst/blob/master/commands.pm#L173

**Comment by nilxam** [comment]
Yes, that is the place where I talking about.

**Comment by nilxam** [comment]
handle this in upload_file https://github.com/os-autoinst/os-autoinst/pull/406

**Pull request closed without merging**
