### PR TITLE
Revert "Refactor reset_container_network_if_needed"

### PR DESCRIPTION
**Pull request by Vogtinator**
Reverts os-autoinst/os-autoinst-distri-opensuse#17527

It caused https://progress.opensuse.org/issues/133808

### CODE REVIEW

**Review by jlausuch — APPROVED** [review]

**Comment by mloviska** [comment]
Isn't the breaking commint this one ?
https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/7d46a0d9000594ad3cc72bd4d15ab8eee0315411

**Comment by Vogtinator** [comment]
> Isn't the breaking commit this one ? [7d46a0d](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/7d46a0d9000594ad3cc72bd4d15ab8eee0315411)

No, it was already broken before that commit: https://openqa.opensuse.org/tests/3479576

**Comment by mloviska** [comment]
> > Isn't the breaking commit this one ? [7d46a0d](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/7d46a0d9000594ad3cc72bd4d15ab8eee0315411)
> 
> No, it was already broken before that commit: https://openqa.opensuse.org/tests/3479576

Damn, this will break BCI tests though. Let's hope there won't be many builds over the weekend.

**Comment by Vogtinator** [comment]
We could also wait for a proper fix, if it won't take too long. For Leap I already tagged all failures appropriately and TW doesn't appear to be affected, so at least the current fallout isn't severe. WDYT?

**Comment by mloviska** [comment]
> We could also wait for a proper fix, if it won't take too long. For Leap I already tagged all failures appropriately and TW doesn't appear to be affected, so at least the current fallout isn't severe. WDYT?

I think reverting is a better solution for now, Felix is already out

**Pull request merged**
