### PR TITLE
use send_key_until_needlematch() instead of key_round()

### PR DESCRIPTION
**Pull request by nilxam**
require https://github.com/os-autoinst/os-autoinst/pull/268

### CODE REVIEW

**Comment by nilxam** [comment]
seems accepted it earlier than deploy updated os-autoinst to openqa.o.o

**Comment by sysrich** [comment]
yeah..I just had to do a hurried deploy to openqa.s.d

Lets try and co-ordinate merges that rely on modified testapi in the future
please :)

**Comment by lnussel** [comment]
ups. sorry

**Comment by nilxam** [comment]
don't worry, I've also deployed updated os-autoinst to openqa.o.o very early this morning :)

**Pull request merged**
