### PR TITLE
Add config files tests

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
+1, needs rebase

**Comment by asmorodskyi** [comment]
Commit is ready . 
Proof run : http://kimball.arch.suse.de/tests/358#step/wicked_basic/77

**Comment by asmorodskyi** [comment]
wicked_risky proof run - 
http://kimball.arch.suse.de/tests/374
http://kimball.arch.suse.de/tests/373

**Comment by DimStar77** [comment]
Not working on Tumbleweed: https://openqa.opensuse.org/tests/559721#step/wicked_basic/81

TW uses predictable network interface names

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4066 is the fix. it's in

**Pull request merged**
