### PR TITLE
toolkits: Explicitly set scaling factor to fix text rendering (boo#1137203)

### PR DESCRIPTION
**Pull request by okurz**
A problem is that depending on the virtual graphics adapter, e.g. in our case
aarch64, the X server reports a zero sized screen and consequently a
practically infinite screen resolution.

Tk uses this information to initialize the scaling factor for translating
between points and pixels which in turn is used for rendering fonts if their
size is specified in points. This value can be set explicitly with "tk scaling
1.0" to ensure a proper text rendering.

Verification run:

```
MARKDOWN=1 openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12856 https://openqa.opensuse.org/tests/1755968
```

* [opensuse-15.3-DVD-aarch64-Build160.3-toolkits@aarch64](https://openqa.opensuse.org/tests/1830492)

Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1137203

### CODE REVIEW

**Comment by okurz** [comment]
https://openqa.opensuse.org/t1830413 showed the text now correctly but with different scaling. Created new needle to cover the new rendering.

**Comment by okurz** [comment]
https://openqa.opensuse.org/tests/1830492#step/tk/9 shows the expected result

**Comment by Vogtinator** [comment]
IMO this needs to be addressed in X and/or QEMU, because invalid physical sizes mess with other applications as well.

**Comment by okurz** [comment]
yes, that would be nice. https://bugzilla.suse.com/show_bug.cgi?id=1137203#c29 explains that. I believe that we will just become frustrated convincing people that the "tk" test shows how the QXL video adapter yields an invalid screen dimension though. However we can still keep the bug https://bugzilla.suse.com/show_bug.cgi?id=1137203 about the actual issue. So, I see the test change as workaround for a bug that was not fixed over more than 2 years already so I don't expect it to be fixed anytime soon if at all anyway.

**Comment by asdil12** [comment]
This looks like something that should trigger a softfail.

**Review by asdil12 — APPROVED** [review]

**Pull request merged**
