### PR TITLE
Prepararing a webserver scenario

### PR DESCRIPTION
**Pull request by coolo**
Validation: https://tortuga.suse.de/tests/771

### CODE REVIEW

**Comment by okurz** [comment]
you might want to update https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Definition-of-DONE to state that these rules apply to everyone besides @coolo because he is the chosen one beyond rules, the true master of fixing sh*t, the holyness of "who does thingies, decides"

**Comment by coolo** [comment]
calm down, it was reviewed in IRC

**Comment by coolo** [comment]
And: seriously? you have a definition of done in the wiki?

**Comment by okurz** [comment]
sure, why not :-) http://www.goodreads.com/quotes/40705-but-the-plans-were-on-display-on-display-i-eventually

Where else would you expect it?

**Pull request merged**
