### PR TITLE
Reorder tests in load_extra_tests_kernel

### PR DESCRIPTION
**Pull request by pevik**
* Move module_build as the latests because it taints kernel
* Move BPF and io_uring to the top (the most important for SLE15, Tumbleweed)

Verification run: TODO

### CODE REVIEW

**Comment by czerw** [comment]
@pevik How is possible that it was merged without verification runs with `Verification run: TODO` ?!?  Please see https://openqa.suse.de/tests/11114594  what it breaks (folow-up tests are skipped).

**Comment by pevik** [comment]
@czerw I'm very sorry. It should be fixed by flags, I'll verify it and create PR:
```
sub test_flags {                                                        
    return {fatal => 0};                                                
}                                                                       
```

**Comment by pevik** [comment]
Hopefully fix of this: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17065

**Comment by czerw** [comment]
@pevik Thanks a lot for the quick fix!

**Pull request merged**
