### PR TITLE
Add SLE12SP4 to docker_image and increase some timeouts

### PR DESCRIPTION
**Pull request by pdostal**
The *SLE 12 SP 4 docker base image* is here so we need to test it:
 * Internal repository: `registry.suse.de/suse/sle-12-sp4/docker/update/cr/images/suse/sles12sp4:latest`
 * Public repository: `registry.suse.com/suse/sles12sp4:latest`

- Related ticket: [poo#36775](https://progress.opensuse.org/issues/36775)
- Needles: No need for those.
- Verification run: [SLE12SP4](http://pdostal-server.suse.cz/tests/481) [SLE15](http://pdostal-server.suse.cz/tests/483) [Leap15](http://pdostal-server.suse.cz/tests/489) [42.3](http://pdostal-server.suse.cz/tests/488) [Tumbleweed](http://pdostal-server.suse.cz/tests/491)

### CODE REVIEW

**Comment by Vogtinator** [comment]
Please only merge this after #6160.

**Comment by rwx788** [comment]
#6160 merged

**Comment by Vogtinator** [comment]
This will break Leap 15.1 testing!

```assert_script_run("docker pull $stable_names[$i]", 900);```

**Comment by foursixnine** [comment]
@pdostal please fix the commit message :) I'll merge afterwards

**Comment by Vogtinator** [comment]
>  I'll merge afterwards

I object as long as my commentl is not fixed.

**Comment by foursixnine** [comment]
> > I'll merge afterwards
> 
> I object as long as my comment is not fixed.

(actually, not anymore as the stable image exists now, but not using assert_script_run for that pull is intentional)

@Vogtinator I'm confused :) Can you clarify?

**Comment by Vogtinator** [comment]
> I'm confused :) Can you clarify?

The `assert_script_run("docker pull $stable_names[$i]")` was replaced with `if(script_run("docker pull $stable_names[$i]"))` to allow images to be tested *before* release.

This PR breaks that.

**Comment by pdostal** [comment]
I'm sorry about that, @Vogtinator, can you please check it now? The commit message is also fixed so @foursixnine if you both agree we can merge it I think.

**Comment by Vogtinator** [comment]
> I'm sorry about that, @Vogtinator, can you please check it now?

LGTM

**Comment by foursixnine** [comment]
Tidy :(

**Comment by dzedro** [comment]
:D

**Pull request merged**
