### PR TITLE
Schedule only relevant checks for remote_ssh_target_ftp

### PR DESCRIPTION
**Pull request by b10n1k**
+**console/validate_mirror_repos** validate the installation medium that used 
+ **console/textinfo** This does not run in any other module in YaST group jobs. Makes some sanity/smokes checks. Useful IMO
+ **console/firewall_enabled**  I found this only in one other test. i included to ensure that fwl is enabled as it should be but for testing sometimes we disable it
+ **console/sshd**               verifies that the ssh accepts connections
+ **console/sshd_running** verifies that the ssh is running after the installation

- Related ticket: https://progress.opensuse.org/issues/69199
- Verification run: 
Created job #4559164: sle-15-SP3-Online-x86_64-Build14.2-remote_ssh_controller@64bit -> https://openqa.suse.de/t4559164
Created job #4559165: sle-15-SP3-Online-x86_64-Build14.2-remote_ssh_target_ftp@64bit -> https://openqa.suse.de/t4559165

### CODE REVIEW

**Comment by JRivrain** [comment]
LGTM

**Comment by jknphy** [comment]
LGTM
@rwx788 I think ssh is covered well, but I'm not sure about ftp, we just check the mirror, but not that actually is working, although I didn't find any module which could do that, do we need another ticket or it is good enough, wdyt?

**Comment by rwx788** [comment]
> LGTM
> @rwx788 I think ssh is covered well, but I'm not sure about ftp, we just check the mirror, but not that actually is working, although I didn't find any module which could do that, do we need another ticket or it is good enough, wdyt?

@b10n1k Don't you mind to enable `zypper_ref` module? Because that will validate that all the added repos are valid.

**Comment by b10n1k** [comment]
> > LGTM
> > @rwx788 I think ssh is covered well, but I'm not sure about ftp, we just check the mirror, but not that actually is working, although I didn't find any module which could do that, do we need another ticket or it is good enough, wdyt?
> 
> @b10n1k Don't you mind to enable `zypper_ref` module? Because that will validate that all the added repos are valid.

sure

**Comment by b10n1k** [comment]
http://aquarius.suse.cz/tests/3119

**Pull request merged**
