### PR TITLE
FIPS installation with encrypted volume

### PR DESCRIPTION
**Pull request by rfan1**
Implement & Integrate LUKS test case into openQA
- Related ticket: https://progress.opensuse.org/issues/109163

- Verification run: 
http://openqa.suse.de/tests/8906171
http://openqa.suse.de/tests/8906497
http://openqa.suse.de/tests/8912867
http://openqa.suse.de/tests/8912868
http://openqa.suse.de/tests/8912869
http://openqa.suse.de/tests/8912870
http://openqa.suse.de/tests/8912871 [https://bugzilla.suse.com/show_bug.cgi?id=1200322 ]
http://openqa.suse.de/tests/8912897
http://openqa.suse.de/tests/8921605
http://openqa.suse.de/tests/8921612

### CODE REVIEW

**Review by wangqianzou — APPROVED** [review]
LGTM.
Just asked a question: if it's muti-path, how to configure boot?

**Comment by rfan1** [comment]
> LGTM. Just asked a question: if it's muti-path, how to configure boot?

AFAIK， no such requirement

**Review by Amrysliu — APPROVED** [review]

**Comment by jouyingbin** [comment]
@rfan1 
Would you please add some information for each of the VR? 

For exp. ,
http://openqa.suse.de/tests/8906171 (lvm-encrypt-separate-boot@64bit)
http://openqa.suse.de/tests/8906497 (lvm-full-encrypt@64bit)
http://openqa.suse.de/tests/8912867 (lvm-full-encrypt@ppc64le-hmc-single-disk)
...etc.

IMHO, it would be easier to review them from the beginning I see the PR, 
But I think it is not a big deal. 
:-) Thanks.

**Comment by rfan1** [comment]
> @rfan1 Would you please add some information for each of the VR?
> 
> For exp. , http://openqa.suse.de/tests/8906171 (lvm-encrypt-separate-boot@64bit) http://openqa.suse.de/tests/8906497 (lvm-full-encrypt@64bit) http://openqa.suse.de/tests/8912867 (lvm-full-encrypt@ppc64le-hmc-single-disk) ...etc.
> 
> IMHO, it would be easier to review them from the beginning I see the PR, But I think it is not a big deal. :-) Thanks.

I cloned other teams job, so not an easy to check the test result :(
I will try to trigger my own job next time

**Review by jouyingbin — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
