### PR TITLE
Add feature test case #1480297

### PR DESCRIPTION
**Pull request by QingmingSu**
Test Feature 318354: zypper: more advanced $releasever handling

### CODE REVIEW

**Comment by okurz** [comment]
looks good, do you have a reference to a working test run on a local machine which you can link or show a screenshot?

**Comment by QingmingSu** [comment]
Yeah, please refer to the test run for this case on my local host at: 
http://147.2.207.87/tests/326

**Comment by QingmingSu** [comment]
The screenshot of test results of this case is attached.
zypper_releasever

**Comment by okurz** [comment]
thank you

**Pull request merged**
