### PR TITLE
Remove openSUSE and staging portion from zypper_lr

### PR DESCRIPTION
**Pull request by mnowaksuse**
After all it seems that openSUSE and staging is not that important.It
brought problems which might not be fixed easily:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1495#issuecomment-237471579.
After suggestion from Max Lin (@nilxam)
(https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1636)
this change removes openSUSE and staging testing; including control.xml
validation code as it seems that SLE control.xml files do not include
repository information at all.

WIP, validation runs pending.

### CODE REVIEW

**Comment by nilxam** [comment]
I'd prefer move script_run "clear"; into if{} block. the rest looks good to me.

**Comment by mnowaksuse** [comment]
> I'd prefer move script_run "clear"; into if{} block. the rest looks good to me.

Done.

**Comment by mnowaksuse** [comment]
60some tests run, and passed: http://assam.suse.cz/tests.

**Comment by nilxam** [comment]
LGTM

**Pull request merged**
