### PR TITLE
Add apparmor profile apache changehat cases

### PR DESCRIPTION
**Pull request by lilyeyes**
Add apparmor profile "apache changehat" test cases.
NOTE:  
    This test case does not support running on Tumbleweed now, I will do it later as there are lots of
    issues/fails need to be investigated.

- Related ticket: https://progress.opensuse.org/issues/48773
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1107
- Verification run: http://10.67.19.89/tests/765    http://10.67.19.89/tests/771

### CODE REVIEW

**Comment by lemon-suse** [comment]
LGTM.

**Comment by jwbruno** [comment]
Hello, 
 The test does not run being properly on Maintenance SLE products. Could you please check this? It seems that it's missing some needles or so.

**Comment by lilyeyes** [comment]
> Hello,
> The test does not run being properly on Maintenance SLE products. Could you please check this? It seems that it's missing some needles or so.

Thank you for the reminder, the new added test case should be run in gnome environment, e

**Comment by DimStar77** [comment]
>  This test case does not support running on Tumbleweed now, I will do it later as there are lots of
issues/fails need to be investigated.

Might be a stupid question: but why was it enabled on tumbleweed then!?! https://openqa.opensuse.org/tests/898372#step/apache2_changehat/59

**Comment by lilyeyes** [comment]
> > This test case does not support running on Tumbleweed now, I will do it later as there are lots of
> > issues/fails need to be investigated.
> 
> Might be a stupid question: but why was it enabled on tumbleweed then!?! https://openqa.opensuse.org/tests/898372#step/apache2_changehat/59

Thanks for asking. It is really a good question.
I found no any switch to off/unload/not-run this test case on Tumbleweed so I just keep the test case and plan to fix the fail on Tumbleweed later.

**Pull request merged**
