### PR TITLE
Exclude non-existant WE on ppc64le and s390x

### PR DESCRIPTION
**Pull request by okurz**
See https://openqa.suse.de/tests/1154823#step/scc_registration/48

### CODE REVIEW

**Comment by okurz** [comment]
@DrMullings couldn't test it right now, if possible please take over, test it and then one can merge.

**Comment by DrMullings** [comment]
@okurz I have neither a ppc nor a s390x worker

**Comment by okurz** [comment]
I know, you could test it for x86_64 though

**Comment by DrMullings** [comment]
x86_64:
http://10.160.65.204/tests/628

**Comment by okurz** [comment]
Great, thx. The job didn't pass but the main.pm evaluated fine as can be seen in the uploaded vars.json so LGTM. I hope no one minds if I merge this now.

**Pull request merged**
