### PR TITLE
add yast_ftp_server.pm

### PR DESCRIPTION
**Pull request by skliu**
- Related ticket: https://progress.opensuse.org/issues/49271
- Needles: none
- Verification run:
  SLE12: http://10.67.20.133/tests/401
  SLE15: http://10.67.20.133/tests/402

### CODE REVIEW

**Comment by asdil12** [comment]
Please make sure to tidy the code using `./tools/tidy`

**Comment by asdil12** [comment]
The code looks good - your documentation is more than sufficient.

It might be a good idea to ensura that the ftp server is actually working, using the commandline tool `ftp` or `curl` and perform a test connection to the local ftp server.

**Comment by skliu** [comment]
> The code looks good - your documentation is more than sufficient.
> 
> It might be a good idea to ensura that the ftp server is actually working, using the commandline tool `ftp` or `curl` and perform a test connection to the local ftp server.

Hi, I use wget to check the ftp server working well. Please review it again.

**Comment by asdil12** [comment]
> > The code looks good - your documentation is more than sufficient.
> > It might be a good idea to ensura that the ftp server is actually working, using the commandline tool `ftp` or `curl` and perform a test connection to the local ftp server.
> 
> Hi, I use wget to check the ftp server working well. Please review it again.

Sorry - I overlooked that.

**Pull request merged**
