### PR TITLE
Update shortcuts for SLES 15-SP5

### PR DESCRIPTION
**Pull request by foursixnine**
Quck and dirty hack to try to get: https://progress.opensuse.org/issues/124347#note-3

Trying out:
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16366 https://openqa.suse.de/tests/10478712

Created job #10483482: sle-15-SP5-Online-x86_64-Build70.1-gi-guest_developing-on-host_developing-xen@64bit-ipmi-large-mem-intel -> https://openqa.suse.de/t10483482
Created job #10483534: sle-15-SP5-Online-ppc64le-Build70.1-create_hdd_textmode@ppc64le-spvm -> https://openqa.suse.de/t10483534

### CODE REVIEW

**Comment by Julie-CAO** [comment]
LGTM

**Comment by waynechen55** [comment]
After giving them a second look, I think might be https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16368 is better ?

Because the most specific one should be put at the last instead at the beginning, otherwise the other general ones will be overwritten. IMHO.

**Comment by jknphy** [comment]
LGTM, probably better than including 'i', which afik we don't know if it is useful.

**Comment by foursixnine** [comment]
Second round: 
- Created job #10499238: sle-15-SP5-Online-x86_64-Build72.1-create_hdd_textmode@64bit -> https://openqa.suse.de/t10499238
- Created job #10499244: sle-15-SP5-Online-ppc64le-Build72.1-create_hdd_textmode@ppc64le -> https://openqa.suse.de/t10499244

**Comment by waynechen55** [comment]
LGTM if all arch should use "s".

**Comment by Dawei-Pang** [comment]
LGTM, hope we can verify the changes with old release like 15-SP4, 15-SP3 and early, thanks!

**Comment by tjyrinki** [comment]
This would seem to indeed fix the disable_grub_timeout issue too, thank you!

**Comment by rfan1** [comment]
> This would seem to indeed fix the disable_grub_timeout issue too, thank you!

Yes, it can fix the issue https://bugzilla.suse.com/show_bug.cgi?id=1208266

**Comment by bs-suse** [comment]
I need this, please merge.
(closing https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16384)

**Comment by RoyCai7** [comment]
sle15sp5 72.1
UEFI: alt + t  [failed](https://openqa.suse.de/tests/10504713#step/disable_grub_timeout/45)
legacy: alt + r [passed](https://openqa.suse.de/tests/10504687)

**Comment by tjyrinki** [comment]
Indeed on uefi it still [fails](https://openqa.suse.de/tests/10505213#step/disable_grub_timeout/45)

**Pull request merged**
