### PR TITLE
Change to use full installer for sles15sp2

### PR DESCRIPTION
**Pull request by Julie-CAO**
we used <repo_0> repo for both host installation and guest installation prior to sles15sp1. But since sles15sp2, there are two type of installation. we use online image for host installation and full image for guest installation. So we change to use full installer repo.

the link of installer and modules both to be modified to use full installation.

@alice-suse @xguo @waynechen55

- Failing tests: https://openqa.nue.suse.com/tests/3638054
- Verification run for replacing the repos for installer and modules:
gi-guest_sles12sp5-on-host_developing-kvm   http://10.67.18.253/tests/1538
gi-guest_developing-on-host_sles12sp5-kvm   http://10.67.18.253/tests/1539#

### CODE REVIEW

**Comment by waynechen55** [comment]
Please help make sure do not mix up HOST VERSION and GUEST VERSION

**Comment by Julie-CAO** [comment]
> Please help make sure do not mix up HOST VERSION and GUEST VERSION

Thanks. changed to use the build version, rather than the host version or guest version.

**Comment by alice-suse** [comment]
@Julie-CAO @waynechen55 How about this PR? Agreed on the solution?

**Comment by waynechen55** [comment]
LGTM

**Comment by alice-suse** [comment]
LGTM

**Pull request merged**
