### PR TITLE
Fix vsftpd ls output assert

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
```diff
diff -r before/vsftpd/client/bin/04_NOSSL_listdirs_valid_users.sh after/vsftpd/client/bin/04_NOSSL_listdirs_valid_users.sh
30c30
<               diff /tmp/sshoutput /tmp/sshoutput
---
>               diff /tmp/ftpoutput /tmp/sshoutput
diff -r before/vsftpd/client/bin/04_SSL_listdirs_valid_users.sh after/vsftpd/client/bin/04_SSL_listdirs_valid_users.sh
30c30
<               diff /tmp/sshoutput /tmp/sshoutput
---
>               diff /tmp/ftpoutput /tmp/sshoutput
diff -r before/vsftpd/client/bin/05_NOSSL_listdirs_valid_users_chroot.sh after/vsftpd/client/bin/05_NOSSL_listdirs_valid_users_chroot.sh
41c41
<         diff /tmp/sshoutput /tmp/sshoutput
---
>         diff /tmp/ftpoutput /tmp/sshoutput
diff -r before/vsftpd/client/bin/05_SSL_listdirs_valid_users_chroot.sh after/vsftpd/client/bin/05_SSL_listdirs_valid_users_chroot.sh
41c41
<         diff /tmp/sshoutput /tmp/sshoutput
---
>         diff /tmp/ftpoutput /tmp/sshoutput
```

- Related tickets:
  - https://progress.opensuse.org/issues/73423
  - https://bugzilla.suse.com/show_bug.cgi?id=1181512

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
No idea what happened here: https://openqa.suse.de/tests/5358645#step/vsftpd/27

**Comment by SergioAtSUSE** [comment]
> No idea what happened here: https://openqa.suse.de/tests/5358645#step/vsftpd/27

Got it.

vsftpd.service failed to start with
```
Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Misleading by systemd https://github.com/systemd/systemd/blob/v219/src/shared/exit-status.h#L31 which expects https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html
```
2      invalid or excess argument(s)
```

which understood wrong the exit-code=2 from vsftpd, which shows the following output when executed manually
```
500 OOPS: config file not owned by correct user, or not a file
```

From `vsftpd/server/bin/setup_server.sh`
```
cp -a $suite/data/$1 /etc/vsftpd.conf
```

From man cp
```
-a, --archive
  same as -dR --preserve=all
...
--preserve[=ATTR_LIST]
  preserve the  specified  attributes  (default:  mode,ownership,timestamps),  if  possible  additional
  attributes: context, links, xattr, all
```

When I extracted the files, they got my local userID and were packed with it.

**Comment by SergioAtSUSE** [comment]
Finally, verification run: http://openqa.slindomansilla-vm.qa.suse.de/tests/2925#step/vsftpd/28
The failure is a product bug: https://bugzilla.suse.com/show_bug.cgi?id=1181512

**Review by dzedro — APPROVED** [review]

**Comment by dzedro** [comment]
Good catch :+1:, have been broken for so long. :roll_eyes:

**Pull request merged**
