### PR TITLE
prepare_tools: Adding requirements.txt for each virtual env

### PR DESCRIPTION
**Pull request by asmorodskyi**
VRs: 
http://autobot.qa.suse.de/tests/2322
.....
http://autobot.qa.suse.de/tests/2343
and all jobs between this range

### CODE REVIEW

**Comment by asmorodskyi** [comment]
still need to do some VRs but this is idea , WDYT ?

**Comment by grisu48** [comment]
> still need to do some VRs but this is idea , WDYT ?

I'm missing the bigger picture. Is this to put every publiccloud provider CLI into its own virtualenv?

**Comment by asmorodskyi** [comment]
> > still need to do some VRs but this is idea , WDYT ?
> 
> I'm missing the bigger picture. Is this to put every publiccloud provider CLI into its own virtualenv?

No because having every publiccloud provider CLI into its own virtualenv is current state already before this patch . Only thing which I am adding here is `requirements.txt` for each CLI so we can control which CLI (or only part of CLI) will get updates and which are not

**Review by pdostal — APPROVED** [review]
Looks nice to me 😄

**Review by cfconrad — APPROVED** [review]
LGTM

**Pull request merged**
