### PR TITLE
Change to use default size of dom0 ram since sles15sp1

### PR DESCRIPTION
**Pull request by Julie-CAO**
The original dom0_mem=4G did not work in one of the SUT,grenache-1:16, in OSD. The total memory account of this machine is only 4G. So we use the default size for all OS release with newer than sles15sp1(including sles15sp1, sles12sp5, sles15sp2 and etc), while passing dom0_mem=2G for other release on which the autoballooning is enabled by default during system installation.

- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1153713
- Verification run: 
http://10.67.18.182/tests/1212   gi-guest_developing-on-host_developing-xen
http://10.67.18.182/tests/1215  gi-guest_developing-on-host_sles15-xen
http://10.67.18.182/tests/1217  gi-guest_developing-on-host_sles12sp4-xen

@alice-suse @xguo @waynechen55

### CODE REVIEW

**Comment by alice-suse** [comment]
As we talked offline, please 
- add verification run on 15sp1 host(unit run at least)
- rephase comment to be more simplified
- add var for dom0_mem setting in the if else, then add the string to the executed cmd , will make code cleaner

Thanks.

**Comment by Julie-CAO** [comment]
rephrase the statement.
new verification run:
gi-guest_sles12sp4-on-host_developing-xen  http://10.67.20.201/tests/1232
gi-guest_developing-on-host_sles12sp4-xen http://10.67.20.201/tests/1225
have not had a successful sles15sp1 installation yet, unit test pass.

**Comment by Julie-CAO** [comment]
verified on sles15sp
gi-guest_developing-on-host_sles15sp1-xen http://10.67.20.201/tests/1238

**Comment by alice-suse** [comment]
LGTM. Thanks for the contribution.

**Pull request merged**
