### PR TITLE
Install aarch64 guests on SL Micro 6.1 aarch64 host

### PR DESCRIPTION
**Pull request by waynechen55**
* **Install** aarch64 guests, including SL Micro 6.1 from raw and qcow2 disk images and SLE 15-SP6 from medium repository, on SL Micro 6.1 aarch64 host.

* **New** guest profiles for aarch64:
  * sles_15_sp6_64_kvm_hvm_uefi_without_power_management_aarch64.xml
  * slm_6_1_64_kvm_hvm_aarch64_default_qcow_ignition+combustion.xml
  * slm_6_1_64_kvm_hvm_aarch64_default_raw_ignition+combustion.xml
  
* **New** guest autoyast template for aarch64:
  * sles_15_plus_kvm_hvm_guest_graphical_aarch64.xml
  
* **Add** ```sle-module-python3``` in guest autoyast template, otherwise registration will fail due to missing extension.

* **This** pull request can only be merged after verifying bsc#1229131. 

* **Verification Runs:** 
  * [uefi sles15sp6 on sles15sp6 kvm x86_64](https://openqa.suse.de/tests/15389392)
  * [uefi sles12sp5 on sles15sp6 xen x86_64](https://openqa.suse.de/tests/15389472)
  * [uefi sles15sp5 on sles15sp6 xen x86_64](https://openqa.suse.de/tests/15389489) 
  * [sl-micro 6.1 on sl-micro 6.1 aarch64](http://10.200.140.9/tests/61)
  * [sles15sp6 on sl-micro 6.1 aarch64](http://10.200.140.9/tests/60)
  * [uefi sles15sp7 on sles12sp5 kvm](https://openqa.suse.de/tests/15636480)
  * [uefi sles12sp5 on sles15sp7 xen](https://openqa.suse.de/tests/15636482)

### CODE REVIEW

**Comment by waynechen55** [comment]
@alice-suse @guoxuguang @Julie-CAO @RoyCai7 @nanzhg @tbaev Please have a look.

**Review by alice-suse — APPROVED** [review]
LGTM. Nice extension for aarch64!

It seems aarch64 guest installation does not need much automation code change. Hope it can be similar case for s390, except that some api calling would be different. Once the blocker bug is fixed (bsc#1229131), do you expect potential further PR, or everything will be likely to work just fine?

**Comment by waynechen55** [comment]
> LGTM. Nice extension for aarch64!
> 
> It seems aarch64 guest installation does not need much automation code change. Hope it can be similar case for s390, except that some api calling would be different. Once the blocker bug is fixed (bsc#1229131), do you expect potential further PR, or everything will be likely to work just fine?

* I need to do a successful verification run. If there are further changes, I think they are only related to guest files.
* All dependency for s390x is met. The difference are api calling and reboot behavior. Another story.

**Comment by waynechen55** [comment]
> > LGTM. Nice extension for aarch64!
> > It seems aarch64 guest installation does not need much automation code change. Hope it can be similar case for s390, except that some api calling would be different. Once the blocker bug is fixed (bsc#1229131), do you expect potential further PR, or everything will be likely to work just fine?
> 
>     * I need to do a successful verification run. If there are further changes, I think they are only related to guest files.
> 
>     * All dependency for s390x is met. The difference are api calling and reboot behavior. Another story.

Ready to be merged. @alice-suse

**Pull request merged**
