### PR TITLE
Ready up for the upcoming openldap update

### PR DESCRIPTION
**Pull request by HouzuoGuo**
Add new testing scenario ldap-no-auth; Alter configuration and binary path of openldap to accommodate for the upcoming openldap update.

Made for: https://build.opensuse.org/request/show/355264

### CODE REVIEW

**Comment by nilxam** [comment]
you have to fix https://build.opensuse.org/request/show/355264 first

**Comment by nilxam** [comment]
oh, and please leave the button to me, I'll merge this when the openldap2 update merged to Factory :)

**Comment by HouzuoGuo** [comment]
Here's the new factory submission:
https://build.opensuse.org/request/show/355757

**Comment by DimStar77** [comment]
@nilxam openldap2 has been merged on Jan 30

**Pull request merged**
