### PR TITLE
No touching virtproxyd daemon as it is not installed on modular libvirt

### PR DESCRIPTION
**Pull request by Julie-CAO**
- Not involve `virtproxyd` daemon as it is not installed on modular libvirt. Related ticket: https://progress.opensuse.org/issues/162881
- fix failure https://10.145.10.207/tests/14798677#step/sriov_network_card_pci_passthrough/208

Verification run: 
[gi-guest_sles12sp5-on-host_developing-xen](http://openqa.suse.de/tests/14809044)
[uefi-gi-guest_developing-on-host_developing-xen](https://10.145.10.207/tests/14809046)
[prj4_guest_upgrade_sles15sp5_on_sles15sp5-kvm](https://10.145.10.207/tests/14809047)
[prj2_host_upgrade_sles12sp5_to_developing_kvm](https://10.145.10.207/tests/14809045)
[fix_network_test_failure_in_sriov_test](https://10.145.10.207/tests/14800754#step/sriov_network_card_pci_passthrough/208)
[another_sriov_pass_on_quinn](https://10.145.10.207/tests/14809046#step/sriov_network_card_pci_passthrough/247)

### CODE REVIEW

**Comment by Julie-CAO** [comment]
@alice-suse @guoxuguang @waynechen55 @nanzhg @RoyCai7 @tbaev @martinsmarcelo Welcome review!

**Comment by waynechen55** [comment]
If it is not installed by default, I think you'd better check whether it exists before pushing instead of skipping pushing.

**Comment by Julie-CAO** [comment]
> * https://progress.opensuse.org/issues/162881

about detail, please check https://progress.opensuse.org/issues/162881.  on sle15sp5, it is at present but we need not touch it. on sle15sp6, it is not installed, we should not touch it.

**Comment by waynechen55** [comment]
> > * https://progress.opensuse.org/issues/162881
> 
> about detail, please check https://progress.opensuse.org/issues/162881. on sle15sp5, it is at present but we need not touch it. on sle15sp6/sle12sp5, it is not installed, we should not touch it.

I think you should check its availability before taking action.

**Comment by Julie-CAO** [comment]
> > > * https://progress.opensuse.org/issues/162881
> > 
> > 
> > about detail, please check https://progress.opensuse.org/issues/162881. on sle15sp5, it is at present but we need not touch it. on sle15sp6/sle12sp5, it is not installed, we should not touch it.
> 
> I think you should check its availability before taking action.

proxyd is not a package we need take special care of. Our test is to check if virtualization functions well. We need not know if it exists or not.

**Comment by alice-suse** [comment]
LGTM if answer is yes for https://progress.opensuse.org/issues/162881#note-7.

**Comment by guoxuguang** [comment]
> Are you sure libvirt-daemon-proxy is not installed by default ? Both on freshly installed system and upgraded system ? @Julie-CAO

@waynechen55 After performing a fresh installation of SLES15SP6 GM with KVM system role, verify that the libvirt-daemon-proxy package is not installed by default.

**Comment by Julie-CAO** [comment]
> Are you sure libvirt-daemon-proxy is not installed by default ? Both on freshly installed system and upgraded system ? @Julie-CAO

on which release are your asking ? 

The PR is to partiially fix http://10.100.103.93/tests/409#step/update_package/118.  `virtproxyd` is not present on sle16sp6.

> 
> I think on upgraded system from prior 15-SP6 to 15-SP6, libvirt-daemon-proxy will be installed ?

"upgraded system from prior 15-SP6 to 15-SP6", do you mean a registered sle16sp6 host? The failure I mentioned above is on this system.  Didn't you meet this failure when you run tests recently? this failure is blocking our tests, including Leon, Marcello and I.

**Comment by waynechen55** [comment]
> > Are you sure libvirt-daemon-proxy is not installed by default ? Both on freshly installed system and upgraded system ? @Julie-CAO
> 
> on which release are your asking ?
> 
> The PR is to partiially fix http://10.100.103.93/tests/409#step/update_package/118. `virtproxyd` is not present on sle16sp6.
> 
> > I think on upgraded system from prior 15-SP6 to 15-SP6, libvirt-daemon-proxy will be installed ?
> 
> "upgraded system from prior 15-SP6 to 15-SP6", do you mean a registered sle16sp6 host? The failure I mentioned above is on this system. Didn't you meet this failure when you run tests recently? this failure is blocking our tests, including Leon, Marcello and I.

For upgrade scenario, for example, 12-SP5 to 15-SP6, libvirt-daemon-proxy will be installed on upgraded 15-SP6 system ?

**Comment by Julie-CAO** [comment]
> For upgrade scenario, for example, 12-SP5 to 15-SP6, libvirt-daemon-proxy will be installed on upgraded 15-SP6 system ? I think libvirt-daemon-proxy is for backward compatibility with virt-manager, so in order to have no missing functionality after upgrade compared with prior to upgrade, libvirt-daemon-proxy should be installed on upgraded 15-SP6 system.

`virtproxyd` is not installed on sle12sp5, neither on sle5sp6, so I guess there should not be a `libvirt-daemon-proxy ` package being installed during upgrading procedures. There is a verfication run in this PR description, you are the expert of host upgrade tests, you may have a check.

**Comment by Julie-CAO** [comment]
>  I think libvirt-daemon-proxy is for backward compatibility with virt-manager, so in order to have no missing functionality after upgrade compared with prior to upgrade, libvirt-daemon-proxy should be installed on upgraded 15-SP6 system.

You are mainly talking about if it is a bug that `libvirt-daemon-proxy` is missing from sle12sp5->sle15sp6 scenario. Yes, it deserves a bug if the package is required.

in this case, we really shouldn't install this extra package in our test, or it would overlook a severe bug ---- missing a required package.

**Comment by waynechen55** [comment]
> > I think libvirt-daemon-proxy is for backward compatibility with virt-manager, so in order to have no missing functionality after upgrade compared with prior to upgrade, libvirt-daemon-proxy should be installed on upgraded 15-SP6 system.
> 
> You are mainly talking about if it is a bug that `libvirt-daemon-proxy` is missing from sle12sp5->sle15sp6 scenario. Yes, it deserves a bug if the package is required.
> 
> in this case, we really shouldn't install this extra package in our test, or it would overlook a severe bug ---- missing a required package.

I will have a look at upgrade scenario. 

By the way, virtproxyd is present on SL Micro 6.1:
```
host-1:~ # zypper info libvirt-daemon-proxy
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...


Information for package libvirt-daemon-proxy:
---------------------------------------------
Repository     : @System
Name           : libvirt-daemon-proxy
Version        : 10.0.0-slfo.1.2.2
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 756.1 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libvirt-10.0.0-slfo.1.2.2.src
Upstream URL   : https://libvirt.org/
Summary        : Server side daemon providing libvirtd proxy
Description    : 
    Server side daemon providing functionality previously provided by
    the monolithic libvirtd
host-1:~ # systemctl restart virtproxyd-ro.socket
host-1:~ # systemctl restart virtproxyd-admin.socket
host-1:~ # systemctl restart virtproxyd.service     
```

**Comment by waynechen55** [comment]
I can also confirm that after upgrading from 12-SP5 to 15-SP6, libvirt-daemon-proxy is installed on upgraded 15-SP6 system:

```
Information for package libvirt-daemon-proxy:
---------------------------------------------
Repository     : Server-Applications-Module 15.6-0
Name           : libvirt-daemon-proxy
Version        : 10.0.0-150600.6.2
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 716.2 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libvirt-10.0.0-150600.6.2.src
Upstream URL   : https://libvirt.org/
Summary        : Server side daemon providing libvirtd proxy
Description    : 
    Server side daemon providing functionality previously provided by
    the monolithic libvirtd

host:~ # systemctl restart virtproxyd-ro.socket
host:~ # systemctl restart virtproxyd-admin.socket
host:~ # systemctl restart virtproxyd.service
```

So, at least, virtproxyd is present on SL Micro 6.1 and upgraded 15-SP6 system, so you can not just removing it I think.

**Comment by Julie-CAO** [comment]
Ok, then no bug need to be opened.  

We are not going to remove proxyd from our tests. We just will not install it extra, and not touch it.

**Comment by guoxuguang** [comment]
> I can also confirm that after upgrading from 12-SP5 to 15-SP6, libvirt-daemon-proxy is installed on upgraded 15-SP6 system:
> 
> ```
> Information for package libvirt-daemon-proxy:
> ---------------------------------------------
> Repository     : Server-Applications-Module 15.6-0
> Name           : libvirt-daemon-proxy
> Version        : 10.0.0-150600.6.2
> Arch           : x86_64
> Vendor         : SUSE LLC <https://www.suse.com/>
> Support Level  : Level 3
> Installed Size : 716.2 KiB
> Installed      : Yes (automatically)
> Status         : up-to-date
> Source package : libvirt-10.0.0-150600.6.2.src
> Upstream URL   : https://libvirt.org/
> Summary        : Server side daemon providing libvirtd proxy
> Description    : 
>     Server side daemon providing functionality previously provided by
>     the monolithic libvirtd
> 
> host:~ # systemctl restart virtproxyd-ro.socket
> host:~ # systemctl restart virtproxyd-admin.socket
> host:~ # systemctl restart virtproxyd.service
> ```
> 
> So, at least, virtproxyd is present on SL Micro 6.1 and upgraded 15-SP6 system, so you can not just removing it I think.

Quick update, confirm that libvirt-daemon-proxy package was still installed after host upgrade from 15SP5 to 15SP6.
# zypper info libvirt-daemon-proxy
Refreshing service 'Basesystem_Module_15_SP6_s390x'.
Refreshing service 'Desktop_Applications_Module_15_SP6_s390x'.
Refreshing service 'Development_Tools_Module_15_SP6_s390x'.
Refreshing service 'Legacy_Module_15_SP6_s390x'.
Refreshing service 'Python_3_Module_15_SP6_s390x'.
Refreshing service 'SUSE_Linux_Enterprise_Server_15_SP6_s390x'.
Refreshing service 'SUSE_Package_Hub_15_SP6_s390x'.
Refreshing service 'Server_Applications_Module_15_SP6_s390x'.
Refreshing service 'Web_and_Scripting_Module_15_SP6_s390x'.
Loading repository data...
Reading installed packages...


Information for package libvirt-daemon-proxy:
---------------------------------------------
Repository     : SLE-Module-Server-Applications15-SP6-Updates
Name           : libvirt-daemon-proxy
Version        : 10.0.0-150600.8.6.2
Arch           : s390x
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 768.2 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libvirt-10.0.0-150600.8.6.2.src
Upstream URL   : https://libvirt.org/
Summary        : Server side daemon providing libvirtd proxy
Description    : 
    Server side daemon providing functionality previously provided by
    the monolithic libvirtd

Depending on the current situation, supposed that the behavior of the libvirt-daemon-proxy package can vary between a fresh host installation and a host upgrade.

**Comment by waynechen55** [comment]
I think operations on modular libvirt services should be refactored a little bit. 
```
1. Detect and record service existence 
2. If existence, do operation
3. If no existence, do nothing
```

**Comment by Julie-CAO** [comment]
The best solution is to configure all configuration files in autoyast profiles, then no services need to be restarted during tests, even we need not care about monilic libvirt or modular libvirt in most cases. it need a new ticket for this. but for now,  the failure is blocking our tests, I suggest to merge it firstly,  discuss for final solution and create a new ticket afterwards.

**Comment by waynechen55** [comment]
> The best solution is to configure all configuration files in autoyast profiles, then no services need to be restarted during tests, even we need not care about monilic libvirt or modular libvirt in most cases. it need a new ticket for this. but for now, the failure is blocking our tests, I suggest to merge it firstly, discuss for final solution and create a new ticket afterwards.

For new tickets/tasks:
1. autoyast work maybe
2. operation on modular libvirt should be refactored, otherwise exiting function is not complete and can not provide complete functionality. See [this comment](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19649#issuecomment-2216289299).

**Comment by alice-suse** [comment]
@Julie-CAO Hi Julie, would you please give some reply for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19649#issuecomment-2213038366 and a verification job for guest migration 15sp5->15sp6 kvm?

**Comment by Julie-CAO** [comment]
> @Julie-CAO Hi Julie, would you please give some reply for [#19649 (comment)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19649#issuecomment-2213038366) and a verification job for guest migration 15sp5->15sp6 kvm?

1. Whatever if it can communitcate between sle15sp6 & sle15sp5, it will not affect my PR. if it fails to communicate from sle15sp6 to sle15sp5, it is a product bug. If we install the extra `virtproxyd` in our automation test, this bug would be overlooked.
1. My pr will not take any effect to moduler libivirt or libvirtd, because the PR just does not restart `virtproxd`, no removing or installing. The package works well without restarting even if it exists, or not. It will not be help to verify this PR in your case.
2. OSD is having problem, in particular for a parallel job.

**Comment by alice-suse** [comment]
> > @Julie-CAO Hi Julie, would you please give some reply for [#19649 (comment)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19649#issuecomment-2213038366) and a verification job for guest migration 15sp5->15sp6 kvm?
> 
> 1. Whatever if it can communitcate between sle15sp6 & sle15sp5, it will not affect my PR. if it fails to communicate from sle15sp6 to sle15sp5, it is a product bug. If we install the extra `virtproxyd` in our automation test, this bug would be overlooked.

It seems you already have solid conclusion about the expected behavior for how sle15sp5 and sle15sp6 communicates with each other, especially that proxyd is not needed at all. Well, for me, I am not so sure... Maybe I overlook or misunderstand something. So I was expecting some verification to prove it.

Would you please share me the doc/link that lead you to that solid conclusion? I just want to make sure that merging of this won't fail anything else unexpectedly.

**Comment by Julie-CAO** [comment]
> > > @Julie-CAO Hi Julie, would you please give some reply for [#19649 (comment)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19649#issuecomment-2213038366) and a verification job for guest migration 15sp5->15sp6 kvm?
> > 
> > 
> > 
> > 1. Whatever if it can communitcate between sle15sp6 & sle15sp5, it will not affect my PR. if it fails to communicate from sle15sp6 to sle15sp5, it is a product bug. If we install the extra `virtproxyd` in our automation test, this bug would be overlooked.
> 
> It seems you already have solid conclusion about the expected behavior for how sle15sp5 and sle15sp6 communicates with each other, especially that proxyd is not needed at all. Well, for me, I am not so sure... Maybe I overlook or misunderstand something. So I was expecting some verification to prove it.
> 
> Would you please share me the doc/link that lead you to that solid conclusion? I just want to make sure that merging of this won't fail anything else unexpectedly.

I did not say virtproxyd is "not needed at all". I said "whatever virtproxyd is needed or not" is nothing to do with my PR. if it is needed but not installed, it is a product bug. My PR is what we should to detect the bug. 

And "I just want to make sure that merging of this won't fail anything else unexpectedly.", On the contrary, our tests are being blocked(see http://10.100.103.93/tests/409#step/update_package/118), my PR is to fix this failure and unblock our tests.

**Comment by guoxuguang** [comment]
There may be some misunderstandings here, let me explain.

1. Is it used with proxy daemons by default on 15SP6? 
No, In 15SP6 and newer, enable the modular daemons by default. Meanwhile, the modular daemons don't require libvirt-daemon-proxy.  So, it does not install libvirt-daemon-proxy package by default In 15SP6 and newer. 

2. Why do install libvirt-daemon-proxy. package upgrade to 15SP6 from 12+ or 15+. 
On hosts older than 15SP6, the libvirt-daemon package provides the monolithic libvirtd and virtproxyd. In 15SP6 and newer, virtproxyd has been split out into the libvirt-daemon-proxy package as part of jira PED-4804. For things to work properly on the upgrade, the new libvirt-daemon package must require libvirt-daemon-proxy. That's why libvirt-daemon-proxy package after the upgrade. In 15SP6 and newer, libvirt-daemon is not needed. We use the modular daemons libvirt-daemon-qemu and libvirt-daemon-xen

**Comment by Julie-CAO** [comment]
Trigger a sle15sp5 kvm -> sle15sp6 migration test with this PR to verify: http://openqa.suse.de/tests/14891879

No manual commands can be run as my Eng vpn is having problem.

And forward developer's words for your information:
```
Jim Fehlig
  5 months ago
virtproxyd is for back compat. It's needed when you have old clients, unaware of modular daemons, 
trying to connect to the old /run/libvirt/libvirtd-sock socket. 
Note that although the monolithic libvirtd is still default in SLE15 SP5, it is modular daemon aware. 
I.e, SLE15 SP5 and newer clients can connect to modular daemons without the need for virtproxyd
```

**Comment by alice-suse** [comment]
Based on https://progress.opensuse.org/issues/162881#note-10, I think it's fine to claim that 15sp5 is modular libvirt aware now, then no proxyd is needed. So it is safe to merge without the migration verification. Once issue happens on it(low chance), we can directly open bug for it.

Sorry for the holding and thanks for the work!

**Comment by Julie-CAO** [comment]
the verification run is still scheduing and has not begun to run yet, http://openqa.suse.de/tests/14891879   we have to see the result tomorrow. :disappointed:

**Comment by Julie-CAO** [comment]
> the verification run is still scheduing and has not begun to run yet, http://openqa.suse.de/tests/14891879 we have to see the result tomorrow. 😞

the tests are still queueing. I checked workers are idle but the tests have kept scheduled and not gotten assigned. Likely OSD has not worked well yet.

**Comment by Julie-CAO** [comment]
> > the verification run is still scheduing and has not begun to run yet, http://openqa.suse.de/tests/14891879 we have to see the result tomorrow. 😞
> 
> the tests are still queueing. I checked workers are idle but the tests have kept scheduled and not gotten assigned. Likely OSD has not functioned well yet.

Restart a test directly as the pr has merged, https://openqa.suse.de/tests/14911302, but still no luck. It keep scheduled. I have other non-parallel tests re-triggerd successfully.

**Comment by Julie-CAO** [comment]
> > > the verification run is still scheduing and has not begun to run yet, http://openqa.suse.de/tests/14891879 we have to see the result tomorrow. 😞
> > 
> > 
> > the tests are still queueing. I checked workers are idle but the tests have kept scheduled and not gotten assigned. Likely OSD has not functioned well yet.
> 
> Restarted a test directly as the pr has merged, https://openqa.suse.de/tests/14911302, but still no luck. It keep scheduled. I have other non-parallel tests re-triggerd successfully.

The tests sill have not gotten assigned. Since it is with low priority, I think we have to give up this verification for now. When OSD go back completely, I'll have another try; if the jobs still cannot be triggered at that time, I 'll look into the parallel jobs closely and request a fix from tools team.

**Comment by Julie-CAO** [comment]
> > > > the verification run is still scheduing and has not begun to run yet, http://openqa.suse.de/tests/14891879 we have to see the result tomorrow. 😞
> > > 
> > > 
> > > the tests are still queueing. I checked workers are idle but the tests have kept scheduled and not gotten assigned. Likely OSD has not functioned well yet.
> > 
> > 
> > Restarted a test directly as the pr has merged, https://openqa.suse.de/tests/14911302, but still no luck. It keep scheduled. I have other non-parallel tests re-triggerd successfully.
> 
> The tests sill have not gotten assigned. Since it is with low priority, I think we have to give up this verification for now. When OSD go back completely, I'll have another try; if the jobs still cannot be triggered at that time, I 'll look into the parallel jobs closely and request a fix from tools team.

I finanlly got a complete test, https://openqa.suse.de/tests/14975561

According the test result, we can think that guest migration from sle15sp5 host to sle15sp6 host  need not proxyd.

**Pull request merged**
