### PR TITLE
Allow multiple addons one-by-one in 15-SP2 Full medium

### PR DESCRIPTION
**Pull request by alvarocarvajald**
6f1a3650f8ca05946ea25b84742eb65a03bbad62 and 0e1862612 introduced changes to skip the Add On Product screen (addon-menu-active) when using SLES 15-SP2's Full medium, as the installer goes straight to the Extension and Module Selection screen during installations. However, while this screen is not shown initially to select the addons present in the Full medium, if one adds each addon one by one (for example, with ADDONS=base,serverapp,desktopapp,ha), the Add On Product screen is shown in each successive iteration. This PR introduces a workaround for such cases.

- Related ticket: N/A
- Failing tests: [x86_64](https://openqa.suse.de/tests/3666150), [s390x](https://openqa.suse.de/tests/3658071), [ppc64le](https://openqa.suse.de/tests/3658034) & [aarch64](https://openqa.suse.de/tests/3658014)
- Needles: N/A
- Verification run: [x86_64](http://mango.suse.de/tests/1951), [aarch64](https://openqa.suse.de/t3672036), [ppc64le](https://openqa.suse.de/t3672001) (failure in verification run is unrelated to this PR)

### CODE REVIEW

**Comment by ldevulder** [comment]
Hmm maybe an issue here: http://mango.suse.de/tests/1951#step/addon_products_sle/40, basesystem module appears 3 times.

**Comment by alvarocarvajald** [comment]
> Hmm maybe an issue here: http://mango.suse.de/tests/1951#step/addon_products_sle/40, basesystem module appears 3 times.

Don't think is an issue from this PR, but from the installer/media itself.

**Comment by alvarocarvajald** [comment]
> Maybe I don't fully understand the issue, but for me it looks wrong that we don't select all the modules on the first list and use another menu for it, in this run https://openqa.suse.de/tests/3672036#step/addon_products_sle/36 you end up with basesystem added 3 times as @ldevulder has already mentioned. It's being reported in https://bugzilla.suse.com/show_bug.cgi?id=1158431 and https://bugzilla.suse.com/show_bug.cgi?id=1158495

I don't think we've ever selected all the addons on the first screen, except when using the `all-packages` setting. Is this wrong? I don't know.

Judging by bsc#1158495 I'd say there's merit in testing this both ways.

> All modules are available on the first screen, so why not to select them all there? So I guess we need to fix it that we select the modules there, not sure why we press next.

Currently there's 2 methods to handle module selection within the test module:

- `handle_all_packages_medium` which selects all of the required modules in one go based on the contents of `%registration::SLE15_DEFAULT_MODULES` and on the value of `SLE_PRODUCT`.
- `handle_addon` which goes module by module.

The first approach does not work for HA, as the product is SLES with the HA extension. It does work for plain SLES, SLED or SLES for SAP Applications though.

The suggested change will require that we add a new method to handle several modules in one go (handle_addons? perhaps deciding with a new setting), or that we do some rewrites in `handle_addon` so that it is able to handle both a single addon or a list of addons. Keep in mind that currently the list of addons in `ADDONS` is split in `run()` and then `handle_addon()` gets called for each of the addons, so at first sight the changes could be more extensive than what's already in the PR. I will take a look at this approach during the day.

P.S.: Thanks for the information WRT the bugs.

**Comment by rwx788** [comment]
> > Maybe I don't fully understand the issue, but for me it looks wrong that we don't select all the modules on the first list and use another menu for it, in this run https://openqa.suse.de/tests/3672036#step/addon_products_sle/36 you end up with basesystem added 3 times as @ldevulder has already mentioned. It's being reported in https://bugzilla.suse.com/show_bug.cgi?id=1158431 and https://bugzilla.suse.com/show_bug.cgi?id=1158495
> 
> I don't think we've ever selected all the addons on the first screen, except when using the `all-packages` setting. Is this wrong? I don't know.
> 
> Judging by bsc#1158495 I'd say there's merit in testing this both ways.
> 
> > All modules are available on the first screen, so why not to select them all there? So I guess we need to fix it that we select the modules there, not sure why we press next.
> 
> Currently there's 2 methods to handle module selection within the test module:
> 
>     * `handle_all_packages_medium` which selects all of the required modules in one go based on the contents of `%registration::SLE15_DEFAULT_MODULES` and on the value of `SLE_PRODUCT`.
> 
>     * `handle_addon` which goes module by module.
> 
> 
> The first approach does not work for HA, as the product is SLES with the HA extension. It does work for plain SLES, SLED or SLES for SAP Applications though.
> 
> The suggested change will require that we add a new method to handle several modules in one go (handle_addons? perhaps deciding with a new setting), or that we do some rewrites in `handle_addon` so that it is able to handle both a single addon or a list of addons. Keep in mind that currently the list of addons in `ADDONS` is split in `run()` and then `handle_addon()` gets called for each of the addons, so at first sight the changes could be more extensive than what's already in the PR. I will take a look at this approach during the day.
> 
> P.S.: Thanks for the information WRT the bugs.

Thanks for the detailed explanation. I do understand urgency here, but I would try to make it right as this change not only makes thing wrong (adding same module 3 times), but also increases technical debt to fix it in the future. Obviously, it's not your fault that we have this code like this. But I would invest time in making it work in a less hacky way. Also, keep in mind that Full installer will get registration possible, which should help to test things without any changes to the code.

**Comment by alvarocarvajald** [comment]
> Thanks for the detailed explanation. I do understand urgency here, but I would try to make it right as this change not only makes thing wrong (adding same module 3 times), but also increases technical debt to fix it in the future. Obviously, it's not your fault that we have this code like this. But I would invest time in making it work in a less hacky way. Also, keep in mind that Full installer will get registration possible, which should help to test things without any changes to the code.

Turns out changes weren't that extensive.

Verification run: http://mango.suse.de/tests/1952

Will be pushing changes shortly.

**Comment by rwx788** [comment]
> > Thanks for the detailed explanation. I do understand urgency here, but I would try to make it right as this change not only makes thing wrong (adding same module 3 times), but also increases technical debt to fix it in the future. Obviously, it's not your fault that we have this code like this. But I would invest time in making it work in a less hacky way. Also, keep in mind that Full installer will get registration possible, which should help to test things without any changes to the code.
> 
> Turns out changes weren't that extensive.
> 
> Verification run: http://mango.suse.de/tests/1952
> 
> Will be pushing changes shortly.

That looks so much better! Thanks for the effort, very appreciated!

**Comment by mloviska** [comment]
Hi Alvaro!

Would you mind to check RT add-on installation, please? It seems like your PR broke addons handling in the installer.

https://openqa.suse.de/tests/3681717

Thanks!

**Comment by alvarocarvajald** [comment]
> Hi Alvaro!
> 
> Would you mind to check RT add-on installation, please? It seems like your PR broke addons handling in the installer.
> 
> https://openqa.suse.de/tests/3681717

Hello Martin,

Thank for the heads up. I'll take a look. Seems like a regression for 12-SP5 (and earlier) where we don't have a screen to select the addons from the media (as we don't have an a media with all addons).

**Comment by alvarocarvajald** [comment]
I think I know what's the problem. I'm testing a fix, and will submit a PR shortly.

**Comment by alvarocarvajald** [comment]
Fix in PR #9117.

**Pull request merged**
