### PR TITLE
Change conflict handling and add some features

### PR DESCRIPTION
**Pull request by dzedro**
https://confluence.suse.com/display/~dzedro/%5Bmaintenance%5D+update_install+test

- Verification run: https://openqa.suse.de/tests/overview?build=%3A32019%3AwxWidgets-3_2&groupid=490

### CODE REVIEW

**Comment by rfan1** [comment]
Commit message has a typo: Change conflict handling and add som features -> Change conflict handling and add some features

**Comment by rfan1** [comment]
One more minor comment, can we add a setting like "CONFLICT_PACKAGES" to add more if any?

**Comment by dzedro** [comment]
> One more minor comment, can we add a setting like "CONFLICT_PACKAGES" to add more if any? anyway, it is not hard required.

You mean with like with `UPDATE_ADD_CONFLICT` ?

**Comment by rfan1** [comment]
> > One more minor comment, can we add a setting like "CONFLICT_PACKAGES" to add more if any? anyway, it is not hard required.
> 
> You mean with like with `UPDATE_ADD_CONFLICT` ?

Yes!

**Pull request merged**
