### PR TITLE
Replace wait_supportserver by mutex_wait

### PR DESCRIPTION
**Pull request by kravciak**
@ldevulder please check

### CODE REVIEW

**Comment by okurz** [comment]
+1

@rwx788 I would say the motivation is that the abstraction does not scale because we have many more mutexes and having a method which just calls mutex_wait IMHO does not help anything here.

**Comment by kravciak** [comment]
@rwx788 since I made wait_supportserver into one-liner I don't think it brings any value to have it in utils anymore (in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4967/commits/98b3df6ddc42aa6da68c3816050b8220617f19b0#diff-141f4b5a48eaecb0c631a0de23e41a51R1221).

This way we could have `wait_dhcp`, `wait_dns`, `wait_***` in utils as well. But if it still has value for someone just tell me and I will close this PR.

**Comment by rwx788** [comment]
@kravciak no, I'm fine with that, just wanted to know if there is something I miss. In general finding wait_supportserver method with documentation is easier than checking corresponding mutex name. But as it's basically used only in bootloaders, I doubt that we will have new usages.

**Comment by ldevulder** [comment]
@kravciak, sorry I was off last week for vacation. I will have a look today even if it is already merged, because I have an issue with support-server waiting in the last tests: https://openqa.suse.de/tests/1681947#step/boot_to_desktop/2

**Pull request merged**
