### PR TITLE
Press alt-c when install button is ready

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
## Ticket

- https://progress.opensuse.org/issues/25464

## Verification run

- http://copland.arch.suse.de/tests/1508#step/change_desktop/1

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
Needle already there: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/commit/dccd7a249ce02933e163c1633f68e06dd21e4e48

**Comment by okurz** [comment]
I don't understand that. The ticket mentions https://openqa.suse.de/tests/1178990/modules/change_desktop/steps/1 as the first failing test and http://copland.arch.suse.de/tests/1508#step/change_desktop/1 does not look any different so I don't think you are waiting for an actual event that you check for. Of course the additional `assert_screen` call will take some time so it is less likely the button is pressed prematurely but I don't consider an additional assert_screen the right choice then. Could it be that we have a generic problem within the yast ncurses installer about reactivity on key presses and we should rather replace all send_key-calls with a helper function that internally waits 0.1 seconds and then presses the key?

**Comment by SergioAtSUSE** [comment]
@okurz, it is not the same:

- fail asserting screen because the menu is not open, because the keys were pressed when the menu was not yet ready: https://openqa.suse.de/tests/1178990/modules/change_desktop/steps/1
- menu is ready, than assert screen passes: http://copland.arch.suse.de/tests/1508#step/change_desktop/1

In the [video](https://openqa.suse.de/tests/1178990/file/video.ogv#t=29.30,31.00) you can see how the screen is for some seconds not ready (see the install button as the only reliable optical signal. Then asserting the screen is more human than simply waiting some time.

**Comment by okurz** [comment]
please update the needle for "installation-overview-loaded" instead which should be handle in installation_overview_before

**Comment by SergioAtSUSE** [comment]
- Usability bug: https://bugzilla.suse.com/show_bug.cgi?id=1060214
- Bug in test, wrong needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/500

**Pull request closed without merging**
