### PR TITLE
New test case which cover pdsh-gender plugin usage

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
+1

@Soulofdestiny ?

**Comment by Soulofdestiny** [comment]
based on my experience while developing those multimachine tests, I'd really like to see a verification run
@asmorodskyi let me know if you need help with this

**Comment by asmorodskyi** [comment]
http://kimball.arch.suse.de/tests/649#step/pdsh_slave/7
http://kimball.arch.suse.de/tests/648

run is failing , but they failing with expected reason . Package not yet reach SLE15.

**Comment by asmorodskyi** [comment]
http://kimball.arch.suse.de/tests/647
http://kimball.arch.suse.de/tests/646

this two runs of same module but without PDSH_GENDER_TEST=1 which proving that I not introduce regression at least

**Comment by asmorodskyi** [comment]
I plan to add this test anyway to monitor when package will appear actually in SLE15

**Comment by Soulofdestiny** [comment]
that's fine then
LGTM

**Pull request merged**
