### PR TITLE
Do not run k3s on s390x

### PR DESCRIPTION
**Pull request by pdostal**

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]

**Comment by grisu48** [comment]
Please provide a VR to avoid unintended side-effects, where `k3s` would be necessary

**Comment by mloviska** [comment]
We should exclude, `kubectl`, `podman_pods` and `run_container_in_k3s`. Even better would be to set k3s to last working version that has been published

**Comment by pdostal** [comment]
@mloviska Only `podman_pods` is running on s390x.

**Comment by mloviska** [comment]
> @mloviska Only `podman_pods` is running on s390x.

https://openqa.suse.de/tests/13057032
https://openqa.suse.de/tests/13055076

**Review by grisu48 — CHANGES_REQUESTED** [review]
Blocking this PR until clarification if we need to run the `kubectl` tests. Please stand by.

**Review by grisu48 — APPROVED** [review]
Unblocking it. `kubectl` is still tested elsewhere and we can skip this part for now. See also https://progress.opensuse.org/issues/152593

**Comment by pdostal** [comment]
I've created [poo#152596 - traefik is broken in k3s on s390x](https://progress.opensuse.org/issues/152596)

**Review by clanig — APPROVED** [review]

**Comment by ricardobranco777** [comment]
Shall we close this?

**Pull request closed without merging**
