### PR TITLE
[WIP] Cleanup main.pm a bit

### PR DESCRIPTION
**Pull request by okurz**
* Harmonize 'APPTESTS' based on openSUSE approach
* sle: Extract some test blocks into functions

### CODE REVIEW

**Comment by okurz** [comment]
@lnussel, @coolo do you know where `APPTESTS` is currently used if at all? maintenance tests? openSUSE, SLE?

**Comment by asmorodskyi** [comment]
please solve conflicts

**Comment by coolo** [comment]
APPTESTS is not used - it was meant for incident tests though. I convinced maintenance meanwhile though to run all tests all the time

**Comment by okurz** [comment]
thx. So maybe a better approach is to delete the openSUSE approach again and use something much more simple to trigger single test modules within a "default" test run, e.g. as additional steps after consoletest_setup and such.

**Comment by coolo** [comment]
well, no. For maintenance we have aged systems that we patch with one very specific incident and after *that* we want to run application tests. Doing default installations with patches is only covering so much. So do not remove it

**Comment by okurz** [comment]
I don't get it. You said it's not used. So you plan to use that approach in the near future? And if yes, are you referring to the openSUSE way or the SLE way?

**Comment by asmorodskyi** [comment]
@coolo , @okurz  - it's look like you didn't finish discussion here ...

**Pull request closed without merging**
