### PR TITLE
Windows 10 installation test module

### PR DESCRIPTION
**Pull request by dzedro**
modiffied (only win10 drivers) iso from https://fedoraproject.org/wiki/Windows_Virtio_Drivers is needed

Works only with CDMODEL=ide-cd

http://10.100.98.90/tests/2370

### CODE REVIEW

**Comment by dzedro** [comment]
I don't know if we want this also for SLE

**Comment by coolo** [comment]
the test as it's written is a one-off anyway - once we have the .qcow it doesn't matter what main.pm it used.

**Comment by dzedro** [comment]
I spoke with @sysrich SLES doesn't care about windows what is good I guess :P, but maybe SLED will care, I will try also SLED

**Comment by okurz** [comment]
please fix typo in commit message.

AFAIU the test was intended to work continuously so IMHO the testflow (i.e. `main.pm`) does matter.

**Comment by sysrich** [comment]
I'm not sure it makes sense to consider this test as a 'one-off' - Windows 10 is effectively a rolling release with regular updates - we will want a way of regularly upgrading the qcow with the latest state of Windows 10.

**Comment by dzedro** [comment]
typo fixed

**Comment by okurz** [comment]
LGTM

**Pull request merged**
