### PR TITLE
welcome: Use tab to highlight product instead of kb shortcut

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://progress.opensuse.org/issues/115376
- Needles: already created on osd
- Verification run:

https://openqa.suse.de/tests/10527113#step/welcome/11 x86_64
https://openqa.suse.de/tests/10527111#step/welcome/14 x86_64
https://openqa.suse.de/tests/10527226#step/welcome/11 ppc64le
https://openqa.suse.de/tests/10527176#step/welcome/11 x86_64

### CODE REVIEW

**Comment by foursixnine** [comment]
@emiura, @a-kpappas, I suggest you peeps move to libyui or switch to using autoyast for installations. cc @jknphy

**Review by emiura — APPROVED** [review]
LGTM!

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by jknphy** [comment]
we can take care of the installations with libyui-rest-api as far as they are basic which I think is the case. I will discuss that with Lee next meeting. Please, use AutoYaST as much as possible in the future.

**Pull request merged**
