### PR TITLE
add sle11_kde_setup.pm for KDE

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by sysrich** [comment]
Um, no, most certainly no - why are you changing the openSUSE main.pm for a SLE11 test?

The solution I tried to explain in #465 would only change the main.pm in the SLE11 branch to load the new 'sle11_kde_setup.pm' test

In the SLE11 main.pm I'd insert the line 'loadtest "x11/sle11_kde_setup.pm"' at around line 542, because you're basically changing the behaviour of the Alt-F2 launcher to setup KDE properly for all it's other tests

I'd then take lines 1-20 from your new sle11_yast2_users.pm and put them in sle11_kde_setup.pm.. that's the purpose of that test 'to fix kde's launcher for other X11 tests' - just because it's broken for the Yast2 Users test right now, doesn't mean it's the ONLY test that's going to be affected by the KDE behaviour you're working around :)

The reason I'm advocating this solution is I think it'll be a robust way of handling things if stuff like test execution order changes, or if we add new application tests that also aren't available in the 'find applications' feature.

I would not change yast2_users.pm or replace it with a sle11_* version. yast2_users.pm is 'correct' - we just need a little 'helper' to reconfigure the behaviour of the KDE launcher before we run any tests that aren't included in the 'find applications' search feature

Does this make sense?

**Comment by dzedro** [comment]
ah yes, sorry I misunderstood you :)

**Comment by nilxam** [comment]
if it touched krunner, I'd prefer put this pre-setup test to first step of kdesteps. What do you think?

**Comment by dzedro** [comment]
I did it like that first time, but for some reason yast2_users failed

http://10.100.98.90/tests/868

**Comment by nilxam** [comment]
that because the other test was failed before yast2_users test eg. firefox, then openqa loaded lastgood vm snapshot ie. in this case, the last good snapshot is created at consoletest_finish step, once it loaded, your changes in sle11_kde_setup just gone due to it was executed after of consoletest_finish step. sle11_kde_setup is important for following steps, so you need to add below to your sle11_kde_setup,

sub test_flags() {
    return { 'milestone' => 1 };
}

it will create a snapshot as lastgood if sle11_kde_setup test passed, I guess add them and try http://10.100.98.90/tests/868 again, you should get the result what you looking for originally. :)

**Comment by dzedro** [comment]
works, http://10.100.98.90/tests/883
thx Max, something new for me again :)

**Pull request merged**
