### PR TITLE
Give yast bootloader more time to finish

### PR DESCRIPTION
**Pull request by kravciak**
Should fix: https://openqa.suse.de/tests/611055#step/yast2_bootloader/5

### CODE REVIEW

**Comment by sysrich** [comment]
Have you discussed with the yast2-bootloader maintainer why it might take longer than 30 seconds to make the initrd?

I dont have any major objection to this PR, but it would seem to me we should at least have an idea as to whether or not it's okay it's taking so long sometimes

**Comment by coolo** [comment]
This got broken by 3e0260f0c95e34febb9432b35ed3f87dfd7cbd3e - it used to have 150 seconds timeout

**Comment by kravciak** [comment]
All yast tests have at least 60s to finish and openqa under load creating initrd - seems like good candidate for longer timeout to me.
It feels strange asking maintainer when openqa sometimes fails to start nautilus/gedit when under load (but I can do if you wish).

**Comment by coolo** [comment]
I opt for much longer timeout even in this case

**Comment by dzedro** [comment]
defafult timeout for wait_serial is 90, so you are going to decrease it :)
```
08:40:15.1810 9431 <<< testapi::wait_serial(regex='yast2-bootloader-status-0', timeout=90)
```

**Comment by kravciak** [comment]
so back to 150 seconds?

**Comment by coolo** [comment]
I'd say so

**Comment by kravciak** [comment]
Fixed

**Pull request merged**
