### PR TITLE
xfstests: subtest run could rollback

### PR DESCRIPTION
**Pull request by SeroSun**
This PR made the following changes
1. Benefit test review: Could see the test result for each subtest when it runs finished, no need to wait until all tests are done
2. Getting more stable: Could roll back to last good snapshot when test met crash
3. generate_report changes triggered by run.pm
4. Fix a minor mismatch issue when test fail

- Related ticket: https://progress.opensuse.org/issues/162884
- Verification run: 
- Heartbeat mode: http://10.67.133.133/tests/792
- Non-heartbeat mode: http://10.67.133.133/tests/793

More VR in testing products:
[SLE15SP7]
sle-15-SP7-Online-x86_64-Build18.1-xfstests_btrfs-generic-201-300@64bit-smp
https://openqa.suse.de/tests/15487314
[SLE-Micro6.1]
sle-micro-6.1-Default-x86_64-Build17.1-slmicro-xfstests_btrfs-generic-001-100@64bit-smp
https://openqa.suse.de/tests/15487308
 sle-micro-6.1-Default-aarch64-Build17.1-slmicro-xfstests_btrfs-generic-001-100@aarch64
https://openqa.suse.de/tests/15485746
[QAM-KOTD]
sle-15-SP5-Server-DVD-Incidents-Kernel-KOTD-x86_64-Build5.14.21-150500.509.1.gcc96d7e-qam-klp_xfstests_xfs@64bit
https://openqa.suse.de/tests/15461985
[QAM-KLP]
sle-15-SP6-Server-DVD-Incidents-Kernel-x86_64-Build:35773:kernel-livepatch-SLE15-SP6_Update_0-qam-klp_xfstests_btrfs@64bit
https://openqa.suse.de/tests/15487298

### CODE REVIEW

**Comment by SeroSun** [comment]
All test done, ready to merge

**Comment by SeroSun** [comment]
> We need, `test ranges` info, please add it back.

Thx Long, I add summary and test_range back. And run a new VR in SLMicro, please see https://openqa.suse.de/tests/15518118

**Comment by lansuse** [comment]
> > We need, `test ranges` info, please add it back.
> 
> Thx Long, I add summary and test_range back. And run a new VR in SLMicro, please see https://openqa.suse.de/tests/15518118

Cool! Then LGTM.

**Comment by asmorodskyi** [comment]
Hi @SeroSun  , this PR broke execution logic in Public Cloud . I want to kindly ask to ping us in case of changes like that . We trying to address the problem in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20319 can you please review this ?

**Comment by rbmarliere** [comment]
From what I see, [this one](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/products/opensuse/main.pm#L331) might still present an issue. I'm not sure if it's being actively scheduled, though.

**Pull request merged**
