### PR TITLE
autofs: Update summary with a more descriptive text

### PR DESCRIPTION
**Pull request by emiura**
For usage with https://confluence.suse.com/pages/viewpage.action?spaceKey=~martinsmac&title=Script+collecting+testcase+coverage

### CODE REVIEW

**Comment by okurz** [comment]
nit-pick: Please delete the dot at the end of line of the git commit subject line

**Comment by okurz** [comment]
I think your extension of the description is a good idea however I doubt that with this much details it will be long-term sustainable. The test code will change and be invalid sooner or later. The source code of openQA tests was always intended to be easily readable so maybe not that much detail would be necessary but just a link to the source code?

**Comment by emiura** [comment]
@okurz That's not my initiative, but rather my manager asked to do this. The goal is to somehow understand what is being covered by the tests and fill the gaps on the testing. There's another tool that compiles the summaries on a page, so people can see what's being tested.
Maybe I can forward you the mails my manager sent to the team.

**Comment by okurz** [comment]
> @okurz That's not my initiative, but rather my manager asked to do this

Yes, I am even aware about this but I am sure your manager trusts you to decide how much detail goes into the description :) And I guess anyone would be happy to see suggestions to the script. I myself unfortunately don't know where it lives :)

**Comment by emiura** [comment]
@okurz I think they would be more than happy to accept some suggestion. The script is on the url from my commit: https://confluence.suse.com/pages/viewpage.action?spaceKey=~martinsmac&title=Script+collecting+testcase+coverage

**Comment by okurz** [comment]
thx!

**Comment by okurz** [comment]
in any case, ok like it is for now

**Pull request merged**
