### PR TITLE
Workaround the 'shift is pressed after a start from snapshot' by pres…

### PR DESCRIPTION
**Pull request by sysrich**
…sing the A key and deleting it

This is Denis' idea, and I liked it, so here it is

### CODE REVIEW

**Comment by nilxam** [comment]
yeah, why not, I'd say give it a try :)

**Comment by nilxam** [comment]
oh, btw just for a record, I tried 3 different way debugging this issue this week, but fails to find the root cause,

1) input some words end of post_fail_hook() while x11 test: didn't seen uppercase there
2) send_key("backspace") in x11_start_program before type $program: doesn't help, sometimes the capital letter is uppercase
3) send_key("shift") in x11_start_program before type $program: doesn't help, sometimes the capital letter is uppercase

2) and 3) sounds not really make sense though, since "alt-f2" sent before...

**Comment by nilxam** [comment]
after discuss with @DimStar77 , I'll merge it for now and give it a try...

**Comment by nilxam** [comment]
looks it's not perfect :)
https://openqa.opensuse.org/tests/65206/modules/yast2_users/steps/4

**Comment by sysrich** [comment]
Looks like it needs a sleep after typing A. You could poke Denis (dzyuin or
there about) in SUSE IRC - its his idea, he might be willing and able to
fix it :)

**Comment by nilxam** [comment]
I've an "enhanced workaround" https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/468
what do you think about it? want to give it a try? :)

**Comment by sysrich** [comment]
I like the approach (its crazy, but I like crazy), but it looks like Travis
disagrees atm

**Comment by nilxam** [comment]
pffff...missing a "if", fixed.

**Pull request merged**
