### PR TITLE
Test firewalld timeout

### PR DESCRIPTION
**Pull request by pdostal**
- Related ticket: [poo#120955](https://progress.opensuse.org/issues/120955)
- Verification run: [mau-extratests1@64bit](https://pdostal-server.suse.cz/tests/3169)

### CODE REVIEW

**Comment by foursixnine** [comment]
maybe also upload `/tmp/nr_rules.txt`?

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/2907539#step/firewalld/157 ??

**Comment by Zaoliang** [comment]
> https://openqa.opensuse.org/tests/2907539#step/firewalld/157 ??

yes, this is an issue which should be resolved asap because it blacks further tests, see https://openqa.suse.de/tests/10050783#

**Comment by pdostal** [comment]
> > https://openqa.opensuse.org/tests/2907539#step/firewalld/157 ??
> 
> yes, this is an issue which should be resolved asap because it blacks further tests, see https://openqa.suse.de/tests/10050783#

This has been resolved yesterday.

**Pull request merged**
