### PR TITLE
adapt main sles11 for Livecdreboot PR 1007

### PR DESCRIPTION
**Pull request by MalloZup**
Rename and tidy livecdreboot.
Grub code is now on grub_test.pm

### CODE REVIEW

**Comment by MalloZup** [comment]
so,  an issue on cpanm ?

0.07s$ cpanm -nq `cat os-autoinst/DEPENDENCIES.txt`

cat: os-autoinst/DEPENDENCIES.txt: No such file or directory

Usage: cpanm [options] Module [...]

**Comment by aaannz** [comment]
It's just that no one updated sle11 branch `.travis.yml`. We now use `cpanfile` instead of `DEPENDENCIES.txt`, See [SLE12 branch .travis.yml](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/sle12/.travis.yml#L12)

**Comment by coolo** [comment]
note that sle12 is outdated too - okurz moved to Makefile logic

**Comment by aaannz** [comment]
Hmm, I don't follow. cpan is still installed explicitly in `.travis.yml` even in os-autoinst [see](https://github.com/os-autoinst/os-autoinst/blob/master/.travis.yml#L9). Or do you mean something else?

**Pull request merged**
