### PR TITLE
Allow boot into console

### PR DESCRIPTION
**Pull request by yxususe**
In order to proceed with test described in the ticket:
https://progress.opensuse.org/issues/19566

### CODE REVIEW

**Comment by okurz** [comment]
`wait_boot` in line https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3628/files#diff-16208615c5a1a0bcba7e33c6d6a68020R418 already supports looking for the textmode. I don't think we should extend the "GUI-part" in the same way.

**Comment by yxususe** [comment]
Can you check if the needles emergency-shell emergency-mode are there?

**Comment by okurz** [comment]
I'm not sure I understand your question. os-autoinst-needles-sles lists

```
$ git ls-files "*emergency*"
online_migration_setup-emergency-shell-20170201.json
online_migration_setup-emergency-shell-20170201.png
online_migration_setup-emergency-shell-20170330.json
online_migration_setup-emergency-shell-20170330.png
snapper-emergency-shell-20170620.json
snapper-emergency-shell-20170620.png
snapper-emergency-shell-20170918.json
snapper-emergency-shell-20170918.png
```

so … yes?

**Comment by yxususe** [comment]
OK. However those emergency-shell needles (and there's no emergency-mode) are different as needle linux-login, which is the normal tty1(or tty2...) login, and this we still need.

**Comment by okurz** [comment]
I don't think I fully understand, better we talk about it in a daily meeting, ok?

**Comment by okurz** [comment]
I think we found a common understanding that we don't need this because what we were missing was basically a missing "DESKTOP=textmode" setting on the test.

**Pull request closed without merging**
