### PR TITLE
svirt: Use telnet from worker host to SUT to verify it's up

### PR DESCRIPTION
**Pull request by coolo**
to avoid https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/5099, I'm proposing this

Validation: http://tortuga.suse.de/tests/221#step/boot_to_desktop/23

### CODE REVIEW

**Comment by okurz** [comment]
I had a code change prepared to probe the ssh port using nc from the hypervisor host but haven't prepared a PR so far

**Comment by coolo** [comment]
I could only verify it works if the SUT comes up - how the failure condition would look like is to be seen

**Comment by okurz** [comment]
Alternative: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/5112 Which one you like more?

I also could not reproduce the failure with the workaround not in place but 800 runs were fine in a row in both cases, with my new workaround or none at all.

**Comment by okurz** [comment]
Ok, @Soulofdestiny and me like this approach, let's try it out

**Pull request merged**
