### PR TITLE
ImageMagick test

### PR DESCRIPTION
**Pull request by rwmanos**
This test creates, displays, and evaluates 200+ images utilizing
various convertion options of ImageMagick.

The examined examples were taken from:
https://www.imagemagick.org/Usage/canvas/ (Aug 2016)

A set of preloaded images and a script are required as input. This
test generates multiple new images and evaluates the output. Some
of the new images are converted from the preloaded images, while
others are drawn from scratch. The preloaded script contains all
the executed commands because typing them appeared to be extremely
time-consuming (more than two hours in a specific case, while this
test can finish in less than 20 minutes).

### CODE REVIEW

**Comment by rwmanos** [comment]
Working example: http://rwmanosvm2.suse.cz/tests/460

**Comment by Soulofdestiny** [comment]
please use tools/tidy from the os-autoinst repo and update your pr ;)

**Comment by rwmanos** [comment]
Soulofdestiny: Thanks for the info. I fixed it.

Regarding the pull request, I haven't modified the main.pm. I guess such a modification should be done by someone more experienced than me. In case you find this test interesting, it can be part of the x11regressions but with conditions. For the record, ImageMagick is part of the SDK and the test works only for GNOME (uses eog).

**Comment by sysrich** [comment]
+1 to this PR, but I would like to see it merged only when there is an appropriate main.pm commit also.

@rwmanos I think I'd like to see you try to do the main.pm change, and then squash the commits so we see it all as 'Add ImageMagick test' - do you think that's possible?

**Comment by Soulofdestiny** [comment]
lgtm :+1:

**Comment by rwmanos** [comment]
Hi Richard, I squashed the commits and modified the main.pm. I didn't write earlier because I wanted to look it again (since it's my first edit to main.pm) and get some feedback. However, I'm happy that my edits were acceptable and the commit was merged :)

**Comment by coolo** [comment]
you need to cleanup - you are breaking following tests: https://openqa.suse.de/tests/623959#step/nautilus/4

**Comment by rwmanos** [comment]
@coolo sorry I should have foreseen that. Fixed in #2040 .

**Pull request merged**
