### PR TITLE
autoupgrade part added in order to initialize the autoupgrade test

### PR DESCRIPTION
**Pull request by razghe**
Autoupgrade part added in order to initialize the autoupgrade. extra ifcfg parameter added for dhcp functionallity.

### CODE REVIEW

**Comment by sysrich** [comment]
Wouldnt it make sense to use the "$netsetup" stuff from the if AUTOYAST block starting at line 235?

Maybe it should look something like this to replace this commit and lines 235-242

    if ( get_var("AUTOYAST") || get_var("AUTOUPGRADE")) {
            my $netsetup = " ifcfg=*=dhcp"; #need this instead of netsetup as default, see bsc#932692
            $netsetup = " ".get_var("NETWORK_INIT_PARAM") if defined get_var("NETWORK_INIT_PARAM"); #e.g netsetup=dhcp,all
            $netsetup = " netsetup=dhcp,all" if defined get_var("USE_NETSETUP"); #netsetup override for sle11
    }

    if ( get_var("AUTOYAST")) {
        $args .= $netsetup;
        $args .= " autoyast=" . autoinst_url . "/data/" . get_var("AUTOYAST") . " ";
    }

    if ( get_var("AUTOUPGRADE)) {
         $args .= $netsetup;
         $args .= " autoupgrade=1";
    }

    type_string $args,13

**Comment by razghe** [comment]
I tried to run the code on my local openqa, I think that $args .= $netsetup; needs to be in the same if else statement where netsetup variable is declared. 

Failed test:
  http://10.100.103.118/tests/521/file/autoinst-log.txt
Error message:
  error on tests/installation/bootloader.pm: Global symbol "$netsetup" requires explicit package name at /var/lib/openqa/share/tests/sle12/tests/installation/bootloader.pm line 242.

I modified a bit the code to this:

235 
    if ( get_var("AUTOYAST") || get_var("AUTOUPGRADE")) {
        my $netsetup = " ifcfg=*=dhcp"; #need this instead of netsetup as default, see bsc#932692
        $netsetup = " ".get_var("NETWORK_INIT_PARAM") if defined get_var("NETWORK_INIT_PARAM"); #e.g netsetup=dhcp,all
        $netsetup = " netsetup=dhcp,all" if defined get_var("USE_NETSETUP"); #netsetup override for sle11
        $args .= $netsetup;
        $args .= " autoyast=" . autoinst_url . "/data/" . get_var("AUTOYAST") . " ";
    }

    if ( get_var("AUTOUPGRADE")) {
        $args .= " autoupgrade=1";
    }

    type_string $args, 13;
    save_screenshot;
253 

Everything is working ok, with fixed handling of the dhcp parameter, ifcfg=*=dhcp

http://10.100.103.118/tests/518

Do you agree with the modif?

**Comment by sysrich** [comment]
$args .= " autoyast=" . autoinst_url . "/data/" . get_var("AUTOYAST") . " ";

Isn't this going to put a whole bunch of autoyast junk before your autoupgrade all the time? or am I misunderstanding something?

**Comment by razghe** [comment]
Yes, it is loading the autoyast file from the data directory, because the autoyast parameter is set in the test suite. autoupgrade works together with autoyast, besides the autoyast and network "junk"  it will type autoupgrade=1.

**Pull request merged**
