### PR TITLE
Fix product shortcuts for SLE 15 SP5

### PR DESCRIPTION
**Pull request by rakoenig**
- Related ticket: https://progress.opensuse.org/issues/124347
- Needles: 
- Verification run: https://openqa.suse.de/tests/10483450

### CODE REVIEW

**Comment by waynechen55** [comment]
LGTM. Not sure whether https://bugzilla.suse.com/show_bug.cgi?id=1208180 should be taken into consideration.

**Review by alice-suse — APPROVED** [review]
Given the big impact of this issue to virtualization, merge it now. Thanks for the fix.

**Comment by tjyrinki** [comment]
Thanks a lot for this fix!

**Comment by foursixnine** [comment]
Looks like we'll have to go in the end with: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16366 as https://openqa.suse.de/tests/10495207 still fails with the same problem

**Comment by Dawei-Pang** [comment]
The MR only fixes x86_64 but ppc64le: http://10.67.129.4/tests/55802#step/welcome/6

**Pull request merged**
