### PR TITLE
Check disk usage widget for not showing subvolumes (bsc#949945)

### PR DESCRIPTION
**Pull request by cwh42**
Needles in:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/57

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

notice to merger: the "send_key" with ",1" is subject to change according to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/997

**Comment by cwh42** [comment]
Will the API for send_key change? Or is it just to get rid of unwanted delays?
It would be actually useful to get millisecond brakes here, since without at least a tiny delay some keypresses often get lost.

**Comment by okurz** [comment]
**first** avoid "wait_idle" and explicit "sleeps" as they are not portable or consistent when running tests on qemu as well as physical machines and such and **then** maybe change api to get rid of these (or mark deprecated)

**Comment by coolo** [comment]
interrupt the send_keys with wait_still_screen; the ,1 is not a "tiny delay" - it's a wait between 3 and 19 seconds. If you can't assert_screen, then wait for something else than time.

**Comment by cwh42** [comment]
Ok - using ```wait_still_screen``` now.

**Comment by coolo** [comment]
https://openqa.suse.de/tests/195545/modules/yast2_i/steps/8 - what's a correct needle?

**Comment by cwh42** [comment]
@coolo This one https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/48

**Pull request merged**
