### PR TITLE
Add glibc test suite

### PR DESCRIPTION
**Pull request by eisfuchs-de**
The test will soft fail if the glibc-test reports FAIL and upload the
log file of the test to the asset list, so the reviewer can look at
the results.

- Progress ticket: https://progress.opensuse.org/issues/43892
- Verification run: http://silverfox.suse.de/tests/113

### CODE REVIEW

**Comment by wjn740** [comment]
Hi @eisfuchs-de 
Travis reports the following error during code check, your testing using soft_failure but no-reference.
Please fix this warning. so that the review could continue.

make: *** [test-soft_failure-no-reference] Error 1
The command "make test" exited with 2.

**Comment by eisfuchs-de** [comment]
Sorry about that. I didn't even realize my commit made it here, All I got was weird error messages, and eventually I had to give up working on it anyway. So this commit can be removed. I apologize for the confusion.

**Comment by OleksandrOrlov** [comment]
@eisfuchs-de Hi! Do you plan to look at this ever again?

**Comment by eisfuchs-de** [comment]
> @eisfuchs-de Hi! Do you plan to look at this ever again?

No. As I said in my earlier comment, I had to give up working on it and I wasn't even aware that the commit went through.

**Pull request closed without merging**
