### PR TITLE
[WIP] Add skipconsolereset option to power_action

### PR DESCRIPTION
**Pull request by czerw**
Fix poo#57329: When is system rebooted, all consoles are reset.
It means that messages during system reboot are lost on backends
like spvm (where management console needs to be reconnected).
This option will skip console reset and is possible to catch kernel
messages during shutdown.

- Related ticket: https://progress.opensuse.org/issues/57329
- Needles: none
- Verification run:
functional demo (not real code):  http://10.100.12.105/tests/3292#step/lpar#13/9
http://10.100.12.105/tests/3281#step/lpar#4/10

Not real code, just demo.
```
    select_console('root-console');
    record_info "rebooting";
    # skip console reset to caoture shutdown messages
    power_action('reboot', keepconsole => is_spvm, skipconsolereset => 1);
    record_info "selecting novalink-ssh directly";
    # reuse existing novalink-ssh console to see mkvterm console
    select_console "novalink-ssh", await_console => 0;
    assert_screen "system-reboot", timeout => 90, no_wait => 1;
    $self->wait_boot;
    select_console('root-console');
    script_run "echo 2";
    reset_consoles;
```

### CODE REVIEW

**Comment by czerw** [comment]
@okurz @Soulofdestiny could you please have a look? Although suggested solution works for me, it doesn't mean that it is right. Basically I'm trying to catch specific spvm backend issue, so not sure if it is right to implement it in this way or should implement it in test itself (specific reboot steps).

**Comment by okurz** [comment]
To me it either makes sense to reset consoles because we must, or we don't. However some consoles are reset on reboot of the *SUT* even though they could stay, e.g. the connection to the serial line of the SUT. So what I think you want instead: No option but only reset the consoles that are directly connected to the SUT, not reset any consoles that are connected to e.g. the hypervisor host or the serial line connection.

**Comment by czerw** [comment]
>  So what I think you want instead: No option but only reset the consoles that are directly connected to the SUT, not reset any consoles that are connected to e.g. the hypervisor host or the serial line connection.

Thank you for feedback! It means that I will have go to `os-autoinst` to make it more general for spvm backend and novalink-ssh console. Will have to be careful with side effects. I think I will start here
https://github.com/os-autoinst/os-autoinst/blob/2a217e9967c34ac02ca7c24d05ee678d2ee62e04/testapi.pm#L1651 and here https://github.com/os-autoinst/os-autoinst/blob/2a217e9967c34ac02ca7c24d05ee678d2ee62e04/backend/baseclass.pm#L565

to skip reset of particular console.

**Comment by okurz** [comment]
Yes, sounds good. But I recommend to not decide about resetting or not resetting by name but depending on the type, or the connection target or maybe some additional flag which we might want to set when we add the console

**Comment by czerw** [comment]
Will prepare new PR with better solution as was suggested by @okurz .

**Pull request closed without merging**
