### PR TITLE
Load bootloader_zkvm in CC test when ARCH is s390x

### PR DESCRIPTION
**Pull request by Amrysliu**
Verification run: https://openqa.suse.de/tests/7740832

### CODE REVIEW

**Comment by lilyeyes** [comment]
waiting for the openQA run to be finished :)

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Review by tinawang123 — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM

**Review by rfan1 — APPROVED** [review]
LGTM

**Pull request merged**
