### PR TITLE
Make sure installation overview is checked before any install, including...

### PR DESCRIPTION
**Pull request by sysrich**
... upgrades

### CODE REVIEW

**Comment by coolo** [comment]
isn't e.g. the select-patterns test assuming it's in the overview because it was checked before?

**Comment by sysrich** [comment]
Uhh, good point - any problem with running the same module twice? I want to
have the overview dep check occur in both before and after any pattern play

**Comment by coolo** [comment]
I don't actually know if os-autoinst has a problem with that, but openQA for sure uses the script name as  key in the database. But a symlink _after.pm will do for both.

**Comment by sysrich** [comment]
Closing because I'm going away and doing it properly for all 3 distros

**Pull request closed without merging**
