### PR TITLE
Containers: minor adjustments in autoyast profile

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/93817

- VR: https://openqa.suse.de/tests/overview?flavor=Container-Host&groupid=377&build=GM
- 15-SP4: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=43.1&groupid=313&test=create_hdd_autoyast_containers

### CODE REVIEW

**Comment by jlausuch** [comment]
Needs this modification in some job groups: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/448

**Review by pdostal — COMMENTED** [review]
Do we really wanna have image with both `docker` and `podman` installed? They may easily interfere.

**Comment by jlausuch** [comment]
> Do we really wanna have image with both `docker` and `podman` installed? They may easily interfere.

The idea is to have all preinstalled to save time in the tests. I don't see why docker and podman can work together. We already have tests in OSD and O3 that test docker and podman in the same job, they are not supposed to interfere, both should be ok to coexist. Actually if that doesn't work, then we have a serious product bug :)

**Review by cfconrad — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
