### PR TITLE
openqa script and entry for tc#1503908: evolution_timezone_setup

### PR DESCRIPTION
**Pull request by xjinGitty**
Local test result:
http://147.2.212.232/tests/543

### CODE REVIEW

**Comment by sysrich** [comment]
Does it really need to setup and use an external email address on an external email server? 
The test case is meant to be to set the timezone, you don't need to connect to aim.com for that..

**Comment by xjinGitty** [comment]
Yep, your concern is reasonable:), While doing so (add an EXTERNAL email account) is because first time start evolution will launch the 'Evolution Account Assistant' which need an account be setup.

EXTERNAL email account is not mandatory here, setup an internal email account which use Imap protocol is alternative, while this will have more complexity test steps, I don't think it matters.

**Comment by sysrich** [comment]
The way I would solve that is as follows:
Welcome screen > CLICK NEXT
Identity screen > Enter an Email-address (fake@address.com?), untick "Look up mail server details based on entered email address" > CLICK NEXT
Recieving E-Mail Screen > Server Type NONE > CLICK NEXT
Sending Email > Sendmail > CLICK NEXT
Account Summary > CLICK NEXT
Done > CLICK APPLY

There is no need for an EXTERNAL or INTERNAL email account to get Evolution setup the way you need it for this test..

**Comment by xjinGitty** [comment]
Thank you for the detailed comment, I updated the script accordingly which could be found in the commit.
Local run result:
http://147.2.212.232/tests/555

This time I use the original external email account as the "fake" email, which means: 1. skip looking up... 2. receiving -> None 3. sending -> Sendmail

**Pull request merged**
