### PR TITLE
hpc: create slurm user and group before installation

### PR DESCRIPTION
**Pull request by asmorodskyi**
create slurm user and group before installation

### CODE REVIEW

**Comment by asmorodskyi** [comment]
verification runs :
http://kimball.arch.suse.de/tests/535
http://kimball.arch.suse.de/tests/536
http://kimball.arch.suse.de/tests/534

@czerw  , @schlad  WDYT ?

**Comment by czerw** [comment]
@asmorodskyi This should be a part of package itself to create proper user/group for its usage. Or hpc maintainers have different opinion?

**Comment by asmorodskyi** [comment]
@czerw  not think it is easily doable on package level because it requires package installation script to be aware about results of installation of that package on different host. Also you should keep in mind that package could be installed in different time frame. Of course you can find several solutions to that problem but as far as I know currently we planning just update Release Notes with statement that user should care about it

**Comment by czerw** [comment]
@asmorodskyi Why do installation script to be aware about results of installation on different host?  Also not sure what do you mean by different time frame. I suppose if package needs specific user/group, it should be defined in spec file of that package. Or is this change linked to some bug which can't be solved at the moment and it needs special behavior ?

**Comment by asmorodskyi** [comment]
@czerw so first of all it is not my decision I just agree with it but I would be also agree if package would be capable to solve it. But for now I just trying to follow this https://bugzilla.suse.com/show_bug.cgi?id=1124587#c7 .
Getting back to your questions. there are two ways how to get same UID/GID in all hosts where slurm needs to be installed - static ( hard code some value ) and dynamic ( calculate some UID during installation running). From your questions I see that for you obvious to use static one. In this case all what I said does not make sense but also in this case you will not be able to install slurm if UID which install script using will be busy by some other user. And if you using dynamic way you facing all problems which I mention in my previous comment . Hope now it's clear if not let's setup something to discuss this with voice :)

**Comment by czerw** [comment]
@asmorodskyi ok, just please put  a comment(with bug relation) about user/group requirements to prepare_user_and_group and I will be fine

**Comment by asmorodskyi** [comment]
@czerw  - done

**Pull request merged**
