### PR TITLE
Apply direct method call to get_test_data

### PR DESCRIPTION
**Pull request by rwx788**
[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/xyz
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

### CODE REVIEW

**Comment by jknphy** [comment]
I guess we used a name that was picked, that will help to avoid the warning.

**Comment by rwx788** [comment]
> I guess we used a name that was picked, that will help to avoid the warning.

I'm not really sure as it works fine in 64bit: https://openqa.suse.de/tests/3635528

So this is weird one and ppc64le specific.

**Comment by rwx788** [comment]
Feels like we have dependency loop or something like that, but I still don't understand how it works on 64bit, for example.

**Comment by rwx788** [comment]
Didn't work.

**Comment by jknphy** [comment]
In 64bit the warning is present:
```
Subroutine validate_encrypt::get_test_data redefined at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
 at /var/lib/openqa/cache/openqa.suse.de/tests/sle/tests/console/validate_encrypt.pm line 23.
```
This works to avoid the warning as there a function with the same name in that package: `use testapi 'select_console';`

**Comment by rwx788** [comment]
> In 64bit the warning is present:
> 
> ```
> Subroutine validate_encrypt::get_test_data redefined at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
>  at /var/lib/openqa/cache/openqa.suse.de/tests/sle/tests/console/validate_encrypt.pm line 23.
> ```
> 
> This works to avoid the warning as there a function with the same name in [that package](https://github.com/os-autoinst/os-autoinst/blob/1b6d94a7605791c41297b93771dac0082eb1856f/testapi.pm#L1135): `use testapi 'select_console';`

Nice catch! Hmm, then we should rename the method, I can see that we have same in `testapi.pm`.

**Pull request closed without merging**
