### PR TITLE
Close without change in case gnucash are asking save changes

### PR DESCRIPTION
**Pull request by nilxam**
https://openqa.opensuse.org/tests/115125/modules/gnucash/steps/39

### CODE REVIEW

**Comment by coolo** [comment]
this begs the question if the default timeout of 30 isn't a bit much for such use cases.

**Comment by nilxam** [comment]
I've a bit not so sure people are prefer 'with timeout' or 'without timeout' now :-)

**Comment by sysrich** [comment]
For a check_screen used in this circumstance, I'd recommend a timeout of
between 5-10 seconds

**Comment by nilxam** [comment]
let's use 10 then. updated.

**Comment by okurz** [comment]
would it make sense to do something like
```
# either gnucash closes or asks to save changes if any
my $ret = check_screen([qw/gnucash-save-changes whatever-the-tag-is-for-clean-desktop/]);
# if we reached timeout with no screen change gnucash hangs
die "gnucash did not close in time" unless $ret;
# if gnucash asks to save changes ...
if ($ret->{needle}->has_tag('gnucash-save-changes')) {
    # ... close it without saving
    send_key "alt-w";    # close without saving
}
```
Then we would do the same amount of 'check screens' only against more needles but exit early

**Comment by nilxam** [comment]
in your way, it looks exit gnucash test early indeed when it found generic desktop, however in *x11* test it will executing assert_screen generic-desktop in post hook anyway, so it won't exit early in real.

**Comment by okurz** [comment]
ok, if the assert screen is in the post hook anyway then we could still check for both possible tags so we will save time even though we check *again* for the same tag in the post hook

**Comment by nilxam** [comment]
well, 1) I don't get the benefit for check 2 tags in one check_screen will save time than check 1 tag, the code "looks like" it is, but if check_screen("gnucash-save-changes", 10) failed it will exit the test, ther're the same thing IMO.
2) check 2 tags in check_screen plus overwrite post_run_hook should does help, but is it really important for that 1x seconds then we have to add a overwrite function in the test?

**Comment by okurz** [comment]
No, not important just for this single module. I just wanted to know what you think about it, if I get it right. I would propose to eventually do it right for all modules, then. It should resemble more how humans would interact. They would not wait in front of an empty screen and see if the save dialog pops up. They would look and detect the current state and decide from there, be it the save dialog or empty desktop.

**Comment by nilxam** [comment]
if so then that's about redesign post_run_hook to integrate with the last screen matching IMO. I dislike to add "die ... useless ..." to every single module at least.

**Pull request merged**
