### PR TITLE
Fix metadata in HA cluster tests

### PR DESCRIPTION
**Pull request by dzyuzin**

### CODE REVIEW

**Comment by coolo** [comment]
cool. but you need to remove the G- prefix too

**Comment by okurz** [comment]
You are doing more than just replacing the metadata, please split commits

**Comment by sysrich** [comment]
@dzyuzin please make the changes suggested by coolo and okurz

**Comment by okurz** [comment]
the two replaced files were symlinks. @dzyuzin stated that the script which added "g-summary" and "g-maintainer" broke it.

**Pull request merged**
