### PR TITLE
Fix the rework of x11_start_program

### PR DESCRIPTION
**Pull request by DrMullings**
Now only pressing esc if an open desktop runner

- Related ticket: https://progress.opensuse.org/issues/55580
- Verification run: tbd

### CODE REVIEW

**Comment by DrMullings** [comment]
First:
https://openqa.opensuse.org/tests/1053135

**Comment by DrMullings** [comment]
New (old) code, new verification run: https://openqa.opensuse.org/tests/1053421

**Comment by DrMullings** [comment]
New Code means new verification:
https://openqa.opensuse.org/tests/1054433

**Comment by DrMullings** [comment]
Well as Contact is broken anyways I guess this is not my fault

**Comment by okurz** [comment]
what do you mean by "Kontact is broken"?

**Comment by DrMullings** [comment]
If you take look at the Module it did not run through for a while

**Comment by okurz** [comment]
https://openqa.opensuse.org/tests/1055652#step/kontact/16 is fine. I don't know what else you are referring to

**Comment by DrMullings** [comment]
@SergioAtSUSE wdyt?

**Comment by DrMullings** [comment]
@okurz I mean the scenario I used for verification which is on krypton:
https://openqa.opensuse.org/tests/1056111#next_previous

**Comment by DrMullings** [comment]
Anyway I created https://openqa.opensuse.org/tests/1056609 as another verification

**Comment by SergioAtSUSE** [comment]
> @okurz I mean the scenario I used for verification which is on krypton:
> https://openqa.opensuse.org/tests/1056111#next_previous

Well in that one at least you can see how it started loading and freeze. Maybe we just need to wait more? are you able to manually reproduce it?

**Comment by okurz** [comment]
https://openqa.opensuse.org/tests/1056111#step/kontact/19 shows that the system is under stress. This might just be for the simple reason of the live system not having enough memory. For testing purposes you can try with e.g. 4GB RAM. Nevertheless the post_fail_hook could be improved to detect this situation by using magic sysrq – or simply longer waiting

**Comment by DrMullings** [comment]
I do not care about Kontact in that ticket, so lets please stay focused and you tell me whether I need to change something

**Comment by SergioAtSUSE** [comment]
@DrMullings, if we cannot properly discard that your change makes the kontact module to work worst, we have to still care.

Could you provide 100 runs of https://openqa.opensuse.org/tests/1056609 ?
That would be enough for me to consider your changes not affecting kontact negatively.

**Comment by DrMullings** [comment]
Runs:
https://openqa.opensuse.org/tests/overview?build=verify_pr_8633_investigation&distri=opensuse&version=Tumbleweed

**Comment by Vogtinator** [comment]
Broke gnucash, opened a revert (again): https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8723

**Pull request merged**
