### PR TITLE
Fix ssh port timeout issue and mac addr conflict issue in swtpm tests

### PR DESCRIPTION
**Pull request by rfan1**
- Related ticket:
 https://progress.opensuse.org/issues/102849
 https://progress.opensuse.org/issues/102933
- Needles: n/a
- Verification run: 
Create-swtpm-hdd: 
  https://openqa.suse.de/tests/7734361
  https://openqa.suse.de/tests/7734362
Swtpm-verify:
 https://openqa.suse.de/tests/7738821
 https://openqa.suse.de/tests/7738814

### CODE REVIEW

**Review by Amrysliu — APPROVED** [review]
lgtm

**Review by lilyeyes — APPROVED** [review]
lgtm

**Comment by jouyingbin** [comment]
@rfan1 
As I remember this case was run on TW as well. would you like to provide a VR on TW too?

**Comment by rfan1** [comment]
> @rfan1 As I remember this case was run on TW as well. would you like to provide a VR on TW too?

@jouyingbin 2 reasons not running this on TW, 
1. there is an open bug blocks tw swtpm test
2. the changes is not platform specific

**Comment by jouyingbin** [comment]
> > @rfan1 As I remember this case was run on TW as well. would you like to provide a VR on TW too?
> 
> @jouyingbin 2 reasons not running this on TW,
> 
>     1. there is an open bug blocks tw swtpm test
> 
>     2. the changes is not platform specific

okay, thanks for the information.

**Review by jouyingbin — APPROVED** [review]
LGTM

**Pull request merged**
