### PR TITLE
[WIP] Another desperate try to fix minimalx shutdown

### PR DESCRIPTION
**Pull request by DrMullings**
Please just work

DO NOT MERGE, JUST FOR TESTING ON PRODUCTION

- Related ticket: https://progress.opensuse.org/issues/46076

### CODE REVIEW

**Comment by DrMullings** [comment]
A few verifications:
https://openqa.suse.de/tests/2544989
https://openqa.suse.de/tests/2544989
https://openqa.suse.de/tests/2544991
https://openqa.suse.de/tests/2544992

**Comment by DrMullings** [comment]
Just a test comment

**Comment by DrMullings** [comment]
This comes from a command line

**Comment by OleksandrOrlov** [comment]
@DrMullings Hi! Do you plan to look at this ever again?

**Comment by DrMullings** [comment]
At the ticket maybe, not the PR

**Pull request closed without merging**
