### PR TITLE
Add dm crypt test for fips

### PR DESCRIPTION
**Pull request by mitiao**
verified result:
http://147.2.207.208/tests/39
needle merge request:
https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/185

### CODE REVIEW

**Comment by sysrich** [comment]
What is the benefit of this test compared to instead doing a RAID1 install with FIPS=1 set?

From my perspective it seems we're adding .pms when we could just add scenarios that could cover this

**Comment by coolo** [comment]
RAID1 is not asking for passwords, no? (I already merged the needles :)

**Comment by sysrich** [comment]
I guess I meant to say the cryptlvm+RAID1 test

**Comment by sysrich** [comment]
but as we've merged the needles already..

**Pull request merged**
