### PR TITLE
Increase timeout for yast2_software_management

### PR DESCRIPTION
**Pull request by hjluo**
We need to Increase timeout for yast2_software_management.

- Related ticket: https://progress.opensuse.org/issues/124592
- Needles: N/A
- Verification run: 
   https://openqa.suse.de/tests/10522919
   https://openqa.suse.de/tests/10538731
   https://openqa.suse.de/tests/10538739
   https://openqa.suse.de/tests/10539295

### CODE REVIEW

**Comment by jknphy** [comment]
why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.

**Comment by hjluo** [comment]
> why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.

reflected in the ticket and now I've added it in the description. thanks

**Comment by jknphy** [comment]
> > why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.
> 
> reflected in the ticket and now I've added it in the description. thanks

I don't see any timeout issue in the other two, can you explain it? it could be that sporadically succeeds without your change in those two files...

**Comment by hjluo** [comment]
> > > why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.
> > 
> > 
> > reflected in the ticket and now I've added it in the description. thanks
> 
> I don't see any timeout issue in the other two, can you explain it? it could be that sporadically succeeds without your change in those two files...

this looks like timeout for me:
https://openqa.suse.de/tests/10522712#step/yast2_lan_restart_bridge/44

this looks like libyui-rest-api server is down, if it's true I can remove the timeout for this case. thanks
https://openqa.suse.de/tests/10525970#step/yast2_network_settings/21

**Comment by jknphy** [comment]
> > > > why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.
> > > 
> > > 
> > > reflected in the ticket and now I've added it in the description. thanks
> > 
> > 
> > I don't see any timeout issue in the other two, can you explain it? it could be that sporadically succeeds without your change in those two files...
> 
> this looks like timeout for me: https://openqa.suse.de/tests/10522712#step/yast2_lan_restart_bridge/44
> 
> this looks like libyui-rest-api server is down, if it's true I can remove the timeout for this case. thanks https://openqa.suse.de/tests/10525970#step/yast2_network_settings/21

The first one could be due to we send some keys after going to collect logs, and the libyui-rest-api is is unrelated, the screen is not there and we rest calls are not reaching it. I'd suggest to bump only the timeout we need and run verification, if stills fails, let's discuss on slack.

**Comment by hjluo** [comment]
> could be due to we send some

OK. thank you.

**Comment by hjluo** [comment]
> > > > > why we need to change for the other two files? It is not reflected in the title/commit/title and I don't see the screen changing after the failure in the screenshot.
> > > > 
> > > > 
> > > > reflected in the ticket and now I've added it in the description. thanks
> > > 
> > > 
> > > I don't see any timeout issue in the other two, can you explain it? it could be that sporadically succeeds without your change in those two files...
> > 
> > 
> > this looks like timeout for me: https://openqa.suse.de/tests/10522712#step/yast2_lan_restart_bridge/44
> > this looks like libyui-rest-api server is down, if it's true I can remove the timeout for this case. thanks https://openqa.suse.de/tests/10525970#step/yast2_network_settings/21
> 
> The first one could be due to we send some keys after going to collect logs, and the libyui-rest-api is is unrelated, the screen is not there and we rest calls are not reaching it. I'd suggest to bump only the timeout we need and run verification, if stills fails, let's discuss on slack.

OK, thank you!

**Pull request merged**
