### PR TITLE
add 3 shotwell cases to x11regression

### PR DESCRIPTION
**Pull request by chuchingkai**
Test Result: http://147.2.212.239/tests/117

shotwellbase.pm provides a package that the other 3 scripts can use to import testing pictures and clean the testing files.

- Case 1503962 - Shotwell: Import image files
- Case 1503811 - Shotwell: Delete or edit an imported image
- Case 1503754 - Shotwell: Shotwell: Export Images to Folder

### CODE REVIEW

**Comment by coolo** [comment]
I merged the needles and the tests look good to me

**Comment by chuchingkai** [comment]
sorry, the code is not clean (not passed by travis-ci) so I closed this pr.
I will re-submit a new pr.

**Comment by okurz** [comment]
No need to close the PR. After you push updated commits to the same branch as used for the initial PR the content will be updated automatically.

**Comment by chuchingkai** [comment]
travis prompt that:
export PERL5LIB="../..:os-autoinst:lib:tests/installation:tests/x11:tests/qa_automation:$PERL5LIB" ; for f in `git ls-files "*.pm" || find . -name \*.pm|grep -v /os-autoinst/` ; do perl -c $f 2>&1 | grep -v " OK$" && exit 2; done ; true

Can't locate shotwellbase.pm in @INC (you may need to install the shotwellbase module) (@INC contains: /home/travis/build/chuchingkai/os-autoinst-distri-opensuse/blib/arch /home/travis/build/chuchingkai/os-autoinst-distri-opensuse/blib/lib ../.. os-autoinst lib tests/installation tests/x11 tests/qa_automation /home/travis/perl5/perlbrew/perls/5.18-extras/lib/site_perl/5.18.4/x86_64-linux-thread-multi /home/travis/perl5/perlbrew/perls/5.18-extras/lib/site_perl/5.18.4 /home/travis/perl5/perlbrew/perls/5.18-extras/lib/5.18.4/x86_64-linux-thread-multi /home/travis/perl5/perlbrew/perls/5.18-extras/lib/5.18.4 .) at tests/x11regressions/shotwell/shotwell_edit.pm line 13, <DATA> line 2125.

so I'm considering to move shotwellbase.pm into the "lib" and give it a more common name "x11regressiontest.pm"

Could I do this ?

**Comment by okurz** [comment]
yes

**Pull request closed without merging**
