### PR TITLE
Enable debugging and more timeout

### PR DESCRIPTION
**Pull request by MalloZup**
bsc#980337, 
15:56:19.7332 >>> testapi::_check_or_assert: match=linux-login timed out after 200

### CODE REVIEW

**Comment by MalloZup** [comment]
PR not tested locally should work.

**Comment by okurz** [comment]
I think your code makes sense for local reproduction, e.g. for the assignee of the corresponding issue this can be used when running tests on a local instance of openqa. Probably not so much suitable for production.

**Comment by MalloZup** [comment]
i don't know why in the production you will not increase the timeout. If you consider that this can help debug the problem immediately, then to reproduce it locally, this is much more better.

**Comment by okurz** [comment]
It's about the general workflow. It just won't scale if we add debugging output for all cornercases to production tests. If local reproduction is too much work we should try to improve our test infrastructure to be easier to be used but this is a different issue.

**Comment by MalloZup** [comment]
I can agree that the production should be fast, but at least should ensure a good report of the status of testing.

the thing is following:

i think is not a good practice to just open a bug, without give debugging info, log info. This was the case of the bug opened.  ( that at beginning was set to prio1, without any reason)

**Comment by sysrich** [comment]
As commented in https://bugzilla.suse.com/show_bug.cgi?id=980337#c11 I think we need a PR that does something like https://bugzilla.suse.com/show_bug.cgi?id=980337#c8 suggests.

**Comment by sysrich** [comment]
The debug info is a good idea - but I'd rather see it in the form of uploaded logs, and I'd rather see it only uploaded when a failure is noticed, like we do in lib/y2logstep.pm

**Pull request closed without merging**
