### PR TITLE
Solve existing issues for xen hypervisor mitigation test

### PR DESCRIPTION
**Pull request by XGWang0**
Enhance xen vul test to adapt to multiple Micro-architecture test
1.Divide big hash to multiple small one.
2.Add pv_l1tf related test cases
3.Use correct test cases according to machine micro-arch
4.Reduce some output to avoid worker consume more memory. 

- Related ticket: N/A
- Needles: N/A
- Verification run: http://10.67.134.217/tests/10369

### CODE REVIEW

**Comment by XGWang0** [comment]
@Dawei-Pang @lansuse @alice-suse  Please help to review.

**Comment by okurz** [comment]
hi, I am not sure if you have seen my comment or if you changed your git commit message *because* of it but please use a common style. Taking a look into existing commits is a good start. "1.Divide big hash into small one;2.Solve existing some issues " is discouraged for the following reasons:

* Enumeration in a single line
* Missing separation whitespaces
* Multiple things at once
* No clear reasoning of the change or describing the benefit but only stating about *what* changed, not *why*
* No reference to ticket or anything

Please see the guides referenced in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10644#pullrequestreview-442928424

**Comment by XGWang0** [comment]
> hi, I am not sure if you have seen my comment or if you changed your git commit message _because_ of it but please use a common style. Taking a look into existing commits is a good start. "1.Divide big hash into small one;2.Solve existing some issues " is discouraged for the following reasons:
> 
> * Enumeration in a single line
> * Missing separation whitespaces
> * Multiple things at once
> * No clear reasoning of the change or describing the benefit but only stating about _what_ changed, not _why_
> * No reference to ticket or anything
> 
> Please see the guides referenced in [#10644 (review)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10644#pullrequestreview-442928424)

**Comment by XGWang0** [comment]
> hi, I am not sure if you have seen my comment or if you changed your git commit message _because_ of it but please use a common style. Taking a look into existing commits is a good start. "1.Divide big hash into small one;2.Solve existing some issues " is discouraged for the following reasons:
> 
> * Enumeration in a single line
> * Missing separation whitespaces
> * Multiple things at once
> * No clear reasoning of the change or describing the benefit but only stating about _what_ changed, not _why_
> * No reference to ticket or anything
> 
> Please see the guides referenced in [#10644 (review)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10644#pullrequestreview-442928424)

Thank you very much your review. I changed the commit message, please review again.

**Comment by okurz** [comment]
Just some typos left: s/paltform/platform/, s/architechcture/architecture/

**Comment by Dawei-Pang** [comment]
LGTM

**Comment by lansuse** [comment]
LGTM

**Comment by alice-suse** [comment]
> Just some typos left: s/paltform/platform/, s/architechcture/architecture/
@XGWang0 Do you plan to change it as comment? Or has it been finished? I do not see reply to it. Please le.t me know when all changes are done. I am glad to merge it.

**Comment by XGWang0** [comment]
> > Just some typos left: s/paltform/platform/, s/architechcture/architecture/
> 
> @XGWang0 Do you plan to change it as comment? Or has it been finished? I do not see reply to it. Please le.t me know when all changes are done. I am glad to merge it.

yes , done, please review again, thanks

**Comment by XGWang0** [comment]
> Just some typos left: s/paltform/platform/, s/architechcture/architecture/

Changed already. Thanks

**Pull request merged**
