### PR TITLE
Prevent erroneous disabling of ports with STP=off for sle12

### PR DESCRIPTION
**Pull request by Julie-CAO**
- sle12sp5 host failed with `BRIDGE_STP='on'`, fg. https://openqa.suse.de/tests/15389928#step/install_package/11. And a few machines might fail to boot, see https://sd.suse.com/servicedesk/customer/portal/1/SD-167626. The explaination is https://sd.suse.com/servicedesk/customer/portal/1/SD-153019
- remove `WITHOUT_AUTOYAST_SECOND_STAGE=1` settings from sle12sp5 test suites on OSD webUI as there has no error pop-up any more. 

- Related ticket: https://progress.opensuse.org/issues/163682
- Verification run: 
test pass with `BRIDGE_STP='off'`, 
http://openqa.suse.de/tests/15390580
http://openqa.suse.de/tests/15389917
http://openqa.suse.de/tests/15390101

### CODE REVIEW

**Review by alice-suse — COMMENTED** [review]
LGTM. Please pay attention to CI check failures.

**Comment by Julie-CAO** [comment]
> LGTM. Please pay attention to CI check failures.

Rerun the CI checks and they passed.

**Comment by okurz** [comment]
I don't understand the subject "Turn BRIDGE_STP off as it is suspected to leads to some network loop". [STP ](https://en.wikipedia.org/wiki/Spanning_Tree_Protocol) exists to *prevent* loops

**Comment by Julie-CAO** [comment]
> I don't understand the subject "Turn BRIDGE_STP off as it is suspected to leads to some network loop". [STP ](https://en.wikipedia.org/wiki/Spanning_Tree_Protocol) exists to _prevent_ loops

From IT in https://sd.suse.com/servicedesk/customer/portal/1/SD-153019(you have access)
```
We double check the network infrastructure, cables etc  all it fine,

We see that port is administratively down on the ToR switch. This happen due to wrong

network configuration on the server side. The switch detect possible loop via STP (BPDU protection)

and send port down.

We turn is up and in 5 minutes it was down again.

 

This look like the same issue that you had in https://sd.suse.com/browse/SD-151127

Please fix your network setup first.
This possible you have this bug in some template.
make sure you have BRIDGE_STP set to 'off'
```

**Comment by okurz** [comment]
> > I don't understand the subject "Turn BRIDGE_STP off as it is suspected to leads to some network loop". [STP ](https://en.wikipedia.org/wiki/Spanning_Tree_Protocol) exists to _prevent_ loops
> 
> From IT in https://sd.suse.com/servicedesk/customer/portal/1/SD-153019 (you have access)
> 
> ```
> We double check the network infrastructure, cables etc  all it fine,
> 
> We see that port is administratively down on the ToR switch. This happen due to wrong
> 
> network configuration on the server side. The switch detect possible loop via STP (BPDU protection)
> 
> and send port down.
> 
> We turn is up and in 5 minutes it was down again.
> 
>  
> 
> This look like the same issue that you had in https://sd.suse.com/browse/SD-151127
> 
> Please fix your network setup first.
> This possible you have this bug in some template.
> make sure you have BRIDGE_STP set to 'off'
> ```

Exactly. The switch was taken down due to STP to prevent loops. The above text is not correct English but what I assume it wants to tell us that with BRIDGE_STP=off the port is not taken down however that leaves the chance for loops.

**Comment by guoxuguang** [comment]
LGTM

**Comment by RoyCai7** [comment]
LGTM for my ipxe testing

**Comment by alice-suse** [comment]
> > > I don't understand the subject "Turn BRIDGE_STP off as it is suspected to leads to some network loop". [STP ](https://en.wikipedia.org/wiki/Spanning_Tree_Protocol) exists to _prevent_ loops
> > 
> > 
> > From IT in https://sd.suse.com/servicedesk/customer/portal/1/SD-153019 (you have access)
> > ```
> > We double check the network infrastructure, cables etc  all it fine,
> > 
> > We see that port is administratively down on the ToR switch. This happen due to wrong
> > 
> > network configuration on the server side. The switch detect possible loop via STP (BPDU protection)
> > 
> > and send port down.
> > 
> > We turn is up and in 5 minutes it was down again.
> > 
> >  
> > 
> > This look like the same issue that you had in https://sd.suse.com/browse/SD-151127
> > 
> > Please fix your network setup first.
> > This possible you have this bug in some template.
> > make sure you have BRIDGE_STP set to 'off'
> > ```
> 
> Exactly. The switch was taken down due to STP to prevent loops. The above text is not correct English but what I assume it wants to tell us that with BRIDGE_STP=off the port is not taken down however that leaves the chance for loops.

@okurz  Do you have other better idea to solve the problem perfectly? If yes, we appreciate the sharing and will try. Otherwise maybe let's try to set STP=off firstly, if it turns out to be problematic, we can find other solutions?

**Comment by Julie-CAO** [comment]
I changed the commit msg and comment to avoid of misleading.

**Comment by okurz** [comment]
Again, the change is fine but the commit message is wrong. STP does not cause loops, it prevents those. How about "Prevent erroneous disabling of ports with STP=off"

**Comment by Julie-CAO** [comment]
Corrected the commit message.

**Pull request merged**
