### PR TITLE
Containers: make sure that BUILD corresponds with the image version

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/100916

VR: 
http://fromm.arch.suse.de/tests/3496
http://fromm.arch.suse.de/tests/3495

forced failure: http://fromm.arch.suse.de/tests/3497#step/podman_image/58

### CODE REVIEW

**Comment by Vogtinator** [comment]
VR for TW and Leap would be nice as well

**Comment by jlausuch** [comment]
[VR Leap](https://openqa.opensuse.org/tests/overview?version=15.3&distri=opensuse&build=jlausuch%2Fos-autoinst-distri-opensuse%23validate_image)
TW got cancelled, I can wait till latest build finishes all the jobs and do a clone refspec

**Comment by jlausuch** [comment]
[Leap 15.3](https://openqa.opensuse.org/tests/overview?version=15.3&distri=opensuse&build=jlausuch%2Fos-autoinst-distri-opensuse%23validate_image)
[TW](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=jlausuch%2Fos-autoinst-distri-opensuse%23validate_image&distri=opensuse)
[SLE](http://fromm.arch.suse.de/tests/3522)
[SLE wrong image](http://fromm.arch.suse.de/tests/3523#step/podman_image/59)

**Comment by jlausuch** [comment]
Putting this on hold, as it breaks some tests in O3.
https://openqa.opensuse.org/tests/1968247#step/docker_3rd_party_images/78

**Pull request closed without merging**
