### PR TITLE
[WIP] Use more strict 'assert_screen_change' where possible

### PR DESCRIPTION
**Pull request by okurz**
https://github.com/os-autoinst/os-autoinst/pull/689 added a new function to
the testapi 'assert_screen_change' which should be used wherever there is no
explicit checking of the return value of 'wait_screen_change'.

Leaving alone the occurences of 'wait_screen_change' where the return code
is checked.

Verification run: http://lord.arch/tests/5552

### CODE REVIEW

**Comment by okurz** [comment]
needs update of os-autoinst on our workers first

**Comment by okurz** [comment]
… and doesn't work http://lord.arch/tests/5552#step/releasenotes/7 I guess the original PR in os-autoinst was wrong already -> https://github.com/os-autoinst/os-autoinst/pull/689#discussion_r96010240

**Comment by sysrich** [comment]
Still WIP? looks like this needs a rebase

**Comment by okurz** [comment]
can reopen when someone (e.g. me) fixed os-autoinst first

**Pull request closed without merging**
