### PR TITLE
Increase timeout for update_installation_overview

### PR DESCRIPTION
**Pull request by nilxam**
Give it more time while analyzing the system.

https://openqa.opensuse.org/tests/257963#step/upgrade_select_opensuse/7

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
LGTM, let's wait the checks :)

**Comment by nilxam** [comment]
what checks? :)

**Comment by Soulofdestiny** [comment]
I meant the travis check ;)

**Comment by kravciak** [comment]
Timeout partly caused by bsc#997635

**Pull request merged**
