### PR TITLE
Delete unused AIM files after #4072

### PR DESCRIPTION
**Pull request by okurz**
These modules are unused now and are very similar to the irc modules anyway.

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@dehai  - what do you think ?

**Comment by nicksinger** [comment]
Since AIM will close its doors tomorrow, there should be no reason to object ;)
LGTM

**Comment by dehai** [comment]
I have no doubt about this, just remove it . another question, how about needles in those modules?

**Comment by okurz** [comment]
@dehai for needles openQA has a feature to track needles that have not been used for some time. So eventually someone, e.g. coolo, will lookup needles that are not used for some months and delete them from the repo. So in this case we do not need to care so much to cleanup manually. But that is still possible of course.

**Comment by dehai** [comment]
@okurz got it, thanks!

**Pull request merged**
