### PR TITLE
Enable MinimalVM x86_64 with SecureBoot disabled test scenario

### PR DESCRIPTION
**Pull request by rbmarliere**
These are the required modifications in order to add the jeos-nosb test scenario, defined as:

DISTRI=opensuse
VERSION=Tumbleweed
FLAVOR=JeOS-for-kvm-and-xen
ARCH=x86_64 
BOOT_HDD_IMAGE=1
CHECK_MOK_IMPORT=1
DESKTOP=textmode
DISABLE_SECUREBOOT=1
UEFI=1

Please check individual commit messages for more info.

- Related ticket: https://progress.opensuse.org/issues/95434
- Verification runs:
[Tumbleweed](https://openqa.opensuse.org/tests/4624423)
[Leap 15.5](https://openqa.opensuse.org/tests/4627194)
[Leap 15.6](https://openqa.opensuse.org/tests/4627193)
[12 SP5](https://openqa.suse.de/tests/15880206)
[15 SP2](https://openqa.suse.de/tests/15878392)
[15 SP3](https://openqa.suse.de/tests/15878393)
[15 SP4](https://openqa.suse.de/tests/15879453)
[15 SP5](https://openqa.suse.de/tests/15878396)
[15 SP6](https://openqa.suse.de/tests/15878401)
[15 SP6 HyperV](https://openqa.suse.de/tests/15882230)
[15 SP7](https://openqa.suse.de/tests/15877517)

### CODE REVIEW

**Comment by mloviska** [comment]
Good, I see that `mokutil --sb-state` reports disable SB. Could you please run for all maintenance Minimal-VMs + SP7 the same test?

**Comment by rbmarliere** [comment]
More VRs added, all looks good.

**Review by mloviska — APPROVED** [review]

**Comment by hjluo** [comment]
Hi @rbmarliere

**Comment by ggardet** [comment]
This breaks on aarch64 Tumbleweed: https://openqa.opensuse.org/tests/4637168#step/verify_efi_mok/291

**Comment by grisu48** [comment]
> This breaks on aarch64 Tumbleweed: https://openqa.opensuse.org/tests/4637168#step/verify_efi_mok/291
> 
> It looks like commit [9e4c293](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/9e4c2938bbe7c82ada5eb98d493c2335be9a301b) should be reverted

Indeed, will revert it: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20602

**Pull request merged**
