### PR TITLE
Improve check for updated package version

### PR DESCRIPTION
**Pull request by kravciak**
Fix for: https://openqa.opensuse.org/tests/613217#step/transactional_update/48
Local run: http://dhcp91.suse.cz/tests/1444

### CODE REVIEW

**Comment by kravciak** [comment]
@sysrich please re-check first commit, I added code to that should prevent failures if test package rebuilds

**Comment by okurz** [comment]
ah ok. I created https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4442 for the tidy fix now. Let's see. I will merge my PR and then rebase this one.

**Comment by DimStar77** [comment]
The commit is drunk too - it does not work:

https://openqa.opensuse.org/tests/619017#step/transactional_update/48

**Comment by kravciak** [comment]
The issue is that script_output returns: "linux-wvf5 login: 4.1"
```
script_output("rpm -q --qf '%{RELEASE}' $package");
```

I think @okurz was trying to fix script_output, not sure if it's done already.

**Comment by coolo** [comment]
Well, his change is a) not deployed on o3 and b) is not bullet-proof either

**Pull request merged**
