### PR TITLE
Add check for bsc1192051

### PR DESCRIPTION
**Pull request by grisu48**
Add a check for bsc1192051 in `rootless_podman` and skip the test run if present. 
This bug breaks the s390x and ppc64le test runs for `rootless_podman`.

- Related ticket: https://progress.opensuse.org/issues/101280
- Verification run: [15-SP3 aarch64](https://openqa.suse.de/t7590883) | [15-SP3 s390x](https://openqa.suse.de/t7590884) | [15-SP3 x86_64](https://openqa.suse.de/t7590885) | [15-SP4 ppc64le](https://openqa.suse.de/t7590886) | [Tumbleweed](https://openqa.opensuse.org/t2009567)

### CODE REVIEW

**Comment by Vogtinator** [comment]
Can you limit this softfail to the affected arches only? Otherwise failures on currently working archs won't get noticed.

**Review by pdostal — APPROVED** [review]
Looks good, properly commented! :100:

**Comment by grisu48** [comment]
> Can you limit this softfail to the affected arches only? Otherwise failures on currently working archs won't get noticed.

I could, however [aarch64](https://openqa.suse.de/tests/7589740) and [x86_64](https://openqa.suse.de/tests/7589742) are not affected and run the whole test. And they would probably fail in the same way, if they would be affected, right?

**Comment by grisu48** [comment]
I've updated it anyways and limited the check to s390x and ppc64le. New round of VRs is scheduled

**Comment by Vogtinator** [comment]
> I could, however aarch64 and x86_64 (and Tumbleweed) are not affected and run the whole test. And they would probably fail in the same way, if they would be affected, right?

Yes, but a) they shouldn't b) if they fail, it needs to be investigated, instead of just solftfailing.

**Review by Vogtinator — APPROVED** [review]

**Review by jlausuch — APPROVED** [review]
I agree with faking this bug in the code because is the current approach we need to follow for maintenance ...although I am strongly against this way of making the bot happy...

**Pull request merged**
