### PR TITLE
Virtualization: add junit log for subcases in guest migration tests

### PR DESCRIPTION
**Pull request by alice-suse**
Add junit log to show the subtests as individual item in final result display.

- Verification run: http://10.67.18.220/tests/374

### CODE REVIEW

**Comment by asmorodskyi** [comment]
Code looks good. Only concern - log file which you trying to reformat to junit here, isn't it  "our" code  is producing it? In case "yes" why not just initially produce junit instead of creating one format and converting it to another?

**Comment by alice-suse** [comment]
@asmorodskyi  Thanks for the review!  Good question! The log file is indeed generated by our code, however by underlying shell test scripts in qa_lib_virtauto rpm which is  not openqa initialized test code. It is not intended for junit format log (it is more like readable text) and it is also used by somewhere else(jenkins). So  we need to transform here.

**Comment by asmorodskyi** [comment]
maybe than there is a chance to generate both formats simultaneously in this qa_lib_virtauto shell script ? Or you mention that this text-like format consumed by jenkins  and jenkins has several plugins to consume junit, so is there chance to move jenkins to use this junit format ? 
Just think about this for long-term, meanwhile I will merge this PR as from code perspective I have no concerns about it

**Comment by alice-suse** [comment]
Thanks for your suggestion. We will consider about it from long term.

**Pull request merged**
