### PR TITLE
Load the new fortran test

### PR DESCRIPTION
**Pull request by mnowaksuse**
I let this test run as a first one in TCM testsuite as it takes only a couple of minutes.

Depends on pull request #943.

### CODE REVIEW

**Comment by okurz** [comment]
Hi @mnowaksuse content looks fine but you might be interested in the https://github.com/os-autoinst/os-autoinst#rules-for-commits which we just added to the documentation. E.g. your commit message is missing line wrap. But that is just a tiny issue ;-)

**Comment by mnowaksuse** [comment]
Thanks @okurz, history rewritten. Now I guess I should squash it..

**Comment by sysrich** [comment]
Yes please

**Comment by mnowaksuse** [comment]
Should be there.

**Pull request merged**
