### PR TITLE
Use test rpm from server app module

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/64045

### CODE REVIEW

**Comment by asdil12** [comment]
Verification: http://artemis.suse.de/tests/2271#step/command_not_found/19

**Comment by asdil12** [comment]
I removed the softfail as I don't see how something would fail with a FATE reference.
Also it doesn't fail on SLE15SP2 x86_64.

**Comment by SergioAtSUSE** [comment]
It seems it was more complex than we thought. Let's rethink this.

The fate wanted two things:

A. Add a feature to `zypper search` to be able to find packages in non activated modules.
B. Add a fueature to `cnf` to be able to find packages in non activated modules.

Feature A is implemented as `zypper package-search`.
Feature B is not yet implemented. So, we need to file a bug pointing to the fate (I haven't found any Jira ticket)

That means that this test module has to be moved to extra_tests_textmode_mod_desktop.

**Comment by asdil12** [comment]
Updated PR

**Comment by asdil12** [comment]
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9706#issuecomment-595238820

**Pull request merged**
