### PR TITLE
Move powerpc-utils from console to qam-mininal

### PR DESCRIPTION
**Pull request by Zaoliang**
this is a regression test for qam, so we should move it to qam-minimal.
Request from @dzedro. See related poo#49025 and yaml schedule change:
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/commit/59eba8b71315ffd354dbfc4555d91fc3da92cfa1

### CODE REVIEW

**Comment by foursixnine** [comment]
@Zaoliang why the move? (other than what the title is saying) I just want to understand the change better

**Comment by okurz** [comment]
Santiago's comment brings me to:

The commit message could have a bit more details, e.g. **what issue is fixed, why this needs to change**, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

**Comment by Zaoliang** [comment]
the only reason for the move is that test module powerpc-utils "belongs" to qam, this is because of request from @dzedro regarding to schedule on osd.

**Comment by Zaoliang** [comment]
since the request was coming from qam, so we should follow the request at first, if it makes sense to schedule powerpc-utils for functional, then we can do this as well.

**Comment by dzedro** [comment]
https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/72 is merged

**Pull request closed without merging**
