### PR TITLE
Scheduling yast2_gui with yaml scheduling

### PR DESCRIPTION
**Pull request by rwx788**
Third attempt to get #6951 on prod.
Now package is available for aarch64 and power workers.

## Verification runs
 * [ppc64le](https://openqa.suse.de/tests/2543729)
 * [64bit](https://openqa.suse.de/t2543730)
 * [aarch64]( https://openqa.suse.de/t2543731)

### CODE REVIEW

**Comment by rwx788** [comment]
As we are going to have RC1, I would postpone deployment (just to play it safe).

**Comment by jknphy** [comment]
Thanks for revive it. Code looks the same than reverted. Regarding VRs for other architectures I didn't have time to learn how to use `clone-git-ref` but I think you might have pasted wrong links for them, could it be?

**Comment by rwx788** [comment]
@jknphy package was missing (or failed to get installed to be more precise) on power and aarch workers, that's why I've added VR for those. Using script is trivial, e.g.:
`openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7046 https://openqa.suse.de/tests/2536521` 
You can append some parameters if needed. I could not make it find apikeys, so pass them on command line.

**Comment by jknphy** [comment]
> @jknphy package was missing (or failed to get installed to be more precise) on power and aarch workers, that's why I've added VR for those. Using script is trivial, e.g.:
> `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7046 https://openqa.suse.de/tests/2536521`
> You can append some parameters if needed. I could not make it find apikeys, so pass them on command line.

Thanks for the info. Where is that executable? Perhaps in another repo or part of the clone job (that I cannot find because I might not have my systems up-to-date). I'm not sure where is the doc of that feature or the exact name.

**Comment by rwx788** [comment]
> > @jknphy package was missing (or failed to get installed to be more precise) on power and aarch workers, that's why I've added VR for those. Using script is trivial, e.g.:
> > `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7046 https://openqa.suse.de/tests/2536521`
> > You can append some parameters if needed. I could not make it find apikeys, so pass them on command line.
> 
> Thanks for the info. Where is that executable? Perhaps in another repo or part of the clone job (that I cannot find because I might not have my systems up-to-date). I'm not sure where is the doc of that feature or the exact name.
> I think the last, checking other progress tickets I found: `/usr/share/openqa/script/openqa-clone-custom-git-refspec` so I guess that I will need to update my system in some moment.
> My initial search was not good enough :) https://github.com/os-autoinst/openQA/blob/master/script/openqa-clone-custom-git-refspec. I guess even without updating the system I could use it. I will give it a try in some moment. Thanks for the info.

It's actually packages as part of openQA-client, so you can install/update it.

**Pull request merged**
