### PR TITLE
Optimization of image creator test.

### PR DESCRIPTION
**Pull request by psladek**
- package selection more robust and reliable
- put duplicated code into common library
- some check_screen replaced with assert to improve
  reaction time in both cases of detection/nondetection
- minor bug fixes and optimizations

### CODE REVIEW

**Comment by asmorodskyi** [comment]
how this PR correlate with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2613 ? it's look like you try to create same file, no ?

**Comment by psladek** [comment]
This PR is for sle11 branch, basically same as the one for master ( #2613 is in fact twopart PR, for sle11 the first one was already accepted (#2611), this is second part)

**Comment by okurz** [comment]
please see my comment about the dot at EOL

**Comment by psladek** [comment]
yes, I have seen it

**Pull request merged**
