### PR TITLE
Firefox new version on all sle distros except sle12sp4

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://progress.opensuse.org/issues/42611
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/966
- Verification run:
[sle12](http://10.100.12.155/tests/8193)
[sle12sp1](http://10.100.12.155/tests/8192)
[sle12sp2](http://10.100.12.155/tests/8211)
[sle12sp3](http://10.100.12.155/tests/8219)
[sle12sp4](http://10.100.12.155/tests/8191)
[sle15](http://10.100.12.155/tests/8196)

### CODE REVIEW

**Comment by rwx788** [comment]
Do we need new needles for openSUSE?

**Comment by dzedro** [comment]
@rwx788 firefox-regression tests are not running on opensuse, maybe in future

**Comment by dzedro** [comment]
Will run it on opensuse too, now it should be highly possible, all latest changes were because of firefox update to never version, I guess with small changes it should be compatible with opensuse firefox version :eyes:

**Comment by rwx788** [comment]
Sure, I've asked to confirm that we are not missing needles.

**Pull request merged**
