### PR TITLE
Fix thunderbird test issues due to package update

### PR DESCRIPTION
**Pull request by rfan1**
poo#116524

- Related ticket: https://progress.opensuse.org/issues/116524
- Needles: a set of needles have be uploaded
- Verification run: 

[qam-mail-thunderbird](https://openqa.suse.de/tests/9536848#)
[qam-regression-message](https://openqa.suse.de/tests/9536872#)

### CODE REVIEW

**Comment by rfan1** [comment]
@paolostivanin @martinsmarcelo could you please help review my PR?

**Comment by GraceWang571** [comment]
I saw the verification runs covered 15SP3. Could you please verify if the PR works on 15SP4? Because since 15SP4 the GNOME version got updated to 41.2 not 3.xx any more.

**Comment by rfan1** [comment]
> I saw the verification runs covered 15SP3. Could you please verify if the PR works on 15SP4? Because since 15SP4 the GNOME version got updated to 41.2 not 3.xx any more.

We don't run the tests on 15sp4 MU, however, I can pass the tests for GA https://openqa.suse.de/tests/9562540#

**Comment by paolostivanin** [comment]
LGTM

**Comment by GraceWang571** [comment]
LGTM

**Pull request merged**
