### PR TITLE
use http repos for sles and sdk

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
this is basically a workaround for os-autoinst not registering the ISOs unless installing with ADDONS

**Comment by sysrich** [comment]
Is there any point then given that's fixed in the latest os-autoinst?

**Comment by coolo** [comment]
and it's still using check_screen at the end

**Comment by coolo** [comment]
see https://openqa.suse.de/tests/108824/modules/acceptance/steps/58

**Comment by coolo** [comment]
we can remove the hunks when the ISOs work - but for now I would like to get this rolling without a deployment

**Comment by sysrich** [comment]
agreed, woulda merged it if you didn't just beat me to it ;)

**Pull request merged**
