### PR TITLE
Remove unused $self from launch_yast2_module_x11

### PR DESCRIPTION
**Pull request by OleksandrOrlov**
The commit removes $self from the function as a first parameter, as it
is does not share any context with the package where it is defined.
Also $self is not used inside the function.

- Verification runs: 
   - https://openqa.suse.de/tests/5687489
   - https://openqa.suse.de/t5687488

### CODE REVIEW

**Comment by jknphy** [comment]
LGTM

**Comment by OleksandrOrlov** [comment]
> LGTM, is ready?

It is ready now, as I waited for #12127 to be merged first.

**Comment by dzedro** [comment]
This broke https://openqa.suse.de/tests/5741856#step/usr_sbin_smbd/17

**Comment by OleksandrOrlov** [comment]
@dzedro, @jknphy I've added fix in #12205

**Comment by dzedro** [comment]
Thank you

**Pull request merged**
