### PR TITLE
yast2_firewall: Bump timeout in zypper_call

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/25634

### CODE REVIEW

**Comment by mitiao** [comment]
I remember the default timeout of zypper_call is 700

**Comment by DrMullings** [comment]
Why is this necessary? Seems legit though

**Comment by okurz** [comment]
In every occassion when we might install something from remote repos there are components involved which are not under our complete control, e.g. infrastructure so we should be more forgiving. The progress ticket mentions a failure that was because of timeout on `zypper_call`

**Comment by okurz** [comment]
Missed the comment by @mitiao. I checked. Yes, the zypper call timeout is 700 by default so my change does not make sense at all. I will propose 1200 here. See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3799

**Pull request merged**
