### PR TITLE
Jeos kiwi rpm

### PR DESCRIPTION
**Pull request by mloviska**
- Verification run: [sle-15-SP1-JeOS-for-kvm-and-xen-x86_64](https://openqa.suse.de/t4086301)

### CODE REVIEW

**Comment by Vogtinator** [comment]
Is this test also running on Leap? If so, this would break it.

**Comment by mloviska** [comment]
> Is this test also running on Leap? If so, this would break it.

I have added it only to yaml file personally. Thus, it is not in opensuse at all to my knowledge. But let me check

**Comment by Vogtinator** [comment]
I kind of expected that the introduction of the yaml schedule will make the openSUSE test coverage worse for no reason - this confirms it. Is there a good reason it's only testing SLE currently?

**Comment by mloviska** [comment]
> Is this test also running on Leap? If so, this would break it.

not in leap15{1,2} images nor main group of TW

**Comment by mloviska** [comment]
> I kind of expected that the introduction of the yaml schedule will make the openSUSE test coverage worse for no reason - this confirms it. Is there a good reason it's only testing SLE currently?

AFAIR when we had this discussion, the point was to make SLE test suite stable (reduce the randomness of shifting test cases ) and to test modules which make sense to be tested there.
The main argument why not to do yaml in openSUSE, was that we will lose track of new modules, which might be beneficial in JeOS testing.

**Pull request merged**
