### PR TITLE
Aligned to installation-images update

### PR DESCRIPTION
**Pull request by nilxam**

### CODE REVIEW

**Comment by okurz** [comment]
Could you maybe reference the broken test this change fixes? Any maybe also reference the changes which make this change necessary?

**Comment by nilxam** [comment]
https://openqa.opensuse.org/tests/101946 and in my comment out - installation-images 14.210

**Comment by okurz** [comment]
cool, thx.

:+1:

**Comment by nilxam** [comment]
Do not merge! I afraid this might break rescuresystem test on SLE, maybe we need a rescuresystem_sle12.pm and update main.pm.

**Comment by coolo** [comment]
how about check_screen? sle12 sp1 has it not, sp2 will most likely get it

**Comment by sysrich** [comment]
Yeah, would be nice to have it figure out if a 'more' button is present, and use it if required, then we can keep it all in one test.

**Pull request merged**
