### PR TITLE
[qa_automation] Use virtio console if VIRTIO_CONSOLE is set to 1

### PR DESCRIPTION
**Pull request by jtzhao**
Use virtio console in qa tests

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@richiejp I think you might be interesting in this

**Comment by richiejp** [comment]
I would have thought that it would only be necessary to add this to install_kotd for fixing KOTD?

I think it is a good idea to add it elsewhere, but if these modules are used in a lot of tests it is a bit risky (I'm not sure what qa_automation is used for).

**Comment by jtzhao** [comment]
@richiejp qa_automation tests are regression tests used by qa team. Why is it risky to use root-virtio-terminal console in qa tests, if it works in other places?

**Comment by richiejp** [comment]
Some of the helper methods have not been ported to use it (e.g. they use assert_screen or are hard coded to expect all text output on /dev/ttyS0). It looks like it should work where you have used it, but it is hard to tell until it has been tested.

**Pull request closed without merging**
