### PR TITLE
New test for yast2-nfs-client and reactivation of yast tests

### PR DESCRIPTION
**Pull request by ancorgs**
Depends on https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/42

Verified that the new test and also the disabled tests are already working in Tumbleweed (they were disabled because I merged them too fast and they broke staging).

### CODE REVIEW

**Comment by sysrich** [comment]
@ancorgs are these tests also going to be activated for SLE12? if so, please send a PR for the sle12 branch

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/78323/modules/yast2_nfs_client/steps/6 looks like nobody ever even tested this... 

on Leap 42, the whole thing looks even worse.

**Comment by sysrich** [comment]
Please go ahead and revert

@ancorgs was this tested before submitting?

**Comment by DimStar77** [comment]
Results on Leap 42.1 for reference: https://openqa.opensuse.org/tests/78357/modules/yast2_cmdline/steps/7 (and follow-up yast tests)

**Comment by ancorgs** [comment]
@sysrich Of course it was. It runs as expected in my openQA instance with Tumbleweed 20150811 (everything ok) and in  20150728 (failing because of the broken package, not the test) .

**Comment by sysrich** [comment]
@ancorgs https://openqa.opensuse.org/tests/78323/modules/yast2_nfs_client/steps/6 how does your test of the test avoid this bash syntax error?

**Comment by ancorgs** [comment]
@sysrich This is how it looks in my instance with both  20150811 and  20150728
 http://paste.opensuse.org/83533396

And about the other failures in Leap. They are not failures of the test. One package is not present and the other one is actually missing for the distribution. So tests are really failing. The only broken test is the nfs-client one.

**Comment by sysrich** [comment]
@ancorgs why the mismatch in the packages being installed in production and in your screenshot? Is your test environment setup to do full test runs with installs, et al, or are you doing some magic which could be invalidating your test guests as a similie for the way openQA runs live?

**Comment by ancorgs** [comment]
@sysrich I usually do a installation with INSTALLONLY and PUBLISH_HDD1 and then run the just application tests from there (if you are a developer writing tests for applications you really don't want to test the full installation on every run).

It's true I didn't test a full run without the INSTALLONLY before submitting, but I (wrongly) assumed that the result must be the same doing "install - reboot - test applications" than doing "install - store image - boot image - test applications".

**Comment by ancorgs** [comment]
@DimStar77 When I said "One package is not present and the other one is actually missing for the distribution" I meant that one package is failing and the other one is missing.

**Comment by sysrich** [comment]
@ancorgs the only way I can explain this is that there must have been some modifications to your stored image which invalidates the authenticity of your local tests. Different package installs, modifications to config files, stuff like that. A clean-room install of the tests, done in the way you have coded them, clearly don't work (because of missing entries in /etc/exports?)

Maybe it would be better to use the documented MAKETESTSNAPSHOTS / SKIPTO features so you can initerate your development of your tests quickly?

(And Ancor, buddy, I hope you didn't mean to sound as condadencing as I felt you were with your "if you are a developer" comment

I am a developer, among other things. I know what you're trying to achieve and how efficiently you need to achieve it. But I also have a responsibility to make sure the tests going into openQA are of a good enough quality that they produce helpful results - in Leap with this test it seems to be true, in TW, not)

**Comment by ancorgs** [comment]
@sysrich It was not condescending at all and I don't know why you got it that way. Believe me.

I was just trying to highlight something that I have been told by many people: that the current openQA workflow and approach does not seem to fit the expectations of people developing new features or closing bugs that simply want to contribute an integration test for it. You can hardly expect them to run the full installation several times for TW (even Factory to check staging), Leap, SLE, etc. As a developer (term not used in any condescending way), you need shortcuts.

**Comment by ancorgs** [comment]
@sysrich There is no modification /etc/exports in my image. The difference in the result is because bash is accepting something in my tests that raise a syntax error in openqa.o.o. It could be a difference in bash (I don't expect that) or (most likely) because the content of the current directory (/tmp) is different and the "*" is expanded in different ways (since it's not properly scaped). Thus, I think the problem is that the test is not robust enough (it can be broken by the testmodules run before), not any difference in the system.

**Comment by sysrich** [comment]
@ancorgs both https://openqa.opensuse.org/tests/78323/modules/yast2_nfs_client/steps/6 (production) and http://paste.opensuse.org/83533396 (your test environment) ran the test in the same current working directory (/tmp)

There is no way I can buy the suggestion that your disk image is pristine - look at the zypper in earlier in both tests. on openqa.opensuse.org it wants to install 3 packages. in your test environment it wants to install only 1

We have shortcuts for developers creating openQA tests. For example, we advocate heavy use of VM snapshoting to make sure your test environment is kept as clean and pristine as possible. I'm pretty certain that your local VM is not in a perfectly clean state after it's INSTALLONLY. I'd recommend you use snapshots heavily to make sure it is in the future. You can even use openQA's MAKETESTSNAPSHOT and SKIPTO features in your isotovideo vars.json to do the snapshotting for you..thats how I do it when I'm developing my tests

**Comment by ancorgs** [comment]
@sysrich I still believe my image is pristine. But, as you can see here, we are using a different initial set of installation settings (http://paste.opensuse.org/28636037 vs https://openqa.opensuse.org/tests/78323/modules/installation_overview/steps/1). So I would have made the same error using  MAKETESTSNAPSHOT (which, if I got it correctly, other people in my team has discouraged because it ate too much hard disk).

Anyway, I have to admit I didn't expect the tests to be run in staging (I consider them more like integration tests than pre-integration one) or in Leap. I just wanted to contribute some tests that I considered useful (although it has been proven that one of them is not robust enough) to test Tumbleweed to verify we don't release a broken snapshot. I bravely added then to main.pm (my fault), but I have to admit that I expected somebody else to decide what is used for testing Staging or to test Leap and to do the needed adjustments, because I'm quite uncertain, as many developers, about the mechanisms used by the openQA operators.

Once again, the word "developer" is used in the previous text without condescendence. But I live in both worlds (as a former openQA developer and now trying to close bugs like crazy and make sure they don't re-appear) and I believe we need more guidance to people that wants to contribute tests (that's something I hear every time I try to advocate openQA, no matter with who). The openQA use case is quite complex and most people just one to contribute a test for you guys to use where needed and when needed. And it will happen a million times that the contributed test works in some cases (like a full KDE installation with no "conflicting" testmodule run before) and breaks in another (like a minimal X11 installation with many consoletests running before). That doesn't mean that the developer didn't tested at all.

In my opinion (and maybe I'm being a little big picky), the current thread can be interpreted as some push back. Something we need to avoid.

**Pull request merged**
