### PR TITLE
Fix condition created by #14207

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14207
- Verification run: 
http://openqa.suse.de/t8133984
http://openqa.suse.de/t8133985
http://openqa.suse.de/t8133986

### CODE REVIEW

**Review by Vogtinator — CHANGES_REQUESTED** [review]
`is_sle_micro` does not accept a version parameter, which is why I used `is_microos`, which should. Apparently that's not working correctly?

**Comment by jlausuch** [comment]
> `is_sle_micro` does not accept a version parameter, which is why I used `is_microos`, which should. Apparently that's not working correctly?

I'm adding that version check functionality in `is_sle_micro`. Let me run some VRs.

**Comment by Vogtinator** [comment]
Please also run a VR on TW for completeness

**Comment by jlausuch** [comment]
VRs:
https://openqa.suse.de/tests/8134369#step/enable_selinux/25
https://openqa.suse.de/tests/8134366#step/enable_selinux/26
https://openqa.suse.de/tests/8134367#step/enable_selinux/26

@Vogtinator are you ok with the version check addition?

**Comment by jlausuch** [comment]
TW: https://openqa.opensuse.org/tests/2181112#step/enable_selinux/14

**Review by mloviska — APPROVED** [review]

**Review by Vogtinator — APPROVED** [review]

**Pull request merged**
