### PR TITLE
New test cases for apparmor aa-autodep and aa-logprof

### PR DESCRIPTION
**Pull request by wnereiz**
New test cases for apparmor aa-autodep([poo#36889](https://progress.opensuse.org/issues/36889)) and aa-logprof([poo#36892](https://progress.opensuse.org/issues/36892))

- Related ticket:
  - aa-autodep: https://progress.opensuse.org/issues/36889
  - aa-logprof: https://progress.opensuse.org/issues/36892
- Verification run:
  - SLE: http://10.67.17.9/tests/777
  - Tumbleweed: http://10.67.17.9/tests/776

### CODE REVIEW

**Comment by okurz** [comment]
Functionally the changes look nice but I am a bit concerned about the future maintainability of the test code because of the code duplication you used. You can try [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself). You are calling the same code multiple times, please try to [extract methods](http://refactoring.com/catalog/extractMethod.html), e.g. to a common base class for these test modules? E.g. take a look how the test modules in tests/networkd/ use the base class from lib/networkdbase.pm

**Comment by wnereiz** [comment]
@okurz In which place do you think code duplication? I will check and try DRY to improve it.  If you mean main.pm or main_common.pm, I will open a new ticket in future to discuss about how to modify.

**Comment by wnereiz** [comment]
@okurz Very good suggestion. I'm looking into the example of lib/networkdbase.pm I'm going to create a base in lib/ . Do you think the name securitybase.pm is reasonable?

**Comment by okurz** [comment]
> Do you think the name securitybase.pm is reasonable?

yes, sounds useful

> And security cases will be not only apparmor testing

That's ok. You can then either let other security tests inherit on just the existing base clases and rename securitybase.pm to apparmorbase.pm or use inheritance over multiple levels.

> I think "post_run_hook" is not better used here

Even that could be overwritten in different clases. E.g. if you have 5 test modules that all use the same, define a "post_run_hook". If there is one additional one that uses the common base but has a special cleanup you can overwrite the "post_run_hook" in this very test module to be special.

**Comment by wnereiz** [comment]
@okurz Have changed as your suggestion. Verification run updated.

**Pull request merged**
