### PR TITLE
Create support image via autoyast with all patterns on SLE12SP5

### PR DESCRIPTION
**Pull request by rfan1**
https://progress.opensuse.org/issues/132653

The tests don't set separate /home partition,
so we can allocate more disk space to / partition.

VRs:
[create_hdd_imgs](https://openqa.suse.de/tests/overview?build=rfan0904_new&version=12-SP5&distri=sle)
[Sanity tests with published qcow2 imgs](http://openqa.suse.de/tests/overview?build=rfan0907&version=15-SP6&distri=sle)

### CODE REVIEW

**Comment by hjluo** [comment]
I think you'd add your test cases in https://openqa.suse.de/admin/job_templates/520 for deployment.

**Comment by lemon-suse** [comment]
> I think you'd add your test cases in https://openqa.suse.de/admin/job_templates/520 for deployment.

Yes, we need save all support images test suites in the job group although it is not controlled in gitlab.
The qcow name is not as expected:  PUBLISH_HDD_1 | all-ptterns-x86_64.qcow2  It should be 'autoyast-SLES-12-SP5-x86_64-GM-all-patterns-updated.qcow2'. 

Others LGTM.

**Comment by rfan1** [comment]
> > I think you'd add your test cases in https://openqa.suse.de/admin/job_templates/520 for deployment.
> 
> Yes, we need save all support images test suites in the job group although it is not controlled in gitlab. The qcow name is not as expected: PUBLISH_HDD_1 | all-ptterns-x86_64.qcow2 It should be 'autoyast-SLES-12-SP5-x86_64-GM-all-patterns-updated.qcow2'.
> 
> Others LGTM.

Thanks, once it gets merged, I will add the tests into the job group

**Comment by chcao** [comment]
LGTM

**Comment by rfan1** [comment]
Job group is modified [adding the corresponding tests]

**Review by lemon-suse — APPROVED** [review]

**Pull request merged**
