### PR TITLE
Schedule Samba/AD tests

### PR DESCRIPTION
**Pull request by foursixnine**
VR: http://phobos.qa.suse.de/tests/3857465
Ticket: https://progress.opensuse.org/issues/72169

### CODE REVIEW

**Review by pdostal — APPROVED** [review]

**Review by pdostal — APPROVED** [review]
Now even better :)

**Comment by DimStar77** [comment]
> Now even better :)

Except on Tumbleweed - where the VR was missing and the result is:
  https://openqa.opensuse.org/tests/1709941#step/samba_adcli/25

**Comment by foursixnine** [comment]
@DimStar77 my bad! https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12384

**Comment by DimStar77** [comment]
> @DimStar77 my bad! #12384 In any case, now that is raised... I wonder if you see a benefit into having the same setup for TW/Leap? I don't imagine many Leap/TW users running their own AD infra or joining domains..

The advantage of running it on TW would be that 'before you branch SLE 16 or get any samba updates from TW to SLE15SPx, you know it already works' (or not, depending on the test result)

**Comment by foursixnine** [comment]
> > @DimStar77 my bad! #12384 In any case, now that is raised... I wonder if you see a benefit into having the same setup for TW/Leap? I don't imagine many Leap/TW users running their own AD infra or joining domains..
> 
> The advantage of running it on TW would be that 'before you branch SLE 16 or get any samba updates from TW to SLE15SPx, you know it already works' (or not, depending on the test result)

Yeah, this one I see clearly

**Pull request merged**
