### PR TITLE
Fix autoyast_btrfs profile

### PR DESCRIPTION
**Pull request by jknphy**
Fixes https://openqa.suse.de/tests/4102690 related with bug https://bugzilla.suse.com/show_bug.cgi?id=1160969
Unfortunately after many trys I was not able to determine which xml tag(s) I removed that make the difference. I tried among other options with obvious candidate, 'software' section, but no luck.

- Verification run: https://openqa.suse.de/tests/4106467

### CODE REVIEW

**Comment by b10n1k** [comment]
Can i suggest to merge this and open a ticket to test it again with old xml once the bug is solved? the problem is indeed hidden but we can track it down, right?. Maybe it is obvious but i am just saying.

**Comment by jknphy** [comment]
> Can i suggest to merge this and open a ticket to test it again with old xml once the bug is solved? the problem is indeed hidden but we can track it down, right?. Maybe it is obvious but i am just saying.

I provided [more info](https://bugzilla.suse.com/show_bug.cgi?id=1160969#c17) to the bug, it is not even clear that is the xml the problem... it only seems that make more stable some sporadic failure.

**Comment by rwx788** [comment]
> Can i suggest to merge this and open a ticket to test it again with old xml once the bug is solved? the problem is indeed hidden but we can track it down, right?. Maybe it is obvious but i am just saying.

As that problem is not related to the test itself (we test multi btrfs here), let's merge. @jknphy could you please file a ticket to test regression from [bsc#1160969](https://bugzilla.suse.com/show_bug.cgi?id=1160969)?

**Comment by jknphy** [comment]
> > Can i suggest to merge this and open a ticket to test it again with old xml once the bug is solved? the problem is indeed hidden but we can track it down, right?. Maybe it is obvious but i am just saying.
> 
> As that problem is not related to the test itself (we test multi btrfs here), let's merge. @jknphy could you please file a ticket to test regression from [bsc#1160969](https://bugzilla.suse.com/show_bug.cgi?id=1160969)?
Created:
https://progress.opensuse.org/issues/65756

**Comment by jknphy** [comment]
> > > Can i suggest to merge this and open a ticket to test it again with old xml once the bug is solved? the problem is indeed hidden but we can track it down, right?. Maybe it is obvious but i am just saying.
> > 
> > 
> > As that problem is not related to the test itself (we test multi btrfs here), let's merge. @jknphy could you please file a ticket to test regression from [bsc#1160969](https://bugzilla.suse.com/show_bug.cgi?id=1160969)?

Created:
https://progress.opensuse.org/issues/65756

**Pull request merged**
