### PR TITLE
Update upgrade tests SF2 -> firewalld

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/55148
Verification: https://openqa.opensuse.org/t999733

### CODE REVIEW

**Comment by DimStar77** [comment]
so we accept replacing a so-far understood issue (sfw2 not found) with a completely new one, where the verification run fails on consoletest_finish?

**Comment by asdil12** [comment]
This looks like a product bug due to SF2 being removed within migration.

**Comment by DimStar77** [comment]
That we can't even switch to X anymore?

**Comment by DimStar77** [comment]
but in fact you very much confirm what I expected: 'it looks like' means 'it is not clear/fully understood'

**Comment by asdil12** [comment]
The *cannot switch to X* issue appeard already after my fix: https://openqa.opensuse.org/tests/999330#

**Comment by DimStar77** [comment]
hm.. strange one - but ok... let's start off with a product bug to check why firewalld is not being enabled in this migration scenario.. Can you please file a bug for that?

**Comment by DimStar77** [comment]
I filed https://bugzilla.opensuse.org/show_bug.cgi?id=1144543

**Pull request merged**
