### PR TITLE
Fix empathy irc and gedit about tests

### PR DESCRIPTION
**Pull request by mitiao**
- both tests are always failed at certain step due to
   'wait_screen_change' affected by desktop effects, use
   'assert_screen' to instead of it

 - use default timeout for previous 'assert_screen' lines

### CODE REVIEW

**Comment by okurz** [comment]
where are the corresponding needles? Can you make a PR on https://github.com/os-autoinst/os-autoinst-needles-opensuse or the SLE needle repo?

**Comment by mitiao** [comment]
Just send a PR with only 1 needle to SLE needle repo.

And I have a question about SLE needle repo:
firefox-click-customize-scrollbar-20160226 needle replaced 20151010 one and merged a day ago, but it could not be found in the lasted regression test ran about 8 hours ago, the test was still using 20151010 needle. 
https://openqa.suse.de/tests/281665/modules/firefox_rss/steps/7

Something wrong?

**Comment by coolo** [comment]
yes, fetchneedle is not fetching needles. and what's similiarly worse: it no longer git pushes commits

**Comment by mitiao** [comment]
I see. Thanks for this info.

**Pull request merged**
