### PR TITLE
Do not create autoyast profile in some conditions

### PR DESCRIPTION
**Pull request by nilxam**

### CODE REVIEW

**Comment by nilxam** [comment]
I'll merge it now since next pulling is in 4 minutes, will to see how this work for staging...

**Comment by coolo** [comment]
isn't this backward? shouldn't we enable this autoyast feature only on request? right now we're changing opensuse's default in every single installation.

**Comment by nilxam** [comment]
hmm..what does :only on request" mean? another test for autoyast profile only?
and I don't understand about changing default in every single installation...maybe my brain is slow today :/

**Comment by coolo** [comment]
not necessarly another test, but at least trigger the autoyast test depending on some condition. E.g. only if DESKTOP=textmode or only if ... I don't mind. But changing it always unconditionally sounds really bad.

**Comment by nilxam** [comment]
ok, I got it, and I also see a bug in my commit, will fix it soon...

**Comment by coolo** [comment]
I guess there is something in sle12 to be adopted? https://openqa.suse.de/tests/178548

**Pull request merged**
