### PR TITLE
skip testing NFSv2 on tumbleweed

### PR DESCRIPTION
**Pull request by dirkmueller**
https://progress.opensuse.org/issues/106679

### CODE REVIEW

**Comment by asdil12** [comment]
Could you provide a verification run?

**Comment by dirkmueller** [comment]
I have no idea how to do that, could you please point me to the documentation?

**Comment by asdil12** [comment]
You could use this script to clone an existing job using the tests from this PR if you have enough permissions on openQA:
https://github.com/os-autoinst/openQA/blob/master/script/openqa-clone-custom-git-refspec

Otherwise just tell me which job to clone and I can schedule it for you.

**Comment by dirkmueller** [comment]
this job should be fixed with this change: https://openqa.opensuse.org/tests/2185323/modules/yast2_nfs_server/steps/14 (as linked in the linked poo ticket)

**Comment by asdil12** [comment]
> this job should be fixed with this change: https://openqa.opensuse.org/tests/2185323/modules/yast2_nfs_server/steps/14 (as linked in the linked poo ticket)

That one doesn't seem to exist anymore so I won't be able to clone from it.
Could you provide a link to a more recent job that I can clone from?

**Comment by dirkmueller** [comment]
> That one doesn't seem to exist anymore so I won't be able to clone from it. Could you provide a link to a more recent job that I can clone from?

well, that is unfortunate timing, it was accessible when I pasted it. 

Is https://openqa.opensuse.org/tests/2248451 better ?

basically anything that calls the `try_nfsv2` function will do.

**Comment by asdil12** [comment]
```
$ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14447 https://openqa.opensuse.org/tests/2248451
Created job #2251326: opensuse-Tumbleweed-DVD-x86_64-Build20220316-yast2_nfs_v4_server@64bit -> https://openqa.opensuse.org/t2251326
```
https://openqa.opensuse.org/t2251326

**Comment by asdil12** [comment]
```
$ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14447 https://openqa.suse.de/tests/8346367
Created job #8351804: sle-15-SP4-Online-x86_64-Build113.1-yast2_nfs_v4_server@64bit -> https://openqa.suse.de/t8351804
```
https://openqa.suse.de/t8351804

**Comment by asdil12** [comment]
@dirkmueller does this look right? 
https://openqa.suse.de/t8351804

Not sure why the other job on osd has dns issues.

**Comment by dirkmueller** [comment]
https://openqa.suse.de/tests/8351804#step/yast2_nfs4_server/61 looks good to me. i also don't see issues in the autoinst-log.txt so I guess it is okay? I have no clue about openqa :)

**Review by asdil12 — APPROVED** [review]

**Pull request merged**
