### PR TITLE
vim: vim-data is not installed on aarch64 JeOS anymore

### PR DESCRIPTION
**Pull request by ggardet**
so remove the aarch64 specific code

- Related ticket: https://progress.opensuse.org/issues/102365

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
nitpick: There should be no comma at the EOL of the git commit message subject line

**Comment by ggardet** [comment]
> nitpick: There should be no comma at the EOL of the git commit message subject line

Fixed.

**Review by okurz — APPROVED** [review]
@jlausuch to review for impact on SLE JeOS

**Comment by ggardet** [comment]
Parallel slightly different submission: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13684

**Comment by jlausuch** [comment]
> Parallel slightly different submission: #13684

Which one should we go for? :)

**Comment by ggardet** [comment]
> > Parallel slightly different submission: #13684
> 
> Which one should we go for? :)

The one you prefer ;)

**Review by okurz — APPROVED** [review]
Ok, let me help you with the decision :)

**Pull request merged**
