### PR TITLE
Add PBOffline to test the support for sle15sp5, and remove the blackl…

### PR DESCRIPTION
**Pull request by simonlm**
Add PBOffline to test the support for sle15sp5, and remove the blacklist when installing the system
- Verification run: 
- http://10.67.129.4/tests/52364
- http://10.67.129.4/tests/52355
- http://10.67.129.4/tests/52358
- http://10.67.129.4/tests/52361

### CODE REVIEW

**Comment by Dawei-Pang** [comment]
@JoyceNa would you please help to take a look? Thanks!

**Comment by JoyceNa** [comment]
LGTM

**Comment by Dawei-Pang** [comment]
LGTM, thanks!

**Review by Amrysliu — APPROVED** [review]
LGTM

**Pull request merged**
