### PR TITLE
Fix tidy fails

### PR DESCRIPTION
**Pull request by OleksandrOrlov**
Perl::Tidy is failing locally, due to not proper code formatting. What is weird, it is still passing on github.
Me and @rwx788 faced the same issue on local environment.

The commit adds the changes made by tools/tidy script on my local environment.

The PR is added at least to check if Travis will accept the introduced changes.

### CODE REVIEW

**Comment by rwx788** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6847 travis worked fine with that one, but my tidy fails on it too... Not sure what's the issue.

**Comment by OleksandrOrlov** [comment]
@foursixnine, would you mind to assist us with the problem?

Could you please run tools/tidy on your local environment with the latest changes on 'master' and check if it will fail for you.

**Comment by foursixnine** [comment]
@OleksandrOrlov sure :)

**Comment by okurz** [comment]
I will also check locally.

**Comment by foursixnine** [comment]
@rwx788 @OleksandrOrlov, all fine here with current master of os-autoinst and test distri:
```
$  make tidy
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ perl -MPerl::Tidy -e 'print $Perl::Tidy::VERSION ."\n";'
20181120
```

**Comment by OleksandrOrlov** [comment]
@foursixnine , @okurz Ok. Thank you guys. Will try to identify the local problem.

**Comment by OleksandrOrlov** [comment]
According to our latest findings, there is actually the issue with tidy script.

Please, see the PR: https://github.com/os-autoinst/os-autoinst/pull/1116

**Comment by foursixnine** [comment]
@OleksandrOrlov Please fix the conflicts

**Comment by OleksandrOrlov** [comment]
@foursixnine Done. All the checks passed.

**Pull request merged**
