### PR TITLE
[virt_autotest] Support guest sles-12-sp5 for virt_v2v test

### PR DESCRIPTION
**Pull request by guoxuguang**
- Needles: 
[virt_autotest] Add needles for virt_v2v test
https://gitlab.suse.de/qa-testsuites/os-autoinst-needles-sles/merge_requests/2
- Verification run: 
SLES12SP5
virt-v2v-developing-from-developing-to-developing-xen-src
http://10.67.20.146/tests/21
virt-v2v-developing-from-developing-to-developing-kvm-dst
http://10.67.20.146/tests/22

### CODE REVIEW

**Comment by guoxuguang** [comment]
@alice-suse @Julie-CAO @michelmno @waynechen55 Please help me review this PR.

**Comment by alice-suse** [comment]
From http://10.67.20.146/tests/22, the uploaded grub.cfg file, it seems that your code actually does not work. The terminal lines are not as expected.

**Comment by alice-suse** [comment]
Sorry,  my misunderstanding. It should be fine.

**Comment by Julie-CAO** [comment]
LGTM

**Pull request merged**
