### PR TITLE
autoyast/console: Remove workaround for VERIFIED FIXED bsc#1042554

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@rwx788 could you test this?

**Comment by rwx788** [comment]
@okurz no, sorry, I doubt I'll have a chance for that today.

**Comment by okurz** [comment]
@rwx788 I set the bug to VERIFIED FIXED for both SLE15 as well as SLE12 SP4 build 0239 now. Also rebased to fix conflict. Good to go?

**Comment by rwx788** [comment]
@okurz, finally! It was failing on SLE15 cause of this workaround, but we fixed that with tty-selected mechanism =)

**Pull request merged**
