### PR TITLE
livecdreboot: LiveCDs do not have inst-linux terminals running, as th…

### PR DESCRIPTION
**Pull request by DimStar77**
…ey spawn the live installer directly...

That should help us get a bit further with the liveCDs again...

### CODE REVIEW

**Comment by DimStar77** [comment]
@sysrich you might want to have a word here...

**Comment by sysrich** [comment]
um how is this expected to work with non-live CD installs which DO have inst-linux terminals?

**Comment by DimStar77** [comment]
erm.. we use LIVECDreboot.pm on NON-Live CDs??

**Comment by sysrich** [comment]
Yes, we use livecdreboot.pm on every single installation

It's the worst named test ever 

https://openqa.suse.de/tests/114635/modules/livecdreboot/steps/2

**Comment by DimStar77** [comment]
dang,... missed that.. then we need to base this on variable.. LIVECD or LIVETEST is hopefully good enough here

**Comment by sysrich** [comment]
LIVECD=1 is already set on the live CD tests, so you might as well reuse that variable

**Comment by DimStar77** [comment]
yes, that's what I wanted; no new variable.. and seems LIVECD is good enough for it

**Comment by sysrich** [comment]
I'd happily accept any PR that also renames this test, but it'll need matching PR's for every main.pm ;)

**Pull request merged**
