### PR TITLE
Remove LV with dmsetup remove before lvremove in sles4sap/hana_install

### PR DESCRIPTION
**Pull request by alvarocarvajald**
There is a sporadic issue with `sles4sap/hana_install` in MACHINE 64bit-ipmi-nvdimm in osd which is tracked in [poo#96833](https://progress.opensuse.org/issues/96833). This PR attempts to fix it by removing DM structures earlier with `dmsetup remove` before any calls to `lvremove`, `vgremove` and `pvremove`.

In cases where this is not enough, the test will fail with a reference to the poo ticket, and will attempt to gather more details during the failure to further debug the issue.

- Related ticket: https://progress.opensuse.org/issues/96833 & https://jira.suse.com/browse/TEAM-4526
- Needles: N/A
- Verification runs (original PR): https://openqa.suse.de/t6838584 - https://openqa.suse.de/t6838585
- Verification runs (remove LV with dmsetup before lvremove): https://openqa.suse.de/tests/6860658 - https://openqa.suse.de/tests/6860657 - https://openqa.suse.de/tests/6868507 - https://openqa.suse.de/t6868744 - https://openqa.suse.de/t6868749 - https://openqa.suse.de/t6868750 - https://openqa.suse.de/t6868751
- Verification runs (final): https://openqa.suse.de/t6882733  - https://openqa.suse.de/t6882735 - https://openqa.suse.de/t6882738 - https://openqa.suse.de/t6882740 - https://openqa.suse.de/tests/6884687

### CODE REVIEW

**Review by ricardobranco777 — COMMENTED** [review]
LGTM

**Review by bs-github — APPROVED** [review]
sleek with the loop in debug_locked_device 👍

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by ldevulder — APPROVED** [review]
LGTM

**Comment by alvarocarvajald** [comment]
Seems latest changes have consistently yielded positive results (12 consecutive tests passing). I think this can be merged. I will update the progress ticket, remove the WIP label and merge.

**Pull request merged**
