### PR TITLE
Virtualization: testsuite changes to adjust to the new ipmi backend

### PR DESCRIPTION
**Pull request by alice-suse**
To avoid the unstable ipmi, we use the new ipmi backend. With it, in test, during reboot or installation we can use sut console which relies on ipmi,  and after system boot up, we can use the root-ssh console which relies on ssh.

### CODE REVIEW

**Comment by coolo** [comment]
Your commit looks good, but I wonder why you have some Tumbleweed changes added to your branch. Rebase error?

**Comment by alice-suse** [comment]
I do not know how I get that commit, weird. I will remove it.

**Comment by alice-suse** [comment]
oh, i know why. When I merge the two commits, I used git rebase -i HEAD~3. And the unwanted commit is that tumbleweed one. So I should not remove it. I guess it is just the user changes.

**Comment by alice-suse** [comment]
I already changed testsuite in openqa.suse.de, so after merging, tests should be able to run.

**Comment by coolo** [comment]
I merged this manually - and rebased cleanly

**Pull request closed without merging**
