### PR TITLE
MicroOS: enable cockpit test in openSUSE MicroOS

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/93438

### CODE REVIEW

**Comment by Vogtinator** [comment]
LGTM, but VRs please (MicroOS image + Kubic DVD install)

**Comment by jlausuch** [comment]
[SLE Micro DVD inst](http://fromm.arch.suse.de/tests/1317)
[SLE Micro DVD inst autoyast](http://fromm.arch.suse.de/tests/1316)
[SLE Micro Image](http://fromm.arch.suse.de/tests/1323#)
[TW MicroOS Container-Host](http://fromm.arch.suse.de/tests/1322)
[TW Kubic DVD Container-Host](http://fromm.arch.suse.de/tests/1320)
[TW MicroOS-Image](http://fromm.arch.suse.de/tests/1319)
[Tumbleweed-MicroOS-Image-ContainerHost](http://fromm.arch.suse.de/tests/1321)

**Comment by jlausuch** [comment]
need to re-run O3 tests, as main.pm is not considered with the CASEDIR and refspec command didn't work.

**Comment by Vogtinator** [comment]
IIRC you can use `PRODUCTDIR` to work around that

**Review by Vogtinator — APPROVED** [review]

**Comment by jlausuch** [comment]
I found a problem in DVD flavor: http://fromm.arch.suse.de/tests/1324
I will try to run it in O3

**Comment by Vogtinator** [comment]
I only checked four of the VRs and didn't check the MicroOS DVD...

The failure is probably https://bugzilla.opensuse.org/show_bug.cgi?id=1186775

**Comment by jlausuch** [comment]
> I only checked four of the VRs and didn't check the MicroOS DVD...


Now in O3: https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=jlausuch%2Fos-autoinst-distri-opensuse%23enable_cockpit_opensuse&distri=microos

> 
> The failure is probably https://bugzilla.opensuse.org/show_bug.cgi?id=1186775

Ok, thanks for the pointer.
Shall we still merge even knowing this will mark the test red?

**Comment by Vogtinator** [comment]
> > I only checked four of the VRs and didn't check the MicroOS DVD...
> 
> Now in O3: https://openqa.opensuse.org/tests/overview?version=Tumbleweed&build=jlausuch%2Fos-autoinst-distri-opensuse%23enable_cockpit_opensuse&distri=microos
> 
> > The failure is probably https://bugzilla.opensuse.org/show_bug.cgi?id=1186775
> 
> Ok, thanks for the pointer.
> Shall we still merge even knowing this will mark the test red?

IMO yes, because if it's this easy to break the product it really should be red...

**Review by Vogtinator — CHANGES_REQUESTED** [review]
Actually, just saw an error with the scheduling.

The test module installs a package, but it's scheduled before the repo replacement. So it uses the wrong repo

**Comment by Vogtinator** [comment]
> > Actually, just saw an error with the scheduling.
> > The test module installs a package, but it's scheduled before the repo replacement. So it uses the wrong repo
> 
> you mean before `zypper_clear_repos.pm`? I have moved it now. Re-running VRs.

And the tests which add the new repos, yes.

**Review by Vogtinator — APPROVED** [review]

**Comment by jlausuch** [comment]
I will merge, the tests are green except this: https://openqa.opensuse.org/tests/1767711#step/cockpit_service/10
which looks like the same bug:

```
(22/25) Installing: cockpit-ws-245-1.1.x86_64 [............done]
Additional rpm output:
groupadd: Cannot determine your user name.
useradd: group 'cockpit-ws' does not exist
groupadd: Cannot determine your user name.
useradd: group 'cockpit-wsinstance' does not exist
warning: group cockpit-wsinstance does not exist - using root
```

**Comment by Vogtinator** [comment]
I notified RM

**Comment by DimStar77** [comment]
> I notified RM

This showing as broken on the product is ok - but unfortunately it also shows all staging projects failed now - which we cannot accept.

A possible solution would be to skip the test in staging until s fix already in the product (we are not regressing after all)

**Comment by Vogtinator** [comment]
Would `EXCLUDE_MODULES=cockpit_service` work until it's addressed in the product?

**Comment by Vogtinator** [comment]
The issue is actually completely different: https://openqa.opensuse.org/tests/1768812#step/cockpit_service/8

Staging tests have no repos, and `cockpit` isn't preinstalled. So this module just can't work. I'll make a PR to add an `unless is_staging` to `main.pm`.

**Comment by Vogtinator** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12660 merged

**Comment by jlausuch** [comment]
Thanks for fixing it!

**Pull request merged**
