### PR TITLE
Upload coredump files and guest autoyast file for virt PRJ3 tests

### PR DESCRIPTION
**Pull request by Julie-CAO**
Related ticket: https://progress.opensuse.org/issues/157762

- Upload coredump files in virt PRJ3 tests
- Change to upload guest autoyast profiles in qa_test_virtualization package(https://github.com/SUSE/qa-testsuites/pull/1090)
- Fix fozzie hostname in host autoyast profile template

Verification run: 
[prj3_kvm_dst_job](https://openqa.suse.de/tests/13896859)
[sl515sp5_kvm_on_fozzie](http://openqa.suse.de/tests/13897648)

### CODE REVIEW

**Comment by Julie-CAO** [comment]
@alice-suse @guoxuguang @waynechen55 and others, welcome review!

**Comment by alice-suse** [comment]
LGTM

**Comment by Julie-CAO** [comment]
@alice-suse is this PR ok to merge? fozzie will not function well without this PR.

**Comment by alice-suse** [comment]
> @alice-suse is this PR ok to merge? fozzie will not function well without this PR.

Sure, then won't wait for more review from others.

**Pull request merged**
