### PR TITLE
Wait longer for yast2 iscsi-client

### PR DESCRIPTION
**Pull request by dzedro**
Sometimes yast iscsi-client need more than 30 seconds to start e.g. https://openqa.suse.de/tests/413017/modules/iscsi_client/steps/16

### CODE REVIEW

**Comment by okurz** [comment]
and how is that acceptable from a users perspective?

**Comment by dzedro** [comment]
We could ask this if openQA would provide always same performance, unfortunately it is not so simple as we run tens of jobs/workers. For example default timeout will be always enough on my local openQA with max. two local workers, so we can wait longer or restart job when it fails.

**Comment by dzedro** [comment]
Or like this ?

**Comment by okurz** [comment]
interesting. Then you might also be interested in my proposal here: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1437

**Comment by dzedro** [comment]
Updated

**Comment by okurz** [comment]
I am sorry if I mislead you. What I did is so far just a proposal and is not merged therefore you can't yet use the command `assert_screen_with_soft_timeout`. However, I would welcome your feedback on what you think about it in #1437

**Comment by dzedro** [comment]
@okurz I have seen it's not merged, I believed it will be merged today :)

**Comment by okurz** [comment]
were you in the openqa call at 1000 CEST today? The decision was to not merge #1437 as is and replace all too low timeouts with at least the default so I think the right approach is to just increase the timeout. No record_soft_failure unless we have a bugref. I would have preferred #1437 myself but decision was made and we should be consistent.

**Comment by dzedro** [comment]
git it now

**Pull request merged**
