### PR TITLE
 Activate existing encrypted volume for Tumbleweed

### PR DESCRIPTION
**Pull request by richiejp**
Mostly the same as commit 681acda, but for OpenSUSE Tumbleweed rather than SLES.

However by default Tumbleweed uses the same password for the main user
and root. It also enables automatic login, but when the
user chooses to import existing user data both these options are
unavailable. So the test operator must set DOCRUN and NOAUTOLOGIN to 1
if IMPORT_USER_DATA is also set.

Also changes the base class for the encrypted_volume_activation module which means it will fail more gracefully.

### CODE REVIEW

**Comment by okurz** [comment]
Let's try something else, as you mentioned what the operator should do. There is a `templates` file in each products dir which if neglected by most but what you could do is insert in there how the test suites should look like. Try that :-)

**Comment by richiejp** [comment]
I can see why people ignore the templates file :-) The formatting in this file seems to be different from the rest of OpenQA and both emacs perl mode and CPerl mode refused to follow the existing indentation. So I ran Perl tidy on it with the standard OpenQA settings except for -l=80 to keep the line lengths sensible and the whole file has been changed.

**Comment by okurz** [comment]
well, then please don't change the format of the file. I refuse to search for the actual changes you made if you try to hide them in tidying ;-) I was thinking more like adding new test_suite without changing the overall format.

**Comment by richiejp** [comment]
I just find this file too big and painful to deal with. Perhaps I should create a templates sub-directory (or even templates/installation) and create a separate template file in there for the new cryptlvm test suits (and a sample machine/job group)? 

That way someone can view all the information relating to these tests on one or two pages and import the tests without worrying if anything unexpected is going to be added. If someone needs to add all the templates at once then they can write something like `./load_templates templates/*`.

**Comment by okurz** [comment]
ok, this discussion is moving too far into an unrelated direction. Please revert your changes on the templates file and keep it separate from this PR. You could suggest changes in another PR or in a progress item with your ideas attached.

**Comment by richiejp** [comment]
Great, I have created a progress item and purely for reference I will post the test suit entries here. Also I did a revert commit, but if you can't accept that (or squish it in the merge) I will create a new pull request.
```Perl
       {
            name     => "cryptlvm",
            settings => [
                {key => "DESKTOP",            value => "minimalx"},
                {key => "ENCRYPT",            value => 1},
                {key => "LVM",                value => 1},
                {key => "REBOOTAFTERINSTALL", value => 0},
                {
                    key => "PUBLISH_HDD_1",
                    value =>
                      "%DISTRI%-%VERSION%-%ARCH%-%DESKTOP%-encrypted.qcow2"
                },
            ],
        },
        {
            name     => "cryptlvm+cancel_existing",
            settings => [
                {key => "DESKTOP",                 value => "gnome"},
                {key => "ENCRYPT",                 value => 1},
                {key => "LVM",                     value => 1},
                {key => "ENCRYPT_CANCEL_EXISTING", value => 1},
                {key => "INSTALLONLY",             value => 1},
                {
                    key => "HDD_1",
                    value =>
                      "%DISTRI%-%VERSION%-%ARCH%-%DESKTOP%-encrypted.qcow2"
                },
                {key => "START_AFTER_TEST", value => "cryptlvm"},
            ],
        },
        {
            name     => "cryptlvm+activate_existing",
            settings => [
                {key => "DESKTOP",                   value => "gnome"},
                {key => "ENCRYPT",                   value => 1},
                {key => "LVM",                       value => 1},
                {key => "ENCRYPT_ACTIVATE_EXISTING", value => 1},
                {key => "INSTALLONLY",               value => 1},
                {
                    key => "HDD_1",
                    value =>
                      "%DISTRI%-%VERSION%-%ARCH%-%DESKTOP%-encrypted.qcow2"
                },
                {key => "START_AFTER_TEST", value => "cryptlvm"},
            ],
        },
        {
            name     => "cryptlvm+activate_existing+import_users",
            settings => [
                {key => "DESKTOP",                   value => "gnome"},
                {key => "ENCRYPT",                   value => 1},
                {key => "LVM",                       value => 1},
                {key => "ENCRYPT_ACTIVATE_EXISTING", value => 1},
                {key => "IMPORT_USER_DATA",          value => 1},
                {key => "INSTALLONLY",               value => 1},
                {
                    key => "HDD_1",
                    value =>
                      "%DISTRI%-%VERSION%-%ARCH%-%DESKTOP%-encrypted.qcow2"
                },
                {key => "START_AFTER_TEST", value => "cryptlvm"},
            ],
        },
```

**Comment by okurz** [comment]
to save you the effort I squashed the template changes locally and merged.

**Pull request closed without merging**
