### PR TITLE
Change mysql to mariadb

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/92215
Verification:
http://kazhua.qa.suse.de/tests/349
http://kazhua.qa.suse.de/tests/348

### CODE REVIEW

**Review by punkioudi — APPROVED** [review]
lgtm! Could you also add the VRs for the maintenance sle versions? :)

**Comment by asdil12** [comment]
SLE12SP5: http://kazhua.qa.suse.de/tests/350
SLE12SP2: http://kazhua.qa.suse.de/tests/351 (still running)

**Comment by punkioudi** [comment]
> SLE12SP5: http://kazhua.qa.suse.de/tests/350
> SLE12SP2: http://kazhua.qa.suse.de/tests/351 (still running)

It fails in sle12sp2, but I think that it can be skipped from being scheduled there as it is not LTSS

**Comment by asdil12** [comment]
SLE15SP4 is the first one where it works: http://kazhua.qa.suse.de/tests/353

**Comment by asdil12** [comment]
I'm using `mysql` insted of `mariadb` for SLE<12SP4. That should do it.

Verification on SLE12SP2: http://kazhua.qa.suse.de/tests/355#

**Comment by punkioudi** [comment]
> I'm using `mysql` insted of `mariadb` for SLE<12SP4. That should do it.
> 
> Verification on SLE12SP2: http://kazhua.qa.suse.de/tests/355#

Awesome!

**Pull request merged**
