### PR TITLE
docker_image_rpm: Do not add devel repos in TW snapshot tests

### PR DESCRIPTION
**Pull request by Vogtinator**
That makes no sense if the objective is to test whether the image works.

Untested.

### CODE REVIEW

**Comment by okurz** [comment]
@pdostal

**Comment by pdostal** [comment]
Hello, the change looks good but I'm not really sure if that will pass. Please @Vogtinator can you provide a test run?

**Comment by Vogtinator** [comment]
@pdostal Why shouldn't it pass?

**Comment by Vogtinator** [comment]
Test run: http://10.160.67.86/tests/160#step/docker_image_rpm/14

I ran it in a livecd test as it's quicker and it succeeded until it ran out of space after the test.

**Comment by pdostal** [comment]
OK, the out of space error seems to be related to the live CD environment and the package seems to be all right. Thank you @Vogtinator for your effort!

**Comment by ggardet** [comment]
@Vogtinator what about the *current* vs *latest* tags? It is currently the problem in openQA: https://openqa.opensuse.org/tests/784346#step/docker_image_rpm/22

**Comment by Vogtinator** [comment]
@ggardet That's exactly what this PR fixes. By using the image from the wrong location, the tags are obviously wrong as well.

**Pull request merged**
