### PR TITLE
Add LTSS update channel for  SLES for SAP 12-SP5

### PR DESCRIPTION
**Pull request by badboywj**
make registration.pm to support LTSS for 12-SP5 for SAP

- Related ticket: https://jira.suse.com/browse/TEAM-9783
- Needles: None
- Verification run: https://openqa.suse.de/tests/15820557

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by lilyeyes** [comment]
One question: why there is no LTSS related repo listed in step: https://openqa.suse.de/tests/15820557#step/patch_and_reboot/30

**Review by lpalovsky — APPROVED** [review]
LGTM

**Comment by badboywj** [comment]
> One question: why there is no LTSS related repo listed in step: https://openqa.suse.de/tests/15820557#step/patch_and_reboot/30

I think the output is only tails, not full. and I downloaded the qcow2 image and check the repos, make sure LTSS was included in the image

**Comment by lilyeyes** [comment]
> > One question: why there is no LTSS related repo listed in step: https://openqa.suse.de/tests/15820557#step/patch_and_reboot/30
> 
> I think the output is only tails, not full. and I downloaded the qcow2 image and check the repos, make sure LTSS was included in the image

I checked https://openqa.suse.de/tests/15820557/logfile?filename=serial_terminal.txt  there are LTSS repos.

**Pull request merged**
