### PR TITLE
Split extra tests to independent suites (part 2)

### PR DESCRIPTION
**Pull request by baierjan**
As the part 1 (#5877) is already merged, it is possible to get rid of all `EXTRATEST=1` in the test suites and remove the compatibility branch from the code entirely. The correct new value to run the test all in one run is `EXTRATEST=zypper,console,opensuse,docker,kdump`.

- Related ticket: https://progress.opensuse.org/issues/41900
- Verification run: 
  - https://openqa.suse.de/tests/overview?distri=sle&version=15&groupid=165 (build > 20181119-1)
  - https://openqa.suse.de/tests/overview?groupid=162&distri=sle&version=12-SP4 (build > 10.30)
  - http://panigale.suse.cz/tests/1003 (TW, textmode)
  - http://panigale.suse.cz/tests/1007 (TW, gnome desktop)

### CODE REVIEW

**Comment by rwx788** [comment]
@baierjan code changes LGTM, the only question, will you be able to change test suite settings yourself? Or do you need help with that? I guess we can do that right now, as new value will be still treated as true.

**Comment by baierjan** [comment]
@rwx788: If I am not mistaken, I already changed all test suites (AFAIK, there were 3 test suites with `EXTRATEST` variable)

**Comment by rwx788** [comment]
Could you please cross-check that. Seems that test suites search is broken as I get 0 matches when look for `EXTRATEST`.
image

**Comment by rwx788** [comment]
Ok, it works by test suite name only, but on o3 there are quite some tests with `EXTRATEST=1`, so please, adjust this first. I also can support you there if you don't have permissions.

**Comment by okurz** [comment]
Not sure if this PR or https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6232 should be merged first

**Comment by okurz** [comment]
Because test suites on https://openqa.opensuse.org/admin/test_suites are not yet adjusted I will go with #6232 first

**Comment by baierjan** [comment]
@rwx788: Apparently, I do not have enough permissions to change test suites on o3.

* extra_tests_in_textmode and jeos-extra should have the same setting as in osd (`EXTRATEST=zypper,console,opensuse,docker,kdump`)

* extra_tests_on_kde, extra_tests_on_xfce, extra_tests_on_gnome should only load `load_extra_tests_desktop` so the correct setting is `EXTRATEST=desktop`. However, due to #6232 it has to stay on `EXTRATEST=1`. But I have some objections to #6232 anyways.

Eventually, it will be possible to merge this all into one, I will look at it more after my vacation :smiley:

**Comment by baierjan** [comment]
Tests definition updated, branch rebased and slightly changed to take into account #6232.

**Pull request merged**
