### PR TITLE
Workaround boot timeout issue for user_defined_snapshot.pm

### PR DESCRIPTION
**Pull request by Zaoliang**
- increase timeout for boot
- see https://progress.opensuse.org/issues/35011 for details
- verification run:
  http://e13.suse.de/tests/6015#step/user_defined_snapshot

### CODE REVIEW

**Comment by okurz** [comment]
Isn't it a sporadic issue? Then we should have more than one job for verification, right?

**Comment by Zaoliang** [comment]
can someone review this or reject this with comment, please? 
thanks!

**Comment by Zaoliang** [comment]
Actually I checked this for about 10 times, but if it is really need to run 40 or 50 times, that is not a problem. I think this is related to timeout.

**Comment by okurz** [comment]
Can you please provide a link to the multiple test runs so that we can crosscheck the statistics?

**Comment by Zaoliang** [comment]
please see some test results:
http://e13.suse.de/tests/6015#next_previous

**Comment by Soulofdestiny** [comment]
so 7 out of 40 failed - all those were triggered with your increased timeout included?

**Comment by Zaoliang** [comment]
@Soulofdestiny I re-triggered test runs:
http://e13.suse.de/tests/latest?distri=sle&machine=64bit&flavor=Server-DVD&test=extra_tests_on_gnome&version=12-SP4&arch=x86_64#next_previous

5 failed from 50 test runs, failure is still too high. Any suggestions? 
I need to re-work on this issue anyway.

**Comment by okurz** [comment]
I assume @dgutu-suse does not want to maintain the test module anymore so we should find a new maintainer. volunteers?

**Comment by okurz** [comment]
@Zaoliang Also see my comment in https://progress.opensuse.org/issues/35011#note-16 . It seems the failures fail in *shutdown* not *booting*.

Also I recommend to use the approach mentioned in https://progress.opensuse.org/projects/openqatests/wiki/#Statistical-investigation to define a custom "build" where it is easier to see statistics than looking into the history of a single test scenario.

**Comment by rwx788** [comment]
Is this still relevant? I don't see how it can help as we don't see grub which is one step before.

**Comment by Zaoliang** [comment]
@rwx788 no, since we have already handled shutdown/reboot issue.

**Pull request closed without merging**
