### PR TITLE
[untested] move the prompt functions into the opensusebasetest

### PR DESCRIPTION
**Pull request by coolo**
and call the standard_prompt function already in select_console

### CODE REVIEW

**Comment by coolo** [comment]
my local tests are all cursed, so let's hope it improves the situation for real

**Comment by okurz** [comment]
separating both prompt setting functions is a bad idea, people will mess around with one of both and forget about the other one. can we find a common location?

**Comment by okurz** [comment]
Also I don't understand why it should be in "opensusebasetest". It certainly is also relevant for SLE right?

**Comment by coolo** [comment]
the whole repo is called opensuse and is still relevant to SLE

**Pull request merged**
