### PR TITLE
Fix keymap_or_login matching on 'cleared-console' too early

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/46508

### CODE REVIEW

**Comment by okurz** [comment]
Triggered potential verification run:

```
openqa-clone-job --skip-download --skip-chained-deps --from https://openqa.opensuse.org --host https://openqa.opensuse.org 835515 _GROUP=0 TEST=textmode@okurz/os-autoinst-distri-opensuse#fix/keymap_poo46508 BUILD=okurz/os-autoinst-distri-opensuse#6615 CASEDIR=https://github.com/okurz/os-autoinst-distri-opensuse.git#fix/keymap_poo46508
```

Created job #835555: opensuse-Tumbleweed-DVD-aarch64-Build20190115-textmode@aarch64 -> https://openqa.opensuse.org/t835555

**Comment by okurz** [comment]
@ggardet

**Comment by ggardet** [comment]
LGTM. Thanks!

**Comment by okurz** [comment]
@Soulofdestiny regarding the use of "is_remote_backend" and potential impact on s390x

**Comment by asmorodskyi** [comment]
> Triggered potential verification run:
> 
> ```
> openqa-clone-job --skip-download --skip-chained-deps --from https://openqa.opensuse.org --host https://openqa.opensuse.org 835515 _GROUP=0 TEST=textmode@okurz/os-autoinst-distri-opensuse#fix/keymap_poo46508 BUILD=okurz/os-autoinst-distri-opensuse#6615 CASEDIR=https://github.com/okurz/os-autoinst-distri-opensuse.git#fix/keymap_poo46508
> ```
> 
> Created job #835555: opensuse-Tumbleweed-DVD-aarch64-Build20190115-textmode@aarch64 -> https://openqa.opensuse.org/t835555
> 
> passed in https://openqa.opensuse.org/tests/835555#step/keymap_or_locale/2

awesome !!!

**Comment by asmorodskyi** [comment]
would it make sense following same logic to also change this line with same change ? 

https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/locale/keymap_or_locale.pm#L86

**Comment by okurz** [comment]
No. Then the test would fail in https://openqa.opensuse.org/tests/835555#step/keymap_or_locale/1 . But thanks to your observation I realized that we have not only "text-login" which is too generic and causes mismatches but also "linux-login" which I assume to be the same. Commented in https://progress.opensuse.org/issues/34471#note-46

If just more people would care about our test distribution as a whole instead of adding more messy copy-paste code *sigh*

**Pull request merged**
