### PR TITLE
Update qa_run.pm

### PR DESCRIPTION
**Pull request by badboywj**
extend the "QA_TESTSUITE" function, make it to trigger more testsuite once, like this: QA_TESTSUITE=cpio,bzip2,... or QA_TESTSUITE=cpio;bzip2;...

### CODE REVIEW

**Comment by foursixnine** [comment]
Looks fine from my point of view, but a verification run wouldn't hurt :)

**Comment by okurz** [comment]
Please also update variables.md with a documentation string

**Comment by badboywj** [comment]
> Please also update variables.md with a documentation string

OK, thank you.

**Comment by okurz** [comment]
You seem to have mixed in some unrelated commits. Please rebase and fix that.

**Comment by badboywj** [comment]
> You seem to have mixed in some unrelated commits. Please rebase and fix that.

I had rebased to fix the issue.

**Pull request merged**
