### PR TITLE
Fix pressure_stall_information on s390x (svirt backend)

### PR DESCRIPTION
**Pull request by pevik**
pressure_stall_information run on s390x-kvm-sle15 needs
installation/bootloader_zkvm.

- Verification run:
- http://quasar.suse.cz/tests/4705 (s390x-kvm-sle15)
- http://quasar.suse.cz/tests/4706 (intel)

### CODE REVIEW

**Comment by pevik** [comment]
@richiejp Although this showed new problem: svirt serial console needs support for reboot. `reconnect_mgmt_console()` might be a place were we need to have a support.

**Comment by richiejp** [comment]
If we only need reboot on this test I think setting `serial_console=0` is OK for now.

**Comment by pevik** [comment]
Yes. There was some problem on kotd, which @czerw solved the same way.
I'll try to fix this issue later (https://progress.opensuse.org/issues/54578).

**Comment by pevik** [comment]
Ready to be merged.

**Comment by pevik** [comment]
@czerw Thanks a lot!

**Pull request merged**
