### PR TITLE
Drop duplicate tags

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by asmorodskyi** [comment]
No proof runs done yet , I am confused which one I should do actually

**Comment by asmorodskyi** [comment]
@thehejik this changes influence on Slenkins tests so please take a look if you ok with them

**Comment by thehejik** [comment]
@asmorodskyi thanks for pointing me to the tag removal PR stuff ... lgtm, you already modified support_server.pm script to use new tag so it should work imo.

**Comment by dzedro** [comment]
just tidy

**Comment by asmorodskyi** [comment]
tidy fixed

**Pull request merged**
