### PR TITLE
Properly fix Utils::Systemd::disable_and_stop_service()

### PR DESCRIPTION
**Pull request by mdoucha**
PR #7084 broke `Utils::Systemd::disable_and_stop_service()` due to differences in behavior between `systemctl disable --now` and `systemctl disable && systemctl stop`. The "fix" merged in PR #9135 is problematic to say the least. Fix the underlying problem properly.

- Related ticket: N/A
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/3695494

### CODE REVIEW

**Comment by mdoucha** [comment]
> You are not fixing it, you are basically reverting my change

Until `systemctl disable --now` gets fixed, reverting your change is the only reasonable way to fix the problem.

> and did not even invite me for review, not nice :,( .

Two LTP developers have asked you to fix the problem properly. Instead, you've decided to ignore both of us and merge a patch that potentially breaks kernel testing even more. So please understand that I'm not interested in your opinion on this PR.

**Comment by asmorodskyi** [comment]
@okurz  - I would agree with @mdoucha  and @richiejp  here . Initially it was you who merged #9135 which changes behavior of LTP and ignore complains of people who actually maintaining LTP tests. And I think that this is something that should not happen ever . We have a big project and a lot of people have merge rights here. But we all need to keep in mind that there still some kind of "virtual projects " which are maintained by smaller group of people and we all need to respect this .
But there is also problem which repeated in both PRs #9135  and this one . You mixing here two not tightly coupled issues : 
1. Refactor of `disable_and_stop_service()` function widely used in project 
2. Changes how install_ltp handles errors in stopping Susefirewall 

And while first one is topic to discuss with @okurz  and anyone else involved in maintenance of tests where it is in use . But second is totally under control of @mdoucha , @richiejp , @pevik - because this is guys who feel the pain everyday when something goes wrong with LTP in openQA . 
So @mdoucha I suggest you to split this PR on two . Second one (about LTP) will be merged immediately . First  one may be discussed but generally I am fine with it too also I don't see why @okurz saying that you simply reverting his changes simple diff of `disable_and_stop_service()` before @okurz change and after yours showing that it is not true

**Comment by asmorodskyi** [comment]
@jlausuch - FYI

**Comment by mdoucha** [comment]
@asmorodskyi I'm fine with dropping 7e7d4f5 from this PR and resubmitting it separately. But please note that `install_ltp` will be failing everywhere until the resubmitted PR gets merged in some form or another.

**Comment by mdoucha** [comment]
Returned 7e7d4f5 back into the PR as per IRC discussion to prevent `install_ltp` failures.

**Pull request merged**
