### PR TITLE
KLP support for openSUSE

### PR DESCRIPTION
**Pull request by pevik**
Verification run
- openSUSE
http://quasar.suse.cz/tests/1719
NOTE: failure is in kernel live patching infrastructure tests: http://quasar.suse.cz/tests/1719/file/serial_terminal.txt

- SLE12 (QAM)
http://quasar.suse.cz/tests/1721

- SLE15 SP1
http://quasar.suse.cz/tests/1720

### CODE REVIEW

**Comment by sysrich** [comment]
Kernel live patching is coming to openSUSE?

**Comment by pevik** [comment]
@sysrich not really. This was to test KLP infrastructure before it hits SLES.

**Comment by sysrich** [comment]
Aww :sad panda:

**Comment by asmorodskyi** [comment]
LGTM but please tidy up your code , can't merge something which Mr. Travis don't like

**Comment by pevik** [comment]
Mr. Travis made happy, please merge :).

**Comment by asmorodskyi** [comment]
Happy Mr. Travis => happy @asmorodskyi  => happy @pevik  :D

**Pull request merged**
