### PR TITLE
Prepare for GREP 3.8

### PR DESCRIPTION
**Pull request by DimStar77**
egrep and fgrep have been deprecated in favor of grep -E and grep -F for a long time
grep 3.8 starts spitting out deprecation warnings whenever being invoked as egre/fgrep

Handle that by replacing all calls to egrep/fgrep with grep -E, resp grep -F

> grep egrep . -rl | xargs sed -i "s|egrep|grep -E|g"
> grep fgrep . -rl | xargs sed -i "s|fgrep|grep -F|g"

- Related ticket: https://build.opensuse.org/request/show/1001674
- Needles: N/A
- Verification run: None defined

### CODE REVIEW

**Review by foursixnine — APPROVED** [review]

**Review by b10n1k — APPROVED** [review]
+1

**Comment by foursixnine** [comment]
Created https://progress.opensuse.org/issues/117118 as a follow up

**Review by mimi1vx — APPROVED** [review]

**Comment by foursixnine** [comment]
@DimStar77 regardless of whether Grep is accepted or not, we can move forward here... wdyt?

**Comment by DimStar77** [comment]
I rebased the PR and resolved the conflict

**Pull request merged**
