### PR TITLE
[virt_autotest] add switch for virsh external snapshot test

### PR DESCRIPTION
**Pull request by guoxuguang**
Add switch for virsh external snapshot test

### CODE REVIEW

**Comment by guoxuguang** [comment]
@alice-suse @Julie-CAO @waynechen55 Please help me review this PR, if have time.

**Comment by Julie-CAO** [comment]
So only external snapshot has switch, internal snapshot is a mandatory test?

**Comment by guoxuguang** [comment]
imho, internal snapshot much more available and acceptable than external snapshot for SLE OSD. 
So, this PR just only made switch for external snapshot without internal snapshot.

**Comment by Julie-CAO** [comment]
LGTM

**Comment by alice-suse** [comment]
I am afraid this is a "too lazy" way to skip unsupported internal/external snapshot test -- sle11sp4 host guests defautly use raw as disk type by our vm-install.sh tool, and snapshot tests are only supported on qcow2 disks.

A smart enough way should be that in snapshot scripts, in its loop for guests, checking disk type and only continue tests on qcow2 disk guests.

**Comment by guoxuguang** [comment]
@alice-suse firstly, need to be clarification here for this PR. As we discussed, we need to add switch for external snapshot. So, I had created this PR. 

Moreover, as your mentioned, "to skip unsupported internal/external snapshot test -- sle11sp4 host guests defautly use raw as disk type by our vm-install.sh tool, and snapshot tests are only supported on qcow2 disks.“ I had created the other one as PR#9693 [WIP][virt_autotest] disable virsh snapshot test on sles11sp4 vm host. 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9693

So, we'd better to discuss about disable snapshot test under PR#9693 not here. 

This PR just only involve that add switch for external snapshot test.

**Comment by alice-suse** [comment]
> @alice-suse firstly, need to be clarification here for this PR. As we discussed, we need to add switch for external snapshot. So, I had created this PR.
> 
> Moreover, as your mentioned, "to skip unsupported internal/external snapshot test -- sle11sp4 host guests defautly use raw as disk type by our vm-install.sh tool, and snapshot tests are only supported on qcow2 disks.“ I had created the other one as PR#9693 [WIP][virt_autotest] disable virsh snapshot test on sles11sp4 vm host.
> #9693
> 
> So, we'd better to discuss about disable snapshot test under PR#9693 not here.
> 
> This PR just only involve that add switch for external snapshot test.

Sure. Reasonable. Let's discuss there. With #9693, seems the necessity for a external snapshot switch is less.

**Comment by guoxuguang** [comment]
@alice-suse firstly, need to be clarification here for this PR. As we discussed, we need to add switch for external snapshot. So, I had created this PR. 

Moreover, as your mentioned, "to skip unsupported internal/external snapshot test -- sle11sp4 host guests defautly use raw as disk type by our vm-install.sh tool, and snapshot tests are only supported on qcow2 disks.“ there was created the other submitted PR as PR#9693 [WIP][virt_autotest] disable virsh snapshot test on sles11sp4 vm host. 

So, we'd better to discuss under PR#9693 not here. 

This PR just add switch for external snapshot test

> > @alice-suse firstly, need to be clarification here for this PR. As we discussed, we need to add switch for external snapshot. So, I had created this PR.
> > Moreover, as your mentioned, "to skip unsupported internal/external snapshot test -- sle11sp4 host guests defautly use raw as disk type by our vm-install.sh tool, and snapshot tests are only supported on qcow2 disks.“ I had created the other one as PR#9693 [WIP][virt_autotest] disable virsh snapshot test on sles11sp4 vm host.
> > #9693
> > So, we'd better to discuss about disable snapshot test under PR#9693 not here.
> > This PR just only involve that add switch for external snapshot test.
> 
> Sure. Reasonable. Let's discuss there. With #9693, seems the necessity for a external snapshot switch is less.

Great, got it.

**Comment by waynechen55** [comment]
Probably provide some background information in the description if this pull request is going to go live, for example, maybe just "I need to disable it to workaround something temporarily" is better than nothing.

**Comment by guoxuguang** [comment]
It was the interim PR for virsh external snapshot automation issue on s11sp4. 
For now, PR#10008 was resolved this automation issue on s11sp4 now.
So, closed this PR.

**Pull request closed without merging**
