### PR TITLE
Change console connection from serial to vnc

### PR DESCRIPTION
**Pull request by rfan1**
Change the console connection from serial to vnc for some tests

The reason why post this commit is that, we hit some tests failed on s390x platform when re-connecting the active serial console.
https://openqa.nue.suse.com/tests/4285536#step/git/2
https://openqa.nue.suse.com/tests/4285602#step/sestatus/59

- Related ticket:67624
- Needles: N/A
- Verification run: https://openqa.nue.suse.com/tests/4305744
                             https://openqa.nue.suse.com/tests/4305656

### CODE REVIEW

**Comment by jouyingbin** [comment]
@rfan1 It looks like the CI check fail.
https://travis-ci.org/github/os-autoinst/os-autoinst-distri-opensuse/jobs/694190383

**Comment by rfan1** [comment]
> @rfan1 It looks like the CI check fail.
> https://travis-ci.org/github/os-autoinst/os-autoinst-distri-opensuse/jobs/694190383

fixed, thanks Ben

**Comment by okurz** [comment]
You should be careful with changes like these. Your commit message basically says "change this to that" but the original change had been done for a reason. And you did not invite the author of the previous change in the conversation, e.g. tests/console/git was just recently changed in 4e9cca349 by @dzedro who you did not gave a good chance to comment, not so nice.

**Comment by rfan1** [comment]
> You should be careful with changes like these. Your commit message basically says "change this to that" but the original change had been done for a reason. And you did not invite the author of the previous change in the conversation, e.g. tests/console/git was just recently changed in [4e9cca3](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/4e9cca349646152944d403c221b8322ac6842a72) by @dzedro who you did not gave a good chance to comment, not so nice.

Thanks Oliver the the comments! and you are correct,  we should explain why we did these changes, it is not so nice to just change the test logic once hitting an issue, since we have been using serial console for a long time (over 1 year I think, but please correct me if I was wrong)

Let me add some background here, actually there was a poo filed by Lili:
https://progress.opensuse.org/issues/67144

The issue was seen recently with no code changes from our test cases.  whenever a test case used the method "$self->select_serial_terminal",  and next case failed if it re-used this method on s390x platform.

For now, we didn't get any update for this poo, so we discussed it within team, and decided to use "root console" as a workaround to by-pass this issue for now.

So, can you please share some light on this?  it should be great we can get a method to re-connect a active serial console/session (or disconnect the serial console once completing a test case/module).

-Richard.

**Comment by dzedro** [comment]
This is know issue of serial_terminal especially on s390x svirt backend, where switching back to serial_terminal is not handled properly, when the console is already activated.
You could just use VIRTIO_CONSOLE=0 or even try to fix the issue :roll_eyes:

**Comment by rfan1** [comment]
> This is know issue of serial_terminal especially on s390x svirt backend, where switching back to serial_terminal is not handled properly, when the console is already activated.
> You could just use VIRTIO_CONSOLE=0 or even try to fix the issue 🙄

Thanks much for the update! 
I will try with this and then let you know and if it works fine, I can revert this commit.

**Pull request merged**
