### PR TITLE
Give more descriptive names to the CI tests

### PR DESCRIPTION
**Pull request by foursixnine**

### CODE REVIEW

**Comment by okurz** [comment]
It says "PR CI / CI: Running …" now, a bit redundant?

**Review by rwx788 — APPROVED** [review]
LGTM

**Comment by foursixnine** [comment]
> It says "PR CI / CI: Running …" now, a bit redundant?

No, it isn't

image

**Review by okurz — APPROVED** [review]

**Comment by rwx788** [comment]
> It says "PR CI / CI: Running …" now, a bit redundant?

True. So there is a name listed in the header of the yaml, then there is job name and steps names.

**Comment by rwx788** [comment]
> > It says "PR CI / CI: Running …" now, a bit redundant?
> 
> No, it isn't
> 
> image

I thought @okurz means this one: 
image

So maybe we should also rename "PR CI" to "PR checks", for instance.

**Comment by foursixnine** [comment]
@rwx788 renamed to pr checks, also added the `CI` to the deploy workflow

**Pull request merged**
