### PR TITLE
Update libreoffice cases for x11regression

### PR DESCRIPTION
**Pull request by chuchingkai**
Testing Result:

http://147.2.207.174/tests/587

### CODE REVIEW

**Comment by okurz** [comment]
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

**Comment by okurz** [comment]
ok, maybe I wasn't clear enough: Are there any test cases failing right now which are fixed by this change?

**Comment by chuchingkai** [comment]
Hi @okurz ,

These libreoffice cases have flaws since [Build0575](https://openqa.suse.de/tests/372533) (We were still in Gnome 3.1x at that time). Now we have Gnome320, the reneedling job is blocked by these flaws, that's why we have this commit:

- libreoffice_default_theme.pm
- libreoffice_pyuno_bridge.pm

  Add wait_still_screen to make it more stable

- libreoffice_mainmenu_favorites.pm

  Change send_key_until_needlematch and assert_screen to assert_and_click to make it more efficiency.

- libreoffice_recent_documents.pm

  Failed at [Build0575](https://openqa.suse.de/tests/372533#step/libreoffice_recent_documents/18). The shortcut to clear libreoffice's history  is often ineffective, so I use send_key_until_needlematch instead.

Should I add all these info to the commit message ?

**Comment by okurz** [comment]
> Should I add all these info to the commit message ?

sure, that would be great. Currently "Update libreoffice cases" is merely stating the obvious. From the code change one can already see that libreoffice test cases are updated but it does not tell why. Your explanation is very good and it would help to have this in the commit message, too.

**Comment by chuchingkai** [comment]
OK, I will correct it.

**Pull request merged**
