### PR TITLE
Add script which generates yaml schedulers

### PR DESCRIPTION
**Pull request by b10n1k**
This is a python(v3) script which will generates a yaml scheduler
based on the information gained from the test suite settings and
parsing the corresponding openqa Job.

### CODE REVIEW

**Comment by OleksandrOrlov** [comment]
I've checked out your branch, executed the following:

1. `cd /os-autoinst-distri-opensuse/script/yaml_generator`;
2. `python3 -m venv env`;
3. `source env/bin/activate`;
4. `pip install -r requirements.txt`;
5. exported both SUSE_EMAIL and SUSE_PASS with my email and password;
6. Executed: `python3 create_scheduler.py 3998076 3998076_job.txt`

I've got an error:
```
Traceback (most recent call last):
  File "create_scheduler.py", line 3, in <module>
    from openqa_client.client import OpenQA_Client
ModuleNotFoundError: No module named 'openqa_client'
```

Could you please provide me the correct steps if I did something wrong or fix the issue if there are some code changes required.

**Comment by b10n1k** [comment]
97907f947 should have the correct dependencies. openqa-python-client was missing.

**Comment by OleksandrOrlov** [comment]
I just have a few thoughts about this. You can agree or disagree on them for sure:)

1. I'm not sure, but I guess it should work without credentials, as autoinst-log.txt and test suite settings are available without logging in;
2. Would be cool if openqa.suse.de will be a parameter that could be changed, as we also have o3. Maybe we can leave osd by default, but also add ability to change the server from command line;
3. And the last thing, but probably the main, it takes more than 4 minutes for script to create the template (at least for me). I guess it may be related to the slow Test Suites page load time, but maybe it is related to something else, or can be improved. Could you debug, why it takes so long? Or it is only for me?

**Comment by b10n1k** [comment]
3. indeed. the problem is suitevars = client.openqa_request('GET', 'test_suites').  As you can see this retrieves all the test_suites. The generator helps a bit here in the performance. But the short answer is that it can do better( calling +/test_suites/:id ). I just want it to make it more "generic" at the time of the coding, and that was a problem then
2. Done. 
1. indeed. I removed this and it looks ok

**Comment by rwx788** [comment]
@okurz Hey Oliver, could you please take a look? We want to share some scripts with other teams, which can make our life easier. Do you have any better idea where to store them?

**Comment by okurz** [comment]
> Do you have any better idea where to store them?

Do you mean the path *within* os-autoinst-distri-opensuse or a different repo?

For the first: I guess "script/" is fine. For the latter: Due to the a bit unusual dependency on "ruamel.yaml" I guess we should not try to put it into os-autoinst/openQA but you can submit it to os-autoinst/scripts where we only have lax requirements :) Would this fit? If you would prefer to submit it to openQA then as first hint I suggest to replace "ruamel.yaml" by something which is more standard.

**Comment by b10n1k** [comment]
To be fair and stand up by my choice(which was not random), "ruamel.yaml" is a enhanced set of the PyYAML which supports yaml v1.2 and can be found on pypi. And it is not so unusual. Checking on github[0] returned 339,357. 
I am not sure why people still keep using the pyyaml but if you search around, there are many who suggest to turn in favor of "ruamel.yaml" rather of pyyaml.
Personally it doesnt make difference for me, whether os-autoinst/openQA or os-autoinst/scripts, I just thought that it is worth to share this info

[0] https://github.com/search?q=ruamel.yaml&type=Code

**Comment by okurz** [comment]
Of course your choice is not random. But just for example see that ruamel.yaml might be included in openSUSE Leap 15.1 and openSUSE Tumbleweed but for example not in SLE 15 SP1: https://build.opensuse.org/project/show/SUSE:SLE-15-SP1:GA

**Comment by b10n1k** [comment]
> Of course your choice is not random. But just for example see that ruamel.yaml might be included in openSUSE Leap 15.1 and openSUSE Tumbleweed but for example not in SLE 15 SP1: https://build.opensuse.org/project/show/SUSE:SLE-15-SP1:GA

Thats interesting point. However i was counting on the pypi package.

**Comment by okurz** [comment]
well, I think we should not overlook that SUSE builds distributions ;)

**Comment by rwx788** [comment]
> To be fair and stand up by my choice(which was not random), "ruamel.yaml" is a enhanced set of the PyYAML which supports yaml v1.2 and can be found on pypi. And it is not so unusual. Checking on github[0] returned 339,357.
> I am not sure why people still keep using the pyyaml but if you search around, there are many who suggest to turn in favor of "ruamel.yaml" rather of pyyaml.
> Personally it doesnt make difference for me, whether os-autoinst/openQA or os-autoinst/scripts, I just thought that it is worth to share this info
> 
> [0] https://github.com/search?q=ruamel.yaml&type=Code

As we use pyyaml in openQA develoment including yamllint (which uses pyyaml) it would be more consistent to use it. Looks like it won't be hard to rewrite script to use pyyaml. 
ruamel looks more advanced, but as we don't use it anywhere else as of now, we cannot directly benefit from it unfortunately. WDYT?

**Comment by b10n1k** [comment]
> 
> As we use pyyaml in openQA develoment including yamllint (which uses pyyaml) it would be more consistent to use it. Looks like it won't be hard to rewrite script to use pyyaml.
> ruamel looks more advanced, but as we don't use it anywhere else as of now, we cannot directly benefit from it unfortunately. WDYT?

I understand. And yes the main changes are quite trivial.  
The problem is that pyyaml is very limited in control over the indentation of the output. And i did try to find a way but it seems harder than you expect maybe. At least i didnt find a proper way to have correct output. There are even open issues in pyyaml repo, checking now. 
I dont know whats the best place for it.

**Comment by b10n1k** [comment]
@okurz @rwx788 i replaced the yuamel.yaml with pyyaml

**Comment by b10n1k** [comment]
Definitely the script might need some update. i will let you know 

> I've tried the script and got:
> 
> ```
> python3 create_scheduler.py 4247916 /tmp
> /usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host 'openqa.suse.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> Traceback (most recent call last):
>   File "create_scheduler.py", line 67, in <module>
>     _create_template(schd, conf, save_to)
>   File "create_scheduler.py", line 44, in _create_template
>     'description': '|\n%s' % configs['description'].replace('\n', '')}
> KeyError: 'description'
> ```
> 
> Could you please take a look?

**Comment by perlpunk** [comment]
Regarding PyYAML:
As a regular contributor to PyYAML, I think I can say that adding control over quoting style on output is a feature that is not planned in the near future, not to mention roundtripping with comments. For that ruamel is probably the better choice.

The most important thing is IMHO to add support for YAML 1.2, which is a bit tricky because the implementation is quite inflexible, especially if we want to add automatic schema detection depending on the version directive `%YAML 1.x`.

**Pull request merged**
