### PR TITLE
Ajust HA tests for use of HA_CLUSTER_TEST_ADVANCED

### PR DESCRIPTION
**Pull request by hsehic**
- use fancing*, check_logs and pacemeker_cts tests only if HA_CLUSTER_TEST_ADVANCED is set
- ajusted variables

### CODE REVIEW

**Comment by okurz** [comment]
what did you do to products/sle/main.pm? the changes look unrelated. Please fix

**Comment by hsehic** [comment]
executed ./tools/tidy

**Comment by okurz** [comment]
sure, makes sense. But please check the diff yourself and you should see that something broke. Did `tools/tidy` throw any errors?

**Comment by okurz** [comment]
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2732 for my proposal

**Comment by okurz** [comment]
replaced by #2732

**Pull request closed without merging**
