### PR TITLE
openqa_bootstrap_container: upload container journal on fail

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/66283

### CODE REVIEW

**Comment by okurz** [comment]
verification run plz

**Comment by asdil12** [comment]
https://openqa.opensuse.org/tests/1256031 - but if it doesn't fail it will only tell us that the syntax is correct.

**Comment by okurz** [comment]
then please simulate a failure so that we can see that your change does what it is supposed to do :)

**Comment by asdil12** [comment]
`SIMULATING FAILURE...` http://kazhua.suse.de/tests/28

**Comment by asdil12** [comment]
Log got uploaded: http://kazhua.suse.de/tests/28/file/openqa_bootstrap_container-journal_container.log

**Comment by okurz** [comment]
great

**Pull request merged**
