### PR TITLE
Don't install git in rstudio_prepare

### PR DESCRIPTION
**Pull request by dcermak**
- Related ticket: N/A
- Needles: not required
- Verification run: https://openqa.opensuse.org/tests/1199305

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by dcermak** [comment]
The verification run is green now.

**Comment by ggardet** [comment]
It seems to break now: https://openqa.opensuse.org/tests/1211453#step/rstudio_prepare/20

**Comment by dcermak** [comment]
For completeness: this PR is actually unrelated, so don't revert it please ;-)

**Pull request merged**
