### PR TITLE
sles12_autoinst_h1_btrfs.xml autoyast profile

### PR DESCRIPTION
**Pull request by psladek**

### CODE REVIEW

**Comment by coolo** [comment]
Your commit logs basically are the file name. That is too little information even for my taste - please put a bit of a description what you want to achieve with this in your commit log

**Comment by psladek** [comment]
- converted and sanitized sle12 profile, part of
   larger set of profiles from various sources
   and cases, to increase autoyast install stage coverage
 - further tests to follow

**Comment by okurz** [comment]
Please rewrite the commit messages according to https://github.com/os-autoinst/os-autoinst/#rules-for-commits
Maybe the filenames should better describe what is tested here

**Comment by okurz** [comment]
The commit "Removed package as of fate#320612" should be squashed into one of the other commits

**Comment by psladek** [comment]
description of ambiguous profiles is now included at the beginning of the xml file

**Comment by okurz** [comment]
LGTM

**Pull request merged**
