### PR TITLE
Update perltidy to 20201001

### PR DESCRIPTION
**Pull request by b10n1k**
update perltidy to 20201001

### CODE REVIEW

**Comment by alice-suse** [comment]
@b10n1k From changed files, it seems many irrelevant test code changes are also included. I guess it is not intended, right?

**Comment by schlad** [comment]
Please move comment to the git commit message. 
You also mean affected? instead of effected.

**Comment by okurz** [comment]
there is https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11169 , this is redundant.

**Comment by okurz** [comment]
I know https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11169 hasn't been up for long but it was there. I would really appreciate if more can care about open pull requests in this *collaborative* repository. In this case it would have even helped you directly merging my pull request :)
I can merge my own pull requests of course and did that myself now to fix the problems you are having but other contributors need the help of people that have merge permissions. Your help there would be appreciated.

**Pull request closed without merging**
