### PR TITLE
Refactor NFS client ID code & Increase timeout in copy_media call in hana_install test module

### PR DESCRIPTION
**Pull request by alvarocarvajald**
This PR includes 2 changes:

1. Refactor NFS client ID code so it is used by `copy_media` and `mount_media` methods.
2. Increase `copy_media` timeout from 30 minutes (1800 seconds) to 45 minutes (2700 seconds) in the `copy_media` call in the `sles4sap/hana_install` test module.

- Related ticket: https://progress.opensuse.org/issues/135923
- Needles: N/A
- Verification run: [HANA on 15-SP1](https://openqaworker15.qa.suse.cz/tests/236448), [NetWeaver on 12-SP5](http://openqaworker15.qa.suse.cz/tests/236449), [HANA on 15-SP5](http://openqaworker15.qa.suse.cz/tests/236450), [NetWeaver on 15-SP5](http://openqaworker15.qa.suse.cz/tests/236447), [HANA on 12-SP5](http://openqaworker15.qa.suse.cz/tests/236451)

### CODE REVIEW

**Comment by alvarocarvajald** [comment]
> I think we also need to run an rsync with `--dry-run --stats ` before the actual copy, to be able to see what is coming down the pipe and what failed. It will also let us compare the timeouts.

Will add that too.

**Review by bs-suse — APPROVED** [review]
LGTM

I'm neither for nor against the rsync dry run that @a-kpappas suggests.

**Review by lpalovsky — APPROVED** [review]
LGTM

**Comment by emiura** [comment]
LGTM

**Comment by alvarocarvajald** [comment]
> I think we also need to run an rsync with `--dry-run --stats ` before the actual copy, to be able to see what is coming down the pipe and what failed. It will also let us compare the timeouts.

Done. Verification runs restarted. I'll wait until we have them passing before merging.

**Comment by alvarocarvajald** [comment]
All VRs passed. Merging this.

**Pull request merged**
