### PR TITLE
Fix grub_test for cryptlvm when disable grub timeout

### PR DESCRIPTION
**Pull request by jknphy**
I closed accidentally: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3837

Fix grub_test for cryptlvm when disable grub timeout. grub screen was asserted twice, see this job, so this should help to finish test properly in the desktop and at the same time, not to remove lines enclosed in the "else" statement that probably are used for some other older job.

Related ticket: https://progress.opensuse.org/issues/25376

### CODE REVIEW

**Comment by jknphy** [comment]
I believe that the `else` should not affect other product and this particular issue would be solved or at least not hide forward problems in this test.

**Comment by okurz** [comment]
If you close a PR why not just open it again?

Please provide verification runs and please include TW tests

**Comment by jknphy** [comment]
I did a mess with my repo, as you can see in the previous closed pull request that I dragged commits from other people, there are more File changes that the one that I touched even if my pull request in my "updated" fork only contained one when I reopened. Very strange, maybe a github issue or just my fault. @SergioAtSUSE was providing verification for that due to is a different architecture. This change only affects tests with STORAGE_NG=1 & ENCRYPT=1 and avoid [double assert of grub](https://openqa.suse.de/tests/1239194#step/grub_test/10) For the rest, should behave exactly the same. I didn't find any STORAGE_NG in TW, but I can add [this run verification](http://dhcp227/tests/279#step/grub_test/1) for one with ENCRYPT=1:

**Comment by jknphy** [comment]
It seems that the initial point to hit 'ret' is incorrect and is blocking in other architectures, because only in ppc64 the password is after grub screen, which need to be further investigated.

**Pull request merged**
