### PR TITLE
Dont run docker tests on older SLES

### PR DESCRIPTION
**Pull request by mimi1vx**
fixes -> https://openqa.suse.de/tests/2423331/file/autoinst-log.txt

### CODE REVIEW

**Comment by sysrich** [comment]
I'm not sure I agree, or understand the need for this change.

We shouldn't be testing unsupported combinations, if we do test, and they fail, we want the job to fail.

@Vogtinator opinion?

**Comment by mimi1vx** [comment]
second option is dont use:
```
sub load_extra_tests_docker {
    my ($image_names, $stable_names) = get_suse_container_urls();
    return unless @$image_names;
```

directly in `main_common.pm`

**Comment by Vogtinator** [comment]
The whole point of the `die` is to kill the whole job. If the `die` is encountered, the test is incomplete and must fail.

So I strongly object this change,

**Comment by mimi1vx** [comment]
@Vogtinator  -- module is to die ... no whole job which tests many other things than "docker"

**Comment by Vogtinator** [comment]
If there are platforms where docker is available but no base container is, it would be fine to move the check inside the is_sle check.

Is that the case for the failing job?

**Comment by Vogtinator** [comment]
This approach looks better, but can it be moved into get_suse_container_urls?

**Comment by mimi1vx** [comment]
@Vogtinator  so `return undef, undef`  to suse_container_urls, and move `die ..... unless @images` into `docker_image.pm` and `podman_image.pm`  ?

**Comment by Vogtinator** [comment]
+1 from me

**Pull request merged**
