### PR TITLE
Enable docker_image test for all new SLE versions

### PR DESCRIPTION
**Pull request by Vogtinator**
It's necessary for 12 SP5+ and 15 SP1+ as well.

Untested.

### CODE REVIEW

**Comment by Vogtinator** [comment]
CC @pdostal

**Comment by pdostal** [comment]
We don't have images for SLES12sp5 nor for SLES15sp1 so it will the whole scenario on those - please see `lib/suse_container_urls.pm`.

**Comment by Vogtinator** [comment]
> We don't have images for SLES12sp5 nor for SLES15sp1 so it will the whole scenario on those - please see lib/suse_container_urls.pm.

URLs for those should be calculated automatically now.

**Comment by pdostal** [comment]
@Vogtinator that is true, well give me ~2 hours and we can merge it 👍

**Comment by Vogtinator** [comment]
> @Vogtinator LGTM for me.

Thanks for testing!

**Comment by Vogtinator** [comment]
Ping!

**Comment by okurz** [comment]
I guess you are pinging anybody that can merge? :)

**Pull request merged**
