### PR TITLE
Remove invalid softfailure

### PR DESCRIPTION
**Pull request by DrMullings**
Removed softfailure for bsc#1057223 which is resolved
And another softfailure whose bug is already closed

### CODE REVIEW

**Comment by QingmingSu** [comment]
Is there any soft failure for bsc#1057223 observed on o.s.d? I didn't see such soft failure for a while

**Comment by QingmingSu** [comment]
Seems the license agreement is still missing, see: 
https://openqa.suse.de/tests/1628657#step/addon_products_sle/9

And also refer to:
https://bugzilla.suse.com/show_bug.cgi?id=1080934

**Comment by ldevulder** [comment]
@QingmingSu, that's normal now, HA license is not shown anymore as it's the same license as SLES. Now when a license is the same as an already selected product it is not shown anymore (change since RC3).

**Comment by rwx788** [comment]
Please, crossecheck with @OleksandrOrlov, he crested this PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4911 which revert whole commit and not just a soft-failure.

**Comment by rwx788** [comment]
I guess we can close this one. WDYT?

**Comment by OleksandrOrlov** [comment]
@rwx788, I've double-checked PR #4911 and can confirm that the change is covered there.

**Comment by rwx788** [comment]
As per @OleksandrOrlov comment, I close this one. Feel free to reopen if we missed something.

**Pull request closed without merging**
