### PR TITLE
Workaround workqueue lockup message for select_console

### PR DESCRIPTION
**Pull request by Zaoliang**
we have sporadic issue with workqueue lockup message over console,
this breaks our test module.
see https://progress.opensuse.org/issues/60992
Needle PR:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/630
verfication test run:
http://f40.suse.de/tests/6211
http://f40.suse.de/tests/6229
http://f40.suse.de/tests/6230

### CODE REVIEW

**Comment by StefanBruens** [comment]
The handling should go to the generic code, as this can happen for **any** module which calls select_console.

The corresponding code is in lib/susedistribution.pm: `sub console_selected()`.

**Comment by SergioAtSUSE** [comment]
@StefanBruens, any comments?

**Comment by StefanBruens** [comment]
Given I can't see any of the verification runs, it is hard to comment on this. Does any of the VRs trigger the workaround?

**Comment by SergioAtSUSE** [comment]
None of the provided runs trigger the workaround

@Zaoliang, please, could you run some jobs on O3 with your PR?

**Comment by Zaoliang** [comment]
the problem is: I cannot reproduce this lookup message. I even don't see this issue on o3 recently.

**Comment by Zaoliang** [comment]
https://openqa.opensuse.org/tests/1146571#live

**Comment by StefanBruens** [comment]
As this is a non-deterministic issue, you likely have to do multiple runs. Scheduling these while openQA is busy probably "helps" to trigger the problem.

For better tracking of the problem, please add a
```
record_soft_failure "boo#1126782 - Spurious kernel message on console";
```
before the `send_key 'ret';`.

**Comment by Zaoliang** [comment]
> As this is a non-deterministic issue, you likely have to do multiple runs. Scheduling these while openQA is busy probably "helps" to trigger the problem.
> 
> For better tracking of the problem, please add a
> 
> ```
> record_soft_failure "boo#1126782 - Spurious kernel message on console";
> ```
> 
> before the `send_key 'ret';`.

not busy? O3 is slow and busy all the time...
anyway I will run some tests and see if we can reproduce this lockup message.

**Comment by Zaoliang** [comment]
https://openqa.opensuse.org/tests/1149288#step/orphaned_packages_check/1

It works!

**Comment by SergioAtSUSE** [comment]
> This would be one additional unconditional screen check in all test scenarios regardless if the connected way can even show this message.

The check_screen is the condition. The lockup happens in any arch. Do you mean it should only check for 15-SP2+?

**Comment by StefanBruens** [comment]
> The check_screen is the condition. The lockup happens in any arch. Do you mean it should only check for 15-SP2+?

The check_screen is always run, even when the connection is over SSH, where we will never see any kernel messages. AFAIK this can only happen when the console is a VTTY.

**Comment by okurz** [comment]
> not busy? O3 is slow and busy all the time...

The load differs over time so the suggestion is valid to expect potentially different results based on worker load.

The job you referenced shows that the issue is already correctly detected when checking for the "root-console" terminal as in https://openqa.opensuse.org/tests/1149288#step/orphaned_packages_check/2 which already yields a soft-fail. It does *not* show the code you added so the reference is not a proof for your PR more that we do not even need it. Apparently there is already a check at the right location with the "root-console" tag in an efficient manner as there is no additional screen check (Maybe you just want to add the bug as tag for the soft-fail root-console needle and apply the "ret" key press after the tag has been found).

Please read my suggestions that I provided carefully but I will also try to make it more clear:

1. The PR is added a costly check to too many places where we do not need it
2. There is already a working check, no need to add an additional one
3. Your git commit details basically describe "we need this" but there should be a proper explanation of the problem and your proposed solution and also a good statistical proof (suggestion: https://progress.opensuse.org/projects/openqatests/wiki#Statistical-investigation)

**Comment by Zaoliang** [comment]
okay, I checked this again and as okurz already pointed out that the code change is not proved. Since this issue is already covered by workaround issue. I'll close this PR and reject the ticket, thanks

**Pull request closed without merging**
