### PR TITLE
Public Cloud: Reuse resources in Google and Azure

### PR DESCRIPTION
**Pull request by pdostal**
* Follows: #18123
 * Verification runs: 
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-EC2-Updates.aarch64	  [publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/5424)	[23](https://pdostal-server.suse.cz/tests/5424)	16 minutes ago
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-EC2-BYOS-Updates.x86_64	  [publiccloud_consoletests@64bit](https://pdostal-server.suse.cz/tests/5421)	[23](https://pdostal-server.suse.cz/tests/5421)	23 minutes ago
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-GCE-BYOS-Updates.aarch64	  [publiccloud_containers@64bit](https://pdostal-server.suse.cz/tests/5422)	[25](https://pdostal-server.suse.cz/tests/5422)	38 minutes ago
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-Azure-BYOS-Updates.aarch64	  [publiccloud_img_proof@64bit](https://pdostal-server.suse.cz/tests/5420)	[24](https://pdostal-server.suse.cz/tests/5420)	about an hour ago
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-Azure-Basic-Updates.x86_64	  [publiccloud_cloud_netconfig@64bit](https://pdostal-server.suse.cz/tests/5425)	[7](https://pdostal-server.suse.cz/tests/5425)	about an hour ago
> [BuildPDOSTAL](https://pdostal-server.suse.cz/tests/overview?build=PDOSTAL&distri=sle&version=15-SP5) of sle-15-SP5-GCE-Updates.x86_64	  [publiccloud_img_proof@64bit](https://pdostal-server.suse.cz/tests/5423)	[28](https://pdostal-server.suse.cz/tests/5423)	about an hour ago

### CODE REVIEW

**Review by ricardobranco777 — COMMENTED** [review]
Are you sure these resources are not cleaned up by pcw?

**Comment by pdostal** [comment]
> Are you sure these resources are not cleaned up by pcw?

You may so far check [gitlab.suse.de/qac/terraform#373624](https://gitlab.suse.de/qac/terraform/-/commit/37362464e56fe99a1be6089d7d76a3af6c656b3f). Maybe @asmorodskyi would also like to join here.

I'm right now working on Terraform merge request for Amazon.

**Comment by asmorodskyi** [comment]
> Are you sure these resources are not cleaned up by pcw?

didn't get your question . whole point here is to NOT do a cleanup but also NOT to create anything new by tests ( meaning network infra ofc. we still want to create VMs )

**Comment by ricardobranco777** [comment]
> > Are you sure these resources are not cleaned up by pcw?
> 
> didn't get your question . whole point here is to NOT do a cleanup but also NOT to create anything new by tests ( meaning network infra ofc. we still want to create VMs )

We're reusing resources and we must make sure those are always available - not cleanup by pcw.

**Comment by pdostal** [comment]
Blocked by SUSE/pcw#328

**Pull request merged**
