### PR TITLE
Send EOF to serial terminal

### PR DESCRIPTION
**Pull request by mloviska**
Motivation: [Failed login](https://openqa.opensuse.org/tests/1466407#step/btrfsmaintenance/1)

Transition from `rescue` to `default` target terminates both user sessions on both previously logged consoles (tty and ttyS) in QEMU.
Unfortunately in case of failure, serial terminal might not been able to match login prompt and eating the stale buffer does not help to recover login prompt.
Issuing `ctrl+d` might work for now. 

- Verification run: [Build20201109-jeos-filesystem@64bit_virtio](http://kepler.suse.cz/tests/2659#step/btrfsmaintenance/1)

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

**Comment by Vogtinator** [comment]
> I can recommend the tool hub (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script pr-last to create a PR with proper description for these simple one-commit PRs:

When I run `git push`, I get a link where I can open a PR with the title and description already filled out. No other tools needed.

**Comment by Vogtinator** [comment]
I believe what happens is this:

1. `consoletest_setup` logs into serial terminal, a snapshot is saved
2. `snapper_jeos_cli` does a few reboots and so logs out again
3. `btrfs_qgroups` fails (for whatever reason) and triggers a restore of `lastgood`. This means the serial terminal is logged in again!
4. `snapper_cleanup` does `systemctl default` and resets all consoles. For some reason the serial terminal is still logged in.

When `btrfs_qgroups` doesn't fail, there is no snapshot restore and so the console is still logged out, matching what openQA expects.

**Comment by okurz** [comment]
> When I run `git push`, I get a link where I can open a PR with the title and description already filled out. No other tools needed.

Both works. With `hub` it's one command for me from CLI, no need to switch to the browser afterwards. I normally only look into the browser sometime later or when receiving an email notification from reviews or CI results.

**Comment by cfconrad** [comment]
I like this approach, as it makes our login behavior more robust.
But I would like to discus also the thing, that we might miss some coverage. The case that we always logout, might hide errors, which actually expect a logout (e.g. just calling `exit` and expect login-prompt). Or even, that we see a login-prompt after reboot without typing anything on the console...
Maybe we should make it conditional - so we do not fail during some tests, where getting a terminal is just the "environment".

**Comment by Vogtinator** [comment]
> The case that we always logout, might hide errors, which actually expect a logout (e.g. just calling exit and expect login-prompt). Or even, that we see a login-prompt after reboot without typing anything on the console...

For other consoles (specifically ttyConsole), there's code to handle the "already logged in" case explicitly. Here the same could be done, but it's not as easy as this allows reconfiguring the login prompt, so it's not possible to handle every case...

**Comment by cfconrad** [comment]
> For other consoles (specifically ttyConsole), there's code to handle the "already logged in" case explicitly.

that sounds promising! Just curious, do you have a pointer to these tests?

**Comment by Vogtinator** [comment]
> > For other consoles (specifically ttyConsole), there's code to handle the "already logged in" case explicitly.
> that sounds promising! Just curious, do you have a pointer to these tests?

AFAICT that's https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/susedistribution.pm#L727 and it can be seen here: https://openqa.opensuse.org/tests/1476548#step/glibc_locale/81

**Comment by okurz** [comment]
@mloviska as you are touching a crucial lib module used in a lot of tests I recommend you trigger many more verification runs, e.g. also a bit more exotic hardware, SLE maintenance tests, etc.

With 

Please http://open.qa/docs/#_triggering_tests_based_on_an_any_remote_git_refspec_or_open_github_pull_request that should be a breeze :)

**Comment by mloviska** [comment]
> Please put yourself into the shoes of future-Martin - with a realistic human memory, i.e. forgetting things :) You might be investigating a very weird issue just to find this one code line you changed and all you find in the git commit message is stating the _what_, not the _reasoning_.
> 
> What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has _only_ the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.
> 
> I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [pr-last](https://github.com/okurz/scripts/tree/master/pr-last) to create a PR with proper description for these simple one-commit PRs:
> 
> ```shell
> $ cat $(which git-pr-last )
> #!/bin/sh -e
> target="${target:-"$USER"}"
> git push $target && git show --no-patch --format=%B | hub pull-request -F -
> ```

I do `git commit -m "foo"`, `git push` and fill the template in the description directly in GitHub. I haven't been aware of this difference. Thanks!

**Comment by mloviska** [comment]
> I like this approach, as it makes our login behavior more robust.

Seems like it works only on QEMU backend, although does not break [s390x](https://openqa.suse.de/tests/5078074) either.

On the second thought, I am not sure whether it is the right approach as [Fabian stated the situation correctly](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11405#issuecomment-728130078). We restore SUT's VM to state when `consoletest_setup` finished, but openQA's test object has been not restored therefore mismatch occurs.

Ideally, we should save states of both openQA test object and VM's snapshot, but that should be done in `os-autoinst` repo.
Maybe meanwhile, we can log out consoles in `consoletest_setup` to be consistent, but that would also imply that `consoletest_setup` should be the last module in chain storing `lastgood`.

**Comment by Vogtinator** [comment]
> Seems like it works only on QEMU backend, although does not break s390x either.

Where does it fail?

> Ideally, we should save states of both openQA test object and VM's snapshot, but that should be done in os-autoinst repo.

That's done for consoles already, but the issue here is that `reset_consoles` without actually making sure that the serial terminalis also logged out doesn't work. #11415 is another case of this. For other consoles it works because those can handle the case of logging into an already logged in instance.

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11439#issuecomment-731073664 is a related issue.

> Maybe meanwhile, we can log out consoles in consoletest_setup to be consistent, but that would also imply that consoletest_setup should be the last module in chain storing lastgood.

That won't really work, it restricts `lastgood` too much, to the point of being almost useless.

**Pull request closed without merging**
