### PR TITLE
Extract command from var test_conf_file_content

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Related ticket: https://progress.opensuse.org/issues/67234
- Verification run: https://openqa.suse.de/tests/4565885#step/autofs_client/40

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@dzedro, would you be able to provide a verification run for this PR?

**Comment by SergioAtSUSE** [comment]
@dzedro, I have it: https://openqa.suse.de/tests/4565885#step/autofs_client/40

**Comment by dzedro** [comment]
When you do changes in MM you should have also MM VR, which you didn't have also in previous PR.

**Comment by dzedro** [comment]
https://openqa.suse.de/tests/4566111#step/autofs_client/24

**Pull request merged**
