### PR TITLE
Add MDS_TAA and MITIGATIONS testcases for CPU_BUGS

### PR DESCRIPTION
**Pull request by Dawei-Pang**
These changes will address the followed requirements:
1. The mitigation switch for MDS and TAA are linkage, test individual
or combination mitigation according to vulnerable detection status.
2. Tests kernel boot options "mitigations=auto/off/auto,nosmt" by
verifying sysfs changes according to vulnerable detection status.

Major changes to implement above requirements:
1. Add/improve TAA and  L1TF vulnerable detection.
2. Add/improve read_cpuid_*
3. Mitigation.pm: Handle ARRAY or non-ARRAY on check_default_status(),
check_sysfs(), add_parameter() and remove_parameter()
4. Workflow for MDS_TAA and MITIGATIONS:
new Mitigation obj with hash -> check vulnerable -> update hash -> do_test
5. Fill checking pairs between mitigation switch and sysfs output.
6. Share mitigations_list from each tests.

Verification URL: http://10.67.19.72/

### CODE REVIEW

**Comment by Dawei-Pang** [comment]
@lansuse @XGWang0 @alice-suse would you please help to review this PR? Thank you!

**Comment by lansuse** [comment]
LGTM

**Comment by XGWang0** [comment]
LGTM， 
I have a question, is that if a new test case coming, we have to create a .pm file to deal with the new test case, right?

**Comment by Dawei-Pang** [comment]
> LGTM，
> I have a question, is that if a new test case coming, we have to create a .pm file to deal with the new test case, right?

Thanks! The new test cases are mds_taa.pm(new) and mitigations.pm(refresh old implementation).

**Comment by alice-suse** [comment]
@Dawei-Pang Seems this PR changes a lot of files. I only see one verification link. I am not sure whether you already did enough various verification locally?

**Comment by Dawei-Pang** [comment]
> @Dawei-Pang Seems this PR changes a lot of files. I only see one verification link. I am not sure whether you already did enough various verification locally?

Thanks! 

Yes, I changes lot files.
To guarantee quality I ran this codes with all test cases more than 5 times (one loop every night) and 3 platforms to verification.
That is why I provide a openqa URL for verification.

-Dawei

**Comment by alice-suse** [comment]
Ah, cool

**Pull request merged**
