### PR TITLE
Add Lynis baseline for aarch64 Tumbleweed

### PR DESCRIPTION
**Pull request by ggardet**
- Verification run: 
  - https://openqa.opensuse.org/t1950143
  - https://openqa.opensuse.org/t1950144

### CODE REVIEW

**Comment by Vogtinator** [comment]
Noteworthy diff to x86_64:

```
   - Disable kernel support of some filesystems
-    - Module cramfs is blacklisted                            [ OK ]
-    - Module freevxfs is blacklisted                          [ OK ]
-    - Module hfs is blacklisted                               [ OK ]
```

Shouldn't this blacklisting also appear on aarch64?

**Comment by Vogtinator** [comment]
CC @lilyeyes

**Comment by lilyeyes** [comment]
> Noteworthy diff to x86_64:
> 
> ```
>    - Disable kernel support of some filesystems
> -    - Module cramfs is blacklisted                            [ OK ]
> -    - Module freevxfs is blacklisted                          [ OK ]
> -    - Module hfs is blacklisted                               [ OK ]
> ```
> 
> Shouldn't this blacklisting also appear on aarch64?
Thanks for the PR.
I am not sure if missing the blacklisting is OK. But I checked the lynis outputs for sle14sp4 on aarch64 it is the same with your baseline (no the `Module * is blackedlisted [OK]`). Etc, https://openqa.suse.de/assets/other/07274343-baseline-lynis-audit-system-nocolors-15-SP4-aarch64-textmode
You can ask jsegitz@suse.de for a double check for TW.

**Comment by Vogtinator** [comment]
> I checked on a current tumbleweed x86 and there the modules are also not blacklisted. So it's fine to have this missing for aarch64.

They are blacklisted by `/usr/lib/modprobe.d/60-blacklist_fs-*.conf` in the `suse-module-tools` package.

Did you check using Lynis? If so, it might be a bug or intentional change in display.

**Comment by ggardet** [comment]
@lilyeyes The blacklisting is only on Tumbleweed.

**Comment by tjyrinki** [comment]
The CI is stuck on Running to isotovideo test, could you make a dummy force push to trigger it again? At least I do not have powers to kick the CI manually otherwise.

**Comment by ggardet** [comment]
> The CI is stuck on Running to isotovideo test, could you make a dummy force push to trigger it again? At least I do not have powers to kick the CI manually otherwise.

Done

**Pull request merged**
