### PR TITLE
Avoid die in check_takeover for uninitialized variables

### PR DESCRIPTION
**Pull request by mpagot**
Avoid an exception if get_hana_topology return an empty result. It could happens if SAPHanaSR-showAttr is not successful and output is not what expected.
This new behavior is obtained avoiding the usage of local variables in check_takeover.
Sleep 30 moved in a different position only to be used once for each get_hana_topology and not to be called when there's no more retry to run.
Add some unit testing for these two functions.

- Related ticket: TEAM-8878

### sle-15-SP4-HanaSr-Azure-Byos-x86_64-Build15-SP4_2023-12-15T05:03:11Z-hanasr_azure_test_sapconf_spn@64bit
 
 -  http://openqaworker15.qa.suse.cz/tests/273037 :red_circle:  Here the `check_takeover` runs fine http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_a-primary/96  but here http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_b-primary/99 it is not ok
 
```
# Test died: Use of uninitialized value $host_entry{"sync_state"}
 in string eq at /var/lib/openqa/pool/75/os-autoinst-distri-opensuse/lib/sles4sap_publiccloud.pm line 365.
```
It is because field `sync_state` is missing in **SAPHanaSR-showAttr --format=script**
It needs PR improvement: https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/117380726ba2dd7f10aa6c2a3078a08886185ed7..18da85a3f6ba7f6965c97064170154e325960242

-  http://openqaworker15.qa.suse.cz/tests/273217 :green_circle: in the same test, successful takeover are properly handled like in http://openqaworker15.qa.suse.cz/tests/273217#step/Stop_site_a-primary/56 and failure is due to ssh connection.

### sle-12-SP5-Azure-SAP-PAYG-Incidents-x86_64-Build:31892:nfs-utils-SAPHanaSR-ScaleUp-PerfOpt@az_Standard_E8s_v3 

 -  http://openqaworker15.qa.suse.cz/tests/273038 :red_circle:  Fails at `sudo zypper --no-gpg-checks ar -f -n TEST_0` due to locked zypper. Issue is not related to the PR content, but prevent code of interest to be reached.
 -  http://openqaworker15.qa.suse.cz/tests/273216 :green_circle: `Test died: Test failed: takeover failed to complete` in case of `Signon CIB failed`. It is the right way to react to terminate an unsuccessful takeover

### CODE REVIEW

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by lilyeyes** [comment]
But in the VRs the `Test died: Use of uninitialized value $host_entry{"sync_state"} in string eq ... ` is still existing with this branch: http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_b-primary/99

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Review by hadeskun — APPROVED** [review]
LGTM

**Comment by mpagot** [comment]
> But in the VRs the `Test died: Use of uninitialized value $host_entry{"sync_state"} in string eq ... ` is still existing with this branch: http://openqaworker15.qa.suse.cz/tests/273037#step/Crash_site_b-primary/99

Yes, fixed in https://github.com/os-autoinst/os-autoinst-distri-opensuse/compare/117380726ba2dd7f10aa6c2a3078a08886185ed7..18da85a3f6ba7f6965c97064170154e325960242

**Review by lpalovsky — COMMENTED** [review]
LGTM

**Pull request merged**
