### PR TITLE
Remove sles11sp4 from virtulization tests

### PR DESCRIPTION
**Pull request by tbaev**
From https://www.suse.com/lifecycle/, SLE11SP4 LTSS will end up in "31 Mar 2022" this PR will completely remove SLE11SP4 from our tests.

- Related ticket: https://progress.opensuse.org/issues/104749
- Needles: N/A
- Verification run: 
http://openqa.qam.suse.cz/tests/38016
http://openqa.qam.suse.cz/tests/38028
http://openqa.qam.suse.cz/tests/38085

### CODE REVIEW

**Comment by tonyyuan1** [comment]
Although there aren't VR yet, the change looks very good to me.

**Comment by Julie-CAO** [comment]
LGTM

**Comment by tbaev** [comment]
@alice-suse , @tonyyuan1 I have done VR runs, I think we are good for merge this PR :)

http://openqa.qam.suse.cz/tests/38016
http://openqa.qam.suse.cz/tests/38028
http://openqa.qam.suse.cz/tests/38085

**Comment by alice-suse** [comment]
@tbaev LGTM, thanks. I am afraid we need to hold on the merge of the PR until end of March when 11SP4 LTSS really ends.

**Review by alice-suse — APPROVED** [review]

**Comment by tbaev** [comment]
Yes, we should merge it at the end of March. Just wanted to be reviewed/approved that is good to be merged.

**Pull request merged**
