### PR TITLE
ltp: Use power_action() to avoid incompletes

### PR DESCRIPTION
**Pull request by Soulofdestiny**
[related ticket](https://progress.opensuse.org/issues/37087)
[Verification runs](http://opeth/tests/2451) to http://opeth/tests/2552
[crosscheck with old code](http://opeth/tests/2551) -> incomplete

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
@pevik

**Comment by okurz** [comment]
LGTM

**Comment by rwx788** [comment]
Let's try it out ;)

**Comment by pevik** [comment]
@Soulofdestiny thanks for handling it, @okurz @rwx788 thanks for review!

**Comment by pevik** [comment]
@richiejp @mimi1vx FYI

**Comment by pevik** [comment]
@Soulofdestiny I don't remember details, but in some cases incompleteness was caused by slow system, when doing snapshots (e.g. aarch64).

**Pull request merged**
