### PR TITLE
Call enter_userinfo as a function not as a method

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
$self is not needed and changes to make $self work are not desired.

### CODE REVIEW

**Comment by alvarocarvajald** [comment]
This breaks tests: https://openqa.suse.de/tests/4009395#step/user_settings/3

Can we go back to enforcing verification runs?

**Comment by rwx788** [comment]
Missing import =(

**Comment by foursixnine** [comment]
My bad guys :(,

**Comment by alvarocarvajald** [comment]
> Missing import =(

It's in L22 as: `use parent qw(installation_user_settings y2_installbase);`

**Comment by SergioAtSUSE** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9834

**Comment by foursixnine** [comment]
@SergioAtSUSE Let's just revert this, if the previous state didn't have any implications instead

**Comment by SergioAtSUSE** [comment]
> @SergioAtSUSE Let's just revert this, if the previous state didn't have any implications instead

It had, yast test was broken for missing self.

**Pull request merged**
