### PR TITLE
addon_products_yast2 with SCC registration

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by coolo** [comment]
What's wrong with using parameters? Global variables are even worse IMO

**Comment by okurz** [comment]
-1: variable names are better but I don't see why this requires global variables (as stated by @coolo )

**Comment by dzedro** [comment]
should be better now

**Comment by coolo** [comment]
yes. does it still work too? :)

**Comment by dzedro** [comment]
of course it does still work :)

http://10.100.98.90/tests/347
http://10.100.98.90/tests/348

**Comment by dzedro** [comment]
I will update this PR with working SCC registration

**Comment by dzedro** [comment]
without SCC registration
http://10.100.98.90/tests/overview?distri=sle&version=12-SP1&build=GMd&groupid=1
with SCC registration
http://10.100.98.90/tests/overview?distri=sle&version=12-SP1&build=GMc&groupid=1

**Pull request merged**
