### PR TITLE
changes to support maintenance testing

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
anyone from QA having any comments on my changes? @sysrich,@razghe, @dzedro?

**Comment by dzedro** [comment]
I had yesterday comment to SCC part, but it was gone faster than I could react. :)
:+1:

**Comment by lnussel** [comment]
I filed that one separately now

**Comment by lnussel** [comment]
can we merge this so have at least tomorrow to fix potential fallout?

**Comment by nilxam** [comment]
LGTM. But it has SLE relates, so leave the button to QA...

**Pull request merged**
