### PR TITLE
Also use needles to find the DVD

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by okurz** [comment]
why?

**Comment by lnussel** [comment]
the workers use an old ovmf on openqa.o.o where the order of entries in that menu also differs from what I get on my workstation with TW.

**Comment by lnussel** [comment]
this one doesn't seem to work at all https://openqa.opensuse.org/tests/244797

oh my *sigh*

**Comment by okurz** [comment]
well, LGTM. merge if you like

**Pull request merged**
