### PR TITLE
Verify that vim-data is not there only for JeOS

### PR DESCRIPTION
**Pull request by rwx788**
Hotfix for [PR#4050](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4050)

### CODE REVIEW

**Comment by DimStar77** [comment]
TW does not install vmi-data in every scenario; That's been like this for like ever

**Comment by DimStar77** [comment]
Hmm.. we have an explicit

```job lock name vim-data```

on the Staging test dvd1, dating back to Apr 2014

**Comment by DimStar77** [comment]
ok - thanks to @coolo outstanding memory: we can't add vim-data everywhere, due to space constraints.

The most limited ones at the moment are the Live images (e.g Rescue CD, which, as the name suggests, has to fit on a CD); vim-data (27MiB installed size) was blocked out from this type of media to have room for other things - a hard fail is thus not acceptable on TW when vim-data is not present

**Comment by rwx788** [comment]
@mnowaksuse No worries, it's hard to predict behavior for all distris =)

**Comment by DimStar77** [comment]
@mnowaksuse indeed, don't worry about that. Even we had to think again why there were cases where we ran without vim-data... There are so many constraints to consider, we don't expect all test writers to remember all of them.

The important thing is that we work quickly on fixes once such fallouts are identified - which definitively happened.

**Pull request merged**
