### PR TITLE
Remove az_sas_token variable from qesap configuration yaml config files

### PR DESCRIPTION
**Pull request by badboywj**
With https://jira.suse.com/browse/TEAM-9540, having the az_sas_token value defined in qesap.py's YAML configuration files is no longer necessary, as qesap.py will calculate a SAS token dynamically if a valid key name was provided in az_key_name.

- Related ticket: https://jira.suse.com/browse/TEAM-9668
- Needles: None
- Verification run:
    - hanasr-regresion
        - 15-SP6-HanaSr-Aws-Byos-hanasr_aws_test_saptune_fencing_native
            - https://openqaworker15.qa.suse.cz/tests/297635 :green_circle: : false not related to az_sas_token
        - 15-SP5-HanaSr-Aws-Byos-hanasr_aws_test_fencing_sbd
            - https://openqaworker15.qa.suse.cz/tests/297617 :green_circle: false not related to az_sas_token
        - 15-SP6-HanaSr-Azure-Byos-hanasr_azure_test_saptune_spn
            - https://openqaworker15.qa.suse.cz/tests/297636 :green_circle: false not related to az_sas_token
        - 15-SP5-HanaSr-Azure-Byos-hanasr_azure_test_sapconf_msi
            - https://openqaworker15.qa.suse.cz/tests/297618 :green_circle: false not related to az_sas_token
        - 12-SP5-HanaSr-Azure-Byos-hanasr_azure_test_msi
            - https://openqaworker15.qa.suse.cz/tests/297637 :green_circle: false not related to az_sas_token
        - 12-SP5-HanaSr-Azure-Byos-hanasr_azure_test_sbd
            - https://openqaworker15.qa.suse.cz/tests/297638 :green_circle: 
    - qesap-regression-latest
        - 15-SP6-Qesap-Azure-Payg-qesap_azure_saptune_test
            - https://openqaworker15.qa.suse.cz/tests/297382 :green_circle: 
        - 15-SP6-Qesap-Azure-Byos-qesap_azure_saptune_test
            - https://openqaworker15.qa.suse.cz/tests/297383 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_fencing_native_test
            - https://openqaworker15.qa.suse.cz/tests/297384 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_fencing_sbd_test
            - https://openqaworker15.qa.suse.cz/tests/297413 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_ibsmirror_peering_test
            - https://openqaworker15.qa.suse.cz/tests/297386 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_r48xlarge_test
            - https://openqaworker15.qa.suse.cz/tests/297387 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_r58xlarge_test
            - https://openqaworker15.qa.suse.cz/tests/297414 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_r5bmetal_test
            - https://openqaworker15.qa.suse.cz/tests/297454 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_sapconf_test
            - https://openqaworker15.qa.suse.cz/tests/297390 :green_circle: 
        - 15-SP6-Qesap-Aws-Byos-qesap_aws_saptune_test
            - https://openqaworker15.qa.suse.cz/tests/297391 :green_circle: 
        - 15-SP5-Qesap-Aws-Payg-qesap_aws_saptune_test
            - https://openqaworker15.qa.suse.cz/tests/297392 :green_circle: 
        - 15-SP5-Qesap-Gcp-Payg-qesap_gcp_sapconf_test
            - https://openqaworker15.qa.suse.cz/tests/297393 :green_circle: 
        - 15-SP5-Qesap-Gcp-Byos-qesap_gcp_sapconf_test
            - https://openqaworker15.qa.suse.cz/tests/297394 :green_circle: 
        - 15-SP5-Qesap-Gcp-Byos-qesap_gcp_saptune_test
            - https://openqaworker15.qa.suse.cz/tests/297395 :green_circle: 
        - 15-SP5-Qesap-Gcp-Byos-qesap_gcp_sbd_test
            - https://openqaworker15.qa.suse.cz/tests/297396 :green_circle: 
    - Maintenance SAP Single Incidents
        - 15-SP6-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt
            - https://openqa.suse.de/tests/15438276 :green_circle: 
        - 15-SP6-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt-msi
            - https://openqa.suse.de/tests/15438277 :green_circle: false  not related to az_sas_token 
        - 15-SP6-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt-spn
            - https://openqa.suse.de/tests/15438278 :green_circle: 
        - 15-SP5-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt-msi
            - https://openqaworker15.qa.suse.cz/tests/297380 :green_circle: false not related to az_sas_token
        - 15-SP5-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt
            - https://openqaworker15.qa.suse.cz/tests/297381 :green_circle: false not related to az_sas_token 
        - 12-SP5-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt
            - https://openqa.suse.de/tests/15438281 :green_circle: 
        - 12-SP5-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt-msi
            - https://openqa.suse.de/tests/15438282 :green_circle: false  not related to az_sas_token
        - 12-SP5-Azure-SAP-BYOS-SAPHanaSR-ScaleUp-PerfOpt-spn
            - https://openqa.suse.de/tests/15438283 :green_circle: false not related to az_sas_token
        - 12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_delete_rename
            - https://openqa.suse.de/tests/15438284 :green_circle: 
        - 12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_notes
            - https://openqa.suse.de/tests/15438285 :green_circle: 
        - 12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_overrides
            - https://openqa.suse.de/tests/15438286 :green_circle: 
        - 12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_solutions
            - https://openqa.suse.de/tests/15438287 :green_circle: 
        - 15-SP6-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt
            - https://openqa.suse.de/tests/15438288 :green_circle: 
        - 15-SP6-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt-msi
            - https://openqa.suse.de/tests/15438289 :green_circle: false not related to az_sas_token
        - 15-SP6-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt-spn
            - https://openqa.suse.de/tests/15438290 :green_circle: false not related to az_sas_token
        - 12-SP5-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt
            - https://openqa.suse.de/tests/15438291 :green_circle: 
        - 12-SP5-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt-msi
            - https://openqa.suse.de/tests/15438292 :green_circle: false not related to az_sas_token
        - 12-SP5-Azure-SAP-PAYG-SAPHanaSR-ScaleUp-PerfOpt-spn
            - https://openqa.suse.de/tests/15438293 :green_circle: false not related to az_sas_token
        - 12-SP5-Azure-SAP-PAYG-sles4sap_gnome_saptune_delete_rename
            - https://openqa.suse.de/tests/15438294 :green_circle: 
        - 12-SP5-Azure-SAP-PAYG-sles4sap_gnome_saptune_notes
            - https://openqa.suse.de/tests/15438295 :green_circle: 
        - 12-SP5-Azure-SAP-PAYG-sles4sap_gnome_saptune_overrides
            - https://openqa.suse.de/tests/15438296 :green_circle: 
        - 12-SP5-Azure-SAP-PAYG-sles4sap_gnome_saptune_solutions
            - https://openqa.suse.de/tests/15438297  :green_circle:

### CODE REVIEW

**Review by mpagot — APPROVED** [review]
LGTM, even some of the red jobs has token generated, that is enough to say the PR code is fine.

**Comment by lilyeyes** [comment]
> IMO, this PR does not need too many VRs, for example for "12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_*" only one VR (for example only do VR for delete_rename) is enough.

Sorry, mr_test is not a good example as this PR does not revise `mr_test_azure.yaml` so no need to do VRs for mr_test.

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by badboywj** [comment]
> > IMO, this PR does not need too many VRs, for example for "12-SP5-Azure-SAP-BYOS-sles4sap_gnome_saptune_*" only one VR (for example only do VR for delete_rename) is enough.
> 
> Sorry, mr_test is not a good example as this PR does not revise `mr_test_azure.yaml` so no need to do VRs for mr_test.

yes, you are right. I am not familiar the code and running more jobs to make sure no problem in the PR :D

**Review by BillAnastasiadis — APPROVED** [review]
LGTM

**Pull request merged**
