### PR TITLE
Modify partition size as ppc requires > 10.5GiB

### PR DESCRIPTION
**Pull request by JRivrain**
Fixes this failure https://openqa.suse.de/tests/3561668#step/modify_existing_partition/16

- Verification run: 
[ppc64le](https://openqa.suse.de/tests/3564642#step/logs_from_installation_system/19), [X86_64](https://openqa.suse.de/tests/3564643#step/validate_modify_existing_partition/12)

### CODE REVIEW

**Comment by b10n1k** [comment]
i have a question. why the size of the disk is 30? i can see that the settings have HDDSIZEGB	20?

**Comment by JRivrain** [comment]
> i have a question. why the size of the disk is 30? i can see that the settings have HDDSIZEGB 20?

Good catch, though it is not related to this change, and does not prevent the test suite from working. This test depends on create_hdd_gnome, which creates a 30GiB disk. Then I assume here we are using the default size. I could update this parameter in the test suite.

**Comment by JRivrain** [comment]
> > i have a question. why the size of the disk is 30? i can see that the settings have HDDSIZEGB 20?
> 
> Good catch, though it is not related to this change, and does not prevent the test suite from working. This test suite depends on create_hdd_gnome, which creates a 30GiB disk. Then I assume here we are using the default HDDSIZEGB. I could update this parameter in the test suite.

Actually, it really does not matter, all the other tests depending on create_hdd_gnome are in the same situation.

**Comment by jknphy** [comment]
I'm afraid those comments will still remain there, but let's not block merging for such a minor thing :)

**Pull request merged**
