### PR TITLE
Also remove https repositories

### PR DESCRIPTION
**Pull request by DrMullings**
As requested by lnussel this is a preparation for https repos

- Related ticket: https://progress.opensuse.org/issues/66259
- Verification run: https://openqa.opensuse.org/tests/1313827

### CODE REVIEW

**Comment by DrMullings** [comment]
New verification:
https://openqa.opensuse.org/tests/1321073

**Comment by DrMullings** [comment]
@foursixnine please review

**Comment by DrMullings** [comment]
New try
https://openqa.opensuse.org/tests/1321626

**Comment by DrMullings** [comment]
Worked like a charm:
https://openqa.opensuse.org/tests/1323235#step/zypper_clear_repos/2

Ready to merge if no one has a problem with this

**Comment by DrMullings** [comment]
@Zaoliang

**Comment by Zaoliang** [comment]
LGTM

**Comment by DimStar77** [comment]
Does not look good to me

https://openqa.opensuse.org/tests/overview?distri=microos&distri=opensuse&version=Tumbleweed&build=20200704&groupid=1

Plenty of 'zypper_clear_repos' failures. The first call deleted already all repos; the 2nd call has no more repo files left to inspect and fails

**Comment by DimStar77** [comment]
The VR was ok as it was based on a DVD install - where there is a cd:// repo added (in state disabled) - as such there was at least one *.repo file left in /etc/zypp/repos.d.

On NET install and Live media there are only online repos registered

**Comment by ggardet** [comment]
Also breaks on JeOS images.

**Comment by Vogtinator** [comment]
I suggest to revert this and just amend the previous `find .. -exec grep ...` call to also match `https://`.

**Comment by foursixnine** [comment]
@Vogtinator @DimStar77 @ggardet, @DrMullings will take care, for now a revert ought do

**Comment by DrMullings** [comment]
Followup:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10661

**Pull request merged**
