### PR TITLE
add empathy_aim regression test script

### PR DESCRIPTION
**Pull request by dehai**

### CODE REVIEW

**Comment by MalloZup** [comment]
hi Dehai, thank you for your pr ! :) you should check the style of your commit firs. 
We have a script for clean the code with the standars,  before merging like the linux-kernel community has one.

You can find this on os-autoinst.
I have also i script in bash, /usr/bin/tidyopenqa it make this: 

#!/bin/bash
#

TIDY_ARGS="-l=0 -fbl -nsfs -baao -bbao -pt=2 -bt=2 -sbt=2 -sct"

perltidy $TIDY_ARGS $1
~

**Comment by okurz** [comment]
As @MalloZup suggested, call
```
make test
```
to check your code. To fix the style call
```
tools/tidy
```

**Comment by sysrich** [comment]
Hi @dehai - are you running tools/tidy like @okurz and @MalloZup have suggested? your latest commits still looke like they're incorrectly formatted, which tools/tidy would have taken care of

**Comment by dehai** [comment]
@sysrich ,-yes , I am trying for formatting the code with the Travis-ci and  tidy script , but something goes wrong on Travis-ci website, and when I am running the Makefile on my computer . It always appear the Perl issue. and I am trying to fix it.

**Comment by dehai** [comment]
Hello, I am done with the code checking. should I raise a new pull request in github? or other things? could you tell me what should I do next ?

**Comment by okurz** [comment]
Hi @dehai please see https://github.com/os-autoinst/os-autoinst/#rules-for-commits for some help. Now the commits should be squashed into one. see "git rebase --interactive". Please describe the goal or benefit of your commit in the commit message.

**Comment by coolo** [comment]
shouldn't this be hookd into main.pm too?

**Comment by dehai** [comment]
@coolo - yes, I add the empathy_aim.pm into main.pm ,under the x11regressions. and  I raise a new PR #1146 . next time , I will  do the both things together to raise the PR. thanks!!

**Pull request merged**
