### PR TITLE
Adapt kvm mitigations on spectre_v2 for passthrough

### PR DESCRIPTION
**Pull request by museQi**
modify mitigations.pm for kvm passthrough of spectre_v2 cases on skylake machine.
http://10.67.129.4/tests/56928#

Verification run: http://10.67.129.4/tests/56989

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @zyuhu Please help me review.

**Comment by zyuhu** [comment]
LGTM

**Comment by XGWang0** [comment]
LGTM

**Comment by museQi** [comment]
hello,Alice @alice-suse,Please help me merge.Thanks.

**Pull request merged**
