### PR TITLE
Revert "Disk 'b' always the secondary disk for tests"

### PR DESCRIPTION
**Pull request by okurz**
This reverts commit ed7370942b9fa894aa9404e2c7ef07f9e5ec5325.

See https://openqa.suse.de/tests/1007823#step/btrfs_qgroups/12

### CODE REVIEW

**Comment by okurz** [comment]
@asmorodskyi @mnowaksuse

**Comment by okurz** [comment]
I kept the "snapper dbus" part intact. I assume that snuck into the original commit by mistake

**Comment by mnowaksuse** [comment]
No it did not. It's described in the commit log, why it's needed there.

**Comment by okurz** [comment]
I still don't get it. let's discuss in call first.

**Comment by okurz** [comment]
@mnowaksuse did a way better solution with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3109 thanks for that

**Pull request closed without merging**
