### PR TITLE
MicroOS 15.2 test fixes

### PR DESCRIPTION
**Pull request by lnussel**
Fixes booting and transactional_update for MicroOS on 15.2.

Removes the need for #10161 for MicroOS

- Related ticket: https://progress.opensuse.org/issues/66200
- Verification run: http://tortuga.suse.de/tests/54
  http://tortuga.suse.de/tests/55
  http://tortuga.suse.de/tests/56

### CODE REVIEW

**Comment by foursixnine** [comment]
Tidy ain't your friend :)

**Comment by lnussel** [comment]
fixed

**Comment by lnussel** [comment]
ping?

**Comment by jknphy** [comment]
hi @lnussel this change breaks sle transactional tests: https://openqa.suse.de/tests/4222630

**Comment by lnussel** [comment]
those random effects are not fun at all. Maybe try putting is_opensuse where is_leap used to be.

**Comment by lnussel** [comment]
but then why are the update-test packages not installed on SLE when in beta?

**Comment by jknphy** [comment]
> but then why are the update-test packages not installed on SLE when in beta?

I cannot tell, not expert on transaction server. I created #10250

**Pull request merged**
