### PR TITLE
Fix mau-extratests2 yaml schedule for SLE 15-SP4

### PR DESCRIPTION
**Pull request by pdostal**
Schedule **15-SP4** -specific tests from **15-SP3** in `mau-extratests2.yaml`

- Verification run: [pdostal-server.suse.cz/t2746](https://pdostal-server.suse.cz/tests/2746)

### CODE REVIEW

**Comment by rfan1** [comment]
CI check failed

**Comment by pdostal** [comment]
> CI check failed

It was just a fluke. Now it's green.

**Comment by rfan1** [comment]
LGTM, 

@pdostal Do you have a progress ticket to track this issue？

**Comment by pdostal** [comment]
> @pdostal Do you have a progress ticket to track this issue？

No.

**Review by Avinesh — APPROVED** [review]

**Comment by pdostal** [comment]
> > ```
> > * Verification run: [pdostal-server.suse.cz/t2194](https://pdostal-server.suse.cz/t2194)
> > ```
> 
> 
> @pdostal , why VR from sle-15-SP3?

By mistake. Fixed.

**Pull request merged**
