### PR TITLE
Amend ansible tests for ALP

### PR DESCRIPTION
**Pull request by grisu48**
Skip the ansible-test module on ALP since some dependencies are not available.

- Related ticket: https://progress.opensuse.org/issues/119086
- Verification run: [ALP](https://duck-norris.qam.suse.de/tests/11078#step/ansible/218) | [SLES15-SP4](https://duck-norris.qam.suse.de/t11079) | [MicroOS](https://duck-norris.qam.suse.de/t11087) | [Tumbleweed](https://duck-norris.qam.suse.de/t11081)

Note: The journalcheck issue on ALP is unrelated and happens also if [ansible is excluded](https://duck-norris.qam.suse.de/tests/11082#step/journal_check/21)

### CODE REVIEW

**Review by b10n1k — APPROVED** [review]
+1

**Comment by mloviska** [comment]
> Note: The journalcheck issue on ALP is unrelated and happens also if [ansible is excluded](https://duck-norris.qam.suse.de/tests/11082#step/journal_check/21)

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15822

**Comment by mloviska** [comment]
Hm...ansible worked [here](https://pdostal-server.suse.cz/tests/2871#step/ansible/1). Maybe we should not schedule the test for ALP staging

**Comment by grisu48** [comment]
> Hm...ansible worked [here](https://pdostal-server.suse.cz/tests/2871#step/ansible/1). Maybe we should not schedule the test for ALP staging

The part I'm disabling actually never worked but is masked by a softfailure: https://pdostal-server.suse.cz/tests/2871#step/ansible/142, so this would not hurt either at this point.

That being said, it might be a good idea to disable this for staging, yes. I would like to hear @pdostal word on this though, as the creator of the test.

**Review by pdostal — CHANGES_REQUESTED** [review]
I wrote the Ansible test mainly because of ALP.

Can you share which dependencies are missing?
I don't really consider `ansible-test` important on ALP.
But I still plan to work on the Ansible zypper module on ALP.

See [bsc#1204544](https://bugzilla.suse.com/show_bug.cgi?id=1204544).

**Comment by grisu48** [comment]
> Can you share which dependencies are missing? 

Well, exactly the one I'm removing, i.e. `python3-yamllint`, see e.g. https://openqa.opensuse.org/tests/2846163#step/ansible/29

> I don't really consider `ansible-test` important on ALP. But I still plan to work on the Ansible zypper module on ALP.

Yes indeed, this change only removes `ansible-test` from the test module on ALP, the rest of the test run is still working nicely. And we can add it later on if `python3-yamllint` ever becomes available as system package on ALP.

I don't really see how https://bugzilla.suse.com/show_bug.cgi?id=1204544 is related to this issue :thinking:

**Comment by fcrozat** [comment]
Please note I've added python3-yamllint to SUSE:ALP but it might take a few days to have it available.

**Comment by grisu48** [comment]
Closing PR as https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15846 is now merged.

**Pull request closed without merging**
