### PR TITLE
Set SYSTEM_ROLE to respect DESKTOP=textmode

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by mnowaksuse** [comment]
This may be breaking `textmode` test suite on SLE 12: https://progress.opensuse.org/issues/52550/

**Comment by ldevulder** [comment]
Why this change without a description to motivate it!? It breaks all HA tests in SLE-15+ because `SYSTEM_ROLE=default` should be the default value in SLE-15, and thus all code that test this fail...

In HA, `SYSTEM_ROLE=default` set `DESKTOP=textmode`, but it's **\*NOT\*** equivalent to `SYSTEM_ROLE=textmode`.

IMHO other (bad?) impact should be expected...

**Comment by rwx788** [comment]
@ldevulder I was surprised that this change didn't break anything... Could you please provide a link to some failed test, so we can fix it? @mimi1vx: could you please take a look?

**Comment by ldevulder** [comment]
@rwx788 for example this test: https://openqa.suse.de/tests/3012732#step/yast2_ntpclient/13

It fails because in HA we only execute `yast2_ntpclient` if `SYSTEM_ROLE` is set to default or HA during installation. In these cases NTP is already configured but not if `SYSTEM_ROLE` is set to textmode.

So we need to find a way to handle all the cases, but in fact I think that we can't assume that `SYSTEM_ROLE` should be set to textmode if `DESKTOP=textmode`.

**Comment by alvarocarvajald** [comment]
Agree with @ldevulder here.

Basically in 15+, for SLES4SAP the default system role (SLES for SAP Applications) uses gnome, while in HA the default system role (HA Node) uses textmode. For openqa both system roles while being the default, must use a different value of `DESKTOP` for the tests that follow. I figured the only "odd" case was SLES4SAP which is why @rwx788 (I think) added there the `is_sles4sap()` call initially, but judging by this PR there must be other cases. A description would've been helpful. :(

**Comment by juadk** [comment]
Automatic tests for maintenance failed since a month:
[Example of failed tests](https://openqa.suse.de/tests/overview?distri=sle&flavor=Server-DVD-HA-Incidents&version=15-SP1&groupid=236&build=%3A11706%3Alibqb)

**Comment by rwx788** [comment]
As there is no feedback from @mimi1vx, let me revert and then Ondrej can adjust his code to fix original issue he tried to address.

**Comment by rwx788** [comment]
See #7840

**Pull request merged**
