### PR TITLE
Fix license issue in SLE15 with Packages DVD

### PR DESCRIPTION
**Pull request by ldevulder**
In SLE15, license is shown after module selection when we use Packages DVD.

This PR also changed call to "sle_version_at_least('15')" by "is_sle('15+')".

Failing test: https://openqa.suse.de/tests/1502668#step/addon_products_sle/75

- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/720
- Verification run: http://moon.qa.suse.cz/tests/2089

### CODE REVIEW

**Comment by alvarocarvajald** [comment]
LGTM

**Comment by okurz** [comment]
Aren't you working around https://bugzilla.suse.com/show_bug.cgi?id=1081647 now or is it something different?

**Comment by ldevulder** [comment]
@okurz, yes it's the same issue as bsc#108647 (I have not seen it before). Yes the SLES license seems to be seen twice, but for HA it's not the case.

The main difference between SLE12 and SLE15 is that in SLE15 with Packages DVD you select Module(s) and this/these Module(s) are effectively added *after*. In SLE12, you add the Module/Extension directly from the URL/DVD, you don't have a list for the Module before.

**Comment by okurz** [comment]
Well when you are working around a bug can you use `record_soft_failure` ?

**Comment by ldevulder** [comment]
@okurz, I added the soft_failure but only for SLES, has license for HA for example is normal, not shown before.

A question comes to me: maybe I should record a soft failure for all addon but HA? I don't know exactly in which case this double license could happen (sles4sap? sled?)?

**Comment by ldevulder** [comment]
Verification run updated with the last version.

**Comment by okurz** [comment]
hm, I don't know. Could you please carefully crosscheck the scenarios in the functional job group that also handle addons or the packages DVD? At best have multiple verification runs.

**Comment by ldevulder** [comment]
@okurz, I will have a look, but testing all cases on my lab could be a little bit difficult, but I will try to avoid breaking things!

I just saw this PR also related to the licences in Packages-DVD but for all-package: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4554 but I don't understand why this all-package code doesn't use the `addon_license` function. I think somethings could be done to simplify all this code one day ;-)

**Comment by ldevulder** [comment]
@okurz, I do multiple run to test this PR, and I had no issue.

I also do a test with a basic configuration, without HA extension, to be sure that addons selection using Packages DVD still works: http://moon.qa.suse.cz/tests/2654

**Pull request merged**
