### PR TITLE
Fix for the mess that the workaround for screen_refresh created

### PR DESCRIPTION
**Pull request by rakoenig**
- forgot to "use YaST::workarounds" in registration.pm

- Related ticket: https://progress.opensuse.org/issues/117949
- Needles: 
- Verification run: currently running

### CODE REVIEW

**Comment by rakoenig** [comment]
Closed by merging https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16016

**Comment by rakoenig** [comment]
Another Fix for iscsi-client is needed.

**Review by ge0r — APPROVED** [review]

**Comment by ge0r** [comment]
@rakoenig looks good, if the conflicts are fixed we can merge it

**Comment by rakoenig** [comment]
Merge conflict resolved.

**Pull request closed without merging**
