### PR TITLE
Add optional version check to is_leap

### PR DESCRIPTION
**Pull request by kravciak**
Local runs:
 - http://dhcp91.suse.cz/tests/1833 - Leap staging
 - http://dhcp91.suse.cz/tests/1834 - Leap Build152.1

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by okurz** [comment]
This looks all very good to me. What is missing from your POV?

**Comment by kravciak** [comment]
I am finished here, please check again (I added second commit)

**Comment by okurz** [comment]
LGTM

not merging myself right now because of my limited availability

**Pull request merged**
