### PR TITLE
Ensure sle11 is self-contained

### PR DESCRIPTION
**Pull request by okurz**
This is very much desired to know which version was tested of all the test
plan and the modules. Also, it means for old SLE11 we do not need to care
about support in the modules anymore and can delete modules that are not used
within the master branch which would otherwise be way harder to check for.

### CODE REVIEW

**Comment by coolo** [comment]
I support the reason, but not the action. I think we should rename sle11 branch to whatever, branch master to sle11 and the commit back the main.pm from the old sle11 branch and do cleanups there and in sle12. Not copy from branch to branch, git will not be able to git blame.

**Comment by okurz** [comment]
> rename sle11 branch to whatever

copied `sle11` to `sle11_only_testplan`

> branch master to sle11 and the commit back the main.pm from the old sle11 branch

DONE, see commit content. It looks super weird now as it compares against the original sle11 branch. I did not want to delete the `sle11` branch now without additional confirmation so please ignore the displayed conflicts, delete sle11 branch, merge my changes to create a new sle11 branch and update repo on osd afterwards if you agree with the change.

**Comment by coolo** [comment]
didn't work this way. Once sle11 was gone, the PR couldn't be reopened. So I created a copy of master to sle11 for you to update, but that didn't work. So you have to rebase or whatever

**Comment by okurz** [comment]
done.

**Comment by okurz** [comment]
checks fail now because tidy wants to change sle11 main.pm and also is detecting duplicate code in there. I would recommend to not change the code in this PR and force-accept as is so that we don't mangle the sle11 branch. Afterwards we might still try some cleanup.

**Comment by coolo** [comment]
ok, in the end I think we still want this in products/sle - otherwise it's just too confusing. But we can that once we care for sle11 again. For now feel free to remove sle11 from master

**Pull request merged**
