### PR TITLE
Add hostname setup when creating image

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by sysrich** [comment]
I don't see anything wrong with this...but I have one question

Why?

**Comment by dzedro** [comment]
to avoid something like this http://10.100.98.90/tests/866/modules/iscsi_server/steps/9

**Comment by dzedro** [comment]
when we will test something with pre-installed image, xterm will fail because we expect to have hostname set to susetest e.g. this https://openqa.suse.de/tests/292770/modules/sshxterm/steps/4 would fail with pre-installed image

**Comment by sysrich** [comment]
:+1:

**Pull request merged**
