### PR TITLE
Use correct image name in containers/utils

### PR DESCRIPTION
**Pull request by b10n1k**
- Related ticket: https://progress.opensuse.org/issues/80642
- Verification run: http://aquarius.suse.cz/tests/4126
[osd](https://openqa.suse.de/tests/overview?distri=sle&build=b10n1k%2Fos-autoinst-distri-opensuse%2311530&version=15-SP2) scheduled

### CODE REVIEW

**Comment by jlausuch** [comment]
The reason why https://openqa.suse.de/tests/5107415#step/docker/83 fails is because the job is missing the new variable REGISTRY

**Review by jlausuch — CHANGES_REQUESTED** [review]
I have added the variable to the test, let's wait for the next iteration and will decide upon on that.

**Comment by jlausuch** [comment]
shall we close this one?

**Comment by Vogtinator** [comment]
IMO this is a valid bug - runs without `REGISTRY` set fail for a valid reason:

```
> docker pull docker.io/library/hello-world
Using default tag: latest
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete 
Digest: sha256:e7c70bb24b462baa86c102610182e3efcb12a04854e8c582838d92970a09f323
Status: Downloaded newer image for hello-world:latest
> docker image ls docker.io/library/hello-world
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> docker image ls hello-world
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              bf756fb1ae65        11 months ago       13.3kB
```

So it seems like the fallback values need some massaging for docker.

**Comment by jlausuch** [comment]
> IMO this is a valid bug - runs without `REGISTRY` set fail for a valid reason:
> 
> ```
> > docker pull docker.io/library/hello-world
> Using default tag: latest
> latest: Pulling from library/hello-world
> 0e03bdcc26d7: Pull complete 
> Digest: sha256:e7c70bb24b462baa86c102610182e3efcb12a04854e8c582838d92970a09f323
> Status: Downloaded newer image for hello-world:latest
> > docker image ls docker.io/library/hello-world
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> > docker image ls hello-world
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> hello-world         latest              bf756fb1ae65        11 months ago       13.3kB
> ```
> 
> So it seems like the fallback values need some massaging for docker.

ok, but the solution proposed in this PR is not the right approach to fix that.

**Comment by Vogtinator** [comment]
> > IMO this is a valid bug - runs without `REGISTRY` set fail for a valid reason:
> > ```
> > > docker pull docker.io/library/hello-world
> > Using default tag: latest
> > latest: Pulling from library/hello-world
> > 0e03bdcc26d7: Pull complete 
> > Digest: sha256:e7c70bb24b462baa86c102610182e3efcb12a04854e8c582838d92970a09f323
> > Status: Downloaded newer image for hello-world:latest
> > > docker image ls docker.io/library/hello-world
> > REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> > > docker image ls hello-world
> > REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> > hello-world         latest              bf756fb1ae65        11 months ago       13.3kB
> > ```
> > 
> > 
> > So it seems like the fallback values need some massaging for docker.
> 
> ok, but the solution proposed in this PR is not the right approach to fix that.

Yep, it would break when `REGISTRY` is set.

**Comment by b10n1k** [comment]
resolved. no needed after all

**Pull request closed without merging**
