### PR TITLE
console/clamav: Uninstall clamav during cleanup

### PR DESCRIPTION
**Pull request by Vogtinator**
While it stops the service at the end, it's started again after the reboot.
At that point however the environment is no longer prepared, which causes
issues like slowdowns and the system running out of memory.

So just uninstall the package at the end.

This fixes the cascade of errors in the `jeos-extra` test: https://openqa.opensuse.org/tests/2010513#step/rails/31

- Verification run: http://fussheizung/tests/1109#step/clamav/143

### CODE REVIEW

**Review by DimStar77 — APPROVED** [review]
Sometimes the solution can be that easy

**Comment by Vogtinator** [comment]
Thanks to the stuck CI job I noticed that an 's' was missing in the subject - fixed.

**Review by dzedro — APPROVED** [review]

**Comment by Vogtinator** [comment]
> Clamav daemon is enabled after installation ? Because test is just start/stopping the daemon

I was suspicious of this as well, and I think it's actually not. openQA is just showing the wrong log entries here.

The OOM probably happens during the clamav module, but it's only on the next `export_logs` call that openQA notices.

I remember that this was already reported somewhere, maybe even for clamav as well.

**Comment by DimStar77** [comment]
> The OOM probably happens during the clamav module, but it's only on the next `export_logs` call that openQA notices.
> 
> I remember that this was already reported somewhere, maybe even for clamav as well.

https://progress.opensuse.org/issues/81382 ?

**Comment by dzedro** [comment]
true
```
Nov 03 08:05:14.800421 localhost systemd[1]: freshclam.service: Deactivated successfully.
Nov 03 08:05:14.800638 localhost systemd[1]: Finished Clam AntiVirus database updater.
Nov 03 08:06:47.252691 localhost kernel: systemd-journal invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=-250
Nov 03 08:06:47.303201 localhost kernel: CPU: 0 PID: 396 Comm: systemd-journal Not tainted 5.14.14-1-default #1 openSUSE Tumbleweed eb80aab517ad5c2c72fc7811cce14acf272d56c0
Nov 03 08:06:47.303424 localhost kernel: Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.12.0-59-gc9ba527-rebuilt.opensuse.org 04/01/2014
Nov 03 08:06:47.303554 localhost kernel: Call Trace:
Nov 03 08:06:47.303617 localhost kernel:  dump_stack_lvl+0x46/0x5a
Nov 03 08:06:47.303686 localhost kernel:  dump_header+0x4a/0x1f3
Nov 03 08:06:47.303756 localhost kernel:  oom_kill_process.cold+0xb/0x10
Nov 03 08:06:47.303822 localhost kernel:  out_of_memory+0x1b9/0x4c0
Nov 03 08:06:47.303877 localhost kernel:  __alloc_pages_slowpath.constprop.0+0xbcc/0xcb0
Nov 03 08:06:47.303932 localhost kernel:  __alloc_pages+0x1e5/0x210
Nov 03 08:06:47.303990 localhost kernel:  pagecache_get_page+0x14c/0x4f0
Nov 03 08:06:47.304038 localhost kernel:  filemap_fault+0x5c6/0x880
Nov 03 08:06:47.304092 localhost kernel:  ? filemap_map_pages+0x137/0x680
Nov 03 08:06:47.304150 localhost kernel:  __do_fault+0x36/0xd0
Nov 03 08:06:47.304206 localhost kernel:  __handle_mm_fault+0xee8/0x1520
Nov 03 08:06:47.304267 localhost kernel:  handle_mm_fault+0xcf/0x2a0
Nov 03 08:06:47.304323 localhost kernel:  do_user_addr_fault+0x1c1/0x680
Nov 03 08:06:47.304373 localhost kernel:  ? syscall_exit_to_user_mode+0x18/0x40
Nov 03 08:06:47.304431 localhost kernel:  exc_page_fault+0x68/0x130
Nov 03 08:06:47.304477 localhost kernel:  ? asm_exc_page_fault+0x8/0x30
Nov 03 08:06:47.304518 localhost kernel:  asm_exc_page_fault+0x1e/0x30
Nov 03 08:06:47.304565 localhost kernel: RIP: 0033:0x7f82daf7d190
Nov 03 08:06:47.304615 localhost kernel: Code: Unable to access opcode bytes at RIP 0x7f82daf7d166.
Nov 03 08:06:47.304673 localhost kernel: RSP: 002b:00007ffd12f0ce58 EFLAGS: 00010203
Nov 03 08:06:47.304747 localhost kernel: RAX: 0000000000000001 RBX: 000056221412e580 RCX: 00007f82db004c1e
Nov 03 08:06:47.304808 localhost kernel: RDX: 000000000000003f RSI: 000056221413e210 RDI: 0000000000000000
Nov 03 08:06:47.304868 localhost kernel: RBP: 000000000000018c R08: 0000000000000000 R09: 0000562214142870
Nov 03 08:06:47.304904 localhost kernel: R10: 00000000ffffffff R11: 0000000000000293 R12: 0000000000000118
Nov 03 08:06:47.304971 localhost kernel: R13: 000000000000003f R14: 000000000000001c R15: 000056221412e710
Nov 03 08:06:47.305025 localhost kernel: Mem-Info:
Nov 03 08:06:47.305085 localhost kernel: active_anon:234801 inactive_anon:233686 isolated_anon:0
                                          active_file:147 inactive_file:512 isolated_file:0
                                          unevictable:788 dirty:0 writeback:0
                                          slab_reclaimable:4853 slab_unreclaimable:7367
                                          mapped:4 shmem:2490 pagetables:1560 bounce:0
                                          free:13183 free_pcp:497 free_cma:0
Nov 03 08:06:47.305132 localhost kernel: Node 0 active_anon:939204kB inactive_anon:934744kB active_file:588kB inactive_file:2048kB unevictable:3152kB isolated(anon):0kB isolated(file):0kB mapped:16kB dirty:0kB writeback:0kB shmem:9960kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB kernel_stack:1744kB pagetables:6240kB all_unreclaimable? yes
Nov 03 08:06:47.305184 localhost kernel: Node 0 DMA free:8068kB min:344kB low:428kB high:512kB reserved_highatomic:0KB active_anon:6320kB inactive_anon:688kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15360kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Nov 03 08:06:47.305233 localhost kernel: lowmem_reserve[]: 0 1931 1931 1931 1931
Nov 03 08:06:47.305274 localhost kernel: Node 0 DMA32 free:44664kB min:44708kB low:55884kB high:67060kB reserved_highatomic:0KB active_anon:932884kB inactive_anon:934056kB active_file:588kB inactive_file:2048kB unevictable:3152kB writepending:0kB present:2080624kB managed:2000912kB mlocked:80kB bounce:0kB free_pcp:1988kB local_pcp:1988kB free_cma:0kB
Nov 03 08:06:47.305335 localhost kernel: lowmem_reserve[]: 0 0 0 0 0
Nov 03 08:06:47.305412 localhost kernel: Node 0 DMA: 3*4kB (U) 5*8kB (UE) 5*16kB (UE) 4*32kB (UME) 2*64kB (UE) 4*128kB (UME) 2*256kB (UE) 1*512kB (E) 2*1024kB (ME) 2*2048kB (UM) 0*4096kB = 8068kB
Nov 03 08:06:47.305465 localhost kernel: Node 0 DMA32: 1430*4kB (UME) 958*8kB (UE) 621*16kB (UME) 359*32kB (UME) 94*64kB (UME) 22*128kB (U) 0*256kB 0*512kB 1*1024kB (M) 0*2048kB 0*4096kB = 44664kB
Nov 03 08:06:47.305514 localhost kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Nov 03 08:06:47.305603 localhost kernel: 3402 total pagecache pages
Nov 03 08:06:47.305659 localhost kernel: 236 pages in swap cache
Nov 03 08:06:47.305737 localhost kernel: Swap cache stats: add 196571, delete 196335, find 5830/35935
Nov 03 08:06:47.305789 localhost kernel: Free swap  = 0kB
Nov 03 08:06:47.305840 localhost kernel: Total swap = 524284kB
Nov 03 08:06:47.305885 localhost kernel: 524154 pages RAM
Nov 03 08:06:47.305951 localhost kernel: 0 pages HighMem/MovableOnly
Nov 03 08:06:47.305987 localhost kernel: 20086 pages reserved
Nov 03 08:06:47.306021 localhost kernel: 0 pages cma reserved
Nov 03 08:06:47.306062 localhost kernel: 0 pages hwpoisoned
Nov 03 08:06:47.306111 localhost kernel: Tasks state (memory values in pages):
Nov 03 08:06:47.306137 localhost kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Nov 03 08:06:47.306185 localhost kernel: [    396]     0   396    16178      114   114688      222          -250 systemd-journal
Nov 03 08:06:47.306237 localhost kernel: [    432]     0   432     6786        9    73728      327         -1000 systemd-udevd
Nov 03 08:06:47.306278 localhost kernel: [    508]   481   508     2197      174    61440      109          -900 dbus-daemon
Nov 03 08:06:47.306332 localhost kernel: [    516]     0   516     3902       80    69632      185             0 systemd-logind
Nov 03 08:06:47.306387 localhost kernel: [    614]     0   614     2425        2    57344      293             0 wickedd-auto4
Nov 03 08:06:47.306431 localhost kernel: [    615]     0   615     2426        6    53248      295             0 wickedd-dhcp4
Nov 03 08:06:47.306484 localhost kernel: [    616]     0   616     2426        0    53248      296             0 wickedd-dhcp6
Nov 03 08:06:47.306538 localhost kernel: [    627]     0   627      655        0    49152       24             0 bpfilter_umh
Nov 03 08:06:47.306580 localhost kernel: [    632]     0   632     2479        5    57344      357             0 wickedd
Nov 03 08:06:47.306628 localhost kernel: [    661]     0   661     2464        9    61440      306             0 wickedd-nanny
Nov 03 08:06:47.306681 localhost kernel: [   1232]     0  1232     2109       61    49152      104             0 login
Nov 03 08:06:47.306740 localhost kernel: [   1234]   478  1234    21059       42    65536      119             0 chronyd
Nov 03 08:06:47.306782 localhost kernel: [   1326]     0  1326      770        1    40960       30             0 agetty
Nov 03 08:06:47.306851 localhost kernel: [   1327]     0  1327     1412        4    53248       31             0 agetty
Nov 03 08:06:47.306893 localhost kernel: [   1331]     0  1331     1353        0    49152      169             0 login
Nov 03 08:06:47.306940 localhost kernel: [   1333]     0  1333     4341      146    69632      270             0 systemd
Nov 03 08:06:47.307027 localhost kernel: [   1334]     0  1334     4877       36    73728      736             0 (sd-pam)
Nov 03 08:06:47.323125 localhost kernel: [   1341]     0  1341     2026        5    49152      304             0 bash
Nov 03 08:06:47.323331 localhost kernel: [   1471]     0  1471     1353       80    45056       80             0 login
Nov 03 08:06:47.323393 localhost kernel: [   1928]     0  1928     1417      122    49152      217             0 bash
Nov 03 08:06:47.323452 localhost kernel: [   2840]  1000  2840     4341       92    69632      328             0 systemd
Nov 03 08:06:47.323504 localhost kernel: [   2841]  1000  2841    42011      306    90112     1306             0 (sd-pam)
Nov 03 08:06:47.323548 localhost kernel: [   2848]  1000  2848     2026      120    57344      188             0 bash
Nov 03 08:06:47.323694 localhost kernel: [   7186]   476  7186   647118        0   196608     1623             0 polkitd
Nov 03 08:06:47.323765 localhost kernel: [  24406]     0 24406     3326        0    65536      232         -1000 sshd
Nov 03 08:06:47.323835 localhost kernel: [  27939]     0 27939   332171   205900  2510848    92723             0 clamd
Nov 03 08:06:47.323901 localhost kernel: [  27963]     0 27963   299613   258719  2387968    25144             0 clamscan
Nov 03 08:06:47.323951 localhost kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice,task=clamd,pid=27939,uid=0
Nov 03 08:06:47.323998 localhost kernel: Out of memory: Killed process 27939 (clamd) total-vm:1328684kB, anon-rss:823596kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:2452kB oom_score_adj:0
Nov 03 08:06:47.379131 localhost kernel: oom_reaper: reaped process 27939 (clamd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by DimStar77** [comment]
> > The OOM probably happens during the clamav module, but it's only on the next `export_logs` call that openQA notices.
> > I remember that this was already reported somewhere, maybe even for clamav as well.
> 
> https://progress.opensuse.org/issues/81382 ?

Looking at that debug log I reported in that - we might 'just' set the test that vacuums the journal as milestone (so subsequent reverts go back to this step)

**Comment by Vogtinator** [comment]
According to the OOM log, both clamd and clamscan take 1GiB each - that looks like just one of those processes should be enough... The VM has 1.5GiB of RAM + the added 512MiB of Swap that's not enough.

I'll keep the `zypper rm -u clamd` and add a call to `show_oom_info` to fail the test if OOM happens, that way it's found at the right spot, before it cascades. Opinions?

**Comment by Vogtinator** [comment]
> Sometimes the solution can be that easy

Unfortunately this became yet another rabbit hole.

`show_oom_info` itself doesn't fail the test, it only checks for OOM to show a red box as marker. As a side effect of grepping for the OOM message, it ends up in the serial file (`serial_terminal.txt` for the serial terminal and `serial0.txt` for others). What actually fails the test is that `basetest::search_for_expected_serial_failures`, which runs after each module, looks through `serial0.txt` for the message and finds the one written by `show_oom_info`...

For some reason `basetest::search_for_expected_serial_failures` after the `clamav` module does not catch the OOM message in `serial0.txt`, no idea why yet.

**Comment by Vogtinator** [comment]
> For some reason basetest::search_for_expected_serial_failures after the clamav module does not catch the OOM message in serial0.txt, no idea why yet.

Because when `SCHEDULE` is set, `main.pm` runs too late and the `serial_failures` array is empty. That means using `SCHEDULE` has different results than using `main.pm`, great...

**Comment by Vogtinator** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1842 fixes that messages printed during the `post_fail_hook` cause the next module to fail.

In the initially linked test run, the OOM message appears after the `clamav` module finished, in the `rails` module. I suspect there's still a `clam*` process running, despite the `systemctl stop`. This can only happen if the `journalctl` module fails, because otherwise there's a reboot which stops the process.

**Comment by Vogtinator** [comment]
> In the initially linked test run, the OOM message appears after the `clamav` module finished, in the `rails` module, so there's no reason to fail it and do a rollback. I suspect there's still a `clam*` process running, despite the `systemctl stop`. This can only happen if the `journalctl` module fails, because otherwise there's a reboot which stops the process.

Nope, I was too quick on that. The reason the OOM message is not visible in the `clamav` module is (most likely) just the default log level of JeOS being too low (`quiet`) and thus it's not sent to the console, but just saved in dmesg.

The `rails` test fails naturally, and its `post_fail_hook` triggers the OOM message from dmesg to be sent to the serial console, which starts the cascade.

So the proper fix is actually simple: Increase the log level!

**Pull request closed without merging**
