### PR TITLE
openvswitch_ssl: add back SLES 12 support

### PR DESCRIPTION
**Pull request by paolostivanin**
- Related ticket: https://progress.opensuse.org/issues/118630
- Verification runs:
  - 15-SP4: https://openqa.suse.de/tests/9721612
  - 15-SP3: https://openqa.suse.de/tests/9721644
  - 15-SP2: https://openqa.suse.de/tests/9721645
  - 15-SP1: https://openqa.suse.de/tests/9721669
  - 12-SP5: https://openqa.suse.de/tests/9721613
  - 12-SP4: https://openqa.suse.de/tests/9721668
  - 12-SP3: https://openqa.suse.de/tests/9721667
  - Tumbleweed: https://openqa.opensuse.org/tests/2798668
  - Leap: https://openqa.opensuse.org/tests/2798708

### CODE REVIEW

**Review by rfan1 — APPROVED** [review]
LGTM

**Comment by punkioudi** [comment]
Could you please add all the VRs in all versions that this module runs? :)

**Comment by paolostivanin** [comment]
I can't call `mau-extratests2`, otherwise it will conflict with the one in maint repo. Therefore I added the `dev` :)

**Comment by punkioudi** [comment]
> I can't call `mau-extratests2`, otherwise it will conflict with the one in maint repo. Therefore I added the `dev` :)

Yes you can run the following command: `openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15702 https://openqa.suse.de/tests/9720294 _SKIP_POST_FAIL_HOOKS=1` :)

**Comment by paolostivanin** [comment]
ah, good to know! Thanks Anna :+1:

**Comment by punkioudi** [comment]
btw + TW and Leap just in case :) https://openqa.opensuse.org/tests/2797779#step/openvswitch_ssl/46, https://openqa.opensuse.org/tests/2797796#step/openvswitch_ssl/46

**Comment by paolostivanin** [comment]
@punkioudi done!

**Review by punkioudi — APPROVED** [review]
Super!

**Review by jouyingbin — COMMENTED** [review]
AWESOME, LGTM.

**Pull request merged**
