### PR TITLE
Clear root console after adding users

### PR DESCRIPTION
**Pull request by lnussel**
select_console 'root-console' later looks for a lonely prompt on an
empty screen.

### CODE REVIEW

**Comment by okurz** [comment]
Please provide a link or screenshot to a local verification run.

**Comment by sysrich** [comment]
@okurz we can probably trust @lnussel ..at least laugh really really really loudly at him in the next stand-up call if merging this breaks everything...

**Comment by okurz** [comment]
Sorry, I am QA: "Trust Nobody, Not Even Yourself!" :-)

**Comment by coolo** [comment]
actually that select_console 'root-console' looks at any prompt is okurz's doing. It's not supposed to this. It's just his ugly workaround

**Comment by coolo** [comment]
and as his workaround got a yellow card and we agreed that we revert when the next problem appears with that, now would be a good time to do so. The change of @lnussel can't hurt though

**Comment by lnussel** [comment]
https://openqa.tanana.suse.de/tests/1698

**Pull request merged**
