### PR TITLE
Use correct naming syntax for iscsi iqn

### PR DESCRIPTION
**Pull request by asdil12**
Requires: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/834
Verification run: http://artemis.suse.de/tests/259

The verification run will still fail at a later state due to [bsc#1091626](https://bugzilla.suse.com/show_bug.cgi?id=1091626).

### CODE REVIEW

**Comment by okurz** [comment]
SLE needles merged

Please add a verification run for SLE12SP4

**Comment by ldevulder** [comment]
Good point! Support Server also configure a iSCSI server (partial copy/paste from the test you changed), could you also change the naming for it (file `tests/sle/tests/support_server/setup.pm`)?

**Comment by ldevulder** [comment]
@asdil12, indeed they are the same file... I think I need to open my eyes or take another coffee, or maybe both :D
Sorry :-)

**Comment by asdil12** [comment]
@okurz 
SLE12SP4 works:
http://artemis.suse.de/tests/263#
Needles for SLE12SP4: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/835

**Pull request merged**
