### PR TITLE
Select the right folder since an additional BOOT/ folder is now present

### PR DESCRIPTION
**Pull request by ggardet**
in addition to opensuse/ or sles/ folder

- Related ticket: https://progress.opensuse.org/issues/67204
- Needles: 
  - openSUSE: https://github.com/os-autoinst/os-autoinst-needles-opensuse/commit/252afff64fe36e2c9dd937eb55224fa116981081
  - SLE: https://openqa.suse.de/tests/4289112
- Verification run: 
  - Leap 15.2 aarch64: https://openqa.opensuse.org/t1278954
  - Leap Tumbleweed aarch64: https://openqa.opensuse.org/t1278955

### CODE REVIEW

**Comment by ggardet** [comment]
Who could handle SLE needles?

**Comment by ggardet** [comment]
> LGTM, but we need needles for sles. Is there anyone helping you with that already? If not I can help.

No, nobody took care of SLE needles yet.

**Comment by rwx788** [comment]
> > LGTM, but we need needles for sles. Is there anyone helping you with that already? If not I can help.
> 
> No, nobody took care of SLE needles yet.

Alright. In case it's urgent, I would propose to add `is_opensuse` clause for the change. But I will take a look today what we need for SLE. Cheers!

**Comment by rwx788** [comment]
https://openqa.suse.de/tests/overview?build=ggardet%2Fos-autoinst-distri-opensuse%2310377&version=15-SP2&distri=sle
So I've triggered 2 jobs to create needles, but I can see that for one of the scenarios I have found, there is no `sles` directory:
image
There is no video, so hard to say if there is no directory or there is no screenshot in openQA.

**Comment by rwx788** [comment]
Alright, runs for SLES worked fine with new needle. So we can merge.

**Pull request merged**
