### PR TITLE
Wicked: add sleep after hotplug-in a device

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/58538
- Verification run: http://fromm.arch.suse.de/tests/161

### CODE REVIEW

**Comment by jlausuch** [comment]
@dzedro can you please test this change in QAM job? I can't reproduce the failure in my local instance.

**Comment by asmorodskyi** [comment]
LGTM but I wouldn't merge it without QAM test run so we actually see that this sleep doing something

**Comment by jlausuch** [comment]
> 
> Tried but mine mm is broken.

you can trigger it directly in openqa 
https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#triggering-tests-based-on-an-any-remote-git-refspec-or-open-github-pull-request

**Comment by dzedro** [comment]
> > Tried but mine mm is broken.
> 
> you can trigger it directly in openqa
> https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#triggering-tests-based-on-an-any-remote-git-refspec-or-open-github-pull-request

Multimachine ? since when ?

**Comment by asmorodskyi** [comment]
> > > Tried but mine mm is broken.
> > 
> > 
> > you can trigger it directly in openqa
> > https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#triggering-tests-based-on-an-any-remote-git-refspec-or-open-github-pull-request
> 
> Multimachine ? since when ?

hard to tell since when but I can ensure you that yes you can clone MM jobs in osd and they will properly work . In case of wicked just make sure that you cloning SUT job

**Comment by coolo** [comment]
make sure you clone the job that has the PARALLEL_WITH setting, so that clone-job knows

**Comment by dzedro** [comment]
> > > > Tried but mine mm is broken.
> > > 
> > > 
> > > you can trigger it directly in openqa
> > > https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#triggering-tests-based-on-an-any-remote-git-refspec-or-open-github-pull-request
> > 
> > 
> > Multimachine ? since when ?
> 
> hard to tell since when but I can ensure you that yes you can clone MM jobs in osd and they will properly work . In case of wicked just make sure that you cloning SUT job

Please show me, because it doesn't work for me.
```
# openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8766 https://openqa.suse.de/tests/3517471
Cloning dependencies of sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_sut@64bit
Created job #3518308: sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_ref@64bit -> https://openqa.suse.de/t3518308
Created job #3518309: sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_sut@64bit -> https://openqa.suse.de/t3518309
```

**Comment by rwx788** [comment]
> > > > > Tried but mine mm is broken.
> > > > 
> > > > 
> > > > you can trigger it directly in openqa
> > > > https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#triggering-tests-based-on-an-any-remote-git-refspec-or-open-github-pull-request
> > > 
> > > 
> > > Multimachine ? since when ?
> > 
> > 
> > hard to tell since when but I can ensure you that yes you can clone MM jobs in osd and they will properly work . In case of wicked just make sure that you cloning SUT job
> 
> Please show me, because it doesn't work for me.
> 
> ```
> # openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8766 https://openqa.suse.de/tests/3517471
> Cloning dependencies of sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_sut@64bit
> Created job #3518308: sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_ref@64bit -> https://openqa.suse.de/t3518308
> Created job #3518309: sle-15-Server-DVD-Updates-x86_64-Build20191024-1-qam_wicked_advanced_sut@64bit -> https://openqa.suse.de/t3518309
> ```

I can state only thing I faced myself, that PR changes are applied only to the cloned job and other parallel jobs use master branch of the upstream repo.

**Comment by jlausuch** [comment]
> 
> I can state only thing I faced myself, that PR changes are applied only to the cloned job and other parallel jobs use master branch of the upstream repo.

In this case it's fine, as we are cloning the job which contains the change.

**Comment by coolo** [comment]
Ah, right - you need some more tricks.

This is what I did last time:
```
coolo@openqa:~> dry_run=echo openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8653 https://openqa.suse.de/tests/3468890openqa-clone-job --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles
```

-> editing the output to include --parental-inheritance 

```
openqa-clone-job --parental-inheritance --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles

**Comment by dzedro** [comment]
> Ah, right - you need some more tricks.
> 
> This is what I did last time:
> 
> ```
> coolo@openqa:~> dry_run=echo openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8653 https://openqa.suse.de/tests/3468890openqa-clone-job --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles
> ```
> 
> -> editing the output to include --parental-inheritance
> 
> ```
> openqa-clone-job --parental-inheritance --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles
> ```

secret tricks as always :laughing:

**Comment by jlausuch** [comment]
> Ah, right - you need some more tricks.
> 
> This is what I did last time:
> 
> ```
> coolo@openqa:~> dry_run=echo openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8653 https://openqa.suse.de/tests/3468890openqa-clone-job --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles
> ```
> 
> -> editing the output to include --parental-inheritance
> 
> ```
> openqa-clone-job --parental-inheritance --skip-chained-deps --within-instance https://openqa.suse.de 3468890 _GROUP=0 TEST=qam-wicked_basic_sut@asmorodskyi/os-autoinst-distri-opensuse#fix_for_fix BUILD=asmorodskyi/os-autoinst-distri-opensuse#8653 CASEDIR=https://github.com/asmorodskyi/os-autoinst-distri-opensuse.git#fix_for_fix PRODUCTDIR=os-autoinst-distri-opensuse/products/sle NEEDLES_DIR=/var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle/needles
> ```

When I try this I end up in having same test in both jobs (sut, sut):
https://openqa.suse.de/tests/3526018#dependencies

**Comment by jlausuch** [comment]
I managed to have a VR cloning failed job in qam: https://openqa.suse.de/tests/3529238

Let me know if that's sufficient or you would like to test it yourself.

**Pull request merged**
