### PR TITLE
Add new test cases to cover firefox print

### PR DESCRIPTION
**Pull request by GraceWang571**
Add new test cases to cover the below test points:

1. Test if a page with portrait and landscape settings prints properly
2. Test if a page with aligned text print as seen on screen
3. Test whether a page with various formats prints properly
4. Test whether a page with frames prints properly
5. Test if a page with indentation prints as seen on screen
6. Test if lists print correctly
7. Test if PDF file prints correctly
8. Test if print ranges works properly
9. Test if print Preview works properly
10. Print a test page and check if it prints properly

- Related ticket: https://progress.opensuse.org/issues/120324
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1631
- Verification run: http://10.163.42.54/tests/105

### CODE REVIEW

**Comment by zhaocongjia** [comment]
[data/x11/firefox/test.pdf](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15899/files#diff-7029921d1366d7b137f71fbe9701f37381c21c21678ede6b860ec0ab4825a59b) is a symbolic link, not a real file.

**Comment by zhaocongjia** [comment]
In the summary section, it should be "Copy file" first, then "Launch firefox".

**Comment by GraceWang571** [comment]
> [data/x11/firefox/test.pdf](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15899/files#diff-7029921d1366d7b137f71fbe9701f37381c21c21678ede6b860ec0ab4825a59b) is a symbolic link, not a real file.

Yes, this is by design not a typo. I want to use the test.pdf file (in the directory /data/x11/firefox) which already exists in [data/x11/test.pdf], so I created a symbolic link in order not to duplicate the file.

**Comment by GraceWang571** [comment]
> In the summary section, it should be "Copy file" first, then "Launch firefox".

Codes have been updated to reflect this.
Besides, the copyright part and the wget part have also been udpated accordingly as discussed in slack.

Latest VR http://10.163.42.54/tests/105

**Comment by zhaocongjia** [comment]
LGTM now.

**Pull request merged**
