### PR TITLE
Add additional php checks

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/49115
Verification: http://artemis.suse.de/tests/2246

### CODE REVIEW

**Comment by DimStar77** [comment]
Breaks the jeos case - https://openqa.opensuse.org/tests/1133752

**Comment by Zaoliang** [comment]
yast2_bootloader failed and this has to do with php checks??

It failed already before the merge, see https://bugzilla.opensuse.org/show_bug.cgi?id=1140040

**Comment by DimStar77** [comment]
Meh, sorry, I linked the 'previous' run of the test.. current fails like this

https://openqa.opensuse.org/tests/1136325#step/php7/40

**Comment by asdil12** [comment]
I will fix it in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9259

**Pull request merged**
