### PR TITLE
Test opensuse docker images

### PR DESCRIPTION
**Pull request by binary-sequence**
Improve docker test with openSUSE images.

- Verification run: http://copland.arch.suse.de/tests/912

### CODE REVIEW

**Comment by binary-sequence** [comment]
A local verification run passed.

**Comment by asmorodskyi** [comment]
@binary-sequence I trust you enough , but still why not provide a URL ?

**Comment by asmorodskyi** [comment]
LGTM , resolve conflict and can be merged

**Comment by SergioAtSUSE** [comment]
@asmorodskyi, do you mean, why do I not provide a link for a verification run?
Because that was done during my leisure time. I don't have any public openQA instance yet.

(No, I don't see as an option the use of company resources on my free time, like copland)

Fixing conflict

**Comment by SergioAtSUSE** [comment]
Verification run: http://copland.arch.suse.de/tests/912

**Comment by kravciak** [comment]
Please fix https://openqa.suse.de/tests/1510594#step/docker/22 - I guess 30s time to download tumbleweed image is not enough

**Comment by SergioAtSUSE** [comment]
@kravciak, actually, the default is 90 seconds. Bu the video shows that it was not enough. Fixing.

**Comment by kravciak** [comment]
Right, I confused it with needles - thanks :)

**Comment by SergioAtSUSE** [comment]
@kravciak, https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4524

**Pull request merged**
