### PR TITLE
Fix license agreement failure during upgrade

### PR DESCRIPTION
**Pull request by QingmingSu**
No license agreements are shown in SLE 15 at the moment,
that's why workaround of bsc#1057223 is applied.
But during the upgrade from SLE 12-SP3 to SLE 15, the
system on hdd image is actually still SLE 12-SP3 at
the patch_before_migration step. Then workaround is not
appropriate and license should be accepted.
- See poo#29685

- Related ticket: https://progress.opensuse.org/issues/29685
- Needles: N/A
- Verification run: http://openqa-apac1.suse.de/tests/283

### CODE REVIEW

**Comment by nicksinger** [comment]
LGTM

**Comment by coolo** [comment]
you should consider switching VERSION as part of the tests - just as we did with @alice-suse

**Comment by QingmingSu** [comment]
@coolo : I talked with alice and reviewed related codes, but I'm not sure whether it is really working
as expected, because I find cleanup_needles action happens before set_var('TARGET_DEVELOPING_VERSION', get_var('VERSION'));

Refer to: https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/products/sle/main.pm

line 363: $needle::cleanuphandler = \&cleanup_needles;

line 1305: set_var('TARGET_DEVELOPING_VERSION', get_var('VERSION'));

Does the cleanup_needles action happens too early?

**Comment by QingmingSu** [comment]
@coolo In current offline migration testing, we just boot the original system (from hdd) to patch it, not install system-to-be-upgraded from scratch, then it actually doesn't require needles for installation of original system.

Yes, switching VERSION will also work in offline migration testing, but seems not the easiest way at the moment. Currently we are using the HDDVERSION to mark the system state during migration, maybe related codes need to be updated to adapt switching VERSION

**Comment by coolo** [comment]
yeah, but this way you always have to remember (just as in this code) what VERSION to look at. If you need needles or not doesn't matter - if you set_var('VERSION', get_var('THEREALONE')) in the test actually booting into it (and *not* in main.pm) - while previously have VERSION=$HDDVERSION you can have one function to rule them all.

And for virtualization the key test is tests/virt_autotest/switch_version_and_reload_needle.pm

**Comment by QingmingSu** [comment]
I am trying to use version switching, but it doesn't work when I want to switch the VERSION back to 15, for example, the scc_registration test module shouldn't be loaded in media based upgrade, see line 575 of https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/products/sle/main.pm

But it is actually loaded by main.pm, for example:
http://openqa-apac1.suse.de/tests/284#step/scc_registration/5

Any idea to fix the above issue?

**Comment by alice-suse** [comment]
It is kind of tricky here.
For the code that will be executed when processing main,pm, like the if else branches that decides which pm to load according to VERSION, use set_var('VERSION',XXX) to ensure correct VERSION. For the test pms which will be processed after main.pm is finished processing, ensure to insert corresponding " loadtest swtich_version_and_reload_needle", which switch to correct version during the loaded tests(xxx.pm) running.

**Comment by QingmingSu** [comment]
@alice-suse Thanks for figuring out the issue. I think I need switch version twice during upgrade and both in test module, such as: 

        #Before upgrading, orginal system version is actually HDDVERSION
        loadtest "migration/version_switch_origin_system";
        load_patching_tests();
        #After original system patched, switch to UPGRADE_TARGET_VERSION
        loadtest "migration/version_switch_upgrade_target";


And seems it works as expected:
http://openqa-apac1.suse.de/tests/286
Note the failure is another issue to be fixed.

**Comment by QingmingSu** [comment]
@coolo Would you please help review my last implement with version switching in migration?

**Comment by coolo** [comment]
looks good to me - and I guess you could drop most other uses of HDDVERSION now

**Comment by QingmingSu** [comment]
Yes, most of HDDVERSION currently used can be dropped now. I will submit a separate commit to do a clean up.

**Comment by coolo** [comment]
and the good thing is that e.g. needles for http://openqa-apac1.suse.de/tests/286#step/boot_to_desktop/1 can be ENV-VERSION without breaking your use case

**Pull request merged**
