### PR TITLE
Update reboot_gnome_pre_sle11.pm

### PR DESCRIPTION
**Pull request by dzedro**
Hello,

power('acpi'); 
doesn't work for reboot on sle 11, is my change ok ?
I have tested it on http://10.100.98.90/tests/46

### CODE REVIEW

**Comment by coolo** [comment]
the only thing I would love to see you doing is splitting this into a function as we did for all the other tests - so that one day we can refactor this without having to extract the function first

**Comment by dzedro** [comment]
Like this ?
I think now about putting lines 27-38 into this fuction to do the whole action in this function "startmenu->dialog->action shutdown or reboot or other option based on what is requested"

**Comment by coolo** [comment]
ouch. This doesn't even look like proper perl. I mean seperating the key_round function as its down in all other tests.

**Comment by dzedro** [comment]
sorry, I was confused as I didn't know about fuction 'key_round'.

**Comment by coolo** [comment]
fine with me

**Pull request merged**
