### PR TITLE
Extend time for snapper delete timeout problem

### PR DESCRIPTION
**Pull request by tinawang123**
Extend time for snapper delete timeout problem

- Related ticket: https://progress.opensuse.org/issues/105552
- Verification run: http://openqa.suse.de/tests/8177590

### CODE REVIEW

**Review by chcao — APPROVED** [review]
LGTM

**Review by lilyeyes — APPROVED** [review]
LGTM

**Comment by lemon-suse** [comment]
[2022-02-15T08:22:21.987168+01:00] [debug] >>> testapi::wait_serial: snapper delete $snapaf $snapbf; echo U1teK-$?-: ok
[2022-02-15T08:22:21.987586+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run
[2022-02-15T08:22:21.987835+01:00] [debug] <<< testapi::type_string(text="\n")
[2022-02-15T08:22:21.989042+01:00] [debug] <<< consoles::serial_screen::type_string(text="\n", json_cmd_token="TjyivJIj", cmd="backend_type_string")
[2022-02-15T08:22:21.989869+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run
[2022-02-15T08:22:21.990491+01:00] [debug] <<< testapi::wait_serial(quiet=undef, buffer_size=undef, timeout=180, no_regex=0, record_output=undef, regexp=qr/U1teK-\d+-/u, expect_not_found=0)
[2022-02-15T08:22:21.992323+01:00] [debug] <<< consoles::serial_screen::read_until(pattern="(?^u:U1teK-\\d+-)", cmd="backend_wait_serial", no_regex=0, record_output=undef, buffer_size=undef, regexp="(?^u:U1teK-\\d+-)", json_cmd_token="kmWhqZIW", expect_not_found=0, timeout=360, quiet=undef)
[2022-02-15T08:23:03.461773+01:00] [info] ::: consoles::serial_screen::read_until: Matched output from SUT in 3 loops & 41.4697899549974 seconds: U1teK-0-
[2022-02-15T08:23:03.464124+01:00] [debug] >>> testapi::wait_serial: (?^u:U1teK-\d+-): ok
############################################

From the VR, it used 42s, I think update the timeout value to 90s is suitable. WDYT?

**Comment by tinawang123** [comment]
> [2022-02-15T08:22:21.987168+01:00] [debug] >>> testapi::wait_serial: snapper delete $snapaf $snapbf; echo U1teK-$?-: ok [2022-02-15T08:22:21.987586+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run [2022-02-15T08:22:21.987835+01:00] [debug] <<< testapi::type_string(text="\n") [2022-02-15T08:22:21.989042+01:00] [debug] <<< consoles::serial_screen::type_string(text="\n", json_cmd_token="TjyivJIj", cmd="backend_type_string") [2022-02-15T08:22:21.989869+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run [2022-02-15T08:22:21.990491+01:00] [debug] <<< testapi::wait_serial(quiet=undef, buffer_size=undef, timeout=180, no_regex=0, record_output=undef, regexp=qr/U1teK-\d+-/u, expect_not_found=0) [2022-02-15T08:22:21.992323+01:00] [debug] <<< consoles::serial_screen::read_until(pattern="(?^u:U1teK-\d+-)", cmd="backend_wait_serial", no_regex=0, record_output=undef, buffer_size=undef, regexp="(?^u:U1teK-\d+-)", json_cmd_token="kmWhqZIW", expect_not_found=0, timeout=360, quiet=undef) [2022-02-15T08:23:03.461773+01:00] [info] ::: consoles::serial_screen::read_until: Matched output from SUT in 3 loops & 41.4697899549974 seconds: U1teK-0- [2022-02-15T08:23:03.464124+01:00] [debug] >>> testapi::wait_serial: (?^u:U1teK-\d+-): ok ############################################
> 
> From the VR, it used 42s, I think update the timeout value to 90s is suitable. WDYT?



assert_script_run($cmd [, $timeout [, $fail_message]]);

Run $cmd via $distri\u2192script_run and die unless it returns zero (indicating successful completion of $cmd). Default timeout is 90 seconds.

**Comment by lemon-suse** [comment]
> > [2022-02-15T08:22:21.987168+01:00] [debug] >>> testapi::wait_serial: snapper delete $snapaf $snapbf; echo U1teK-$?-: ok [2022-02-15T08:22:21.987586+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run [2022-02-15T08:22:21.987835+01:00] [debug] <<< testapi::type_string(text="\n") [2022-02-15T08:22:21.989042+01:00] [debug] <<< consoles::serial_screen::type_string(text="\n", json_cmd_token="TjyivJIj", cmd="backend_type_string") [2022-02-15T08:22:21.989869+01:00] [debug] tests/console/pam.pm:67 called testapi::assert_script_run [2022-02-15T08:22:21.990491+01:00] [debug] <<< testapi::wait_serial(quiet=undef, buffer_size=undef, timeout=180, no_regex=0, record_output=undef, regexp=qr/U1teK-\d+-/u, expect_not_found=0) [2022-02-15T08:22:21.992323+01:00] [debug] <<< consoles::serial_screen::read_until(pattern="(?^u:U1teK-\d+-)", cmd="backend_wait_serial", no_regex=0, record_output=undef, buffer_size=undef, regexp="(?^u:U1teK-\d+-)", json_cmd_token="kmWhqZIW", expect_not_found=0, timeout=360, quiet=undef) [2022-02-15T08:23:03.461773+01:00] [info] ::: consoles::serial_screen::read_until: Matched output from SUT in 3 loops & 41.4697899549974 seconds: U1teK-0- [2022-02-15T08:23:03.464124+01:00] [debug] >>> testapi::wait_serial: (?^u:U1teK-\d+-): ok ############################################
> > From the VR, it used 42s, I think update the timeout value to 90s is suitable. WDYT?
> 
> assert_script_run($cmd [, $timeout [, $fail_message]]);
> 
> Run $cmd via $distri\u2192script_run and die unless it returns zero (indicating successful completion of $cmd). Default timeout is 90 seconds.

Ok, then please run VRs to prove it need timeout extend to 180s.

**Review by lemon-suse — APPROVED** [review]

**Pull request merged**
