### PR TITLE
Add development-tool-module as default

### PR DESCRIPTION
**Pull request by tinawang123**
[Added development tool module as default when doing migration]

- Related ticket: https://progress.opensuse.org/issues/44825

- Verification run: http://openqa-apac1.suse.de/tests/2555#
[autoinst-log.txt](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/2666005/autoinst-log.txt)

### CODE REVIEW

**Comment by coolo** [comment]
Why? I don't see any reasoning in the ticket

**Comment by tinawang123** [comment]
Updated the ticket.

> Why? I don't see any reasoning in the ticket
Updated the ticket.
According fate: https://fate.suse.com/325293

**Comment by coolo** [comment]
Thanks - that link helps

**Comment by ldevulder** [comment]
This PR breaks the HA upgrade test from SLE15 to SLE15-SP1: https://openqa.suse.de/tests/2360691#step/addon_products_sle/78

Because DevTools module is added but not the others needed one (according to the fate). Again because DevTools should have been added like desktop, legacy, serverapp and script module (check line 54) and only for MEDIA_UPGRADE (SCC upgrade should have the module automatically selected).

I will do a PR with a fix for this shortly.

**Pull request merged**
