### PR TITLE
Check package libgcrypt20-hmac installed

### PR DESCRIPTION
**Pull request by wangqianzou**
Progress issue: https://progress.opensuse.org/issues/107509

Check if the package libgcrypt20-hmac is installed

- Related ticket:  https://progress.opensuse.org/issues/107509
- Needles: None
- Verification run:
  - ENV mode: http://openqa.suse.de/tests/8695346#step/gpg/1
  - Kernel mode: https://openqa.suse.de/tests/8695319#step/gpg/1

### CODE REVIEW

**Comment by jouyingbin** [comment]
@wangqianzou looks like there are 3 duplicate git commits in this PR, please combine them into 1 commit.

**Comment by wangqianzou** [comment]
> @wangqianzou looks like there are 3 duplicate git commits in this PR, please combine them into 1 commit.

How to do it?

**Comment by wangqianzou** [comment]
> > @wangqianzou looks like there are 3 duplicate git commits in this PR, please combine them into 1 commit.
> 
> How to do it?

Combine duplicate commits by google.

**Review by jouyingbin — APPROVED** [review]
LGTM, thanks for the patch.

**Review by rfan1 — APPROVED** [review]

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Review by Amrysliu — APPROVED** [review]

**Pull request merged**
