### PR TITLE
Allow control for Installer self update funcionality on ppc64le

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by okurz** [comment]
Please don't [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself). You are copy-pasting existing code, please [extract method](http://refactoring.com/catalog/extractMethod.html).

**Comment by mimi1vx** [comment]
and ? I only fixing issue introduced by You

**Comment by coolo** [comment]
If you don't want to fix it properly, file an issue and assign it to okurz instead

**Comment by mimi1vx** [comment]
poo#18282

**Comment by sysrich** [comment]
> and ? I only fixing issue introduced by You

@mimi1vx can you point to the PR where @okurz introduced the issue?
We should fix what we broke, but I do not think Oli should be assigned this issue if we didn't break it.

**Comment by okurz** [comment]
The original PR by me was https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1540 in July 2016

**Comment by mimi1vx** [comment]
@sysrich worst, false feelings everything is good. But in reality is yast_self_update and yast_no_self_update test valid only for x86_64 and aarch64

**Comment by plusky** [comment]
@mimi1vx well my understanding is that test for installer updates was incomplete from beginning so it was not broken per se, it also creates impression of coverage that is not present. But as now QAM is interested in using it, its our responsibility to get it to state that would be acceptable for us.

**Comment by mimi1vx** [comment]
succeeded by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2758

**Pull request closed without merging**
