### PR TITLE
Fix lynis failures and update baselines

### PR DESCRIPTION
**Pull request by lilyeyes**
poo#108314 - [sle][security][sle15sp4] Lynis: update the baselines accordingly to bsc#1193804 (lynis updated from "2.6.1" to "3.0.6")

[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/108314
- Needles: none
- Verification run:
https://openqa.nue.suse.com/tests/8382538 (x86_64 textmode, as expected)
https://openqa.nue.suse.com/tests/8388584 (s390x gnome, as expected)
https://openqa.nue.suse.com/tests/8382534 (s390x textmode, as expected)
https://openqa.nue.suse.com/tests/8388793 (ppc64 gnome, as expected)
http://openqa.nue.suse.com/t8361892 (ppc64 textmode, as expected)
https://openqa.nue.suse.com/tests/8382536 (arm64 gnome, as expected)
https://openqa.nue.suse.com/tests/8382537 (arm64 textmode, as expected)

### CODE REVIEW

**Review by jouyingbin — APPROVED** [review]
LGTM

**Comment by jouyingbin** [comment]
small comment:
remove the **,** from the git commit message will be better.

**Comment by lilyeyes** [comment]
> small comment: remove the **,** from the git commit message will be better.

Done.

**Review by Amrysliu — COMMENTED** [review]
lgtm

**Pull request merged**
