### PR TITLE
Add expect script get_guest_ip to openqa data

### PR DESCRIPTION
**Pull request by XGWang0**
Add expect script to openqa data folder
This script is used to get guest ip address

- Related ticket: N/A
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11157

### CODE REVIEW

**Comment by XGWang0** [comment]
@Dawei-Pang  @alice-suse @lansuse Please help to review. thanks

**Comment by lansuse** [comment]
LGTM

**Comment by alice-suse** [comment]
LGTM. I am curious about the stability of expect script. How about that?

**Comment by XGWang0** [comment]
> LGTM. I am curious about the stability of expect script. How about that?

I did test for many times, very stable for single network card.

**Comment by Dawei-Pang** [comment]
LGTM

**Comment by alice-suse** [comment]
Cool.

**Pull request merged**
