### PR TITLE
Containers: fix hardcoded name for Dockerfile

### PR DESCRIPTION
**Pull request by jlausuch**
Detected failure: https://openqa.opensuse.org/tests/1913262#step/docker_image/111

### CODE REVIEW

**Comment by jlausuch** [comment]
https://openqa.opensuse.org/tests/1914049#live

**Review by Vogtinator — CHANGES_REQUESTED** [review]
I think that code is correct, see `BuildTest/Dockerfile` in line 50.

FWICT, `$base` is broken already and just `/python:3`, because of the special treatment of `docker.io` in `registry_url`.

**Comment by jlausuch** [comment]
> I think that code is correct, see `BuildTest/Dockerfile` in line 50.
> 
> FWICT, `$base` is broken already and just `/python:3`, because of the special treatment of `docker.io` in `registry_url`.

nah... yes, you are right... We are downloading the file to `" > $dir/BuildTest/Dockerfile"`.

**Comment by jlausuch** [comment]
That job shoudln't run container tests,as there is no container image for ppc

**Pull request closed without merging**
