### PR TITLE
Livecd installations can yield orphans

### PR DESCRIPTION
**Pull request by mloviska**
- Related ticket: https://progress.opensuse.org/issues/xyz
- Verification runs: 
   * [Rescue-CD-aarch64-Build1.1-rescue@USBboot_aarch64](http://eris.suse.cz/tests/3969#step/orphaned_packages_check/1)
   * [opensuse-15.1-GNOME-Live](http://eris.suse.cz/tests/3972)
   * [opensuse-15.2-KDE-Live](http://eris.suse.cz/tests/3971)
   * [opensuse-15.2-GNOME-Live](http://eris.suse.cz/tests/3970)
   * [opensuse-15.2-GNOME-Live](http://eris.suse.cz/tests/3968)

### CODE REVIEW

**Comment by mloviska** [comment]
> Patch looks good, but I cannot check the verification run as not publicly available.

I am sorry, I always forget about that. I am considering you as another fellow *geeko* already :)

**Comment by ggardet** [comment]
@mloviska no worries. Thanks for the new vr on o3.

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/1149402#step/zypper_clear_repos/21

Makes all stagings broken - the issue here is that the repo is actually not enabled post installation, leaving ALL packages being orphans

**Comment by DimStar77** [comment]
hmm.. probably this PR is not the actualy cause of the failure - there is a change in the ordering of the tests - orphan_packages is now in front of zypperl_lr and enable_usb_repo - which is definitively wrong

**Comment by DimStar77** [comment]
Found the PR responsible for this breakage - everything here seems ok. Sorry for the noise

**Pull request merged**
