### PR TITLE
add manual LVM setup testing

### PR DESCRIPTION
**Pull request by bmwiedemann**
to catch bugs like https://bugzilla.suse.com/show_bug.cgi?id=944634

### CODE REVIEW

**Comment by coolo** [comment]
what's the point of having a test within another?

**Comment by bmwiedemann** [comment]
It reduces confusion in the main.pm because there is one place where LVM is setup.

**Comment by sysrich** [comment]
It adds confusion, because it's two different tests, which will need to be called by two different sets of variables

This should be in two different test modules.

**Comment by bmwiedemann** [comment]
updated to be in a separate test file

**Comment by sysrich** [comment]
There's a lot of scope of things to go wrong with that test..lots of blind 'monkey mode' keypresses with no assert_screens in between

experiance has shown the need for assert screens, especially when doing lots of stuff in the expert partitioner - have a look at  partitioning_raid, lines 87-107 for an example of the expected level of needles for a test like this.

**Comment by bmwiedemann** [comment]
Feel free to add those asserts as needed. I cannot do it easily with os-autoinst, thus I just added the important part.

**Comment by sysrich** [comment]
#734 tests for the same bug, and doesn't need me to add extra assert screens, so closing this PR as I consider it superseded. Sorry :-/

**Pull request closed without merging**
