### PR TITLE
Allow cloning openQA jobs mentioned in PR comments

### PR DESCRIPTION
**Pull request by Martchus**
Related ticket: https://progress.opensuse.org/issues/130940

### CODE REVIEW

**Comment by Martchus** [comment]
openqa: Clone https://openqa.opensuse.org/tests/4188055

**Comment by okurz** [comment]
Should this work already, I assume not?

**Comment by Martchus** [comment]
Test comment; this probably won't trigger an action and we will just need to merge this PR to see whether it works.

**Review by b10n1k — APPROVED** [review]
Lets merge and see what will happen :)

**Review by kalikiana — APPROVED** [review]

**Comment by Martchus** [comment]
openqa: Clone https://openqa.opensuse.org/tests/4188055

**Comment by Martchus** [comment]
openqa: Clone https://openqa.opensuse.org/tests/4221654

(yet another test)

**Comment by Martchus** [comment]
Looks like it worked. For https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19305#issuecomment-2132991923 no openQA job was cloned due to:

> No test cloned; the user 'os-autoinst-bot' is not member of the team 'tests-maintainer' within 'os-autoinst'.

For https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19305#issuecomment-2132994132 the openQA job https://openqa.opensuse.org/tests/4223798 was created. It passed, had correct settings and a back reference to the relevant comment.

Not sure about the status reporting because for that I probably need to test on an open PR.

**Pull request merged**
