### PR TITLE
console/gpg: Use RSA keys explicitly and fix test for success

### PR DESCRIPTION
**Pull request by Vogtinator**
The test is meant to check with different key lengths, but those are only
used with non-ECC keys. So use RSA explicitly. Ideally there'll be a separate test for ECC keys in the future.

With ECC as default, key generation fails anyway because of
https://dev.gnupg.org/T5444.

Additionally, fix the `wait_serial` which failed with recent versions because the message isn't always printed.

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1193133
- Verification run: http://10.160.67.86/tests/1188

### CODE REVIEW

**Review by czerw — APPROVED** [review]
LGTM, but i thought that my name was already removed from that test

**Comment by Vogtinator** [comment]
> LGTM, but i thought that my name was already removed from that test

`# Maintainer: Petr Cervinka <pcervinka@suse.com>, Ben Chou <bchou@suse.com>`, and I couldn't add Ben as reviewer.

**Comment by czerw** [comment]
@foursixnine could you please check review as well as it runs in functional group?

**Comment by foursixnine** [comment]
@czerw Thanks, looks good, https://progress.opensuse.org/issues/101358 should be taken into account too

**Pull request merged**
