### PR TITLE
Squash the conditon against creating autoyast profile

### PR DESCRIPTION
**Pull request by nilxam**
create autoyast profile only when it's NORMAL DVD minimalx test

### CODE REVIEW

**Comment by DimStar77** [comment]
IMHO - we should never change the default install method - we are simply assuming now that saving the yast profile has no side effects... and assumption is always the beginning of a disaster (we no longer test MinimalX without autoyast profile being written)

This whole thing would be cleaner, imho, if a test, targeting yast things (we already have yast2_ui_gnome, but that does not pass the installer) would just set the variable as part of the test suite.. and not as part of the test run trying to get an idea if we should/could/want to test this.

**Comment by sysrich** [comment]
autoyast is considered a key feature for SLE, we need it to be tested as heavily as possible (because it is so key), as often as possible (because it is so sensitive to all the different variables which openQA is controlling), and as early as possible (because YaST issues can, and do, break stagings and therefore halt all development on SLE)

While I understand the need for autoyast testing might not be quite so strong in openSUSE, I think it's really important to share the SLE perspective here because testing autoyast has identified a huge pile of openSUSE affecting bugs also..we shouldn't let this just be pushed to one side because it's inconvenient.

**Comment by DimStar77** [comment]
I'm fine with testing it - I'm not fine in no longer testing what 99% of the user base installs.

**Comment by DimStar77** [comment]
(99% of the user base opting for minimal X that is)

**Comment by sysrich** [comment]
Agreed..why not have it on (at least) the main 3 options, KDE, GNOME and Minimal (Server)?

That seems to make sense to me..I don't see a need to burrow into the deeper ones like Minimal_X, XFCE, etc, but the 'big 3' should probably get covered

**Comment by okurz** [comment]
… and a typo in the commit message

**Comment by DimStar77** [comment]
@sysrich but should it be covered in the 'default install' we test to represent what users do or should it rather be additional test suites with a variable specified as an explicit test for this special case?

Again: we assume that the 'write' link in yast does not cause side-effects

**Comment by sysrich** [comment]
The 'write' link in yast shouldn't cause side effects - and if it does, then we should file those as bugs

I think that creating additional scenarios for autoyast testing in openSUSE openQA is wasteful of the already struggling hardware that openSUSE openQA has

We won't be doing that on SLE openQA, because write is default and because autoyast is so important to be tested heavily

**Comment by nilxam** [comment]
Other than discuss how we handle this test in openSUSE openQA, I'm suspect this test would not for now as https://openqa.opensuse.org/tests/113463/modules/ay_profilecheck/steps/4 is failed, seems failed in openqa.suse.de as well, it's about https://bugzilla.suse.com/show_bug.cgi?id=956012 and yast2-network 3.1.140 was in Factory already, so I've just asked Michal, he will check it later.

**Comment by nilxam** [comment]
IMO I agree we should have a test against autoyast in openSUSE, BUT the test should not block the process ie. give us a chance put it in %known_failures% rather than stop the process till the bug fixed, enable it in the main 3 tests is too much for me.

**Comment by nilxam** [comment]
we can continue the discussion, but can we agree revert https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/af5afc1b0d3b870f7df3ae71acd12c66eaf5461a and https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/af5afc1b0d3b870f7df3ae71acd12c66eaf5461a for now(and I'll close this one)?

**Comment by DimStar77** [comment]
I agree with the revert... it's too invasive and untested to block all stagings and releases of TW snapshots at this moment.

Let's re-introduce it in a more phased / testable approach please:
1) enable it based on a test suite variable (yes, this is a bit more load on the openQA HW, but we can gain experience with the test, mark it as broken and not block TW releases for now)
2) once *1* is sufficiently good, we can discuss changing it to be more wide-spread enabled - by either setting the variable in more tests or even changing the code...

**Comment by coolo** [comment]
Yes, openqa.opensuse is not supposed to test SLE defaults, but opensuse ones.

**Comment by nilxam** [comment]
I'll revert it in 10 minutes.

**Comment by sysrich** [comment]
Paging @cwh42 - I Want you to be aware that we had to revert this and have a chance to review the discussion here. You probably want an opportunity to be involved in the reworking of the tests also.

**Comment by cwh42** [comment]
Neverlasting story.
So let's drop the changes in installation_overview.
Let's schedule ay_profilecheck not for openSUSE but only for SLE and all should be fine.

**Comment by nilxam** [comment]
btw  per the comment in ay_profilecheck.pm

# This test only succeeds if system is booted with static network config like this:
# EXTRABOOTPARAMS="ifcfg='eth0=10.0.2.22/24,10.0.2.2,10.0.2.3,susetest'"

so just merge https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/186c563add397152bbaaa93a099d0d4cb46722fe won't I assumed, need some more work in main.pm or change job settings(new variable for new test or update old job settings).

**Comment by cwh42** [comment]
First I considered the AY tests be tested only in a special test scenario. So it was triggered by a setting AY_PROFILECHECK which also set the above EXTRABOOTPARAMS.
Since I was asked to change it to be the default scenario I removed this code.
So I need to add it again.

Do you all agree that this is the way to go?

**Comment by nilxam** [comment]
Sounds good to me, if we want to enable it in old testsuite we can add AY_PROFILECHECK to the settings of testsuite.

**Pull request closed without merging**
