### PR TITLE
Introduce timeout for installation

### PR DESCRIPTION
**Pull request by rwx788**
As part of commit 44e5ffe3 we have removed timeout in order to get
better error handling if test fails to match any of possible needles.
Whereas under some conditions, we may end up in infinite loop if
assert_screen always matches a needle. So, we introduce timeout back,
but try to keep advantages of previous implementation as well.

Verification run for failing scenario: http://gershwin.arch.suse.de/tests/226
Verification run for successful installation: http://gershwin.arch.suse.de/tests/247 (another test used)

### CODE REVIEW

**Comment by okurz** [comment]
+1

@kravciak ?

**Comment by kravciak** [comment]
This approach shortens 2 hour loop into 30 minute loop - I would suggest using something like
wait_screen_change(undef, 300) to detect corner case where installation gets stack.

But LGTM, it's an improvement to have screenshots instead of incomplete.

**Comment by okurz** [comment]
cool, so let's see how it behaves. Your suggestion regarding wait_screen_change is good. @rwx788 you might want to try it out.

**Comment by kravciak** [comment]
Related PR (should also fix you issue in some cases) https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3068

**Comment by rwx788** [comment]
@okurz I'll try it out. Looked a bit like a hack to me, as we don't pass any code ref.

**Pull request merged**
