### PR TITLE
wicked: Add PowerKVM support to 15

### PR DESCRIPTION
**Pull request by asmorodskyi**
Add PowerKVM support to 15

### CODE REVIEW

**Comment by okurz** [comment]
Seeing the subject line I was surprised and asked myself: "What? Do we not have powerKVM support for '15' – whatever that refers to – since long?" :D Please be more specific in the commit message

**Comment by asmorodskyi** [comment]
is it good enough ?

**Comment by okurz** [comment]
Please change the **commit**

**Comment by asmorodskyi** [comment]
> Please change the **commit**


sure thing, I will change commit . Just because changing **commit** is more time consuming I just wanted to agreed with you on something to not changing commit dozen times :)

**Comment by asmorodskyi** [comment]
also keep in mind that current PR has WIP label so not ready for review actually ...

**Comment by schlad** [comment]
I would still ask for better subject. Current one still is at least misleading and in fact incorrect.

What you are doing is: "wicked: create powerKVM autoyast profile"
Right?

I can't see how you "Add PowerKVM support to 15".

Yeah... being picky again ;-)

**Comment by asmorodskyi** [comment]
> create powerKVM autoyast profile

done

**Pull request merged**
