### PR TITLE
Cleanup not used fixup code for 13.1

### PR DESCRIPTION
**Pull request by dzedro**
I could not find tests using this code.
This can be removed ... https://openqa.opensuse.org/tests/1275141

### CODE REVIEW

**Comment by okurz** [comment]
I don't understand. You linked a failing test case that is clearly showing "fixup/network_configuration" in the schedule. How do you think you can remove it then?

Of course there are multiple problems here as well:

1. you requested review from me and DimStar and I have not responded. I tend to go over https://github.com/notifications and try to handle all relevant entries. Seems I have marked this PR as "read" even though I failed to look. I do not know how to be reminded about "all open PRs where I am requested for review" in a consistent way. I was only seeing it now because @rwx788 merged the PR so it popped up as unread again

2. The test scenario should not stay in "Development" in this unhandled way without an open ticket reference. We should ensure to handle tests accordingly. I will open a ticket for this and we can decide if we want to bring the scenarios back or if they should be gone for good.

**Comment by dzedro** [comment]
Heh forgot about it, thank you @rwx788 !

img

**Comment by okurz** [comment]
Noted in https://progress.opensuse.org/issues/53729#note-22

**Comment by rwx788** [comment]
I guess we can remove that scenario, it even feels like we don't officially support upgrade from 13.1, and I mean it's ancient =)

**Comment by okurz** [comment]
Yeah, that's true. It was a cool show-off though for openSUSE *and* openQA that this still worked for so long :) and it was showing quite some valid problems. And official "support" is something that is vague for openSUSE anyway ;)

**Pull request merged**
