### PR TITLE
Merge podman and docker 3rd_party_images tests

### PR DESCRIPTION
**Pull request by ilausuch**
- Related ticket: https://progress.opensuse.org/issues/101213
- Verification run: 
https://openqa.suse.de/tests/8185823 (docker)
https://openqa.suse.de/tests/8185822 (podman)
O3:
https://openqa.opensuse.org/tests/2193756
https://openqa.opensuse.org/tests/2193757
https://openqa.opensuse.org/tests/2193760
https://openqa.opensuse.org/tests/2193763
https://openqa.opensuse.org/tests/2193764 (microos)

### CODE REVIEW

**Review by mloviska — APPROVED** [review]
So far, so good! Let's wait for VRs

**Review by jlausuch — APPROVED** [review]

**Review by pdostal — APPROVED** [review]

**Comment by mloviska** [comment]
We might break sle-micro (still using yaml) and microos as with the previous PR.

**Comment by mloviska** [comment]
Actually it might work http://kepler.suse.cz/tests/13745# adding `TEST_CONTEXT=OpenQA::Test::RunArgs`

**Review by jlausuch — CHANGES_REQUESTED** [review]
yes, I completely forgot about that... I'm changing to `request changes` to not create regression.

**Comment by jlausuch** [comment]
> We might break sle-micro (still using yaml) and microos as with the previous PR.

MicroOS was broken due to the podman_image filename change, but I already fixed it: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14268

3rd party is not executed in MicroOS. 

But Both are executed in SLE Micro, and they use yaml (something to move to main_containers), and it's also broken: https://openqa.suse.de/tests/8184518

**Comment by mloviska** [comment]
> Actually it might work http://kepler.suse.cz/tests/13745# adding `TEST_CONTEXT=OpenQA::Test::RunArgs`

http://kepler.suse.cz/tests/13746 doesnt and not even with specifying container runtime to podman explicitly. 
In order to proceed, let me create a PR to shift the schedule to `main.pm` like scheduling.

**Comment by ilausuch** [comment]
I rebased from master

**Comment by ilausuch** [comment]
Restarting all tests

**Review by jlausuch — APPROVED** [review]

**Pull request merged**
