### PR TITLE
Substitute SAP repo to LTSS

### PR DESCRIPTION
**Pull request by dzedro**
SAP is ESPOS so updates are going into Update LTSS repo
e.g. SLES_SAP_15_x86_64 -> SLES_15-LTSS_x86_64

- Related ticket: https://progress.opensuse.org/issues/105843
- Verification run:
https://openqa.suse.de/tests/8090946 15 SP1 x86_64
https://openqa.suse.de/tests/8090945 15 SP1 ppc64le
https://openqa.suse.de/tests/8090951 15 x86_64

### CODE REVIEW

**Comment by a-kpappas** [comment]
I think we should talk to MaintSec Tools first. This could be a submission/ibs error, because there is an ESPOS channel.[

**Comment by a-kpappas** [comment]
Security said they will be retracting the submission, as it was done in error.

**Comment by msmeissn** [comment]
it was not an error, submission was fine... see slack thread.

**Comment by dzedro** [comment]
I would merge this change, until new API call is used ?

**Pull request merged**
