### PR TITLE
s390x: For Version < 12-SP4 look into fixed folder

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
@okurz @rwx788 
WDYT?

**Comment by okurz** [comment]
If we can't get multiple paths to search for then maybe we should look for 'GM' in the name and assume that repo to be under fixed but please fail with obvious error messages if any of the assumptions don't meet.

**Comment by coolo** [comment]
What's wrong with the symlinks to fixed we added?

**Comment by rwx788** [comment]
@coolo We are not sure if gru clean up won't remove these. Another workaround we can do is to set permissions in the way that gru cannot remove files.

**Comment by okurz** [comment]
@coolo the symlinks are removed by GRU -> https://progress.opensuse.org/issues/21038#note-7

**Comment by asmorodskyi** [comment]
@Soulofdestiny  near 1 month pass since PR was created - is it still relevant ?

**Comment by Soulofdestiny** [comment]
@asmorodskyi I guess so, but the discussion wasn't ongoing
@okurz ?

**Comment by rwx788** [comment]
Solution with symlinks doesn't work, they get removed unless created with root permissions. But I would still rather look in both directories in all cases.

**Comment by okurz** [comment]
we should together discuss with @coolo in person. Currently on osd I have as a workaround a cron job that periodically is recreating the symlinks in case they get cleaned up.

**Comment by Soulofdestiny** [comment]
I'm closing this...

**Pull request closed without merging**
