### PR TITLE
Fix desktop on leanos

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
oops, pushed to wrong repo. Fortunately to the right branch :)

**Comment by coolo** [comment]
validation run http://tortuga.suse.de/tests/2539#

**Comment by okurz** [comment]
Couldn't access the validation run. I guess the machine is down right now?

You are removing the "update" test also from staging which I think previously was testing at least that the update applet works. I don't mind removing it now but do you think we should revisit this and all other modules that were removed from staging and call some more tests in staging again in the future?

**Comment by coolo** [comment]
I didn't turn off tortuga, but can't reach it either - monday...

Staging coverage is indeed a balance - it should be quick but avoid as many regressions as possible. The value of testing the update applet during alpha phase is limited - but during RC phase is crucial.

What's critical with this test (and why we might want to add it back asap) is that it's fatal. So while in stagings we see failures after it, in post validation we don't. The catch: it's only fatal for maintenance tests, for product QA it's a test like any other.

**Pull request merged**
