### PR TITLE
vlc: type slowly to avoid mistyping

### PR DESCRIPTION
**Pull request by ggardet**
- Related ticket: https://progress.opensuse.org/issues/54914
- Verification run: https://openqa.opensuse.org/t1092780

### CODE REVIEW

**Comment by okurz** [comment]
I think coolo conducted some tests with very low limits of VNC_TYPING_LIMIT mentioning exactly this line being problematic especially when typing *slow*.

Neither your commit nor the ticket show a good statistical investigation. I recommend to follow https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation , give o3 some work for the weekend :) E.g. schedule 100 tests with just boot_to_desktop,vlc with and without your changes and compare the numbers

**Comment by ggardet** [comment]
> I think coolo conducted some tests with very low limits of VNC_TYPING_LIMIT mentioning exactly this line being problematic especially when typing _slow_.
> 
> Neither your commit nor the ticket show a good statistical investigation. I recommend to follow https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation , give o3 some work for the weekend :) E.g. schedule 100 tests with just boot_to_desktop,vlc with and without your changes and compare the numbers

IIRC, the problem occurs more often on a full schedule, compared to just boot_to_desktop,vlc 
I will check with coolo what he tried.

**Comment by ggardet** [comment]
With `type_string_slow`, VR passed properly on aarch64.

**Comment by coolo** [comment]
On aarch64 we type with 0.14 seconds per keypress, type_slow adds 0.3s to that - so basically 2 keys per second. vlc seems to trigger something in the background while typing. I bet you can reproduce this in manual tests as well.

**Comment by ggardet** [comment]
> On aarch64 we type with 0.14 seconds per keypress, type_slow adds 0.3s to that - so basically 2 keys per second. vlc seems to trigger something in the background while typing. I bet you can reproduce this in manual tests as well.

So, you would recommend to wait for vlc to finish whatever it is doing instead of slower typing?

**Comment by okurz** [comment]
@ggardet I would like that as well, yes. Because it would make it explicit *what* we wait for rather than just typing slower based on a hunch :)

**Comment by ggardet** [comment]
Let's close this PR as VLC problem has not pop up since a while.

**Pull request closed without merging**
