### PR TITLE
Revert 969d2b9 for systemd_testsuite

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Related ticket: https://progress.opensuse.org/issues/56012
- Failing jobs: https://openqa.suse.de/tests/3290268#next_previous
- Related PR: #7837

### CODE REVIEW

**Comment by foursixnine** [comment]
@SergioAtSUSE I would prefer if @pevik would propose a solution before reverting, since also @mloviska is affected by this. Unless he doesn't have bandwidth for it?

**Comment by pevik** [comment]
If this cannot be fixed with correct `QA_HEAD_REPO` variable definition let's revert it. Sorry for a breakage.

**Comment by pevik** [comment]
@foursixnine @SergioAtSUSE I'll have a look into it.

**Comment by foursixnine** [comment]
> If this cannot be fixed with correct `QA_HEAD_REPO` variable definition let's revert it. Sorry for a breakage.

No worries :)

**Comment by SergioAtSUSE** [comment]
This revert is a workaround. The real fix should be done here https://progress.opensuse.org/issues/56012

This test should have never used QA_HEAD_REPO, it was a mistake since the beginning.

**Comment by pevik** [comment]
FYI JeOS fixed in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8308, now investigating systemd failure.

**Comment by pevik** [comment]
@foursixnine https://progress.opensuse.org/issues/56012#note-4
I guess this should be merged as a quick fix solution, @SergioAtSUSE plan to do further changes in https://progress.opensuse.org/issues/56012.

**Comment by foursixnine** [comment]
> https://progress.opensuse.org/issues/56012#note-4

What a mess. @SergioAtSUSE Please before proposing and building a big solution based on yet another obs repo, let's discuss it further to avoid the messy situation between QA:Head and other things.

**Comment by SergioAtSUSE** [comment]
@foursixnine, that is why this is to be refined in a grooming meeting: https://progress.opensuse.org/issues/56012

**Pull request merged**
