### PR TITLE
s390x: Give grub more time to appear after reboot

### PR DESCRIPTION
**Pull request by Soulofdestiny**
fixes e.g. https://openqa.suse.de/tests/1816610

### CODE REVIEW

**Comment by okurz** [comment]
I don't understand the problem. How did you know that we need more time? Can I see that within https://openqa.suse.de/tests/1816610/file/autoinst-log.txt but I did not see it?

**Comment by Soulofdestiny** [comment]
```
[2018-07-05T16:26:40.0716 CEST] [debug] <<< backend::console_proxy::__ANON__(wrapped_call={
  'function' => 'expect_3270',
  'console' => 'x3270',
  'args' => [
              'output_delim',
              'GNU GRUB',
              'timeout',
              30
            ]
})
```

but serial output is still from the installation system which means that system is not rebooted yet.

30seconds later:

```
[2018-07-05T16:27:10.0360 CEST] [debug] Could not find GRUB screen, continuing nevertheless, trying to boot
```

**Comment by Soulofdestiny** [comment]
but yeah, there might be something else wrong.
nevertheless - 60s is not too much time for the reboot imho

**Comment by okurz** [comment]
but it's not 60s for the complete "reboot" cycle but only from clicking the button to reboot from the installation until the grub screen shows up again, right? We can merge this. I guess we could even live with a way higher timeout.

**Pull request merged**
