### PR TITLE
Fix switch to console in welcome and addon_dud schedule

### PR DESCRIPTION
**Pull request by jknphy**
After #7380 we are switching to console in a few scenarios in welcome module during installation before accepting the license and the combination of keys `ctrl-alt-shift-x` does not work when the focus is on a select box: https://openqa.suse.de/tests/2882740#step/welcome/5 producing strange effect that the following commands that are written in the terminal makes a search in the select box (Galician is selected when grep is typed).
Also related with the change in workflow after #7380, we need to schedule `addon_dud` after license acceptance.

- Related ticket: https://progress.opensuse.org/issues/50666
- Needles: N/A
- Verification run: 
  - [sle-12-SP5-MINI-ISO-gnome_http](http://rivera-workstation.suse.cz/tests/2680#step/welcome/6)
  - [sle-12-SP5-dud_sdk](http://rivera-workstation.suse.cz/tests/2682#step/dud_addon/5)

### CODE REVIEW

**Comment by b10n1k** [comment]
@jknphy i cant see the changes on welcome in the VR links which you provide

**Comment by jknphy** [comment]
> @jknphy i cant see the changes on welcome in the VR links which you provide

Both links appears accessible to me. fqdn is provided ending in suse.cz. Perhaps you dns configuration?

**Comment by b10n1k** [comment]
they links are accesible. the welcome module is not containing the PR;s changes. So i assume the VRs run with old welcome module or something

**Comment by jknphy** [comment]
> they links are accesible. the welcome module is not containing the PR;s changes. So i assume the VRs run with old welcome module or something

on openQA Web UI you cannot trust on the module code, as it depends on the current git branch you are.

**Comment by b10n1k** [comment]
> > they links are accesible. the welcome module is not containing the PR;s changes. So i assume the VRs run with old welcome module or something
> 
> on openQA Web UI you cannot trust on the module code, as it depends on the current git branch you are.

yup that s what i am saying. if you are not running the VR from the working branch how do you verify that the VR is correct?

**Comment by jknphy** [comment]
> > > they links are accesible. the welcome module is not containing the PR;s changes. So i assume the VRs run with old welcome module or something
> > 
> > 
> > on openQA Web UI you cannot trust on the module code, as it depends on the current git branch you are.
> 
> yup that s what i am saying. if you are not running the VR from the working branch how do you verify that the VR is correct?

I'm running the VR from the working branch, one way to know is to check the logs:
`[2019-05-10T14:45:47.0826 CEST] [debug] <<< testapi::send_key(key='alt-y', do_wait=0)`
```
[2019-05-10T15:07:15.0491 CEST] [debug] scheduling accept_license tests/installation/accept_license.pm
[2019-05-10T15:07:15.0492 CEST] [debug] scheduling dud_addon tests/installation/dud_addon.pm
```
The other way is to check in `var.json`: `TEST_GIT_HASH`:
This is my branch related with my PR: https://github.com/jknphy/os-autoinst-distri-opensuse/commits/fix_switch_to_console_welcome and you can find 49b8ef8 related to one commit and 0048ec4 related to the other one. I fact that was not true, I checked and was not pointing to a previous commit to my work 97c6a65, so I restarted the job again http://rivera-workstation.suse.cz/tests/2696 What I realized is that even if you trigger the job with your working branch, var.json is written at the end when the job finishes, so if I have a different branch when the job is uploading assets then TEST_GIT_HASH is not realiable, So I guess when reviewing PRs, we might want to check first this setting and if doesn't match go the logs or go to the logs straightforward to see if the changes are meaningful and corresponds with the PR. I hope it is more clear now

**Comment by jknphy** [comment]
Ok, let's give it a try and address this specific issues.

**Pull request merged**
