### PR TITLE
Support new sle15sp7 release

### PR DESCRIPTION
**Pull request by Julie-CAO**
https://progress.opensuse.org/issues/163682

No verfification run yet. Going to verify on OSD after PR is merged.

@alice-suse @guoxuguang @waynechen55 and others, welcome review!

### CODE REVIEW

**Comment by alice-suse** [comment]
Thanks for the PR. Similar comment with https://github.com/SUSE/qa-automation/pull/837. Do not forget to update 15sp6 xml files to turn on registration.

**Comment by Julie-CAO** [comment]
> Thanks for the PR. Similar comment with [SUSE/qa-automation#837](https://github.com/SUSE/qa-automation/pull/837). Do not forget to update 15sp6 xml files to turn on registration.

Thanks, done.

**Comment by alice-suse** [comment]
No more wait for review. Let's merge it to further check result .

**Comment by guoxuguang** [comment]
LGTM

**Pull request merged**
