### PR TITLE
Integrate xen_pv and xen_hvm into one

### PR DESCRIPTION
**Pull request by XGWang0**
Integrate xen_pv and xen_hvm into one
Divide big test case hash into multiple one, is convenient to extend test cases and adapt to multiple test planform.
Using openqa file service as storage to fetch expect scripts instead  of gitlab
Remove pti_check and mds_taa_check functions, and convert them to test cases and store them in case hash.
Add junit log, is easy to review test result.
Support user specify parts of test suite to run instead of full.

- Related ticket: N/A
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11097

### CODE REVIEW

**Comment by XGWang0** [comment]
@alice-suse @Dawei-Pang @lansuse  Please help to review. Thanks

**Comment by Dawei-Pang** [comment]
LGTM

**Comment by alice-suse** [comment]
@XGWang0 Are you planning to deliver the changes in 10 commits?

**Comment by XGWang0** [comment]
> @XGWang0 Are you planning to deliver the changes in 10 commits?

I rebase them into one.

**Pull request merged**
