### PR TITLE
Keep VM running option

### PR DESCRIPTION
**Pull request by mnowaksuse**
@mimi1vx FYI.

### CODE REVIEW

**Comment by okurz** [comment]
typo in PR subject line

> LGTM , must be merged with os-autoinst/os-autoinst#697/

keep in mind that os-autoinst changes are not synced to the worker infrastructure automatically and only on demand

**Comment by mnowaksuse** [comment]
Both API notations are now supported. Though this can be used only after https://github.com/os-autoinst/os-autoinst/pull/697 is deployed.

**Comment by mnowaksuse** [comment]
@coolo Can it be merged now?

**Comment by coolo** [comment]
yeah, workers are deployed

**Comment by okurz** [comment]
LGTM, @mnowaksuse remove notready label and merge as you like

**Comment by mnowaksuse** [comment]
Can't merge on my own, don't have permissions.

**Pull request merged**
