### PR TITLE
Detect unused modules

### PR DESCRIPTION
**Pull request by okurz**
* Accept modules loaded by load_testdir as 'used'
* Make 'detect-unused-modules' a real test
* travis: Also check for unused modules
* Delete unused modules as reported by 'detect_unused_modules'
* tools: Add script to detect unused modules

### CODE REVIEW

**Comment by asmorodskyi** [comment]
LGTM

**Comment by okurz** [comment]
better not merge that one yet as it is deleting some modules. I at least want to give colleagues possibility for taking a look

**Comment by okurz** [comment]
@nadvornik @psladek @DimStar77 @alice-suse @QingmingSu @xjinGitty @chuchingkai I am deleting modules you maintain/created. Please respond back if needed. Otherwise, revive them after deletion.

**Comment by nilxam** [comment]
don't count those `DE`_reconfigure_openqa module, your script does not handle that...

**Comment by alice-suse** [comment]
Oliver, the file, host_upgrade_step1_run.pm, can you keep it? We may use this step in future.

**Comment by chuchingkai** [comment]
Hi Oliver,

I will add the entry in main.pm and testsuits for all remote desktop cases after I finished another remote desktop case, because I haven't decided how to arrange the testsuits yet. They will be activate in the next week, including:

- onetime_vncsession_multilogin_failed.pm
- onetime_vncsession_xvnc_java.pm
- onetime_vncsession_xvnc_tigervnc.pm
- persistent_vncsession_xvnc.pm
- x11_forwarding_openssh.pm
- xdmcp_gdm.pm
- xdmcp_xdm.pm

And the two evolution cases are blocked by Exchange testing mail account, we will re-activate them once the account is ready, could you also keep them, including:

- evolution_mail_ews.pm
- evolution_task_ews.pm

**Comment by QingmingSu** [comment]
As to "evolution_mail_ews.pm", it is still required by chuchingkai.

**Comment by nadvornik** [comment]
@okurz Can you please keep the tests in slepos directory? They are used in sle11 and I'd like to keep the slepos directory the same to simplify maintenance.

**Comment by asmorodskyi** [comment]
@okurz  what your plans regarding this PR ?

**Comment by okurz** [comment]
> @okurz what your plans regarding this PR ?

rebase, check the files that have been reported and either put them into a kind of exclude list or convince people that they should not be in the master branch when they are not actively used

**Comment by okurz** [comment]
need to recheck

**Comment by okurz** [comment]
@nadvornik @psladek @DimStar77 @alice-suse @QingmingSu @xjinGitty @chuchingkai updated to delete less:

```
tests/virt_autotest/host_upgrade_step1_run.pm
tests/virtualization/virtman_create_guest.pm
tests/virtualization/virtman_networkinterface.pm
tests/x11regressions/evolution/evolution_mail_ews.pm
tests/x11regressions/evolution/evolution_task_ews.pm
tests/x11regressions/tomboy/tomboy_Open.pm
tests/x11regressions/tomboy/tomboy_StartNoteCannotBeDeleted.pm
tests/x11regressions/tomboy/tomboy_checkinstall.pm
tests/x11regressions/tomboy/tomboy_firstrun.pm
```

Keep in mind that we can always get back test modules from git history so nothing is lost :)

**Comment by okurz** [comment]
@Soulofdestiny please re-review as well

**Comment by asmorodskyi** [comment]
@okurz  - should I merge ? it's git after all we can always revert :)

**Comment by okurz** [comment]
let me handle that. At least one test module (snapper_ncurses) is used now so I will keep it then.

**Comment by okurz** [comment]
Updated, please take a look again

**Pull request merged**
