### PR TITLE
WIP:Fix hardcoded snapshot number.

### PR DESCRIPTION
**Pull request by MalloZup**

### CODE REVIEW

**Comment by MalloZup** [comment]
proof

**Comment by MalloZup** [comment]
test2

**Comment by MalloZup** [comment]
after update is the snap after upgrade. the current snap 
is before upgrade

**Comment by MalloZup** [comment]
testing the snapper rollback right now

**Comment by sysrich** [comment]
Looks good so far

I'm thinking about how this will go live..looking at your 2nd screenshot, I do not believe we can use that approach to edit an existing scenario - wouldn't that end up running Console and X11 tests on the 'before migration' system?

Therefore I think we need a new scenario

migration_rollback_sle12sp1 and migration_rollback_sle12ga

I see two ways we could test this

option a) do it the way you have screenshotted, using the variables you used for your testing

option b) save time and have the scenario triggered after a regular migration test <- this approach takes longer, but has the added benefit of testing the migration of ga/sp1 to sp2 and fully validating the distribution, then rolling back that exact image and fully re-validating the distribution on the earlier version

**Comment by MalloZup** [comment]
wouldn't that end up running Console and X11 tests on the 'before migration' system? 

In the snapper_rollback test, after the test i rollback in the "after migration system" so we can do the others tests.

**Comment by sysrich** [comment]
yes but that's a good thing - how else are you going to know the rollback worked?

**Comment by MalloZup** [comment]
good question, well this is a problem yes, if you want to test the whole distro rollbacked.. 
 we should create an image for that maybe, and make the standards tests.. 

i think is the same as solution b) you proposed

**Comment by MalloZup** [comment]
btw, what it a call for api to reboot and wait it ( i have to reboot 2 times)

**Pull request closed without merging**
