### PR TITLE
Upload active runfiles in boot_ltp

### PR DESCRIPTION
**Pull request by mdoucha**
Passing runfile contents through `script_output()` sometimes results in pieces of the file missing. Upload the active runfiles as assets instead. As a bonus, the runfile will be downloadable from the job assets tab in the web UI.

- Related ticket: N/A
- Needles: N/A
- Verification runs:
  - SLE-12SP5@x86_64: https://openqa.suse.de/tests/4414150
  - SLE-12SP5@s390x: https://openqa.suse.de/tests/4414153

### CODE REVIEW

**Comment by richiejp** [comment]
LGTM, except for issue with `~` (not being expanded/removed?) in the openposix runtest path.

**Comment by mdoucha** [comment]
Fixed the openposix runtest path.

**Comment by richiejp** [comment]
Needs a repush/retest with the Perltidy fix *sigh*

**Comment by mdoucha** [comment]
Fixed the style error in `read_runfile()`. The perltidy version should be fixed in Travis. New verification runs:
https://openqa.suse.de/tests/4424662
https://openqa.suse.de/tests/4424663

**Comment by richiejp** [comment]
Thanks!

**Pull request merged**
