### PR TITLE
Install yast module per test

### PR DESCRIPTION
**Pull request by nilxam**
Install yast module per test before started to testing

P.S. require new api assert_script_run and assert_script_sudo deployed

### CODE REVIEW

**Comment by lnussel** [comment]
is there a reason for the extra wait_idle? The command is guaranteed to be completed when it returns.

**Comment by nilxam** [comment]
updated

**Comment by dzedro** [comment]
https://openqa.suse.de/tests/97452/file/autoinst-log.txt

**Comment by sysrich** [comment]
Yup, waiting for OBS to publish the new os-autoinst

**Pull request merged**
