### PR TITLE
Follow itlb kernel changes and replace error by softfail

### PR DESCRIPTION
**Pull request by Dawei-Pang**
kernel-sources commit 52699f0f6a3a905d203dbea53c8936e3b6badba0 modify itlb sysfs behaviour, follow it and make testing as expected.  
Verification URL: http://openqa.qa2.suse.asia/tests/20932

Due to make the functional failure not block remaining test cases, replace assert by record_soft_failure.
Verification URL: http://openqa.qa2.suse.asia/tests/21094

### CODE REVIEW

**Comment by Dawei-Pang** [comment]
@lansuse @XGWang0 @alice-suse 

Would you please help to review? Thanks!

**Comment by lansuse** [comment]
LGTM

**Comment by alice-suse** [comment]
Would you please merge the two commit into one?

**Comment by Dawei-Pang** [comment]
> Would you please merge the two commit into one?

done

**Pull request merged**
