### PR TITLE
Check FIPS vars in the correct way or bailout

### PR DESCRIPTION
**Pull request by ilmanzo**
Fixes an incorrect way of checking for test variables. 

note: this most likely will make some not properly configured test suites to fail, so we can promptly fix them. 

- Related ticket: https://progress.opensuse.org/issues/167063
- Needles: n/a
- Verification runs:
  - https://openqa.suse.de/tests/15505991
  - https://openqa.suse.de/tests/15505992
  - https://openqa.suse.de/tests/15506004
  - https://openqa.suse.de/tests/15506023

### CODE REVIEW

**Comment by feri** [comment]
LGTM

**Comment by DimStar77** [comment]
This seems to break the known fips tests for tumbleweed:

https://openqa.opensuse.org/tests/4502637#step/fips_setup/1

**Comment by ggardet** [comment]
For aarch64 Tumbleweed as well: https://openqa.opensuse.org/tests/4503246#step/fips_setup/2

**Comment by ilmanzo** [comment]
Thanks for the heads up; created [new PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20255). Please consider that FIPS is not officially supported on Tumbleweed.

**Pull request merged**
