### PR TITLE
Determine kernel dynamically

### PR DESCRIPTION
**Pull request by DrMullings**
To avoid hardcoding and coplex conditions

- Related ticket: https://progress.opensuse.org/issues/53660

### CODE REVIEW

**Comment by Vogtinator** [comment]
Verification run?

**Comment by DrMullings** [comment]
Is pretty difficult as the scenario keeps failing before the affected module

**Comment by DrMullings** [comment]
https://openqa.suse.de/tests/3221776
https://openqa.opensuse.org/tests/1000667

**Comment by DrMullings** [comment]
Lets see:
https://openqa.suse.de/tests/3224700

**Comment by DrMullings** [comment]
still not able to get a verification run working

**Comment by Vogtinator** [comment]
Your test has a broken `PRODUCTDIR` setting.

**Comment by DrMullings** [comment]
Apparently you cannot use the git-refspec clone on a job that has been cloned that way

**Comment by DrMullings** [comment]
We have now at least one verification run:
https://openqa.opensuse.org/tests/1002128#

**Comment by Vogtinator** [comment]
> We have now at least one verification run:
> https://openqa.opensuse.org/tests/1002128#

And that one shows that it does not work as it should - it uses `kernel-default` anyway as it's overwritten in line 27: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8100/files#diff-0f17e14131e2124422eb8b917e56bd95R27

That's not a fault of this PR though, it simply never worked...

**Comment by DrMullings** [comment]
https://openqa.opensuse.org/tests/1002129#step/kdump_and_crash/22
This looks better in that matter

**Comment by Vogtinator** [comment]
> https://openqa.opensuse.org/tests/1002129#step/kdump_and_crash/22
> This looks better in that matter

Indeed, LGTM

**Comment by DrMullings** [comment]
@foursixnine please revisit

**Comment by ostruzina** [comment]
It would seem that this change might be breaking QAM tests:
https://openqa.suse.de/tests/3230551#step/kdump_and_crash/136

**Comment by DrMullings** [comment]
@ostruzina why is getting two kernel names back?

**Comment by Vogtinator** [comment]
@DrMullings On SLE there's a "kernel-default-extra" package with additional modules available, which appears to own the /lib/modules/... directory as well...

So maybe `rpm -qf /boot/initrd-$(uname -r)` is a better fit here.

**Comment by DrMullings** [comment]
Thanks for the quick answer, fix is on the way before lunchtime then

**Comment by DrMullings** [comment]
Created:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8174


Verifications look good

**Pull request merged**
