### PR TITLE
Change naming convention of qesap regression settings

### PR DESCRIPTION
**Pull request by mpagot**
Enforce naming convention for settings used in qesap regression testing.

Verification
- http://openqaworker15.qa.suse.cz/tests/184653
- http://openqaworker15.qa.suse.cz/tests/185060
-  http://openqaworker15.qa.suse.cz/tests/185061

### CODE REVIEW

**Review by BillAnastasiadis — APPROVED** [review]
LGTM

**Comment by lilyeyes** [comment]
Oops. I merged my PR (https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17185) as you mentioned in daily meeting that your comments will not block it's merger.  So there is `This branch has conflicts that must be resolved` now in your PR now.

Another thing: If you use `get_required_var` here you need to set `QESAPDEPLOY_USE_SAPCONF` in job templates accordingly.
Also 'data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml' is using `USE_SAPCONF` it needs to update too.

FYI:
```
localhost:/var/lib/openqa/tests/sle # grep -r USE_SAPCONF

data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml:    SAPCONF: "%USE_SAPCONF%"
tests/sles4sap/qesapdeployment/configure.pm:    $variables{USE_SAPCONF} = get_required_var('USE_SAPCONF');
tests/sles4sap/publiccloud/qesap_terraform.pm:# USE_SAPCONF - (true/false) set 'false' to use saptune
tests/sles4sap/publiccloud/qesap_terraform.pm:        push @hana_playbook_list, 'pre-cluster.yaml', 'sap-hana-preconfigure.yaml -e use_sapconf=' . set_var_output('USE_SAPCONF', 'true');
```

**Comment by mpagot** [comment]
> Also 'data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml' is using USE_SAPCONF so it needs to update too.

For qesap regression testing, by design, names in the conf.yaml template are decoupled from settings names. No need to adapt conf.yaml.

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Pull request merged**
