### PR TITLE
LTP: Add LTP_COMMAND_EXCLUDE variable

### PR DESCRIPTION
**Pull request by richiejp**
The inverse of LTP_COMMAND_PATTERN; any command whose name matches this
pattern will not be run even if it matches LTP_COMMAND_PATTERN. This reduces
the complexity of the regular expressions required to black list tests.

### CODE REVIEW

**Comment by coolo** [comment]
so how far away is having new LTP runner in production?

**Comment by richiejp** [comment]
I have configured it on a test instance, see:
https://progress.opensuse.org/issues/15040

At this stage I will quite happily start configuring it on the main suse.de instance, I could have done it a while ago, but I am bit unsure about where I stand with that. I just need someone to comment on that Progress issue. I also need to be granted admin access to do it on opensuse.com. Alternatively someone else could do it by viewing my test instance configuration and reading the PODs inside the test modules. I don't mind either way, but due to the vast number of LTP tests and the number of scenarios we want to run it in, anyone who configures it needs to be careful not to fall into a combinatorial trap.

There could be a lot more development related to LTP runner though, some of the tests have special requirements which requires significantly more work, but we can run a lot of tests now. We just need to work through enabling the tests and see what is required.

**Comment by coolo** [comment]
the progress item is private?

**Comment by richiejp** [comment]
Apparently it is in our teams private area and I can not move it out without breaking our milestones. At any rate I have started running the LTP on o3 so it is a bit redundant now.

**Comment by okurz** [comment]
@richiejp you could create a ticket in https://progress.opensuse.org/projects/openqatests/issues and link it to https://progress.opensuse.org/issues/15040
I already proposed the idea to schlad to have milestones in progress.o.o which have a strict cadence of 6 weeks and bind tickets to that. Worrying about "breaking milestone binding" of tickets should be the least of our concerns. In the end, when working with openQA or relying on it - at least on osd or o3 - you must not forget about https://progress.opensuse.org/projects/openqatests/. suseqa can be used for the high-level plan.

**Comment by richiejp** [comment]
You are probably right assuming we can't just make suseqa at least internally accessible, I have told Sebastian my opinion and it seems it might need to be discussed further. This is quite off-topic though, I'm not sure if this hasn't been merged yet because of this discussion or if there is an issue with me doing too many small pull requests or there is some technical issue or no reason in particular?

**Pull request merged**
