### PR TITLE
Add missing packages to the ay multipath profile

### PR DESCRIPTION
**Pull request by rwx788**
Fixes https://openqa.suse.de/tests/3244310#
[Verification run](http://f174.suse.de/tests/287#step/installation/5). Fails on https://bugzilla.suse.com/show_bug.cgi?id=1146501

### CODE REVIEW

**Comment by jknphy** [comment]
Is it the same issue seen in multiple test suites in sle-15-sp2? Should we add this change to all of them? I created https://bugzilla.suse.com/show_bug.cgi?id=1146494 but maybe the problem is in our side, WDYT?

**Comment by rwx788** [comment]
> Is it the same issue seen in multiple test suites in sle-15-sp2? Should we add this change to all of them? I created https://bugzilla.suse.com/show_bug.cgi?id=1146494 but maybe the problem is in our side, WDYT?

There are only 2 profiles affected, I've created PR for both. Second one is on the aytests repo.

**Comment by jknphy** [comment]
> > Is it the same issue seen in multiple test suites in sle-15-sp2? Should we add this change to all of them? I created https://bugzilla.suse.com/show_bug.cgi?id=1146494 but maybe the problem is in our side, WDYT?
> 
> There are only 2 profiles affected, I've created PR for both. Second one is on the aytests repo.

I found this two for your change: https://openqa.suse.de/tests/3244310#step/installation/31, https://openqa.suse.de/tests/3244009#step/installation/34, for tftp this one https://openqa.suse.de/tests/3244149#step/installation/37 that we could add and the rest is about repos (as the service is missing), right?:
https://openqa.suse.de/tests/3244087#step/installation/43
https://openqa.suse.de/tests/3244024#step/installation/43
https://openqa.suse.de/tests/3248589#step/installation/11

**Comment by rwx788** [comment]
> > > Is it the same issue seen in multiple test suites in sle-15-sp2? Should we add this change to all of them? I created https://bugzilla.suse.com/show_bug.cgi?id=1146494 but maybe the problem is in our side, WDYT?
> > 
> > 
> > There are only 2 profiles affected, I've created PR for both. Second one is on the aytests repo.
> 
> I found these two for your change: https://openqa.suse.de/tests/3244310#step/installation/31, https://openqa.suse.de/tests/3244009#step/installation/34, for tftp this one https://openqa.suse.de/tests/3244149#step/installation/37 that we could add and the rest is about repos (as the service is missing), right?:
> https://openqa.suse.de/tests/3244087#step/installation/43
> https://openqa.suse.de/tests/3244024#step/installation/43
> https://openqa.suse.de/tests/3248589#step/installation/11

I need to take closer look to this kdump service issue. As for tftp, I've already created PR: https://github.com/yast/aytests-tests/pull/146 It's in aytest repo.


And nice catch with https://openqa.suse.de/tests/3244009# I've missed that one, will add change to that profile in this PR. Thanks!

**Pull request merged**
