### PR TITLE
Extract all version related function from utils to separate module

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by asmorodskyi** [comment]
A lot of work need to be done here , so before invest this time want to gather early feedback if there is sense at all .
So @okurz , @coolo , @DimStar77 , @Soulofdestiny , @kravciak , basically all reviewers :) because this touch everything . What do you think ?

**Comment by coolo** [comment]
I don't mind

**Comment by asmorodskyi** [comment]
proof runs :
- http://kimball.arch.suse.de/tests/316
- http://kimball.arch.suse.de/tests/315
Both failing actually but failures can't be related to this PR. Actually because it is just refactoring travis check which is doing `make test` is enough

**Comment by asmorodskyi** [comment]
So who is brave enough to merge this ? :) ( I am but unfortunately I can't :D )

**Comment by okurz** [comment]
LGTM. Please rebase, fix conflicts and ping me to expedite the merge before another conflict appears which is more likely for changes which cover so many files.

**Comment by asmorodskyi** [comment]
Done , will come to you when I will get to the office :) Or you can just merge this without me I don't mind :)

**Pull request merged**
