### PR TITLE
Don't use virtio-terminal on architectures other than x86_86

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by richiejp** [comment]
The problem is not specifically with qa_run: https://progress.opensuse.org/issues/18980

I have disabled virtio console on ppc64le again, so it shouldn't be an issue until it next gets enabled :-)

**Comment by okurz** [comment]
I don't see the point of this PR. I guess @richiejp made a good point. Why should the architecture or the test module be specific in this regard?

**Comment by mimi1vx** [comment]
@okurz point is very simple .. only on x86_64 virtio console works now correctly.

**Comment by sysrich** [comment]
If virtio console only works on x86_64, what is the bug id for that problem? We (SUSE) ship qemu with virtio_console to customers, they probably expect it to work. @mimi1vx do you have an eta as to when a fix for virtio_console will get through QAM for SLE 12 SP2?

**Comment by mimi1vx** [comment]
@sysrich virtio_console works , but not start automatically on SLE12/SLE12SP1 and  systemd by default don't start on another consoles than first (ended with 0) as I mention in  https://progress.opensuse.org/issues/18980

**Comment by coolo** [comment]
that's a product bug then - and should be handled like that by not scheduling the variable on the product/machine combination with the bug. This PR is wrong IMO - and others seem to agree, so closing

**Pull request closed without merging**
