### PR TITLE
Fix "Add some API for Xen command-line" patch

### PR DESCRIPTION
**Pull request by wjn740**
Fix compat_args function wasn't exported.

### CODE REVIEW

**Comment by wjn740** [comment]
@pevik @mloviska Please take a look at this version.

**Comment by mloviska** [comment]
At first glance, I cannot see any issue, but let's be sure and let's run several VRs.
Would you mind cloning https://openqa.suse.de/tests/3455514, please?

**Comment by wjn740** [comment]
@mloviska, No problem.

**Comment by wjn740** [comment]
http://10.67.134.217/tests/6026

Haven't finished, but it is passed, on the previous failed step.

**Comment by mloviska** [comment]
> http://10.67.134.217/tests/6026
> 
> Haven't finished, but it is passed, on the previous failed step.

Yup, that is enough. Thanks a lot @wjn740

**Comment by wjn740** [comment]
@asmorodskyi Please give a merge at the next merge window.

**Pull request merged**
