### PR TITLE
CaaSP can't use zypper install

### PR DESCRIPTION
**Pull request by kravciak**
Fix for: https://openqa.opensuse.org/tests/604987#step/docker/6
Local runs:
 - http://dhcp91.suse.cz/tests/1356 - DVD
 - http://dhcp91.suse.cz/tests/1355 - Kubic - fails on valid bug

### CODE REVIEW

**Comment by nicksinger** [comment]
LGTM

**Comment by kravciak** [comment]
There is no such role in CaaSP for now (thanks for wiki link, we did not know about this)
We don't have test for MicroOS role, so maybe we can merge this for now (and modify when adding microos role test)

**Comment by sysrich** [comment]
> There is no such role in CaaSP for now

Are you sure? it's most certainly in the CaaSP Master control.xml file

https://github.com/yast/skelcd-control-CAASP/blob/master/control/control.CAASP.xml#L451

was added a month ago by Thorsten, at the direct request of SUSE Product Management

I had to adjust Kubic to rename SUSE-MicroOS to openSUSE-MicroOS, so I'd be very surprised if it hasn't made its way into the CaaSP product yet

**Comment by kravciak** [comment]
I'm sure - latest image: https://openqa.suse.de/tests/1458707#step/oci_role/1

**Comment by sysrich** [comment]
oh crap..I just read why you're doing this change.. dude..it's not necessary; even if we accept it, the tests will still fail, because all of the -kubic packages are broken..like you found

That's why i'm fixing them:

https://build.opensuse.org/request/show/574254
https://build.opensuse.org/request/show/574253
https://build.opensuse.org/request/show/574252
https://build.opensuse.org/request/show/574251

So..we can merge this (with the knowledge we'll need to come back and fix it v. soon for the MicroOS system-role).. but the tests will still fail because the missing provides

Or we can just wait for my SR's to end up in Kubic -  which should mean the zypper in docker will become an noop

What do you think?

**Comment by kravciak** [comment]
I updated main.pm to skip docker tests for MicroOS role - that should be enough to keep openQA failing on product bug, and not trying "zypper in".

**Comment by sysrich** [comment]
Thanks! and thanks for putting up with my questions..busy day today

**Pull request merged**
