### PR TITLE
Mitigations funtion test  adaption for hvm and pv

### PR DESCRIPTION
**Pull request by museQi**
Modify the xen_domu_mitigation_test.pm file to adapt the function test of mitigations on xen hypervisor(hvm and pv)
machine include:skylake,icelake,haswell,cascadelake
About the cross_cases_on_spec-ctrl_yes is a bug. Refer to:https://bugzilla.suse.com/show_bug.cgi?id=1205618
- Verification run: 
http://10.67.129.4/tests/57335#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57320#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57345#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57346#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57326#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.4/tests/57325#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.7/tests/1864#step/cross_cases_on_spec-ctrl_yes/1
http://10.67.129.7/tests/1866#step/cross_cases_on_spec-ctrl_yes/1

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @zyuhu  Please help me review.

**Comment by zyuhu** [comment]
LGTM

**Comment by XGWang0** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse Please help me review and merge.Thanks.

**Pull request merged**
