### PR TITLE
Make test module to export results in xml

### PR DESCRIPTION
**Pull request by b10n1k**
Refactor test module to export the results in xml and make use of the xml representation in OpenQA.

Signed-off-by: Ioannis Bonatakis <ybonatakis@suse.com>

- Verification run: http://aquarius.suse.cz/tests/12251

### CODE REVIEW

**Review by foursixnine — COMMENTED** [review]
You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...

**Comment by b10n1k** [comment]
> You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...

Do you have a link to take a look? thing is that this approach is already used in another HPC module. i just try to abstracted to reuse it wherever

**Comment by foursixnine** [comment]
> > You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...
> 
> Do you have a link to take a look? thing is that this approach is already used in another HPC module. i just try to abstracted to reuse it wherever

[    parse_extra_log(TAP => $tap_results);](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/afff37a3fc28da190070e15f8f481b0baf2c665b/tests/console/sqlite3.pm#L42)

and here's an example of the tap output: 

file: https://openqa.suse.de/tests/9601745/file/sqlite3-results.tap, is represented like: https://openqa.suse.de/tests/9601745 (see at the end)

**Comment by b10n1k** [comment]
> > > You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...
> > 
> > 
> > Do you have a link to take a look? thing is that this approach is already used in another HPC module. i just try to abstracted to reuse it wherever
> 
> [ parse_extra_log(TAP => $tap_results);](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/afff37a3fc28da190070e15f8f481b0baf2c665b/tests/console/sqlite3.pm#L42)
> 
> and here's an example of the tap output:
> 
> file: https://openqa.suse.de/tests/9601745/file/sqlite3-results.tap, is represented like: https://openqa.suse.de/tests/9601745 (see at the end)...
> 
> File is fairly simple: https://testanything.org
> 
> ```
> 1..4
> ok 1 - Input file opened
> not ok 2 - First line of the input valid
> ok 3 - Read the rest of the file
> not ok 4 - Summarized correctly # TODO Not written yet
> ```

i took a look. From my understanding this will require to implement a different design of the module to produce the TAP output. I think this is different concept here. What we need is the openqa results which it would be represent even without TAP format. But thanks for alternative idea

**Comment by foursixnine** [comment]
> > > > You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...
> > > 
> > > 
> > > Do you have a link to take a look? thing is that this approach is already used in another HPC module. i just try to abstracted to reuse it wherever
> > 
> > 
> > [ parse_extra_log(TAP => $tap_results);](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/afff37a3fc28da190070e15f8f481b0baf2c665b/tests/console/sqlite3.pm#L42)
> > and here's an example of the tap output:
> > file: https://openqa.suse.de/tests/9601745/file/sqlite3-results.tap, is represented like: https://openqa.suse.de/tests/9601745 (see at the end)...
> > File is fairly simple: https://testanything.org
> > ```
> > 1..4
> > ok 1 - Input file opened
> > not ok 2 - First line of the input valid
> > ok 3 - Read the rest of the file
> > not ok 4 - Summarized correctly # TODO Not written yet
> > ```
> 
> i took a look. From my understanding this will require to implement a different design of the module to produce the TAP output. I think this is different concept here. What we need is the openqa results which it would be represent even without TAP format. But thanks for alternative idea

Your last changes look much better :)

**Comment by b10n1k** [comment]
> > > > > You could also use TAP, like it's done in the SQLite tests, which would be much easier to parse and generate...
> > > > 
> > > > 
> > > > Do you have a link to take a look? thing is that this approach is already used in another HPC module. i just try to abstracted to reuse it wherever
> > > 
> > > 
> > > [ parse_extra_log(TAP => $tap_results);](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/afff37a3fc28da190070e15f8f481b0baf2c665b/tests/console/sqlite3.pm#L42)
> > > and here's an example of the tap output:
> > > file: https://openqa.suse.de/tests/9601745/file/sqlite3-results.tap, is represented like: https://openqa.suse.de/tests/9601745 (see at the end)...
> > > File is fairly simple: https://testanything.org
> > > ```
> > > 1..4
> > > ok 1 - Input file opened
> > > not ok 2 - First line of the input valid
> > > ok 3 - Read the rest of the file
> > > not ok 4 - Summarized correctly # TODO Not written yet
> > > ```
> > 
> > 
> > i took a look. From my understanding this will require to implement a different design of the module to produce the TAP output. I think this is different concept here. What we need is the openqa results which it would be represent even without TAP format. But thanks for alternative idea
> 
> Your last changes look much better :)

Thats why it was a drafted. i was waiting another PR with related changes before finish with it. Thanks again @foursixnine

**Review by schlad — APPROVED** [review]
This looks imho very good; It is nicely abstracting some steps.

**Pull request merged**
