### PR TITLE
15sp4teradata virtulization tests

### PR DESCRIPTION
**Pull request by tbaev**
- Related ticket: https://progress.opensuse.org/issues/131504
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1648
- Verification run: 
- 
[15SP4TD_XEN](http://openqa.qam.suse.cz/tests/59300#dependencies)
[15SP4TD_KVM](http://openqa.qam.suse.cz/tests/59318#dependencies)
[15SP4TD_migrationKVM](http://openqa.qam.suse.cz/tests/59278#dependencies)
[15SP4TD_migrationXEN](http://openqa.qam.suse.cz/tests/59299#dependencies) know issue for migration [bugzilla#1212964](https://bugzilla.suse.com/show_bug.cgi?id=1212964)
[HyperV](https://openqa.suse.de/tests/11904301)
[VMware](https://openqa.suse.de/tests/11904302)

### CODE REVIEW

**Comment by Julie-CAO** [comment]
LGTM

**Comment by RoyCai7** [comment]
LGTM

**Comment by varunkojha** [comment]
it seems like these changes are specific to enabling testing for SLES 15 SP4 on Teradata platforms using virtualization. The profiles, filtering logic, and OS information generation are all customized to specific testing scenarios :+1: 

maybe we can add more info for the autoyast, Looks good to me thanks

**Comment by tonyyuan1** [comment]
There is very simple and easy way to do this. I just updated the ticket with detail. Please check.

**Comment by tbaev** [comment]
After a discussion with Tony and Julie, I have created a new PR and will close this one. 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17672

The branch with be kept it may be useful in the future.

**Pull request closed without merging**
