### PR TITLE
Change main.pm for sle12 for boot_to_snapshot test pr  #1060

### PR DESCRIPTION
**Pull request by MalloZup**
PR: #1060

### CODE REVIEW

**Comment by okurz** [comment]
Please update the commit message. It should start with capital letter but this is not the main point. "change" is not a good subject. Better describe the impact of your change, e.g. as simple as

    Add boot_to_snapshot test

**Comment by sysrich** [comment]
I disagree - I fixed the capital letter but seriously, we don't need to nitpick such changes

"change main.pm for sle12 for boot_to_snapshot test pr#1060" makes perfect sense to me

As a native english speaker I might change it to "change sle12 main.pm to add boot_to_snapshot test" and only mention the PR# in the PR comment

But I would NOT use "Add boot_to_snapshot test" - that was a suitable commit comment for PR 1060 which actually added the test.. this is altering the main.pm, the commit message is accurate.

**Comment by okurz** [comment]
Right, maybe "Enable boot_to_snapshot test" might also work. In my personal experience developers often enough just stated something like "Change <this> to <that>" without looking at the history which said "Change <that> to <this>" without stating what the intention of the change is. This does *not* apply to the current commit message, though.

**Comment by sysrich** [comment]
Yeah, 'enable' is a better word in this case

I propose "enable boot_to_snapshot test in sle12 main.pm" would be a perfect commit message for this PR

But I don't mind the current one

**Comment by MalloZup** [comment]
i didn't get it guys .. .what you want ? :)

**Comment by MalloZup** [comment]
ok,  for me , you can  merge the PR in the big soup :)

**Comment by okurz** [comment]
thanks for renaming

**Pull request merged**
