### PR TITLE
Split upstream testsuites from extratests

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket:
https://progress.opensuse.org/issues/52859
https://confluence.suse.com/display/~vpelcak/Testsuite+Split
- Verification run:
http://10.100.12.155/tests/13562 15sp1 extratests
https://openqa.suse.de/tests/3487460 15sp1 extratests zkvm
https://openqa.suse.de/tests/3487461 15sp1 extratests
https://openqa.suse.de/tests/3486879 12sp4 extratests
http://10.100.12.155/tests/13570 15sp1 openldap2
http://10.100.12.155/tests/13567 15sp1 bind

### CODE REVIEW

**Comment by coolo** [comment]
Is it really necessary to duplicate mau-bind.yaml between service packs? Or files that are all the same in general. WDYT @rwx788 ?

**Comment by coolo** [comment]
incomplete: https://openqa.suse.de/tests/3486877/file/autoinst-log.txt

**Comment by dzedro** [comment]
> Is it really necessary to duplicate mau-bind.yaml between service packs? Or files that are all the same in general. WDYT @rwx788 ?
I don't like it too, I would just put outside VERSION directory yamls that are same for all versions

**Comment by coolo** [comment]
So create a qam/common ?

**Comment by dzedro** [comment]
> > Is it really necessary to duplicate mau-bind.yaml between service packs? Or files that are all the same in general. WDYT @rwx788 ?
> 
> I need to make diff of those to see how different those are. But this is again main challenge here is to understand why we have different set of test modules and act on the root cause.

yaml files in common are same for all versions

**Pull request merged**
