### PR TITLE
Autoyast profile for bsc#968346

### PR DESCRIPTION
**Pull request by psladek**
- test for LVM_LV_CREATE_FAILED -4014 issue, 
   bsc#968346

### CODE REVIEW

**Comment by okurz** [comment]
hi, did you think about creating autoyast profiles based on openSUSE Tumbleweed instead or additionally?

Also, where is this profile used?

**Comment by asmorodskyi** [comment]
@psladek  no activity for 2 month , is it still relevant ?

**Comment by mnowaksuse** [comment]
I think we should rather go with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2489 (waiting for the LVM fix being implemented).

**Comment by okurz** [comment]
fine

**Pull request closed without merging**
