### PR TITLE
GraphicksMagick: Fix wrong base class assuming cleared console

### PR DESCRIPTION
**Pull request by okurz**
Verification run:

```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9209 https://openqa.opensuse.org/tests/1118210
```

Created job #1118329: opensuse-Tumbleweed-DVD-x86_64-Build20191218-zdup-Leap-15.0-gnome@64bit_cirrus -> https://openqa.opensuse.org/tests/1118931

### CODE REVIEW

**Comment by okurz** [comment]
Verification run pending

**Comment by ilausuch** [comment]
Thanks @okurz

**Comment by StefanBruens** [comment]
You need another "alt-f4" after "exit\n" to close the terminal window.

**Comment by ilausuch** [comment]
It is failing, maybe the problem is the final command?

type_string "exit\n";

**Comment by okurz** [comment]
updated, new verification run: https://openqa.opensuse.org/tests/1118931

**Comment by ilausuch** [comment]
GraphicsMagick now pass in the test https://openqa.opensuse.org/tests/1118931

**Pull request merged**
