### PR TITLE
Change long tag name into shorter name

### PR DESCRIPTION
**Pull request by Zaoliang**
- use now shorter name for needle tag as following: 
yast2_apparmor_file_permissions_read, yast2_apparmor_file_permissions_write
yast2_apparmor_dir_permissions_read, yast2_apparmor_dir_permissions_write

### CODE REVIEW

**Comment by rwx788** [comment]
Am I right, that we are not sure if this is the issue? And do we have needles already merged?

**Comment by Zaoliang** [comment]
@rwx788 The real problem was the last merge was not successful. And I change the tag name since you and others are not happy with long tag name...

**Comment by rwx788** [comment]
@Zaoliang so are needles already there and we can simply merge this one? As I don't see any relevant commit for needles. Could you please create relevant PR for needles, as we need to merge both things.

**Comment by Zaoliang** [comment]
@rwx788 already talked to Oliv yesterday, please just merge it. For needles I created another PR for openSUSE: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/247

**Comment by Zaoliang** [comment]
Please check PR for SLES as well: 
https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/434

**Comment by rwx788** [comment]
Please, put needles PR reference here to avoid this kind of discussions. 
@okurz Could you please merge needles for SLE, as I don't have permissions there.

**Pull request merged**
