### PR TITLE
zypper_lifecycle: Improve regex matching

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
poo: https://progress.opensuse.org/issues/26080
verification: opeth.suse.de/tests/5829#step/zypper_lifecycle/57

**Comment by Soulofdestiny** [comment]
@okurz

**Comment by okurz** [comment]
will be replaced by other PR, standby

**Comment by okurz** [comment]
Replaced by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3877

**Pull request closed without merging**
