### PR TITLE
split userspace into pieces for easy review

### PR DESCRIPTION
**Pull request by SeroSun**
Because different testcase have different bugs. For better mark them in different bugs, I split userspace_1, userspace_2, userspace_3 and userspace_4 into pieces.

### CODE REVIEW

**Comment by coolo** [comment]
Cool! you finally saw the light ;)

**Comment by SeroSun** [comment]
Yes, finally  lol

**Comment by coolo** [comment]
I will try to deploy this with a script - and you please review afterwards

**Comment by SeroSun** [comment]
I'll say no problem.
Thanks to merge it so fast.

**Comment by coolo** [comment]
do you want  all of them for 64bit and ppc64le?

**Pull request merged**
