### PR TITLE
Report fallback CA

### PR DESCRIPTION
**Pull request by grisu48**
In case the distribution for the SUSE CA is not yet published and we fallback to SLE-Factory, report it explicitly with record_info.

- Follow-up of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20424
- Verification run: [SLEM 5.5](https://openqa.suse.de/tests/15738956) | [SLEM 6.1](https://openqa.suse.de/tests/15738957) | [SLE15-SP6](https://openqa.suse.de/tests/15738958) | [CentOS](https://openqa.suse.de/tests/15738959)

### CODE REVIEW

**Review by m-dati — APPROVED** [review]

**Comment by mloviska** [comment]
I lack to see the value of making this information verbose. At the end we all the certificates are the same, just the link differs, and it doesn't matter for the test whether they come from repo for SP6 or a generic one.

**Comment by grisu48** [comment]
> I lack to see the value of making this information verbose. At the end all the certificates are the same, just the link differs, and it doesn't matter for the test whether they come from repo for SP6 or a generic one.

Especially for newer build we often need to poke some people so that they enable it in this repository. Making it visible that the build is missing helps us to poke the right people to make it happen.

**Comment by m-dati** [comment]
Only to mention: I opened a discussion on certificates in [this channe](https://suse.slack.com/archives/C02CBB35W5B/p1728989561633289?thread_ts=1728924896.947509&cid=C02CBB35W5B), where distri-differences were considered not a much relevant, but a clearer report of it may be useful.

**Comment by mloviska** [comment]
> Only to mention: I opened a discussion on certificates in [this channel](https://suse.slack.com/archives/C02CBB35W5B/p1728989561633289?thread_ts=1728924896.947509&cid=C02CBB35W5B), where distri-differences were considered not much relevant, but a clear report of it may be useful.

I would stick to what was Marcus said, the CA is the same for the whole product series. In this particular setup, it will be a red herring outside SLE-15-SPx and one does need to know certain background information in order to handle this informative record_info.

Also, it will be simply another green info box that won't make reviewers without additional information to take any actions.

**Comment by grisu48** [comment]
Agreed, probably not worth it. Closing now.

**Pull request closed without merging**
