### PR TITLE
JeOS changes to shibboleth and posgres tests

### PR DESCRIPTION
**Pull request by mnowaksuse**
- Install packages missing in JeOS
- Change `$cwd` when running command via sudo

### CODE REVIEW

**Comment by mnowaksuse** [comment]
@rwmanos FYI.

**Comment by rwmanos** [comment]
@mnowaksuse well done and thanks for bringing this PR to my attention. Feel free to take over the Maintainer field if you want!

**Comment by rwmanos** [comment]
I looked it again and I'm not sure installing apache2 will fix it. The 'shibboleth' test runs after the 'http_srv' test which has already installed apache2. This is true for your failed test as well.
I see 2 issues (1 new!):
- a2enmod seems to not exist in JeOS version(?)
- `type_string "a2enmod shib"; ` is missing a `\n` !!! I don't know how I missed that, sorry.
Existing tests [1] pass because this doesn't seem to be actually needed (mod enabled by default). Maybe you can remove it?
[1] https://openqa.suse.de/tests/627963#step/shibboleth/7

**Comment by rwmanos** [comment]
I really don't get it why http://assam.suse.cz/tests/4101#step/shibboleth/7 succeeds and https://openqa.suse.de/tests/627948#step/shibboleth/5 fails. Both are obviously wrong but the only difference is that sudo is installed in the first.

**Comment by mnowaksuse** [comment]
Thanks for spotting `a2enmod`! I added `assert_script_run` as in the `a2enmod` script has code paths which might exit with non-zero exit code. If `a2enmod` is needed at all, I know nothing about :), just fixing stuff unrelated to the core of the test. Though:
```
assam:~ # /usr/sbin/a2enmod -l | grep shib
assam:~ # a2enmod shib
assam:~ # /usr/sbin/a2enmod -l | grep shib
actions alias auth_basic authn_file authz_host authz_groupfile authz_core authz_user autoindex cgi dir env expires include log_config mime negotiation setenvif ssl socache_shmcb userdir reqtimeout authn_core headers proxy proxy_http proxy_wstunnel shib
```
The difference between those two jobs is that `postgresql94server` did not fail in the former, hence snapshot snapshot made by `sshd` test (i.e. one without `apache2` installed) was not loaded, therefore we should install `apache2` in the test itself to stay on the safe side.

**Comment by rwmanos** [comment]
I was aware about snapshots but I didn't know they were used that often. Thanks for explaining it and for fixing the code :+1:

**Pull request merged**
