### PR TITLE
Workaround bsc#1159950

### PR DESCRIPTION
**Pull request by ldevulder**
bsc#1159950 (gnome-session-failed is detected) can happens on *big* hardware with lot of cpus/memory.

This commit adds a workaround for this issue.

- Related ticket: N/A
- Needles: Already done in o.s.d. (was needed to be able to run the verification test).
- Verification run: https://openqa.suse.de/t4746387
- Regression test: http://1b210.qa.suse.de/tests/7448

**Note:** the failure in `wizard_hana_install` is not related to this PR. It looks like as if screensaver is activated (see the reducing gamma [here](https://openqa.suse.de/tests/4744503#step/wizard_hana_install/40)). This issue will be addressed in another PR.

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by okurz — APPROVED** [review]
thank you for doing this workaround

**Review by alvarocarvajald — APPROVED** [review]
LGTM. Love `oh-no-something-has-gone-wrong` as a needle tag :P

**Review by juadk — APPROVED** [review]
LGTM :+1:

**Pull request merged**
