### PR TITLE
Change guest list to the required guest list for kvm and xen 

### PR DESCRIPTION
**Pull request by martinsmarcelo**
MU- Change guest list to the required guest list for kvm and xen on each host product.

- Related ticket: https://progress.opensuse.org/issues/162434
- Verification run: 
SLES15-SP6 KVM - http://openqa.qam.suse.cz/tests/76235#step/waitfor_guests/68
SLES15-SP6 XEN - http://openqa.qam.suse.cz/tests/76251#step/waitfor_guests/102
SLES15-SP5 KVM - http://openqa.qam.suse.cz/tests/76288#step/waitfor_guests/90
SLES15-SP5 XEN - http://openqa.qam.suse.cz/tests/76300#step/waitfor_guests/210
SLES 15-SP4 KVM - http://openqa.qam.suse.cz/tests/76377#step/waitfor_guests/66
SLES 15-SP4 XEN - http://openqa.qam.suse.cz/tests/76364#step/waitfor_guests/70

### CODE REVIEW

**Comment by guoxuguang** [comment]
LGTM

**Comment by alice-suse** [comment]
@martinsmarcelo Thanks for the fix! 
I had a comparison with the expected matrix page, it seems all are matching, except that on sle15sp4 kvm and xen host, sle12sp5 shall be dropped too. Please make a double check.

**Review by alice-suse — CHANGES_REQUESTED** [review]
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19591#issuecomment-2186297233.

**Comment by martinsmarcelo** [comment]
> @martinsmarcelo Thanks for the fix! I had a comparison with the expected matrix page, it seems all are matching, except that on sle15sp4 kvm and xen host, sle12sp5 shall be dropped too. Please make a double check.

Ok, I comple a double check and commit . Thank you

**Comment by RoyCai7** [comment]
LGTM

**Comment by alice-suse** [comment]
@martinsmarcelo Code looks good. Will be nice to have sle15sp4 host verification job.

**Review by alice-suse — APPROVED** [review]

**Comment by tbaev** [comment]
LGTM, thank you Marcelo

**Comment by martinsmarcelo** [comment]
> @martinsmarcelo Code looks good. Will be nice to have sle15sp4 host verification job.

SLES 15-SP4
kvm - http://openqa.qam.suse.cz/tests/76377#step/waitfor_guests/66
xen - http://openqa.qam.suse.cz/tests/76364#step/waitfor_guests/70

**Pull request merged**
