### PR TITLE
Fix regex for health-checker

### PR DESCRIPTION
**Pull request by mloviska**
- failure: [ALP](https://openqa.opensuse.org/tests/2842805#step/journal_check/20)
- Verification run: [alp-0.1-kvm-x86_64](https://openqa.opensuse.org/t2868588)

### CODE REVIEW

**Comment by Vogtinator** [comment]
What's actually broken here? For Tumbleweed the text is identical and it matches the regex just fine (https://openqa.opensuse.org/tests/2867851).

**Comment by mloviska** [comment]
> What's actually broken here? For Tumbleweed the text is identical and it matches the regex just fine (https://openqa.opensuse.org/tests/2867851).

It didn't match in ALP unless escaped https://openqa.opensuse.org/tests/2861065#step/journal_check/20. 

Also according to [regex101.com](https://regex101.com/r/YPBmnq/1) it doesn't work :shrug:

**Comment by mloviska** [comment]
> Right, the issue is a conflict with the delimiters:
> 
> ```
> if ($line =~ /$bug_pattern->{$bug}->{description}/)
> ```
> 
> Maybe it works better like this?
> 
> ```
> if ($line =~ $bug_pattern->{$bug}->{description})
> ```

good point, let me try. Thanks

**Comment by mloviska** [comment]
> Right, the issue is a conflict with the delimiters:
> 
> ```
> if ($line =~ /$bug_pattern->{$bug}->{description}/)
> ```
> 
> Maybe it works better like this?
> 
> ```
> if ($line =~ $bug_pattern->{$bug}->{description})
> ```

I guess it works
http://kepler.suse.cz/tests/19536#step/journal_check/20

**Review by Vogtinator — APPROVED** [review]

**Pull request merged**
