### PR TITLE
Revert "evolution_prepare_servers: use 'consoletest' as base to upload logs on failure"

### PR DESCRIPTION
**Pull request by dzedro**
Reverts os-autoinst/os-autoinst-distri-opensuse#8314

https://openqa.suse.de/tests/3308513#step/evolution_prepare_servers/70

### CODE REVIEW

**Comment by czerw** [comment]
@ggardet  could you please check this failure? seems to be related to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8314

**Comment by ggardet** [comment]
> @ggardet could you please check this failure? seems to be related to #8314

I do not have access to openqa.suse.de Could you tell me more about the failure, please?

**Comment by dzedro** [comment]
the problem is that consoletest is expecting to end in console, but the test is ending in x11 if its not `DESKTOP=tesxtmode`
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/x11/evolution/evolution_prepare_servers.pm#L107

**Comment by czerw** [comment]
@dzedro Could you please share details to @ggardet ?

**Comment by ggardet** [comment]
> the problem is that consoletest is expecting to end in console, but the test is ending in x11 if its not `DESKTOP=tesxtmode`
> https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/x11/evolution/evolution_prepare_servers.pm#L107

Could we just drop L107?

**Comment by baierjan** [comment]
@ggardet No, L107 is not a problem, it is a solution to `DESKTOP=gnome` and such as the next test expects to be in the X11 unless `DESKTOP=textmode`. This tests (`evolution_prepare_servers`) is a part of a desktop tests, hence it cannot be based on consoletest.

**Comment by ggardet** [comment]
> @ggardet No, L107 is not a problem, it is a solution to `DESKTOP=gnome` and such as the next test expects to be in the X11 unless `DESKTOP=textmode`. This tests (`evolution_prepare_servers`) is a part of a desktop tests, hence it cannot be based on consoletest.

So, the solution would be to revert and add a call to `upload_logs` ?

**Comment by baierjan** [comment]
Yes, manually uploading the logs in case of failure is a viable solution.

**Comment by baierjan** [comment]
Offtopic: another solution would be to get rid of this and replace the code by supportserver.

**Comment by dzedro** [comment]
@ggardet 107 could be maybe moved into next test so the evolution_prepare_servers is plain `consoletest`

**Comment by dzedro** [comment]
but there are multiple tests that follow `evolution_prepare_servers`

**Pull request merged**
