### PR TITLE
Remove workaround

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by dzedro** [comment]
wow looot of work

**Comment by aaannz** [comment]
I assume that tidy was automated, what rules did you use? What about adding it to travis to enforce it?

**Comment by nilxam** [comment]
:+1:

**Comment by coolo** [comment]
I just ran os-autoinst's tidy

**Comment by coolo** [comment]
rebased

**Comment by sysrich** [comment]
Thanks!

**Pull request merged**
