### PR TITLE
Disable root ssh login on s390x for cc testing

### PR DESCRIPTION
**Pull request by Amrysliu**
We enable root ssh login when installing system on s390x, otherwise the
automation test will fail due to root can't login with ssh. But for CC
testing, disable root ssh login is a requirement. So we need to disable
it before running cc test cases.

Related: https://progress.opensuse.org/issues/105564
Verify run:
       https://openqa.suse.de/tests/8921615#   (audit_test)
       https://openqa.suse.de/tests/8921614#  (audit_test2)
       https://openqa.suse.de/tests/8921616#  (audit_remote)
       https://openqa.suse.de/tests/8921631#  (ipsec)
       https://openqa.suse.de/tests/8921621# (netfilter and netfilebt)
       https://openqa.suse.de/tests/8921962# (cc_atsec)

### CODE REVIEW

**Review by rfan1 — APPROVED** [review]
LGTM
Great job

**Review by lilyeyes — APPROVED** [review]
Generally looks good to me.

**Review by wangqianzou — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM :-)

**Pull request merged**
