### PR TITLE
Add test case for rsyslog server and client

### PR DESCRIPTION
**Pull request by QingmingSu**
This is a multi-machine test, which requires two nodes
with tap network for the rsyslog server and client.

### CODE REVIEW

**Comment by QingmingSu** [comment]
The test case has been verified by my local openQA.
For rsyslog-server:
http://147.2.212.224/tests/95

For rsyslog-client:
http://147.2.212.224/tests/96

**Comment by coolo** [comment]
That seems to overlap with the slenkins test https://openqa.suse.de/tests/687848#step/1__unknown_/6

**Comment by QingmingSu** [comment]
Yeah, seems rsyslog is already tested by slenkins. But I have no idea how to reuse the test code in slenkins.
How can I proceed in this situation? Any suggestion will be appreciated.

**Comment by coolo** [comment]
talk to @thehejik - to me it sounds easier to use your code in the various scenarios and replace the slenkins test suite. But I don't want to have duplicated tests (both test suites are very basic), so Thomas should agree.

**Comment by okurz** [comment]
what's the problem with the slenkins test suite for rsyslog? why not just keep the existing rsyslog test suite?

**Comment by QingmingSu** [comment]
@okurz - The problem is I have no idea how to involve the existing rsyslog test case of slekins in our FIPS testing. 
Currently in openQA, we create a hdd image with FIPS enabled, then run related test cases upon the hdd image. But it is a black-box for me now how to load the rsyslog test from slekins to the FIPS-ready hdd image.
Further more, rsyslog should be run with TLS enabled in FIPS testing, not sure whether TLS is setup or not in existing rsyslog test case of slekins.
I will study some documents of Slekins to see what I do next.

**Comment by thehejik** [comment]
I'm working on importing slenkins suites into FIPS subgroup - one of the testsuites will be rsyslogd. 

This commit will be useless soon. https://progress.opensuse.org/issues/16728

**Comment by QingmingSu** [comment]
@thehejik , Thanks for your update. Good to know that you are porting slenkins tests to openQA for FIPS validation. But please note that there is an known issue (bsc#1020063) on SLE12 sp3, which will block the FIPS test currently.
I'd like to close this PR to avoid duplicate test case in openQA.

**Comment by thehejik** [comment]
@QingmingSu yeah, I know about the issue, thanks

**Pull request closed without merging**
