### PR TITLE
gdb: Fix sporadic issues by waiting for (gdb) prompt

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/90557
Verification: http://kazhua.qa.suse.de/tests/overview.html?build=20210605%3Apoo90557&version=Tumbleweed&groupid=1&distri=opensuse

### CODE REVIEW

**Comment by punkioudi** [comment]
From the progress issue I can see that the issue happens in `Leap 15.3 ppc64le`, so could you provide the VRs for this case?
Also, `gdb` runs in plenty maintenance sle versions and architectures, in mau-extratests1 jobs (eg https://openqa.suse.de/tests/6200325#step/gdb/43), so it would be good to have also VRs for these cases :)

**Comment by asdil12** [comment]
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12665 https://openqa.opensuse.org/tests/1756002 SCHEDULE=tests/boot/boot_to_desktop,tests/console/gdb
Created job #1773615: opensuse-15.3-DVD-ppc64le-Build160.3-extra_tests_in_textmode@ppc64le -> https://openqa.opensuse.org/t1773615

**Comment by asdil12** [comment]
and for the mau jobs: http://kazhua.qa.suse.de/tests/overview.html?build=20210605%3Apoo90557_mau&version=15-SP2&distri=sle

**Review by punkioudi — COMMENTED** [review]
Looks nice!

**Pull request merged**
