### PR TITLE
Remove rstudio openQA tests

### PR DESCRIPTION
**Pull request by dcermak**
I lack the time to maintain the tests for rstudio properly.

### CODE REVIEW

**Comment by DimStar77** [comment]
Sad, but understandable

**Comment by okurz** [comment]
@os-autoinst/tests-maintainer any team willing to take over?

**Comment by dcermak** [comment]
@okurz Don't bother, rstudio will be probably gone from Factory soon as well, as I lack the time to keep it building.

**Comment by okurz** [comment]
fine

**Pull request merged**
