### PR TITLE
Containers: install runc instead of docker-runc for Leap

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/94054

### CODE REVIEW

**Comment by jlausuch** [comment]
VRs:
- [openSUSE jobs](https://openqa.opensuse.org/tests/overview?build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_fix_runc_installation&distri=opensuse) 
- [SLE Update jobs](https://openqa.suse.de/tests/overview?distri=sle&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_fix_runc_installation)

Known issues not related to the PR:
- [registry error](gh#containers/podman#10685)
- [validate_btrfs error](https://progress.opensuse.org/issues/93889)

**Comment by msmeissn** [comment]
lgtm

**Comment by mloviska** [comment]
Wondering if we should not change/drop this check also https://openqa.opensuse.org/tests/1789994#step/docker_runc/51

**Comment by jlausuch** [comment]
> Wondering if we should not change/drop this check also https://openqa.opensuse.org/tests/1789994#step/docker_runc/51

Good point. But to be honest, I don't know the reason for that check... It's probably because we want to test runc only and avoid having docker-runc installed since it's installed when you install `docker` itself... Anyway, this module deserves some revisit.. This PR is just a quick fix to fix a false negative test.

**Comment by mloviska** [comment]
Seems like `docker-runc` is present in `sle15` (Containers Module 15), should we test that over here https://openqa.suse.de/tests/6267183#step/docker_runc/78 ?

**Comment by mloviska** [comment]
> > Wondering if we should not change/drop this check also https://openqa.opensuse.org/tests/1789994#step/docker_runc/51
> 
> Good point. But to be honest, I don't know the reason for that check... It's probably because we want to test runc only and avoid having docker-runc installed since it's installed when you install `docker` itself... Anyway, this module deserves some revisit.. This PR is just a quick fix to fix a false negative test.

Indeed, needs a bit of attention. Would you mind creating a ticket to our backlog? :)

**Comment by msmeissn** [comment]
runc is replacing / obsoleting docker-runc according to aleksa sarai.

**Comment by jlausuch** [comment]
> runc is replacing / obsoleting docker-runc according to aleksa sarai.

any plans to not install docker-runc when install docker package from zypper?

**Comment by msmeissn** [comment]
i would hope that docker would pull runc instead of dockre-runc currently... is this not the case?

**Comment by jlausuch** [comment]
> i would hope that docker would pull runc instead of dockre-runc currently... is this not the case?

oh yes, I missed that. At least this is the case for 15-SP3: https://openqa.suse.de/tests/6248863#step/docker_image/31

**Comment by mloviska** [comment]
> i would hope that docker would pull runc instead of dockre-runc currently... is this not the case?

Same for sle15 https://openqa.suse.de/tests/6267183#step/docker/56. So the test case just requires some updates. :) 
Thanks for your insights!

**Comment by jlausuch** [comment]
> > > Wondering if we should not change/drop this check also https://openqa.opensuse.org/tests/1789994#step/docker_runc/51
> > 
> > 
> > Good point. But to be honest, I don't know the reason for that check... It's probably because we want to test runc only and avoid having docker-runc installed since it's installed when you install `docker` itself... Anyway, this module deserves some revisit.. This PR is just a quick fix to fix a false negative test.
> 
> Indeed, needs a bit of attention. Would you mind creating a ticket to our backlog, please? :)

[poo#94099](https://progress.opensuse.org/issues/94099)

**Review by pdostal — APPROVED** [review]

**Review by mloviska — APPROVED** [review]

**Comment by Vogtinator** [comment]
I wonder what's with SLE 12 - currently this module is effectively a noop there now.

**Comment by msmeissn** [comment]
we have runc also for sle12 ... the docker,podman,runc stack is at the same level as on sle15, so it could be tested there.

**Comment by jlausuch** [comment]
> I wonder what's with SLE 12 - currently this module is effectively a noop there now.

we have a poo to fix this test case, we might even remove the array since we have runc now everywhere.

**Pull request merged**
