### PR TITLE
Refactor docker* and extend docker-compose.yml

### PR DESCRIPTION
**Pull request by pdostal**
* New folder `lib/containers/` is created to separate future different test modules.
 * The library `lib/containers/common.pm` was created and related code moved in.
 * Function `clean_docker_host` was created to ensure every test ends with clean host.
 * Sample `docker-compose.yml` was created and executed in `docker_compose.pm` module.

- Related ticket: [poo#66952](https://progress.opensuse.org/issues/66952) [poo#66955](https://progress.opensuse.org/issues/66955)
- Verification run: [SLE 12 SP4](http://pdostal-server.suse.cz/tests/8556), [SLE 15 SP1](http://pdostal-server.suse.cz/tests/8555), [Tumbleweed](http://pdostal-server.suse.cz/tests/8554)

### CODE REVIEW

**Comment by ggardet** [comment]
It breaks on aarch64: https://openqa.opensuse.org/tests/1272016#step/docker_compose/29 Could you have a look, please?

**Comment by Vogtinator** [comment]
Also fails on x86_64, needs a longer timeout: https://openqa.opensuse.org/tests/1271903#step/docker_compose/21

**Comment by Vogtinator** [comment]
Also on plain TW: https://openqa.opensuse.org/tests/1272552, though it's not done yet.

**Comment by pdostal** [comment]
Hello @Vogtinator and @ggardet, I am aware of those issues since yesterday.
The problem is on my side, I didn't mark this PR properly and it was merged too soon.

I addressed all of this on #10312 and I will monitor runs following those you mentioned.

**Comment by Vogtinator** [comment]
Ok, thanks!

**Pull request merged**
