### PR TITLE
Integrate 'Accessible network interface' into openQA

### PR DESCRIPTION
**Pull request by Amrysliu**
Related: https://progress.opensuse.org/issues/111899

Verification run:
https://openqa.suse.de/tests/9009236#  (aarch64)
https://openqa.suse.de/tests/9009237#  (s390x)
https://openqa.suse.de/tests/9009238#  (x86_64)

### CODE REVIEW

**Comment by lilyeyes** [comment]
LGTM.
Please check the failure in VR in case it is not expected.

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by Amrysliu** [comment]
> LGTM. Please check the failure in VR in case it is not expected.

It's a performance issue and the case failed in 'timeout'.

**Review by rfan1 — APPROVED** [review]
LGTM

**Review by tinawang123 — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM

**Pull request merged**
