### PR TITLE
Remove no more used conf.yaml for hanasr

### PR DESCRIPTION
**Pull request by mpagot**
There's no more JobGroup definition (that I'm aware of) that is using it
They have problematic values like hardcoded ip

Ticket: https://jira.suse.com/browse/TEAM-8705

### CODE REVIEW

**Review by BillAnastasiadis — APPROVED** [review]
LGTM

**Review by jankohoutek — APPROVED** [review]
LGTM

**Review by alvarocarvajald — COMMENTED** [review]
It seems `hanasr_azure.yaml` is still in use, at least as a default value that it's possible overwritten in the tests themselves:

* In https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/maintenance/maintenance_sle15_sp5_sap.yml?ref_type=heads#L50 and other job groups. (also in 12-SP4, 12-SP5, 15-SP1, 15-SP2, 15-SP3 and 15-SP4)
* In https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/ow15/SLE15/pc.yaml?ref_type=heads#L52
* https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/ow15/maintenance/sap15ga.yaml?ref_type=heads#L44 (This is probably no longer relevant)

I checked the rendered/expanded YAML for the 15-SP5 Maintenance Job Group, and settings is indeed not there, but I'd feel better if we could also remove it as a default value from the job group configuration too.

**Comment by mpagot** [comment]
> In https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/maintenance/maintenance_sle15_sp5_sap.yml?ref_type=heads#L50 and other job groups. (also in 12-SP4, 12-SP5, 15-SP1, 15-SP2, 15-SP3 and 15-SP4)

It is, and in all of them is part of the `pc_defaults`. The full list of files is:
# `openQA/yaml_job_groups/maintenance/maintenance_sle12_sp4_sap.yml` 

`hanasr_azure.yaml` is used on line https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/maintenance/maintenance_sle12_sp4_sap.yml#L49 like `QESAP_CONFIG_FILE: 'hanasr_azure.yaml'` in the `.pc_default` alias that is then used everywhere in this YAML. But, but ... `QESAP_CONFIG_FILE` only matter for cloud based tests (better to say tests using `qe-sap-deployment`). 
 * `sle-12-SP4-GCE-SAP-BYOS-Incidents-saptune-x86_64` is commented out and is re-defining  `QESAP_CONFIG_FILE` in https://gitlab.suse.de/qa-css/openqa_ha_sap/-/blob/master/openQA/yaml_job_groups/maintenance/maintenance_sle12_sp4_sap.yml#L303

**Pull request merged**
