### PR TITLE
Add test_flags fatal=1,milestone to grub_test

### PR DESCRIPTION
**Pull request by MalloZup**
Since this test is important,stop the test if something go wrong.

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by nilxam** [comment]
I'm not so sure this test is a good place to set 'milestone', assume another test loaded snapshot from this point the SUT is under booting or initialing, it's useless from my POV.

**Comment by coolo** [comment]
agreed. We just waste time saving the snapshot - it has no value

**Comment by MalloZup** [comment]
ok i will, remove this. where is stored the snapshot? if there is no keephdd , isn't taked?

**Comment by okurz** [comment]
Regarding your last question, yes, the snapshot is not kept persistent but it takes time to create the snapshot during each run.

**Pull request merged**
