### PR TITLE
Allow running LTP tests without reboot after installing livepatches

### PR DESCRIPTION
**Pull request by mdoucha**
Our kernel devs have suggested dropping unnecessary reboots from out livepatch tests so that we have a test scenario that better matches the real-world use case. These chages will be used primarily in the SecureBoot syscalls test which which combines LTP installation and run in a single job.

- Related ticket: https://progress.opensuse.org/issues/80098
- Needles: N/A
- Verification run:
  - KOTD:
    - install_ltp x86_64: https://openqa.suse.de/tests/5072364
    - install_ltp ppc64le: https://openqa.suse.de/tests/5072365
    - install_ltp s390x: https://openqa.suse.de/tests/5072366
    - install_ltp aarch64: https://openqa.suse.de/tests/5072374
    - ltp_cve x86_64: https://openqa.suse.de/tests/5072378
    - ltp_cve ppc64le: https://openqa.suse.de/tests/5072379
    - ltp_cve s390x: https://openqa.suse.de/tests/5072380
    - ltp_cve aarch64: https://openqa.suse.de/tests/5072381
    - UEFI with SecureBoot disabled: https://openqa.suse.de/tests/5112550#step/boot_ltp/23 (expected to fail efivar check)
  - kernel-default:
    - install_ltp x86_64: https://openqa.suse.de/tests/5072382
    - install_ltp ppc64le: https://openqa.suse.de/tests/5072384
    - install_ltp s390x: https://openqa.suse.de/tests/5072385
    - install_ltp aarch64: https://openqa.suse.de/tests/5072386
    - ltp_syscalls_secureboot x86_64: https://openqa.suse.de/tests/5072387 (iopl01 and ioperm01 are expected to fail)
  - kernel-livepatch 12-SP2:
    - install_ltp x86_64: https://openqa.suse.de/tests/5112536
    - ltp_math x86_64: https://openqa.suse.de/tests/5112543
    - ltp_syscalls_secureboot x86_64: https://openqa.suse.de/tests/5112549 (iopl01 and ioperm01 are expected to fail)
  - kernel-livepatch 15-SP2:
    - install_ltp x86_64: https://openqa.suse.de/tests/5112540
    - install_ltp ppc64le: https://openqa.suse.de/tests/5112541
    - install_ltp s390x: https://openqa.suse.de/tests/5112542
    - ltp_cve x86_64: https://openqa.suse.de/tests/5112545
    - ltp_cve ppc64le: https://openqa.suse.de/tests/5112546
    - ltp_cve s390x: https://openqa.suse.de/tests/5112547
    - ltp_syscalls_secureboot x86_64: https://openqa.suse.de/tests/5112548

### CODE REVIEW

**Comment by mdoucha** [comment]
Rebased on current master and added two small fixes.

All verification runs finished with the expected result, this PR is ready for review and merge.

**Comment by czerw** [comment]
Could you please verify on PowerVM for 15-SP3?   On this job https://openqa.suse.de/tests/5124059.

**Review by czerw — APPROVED** [review]
LGTM, thx for spvm verification

**Comment by mdoucha** [comment]
SPVM install_ltp verification run passed: https://openqa.suse.de/tests/5125728

**Review by pevik — APPROVED** [review]

**Comment by pevik** [comment]
`"load_kernel_tests" is not exported by the main_ltp module` fails.

**Comment by mdoucha** [comment]
Trying to fix the bogus main_ltp error by dropping the obsolete dependency on `Archive::Tar`. New verification run to test job initialization:
https://openqa.suse.de/tests/5129693

**Comment by okurz** [comment]
I also could not reproduce the travis CI failure but I realized that the perl version that is used in the CI jobs are rather outdated so I created
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11557
to bump the involved perl versions. Maybe this will behave differently.

**Comment by mdoucha** [comment]
One more attempt to fix the issue without Perl version bump. It seems the issue is related to the circular dependency between `main_common` and `main_ltp`, the latter of which is imported by `install_ltp`. I've moved the functions needed by `install_ltp` to `LTP::utils` so that `main_ltp` doesn't need to be imported by any test modules.

I've restarted livepatch 15-SP2 SecureBoot verification run which should be enough to validate this change: https://openqa.suse.de/tests/5134506

**Comment by pevik** [comment]
@mdoucha testing your rebased version: https://travis-ci.org/github/pevik/os-autoinst-distri-opensuse/builds/748079731, suppose it should help. Could you please rebase your PR?

**Comment by pevik** [comment]
Also perltidy failed:
```
--- ./lib/LTP/utils.pm	2020-12-07 08:23:24.759672828 +0000
+++ ./lib/LTP/utils.pm.tdy	2020-12-07 08:23:56.215672828 +0000
@@ -29,11 +29,11 @@
 use File::Basename 'basename';
 
 our @EXPORT = qw(
-    loadtest_kernel
-    shutdown_ltp
-    prepare_ltp_env
-    schedule_tests
-    init_ltp_tests
+  loadtest_kernel
+  shutdown_ltp
+  prepare_ltp_env
+  schedule_tests
+  init_ltp_tests
 );
```

**Comment by czerw** [comment]
CI job is fixed now.

**Comment by mdoucha** [comment]
One more verification run to check that rebase didn't break anything: https://openqa.suse.de/tests/5140090

**Pull request merged**
