### PR TITLE
Add new SP2 feature (System role)

### PR DESCRIPTION
**Pull request by dzedro**
https://openqa.suse.de/tests/286840

### CODE REVIEW

**Comment by coolo** [comment]
this will break all other builds. You can't assert - unless you're in that very staging. So I suggest to go with check_screen until merged into the product

**Comment by dzedro** [comment]
I thought we will merge it when everything is red, but without green staging there will be no new build I guess ^^
updated

**Comment by coolo** [comment]
+0.5

as SLE does not have a LIVECD, you can cleanup the main.pm part you just touched and have only one if

**Comment by dzedro** [comment]
haha 0.5
I was surprised about LIVECD in sle ... will udpate it

**Comment by dzedro** [comment]
updated, but this LIVECD for sle needs cleanup anyway

**Comment by coolo** [comment]
I agree .)

**Comment by dzedro** [comment]
note created: sle main.pm LIVECD cleanup

**Pull request merged**
