### PR TITLE
Select acl group regardless of the position in the list

### PR DESCRIPTION
**Pull request by OleksandrOrlov**
**For Reviewers: Please merge [needles](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/989) before merging the PR.**

ACL group selection was failed because of relying on the position of the
group in the list.

The commit uses assert_until_needle_match subroutine to select the acl
group without relying on it's position in the list.

Also, the PR fixes some typos.

- Related ticket: https://progress.opensuse.org/issues/43289
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/989
- Verification run 
   - SLE15, s390x: http://oorlov-vm.qa.suse.de/tests/516
   - SLE12: http://oorlov-vm.qa.suse.de/tests/628

### CODE REVIEW

**Comment by okurz** [comment]
needles merged

**Comment by okurz** [comment]
Thanks for fixing typos

**Comment by DimStar77** [comment]
Nedles for openSUSE would have been a nice touch in plus

**Comment by DimStar77** [comment]
just to be clear: the needles for openSUSE are now done - so there is nothing left to do

**Pull request merged**
