### PR TITLE
cryptlvm template and templates directory

### PR DESCRIPTION
**Pull request by richiejp**
See https://progress.opensuse.org/issues/13140

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
Can you please remove the WIP in the commit message? 
then LGTM

**Comment by richiejp** [comment]
OK, thanks.

**Comment by nilxam** [comment]
we're testing cryptlvm on GNOME rather than minimalx?
and you created another cryptlvm testsuite which had a little bit different than the old one in templates file, load_template will ignore the later one if had the name is existed in db already. I think I missed the idea of separating.

**Comment by richiejp** [comment]
Yes, we are testing on GNOME; https://openqa.suse.de/tests/525605

From the progress article:
"I find the products/opensuse/templates file to big and painful to deal with. Perhaps a templates sub-directory should be created, which we then insert template files into just containing test suits, machines, job groups etc. which are tightly related.

That way someone can view all the information relating to these tests on one or two pages and import the tests without worrying if anything unexpected is going to be added. If someone needs to add all the templates at once then they can write something like ./load_templates templates/*.

Templates provide a way of recording how a machine or test suit should be used, in a transportable and human readable format, but one huge monolithic file is only useful for automated export-import. I used this template during my local installation by following the instructions, but the number of tests it has added was counter productive when trying to learn the system. If new users want to see a complex setup they can look no further than openqa.suse.de."

**Comment by nilxam** [comment]
sounds templates and templates.d have no relationship. fine then.

but your change is against openSUSE, openSUSE is using minimalx for cryptlvm test. https://openqa.opensuse.org/tests/247163#settings

**Pull request merged**
