### PR TITLE
HPC: add slurmctld.log to post_fail_hook()

### PR DESCRIPTION
**Pull request by schlad**

### CODE REVIEW

**Comment by schlad** [comment]
> I can see that you have identical test flags and post fail hooks. Have you considered to extract this to single parent perl module? I also wonder how travis is not failing with this duplication =)

I guess travis has some line-limits below which it does not complain. Which is good ;-)

Of course your comment makes total sense. In fact I'm working on some refactoring of the node provisioning as overall there is quite some duplication in the HPC test code. Thx for the pointer!

**Comment by rwx788** [comment]
> > I can see that you have identical test flags and post fail hooks. Have you considered to extract this to single parent perl module? I also wonder how travis is not failing with this duplication =)
> 
> I guess travis has some line-limits below which it does not complain. Which is good ;-)
> 
> Of course your comment makes total sense. In fact I'm working on some refactoring of the node provisioning as overall there is quite some duplication in the HPC test code. Thx for the pointer!

Makes sense, in case you plan to do that later - I can merge current change, so that you have relevant logs if something breaks.

**Comment by schlad** [comment]
> > > I can see that you have identical test flags and post fail hooks. Have you considered to extract this to single parent perl module? I also wonder how travis is not failing with this duplication =)
> > 
> > 
> > I guess travis has some line-limits below which it does not complain. Which is good ;-)
> > Of course your comment makes total sense. In fact I'm working on some refactoring of the node provisioning as overall there is quite some duplication in the HPC test code. Thx for the pointer!
> 
> Makes sense, in case you plan to do that later - I can merge current change, so that you have relevant logs if something breaks.

Yeah, I've added those 2 uploads for specific failures but there is not much rush. Thx for the proposal, but I will simply try to reorganize the post_fails_hook already. No point to pile up on bad solutions ;-)

**Comment by schlad** [comment]
@rwx788 after looking at the slurm tests, I will close this and rather introduce first simplification of the slurm master node provisioning code. This way I will avoid the duplication of the post_fail_hook altogether. Thx again for a good point, which made me look at this bits of the HPC tests, so I could realize that there are some problems introduced earlier on. So I will correct those.

**Pull request closed without merging**
