### PR TITLE
Add snapshot pattern for online migration

### PR DESCRIPTION
**Pull request by mitiao**
missing snapshot pattern:
https://openqa.nue.suse.com/tests/393111/modules/installation_snapshots/steps/1
add it.

### CODE REVIEW

**Comment by coolo** [comment]
this is getting out of control. This is a typical if elif construct put into a very confusing way. Please fix

**Comment by okurz** [comment]
IMHO you should define the snapshot name that you search for outside the pattern definition, e.g. like
```perl
my $snapshot_name;
if (is_jeos) {
    $snapshot_name = 'Factory status';
}
elsif (get_var('AUTOUPGRADE')) {
    $snapshot_name = 'before update';
}
elsif (get_var('ONLINE_MIGRATION')) {
    $snapshot_name = 'before online migration';
}
else {
    die "no valid snapshot name to search for";
}
$pattern = 'single\s*(\|[^|]*){4}\s*\|\s*number\s*\|\s*'.$snapshot_name.'\s*\|\s*important=yes';
```
A cool alternative might be to define a hash map to describe, something like:
```perl
%snapshot_names = {
    jeos => 'Factory status',
    autoupgrade => 'before update',
    online_migration => 'before online migration',
}
```

**Comment by mitiao** [comment]
hash is cool, but a little redundant?

**Comment by okurz** [comment]
> hash is cool, but a little redundant?
I wouldn't say redundant as the if/else would be replaced by the hashmap to resemble a more descriptive still instead of the procedural if/else but in this case we can't directly apply this as the if/else also has an implicit prioritization of test scenarios included which is probably wrong. For example "what if testing online migration on jeos?". I guess this won't scale for long. Do you have an idea how to fix it? If not then this is probably not so important to solve right now.

**Comment by mitiao** [comment]
yes, at least if/else is needed.
and 'online migration on jeos' is not considered, if need, i will solve it later and no idea now :)

**Pull request merged**
