### PR TITLE
Adapt addon product dialog due to recent sle15 changes

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by okurz** [comment]
* awaiting verification
* phrase git commit message in imperativev mood, e.g. "Adapt addon product dialog to recent changes in SLE15"
* Also, this will break behaviour of older builds. Should we handle this conditionally?

**Comment by Soulofdestiny** [comment]
http://opeth.suse.de/tests/5775

**Comment by okurz** [comment]
LGTM *but*

‎23 Oct 2017 15:37:42‏] ‎<‎mgriessmeier‎>‎ okurz: what about https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3769 before 318 hits openQA? ;)
‎[‎23 Oct 2017 15:42:29‏] ‎<‎coolo‎>‎ mgriessmeier: this is still in stagins
‎[‎23 Oct 2017 15:42:52‏] ‎<‎mgriessmeier‎>‎ coolo: ah, so not in 318 - okay
‎[‎23 Oct 2017 16:17:55‏] ‎<‎okurz‎>‎ so we shouldn't even merge it yet

**Comment by coolo** [comment]
Please change it so it's only applied if FLAVOR is 'Installer-DVD-Staging:Y' - for now

**Comment by Soulofdestiny** [comment]
done

**Comment by okurz** [comment]
seems to work so LGTM

**Comment by Soulofdestiny** [comment]
so what's the status here?

**Comment by okurz** [comment]
Did you check if it's fixing a test failure in Y?

**Comment by Soulofdestiny** [comment]
not needed anymore, proper fix is in product now

**Pull request closed without merging**
