### PR TITLE
Add migration testsuites for SLED15SP6 to SLED15SP7: AUTOYAST files

### PR DESCRIPTION
**Pull request by manfredi**
- Related ticket: [poo#165737](https://progress.opensuse.org/issues/165737)
- Verification run:
  + flavor [Server-DVD-Updates](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Server-DVD-Updates)
  + flavor [Migration-from-SLE15-SPx](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Migration-from-SLE15-SPx)
  + flavor [Migration-from-SLE15-SPx-Milestone](https://openqa.suse.de/tests/overview?distri=sle&groupid=529&flavor=Migration-from-SLE15-SPx-Milestone)
- Related `openqa-job-groups` [MR#352](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/352): to be merge after current PR

### CODE REVIEW

**Comment by jknphy** [comment]
did you copy the profiles from previous product version? did you try to reuse them?

**Comment by manfredi** [comment]
Yes, I did. They are the same as:
- `data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml`
- `data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml`    
but with `<addons> <version> 15.6`:
```bash
$ diff data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml data/yam/autoyast/support_images/sled15sp6_install_default_patterns_x86_64.xml
149c149
<         <version>15.5</version>
---
>         <version>15.6</version>
154c154
<         <version>15.5</version>
---
>         <version>15.6</version>
160c160
<         <version>15.5</version>
---
>         <version>15.6</version>
165c165
<         <version>15.5</version>
---
>         <version>15.6</version>

$ diff data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml     data/yam/autoyast/support_images/sled15sp6_install_all_patterns_x86_64.xml
155c155
<         <version>15.5</version>
---
>         <version>15.6</version>
160c160
<         <version>15.5</version>
---
>         <version>15.6</version>
166c166
<         <version>15.5</version>
---
>         <version>15.6</version>
171c171
<         <version>15.5</version>
---
>         <version>15.6</version>
```

**Comment by jknphy** [comment]
> Yes, I did. They are the same as:
> 
> * `data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml`
> * `data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml`
>   but with `<addons> <version> 15.6`:
> 
> ```shell
> $ diff data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml data/yam/autoyast/support_images/sled15sp6_install_default_patterns_x86_64.xml
> 149c149
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 154c154
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 160c160
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 165c165
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 
> $ diff data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml     data/yam/autoyast/support_images/sled15sp6_install_all_patterns_x86_64.xml
> 155c155
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 160c160
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 166c166
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> 171c171
> <         <version>15.5</version>
> ---
> >         <version>15.6</version>
> ```

**Comment by jknphy** [comment]
let's add dynamically the version to not duplicate files, please check other example in our repo how is done this.

**Comment by manfredi** [comment]
created a dynamic version with `{{ARCH}}` and `{{VERSION}}` for each pattern

**Comment by jknphy** [comment]
> let's add dynamically the version to not duplicate files, please check other example in our repo how is done this.

verify for all test cases for all products and please remove redundant files also in this PR.

**Comment by manfredi** [comment]
Could be deleted the:

- `data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml`
- `data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml`  

and use the dynamic ones, after changed the ref in job template

**Comment by manfredi** [comment]
Removed:
- `data/yam/autoyast/support_images/sled15sp5_install_default_patterns_x86_64.xml`
- `data/yam/autoyast/support_images/sled15sp5_install_all_patterns_x86_64.xml`

**Comment by lemon-suse** [comment]
Please make the MR and VR for migration test together with the PR, so that won't miss anything there. Besides, for the compare profile between 15SP5 and 15SP6 ( clone from interactive installation), it is better to be done before PR merged, or we can merge it then continue to do compare, both ok for me.

**Review by rakoenig — APPROVED** [review]
LGTM.

**Comment by lemon-suse** [comment]
I think we can't merge it firstly when MR are not ready for merge, because the PR changed profile name which will cause the test using that profile failed. So just wait when MR is ready also.

**Comment by manfredi** [comment]
@lemon-suse the [MR#352](https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/352) is ready to merge

**Pull request merged**
