### PR TITLE
choose eth0 as default network device for autoyast

### PR DESCRIPTION
**Pull request by dzedro**
https://openqa.suse.de/tests/91656/modules/start_install/steps/5

### CODE REVIEW

**Comment by aaannz** [comment]
How did you get the second NIC? I see no NIC options in test vars.

**Comment by dzedro** [comment]
no idea, some default settings

**Comment by lnussel** [comment]
what happens without this change? I'm not sure eth0 is correct always.

**Comment by dzedro** [comment]
I'm also not sure if eth0 is always correct, another option is to add key_round selection before inst-packageinstallationstarted to select correct network device or get rid of "Red Hat Virtio network device" if that's even possible.

https://openqa.suse.de/tests/91656/modules/start_install/steps/5

**Comment by dzedro** [comment]
I will test it more deeply and reopen or solve it differently.

**Pull request closed without merging**
