### PR TITLE
Remove dead code from lib/containers/container_images.pm

### PR DESCRIPTION
**Pull request by b10n1k**
The functions are not used anymore on buildah test.
So the condition branches for buildah can be removed as they are dead code in the codebase.

- Verification run: 

http://aquarius.suse.cz/tests/7380
http://aquarius.suse.cz/tests/7381

### CODE REVIEW

**Review by jlausuch — COMMENTED** [review]
Looks good. Can you please run some more VRs of different flavors/architectures in OSD and O3?

**Comment by b10n1k** [comment]
> Looks good. Can you please run some more VRs of different flavors/architectures in OSD and O3?

**host_based:**
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7609244
Github oauth token provided, performing authenticated requests
Created job #7611165: sle-15-SP3-Server-DVD-Updates-x86_64-Build20211105-1-podman_tests@64bit -> https://openqa.suse.de/t7611165
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7609318
Github oauth token provided, performing authenticated requests
Created job #7611166: sle-15-SP3-Server-DVD-Updates-s390x-Build20211105-1-docker_tests@s390x-kvm-sle12 -> https://openqa.suse.de/t7611166
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7609333
Github oauth token provided, performing authenticated requests
Created job #7611167: sle-15-SP3-Server-DVD-Updates-aarch64-Build20211105-1-docker_tests@aarch64-virtio -> https://openqa.suse.de/t7611167
❯ 
**image_based**
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553114
Github oauth token provided, performing authenticated requests
Created job #7611168: sle-15-SP3-Container-Image-Updates-x86_64-Build17.8.25-sle-15-SP3_image_on_Leap-15.2_host@64bit -> https://openqa.suse.de/t7611168
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553113
Github oauth token provided, performing authenticated requests
Created job #7611169: sle-15-SP3-Container-Image-Updates-x86_64-Build17.8.25-sle-15-SP3_image_on_centos_8_host@64bit -> https://openqa.suse.de/t7611169
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553075
Github oauth token provided, performing authenticated requests
Created job #7611170: sle-15-SP3-Container-Image-Updates-aarch64-Build17.8.25-sle-15-SP3_image_on_sle-15-SP1_host_docker@aarch64-virtio -> https://openqa.suse.de/t7611170
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553000
Github oauth token provided, performing authenticated requests
Created job #7611171: sle-15-SP3-Container-Image-Updates-ppc64le-Build17.8.25-sle-15-SP3_image_on_sle-15-SP1_host_podman@ppc64le -> https://openqa.suse.de/t7611171
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553087
Github oauth token provided, performing authenticated requests
Created job #7611172: sle-15-SP3-Container-Image-Updates-s390x-Build17.8.25-sle-15-SP3_image_on_sle-15-SP2_host_podman@s390x-kvm-sle12 -> https://openqa.suse.de/t7611172
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.suse.de/tests/7553106
Github oauth token provided, performing authenticated requests
Created job #7611173: sle-15-SP3-Container-Image-Updates-x86_64-Build17.8.25-sle-15-SP3_image_on_sle-15-SP3_host_docker@64bit -> https://openqa.suse.de/t7611173
❯ 
❯ 
**TW**
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.opensuse.org/tests/2014215
Github oauth token provided, performing authenticated requests
Created job #2015858: microos-Tumbleweed-MicroOS-Image-ContainerHost-x86_64-Build20211103-container-host@64bit -> https://openqa.opensuse.org/t2015858
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.opensuse.org/tests/2014061
Github oauth token provided, performing authenticated requests
Created job #2015859: opensuse-Tumbleweed-DVD-x86_64-Build20211103-containers_image@64bit -> https://openqa.opensuse.org/t2015859
❯ openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13601 https://openqa.opensuse.org/tests/2013851
Github oauth token provided, performing authenticated requests
Created job #2015860: opensuse-Tumbleweed-NET-x86_64-Build20211103-containers_tw_image_on_ubuntu_host@64bit -> https://openqa.opensuse.org/t2015860

**Comment by jlausuch** [comment]
> > Looks good. Can you please run some more VRs of different flavors/architectures in OSD and O3?
> 
> **host_based:** ❯ openqa-clone-custom-git-refspec #13601 https://openqa.suse.de/tests/7609244 Github oauth token provided, performing authenticated requests Created job #7611165: sle-15-SP3-Server-DVD-Updates-x86_64-Build20211105-1-podman_tests@64bit -> https://openqa.suse.de/t7611165 ❯ openqa-clone-custom-git-refspec #13601 

Thank you!

**Review by jlausuch — APPROVED** [review]

**Comment by b10n1k** [comment]
> > > Looks good. Can you please run some more VRs of different flavors/architectures in OSD and O3?
> > 
> > 
> > **host_based:** ❯ openqa-clone-custom-git-refspec #13601 https://openqa.suse.de/tests/7609244 Github oauth token provided, performing authenticated requests Created job #7611165: sle-15-SP3-Server-DVD-Updates-x86_64-Build20211105-1-podman_tests@64bit -> https://openqa.suse.de/t7611165 ❯ openqa-clone-custom-git-refspec #13601
> 
> Thank you!

just checked. most of them are green.

**Pull request merged**
