### PR TITLE
WIP: Verify jasonnet syntax for description

### PR DESCRIPTION
**Pull request by hjluo**
We need to adapt jsonnet format for description for new ALP agama build.

- Related ticket: https://progress.opensuse.org/issues/126848
- Needles: N/A
- Verification run: 
   https://openqa.opensuse.org/tests/3340326 
   https://openqa.opensuse.org/tests/3340345

### CODE REVIEW

**Comment by jknphy** [comment]
s/jasonnet/jsonnet/

**Comment by jknphy** [comment]
adapt? seems you are dropping the description? was dropped or require a different string format?

**Comment by hjluo** [comment]
> adapt? seems you are dropping the description? was dropped or require a different string format?

Sorry, this is just dropping the description part, but even if I drop the description, we still hit failures that complained about invalid jsonnet description.
https://openqa.opensuse.org/tests/3340370#next_previous . so I'd suggest we hold off on this PR by now.  

Thank you.

**Comment by jknphy** [comment]
Please, close this PR if not applicable.

**Comment by hjluo** [comment]
Close this PR, cause this is not the cause for the case failure.

**Pull request closed without merging**
