### PR TITLE
yast2_clone_system: record_soft_failure for xmllint (bsc#1013047)

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@kravciak as discussed

**Comment by kravciak** [comment]
I have to fix my mail filters, just noticed this PR - and I finally get your point :)

**Comment by kravciak** [comment]
Seems it doesn't work https://openqa.opensuse.org/tests/337221#step/yast2_clone_system/11

**Comment by dzedro** [comment]
No test, no capital letter ?

**Comment by kravciak** [comment]
Also see http://chris.beams.io/posts/git-commit/ ... :D

**Comment by okurz** [comment]
messed up (like the 100th time in my life): exit code != logical bool

about the capital letter, `record_soft_failure` is a name, you don't want me to write

```
yast2_clone_system: Record_soft_failure does something
```

do you? ;-)

**Comment by kravciak** [comment]
I might be wrong but IIRC they are just inverted (script_run returns 0 on success, which is considered false in perl conditionals). So replacing || with && should work, but it's not very intuitive..

**Pull request merged**
