### PR TITLE
bootloader: check bootmenu needle for different seabios

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
see failing test because of this: https://openqa.suse.de/tests/649270

**Comment by okurz** [comment]
I disagree with the merge. The corresponding needles should just have the tag `boot-menu` anyway. No need to check for all.

In commit message subject start with capital letter after colon.

**Comment by coolo** [comment]
Yes. Please revert and fix the needle

**Comment by Soulofdestiny** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2168

**Pull request merged**
