### PR TITLE
Add script to flash SD cards using sd-mux-ctrl or usbsdmux tools + fixup for cleanup of flasher

### PR DESCRIPTION
**Pull request by ggardet**
Tested with `usbsdmux` only.

### CODE REVIEW

**Comment by foursixnine** [comment]
@asdil12 this might be interesting for you

**Comment by asdil12** [comment]
@foursixnine I'm not sure what this is about.

**Comment by asdil12** [comment]
@ggardet so what exactly does this script do?

**Comment by ggardet** [comment]
> @ggardet so what exactly does this script do?

By using USB/SD mux hardware such as [USB-SD-Mux] or [SDWire] and matching software, this script switch the SD card to the host computer, flash it with a given image and switch it to the Device Under Test. Then, you can power up the device under test and perform your tests.
This should be used with generalhw backend for tests on real hardware, but you can use it standalone if needed.

[USB-SD-Mux]: https://shop.linux-automation.com/usb_sd_mux-D02-R01-V02-C00-en
[SDWire]: https://wiki.tizen.org/SDWire

**Pull request merged**
