### PR TITLE
Containers: fix autoyast profiles for 15-SP4

### PR DESCRIPTION
**Pull request by jlausuch**
docker-runc is not longer available and replaced by runc

[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/95626
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_autoyast_dockerrunc&version=15-SP4

### CODE REVIEW

**Comment by b10n1k** [comment]
i have done the same a few days ago (https://openqa.suse.de/tests/6572714) and then run a job(which i cant find now) which i saw it failing. So i thought that this would need some extra commits when the sp4 is ready. So this is my first point. i would rather have a more robust PR. 
In additional, i do not know how the removal of the package will affect the other versions. Do we need two versions of the create_hdd for two xml, one with docker-runc and one without for sle>sp3 ?

**Comment by jlausuch** [comment]
> i have done the same a few days ago (https://openqa.suse.de/tests/6572714) and then run a job(which i cant find now) which i saw it failing. So i thought that this would need some extra commits when the sp4 is ready. So this is my first point. i would rather have a more robust PR.
> In additional, i do not know how the removal of the package will affect the other versions. Do we need two versions of the create_hdd for two xml, one with docker-runc and one without for sle>sp3 ?

I have removed the old files we have and created a common file for 15-SP4.

**Comment by mloviska** [comment]
I remember thatt docker should pull runc or docker-runc https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12721#issuecomment-862267164, do we need to specify the package in AY ?

**Comment by jlausuch** [comment]
> I remember that docker should pull runc or docker-runc [#12721 (comment)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12721#issuecomment-862267164), do we need to specify the package in AY ?

maybe not, I will actually remove the  container related packages... let just the tests install them, as we might find issues of dependencies.

**Comment by jlausuch** [comment]
Sorry for the noise, I messed with 2 branches... now it should be fine.

**Comment by asmorodskyi** [comment]
I can understand your pain with having for files and need to enter same changes 4 times in some cases ...
But I doubt that this piece of code is better than having 4 files instead : 

```
  % if ($check_var->('ARCH', 's390x')) {
      <activate>false</activate>
      <boot_extended>false</boot_extended>
      <boot_mbr>true</boot_mbr>
      <boot_root>true</boot_root>
      <generic_mbr>false</generic_mbr>
      % } elsif ($check_var->('ARCH', 'ppc64le')) {
      <append>showopts plymouth.ignore-serial-consoles console=hvc0 console=tty mitigations=auto crashkernel=201M</append>
      <boot_boot>false</boot_boot>
      % } else {
      <append>splash=verbose</append>
      % }
      % if ($check_var->('ARCH', 'aarch64')) {
      <timeout config:type="integer">1</timeout>
      % } elsif ($check_var->('ARCH', 's390x')) {
      <timeout config:type="integer">15</timeout>
      % } else {
      <timeout config:type="integer">-1</timeout>
      % }
    </global>
    % if ($check_var->('ARCH', 'ppc64le') or $check_var->('ARCH', 's390x')) {
    <loader_type>grub2</loader_type>
    % }
    ```
For me personally is really hard to understand what would be final version in each case ...
But up to you , if you able to read this and you really think it is better than 4 files

**Comment by jlausuch** [comment]
> I can understand your pain with having 4 files and need to enter same changes 4 times in some cases ...
> But I doubt that this piece of code is better than having 4 files instead :
> 
> ```
>   % if ($check_var->('ARCH', 's390x')) {
>       <activate>false</activate>
>       <boot_extended>false</boot_extended>
>       <boot_mbr>true</boot_mbr>
>       <boot_root>true</boot_root>
>       <generic_mbr>false</generic_mbr>
>       % } elsif ($check_var->('ARCH', 'ppc64le')) {
>       <append>showopts plymouth.ignore-serial-consoles console=hvc0 console=tty mitigations=auto crashkernel=201M</append>
>       <boot_boot>false</boot_boot>
>       % } else {
>       <append>splash=verbose</append>
>       % }
>       % if ($check_var->('ARCH', 'aarch64')) {
>       <timeout config:type="integer">1</timeout>
>       % } elsif ($check_var->('ARCH', 's390x')) {
>       <timeout config:type="integer">15</timeout>
>       % } else {
>       <timeout config:type="integer">-1</timeout>
>       % }
>     </global>
>     % if ($check_var->('ARCH', 'ppc64le') or $check_var->('ARCH', 's390x')) {
>     <loader_type>grub2</loader_type>
>     % }
> ```
> 
> For me personally is really hard to understand what would be final version in each case ...
> But up to you , if you able to read this and you really think it is better than 4 files

I'm getting used to this language for profiles and I actually like it this way :)

**Review by asmorodskyi — APPROVED** [review]
LGTM

**Comment by jlausuch** [comment]
For some reason, the containers module is not selected during installation. I'm currently troubleshooting that...

**Comment by jlausuch** [comment]
So, if you don't install any package from containers module, the module is not shown in the installation...  So, I'm keeping the container packages in the software section.

**Comment by mloviska** [comment]
> So, if you don't install any package from containers module, the module is not shown in the installation... So, I'm keeping the container packages in the software section.

Makes perfect sense and as the profile is for sle15, I guess we can keep `runc` in the package list too

**Review by pdostal — APPROVED** [review]

**Comment by jlausuch** [comment]
[Create hdd tests](https://openqa.suse.de/tests/overview?distri=sle&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_autoyast_dockerrunc&version=15-SP4) are passing.
Jobs using the HDDs are also booting and running:
[64bit](https://openqa.suse.de/tests/6617398) [s390x-kvm-sle12](https://openqa.suse.de/tests/6617400) [ppc64le](https://openqa.suse.de/tests/6617399) [aarch64](https://openqa.suse.de/tests/6617149)

There are other problems not related to this PR which I am addressing in a [different one](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13002).

**Pull request merged**
