### PR TITLE
Pynfs/cleanup

### PR DESCRIPTION
**Pull request by pevik**
Cleanup preparation for https://progress.opensuse.org/issues/160179. The main change is to introduce `NFSVERSION` to be mandatory to pynfs and turn `PYNFS` variable as simple bool.

I've already set `NFSVERSION` for pynfs tests in both o3 and osd (merge of this change will not break the results). 

Verification run:
pynfs 4.0 and 4.1 on SLE 15-SP[56] & Tumbleweed (tested with changed variables (`QEMURAM=4096` - to avoid bsc#1217488 `PYNFS=1` `NFSVERSION=4.0` or `4.1`)
- http://quasar.suse.cz/tests/3279
- http://quasar.suse.cz/tests/3274
- http://quasar.suse.cz/tests/3270
- http://quasar.suse.cz/tests/3269
- http://quasar.suse.cz/tests/3290
- http://quasar.suse.cz/tests/3291

cthon04 on SLE 15-SP[56] & Tumbleweed
- http://quasar.suse.cz/tests/3273
- http://quasar.suse.cz/tests/3275
- http://quasar.suse.cz/tests/3276
- http://quasar.suse.cz/tests/3277
- http://quasar.suse.cz/tests/3280
- http://quasar.suse.cz/tests/3281

### CODE REVIEW

**Comment by czerw** [comment]
Please do verification also on 15-sp5 https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=20240509-1&groupid=411

**Review by czerw — APPROVED** [review]

**Comment by pevik** [comment]
All CI passed, just waiting for @SeroSun.

**Review by SeroSun — APPROVED** [review]
LGTM. would you also update pynfs setting in osd and o3?

**Comment by SeroSun** [comment]
I see you already updated the setting, thx!

**Pull request merged**
