### PR TITLE
kernel/nfs: run stress-ng 

### PR DESCRIPTION
**Pull request by richiejp**
Run stress-ng on our MM setup. So far only added the filename switch, will add more.

https://progress.opensuse.org/issues/127835

Ignore the top two commits, they will be merged in #17170 

@schlad

### CODE REVIEW

**Comment by richiejp** [comment]
Note that kernel/wmp_simple.pm does things differently. I assume this is because it has to test the WMP while stress_ng runs. I am not sure this test requires anyting like that.

**Comment by richiejp** [comment]
Need to rebase once #17170 is merged, but otherwise looks OK

**Comment by richiejp** [comment]
On NFSv3 we get a failure on TW:

```
stress-ng: fail:  [3866] fsize: fallocate unexpectedly succeeded at offset 262144 (0x40000), expecting EFBIG error
stress-ng: fail:  [3866] fsize: expected a SIGXFSZ signal at offset 262144 (0x40000), nothing happened
stress-ng: info:  [3866] fsize: fallocate unexpectedly succeeded at offset 106797 (0x1a12d), expecting EFBIG error
```

For now it ignores the failure, but in the future it could be changed to fail.

**Comment by richiejp** [comment]
@czerw We can merge this after #17170 and run it on TW at least: https://github.com/os-autoinst/opensuse-jobgroups/pull/332

**Comment by czerw** [comment]
Let's wait few more days after is  https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17170 merged, just to be safe if  there is revert.

**Comment by richiejp** [comment]
> Let's wait few more days after is #17170 merged, just to be safe if there is revert.

FWIW I think this can be merged now. After the rebase it is just adding one commit. We may want to hold off merging the TW schedule though.

**Review by czerw — APPROVED** [review]

**Review by schlad — APPROVED** [review]
looks good.

**Pull request merged**
