### PR TITLE
Improve test variables documentation

### PR DESCRIPTION
**Pull request by rwx788**
See [poo#23376](https://progress.opensuse.org/issues/23376).

Here is how it will look like:
image

### CODE REVIEW

**Comment by rwx788** [comment]
Small note for the reviewers: I have removed some variables which are not used in the test coed anymore and also all variables, which are already defined in https://github.com/os-autoinst/os-autoinst/blob/master/doc/backend_vars.asciidoc

**Comment by okurz** [comment]
Wow, this looks awesome! Do we have a self-test already that checks that the used variables must appear in this list? Could be out of scope for this PR/ticket though.

@coolo you were interested in the variable list. WDYT?

**Comment by okurz** [comment]
@asmorodskyi you *did* see that I asked others for their opinion? ;)

**Comment by rwx788** [comment]
@okurz We don't and we have tons of variables which are not described. For some I also could not come up with a good description, so added empty lines. So for now let's not accept PRs which introduce new variables and do not add them to the list.

**Pull request merged**
