### PR TITLE
xfstests: Reload status log for stable

### PR DESCRIPTION
**Pull request by SeroSun**
Some time rum.pm fail by crash, and in generic_report.pm test will reload a last good snapshot, then all log will lose in upload log process. This solution is to upload status log into worker and reload it.
Also add a post_fail_hook to rum.pm for more logs when crash.

a tricky part is add a "ll" in generic_report.pm:43 before "tar", that because sometimes openQA "eaten" that start "t" cause tests fail. So now even test eat the first "l", test will not fail.

- Related ticket: 
  https://progress.opensuse.org/issues/51557
  https://progress.opensuse.org/issues/50216
- Verification run: http://10.67.133.102/tests/921
In this VR, test crash in xfs/473, and generic.pm will remain pass and could show result in a good way.

### CODE REVIEW

**Comment by lansuse** [comment]
LGTM

**Comment by SeroSun** [comment]
Compare with previous VR, the update one got a full log(for download). http://10.67.133.102/tests/938

**Comment by jlausuch** [comment]
LGTM

**Comment by jlausuch** [comment]
LGTM

**Pull request merged**
