### PR TITLE
Remove IDE specific code

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by asmorodskyi** [comment]
it's ready to merge

**Comment by rwx788** [comment]
I'm kind of against it, as it's basically same as keeping project settings files for different IDEs in github, doesn't harm. And I'm pretty sure quite some people are using vim to work with tests.

**Comment by asmorodskyi** [comment]
@rwx788 I know that it will come to this discussion :) but it is does not matter how many people using vim. it is wrong to keep IDE settings in version control. There is a lot reasons for this. Just short example - image tomorrow vim will produce new version which will be incompatible with this settings ?

**Comment by okurz** [comment]
Well, I use vim unlike you and I don't need these settings. I can share my vimrc for people thinking they would still need this code :)

**Comment by okurz** [comment]
Please rebase and merge

**Pull request merged**
