### PR TITLE
Add work around & soft fail for poo#116191

### PR DESCRIPTION
**Pull request by alvarocarvajald**
SLES+HA migrations from 15-SP3 to 15-SP4 & 15-SP5 on ppc64le fail on the `ha/check_after_reboot` test module because the UUID configured for the `cluster_md` MD RAID device in `/etc/mdadm.conf` in the qcow2 images from the 15-SP3 installations is different than the actual block devices UUIDs after the migration. This commit works around the issue and soft fail the test when the issue is detected.

- Related ticket: https://progress.opensuse.org/issues/116191
- Needles: N/A
- Verification runs: [support server](https://openqa.suse.de/tests/9458942), [node 1](https://openqa.suse.de/tests/9458943), [node 2](https://openqa.suse.de/tests/9458941)
- Verification run (regression): Alpha Cluster: [node 1](http://mango.qa.suse.de/tests/4945), [node 2](http://mango.qa.suse.de/tests/4946) & [support server](http://mango.qa.suse.de/tests/4946); 15-SP3 to 15-SP5 Migrations on x86_64: [node 1](http://mango.qa.suse.de/tests/4948), [node 2](http://mango.qa.suse.de/tests/4949) & [support server](http://mango.qa.suse.de/tests/4947)

### CODE REVIEW

**Comment by lilyeyes** [comment]
I only checked "stop_pacemaker" related code changes, it looks good to me.
For other code changes I don't have knowledge on this yet but generally looks good to me.

**Comment by bs-github** [comment]
I like this very much!
LGTM

**Review by lpalovsky — APPROVED** [review]
LGTM

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by alvarocarvajald** [comment]
> I only checked "stop_pacemaker" related code changes, it looks good to me. For other code changes I don't have knowledge on this yet but generally looks good to me.

This is only intended to stop pacemaker during migrations, as migration jobs do not run in Multi-Machine mode, hence cluster nodes do not have access to the support server, and cluster is not working. Intention is to get rid of those pacemaker failures journal messages from reaching the console and causing a needle match failure during the test (such as in [this case](http://mango.qa.suse.de/tests/4912#step/register_system/4)). I added it only in the online migrations schedule for now, as I ran into it during the verification runs, but it may be necessary to add it to the other migration schedules. 

Module should not be used in migration verification jobs as we need pacemaker active in those.

**Pull request merged**
