### PR TITLE
Disable screensaver module; openqa: Simplify webui/test_results

### PR DESCRIPTION
**Pull request by okurz**
This simplifies the code, gets rid of "brute-force refreshing" with
pressing 'f5' repeatedly as well as speeds up the test.by about one
minute.

EDIT: Verification run: ~~https://openqa.opensuse.org/1259293~~

```
$ for i in https://openqa.opensuse.org/tests/1262098 https://openqa.opensuse.org/tests/1259200; do openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10220 $i; done
```

* opensuse-Tumbleweed-DVD-x86_64-Build20200509-openqa_bootstrap@64bit -> https://openqa.opensuse.org/t1263314
* *opensuse-Tumbleweed-DVD-aarch64-Build20200506-openqa_bootstrap@aarch64 -> https://openqa.opensuse.org/t1263315

### CODE REVIEW

**Comment by okurz** [comment]
@asdil12

**Comment by asdil12** [comment]
I would actually rather waste time refreshing the page than trust the screensaver disabling code as I wrote it but gave up as it is not very reliable.
Also the X dpms not disabled so xserver could still disable the screen output.

I'm fine with your first three commits, though.

And your verification run does not exist.
Also a verification run on aarch64 (idk why we even test openQA on that arch) should be done.

**Comment by okurz** [comment]
From my test runs I am pretty sure the screensaver is actually disabled. Thanks for the detailed feedback. I will merge my first three commits first then and provide verification runs again, also aarch64.

**Comment by okurz** [comment]
@asdil12 please check again

**Pull request merged**
