### PR TITLE
wicked: Minor fixes for SLE15 enablement 

### PR DESCRIPTION
**Pull request by asmorodskyi**
Stop disabling Firewalld for SLE 15

VR: https://openqa.suse.de/tests/3393714

### CODE REVIEW

**Comment by jlausuch** [comment]
LGTM.
btw, why firewall is not running by default? Design decision?

**Comment by asmorodskyi** [comment]
> LGTM.
> btw, why firewall is not running by default? Design decision?

firewall is not running not "by default" but by our custom AutoYaST profile , and before_test was relying on state which you getting after default installer choices . This is main issue actually

**Comment by Hoorhay** [comment]
This commit likely broke testing in QAM scenarios, where we use different image. Wouldn't it be easier to do something like?:

> if systemctl ("is-active" . opensusebasetest::firewall) {
>         systemctl("stop " . opensusebasetest::firewall);
>         systemctl("disable " . opensusebasetest::firewall);
> }

[1] https://openqa.suse.de/tests/3460611#step/t08_sit_tunnel_ifdown/258
[2] https://progress.opensuse.org/issues/57926

**Comment by asmorodskyi** [comment]
> This commit likely broke testing in QAM scenarios, where we use different image. Wouldn't it be easier to do something like?:
> 
> > if systemctl ("is-active" . opensusebasetest::firewall) {
> > systemctl("stop " . opensusebasetest::firewall);
> > systemctl("disable " . opensusebasetest::firewall);
> > }
> 
> [1] https://openqa.suse.de/tests/3460611#step/t08_sit_tunnel_ifdown/258
> [2] https://progress.opensuse.org/issues/57926

1. Feel free to verify it and merge in case it solve your problem. https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8647 
2. Are you sure that problem is exactly in firewall ? Please take a look at https://progress.opensuse.org/issues/54197 and https://progress.opensuse.org/issues/55175. Long story short we have some instability in wicked tests not related to wicked but more to infra which setting up VLANs for tests ( openvswitch + QEMU )

**Pull request merged**
