### PR TITLE
Fix x509 server connection issue

### PR DESCRIPTION
**Pull request by nanzhg**
Setting long host name to avoid x509 server connection issue.
Failure job - https://openqa.suse.de/tests/10292462#step/kubevirt_tests_agent/57

- Related ticket: https://progress.opensuse.org/issues/121063
- Verification run: http://openqa.suse.de/tests/10304523

### CODE REVIEW

**Comment by nanzhg** [comment]
@alice-suse @xguo @waynechen55 @Julie-CAO @tbaev @RoyCai7 please help to review this PR. Thanks

**Review by alice-suse — COMMENTED** [review]
LGTM, better to make the 3 commits with same commit msg into 1?

**Comment by Julie-CAO** [comment]
LGTM

**Comment by nanzhg** [comment]
> LGTM, better to make the 3 commits with same commit msg into 1?

Already merged commits. Thanks

**Pull request merged**
