### PR TITLE
Integrate test case 'filter' of audit test into openQA

### PR DESCRIPTION
**Pull request by Amrysliu**
QE security plan to integrate all test cases under `CC audit test`
into openQA. 'filter' is one of these.

Related: https://progress.opensuse.org/issues/95464
Verification run: https://openqa.suse.de/tests/6490980#

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Review by tinawang123 — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM. thanks. :)

**Comment by rfan1** [comment]
into openQA. 'filter' is one of these. to "into openQA. 'filter' is one of them"

**Review by rfan1 — APPROVED** [review]
LGTM

**Pull request merged**
