### PR TITLE
Update variables.md

### PR DESCRIPTION
**Pull request by JRivrain**
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7823

### CODE REVIEW

**Comment by asdil12** [comment]
> To be used when booting from installer medium with the option "Boot Linux System" (uses linuxrc)
I think the description text could be better.
I honestly don't understand, what it does.

Looking at #7823 all it seems to do is adding `linuxrc.log=/dev/$serialdev` as a kernel parameter when set to `true`.

**Comment by JRivrain** [comment]
> Looking at #7823 all it seems to do is adding `linuxrc.log=/dev/$serialdev` as a kernel parameter when set to `true`.

Corrrect, but it could be used for something else. That variable only means 'we are in a scenario where we are booting using the option "Boot Linux System"'. Maybe someone else will do another test suite on a different product and re-use that variable for something else: still booting from that menu entry, but differently. Or maybe (very probably) we will add more options later like "linuxrc.debug=4,trace", for example.

**Comment by JRivrain** [comment]
see also https://openqa.opensuse.org/tests/983377

**Comment by JRivrain** [comment]
I created a new PR since I could not squash commits here : https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7904/files.

**Pull request closed without merging**
