### PR TITLE
Split qam-minimal+base test

### PR DESCRIPTION
**Pull request by rfan1**
Due to poo#115007, split ‘qam-minimal+base’ test into 2 parts,
then we don't need to re-run all test modules in case some test
failures.

I Need modify the test suite and jobgroup as well, https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/362

- Related ticket: https://progress.opensuse.org/issues/115007
- Needles: n/a
- Verification run: 
https://openqa.suse.de/tests/overview?groupid=220&distri=sle&build=20220908-1

### CODE REVIEW

**Comment by michaelgrifalconi** [comment]
Looks great! Would still get a chance for other people to have a look before merging everything since is a relevant change.

I agree on having smaller parts to avoid image recreation on a small failure, will save us a lot of time!
I would like more a single schedule file, common for all versions but I see there are little differences here and there, and in any case it's out of scope and can be considered in future.

Thanks for the great work!

**Comment by ge0r** [comment]
I would recommend for the first part of the split `qam-minimal+base-installation`, to implement it using autoyast for robustness. The interactive installation is already tested in yast, so if you only want this part for the image generation, autoyast would be a good fit.

**Comment by rfan1** [comment]
> I would recommend for the first part of the split `qam-minimal+base-installation`, to implement it using autoyast for robustness. The interactive installation is already tested in yast, so if you only want this part for the image generation, autoyast would be a good fit. [Here](https://confluence.suse.com/display/QYT/How-To%3A+Adapt+an+openQA+installation+testsuite+to+use+AutoYaST) is a small guide on how to generate the autoyast profile and then adjust it for your test, if the ones we already have in the repo won't do.

Why not, thanks much, let me try!

**Comment by rfan1** [comment]
@ge0r now installation is done via autoyast

**Review by ge0r — APPROVED** [review]
LGTM!

**Comment by ge0r** [comment]
> @ge0r now installation is done via autoyast

Nice work!

**Comment by rfan1** [comment]
@foursixnine Could you please double check again?

Please merge my MR https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/362 if you approve it :)

**Review by foursixnine — APPROVED** [review]

**Comment by foursixnine** [comment]
> @foursixnine Could you please double check again?
> 
> Please merge my MR https://gitlab.suse.de/qa-maintenance/qam-openqa-yml/-/merge_requests/362 as well if you approve it :)

Let's merge while playing:
[Paint It Green](https://www.youtube.com/watch?v=b0tsZB_LEQk)

**Pull request merged**
