### PR TITLE
Add ntpd service check

### PR DESCRIPTION
**Pull request by AlynxZhou**
Add ntpd service check

- Related ticket: https://progress.opensuse.org/issues/54998
- Needles: n/a
- Verification run: 
    + Migration service check
        * http://openqa.suse.de/tests/3286477
        * http://openqa.suse.de/tests/3286616 (running)
    + Console ntp check:
        * http://openqa.suse.de/tests/3286480
        * http://openqa.suse.de/tests/3286470

### CODE REVIEW

**Comment by AlynxZhou** [comment]
> Wouldn't be better to reuse existing test scenario from https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/console/ntp.pm instead of copy pasting like in #8209?

Hi, I am afraid that the file you mentioned is a single function module, which is not what we need...

**Comment by AlynxZhou** [comment]
@baierjan I have modified and tested the original console ntp check module to reuse code, you can see changed files and openqa test results.

**Comment by baierjan** [comment]
I would say, this is definitely better. Maybe it would be good to also extract the rest of the code to keep the logic at one place only (to prevent adding lines to `tests/console/ntp.pm` which can brake your code.

And a cosmetic comment, I am not sure about added value of calling a function with one function call (for example `services::ntpd::install_service`).

**Comment by AlynxZhou** [comment]
> I would say, this is definitely better. Maybe it would be good to also extract the rest of the code to keep the logic at one place only (to prevent adding lines to `tests/console/ntp.pm` which can brake your code.

You are right. There are some lines in `tests/console/ntp.pm` I decided not to add them into `lib/services/ntpd.pm` when I was writing it, which are just lines you see in my commit now. I personally think the are useless, they are used to check configuration works or not, but `check_function()` can also do this because only a right configuration can make function works.

I'd like to remove those lines in next commit if that's acceptable.

> And a cosmetic comment, I am not sure about added value of calling a function with one function call (for example `services::ntpd::install_service`).

The reason is that there are other service check module which needs to install more packages, and those modules have a promise that they will use same function name. So I am afraid that I won't change it into a single function call.

**Comment by baierjan** [comment]
No, those lines are required by the QAM testing scenario. The logic behind is a test, that the change in configuration is correctly picked-up by the ntpd: https://progress.opensuse.org/issues/51695

**Comment by AlynxZhou** [comment]
I have updated code in `tests/console/ntp.pm`, what do you think of it now?

**Comment by coolgw** [comment]
@baierjan Any more comments after update?

**Comment by coolgw** [comment]
> I would have similar opinion like in #8209, the code is definitely OK, I do not like the idea of moving the code from the test itself and hide it behind a lot of functions with are basically aliases for existing functions. Who will maintain the test code from this point?
> 
> Also, please add a verification run for at least SLE12-SP4.

@baierjan  There is PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7643 has been discussed. And this PR is updated with same logic.
The background is we need check service before/after migration, and  we can not simply schedule test module before /after migration, for example before migration we need install enable service, but after migration we do not need it. 
So we need new lib/services/ntpd.pm with all function, and all other module (include migration and function)  call lib/func, then we only need maintain lib/services/ntpd.pm. I suppose the module owner will continue maintain the lib/services/ntpd.pm. Hope this can help. Feedback me if any question.

For SLE12-SP4,  could you help give a job link and we can clone it for verification? I try to find one case run ntp on sle12-sp4 but failed.

**Comment by baierjan** [comment]
@coolgw thank you for pointing me to the discussion. If that is a general approach, then I have no objections to it. Who are you referring to by *module owner*?

All relevant stuff can be found in the "Maintenance: Test Repo" job group. Feel free to clone https://openqa.suse.de/tests/3281036 or similar.

**Comment by coolgw** [comment]
> @coolgw thank you for pointing me to the discussion. If that is a general approach, then I have no objections to it. Who are you referring to by _module owner_?
> 
> All relevant stuff can be found in the "Maintenance: Test Repo" job group. Feel free to clone https://openqa.suse.de/tests/3281036 or similar.

@baierjan 
Ntpd module test should belong one qa sle team, what i mean that qa sle team should assign person who will continue maintain it. Correct me if i am wrong.

Thanks for your info about job.

**Comment by lemon-suse** [comment]
LGTM.

**Comment by baierjan** [comment]
> Ntpd module test should belong one qa sle team, what i mean that qa sle team should assign person who will continue maintain it. Correct me if i am wrong.

Why QA SLE? Do they know about the test, they did not write it.

**Pull request merged**
