### PR TITLE
[DISCUSSION]Remove the word "regression" in our tests where not carrying information

### PR DESCRIPTION
**Pull request by okurz**
Used the following approach:

```
for i in $(git ls-files "*x11regression*") ; do j=${i%/*.pm}; mkdir -p ${j/x11regressions/x11}; done
for i in $(git ls-files "*x11regression*") ; do git mv $i ${i/x11regressions/x11}; done
25247  git rm -f lib/x11regressiontest.pm

Related progress issue: https://progress.opensuse.org/issues/31363

### CODE REVIEW

**Comment by okurz** [comment]
@chuchingkai @yifanjiang WDYT?

**Comment by chuchingkai** [comment]
Thank you Oliver, I added a comment:
- https://progress.opensuse.org/issues/31363#note-1

**Comment by coolo** [comment]
I'm happy that this is our biggest problem now!

**Comment by okurz** [comment]
no one said that ;)

**Comment by dasantiago** [comment]
We have tests failing because of this PR.

The tests weren't changed to load from x11 instead:

> dasantiago@magicbox ~/P/os-autoinst-distri-opensuse> ack 'x11regressions'
> lib/main_common.pm
> 543:                loadtest "x11regressions/x11regressions_setup";
> 546:                loadtest "x11regressions/firefox/firefox_java";
> 721:    loadtest "x11regressions/gnote/gnote_first_run";
> 722:    loadtest "x11regressions/gnote/gnote_link_note";
> 723:    loadtest "x11regressions/gnote/gnote_rename_title";
> 724:    loadtest "x11regressions/gnote/gnote_undo_redo";

https://openqa.suse.de/tests/1489804/file/autoinst-log.txt

**Comment by coolo** [comment]
created symlink as hotfix

**Comment by okurz** [comment]
wasn't actually meant to be merged … yet ;) Ok, I will fix it

**Pull request merged**
