### PR TITLE
Alter package version for transactional update

### PR DESCRIPTION
**Pull request by mnowaksuse**
Fails here: https://openqa.suse.de/tests/951210#step/transactional_update/65
Verification run: http://assam.suse.cz/tests/5970

### CODE REVIEW

**Comment by dzedro** [comment]
We have to always update the code ? Wouldn't be variable better ?

**Comment by okurz** [comment]
LGTM, decide with @kravciak  which one to follow :-)

And I **also** agree with @dzedro

**Comment by kravciak** [comment]
Not always, we just created new maintenance incident and packages in repository had to be rebuilt. This should not happen again in near future.

**Comment by kravciak** [comment]
Please merge https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2941 instead as it contains replacement for update-test-trival. This package was broken by intention and should be used to test cases when update fails.

**Comment by mnowaksuse** [comment]
Superseded by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2941.

**Pull request closed without merging**
