### PR TITLE
Rename ibus test to right country

### PR DESCRIPTION
**Pull request by asdil12**
CH: Switzerland
CN: China

Ticket: https://progress.opensuse.org/issues/66553
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/679

`openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10837 https://openqa.opensuse.org/tests/1357390 NEEDLES_DIR=https://github.com/asdil12/os-autoinst-needles-opensuse.git#ibus`
Created job #1365359: opensuse-Tumbleweed-DVD-aarch64-Build20200807-gnome-x11-ibus@aarch64 -> https://openqa.opensuse.org/t1365359

### CODE REVIEW

**Comment by foursixnine** [comment]
@asdil12 for some reason, the needles were not checked out

**Comment by dcermak** [comment]
> @asdil12 for some reason, the needles were not checked out, @dcermak you hahd a similar problem recently right?

Yes I had, but my issue was that I used this syntax: `NEEDLES_DIR=path/to/repo#GIT_HASH` and not `NEEDLES_DIR=path/to/repo#BRANCH_NAME` which caused the test to not even start, which is both not the case here. Maybe just wait a bit and try restarting the job or replicate that locally?

**Comment by asdil12** [comment]
> Maybe just wait a bit and try restarting the job or replicate that locally?

Sadly it is aarch64

**Comment by asdil12** [comment]
Verification: http://kazhua.qa.suse.de/tests/63#

**Pull request merged**
