### PR TITLE
slepos tests update

### PR DESCRIPTION
**Pull request by psladek**
- added services check
- pxe mutex name fix

### CODE REVIEW

**Comment by okurz** [comment]
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

Please provide a link or screenshot to a local verification run.

**Comment by psladek** [comment]
Why has this been closed? The commit messages were reformated and extended on Nov 3, 2016 according to suggestions. Please reopen and/or comment if some other changes are needed.
Btw. this commit is also needed for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2001

**Comment by okurz** [comment]
Well, sorry but the commit message does not correspond to http://chris.beams.io/posts/git-commit/ at all. The commit message subject line should be in imperative mode, start with a capital letter and not have a dot at the end of the line. Also, please provide a link or screenshot to a local verification run.

We reworked the sle11 branch to be fully self-contained which should be helpful also for you. All test modules are now part of the sle11 branch and are not used from the master branch anymore. So please make sure all modules you added are added within this PR into the sle11 branch. Probably your PR was implicitly closed by github because we deleted and recreated the sle11 branch for the above mentioned change.

**Comment by okurz** [comment]
please rebase on current master and make sure your "os-autoinst" subfolder is up to date to use an updated style check. You may have to create a symlink to `.perltidyrc` manually, e.g. with `ln -s os-autoinst/.perltidyrc`

**Comment by psladek** [comment]
rebased and created new pullrequest #2395 according to the above suggestions, which supercedes and obsoletes this

**Comment by okurz** [comment]
replaced by #2395

**Pull request closed without merging**
