### PR TITLE
assert text login instead of sleep

### PR DESCRIPTION
**Pull request by aaannz**
- fix 'none' result and thus failing the test

### CODE REVIEW

**Comment by lnussel** [comment]
isn't there some fallback in the os-autoinst engine that adds a result to tests that didn't produce a result on their own?

**Comment by aaannz** [comment]
I thought so, but does not seem to be. The good place would be after autotest:104 I think.

**Comment by nilxam** [comment]
well, in this case, it at least need a assert_screen() or a wait_serial() then it can go through record_screenmatch or record_serialresult in orderto change $result to ok or fail.
add a assert_screen("console-tty3") right after ctrl-alt-f3 should be the better solution here IMO.

**Comment by lnussel** [comment]
Ondřej Holeček schrieb:
> I thought so, but does not seem to be. The good place would be after
> autotest:104 I think.

Check basetest.pm, it sets the result to 'unk' as fallback at several
places. Maybe the new modular code can't deal with that?

**Comment by lnussel** [comment]
hmm, what's this test good for anyways? the name and comments suggest it ejects a cd but it actually doesn't :)

**Comment by nilxam** [comment]
hmm...good question, this test actually only does a console reboot since long time ago, it's good for some tests need a quick reboot before go next step, but yes...the test name never changed indeed.

**Comment by aaannz** [comment]
Ok, changed it to assert_screen('text-login'). @nilxam what do you think?

**Comment by nilxam** [comment]
LGTM

**Pull request merged**
