### PR TITLE
sysauth: Port from legacy python-PAM to maintained python3-pam

### PR DESCRIPTION
**Pull request by DimStar77**
Port to the newer ctype python pam module and python3

- Related ticket: https://progress.opensuse.org/issues/31246
- Needles: N/A
- Verification run: http://dimstar.internet-box.ch:81/tests/87

### CODE REVIEW

**Comment by DimStar77** [comment]
* python3-python-pam is available in Leap and TW
* I did not find references that maintenance would run any test that would be affected
* SLE seems also not to run this test, there is neither python-pam (legacy) not python-python-pam (new module) available

**Comment by okurz** [comment]
@HouzuoGuo any feedback on this as you are the test module maintainer? Btw, do you want to stay as test module maintainer?

**Comment by HouzuoGuo** [comment]
looks lovely & greetings from Helsinki!

**Comment by okurz** [comment]
ok, fine. Great to hear from you :)

**Pull request merged**
