### PR TITLE
Re-introduce working test modules from BIGTEST

### PR DESCRIPTION
**Pull request by okurz**
'syslinux' and 'sntp' were relying on external ressources not available
anymore.

Local verification run: http://lord.arch/tests/5482

Related progress issue: https://progress.opensuse.org/issues/13004

### CODE REVIEW

**Comment by okurz** [comment]
seems there are more modules within `bigx11test_applicable` which I should take care of

**Comment by okurz** [comment]
Needs https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/146 and https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/275

**Comment by okurz** [comment]
rebased

**Comment by asmorodskyi** [comment]
LGTM

**Comment by okurz** [comment]
merged locally with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2233

**Comment by chuchingkai** [comment]
glxgears failed at SLED12SP3 Build 0080 and SLES 12SP3 Build 0195: https://openqa.suse.de/tests/679407#step/glxgears/13

**Comment by coolo** [comment]
this really should not be tested as part of every scenario on every build.

**Comment by nilxam** [comment]
this breaks all TW/Leap stagings release...

**Comment by okurz** [comment]
@nilxam TW/Leap staging tests fixed with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2242

@chuchingkai thank you for your observations. Feel free in general to propose a corresponding PR to exclude the module whereever it does not make sense. Also you are welcome to review open PRs in advance to prevent breakage.

@coolo I left the module at the position where it was all the time but got rid of "BIGTEST". We can now of course move it to a more suitable location. E.g. extratests?

**Pull request closed without merging**
