### PR TITLE
Disable oom serial failure for LTP tests

### PR DESCRIPTION
**Pull request by foursixnine**
https://openqa.suse.de/t4659370 

Follow up to: #10954

### CODE REVIEW

**Comment by asdil12** [comment]
LGTM

**Comment by dzedro** [comment]
This does not cover everything https://openqa.suse.de/tests/4662661

**Comment by asdil12** [comment]
One approach to catch that one could be to add a `get_var('LTP_KNOWN_ISSUES')` to `is_ltp_test`

**Comment by dzedro** [comment]
It looks like duplicate of new ltp tests, I will most probably remove it.

**Pull request merged**
