### PR TITLE
Fix yast2_lan_restart.pm for installing vlan package

### PR DESCRIPTION
**Pull request by Zaoliang**
- see poo#29319 for details
- add zypper_call(in vlan)
- verification run:
  http://e13.suse.de/tests/88#step/yast2_lan_restart/320
- needle PR: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/612

### CODE REVIEW

**Comment by coolo** [comment]
aehm, that dialog asks you to press Install to continue - and not install it before the test. This is faking

**Comment by okurz** [comment]
Yes, I agree that the dialog should be handled properly whenever it pops up. However the work on yast2_lan_restart is becoming quite costly now. I strongly recommend to work on https://progress.opensuse.org/issues/28666 first, to split the yast2_lan_restart module before continuing.

**Comment by Zaoliang** [comment]
@coolo okay, let me check how to fix it in better way, thanks!

**Comment by Zaoliang** [comment]
found in sub close_yast  yast2_lan_packages_need_to_be_installed, so just add the needle. it looks fine.

**Pull request closed without merging**
