### PR TITLE
Add autoyast ipmi SES5 test

### PR DESCRIPTION
**Pull request by dzedro**
Supermicro servers in Prague assigned for SES testing can be reinstalled with
this test, servers are deployed with installed salt, deepsea, ceph, openattic
configured is only salt, ssh keys of testers.
https://pes.suse.de/QA_Maintenance/Users/SES_Hardware/

- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/651
- Verification run: http://10.100.12.155/tests

### CODE REVIEW

**Comment by foursixnine** [comment]
@dzedro You're deploying servers using openQA? xD, I like the idea! // CC @mudler @dasantiago xD

**Comment by dzedro** [comment]
It's the fastest and simplest way to do it.  click, do something else, done 😄

**Comment by nicksinger** [comment]
FYI: Needles merged

**Comment by okurz** [comment]
Let's propose to SUSE to ditch salt in favor of just openQA ;P

**Pull request merged**
