### PR TITLE
Record a softfailure while bug is not fixed

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by lnussel** [comment]
snapper fix is on the way, so not urgent to merge from my side. Thanks!

**Comment by asmorodskyi** [comment]
closing PR according Ludwig comment

**Comment by coolo** [comment]
Can you snipe out the test from SP1 though? We really shouldn't add regression tests for things not meant to work :(

**Comment by okurz** [comment]
see #2568

**Pull request closed without merging**
