### PR TITLE
 boottime old tests decommissioning

### PR DESCRIPTION
**Pull request by m-dati**
Removed all `publiccloud_boottime` tests collecting old boottime measures and every call of the `publiccloud/boottime.pm` module and its routines.
All related measured data, with the old record structure, is stored in the `perf` bucket on influxDB server.

- Related ticket: https://progress.opensuse.org/issues/118027
- Needles: N/A
- Verification run: To be done. See next posts.

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by m-dati** [comment]
Please note that I did **not delete boottime.pm** module, only removed any call to it.
This because it contains the record structure of the old `perf` bucket/DB still containing valid data and that code could be useful for future maintenance or documentation reference of that DB.
Eventually that module could be moved elsewere, at least saved for archiving.

**Comment by m-dati** [comment]
Note 2: this PR should be merged **after** [MR1245](https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1245) **merged**.

**Comment by m-dati** [comment]
Here are 3 VRs that **FAIL as expected**:

`PUBLIC_CLOUD_CHECK_BOOT_TIME=1`
- sle-15-SP5-GCE-ARM-x86_64-Build0299-publiccloud_boottime@64bit - 
  https://openqa.suse.de/tests/11349504 FAILED as Expected

- sle-15-SP5-Azure-BYOS-x86_64-Build0338-publiccloud_boottime@az_Standard_B2s -
  https://openqa.suse.de/tests/11349505 FAILED as Expected

`PUBLIC_CLOUD_CHECK_BOOT_TIME=0`
- sle-15-SP5-GCE-ARM-x86_64-Build0299-publiccloud_boottime@64bit - 
  https://openqa.suse.de/tests/11349512 FAILED as Expected

**Comment by m-dati** [comment]
> > Please note that I did **not delete boottime.pm** module, only removed any call to it. This because it contains the record structure of the old `perf` bucket/DB still containing valid data and that code could be useful for future maintenance or documentation reference of that DB. Eventually that module could be moved elsewere, at least saved for archiving.
> 
> The git history is a good archive. :)

Considering this, I removed also that module, in a new commit

**Pull request merged**
