### PR TITLE
Add test for libvorbis

### PR DESCRIPTION
**Pull request by emiura**
Tests uses a ogg sample (from gnome-control-center package) to extract some
info about the file using ogginfo and parses output using some grep RE.

Test run:
SLE15: http://10.161.229.180/tests/1656
SLE12SP4: http://10.161.229.180/tests/1692
SLE12SP3: http://10.161.229.180/tests/1691
SLE12SP2: http://10.161.229.180/tests/1688
Leap: http://10.161.229.180/tests/1679
TW: http://10.161.229.180/tests/1678

Fixes poo#49079 ([qam][blue] Regression test libvorbis)

Console only test, no needles required.

### CODE REVIEW

**Comment by Zaoliang** [comment]
https://openqa.suse.de/tests/2898676#step/libvorbis/8 shows that vorbis-tools is not found on ppc64le.

I checked on my sles 15 sp1,  SLE-Module-Desktop-Applications15-SP1-Pool is required for installing vorbis-tools.

**Comment by dzedro** [comment]
Then it's bug when on ppc64le when vorbis-tools are not present ?, on x86_64 is vorbis-tools in desktop-applications pool. https://openqa.suse.de/tests/2898150#step/libvorbis/3

**Comment by dzedro** [comment]
The tested system is not registered I guess... because package is there
http://download.suse.de/install/SLP/SLE-15-Module-Desktop-Applications-GM/x86_64/DVD1/x86_64/vorbis-tools-1.4.0-1.53.x86_64.rpm
http://download.suse.de/install/SLP/SLE-15-Module-Desktop-Applications-GM/ppc64le/DVD1/ppc64le/vorbis-tools-1.4.0-1.53.ppc64le.rpm

**Comment by Zaoliang** [comment]
@dzedro it is then a product issue if vorbis-tools is not available in the corresponding repository.

**Comment by dzedro** [comment]
@Zaoliang no, just desktop application module is not added.

**Pull request merged**
