### PR TITLE
workaround missing release notes

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by okurz** [comment]
how is this a workaround? If release notes are missing test is failed. That was the intention, right? Or don't we expect the release notes to be present (not be correct, just existing) until very late in the development cycle?

**Comment by dzedro** [comment]
yes if release notes are missing test fail, but we want to continue so just soft fail if button/release notes are missing
If release notes are there then we check them as always

**Comment by okurz** [comment]
but didn't you just make them fatal intentionally with https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/2d97c9f95b42fb286ea9038198fcd4f5dbd9e091 ?

**Comment by dzedro** [comment]
yes, it's fatal to get logs if RN are wrong, but if they are missing then just soft fail  to continue e.g. for s390x or ipmi

**Comment by okurz** [comment]
okay …, then +1, I'd guess :-)

**Comment by dzedro** [comment]
RN are looot of fun :laughing:

**Pull request merged**
