### PR TITLE
Record soft failure on bsc#1144000 HPC segfault

### PR DESCRIPTION
**Pull request by dzedro**
MVAPICH2: segfault while executing without ib_uverbs loaded

- Related ticket:
https://bugzilla.suse.com/show_bug.cgi?id=1144000
blocked maintenance update e.g. https://openqa.suse.de/tests/4560315#step/mpi_master/61
- Verification run: https://openqa.suse.de/tests/4569506

### CODE REVIEW

**Review by schlad — COMMENTED** [review]
Isn't 255 about something different?
Shouldn't we only check for 139?
https://openqa.suse.de/tests/4569509#step/mpi_master/59

**Comment by dzedro** [comment]
> Isn't 255 about something different?
> Shouldn't we only check for 139?
> https://openqa.suse.de/tests/4569509#step/mpi_master/59


it's not, for some reason 139 sometimes ends with 255 https://openqa.suse.de/tests/4571517#step/mpi_master/53
but there are failures which are different https://openqa.suse.de/tests/4435033#step/mpi_master/55

**Comment by dzedro** [comment]
With 139 it's reported by master `YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)`
With 255 it's reported by slave `[mpiexec@master-node00] main (ui/mpich/mpiexec.c:344): process manager error waiting for completion`
I guess depends who is first, but the root cause is same `Caught error: Segmentation fault (signal 11)`

```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2671 RUNNING AT master-node00
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:1@slave-node00] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:909): assert (!closed) failed
[proxy:0:1@slave-node00] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@slave-node00] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
Nc1ag-139-
```

```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2369 RUNNING AT slave-node01
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:0@master-node00] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:909): assert (!closed) failed
[proxy:0:0@master-node00] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@master-node00] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
[proxy:0:1@slave-node00] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:909): assert (!closed) failed
[proxy:0:1@slave-node00] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@slave-node00] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@master-node00] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@master-node00] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@master-node00] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@master-node00] main (ui/mpich/mpiexec.c:344): process manager error waiting for completion
Nc1ag-255-
```

**Comment by dzedro** [comment]
Btw what issue is the `No IB device found` ? Is there bug, root cause ?

**Review by schlad — CHANGES_REQUESTED** [review]
I don't like this change. 255 can indicate more problems so that condition seems wrong. Also I would prefer to see why in SP3 we see the return code 1. Could be that ib_uverbs doesn't exist there/have diff name? I would suggest checking the OBS fixes on this MPI flavor as I recall there was another problem there fixed which could not land in older code streams.

I would either do this: " ##TODO: condider more rebust handling of various errors "
or if we want to simply silence red color, I would go for record_soft_failure in the else part and pile up problems/bugs there if needed.

All in all: we already have bad piece of checking the return value and we pill up on that.
-2

**Comment by dzedro** [comment]
> I don't like this change. 255 can indicate more problems so that condition seems wrong. Also I would prefer to see why in SP3 we see the return code 1. Could be that ib_uverbs doesn't exist there/have diff name? I would suggest checking the OBS fixes on this MPI flavor as I recall there was another problem there fixed which could not land in older code streams.
> 
> I would either do this: " ##TODO: condider more rebust handling of various errors "
> or if we want to simply silence red color, I would go for record_soft_failure in the else part and pile up problems/bugs there if needed.
> 
> All in all: we already have bad piece of checking the return value and we pill up on that.
> -2

No, it does not indicate more problems, I explained to you why the 139 fail is sometimes ending with 139 and sometimes 255.
Based on what you consider return value as bad piece of checking ? You write that like you would have list of thousands of failures and you have no idea what is what.

**Comment by schlad** [comment]
> > I don't like this change. 255 can indicate more problems so that condition seems wrong. Also I would prefer to see why in SP3 we see the return code 1. Could be that ib_uverbs doesn't exist there/have diff name? I would suggest checking the OBS fixes on this MPI flavor as I recall there was another problem there fixed which could not land in older code streams.
> > I would either do this: " ##TODO: condider more rebust handling of various errors "
> > or if we want to simply silence red color, I would go for record_soft_failure in the else part and pile up problems/bugs there if needed.
> > All in all: we already have bad piece of checking the return value and we pill up on that.
> > -2
> 
> No, it does not indicate more problems, 

Can't it be that mpirun hit 255 because - for instance - remote host will vanish for some network related issues?

>I explained to you why the 139 fail is sometimes ending with 139 and sometimes 255.
> Based on what you consider return value as bad piece of checking ? You write that like you would have list of thousands of failures and you have no idea what is what.

**Comment by dzedro** [comment]
> > > I don't like this change. 255 can indicate more problems so that condition seems wrong. Also I would prefer to see why in SP3 we see the return code 1. Could be that ib_uverbs doesn't exist there/have diff name? I would suggest checking the OBS fixes on this MPI flavor as I recall there was another problem there fixed which could not land in older code streams.
> > > I would either do this: " ##TODO: condider more rebust handling of various errors "
> > > or if we want to simply silence red color, I would go for record_soft_failure in the else part and pile up problems/bugs there if needed.
> > > All in all: we already have bad piece of checking the return value and we pill up on that.
> > > -2
> > 
> > 
> > No, it does not indicate more problems,
> 
> Can't it be that mpirun hit 255 because - for instance - remote host will vanish for some network related issues?
> 
> > I explained to you why the 139 fail is sometimes ending with 139 and sometimes 255.
> > Based on what you consider return value as bad piece of checking ? You write that like you would have list of thousands of failures and you have no idea what is what.

I don't think so, but I added check for the expected error message.

**Comment by schlad** [comment]
sorry Jozef for not being able to do the proper review by the end of last week. I was really busy with that NetApp hardware and the testing of that.
Today my day looks way better, so I should be able to do the review as it should be.

**Comment by schlad** [comment]
sorry Jozef for not being able to do the proper review by the end of last week. I was really busy with that NetApp hardware and the testing of that.
Today my day looks way better, so I should be able to do the review as it should be.

**Comment by schlad** [comment]
> Btw what issue is the `No IB device found` ? Is there bug, root cause ?

So starting from this.
The test description says: "...we do not support ethernet." So basically this MPI flavor wasn't supporting Ethernet networks and maybe that changed? After all I see we are getting now that binary hello world executed. This should be really checked (I'll do this).

The only expected error here should be - if I remember it correctly - that the MPI stack reports 'no IB devices' and is closing gracefully.
For this reason I would try to avoid having also 255 added to the soft-fail where we strictly talk about MPI binary segfaulting. 

In the meantime I got the first HPC 15 SP3 build and I see some fun there going on too, so perhaps we could simply merge your patch and I will propose some more extensive changes to the way we test MPIs. Would this work for you?

**Review by schlad — APPROVED** [review]

**Pull request merged**
