### PR TITLE
[OOP]Change desktop for sle12 & sle11

### PR DESCRIPTION
**Pull request by dzedro**
ref. http://dzedro.qa.suse.cz/tests/554

### CODE REVIEW

**Comment by coolo** [comment]
what's different in this compared to sle11_change_desktop? Please no copy&paste programming

**Comment by dzedro** [comment]
sorry it's copy&paste, I will use the OOP way

**Comment by dzedro** [comment]
sle11 minimalx http://10.100.98.90/tests/564
sle12 minimalx http://10.100.98.90/tests/565

**Comment by coolo** [comment]
so if I get this right, sle11_change_desktop is just the same as change_desktop. So just rename the file?

**Comment by coolo** [comment]
merged this, but I think you should change sle11 to just directly reference change_desktop and drop the sle11_ test

**Comment by coolo** [comment]
or not - the textmode behaves different in sle12, so we do need some change

**Pull request merged**
