### PR TITLE
Whitelist journal message mm_request_receive: read: Connection reset …

### PR DESCRIPTION
**Pull request by jlausuch**
…by peer

Failure: https://openqa.opensuse.org/tests/2958573#step/journal_check/21
VR: https://openqa.opensuse.org/tests/2959145

### CODE REVIEW

**Comment by Vogtinator** [comment]
The bsc# looks unrelated?

**Comment by jlausuch** [comment]
> The bsc# looks unrelated?

yes, I didn't know where to put it, but it's near the same other error messages:
```
Dec 16 09:18:45.673596 localhost.localdomain login[947]: pam_systemd(login:session): Failed to release session: Interrupted system call
Dec 16 09:20:08.850269 localhost.localdomain login[986]: pam_systemd(login:session): Failed to release session: Interrupted system call
Dec 16 09:20:08.858717 localhost.localdomain sshd[1325]: fatal: mm_request_receive: read: Connection reset by peer
```

Shall I create new bug for this message?

**Comment by Vogtinator** [comment]
> > The bsc# looks unrelated?
> 
> yes, I didn't know where to put it, but it's near the same other error messages:
> 
> ```
> Dec 16 09:18:45.673596 localhost.localdomain login[947]: pam_systemd(login:session): Failed to release session: Interrupted system call
> Dec 16 09:20:08.850269 localhost.localdomain login[986]: pam_systemd(login:session): Failed to release session: Interrupted system call
> Dec 16 09:20:08.858717 localhost.localdomain sshd[1325]: fatal: mm_request_receive: read: Connection reset by peer
> ```
> 
> Shall I create new bug for this message?

Depends on what it's caused by. Probably ansible?

**Comment by mloviska** [comment]
> > > The bsc# looks unrelated?
> > 
> > 
> > yes, I didn't know where to put it, but it's near the same other error messages:
> > ```
> > Dec 16 09:18:45.673596 localhost.localdomain login[947]: pam_systemd(login:session): Failed to release session: Interrupted system call
> > Dec 16 09:20:08.850269 localhost.localdomain login[986]: pam_systemd(login:session): Failed to release session: Interrupted system call
> > Dec 16 09:20:08.858717 localhost.localdomain sshd[1325]: fatal: mm_request_receive: read: Connection reset by peer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Shall I create new bug for this message?
> 
> Depends on what it's caused by. Probably ansible?

Yup, there is some hanging connection, not sure whether we are not closing something properly or it is a "cosmetic" issue

**Comment by jlausuch** [comment]
> > > The bsc# looks unrelated?
> > 
> > 
> > yes, I didn't know where to put it, but it's near the same other error messages:
> > ```
> > Dec 16 09:18:45.673596 localhost.localdomain login[947]: pam_systemd(login:session): Failed to release session: Interrupted system call
> > Dec 16 09:20:08.850269 localhost.localdomain login[986]: pam_systemd(login:session): Failed to release session: Interrupted system call
> > Dec 16 09:20:08.858717 localhost.localdomain sshd[1325]: fatal: mm_request_receive: read: Connection reset by peer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Shall I create new bug for this message?
> 
> Depends on what it's caused by. Probably ansible?

looks like, I re-ran the test without ansible :
https://openqa.opensuse.org/tests/2959195

**Pull request closed without merging**
