### PR TITLE
Adjust bootmenu helper for PowerPC

### PR DESCRIPTION
**Pull request by k0da**
On grub2 powerpc our default boot entry is the last one. Lets go up in
that case.

### CODE REVIEW

**Comment by sysrich** [comment]
this seems a lot more elegant than having a separate test for grub on OFW, coolo, what do you think?

**Comment by coolo** [comment]
you figure the function is called down_to? :)

**Comment by k0da** [comment]
yes. Do I need to remove it?

**Comment by coolo** [comment]
Counter proposal (untested): https://gist.github.com/coolo/a29bab8dbedc2686a930

**Comment by k0da** [comment]
Tested, it works

**Comment by k0da** [comment]
PR updated

**Pull request merged**
