### PR TITLE
Remove workaround for resolved bugs

### PR DESCRIPTION
**Pull request by kravciak**
Both bugs are RESOLVED FIXED

### CODE REVIEW

**Comment by kravciak** [comment]
@QingmingSu please check, it's your workaround

**Comment by QingmingSu** [comment]
Let me run a local verification test with you change first. :)

**Comment by QingmingSu** [comment]
I have verified that it is safe to remove the workaround:

But I found another issue poo#32953 which should be fixed either, otherwise releasenotes.pm will just return with softfailure in 5s.

And one more issue is that addon license is not really checked here, see:

**Comment by kravciak** [comment]
Thank you :)
From the link that you sent - http://openqa-apac1.suse.de/tests/372#step/releasenotes/6
Release notes content says `sles12-sp3`, shouldn't it be sles15?

**Comment by kravciak** [comment]
Ah, I just read the bugs - pls ignore the question :)

**Pull request merged**
