### PR TITLE
Fix security/apparmor_profile/usr_sbin_smbd and usr_sbin_traceroute on TW

### PR DESCRIPTION
**Pull request by Vogtinator**
- Related ticket: https://progress.opensuse.org/issues/92004
- Verification run: https://openqa.opensuse.org/tests/1832705

CC @lilyeyes

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
LGTM. Thanks for the changes.

**Comment by coolo** [comment]
you broke it for SP3: https://openqa.suse.de/tests/6444711#step/usr_sbin_smbd/78

**Comment by Vogtinator** [comment]
> you broke it for SP3: https://openqa.suse.de/tests/6444711#step/usr_sbin_smbd/78

Looks a bit like a product bug, the tab order starts right at the beginning instead of the clicked and focused button...

I'll prepare a workaround PR which just allows more tab presses

**Comment by Vogtinator** [comment]
> > you broke it for SP3: https://openqa.suse.de/tests/6444711#step/usr_sbin_smbd/78
> 
> Looks a bit like a product bug, the tab order starts right at the beginning instead of the clicked and focused button...
> 
> I'll prepare a workaround PR which just allows more tab presses

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12897

**Pull request merged**
