### PR TITLE
ipxe_install: Make the set_bootscript_hdd() delay configurable

### PR DESCRIPTION
**Pull request by mdoucha**
Some workers need more than 2 minutes to reach PXE bootloader after power-on. Add a variable `PXE_BOOT_TIME` to control the bootscript switch delay for UEFI machines so that it can be configured on each worker.

This is the correct solution for #17769

- Related ticket: N/A
- Needles: N/A
- Verification runs:
  - without `PXE_BOOT_TIME`: https://openqa.suse.de/tests/12223015
  - with `PXE_BOOT_TIME`: https://openqa.suse.de/tests/12223016
  - without `AUTOYAST`: https://openqa.suse.de/tests/12223020

### CODE REVIEW

**Review by frankenmichl — APPROVED** [review]
Good idea, lgtm

**Comment by mdoucha** [comment]
Both verification runs worked as expected, note the difference in `ipxe_install` run time. The failure in `autoyast/console` is expected until #17721 gets merged.

**Review by Dawei-Pang — CHANGES_REQUESTED** [review]
I think the root cause is not timing issue, it is hard to specific PXE_BOOT_TIME for each machines.

Your supermicro system has firmware issue to support UEFI standard, that does not mean all servers.

SLE installer can help to setup UEFI nvram and boot installed OS as first boot order in most vendor servers.

**Comment by cachen** [comment]
Please allow me to share my opinion and help a bit :)  
I followed the discussion in [Slack](https://suse.slack.com/archives/C02CANHLANP/p1694684786531609), and thank you very much that we indicate the root cause is that set_bootscript_hdd is only specified to Supermicro machine, but hurt for Dell, HP, Lenovo machines that we also have . Since we are hardly to collecting and setting the exact booting time for each machine, IMO, it sounds more efficiency and effective to specify for the machine brand type(Supermicro), rather than to each machine.

@pcervinka, I guess set_bootscript_hdd was added for kernel testing need on supermicro machine, do you have any opinion or suggestion that we can help here to make the solution be much easier for each team for each different machine?

**Comment by mdoucha** [comment]
> Please allow me to share my opinion and help a bit :) I followed the discussion in [Slack](https://suse.slack.com/archives/C02CANHLANP/p1694684786531609), and thank you very much that we indicate the root cause is that set_bootscript_hdd is only specified to Supermicro machine, but hurt for Dell, HP, Lenovo machines that we also have . Since we are hardly to collecting and setting the exact booting time for each machine, IMO, it sounds more efficiency and effective to specify for the machine brand type(Supermicro), rather than to each machine.

I never said that Supermicro is the only vendor with this problem. I have no idea how many other vendors may be affected.

Measuring boot time is as easy as running one job on the machine with video capture enabled (`NOVIDEO=0`) and then reading timestamps from the video.

**Comment by czerw** [comment]
@Dawei-Pang @cachen I'm sorry I don't understand what is the issue. Fixed sleep is in the code for 3 years already since https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11273  and nobody complained. This PR just improves existing code to have delay configurable.  If the variable is not defined, it will just use same behavior like before.  I will also reply in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17769/f

**Comment by Dawei-Pang** [comment]
> > Please allow me to share my opinion and help a bit :) I followed the discussion in [Slack](https://suse.slack.com/archives/C02CANHLANP/p1694684786531609), and thank you very much that we indicate the root cause is that set_bootscript_hdd is only specified to Supermicro machine, but hurt for Dell, HP, Lenovo machines that we also have . Since we are hardly to collecting and setting the exact booting time for each machine, IMO, it sounds more efficiency and effective to specify for the machine brand type(Supermicro), rather than to each machine.
> 
> I never said that Supermicro is the only vendor with this problem. I have no idea how many other vendors may be affected.
> 
> Measuring boot time is as easy as running one job on the machine with video capture enabled (`NOVIDEO=0`) and then reading timestamps from the video.

From the discussion in the slack, I suppose you verified the [PR#17583](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17583) on Supermicro machine, if  the PR#17583 verified on other brand/model machine, please let me know. Thanks!

If the PR#17583 only verified or workaround for supermicro machine, please add a checker to limit for supermicro only, because the code without `set_bootscript_hdd if get_var('IPXE_UEFI');` can run successfully without any issue for a long time.

**Comment by Dawei-Pang** [comment]
> @Dawei-Pang @cachen I'm sorry I don't understand what is the issue. Fixed sleep is in the code for 3 years already since #11273 and nobody complained. This PR just improves existing code to have delay configurable. If the variable is not defined, it will just use same behavior like before. I will also reply in #17769

Thanks, at beginning, I think this is timing issue, after some research, yes, the sleep code is running for a long time.
The issue comes from PR#17583, adding `set_bootscript_hdd if get_var('IPXE_UEFI');` is root cause.

**Comment by cachen** [comment]
> > Please allow me to share my opinion and help a bit :) I followed the discussion in [Slack](https://suse.slack.com/archives/C02CANHLANP/p1694684786531609), and thank you very much that we indicate the root cause is that set_bootscript_hdd is only specified to Supermicro machine, but hurt for Dell, HP, Lenovo machines that we also have . Since we are hardly to collecting and setting the exact booting time for each machine, IMO, it sounds more efficiency and effective to specify for the machine brand type(Supermicro), rather than to each machine.
> 
> I never said that Supermicro is the only vendor with this problem. I have no idea how many other vendors may be affected.

@mdoucha  Hello Martin, no worry I didn't say you said that, but how I concluded from yours and Dawei's observation when read the discussion in slack, and I believe now you are aware from Dawei, besides Supermicro, that are other vendor's are affected.

"One more time: SuperMicro UEFI machines ignore the "force PXE boot" flag."
"They have to be configured to *ALWAYS* use the following BIOS boot order:"
"I can confirm the SLE installer change the UEFI boot order to installed OS as default behaviour on HPE, DELL and LENOVO/IBM system except for other action"

> 
> Measuring boot time is as easy as running one job on the machine with video capture enabled (`NOVIDEO=0`) and then reading timestamps from the video.

Think about if the code can be much easier to adapting for dozens of machines with different vendor. And if the solution in pr#17769 bring difficult or challenge for kernel team to adapting your test on your machines.

-----------------------------------------------------------------
@czerw Hope Dawei has explained to you in his reply, that the main issue and root cause is not the timing, but was introduced by PR#17583, adding set_bootscript_hdd if get_var('IPXE_UEFI'); so whether revert PR#17583, or how to improving the PR is the topic.

----------------------------------------------------------------
I will stop here to do any micro-management to influence the technical decision :-)
The last suggestion that Vit and I from TL's view is, perhaps it will be helpful to have a debugging session that Dawei and Martin together, to learn from each other what is the challenge and what is the exactly expected, and of course other relevant engineers can be invited if need.

**Comment by mdoucha** [comment]
I've changed the `set_bootscript_hdd()` logic to use a special flag that should be added only to the workers/jobs that need it. The `IPXE_UEFI` condition was wrong.

**Comment by mdoucha** [comment]
Verification runs updated.

**Comment by czerw** [comment]
@Dawei-Pang @frankenmichl  could we have a look on this one please and maybe have it merged?

**Comment by Dawei-Pang** [comment]
Please allow me to involve @Julie-CAO to see if the changes break her testing.

**Comment by Julie-CAO** [comment]
> Please allow me to involve @Julie-CAO to see if the changes break her testing.

I will verify on VIRT-AUTO tests, wait a few fours.

**Comment by mdoucha** [comment]
This PR is quite old so I've just rebased it to the latest `master`.

**Comment by Julie-CAO** [comment]
> > Please allow me to involve @Julie-CAO to see if the changes break her testing.
> 
> I will verify on VIRT-AUTO tests, wait a few fours.

I had two successful runs, I think the PR is ok. @alice-suse , are you also ok with this change?
[sle15sp6_kvm_on_non_uefi_machine](http://openqa.suse.de/tests/14114256)
[on_UEFI_kermit_on_OSD](https://10.145.10.207/tests/14114253)

**Comment by alice-suse** [comment]
LGTM, and verified for usb install, works too.

**Comment by czerw** [comment]
Thanks all, I think we can merge. Just one thing came to my mind, shouldn't we mention variable also in `variables.md` ?

**Comment by mdoucha** [comment]
> Thanks all, I think we can merge. Just one thing came to my mind, shouldn't we mention variable also in `variables.md` ?

Added variable documentation to `variables.md` and rebased to latest master. No other changes.

**Pull request merged**
