### PR TITLE
Add support for LTSS product migration

### PR DESCRIPTION
**Pull request by mitiao**
See: https://progress.opensuse.org/issues/18488

### CODE REVIEW

**Comment by plusky** [comment]
Why should you need to remove ltss product before migration? Migration from LTSS should work just as migration from regular release - it seems to me that you are creating workaround where bug should be reported.

**Comment by mitiao** [comment]
It is not a bug, but a expected process to do migration with ltss, since ltss channel for SP3 would not be ready during testing phrase, we have to disable and remove it before migration. Otherwise the conflict would happen during migration.
Here is my local verified run:
http://147.2.207.208/tests/486 (ignore failure by timeout of test)

**Comment by plusky** [comment]
I am still not sure that its not a bug, customer using SLE-12-GA LTSS might decide to migrate to SLE-12-SP3 and such migration should work. Migration channel for SP3 does not need to be available at at time of migration. LTSS channel is of course not present during testing phase and is not present after testing finishes either.

Other possible scenario might be migration from  SLE-12-GA LTSS to SLE-12-SP2 where LTSS channel is not and never will be available.

**Comment by mitiao** [comment]
I like your concerns :)
And what I did above is about confirmation and feedback from Artem.
Currently if we perform online migration from SLE-12-GA LTSS to SP3 without removing LTSS product, SCC would NOT show any available migration targets which mean migration doesn't work.
And for offline migration I explained that conflicts would happen if not removing LTSS product.
Better to @kalabiyau

**Comment by okurz** [comment]
On Thursday, 13 April 2017 23:12:39 CEST Wei Jiang wrote:
> I like your concerns :)
> And what I did above is about confirmation and feedback from Artem.
> […] And for offline migration I explained
> that conflicts would happen if not removing LTSS product. Better to
> @kalabiyau

Also maybe it helps to refer to documentation which can further explain the 
supported workflow. Maybe migrations from LTSS to any current product needs a 
slight improvement in the product nevertheless?

**Comment by plusky** [comment]
I was not able to find any documentation stating that this is necessary for successful migration, I would guess that removal of product might should be done by zypper migration plugin. Nevertheless I am now curious (and will try) if migration from GA LTSS to SP2 needs some adjustments or works out of box.

**Comment by plusky** [comment]
Interestingly migration from SLE-12-SP0 ltss does not work out of box, zypper migration claims "No migration available." However there is still lacking documentation for this, and afaik its something that zypper migration should take care of - will clarify this further.

**Comment by mitiao** [comment]
I filed a bug to SCC team: bsc#1034598

**Comment by plusky** [comment]
It seems to be tracked at https://fate.suse.com/322483

**Comment by sysrich** [comment]
Marita will follow up whether or not this testing behaviour is acceptable

**Comment by mitiao** [comment]
The bug has been fixed: https://bugzilla.suse.com/show_bug.cgi?id=1034598
From the feedback, we have to de-register the system and then to register again without LTSS product to be able to perform online migration as well as avoid error.
And It should be documented to release note or somewhere else.

**Comment by plusky** [comment]
@mitiao as @sysrich said lets wait for clarification by marita

**Comment by mitiao** [comment]
@plusky sure, I am waiting for it :)

**Comment by mitiao** [comment]
Got confirmation from Marita and Anja, then I did changes on more scripts, please see the description in commit message.
Verified runs:
offline: http://147.2.207.208/tests/486
online: http://147.2.207.208/tests/500

**Comment by okurz** [comment]
hm, looks good to me so far and I understand the reason as described in the commit message. Thanks for that. OTOH I am not sure if the decision for "SKIP_LTSS" should instead not be handled within the test code with a proper description why it's necessary. The reason is that in test suite settings it is very hard to understand why a certain variable is set or not. In the test code with git commit message, history, author and such we can track business logic decisions like these much better. I'm torn but I would be fine with another person merging the PR.

**Pull request merged**
