### PR TITLE
Refine GnuPG case with batch mode for stability

### PR DESCRIPTION
**Pull request by wnereiz**
* Refine GnuPG case with batch mode to avoid interaction commands.
* Improve the test logical to make it clearly.
* Add test for key length of 4096

- Related ticket: https://progress.opensuse.org/issues/50606
- Related needles: 
  * SLE15: ~~https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1131~~ Merged
  * SLE12: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1134
  * Tumbleweed: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/554
- Verification run:
  * SLES15 SP1 FIPS: http://10.67.17.9/tests/987
  * SLES15 SP1: http://10.67.17.9/tests/988
  * SLES12 SP4: http://10.67.17.9/tests/989
  * openSUSE Tumbleweed: http://10.67.17.9/tests/990

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@czerw you are list as maintainer

**Comment by asmorodskyi** [comment]
LGTM , but I will give some time for @czerw to also check it

**Comment by wnereiz** [comment]
@czerw I have updated the cases to support passphrase input with pinentry for both key generation and unlock, some needles changed and additional ones added. All verification run have been updated.
@asmorodskyi Would you please consider to merge [PR for the needles](https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/554)?

**Comment by czerw** [comment]
@wnereiz Please do verification runs for 12-sp3/sp4 as well. Thank you.

**Comment by wnereiz** [comment]
@asmorodskyi @czerw I have modified the code and now SLE12 is supported. But there are some additional needles created. I have also updated the verification run for different distributions.

**Comment by asmorodskyi** [comment]
sorry @czerw , wanted to leave decision to you but only AFTER I merged related needles I realize that now I must merge this one too. Merging to avoid obvious failures .

**Pull request merged**
