### PR TITLE
FIPS install with separate boot

### PR DESCRIPTION
**Pull request by rfan1**
Implement the tests via autoyast

It is REQUIRED to add boot=/dev/sda1 (use the correct path to your boot partition),
or FIPS will fail and the system may not boot. please refer to below link:
https://www.suse.com/support/kb/doc/?id=000019432

- Related ticket: https://progress.opensuse.org/issues/112028
- Verification run:

https://openqa.suse.de/tests/8946699 [x86_Legacy]
https://openqa.suse.de/tests/8950687 [aarch64]
https://openqa.suse.de/tests/8950993 [x86_uefi]
https://openqa.suse.de/tests/8952519 [s390x https://bugzilla.suse.com/show_bug.cgi?id=1200322]
https://openqa.suse.de/tests/8964910 [powervm Setting:KEEP_DISKS=1 ]

### CODE REVIEW

**Review by ShawnHa0 — APPROVED** [review]
LGTM

**Review by wangqianzou — APPROVED** [review]
LGTM

**Comment by jouyingbin** [comment]
@rfan1 Generally LGTM and I just have a bit question.

These 2 VRs without running fips_install_separate_boot_verify, it's the expected result, right?
https://openqa.suse.de/tests/8946699 [x86_Legacy]
https://openqa.suse.de/tests/8950687 [aarch64]

**Comment by rfan1** [comment]
> @rfan1 Generally LGTM and I just have a bit question.
> 
> These 2 VRs without running fips_install_separate_boot_verify, it's the expected result, right? https://openqa.suse.de/tests/8946699 [x86_Legacy] https://openqa.suse.de/tests/8950687 [aarch64]
> 
> note: the VR is hard to open about OSD network issue today :(

Good question, Ben!
Actually, I tried to use some existing jobs to trigger the jobs, in that case I can re-use as many settings as we have :)
Please check the job details for test process

**Review by Amrysliu — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM thaks.

**Pull request merged**
