### PR TITLE
Force sles4sap/hana_cluster test module to run on serial terminal

### PR DESCRIPTION
**Pull request by alvarocarvajald**
This PR has 2 purposes:

1. Force fencing module to run in root-console: Usually, `ha/fencing` module is followed by `boot/boot_to_desktop`, which checks first for a grub screen. In this commit we force fencing module to run in the root-console, so the node reboot goes directly from the console to grub, even on systems installed with gnome. If not doing this, systems installed with gnome will go the long way around of attempting to match the grub needle on the displaymanager and fail after a timeout. This is required because of the 2nd item below.
2. Run HANA nodes on QEMU with **VIRTIO_CONSOLE=1**: To force the tests to use serial console and not the root console which is slower.

- Related ticket: https://jira.suse.com/browse/TEAM-8684 & https://progress.opensuse.org/issues/138113
- Needles: N/A
- Verification run: HanaSR on Maintenance - [node1](https://openqaworker15.qa.suse.cz/tests/250535) & [node2](https://openqaworker15.qa.suse.cz/tests/250534), HanaSR on Product Validation - [node 1](http://openqaworker15.qa.suse.cz/tests/250541) & [node 2](http://openqaworker15.qa.suse.cz/tests/250539)
- Regression tests: 2-node cluster on qemu [node 1](https://openqaworker15.qa.suse.cz/tests/251382) & [node 2](https://openqaworker15.qa.suse.cz/tests/251381), 2-node cluster on svirt [node 1](https://openqa.suse.de/tests/12598772) & [node 2](https://openqa.suse.de/tests/12598773)

### CODE REVIEW

**Comment by emiura** [comment]
LGTM

**Review by lpalovsky — APPROVED** [review]
LGTM

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by alvarocarvajald** [comment]
All qemu VRs passed. svirt (s390x) VRs are still pending.

**Comment by alvarocarvajald** [comment]
s903x jobs failed in an unrelated issue (before `fencing` module). Seems to be a race condition in the `vg` module, as it tries to check for a cluster resource that. I will push more changes to this, so I'll re-request your review once I'm done.

**Comment by alvarocarvajald** [comment]
Pushed a small change to the `ha/vg` test module to fix the failing VR for s390x. Re-reunning HA regression VRs.

**Comment by alvarocarvajald** [comment]
s390x VRs passed. Merging this. Hopefully no `hana_cluster` failures next week.

**Pull request merged**
