### PR TITLE
Boot from HDD with UEFI under svirt backend

### PR DESCRIPTION
**Pull request by mnowaksuse**
POO#15724

Verification run: http://assam.suse.cz/tests/4560

### CODE REVIEW

**Comment by richiejp** [comment]
Is this relevant: https://github.com/os-autoinst/os-autoinst/commit/68c815a9eb6d611efd0609756a75a414ec6f298c ?

**Comment by richiejp** [comment]
Obviously it is a different backend, but maybe a similar fix could apply. Otherwise LGTM.

**Comment by mnowaksuse** [comment]
In svirt we use equivalent of per device `boot orded`, which does not work with UEFI (hence this PR). Will investigate whether `bootindex` works in that case.

**Comment by okurz** [comment]
oops, overlooked the labeld. was it still 'notready'? anyway, not a big change.

**Pull request merged**
