### PR TITLE
netsetup fix: switch via AUTOYAST_USE_NETSETUP

### PR DESCRIPTION
**Pull request by psladek**
as required in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/365#discussion_r28428608

### CODE REVIEW

**Comment by sysrich** [comment]
No...netconfig is wrong, netsetup is right. We don't need both and a
variable to start the right one

**Comment by coolo** [comment]
why didn't you mention that when we discussed it in 365?

**Comment by coolo** [comment]
or in #334 for that matter?

**Comment by sysrich** [comment]
In #334 I made a mistake, should have used netsetup not config

Thatll be the best, simplest, easiest solution

**Comment by coolo** [comment]
I pushed an unconditoinal netsetup now

**Pull request merged**
