### PR TITLE
Fix Mojo::File::spurt() deprecation warning in LTP unit test

### PR DESCRIPTION
**Pull request by mdoucha**
`Mojo::File::spurt()` is deprecated, replace it with `Mojo::File::spew()`.

- Related ticket: N/A
- Needles: N/A
- Verification run: N/A

### CODE REVIEW

**Comment by okurz** [comment]
Curious, https://docs.mojolicious.org/Mojo/File does not mention "spew". @kraih do you know more about deprecation of spurt?

**Comment by mdoucha** [comment]
CPAN does: https://metacpan.org/pod/Mojo::File#spew

**Review by Martchus — APPROVED** [review]
Looks good.

@okurz The related upstream change is https://github.com/mojolicious/mojo/commit/45f1e6091a724ef6380492d751afb9863c324b0d from [v9.34](https://github.com/mojolicious/mojo/releases/tag/v9.34). We might also want to follow-up on that change in os-autoinst and openQA as well (especially because we even might treat these warnings as fatal in tests).

**Comment by Martchus** [comment]
I'm adding the "notready" label because we should not merge this until the new Mojolicious version has been deployed on o3 and OSD workers. At this point v9.34 hasn't even made it to Tumbleweed yet. Note that you can easily test whether this works via e.g. `perl -e "use Mojo::File qw(path); path('/tmp/foo')->spew('test')"`.

**Comment by mdoucha** [comment]
This is a trivial change of unit test. It'll have no effect on actual OpenQA jobs. It just fixes failures in GitHub CI.

**Review by kraih — APPROVED** [review]

**Comment by Martchus** [comment]
Right, this is just the unit test. Then I suppose we can merge it right away.

**Comment by kraih** [comment]
> Curious, https://docs.mojolicious.org/Mojo/File does not mention "spew". @kraih do you know more about deprecation of spurt?

This is the right fix, `spew` replaces `spurt` because of the new direct encoding support that required a new method name. But we will need to also depend on the latest version of Mojolicious, since its a new method.

**Comment by kraih** [comment]
> We should not hard-depend on a new Mojolicious version but consider a gradual deprecation and replacement of such changes.

We will have to depend on 9.34 at some point, because `spew` was added in that release. But i do expect the upstream deprecation period to last quite some time.

**Pull request merged**
