### PR TITLE
Disable kvm module in qemu test for ppc64le

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1153543
Verification: https://openqa.suse.de/t3587881

### CODE REVIEW

**Comment by okurz** [comment]
There might be certain older SLE versions where we still want to have it running resembling what is still supported there.

**Comment by asdil12** [comment]
And which one in particular?
This test is only executed for SLE12 and SLE15 AFAIC and I doubt that there will be a SP6 for SLE12.

**Comment by okurz** [comment]
I see. I guess this is a problem already: IMHO the "qemu" testsuite could be very helpful for QAM.

**Comment by asdil12** [comment]
The qemu testsuite will still run there - just not the kvm test - but kvm on power is not supported anyway.
So even if we would find issues they wouldn't get fixed.

**Comment by okurz** [comment]
could be, fine

**Pull request merged**
