### PR TITLE
Unify names in Helm backend

### PR DESCRIPTION
**Pull request by ilausuch**
- Related ticket: https://progress.opensuse.org/issues/114700
- Verification run: http://marvin5.arch.suse.cz/tests/1100

### CODE REVIEW

**Review by jlausuch — APPROVED** [review]
I guess this should be merged together with job/yaml changes.

**Comment by ilausuch** [comment]
Checked, this doesn't need any change because it is using the default values for PUBLIC_CLOUD_PROVIDER. These are not specified on tests (e.g. http://openqa.suse.de/tests/9259369#settings)

**Review by jlausuch — APPROVED** [review]

**Comment by pdostal** [comment]
Azure is in my opinion not a kubernetes backend. The kubernetes backend is AKS. 
I think that it will be more confusing after more than before.

**Comment by jlausuch** [comment]
Any updates  here?

**Review by pdostal — APPROVED** [review]

**Comment by ilausuch** [comment]
Rebased from the current master

**Review by jlausuch — APPROVED** [review]

**Pull request merged**
