### PR TITLE
Add QE-C members to CODEOWNERS

### PR DESCRIPTION
**Pull request by pdostal**
* [GitHub CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

### CODE REVIEW

**Comment by mloviska** [comment]
Please add me to existing plus
`tests/jeos` and `tests/microos`

**Comment by ricardobranco777** [comment]
Please add me to the publiccloud related directories.

**Comment by jlausuch** [comment]
> Please add me to existing plus `tests/jeos` and `tests/microos`

please add me too, actually add both of us to:
- `tests/transactional`
- `lib/main_micro_alp.pm`
- `lib/main_containers.pm`

**Comment by mloviska** [comment]
> 
>     * `tests/transactional`
> 
>     * `lib/main_micro_alp.pm`
> 
>     * `lib/main_containers.pm`

good point Jose, Pavel please add me here too. Thanks

**Review by jlausuch — COMMENTED** [review]
Thanks!

**Comment by asmorodskyi** [comment]
just realized maybe @mpagot  , @lilyeyes  , @alvarocarvajald or someone else from your team  wants to be notified about every PRs in public cloud area ? 
( don't feel like you taking some **responsibility** by getting into this list , it is just handy way to be notified in set of files which you care in this endless repo :) ) 

if so please create separate PR by adding yourself I think existing CODEOWNERS won't mind ( at least I don't )

**Pull request merged**
