### PR TITLE
Add xml log for kvm mitigation function test

### PR DESCRIPTION
**Pull request by museQi**
Add xml log for kvm mitigation function test.

- Related ticket:https://progress.opensuse.org/issues/130667
- Verification run: http://10.67.129.7/tests/2224#
                                http://10.67.129.7/tests/2218
                                http://10.67.129.7/tests/2122

### CODE REVIEW

**Comment by museQi** [comment]
Hello @XGWang0 @zyuhu, Please help me review. Thanks

**Comment by XGWang0** [comment]
I saw the result of http://10.67.129.7/tests/2218#step/mitigation_off/2, there are no details info in output, how does it help to find the root cause what the subcases are pass or fail?

**Comment by museQi** [comment]
> I saw the result of http://10.67.129.7/tests/2218#step/mitigation_off/2, there are no details info in output, how does it help to find the root cause what the subcases are pass or fail?
Hello John,@XGWang0 Thanks for your review.
Yes,for successful use cases, I don't think it's necessary to list them.So wo add some success  cases and some fail cases.Do you think both successful and failed use cases need to be listed?

**Comment by XGWang0** [comment]
> > I saw the result of http://10.67.129.7/tests/2218#step/mitigation_off/2, there are no details info in output, how does it help to find the root cause what the subcases are pass or fail?
> > Hello John,@XGWang0 Thanks for your review.
> > Yes,for successful use cases, I don't think it's necessary to list them.So wo add some success  cases and some fail cases.Do you think both successful and failed use cases need to be listed?

It's ok if you think it is reasonable.

**Comment by zyuhu** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse Please help me review and merge.

**Pull request merged**
