### PR TITLE
Increase wait for install timeout

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
Without any reasoning?

**Comment by asmorodskyi** [comment]
This is why - https://openqa.suse.de/tests/890914#step/install_and_reboot/21

**Comment by okurz** [comment]
malbec, hm. I guess the full-encrypt makes it slower. I suggest to keep the original timeout and scale it based on parameters, e.g.

```perl
$timeout *= 2 if get_var('ENCRYPT');
```

**Comment by okurz** [comment]
no, please scale with multiplier.

**Comment by asmorodskyi** [comment]
@okurz  will do it as he see it , closing this PR

**Pull request closed without merging**
