### PR TITLE
WIP: systemd-testsuite: improve testsuite run time

### PR DESCRIPTION
**Pull request by eliroca**
This reverts commit d34a9b86e3c0a52977dbd350f5a1dc7d09552b7b.
As discussed with @tblume, reverting this commit will reduce the job time.

Also increase timeouts for all tests, since systemd v246 testsuite will run tests in QEMU, like upstream. 

Verification runs:
TW: http://emerson.suse.de/tests/2490
15-SP3: http://emerson.suse.de/tests/2493

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@eliroca, could you make 10 verification runs on SLE15-SP3 aarch64?

**Comment by eliroca** [comment]
@SergioAtSUSE I haven't taken aarch64 or other architectures into account.. Thanks for pointing that out

**Comment by tblume** [comment]
Eli, ok if I do the test runs for SLE15SP3 and submit these patches together with my additions?

**Comment by eliroca** [comment]
@tblume go ahead :)

**Pull request closed without merging**
