### PR TITLE
Also run the update part for INSTALLONLY test

### PR DESCRIPTION
**Pull request by nilxam**
We've update-test in update channel on 42.3. https://openqa.opensuse.org/tests/332430

### CODE REVIEW

**Comment by coolo** [comment]
this will make it run on tons of more jobs. But if you prefer...

**Comment by okurz** [comment]
I don't understand the purpose of this change and IMHO the word "INSTALLONLY" does not really go in line with "… but test updating"

**Comment by coolo** [comment]
the problem with these "tests" is that they also update - and not only test it

**Comment by okurz** [comment]
yes but whenever the generated images are used there can be new updates anyway so what's the point in updating something that can be out of date on use again?

**Comment by nilxam** [comment]
what do "out-of-date" meaning here? and it's ``update-test`` in the update repo.

**Comment by okurz** [comment]
1. IMHO "INSTALLONLY" and "… but test updating" should not be done together, the words don't fit -> find better names
2. It might work as it is now for Leap 42.3 but for how long? As soon as there are more updates in the update channels for Leap 42.3 I assume they might come in between the time when "gnome-image" generates an image and a job is using the new image. Then the job using the image will also have to check for updates. So I don't understand what should be actually fixed by this change. Should it just make the notification for new updates "go away"? If yes I think it's not a safe or correct approach.

**Comment by nilxam** [comment]
for 1) I can't see the impact.
for 2) what jobs are using the new image but doing ``test updating`` again? the main goal is ensure "new updates notification will not block -image test", if you prefer another approach please do so then.

**Comment by okurz** [comment]
no, it's fine. We'll see :-)

**Pull request merged**
