### PR TITLE
fix textmode with key_round function for sle11 & sle12

### PR DESCRIPTION
**Pull request by dzedro**
ref. http://10.100.98.90/tests/581

### CODE REVIEW

**Comment by sysrich** [comment]
It's a faulty tab for SLE 12..but what about SLE11, isn't the Tab needed there?

**Comment by dzedro** [comment]
for sle11 is sle11_change_desktop.pm

**Comment by coolo** [comment]
... which is using the same function

**Comment by dzedro** [comment]
ah yes, i got it now ... I will fix my fix

**Comment by dzedro** [comment]
sle11 http://10.100.98.90/tests/593
sle12 http://10.100.98.90/tests/594

**Comment by dzedro** [comment]
I will open PR to use just change_desktop.pm

**Comment by coolo** [comment]
great idea

**Comment by coolo** [comment]
the change is clever I mean - opening a PR is good too ;)

**Comment by dzedro** [comment]
wanted to add delete of sle11_change_desktop here, but
I like the complicated way of doing things & coolo is fast :)

**Comment by coolo** [comment]
I pull the requests faster than my shadow :gun:

**Comment by sysrich** [comment]
If coolo was a superhero he'd be The Bald Blur

**Pull request merged**
