### PR TITLE
trinity: switch to latest trinity version

### PR DESCRIPTION
**Pull request by asmorodskyi**
Latest stable version 1.8 stop compiling with latest kernel which we using https://openqa.suse.de/tests/2341667 . This force us to switch to latest master of trinity in github ( pre1.9 version ) 

prove run - http://kimball.arch.suse.de/tests/354

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@plusky , @metan-ucw you were right after all :) using 1.8 is dead end

**Comment by pevik** [comment]
LGTM, nice you fixed it :).
Small perl tidy issue.

**Comment by asmorodskyi** [comment]
#6504 needs to be merged before I can continue with this one

**Comment by asmorodskyi** [comment]
prove run for latest version of code 
http://kimball.arch.suse.de/tests/422

**Comment by jlausuch** [comment]
LGTM

**Pull request merged**
