### PR TITLE
Partial revert of "wicked: enable cleanup_before_shutdown"

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by okurz** [comment]
I agree with Vogtinator. This looks really wrong to me as well.

**Comment by asmorodskyi** [comment]
I get your message guys , but can we move on ? I totally agree that removing this file is no-sense from pure "dev-ops" perspective . But from testing perspective it depends on a lot of factors , mainly running around question - "What you trying to prove by your test ? " .  After all tests actually expected to create not supported and synthetic environments to prove something in software under test. Other tests can run in partially broken environments too if it is proven that "broken part" not directly interact with software under test.

**Comment by DimStar77** [comment]
as commeted on IRC:

I can live with this PR - I'd like to see a more complex commit message though, better explaining the reasoning

**Comment by asmorodskyi** [comment]
@Vogtinator  , @DimStar77 , @okurz  - need LGTM from one of you to merge this . Commit message updated with novel about issue :)

**Comment by asmorodskyi** [comment]
so waiting for Travis and I will merge than ...

**Pull request merged**
