### PR TITLE
SLE Micro: add softfailure for systemd update

### PR DESCRIPTION
**Pull request by jlausuch**
As requested by Jiri Srain, adding a soft-failure for this. More details in [bsc#1182500](https://bugzilla.suse.com/show_bug.cgi?id=1182500)

### CODE REVIEW

**Review by Vogtinator — APPROVED** [review]

**Comment by Vogtinator** [comment]
A public bug report instead would be nice...

**Comment by jsrain** [comment]
> A public bug report instead would be nice...

Can I make the bug public other than changing the product (then it slips off my radar)?

**Comment by Vogtinator** [comment]
> > A public bug report instead would be nice...
> 
> Can I make the bug public other than changing the product (then it slips off my radar)?

Unfortunately I can't answer that.

Ideally, the product itself would default to public, so that internal bug reports can be marked as such.

**Comment by jsrain** [comment]
> > > A public bug report instead would be nice...
> > 
> > 
> > Can I make the bug public other than changing the product (then it slips off my radar)?
> 
> Unfortunately I can't answer that.
> 
> Ideally, the product itself would default to public, so that internal bug reports can be marked as such.

I will keep it for the discussion when we do next version, if we have a public beta (which I hope) it make way more sense.

**Comment by okurz** [comment]
> 
> 
> > A public bug report instead would be nice...
> 
> Can I make the bug public other than changing the product (then it slips off my radar)?

if this is true I am pretty sure your radar is wrong :)

I suggest https://progress.opensuse.org/projects/qa/wiki#Test-results-overview with some bugzilla links that can help to keep an overview.

**Pull request merged**
