### PR TITLE
Add is_sle_micro for open ssh checking

### PR DESCRIPTION
**Pull request by waynechen55**
* **Add** is_sle_micro for open ssh checking

### CODE REVIEW

**Comment by waynechen55** [comment]
@punkioudi @alice-suse  If you think this is helpful, you can just merge this directly. Anyway anyone can solve problem by any other ways. Thanks.

**Comment by punkioudi** [comment]
Hi Wayne, thanks for the PR! 
I would suggest that you add some verification runs before we merge, as this module is being used in different places in osd :)

**Comment by waynechen55** [comment]
> Hi Wayne, thanks for the PR! I would suggest that you add some verification runs before we merge, as this module is being used in different places in osd :)

Of course, I thought you can just apply this for emergency. 
Anyway I did two verification runs. I think it is enough. I added is_sle_micro, so:
It still works for sle micro [verification run 1](http://10.67.131.12/tests/849)
And now it works for sles as well because it is not sle micro [verification run 2](http://10.67.131.12/tests/851)

**Review by punkioudi — APPROVED** [review]
lgtm!

**Pull request merged**
