### PR TITLE
btrfs_qgroups: Accept solution for bsc#1019614, test for real quota

### PR DESCRIPTION
**Pull request by okurz**
Verification run: http://lord.arch/tests/6120#step/btrfs_qgroups/64

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
LGTM

**Comment by coolo** [comment]
And again: this "fix" only applies to current SP3, while the test runs for SP2 too. Please fix the test to work on both

**Comment by okurz** [comment]
it helps if you provide a link to a failing job so that we can fix it faster. I was assuming [bsc#1019614](http://bugzilla.suse.com/1019614) to be fixed for all versions but that apparently is not yet the case. I am on it

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2702

**Pull request merged**
