### PR TITLE
Mitigation adaption for xen hvm and pv

### PR DESCRIPTION
**Pull request by museQi**
Xen mitigation adaption for hvm and pv on sle15sp6,because of the changes
- Related ticket: https://progress.opensuse.org/issues/151352;  https://progress.opensuse.org/issues/151355
- Verificationrun:http://10.67.129.4/tests/73044; http://10.67.129.4/tests/73113; http://10.67.129.4/tests/73112; http://10.67.129.4/tests/73137; http://10.67.129.4/tests/73134; http://10.67.129.4/tests/73128

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @zyuhu please help me review.

**Comment by XGWang0** [comment]
LGTM

**Comment by zyuhu** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse Please help me merge.

**Pull request merged**
