### PR TITLE
extra_tests_textmode: Only run aplay, soundtouch, wavpack, steamcmd on x86_64

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/77653
Verification:
ppc64le: https://openqa.opensuse.org/t1468488
aarch64: https://openqa.opensuse.org/t1468490
x86_64: https://openqa.opensuse.org/t1468492

### CODE REVIEW

**Comment by ggardet** [comment]
Why drop support for aarch64? We have sound support on aarch64.

**Comment by asdil12** [comment]
Ah we do? - I'll update.

**Comment by ggardet** [comment]
LGTM, thanks! 👍

**Comment by michelmno** [comment]
above verification ppc64le triggered on old snapshot failing for other reason https://openqa.opensuse.org/t1468488
propose other one on active snapshot https://openqa.opensuse.org/tests/1468640

**Comment by asdil12** [comment]
> above verification ppc64le triggered on old snapshot failing for other reason https://openqa.opensuse.org/t1468488
> propose other one on active snapshot https://openqa.opensuse.org/tests/1468640

I did that on purpose as the refspec script can't clone from jobs that are still running.

**Pull request merged**
