### PR TITLE
Workaround for bsc#1215591

### PR DESCRIPTION
**Pull request by rfan1**
https://bugzilla.suse.com/show_bug.cgi?id=1215591
At the same time, I used 'dos2unix' command to change the file to Unix format

- Verification run: https://openqa.suse.de/tests/12219080

**The current workaround is set `/root` as the first partition**

### CODE REVIEW

**Comment by hjluo** [comment]
how about we just change the partition in partitioning part, which will show we just address "/root as the first partition:

**Comment by rfan1** [comment]
> how about we just change the partition in partitioning part, which will show we just address "/root as the first partition:

Good comment, let me use 2 commits then

**Comment by rfan1** [comment]
> > how about we just change the partition in partitioning part, which will show we just address "/root as the first partition:
> 
> Good comment, let me use 2 commits then

Now the commit 1 can show the partition changes 
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17838/commits/b25c0b8fc6e1a6557a26462d41346f60e138f811

**Review by lemon-suse — APPROVED** [review]

**Review by hjluo — APPROVED** [review]
LGTM&&Thanks for the fixing.

**Pull request closed without merging**
