### PR TITLE
Add QEMU_DISABLE_SNAPSHOTS=1 in HA yaml schedules

### PR DESCRIPTION
**Pull request by alvarocarvajald**
We need to disable QEMU snapshots in MM HA tests.

- Related ticket: N/A
- Needles: N/A
- Verification run: N/A

### CODE REVIEW

**Review by ldevulder — APPROVED** [review]
LGTM

**Review by juadk — APPROVED** [review]

**Comment by okurz** [comment]
I suggest to provide more explanations into file-comments as well as git commit messages. Your message simply says "do it" but no explanation for the reason or what could be checked in case someone in the future either wants to remove the flag for another advantage or tries to fix a consequence of that change. Without an explanation it's really staggering in the dark what you might have encountered which made you think that you need this. And also unfortunately the approvals by others does not help if there is only the "boolean" information of someone approving.

**Comment by alvarocarvajald** [comment]
> I suggest to provide more explanations into file-comments as well as git commit messages. Your message simply says "do it" but no explanation for the reason or what could be checked in case someone in the future either wants to remove the flag for another advantage or tries to fix a consequence of that change. Without an explanation it's really staggering in the dark what you might have encountered which made you think that you need this. And also unfortunately the approvals by others does not help if there is only the "boolean" information of someone approving.

100% in agreement. Explanation as file-comments are forthcoming while we continue migrating the HA test suites to yaml schedules/yaml job group configuration in the upcoming weeks. My goal is to have for all files something like this: https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/schedule/sles4sap/hana/pvm_hana_cluster_node.yaml

In the meantime I do not want false positives in the job group with the current builds.

**Comment by okurz** [comment]
Absolutely. That makes sense. Keep in mind, adding comments into the YAML files will be perfectly fine.

**Pull request merged**
