### PR TITLE
Add autoyast_create_hdd_gnome test case  modify_existing_partition on PowerVM

### PR DESCRIPTION
**Pull request by hjluo**
We need to add autoyast_create_hdd_gnome for modify_existing_partition
in PowerVM.

- Related ticket: https://progress.opensuse.org/issues/110773#note-14
- Related MR:  https://gitlab.suse.de/qsf-y/qa-sle-functional-y/-/merge_requests/443/
- Needles: N/A
- Verification run: 
   https://openqa.suse.de/tests/10048974
   https://openqa.suse.de/tests/10048975

### CODE REVIEW

**Comment by jknphy** [comment]
please, modify 'spvm' for 'PowerVM' in the commit to not get that confusion we saw.

**Comment by hjluo** [comment]
> please, modify 'spvm' for 'PowerVM' in the commit to not get that confusion we saw.

Done

**Comment by hjluo** [comment]
> It is the AutoYaST profile what we need to clone(=duplicate) to avoid that someone would change the mini. Yaml files and test data files might be reused depending on the case.
so how to reuse it?
<<: !include schedule/yast/autoyast/autoyast_mini_spvm.yam in autoyast_create_hdd_gnome.yaml ? Thanks

**Comment by hjluo** [comment]
> It is the AutoYaST profile what we need to clone(=duplicate) to avoid that someone would change the mini. Yaml files and test data files might be reused depending on the case.

cloned.

**Comment by hjluo** [comment]
@jknphy  please take a look again, thanks!

**Pull request merged**
