### PR TITLE
Execute chain of commands in container

### PR DESCRIPTION
**Pull request by mloviska**
Pass multiple commands in $runtine run command.

- Related ticket: https://progress.opensuse.org/issues/90701#note-5
- Verification run: [hvm](http://kepler.suse.cz/tests/4374)

### CODE REVIEW

**Comment by mloviska** [comment]
Sorry, there are still 3 occurrences of the same problem http://kepler.suse.cz/tests/4384#step/buildah_podman/36

**Review by b10n1k — APPROVED** [review]
+1

**Comment by Vogtinator** [comment]
I don't see how this diff makes a difference, the previous code should work just fine.

Looking at the log and your message on the ticket
> script_output's ctrl-d action sometimes logs out the current console.

My guess is that `ctrl-d` is pressed for too long, so it doesn't just send an EOF to cat, automatic key repeat also sends the EOF to the shell.

QEMU doesn't do autorepeat over VNC FWICT, but in the HyperV tests it connects to `Xvnc` with `xfreerdp` running, so any of those layers might.

**Comment by Vogtinator** [comment]
> QEMU doesn't do autorepeat over VNC FWICT, but in the HyperV tests it connects to `Xvnc` with `xfreerdp` running, so any of those layers might.

I did a quick test: `Xvnc` started with `-r` does not send repeated key events, but without that option it does. So the fix might be to just pass that option.

**Comment by mloviska** [comment]
> I don't see how this diff makes a difference, the previous code should work just fine.
I think the complex chain of commands did not reached the container completely
https://progress.opensuse.org/issues/90701#note-5
So I assume over here https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/containers/common.pm#L219 we need to invoke shell as we do in the other branch https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/containers/common.pm#L226
> 
> Looking at the log and your message on the ticket
> 
> > script_output's ctrl-d action sometimes logs out the current console.
> 
> My guess is that `ctrl-d` is pressed for too long, so it doesn't just send an EOF to cat, automatic key repeat also sends the EOF to the shell.
> 
Eventually I have notice from the video, that we get this error.
https://progress.opensuse.org/attachments/11174/failure.jpg
> QEMU doesn't do autorepeat over VNC FWICT, but in the HyperV tests it connects to `Xvnc` with `xfreerdp` running, so any of those layers might.

**Comment by Vogtinator** [comment]
> Eventually I have noticed from the video, that we get this error.

Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?

**Comment by mloviska** [comment]
> > Eventually I have noticed from the video, that we get this error.
> 
> Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?

Let me check and I will get back to you. Thanks for hint!

**Comment by mloviska** [comment]
> > Eventually I have noticed from the video, that we get this error.
> 
> Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?

http://kepler.suse.cz/tests/4400#step/buildah_podman/54

**Comment by Vogtinator** [comment]
According to `/usr/include/asm-generic/fcntl.h` that is `O_LARGEFILE`. Unless stdin is somehow a file, that makes absolutely no sense...

**Comment by Vogtinator** [comment]
Can you put the fdinfo read into multple places during the test run so that we can track down where it's coming from? It's not O_NONBLOCK, but still weird...

**Comment by mloviska** [comment]
> Can you put the fdinfo read into multple places during the test run so that we can track down where it's coming from? It's not O_NONBLOCK, but still weird...

Sure, ofc!

**Comment by Vogtinator** [comment]
> > > Eventually I have noticed from the video, that we get this error.
> > 
> > 
> > Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?
> 
> http://kepler.suse.cz/tests/4400#step/buildah_podman/54

Actually, that is not run in the same console as the `cat` which fails, so the output here doesn't necessarily help that much. Maybe replace the breaking `cat` command with a cat of the `fdinfo` file? That way it's run in the right environment

**Comment by mloviska** [comment]
> > > > Eventually I have noticed from the video, that we get this error.
> > > 
> > > 
> > > Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?
> > 
> > 
> > http://kepler.suse.cz/tests/4400#step/buildah_podman/54
> 
> Actually, that is not run in the same console as the `cat` which fails, so the output here doesn't necessarily help that much. Maybe replace the breaking `cat` command with a cat of the `fdinfo` file? That way it's run in the right environment

I was thinking whether it makes sense or not. Ok, I will do! Thanks

**Comment by Vogtinator** [comment]
I just checked - on a tty like this, `O_LARGEFILE` is actually normal as it's always set when opening anything. So that's definitely unrelated.

**Comment by mloviska** [comment]
> > > > Eventually I have noticed from the video, that we get this error.
> > > 
> > > 
> > > Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?
> > 
> > 
> > http://kepler.suse.cz/tests/4400#step/buildah_podman/54
> 
> Actually, that is not run in the same console as the `cat` which fails, so the output here doesn't necessarily help that much. Maybe replace the breaking `cat` command with a cat of the `fdinfo` file? That way it's run in the right environment

I have put `type_string` call with the `fdinfo` after https://github.com/os-autoinst/os-autoinst/blob/master/distribution.pm#L295 and added here and there within the `lib`. 
Here is an example of ok run http://kepler.suse.cz/tests/4403#step/buildah_podman/50. Thus, it is O_RDWR + O_APPEND + O_LARGEFILE? All of them are taken within `tty6`

**Comment by Vogtinator** [comment]
Yeah, that looks like a valid combination. The `O_APPEND` is a bit strange, but for a TTY it shouldn't matter.

**Comment by mloviska** [comment]
> > Eventually I have noticed from the video, that we get this error.
> 
> Ok, that's not input related at all then. `EAGAIN` while reading from stdin implies that it has `O_NONBLOCK` set, which is odd. If this is reproducible (or maybe even when it doesn't fail), what's the content of `/proc/self/fdinfo/0`?

http://kepler.suse.cz/tests/4407/file/video.ogv#t=111.54,111.58
https://progress.opensuse.org/attachments/11216/error_fdinfo_flags.jpg

0106002 (**O_NONBLOCK** included!)

**Comment by Vogtinator** [comment]
Great, so we're onto something! Unfortunately that also means that it's not reliably reproducible and probably relies on timing. At least we can tell that it's most likely one of the two `buildah` calls. With some luck it might be reproducible by running those commands in a loop until `O_NONBLOCK` sticks, but maybe just running them through `strace -kfetrace=fcntl` shows the issue.

My guess is that it sets `O_NONBLOCK` "temporarily" to poll for input, but for some reason (abnormal exit, race on cleanup?) doesn't undo that.

**Comment by mloviska** [comment]
[strace_buildah_openqa.txt](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/6324505/strace_buildah_openqa.txt)

**Comment by Vogtinator** [comment]
> [strace_buildah_openqa.txt](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/6324505/strace_buildah_openqa.txt)

I filed https://github.com/containers/buildah/issues/3152

**Comment by mloviska** [comment]
> > [strace_buildah_openqa.txt](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/6324505/strace_buildah_openqa.txt)
> 
> I filed [containers/buildah#3152](https://github.com/containers/buildah/issues/3152)

Thanks!
So are you ok with the updates that are executing the `uname` and `echo` in container? As it is described in the snippets https://progress.opensuse.org/issues/90701#note-5 ?

**Comment by Vogtinator** [comment]
How does that make a difference?

**Comment by mloviska** [comment]
> How does that make a difference?

```
# set -x;buildah run sle15-working-container /bin/uname -r; /bin/echo 'Heartbeat from registry.suse.com/suse/sle15:15.3'; ps; echo LsI4D-$?-
+ set -x
+ buildah run sle15-working-container /bin/uname -r
5.3.18-54-default
+ /bin/echo 'Heartbeat from registry.suse.com/suse/sle15:15.3'
Heartbeat from registry.suse.com/suse/sle15:15.3
+ ps
  PID TTY          TIME CMD
 2049 hvc0     00:00:00 bash
 8112 hvc0     00:00:00 ps
+ echo LsI4D-0-
```

Maybe I am misinterpreting the output, but I to me it seems like buildah run executes only uname not the echo.

**Comment by Vogtinator** [comment]
Ah, I wasn't looking at line 219, only 226, where `$smoketest` is also used. Yes, the old code has a bug, but that doesn't seem to be related to the `O_NONBLOCK` issue actually

**Review by Vogtinator — APPROVED** [review]

**Comment by mloviska** [comment]
> Ah, I wasn't looking at line 219, only 226, where `$smoketest` is also used. Yes, the old code has a bug, but that doesn't seem to be related to the `O_NONBLOCK` issue actually

Yes, it is unrelated. I have just noticed that while reviewing the code. :) Thanks for your confirmation!

**Review by pdostal — APPROVED** [review]

**Pull request merged**
