### PR TITLE
Fix addon product on text mode for SLE15SP2 offline installation

### PR DESCRIPTION
**Pull request by JoyceNa**
fix addon products on text mode offline installation

    Related ticket: N/A
    Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1263
    Verification run: http://10.67.132.78/tests/33

### CODE REVIEW

**Comment by Julie-CAO** [comment]
Perfect. I think our virtualization tests can install host offline with this PR as well.

**Comment by Julie-CAO** [comment]
but one question: why do we have to set both "ADDONS=all-packages" and "SCC_ADDONS=legacy,desktop,hpc" to call handle_all_packages_medium{}? why not make ADDONS=legacy,desktop,hpc work directly for offline installation?

**Comment by JoyceNa** [comment]
> but one question: why do we have to set both "ADDONS=all-packages" and "SCC_ADDONS=legacy,desktop,hpc" to call handle_all_packages_medium{}? why not make ADDONS=legacy,desktop,hpc work directly for offline installation?

Actually I just try this way of settings,and it works for our cases.I think you can setup your configure with your scenario.

**Comment by alice-suse** [comment]
LGTM

**Pull request merged**
