### PR TITLE
Create a YAML schedule to install the agama based leap16.0

### PR DESCRIPTION
**Pull request by DeepthiYV**
- Related ticket: https://progress.opensuse.org/issues/164141
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

### CODE REVIEW

**Comment by lkocman** [comment]
Fails at ("Can't locate object method \"new\" via package \"agama\" at /usr/"...)

I suppose we need to have agama.pm inside, based on the log it always seems to process /var/lib/openqa/pool/30/os-autoinst-distri-opensuse/lib/main_common.pm  and so on, so if the reference doesn't exist it fails.

**Comment by lkocman** [comment]
I'd personally merge it and polish it after.

**Comment by lkocman** [comment]
https://openqa.opensuse.org/tests/4371295#live triggered it thank you @DeepthiYV

**Comment by DeepthiYV** [comment]
As suggested by Lubos,  will merge this PR, and he will make required changes and create a new PR later.

**Pull request merged**
