### PR TITLE
Echo brackets in regex

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@kravciak this should solve the issue , right ?
and again thank you for keeping eye on this !

**Comment by nicksinger** [comment]
Code is LGTM. But I'm missing the proof + proper commit message ;)

**Comment by kravciak** [comment]
Right, this fixes the issue - you can also be more specific with (but that's up to you):
```
addr:.*\[dhcp\]$
```
LGTM even without proof run :)

**Comment by okurz** [comment]
Backets?

**Comment by asmorodskyi** [comment]
yes , sure . you know this "a shallow wooden box used especially to carry fuel or ashes" ? :D  

P.S. I will add missed 'r' of course but tomorrow ...

**Pull request merged**
