### PR TITLE
[Virtualization][SLM] Specify disk id in usb host installation

### PR DESCRIPTION
**Pull request by alice-suse**
This PR aims to install SLE Micro to a specified disk, so that SLES VT tests can run on the same UEFI machine with SLE Micro test machine, without "secure boot" problem mentioned in https://progress.opensuse.org/issues/153037#note-36 by Julie.

- Related ticket: https://progress.opensuse.org/issues/166712
- Verification run: 
  - SLM 6.1 host: https://openqa.suse.de/tests/15426202#step/bootloader_uefi/27
  - SLM 6.0 GM host verification: https://openqa.suse.de/tests/15461667#step/login_console/5 (simulate 6.0  job by passing ISO=SL-Micro.x86_64-6.0-Default-SelfInstall-GM.iso)
  - more evidence jobs for claiming that installing on the same disk solves the "secure boot" problem: https://progress.opensuse.org/issues/166712#note-11

### CODE REVIEW

**Comment by alice-suse** [comment]
@Julie-CAO  @nanzhg @waynechen55  Welcome to review!

**Comment by Julie-CAO** [comment]
LGTM

**Comment by nanzhg** [comment]
Does the verification of slem6.1 run go through the code changes? I don't see it ran passed with these two test modules. (http://openqa.suse.de/tests/15426085)

**Comment by alice-suse** [comment]
> Does the verification of slem6.1 run go through the code changes? I don't see it ran passed with these two test modules. (http://openqa.suse.de/tests/15426085)

My bad. Please check this link , https://openqa.suse.de/tests/15426202#step/bootloader_uefi/27

**Comment by nanzhg** [comment]
> > Does the verification of slem6.1 run go through the code changes? I don't see it ran passed with these two test modules. (http://openqa.suse.de/tests/15426085)
> 
> My bad. Please check this link , https://openqa.suse.de/tests/15426202#step/bootloader_uefi/27

It's OK, LGTM

**Comment by alice-suse** [comment]
Thank you guys for the review! Can anyone click the merge button? It is not proper that the PR author merges the PR ;-)

**Pull request merged**
