### PR TITLE
Reuse the mapping of INCIDENTNR for openSUSE

### PR DESCRIPTION
**Pull request by coolo**
Align the way SLE and openSUSE test maintenance - first step

@mimi1vx

### CODE REVIEW

**Comment by coolo** [comment]
http://tortuga.suse.de/tests/188 for openSUSE

**Comment by mimi1vx** [comment]
lgtm , any testrun for SLE ?

**Comment by coolo** [comment]
not yet. Which scenario shall I pick?

**Comment by coolo** [comment]
http://tortuga.suse.de/tests/193 - picked qam-gnome

**Pull request merged**
