### PR TITLE
Containers: create schedule for only container packages and features

### PR DESCRIPTION
**Pull request by jlausuch**
This schedule doesn't include the test of official images.

### CODE REVIEW

**Review by asmorodskyi — APPROVED** [review]
LGTM

**Comment by asmorodskyi** [comment]
what about `extra_tests_textmode_containers.yaml` is someone using it ?

**Comment by pdostal** [comment]
> what about `extra_tests_textmode_containers.yaml` is someone using it ?

I scanned through Medium types and Test suites in O3 and OSD and found nothing.

**Comment by asmorodskyi** [comment]
> > what about `extra_tests_textmode_containers.yaml` is someone using it ?
> 
> I scanned through Medium types and Test suites in O3 and OSD and found nothing.

```
select distinct group_id,test,version,flavor from jobs where id in (select job_id from job_settings where key='YAML_SCHEDULE' and value='schedule/containers/extra_tests_textmode_containers.yaml') and group_id is not null;
 group_id |       test       | version |       flavor       
----------+------------------+---------+--------------------
      313 | containers_basic | 15-SP2  | Online
      313 | containers_basic | 15-SP3  | Online
      352 | containers_basic | 15-SP2  | Server-DVD-Updates
      353 | containers_basic | 15-SP1  | Server-DVD-Updates
      354 | containers_basic | 12-SP4  | Server-DVD-Updates
      355 | containers_basic | 12-SP5  | Server-DVD-Updates
      357 | containers_basic | 15      | Server-DVD-Updates
      358 | containers_basic | 12-SP3  | Server-DVD-Updates
      369 | containers_basic | 15-SP3  | Server-DVD-Updates
```

**Pull request merged**
