### PR TITLE
SLE Micro: fix s390x installation

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/93125

### CODE REVIEW

**Comment by asdil12** [comment]
Please run `./tools/tidy` to make the testsuite happy.

**Comment by jlausuch** [comment]
> Please run `./tools/tidy` to make the testsuite happy.

yeah, sorry. Added WIP as I'm postponing this to next week :)

**Comment by mloviska** [comment]
Current issue, after `btrfs quota rescan` runs somewhere in the background.

* [sle-micro_autoyast](https://openqa.suse.de/tests/6317265#step/transactional_update/249)
* [sle-micro_installation+update](https://openqa.suse.de/tests/6317236#step/transactional_update/249)

**Comment by mloviska** [comment]
> Current issue, after `btrfs quota rescan` runs somewhere in the background.
> 
>     * [sle-micro_autoyast](https://openqa.suse.de/tests/6317265#step/transactional_update/249)
> 
>     * [sle-micro_installation+update](https://openqa.suse.de/tests/6317236#step/transactional_update/249)

In order to at least deploy and continue with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12759 I will merge this PR and kernel message issue, can be addressed later.

**Comment by jlausuch** [comment]
Thanks Martin!

**Pull request merged**
