### PR TITLE
Unlocking LUKS volumes with TPM2 key

### PR DESCRIPTION
**Pull request by rfan1**
Base on https://jira.suse.com/browse/SLE-18822
We can unlock full disk encryption devices via
FIDO2 (notebooks) or TPM2 (Server, Edge)

- Related ticket: https://progress.opensuse.org/issues/107488
- Needles: n/a
- Verification run:
https://openqa.opensuse.org/tests/2235259 -TW
https://openqa.suse.de/tests/8296515            -SLE

### CODE REVIEW

**Comment by lilyeyes** [comment]
Can these two yaml schedule file merged to one?

**Review by lilyeyes — APPROVED** [review]
Generally  looks good to me after discussed offline.

**Comment by lilyeyes** [comment]
Btw, do you have plan to run this case on other arches?

**Comment by rfan1** [comment]
> Btw, do you have plan to run this case on other arches?

Yes, but not for now, I will file a new ticket to automate it on aarch64 platform as well.

**Review by jouyingbin — APPROVED** [review]
LGTM, great.

**Review by Amrysliu — APPROVED** [review]

**Pull request merged**
