### PR TITLE
Add four new ltp subtest to regression test

### PR DESCRIPTION
**Pull request by SeroSun**
Add four new ltp subtest to regression test
ltp_connectors
ltp_fcntl_locktests
ltp_filecaps
ltp_hugetlb

### CODE REVIEW

**Comment by sysrich** [comment]
These appear to be missing `use strict;` as introduced in #1310

**Comment by coolo** [comment]
i.e. run make perlcritic

**Comment by coolo** [comment]
(we missed it for slepost tests too)

**Comment by SeroSun** [comment]
@sysrich I think "use strict" is in "use base 'qa_run'".

**Comment by coolo** [comment]
use strict only matters for the file it's in

**Comment by SeroSun** [comment]
@coolo thanks, got it, then all the test script in this folder need to add this line...

**Comment by SeroSun** [comment]
@coolo could you please help to merge it, thanks :)

**Pull request merged**
