### PR TITLE
Add clean target to Makefile

### PR DESCRIPTION
**Pull request by asmorodskyi**
@coolo , @okurz  it's my own idea didn't discuss it with anyone. Just don't know how you doing this without clean ? Sorry if I miss something obvious ...

### CODE REVIEW

**Comment by okurz** [comment]
How working without clean? I added these directories and files to .git/info/exclude and on anything else I use `git clean -df`

I wouldn't mind the clean target but I assume especially with DVCS it gets more and more superfluous

**Comment by asmorodskyi** [comment]
why not to .gitignore ? it already contains 'needles' :)
your solution need to be repeated on every new clone of this repo. And answer "Yeah but only one time" don't work for me.

**Comment by okurz** [comment]
@coolo you so you know, I didn't teach him this stubbornness, he was like this from the beginning ;-)

Not in .gitignore because maybe someone wants not to ignore what make put there automatically, as you do with `make clean`, either way works

**Comment by coolo** [comment]
why would I want to clean to begin with?

**Comment by okurz** [comment]
I guess because this was the common way to simplify patch submission in pre-VCS days

**Comment by asmorodskyi** [comment]
after run "make prepare" your git repo is dirty and next "git status" will give you changed repository state which for example block me from using "git add ." to add everything that I really change in my repo in one command .

**Comment by coolo** [comment]
just don't git add . - how many files did you add that you need this? :)

git commit -a will only commit changed files

**Comment by asmorodskyi** [comment]
After discussion with @okurz  I changed my PR. Let's just add files to gitignore it will not harm

**Comment by coolo** [comment]
I can see that. If you have the choice between discussing with @okurz and changing your PR, even the most stubborn change their mind :)

**Pull request merged**
