### PR TITLE
Replace exclamation mark in bash script

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by DimStar77** [comment]
As discussed on IRC - this results in a different bash syntax error, as assert_script_run adds ```; echo xxxxxx-$?-```; and as the last command of the script ```done``` contains a \n, assert_script_run's extension is on a new line, which in turn is invalid syntax

**Comment by asmorodskyi** [comment]
Fixed http://kimball.arch.suse.de/tests/1027

**Comment by asmorodskyi** [comment]
this test should not fail constantly because any bash changes anyway. So I would prefer to change behavior of this test nevertheless to more stable. And if you want check bash-completion you need to add bash-completion module/test and not test this in wicked job. Which is already "wicked"  don't increase this :)

**Comment by okurz** [comment]
Well, for now your wicked test *is* the bash completion test :) If you create another explicit module, sure we can get rid of the implicit test in wicked

**Comment by DimStar77** [comment]
btrfs-completion already exists and is more suitable as a bash-completion test

**Comment by asmorodskyi** [comment]
LGTM from @okurz

**Pull request merged**
