### PR TITLE
agree the license in case the license checkbox is appear

### PR DESCRIPTION
**Pull request by nilxam**
https://openqa.opensuse.org/tests/102800/modules/installation_mode/steps/1

### CODE REVIEW

**Comment by coolo** [comment]
No, you're hiding a bug. TW has no license to aggree to.

**Comment by nilxam** [comment]
hmm..so https://build.opensuse.org/request/show/346360 is questionable

**Comment by coolo** [comment]
absolutely. if you can get hold of Ludwig in Taipei, tell him :)

**Comment by nilxam** [comment]
ok, I'll prepare the rope :P

**Pull request closed without merging**
