### PR TITLE
Remove mount_by_label test for JeOS on aarch64 openSUSE - boo#1127959

### PR DESCRIPTION
**Pull request by ggardet**
https://bugzilla.opensuse.org/show_bug.cgi?id=1127959

### CODE REVIEW

**Comment by Vogtinator** [comment]
@ccret, @mnowaksuse: Maybe the test should be dropped entirely? I don't see any technical reason for mounting by label.

**Comment by mnowaksuse** [comment]
There may have been a technical reason in the early days of JeOS, but I doubt there is one now. Though, mounting by label is SUSE JeOS product requirement (it was interpreted that way at least), see https://bugzilla.opensuse.org/show_bug.cgi?id=1127959#c8.

**Comment by ggardet** [comment]
What should we do here:
a-Accept this SR
b-Remove the test entirely
?

**Comment by Vogtinator** [comment]
I'm in favor of b) - but there's some internal discussion about that ongoing.

**Comment by ggardet** [comment]
> I'm in favor of b) - but there's some internal discussion about that ongoing.

Ok, let's a bit more time then. :)

**Comment by ggardet** [comment]
If it does not move internally, could you please accept this PR as a fisrt step to fix aarch64 openSUSE tests, please?

**Comment by ggardet** [comment]
As there is no update from internal, let's merge this PR as a first step.

**Pull request merged**
