### PR TITLE
change the shortcut to match the prompt with new libreoffice

### PR DESCRIPTION
**Pull request by nilxam**

### CODE REVIEW

**Comment by nilxam** [comment]
this is the case in Staging J, to avoid affects the others test, please don't merge this for now until bew libreoffice get in into Factory. I'll hot-patch this to openqa host plus a cond. check Staging:J.

**Comment by coolo** [comment]
no other solution? disti-opensuse hosts the tests for SLE too.

**Comment by coolo** [comment]
perhaps a mouse click on "close_libreoffice_button"?

**Comment by nilxam** [comment]
ok, let's do it

**Comment by nilxam** [comment]
btw the needles are created

**Pull request merged**
