### PR TITLE
Give SCC more time to finish the license download. It's a KB after all!

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
Before: https://openqa.suse.de/tests/381763
After: https://tortuga.suse.de/tests/182

**Comment by coolo** [comment]
Just so it fails on the next step ;(
https://tortuga.suse.de/tests/182/modules/scc_registration/steps/44

**Comment by okurz** [comment]
Don't you want to give up waiting after a certain time? Change the while to a timeout loop?

**Comment by coolo** [comment]
the job is killed after 2 hours. That should do as last resort.

**Comment by coolo** [comment]
(optimizing for the 99% case, that it *will* timeout correctly)

**Comment by okurz** [comment]
LGTM

**Pull request merged**
