### PR TITLE
revert:Support for pv vms of RSB

### PR DESCRIPTION
**Pull request by museQi**
Revert “Modify the xen_mitigation.pm of support_for_vm",remove the RSB flag.

Verification run: http://openqa.qa2.suse.asia/group_overview/39

### CODE REVIEW

**Comment by museQi** [comment]
please help me review @alice-suse @XGWang0

**Comment by alice-suse** [comment]
This PR seems to need to be rebased to master. Besides, it is mitigation PR, generally I would suggest to let it reviewed within your team before merge.

**Comment by XGWang0** [comment]
PLease merge multiple commits into one first, additionally , you need to change the details info about this PR

**Comment by museQi** [comment]
Thank you, I have changed the detail info about this PR. About merge two commition,because the two commit interval is too far and the have pull the newest code.So the pr couldn't merge.This PR's objective is to revert the commit 09f6936.

**Comment by museQi** [comment]
Thank you, I have changed the detail info about this PR. About merge two commition,because the two commit interval is too far and the have pull the newest code.So the pr couldn't merge.This PR's objective is to revert the commit 09f6936.

**Comment by XGWang0** [comment]
LGTM

**Pull request merged**
