### PR TITLE
Use common call of yast2 console modules

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
see also needles in gitlab

**Comment by okurz** [comment]
please use 'yast2' reference with no absolute path as discussed in irc.

**Comment by okurz** [comment]
LGTM

**Comment by okurz** [comment]
Missing '# Summary: <multi line summary of test>' in tests/console/yast2_dm_crypt.pm
Missing '# Maintainer: <email address>' in tests/console/yast2_dm_crypt.pm
Missing '# Summary: <multi line summary of test>' in tests/console/yast2_dns_server.pm
Missing '# Maintainer: <email address>' in tests/console/yast2_dns_server.pm
Missing '# Summary: <multi line summary of test>' in tests/console/yast2_http.pm
Missing '# Maintainer: <email address>' in tests/console/yast2_http.pm
Missing '# Summary: <multi line summary of test>' in tests/console/yast2_nfs_server.pm
Missing '# Maintainer: <email address>' in tests/console/yast2_nfs_server.pm
Missing '# Summary: <multi line summary of test>' in tests/console/yast2_vnc.pm
Missing '# Maintainer: <email address>' in tests/console/yast2_vnc.pm

**Comment by kravciak** [comment]
LGTM

**Comment by okurz** [comment]
LGTM, please merge after tests successful

**Pull request merged**
