### PR TITLE
Enable fail while using pipelining in bash

### PR DESCRIPTION
**Pull request by asmorodskyi**
If any commands fail in bash pipeline

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@okurz please review

**Comment by coolo** [comment]
reference a successful test run please

**Comment by okurz** [comment]
Please provide a link or screenshot to a local verification run.

**Comment by coolo** [comment]
one screenshot is very little in this context :)

**Comment by asmorodskyi** [comment]
@coolo agree with you , what will be enough on your opinion ? one full test run ? few tests ? some certain test ?

**Comment by coolo** [comment]
One full (i.e. more than 50 test modules) would do

**Comment by asmorodskyi** [comment]
@coolo  here one full run  http://kimball.arch.suse.de/tests/31#, there are some failures but they are not related to this change for sure.

**Pull request merged**
