### PR TITLE
Set MALLOC_CHECK_ and MALLOC_PERTURB_ variables

### PR DESCRIPTION
**Pull request by mnowaksuse**
MALLOC_CHECK_ and MALLOC_PERTURB_ environmental variables help find
memory allocation bugs sooner.

Tested on x86_64 SLES and TW.

Setup after installation: http://assam.suse.cz/tests/5199

Check if we need to set those variables after boot from HDD_1:
* TW: http://assam.suse.cz/tests/5198
* SLES: http://assam.suse.cz/tests/5197

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by mnowaksuse** [comment]
@sysrich 
> Are we sure these variables will never find a false positive?

Quite unlikely, but surely there are bugs even in GNU libc. We won't know unless we try it. In a limited way for start. The perceived benefits should be higher.

> Are we sure this is not going to produce a behavioural difference to the applications run while this variable is set?

I don't have a reason to think that. Do you? I can only point to reasonable people advising to use it for software development: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MWGBX6NONF4TPVG56OQLF4LRUL7TBTKD/.

> These variables have a documented high performance impact. Are we sure we want to run them on every single test run?

I don't know anything about it. Jim Meyering on the other hand states: "One caveat: this does induce a small performance penalty (usually negligible), so when you're measuring performance, you may want to turn it off." Do we have any performance tests? It won't be run there.

> I like the idea of this test, but I think I'd like to see it implemented as a specific testrun with an openQA var calling it as a mode of operation, not as a setting which openQA has on by default.

Sure, that sounds like a safe approach going forward to me. Can change th PR. Though I still intend to make it default if fallout is not happening.

**Comment by okurz** [comment]
On Wednesday, 1 March 2017 03:30:55 CET Michal Nowak wrote:
> > I like the idea of this test, but I think I'd like to see it implemented
> > as a specific testrun with an openQA var calling it as a mode of
> > operation, not as a setting which openQA has on by default.
> Sure, that sounds like a safe approach going forward to me. Can change th
> PR. Though I still intend to make it default if fallout is not happening.

sure. Add one specific test suite, give it a good description, let it run for 
some time and see if it proves valuable, then change the default around (and 
maybe even still keep the non-default as specific).

**Comment by sysrich** [comment]
Sounds good to me, single testrun at first, we can discuss its benefit as a default once it's been run for some weeks :)

**Comment by coolo** [comment]
Note, that all my systems have aaa_base-malloccheck installed - which does the same thing.

**Comment by asmorodskyi** [comment]
@mnowaksuse please resolve conflicts
@sysrich "some weeks" are passed what your suggestion regarding this PR now ?

**Pull request closed without merging**
