### PR TITLE
Add yast2_proxy

### PR DESCRIPTION
**Pull request by Zaoliang**
Add yast2_proxy test to extra_test.
It works fine on my openqa server: 
http://e13.suse.de/tests/522

### CODE REVIEW

**Comment by sysrich** [comment]
Can you also include the required changes to the opensuse main.pm?

**Comment by coolo** [comment]
the opensuse main.pm is in products/opensuse/main.pm

**Comment by Zaoliang** [comment]
@coolo as I know Richard has added yast2_proxy.pm directly into products/opensuse/main.pm

**Comment by Soulofdestiny** [comment]
@Zaoliang not as far as i can see

**Comment by sysrich** [comment]
Yeah no way i could do that without causing a merge conflict.. Which is why i asked "Can you also include the required changes to the opensuse main.pm?"

**Comment by Zaoliang** [comment]
@sysrich okay, then I'll do this right now

**Pull request merged**
