### PR TITLE
install_and_reboot: Prevent endless loop waiting for countdown stopped

### PR DESCRIPTION
**Pull request by okurz**
Local verification run: http://lord.arch/tests/6172#step/install_and_reboot/1

Related progress issue: https://progress.opensuse.org/issues/18876

### CODE REVIEW

**Comment by mimi1vx** [comment]
lord.arch is reachable in which  network ?

**Comment by plusky** [comment]
@mimi1vx its reachable on r&d network but of course not through vpn

**Comment by okurz** [comment]
it is reachable over vpn for me. try lord.arch.suse.de (or 10.161.8.194 if even dns fails)

**Comment by mimi1vx** [comment]
ahh, orthos :)

**Pull request merged**
