### PR TITLE
Refactor of docker container image tests

### PR DESCRIPTION
**Pull request by grisu48**
This commit adds the routine `test_container_image` in
lib/containers/common.pm, which allows for generic container image
testing using docker and podman.
It also modifies the existing `docker_base_image` -> `container_base_image` test to use this routine and adds podman to the test scenario for openSUSE.

In addition a summary of the smoke tests and their result is uploaded as file `container_base_images-logs.txt`

- Related ticket: https://progress.opensuse.org/issues/67459
- Needles: -
- Verification run: [SLE15-SP1](http://openqa.suse.de/t4322938) | [SLE 15](https://openqa.suse.de/tests/4322702) | [SLE12-SP5](https://openqa.suse.de/tests/4322703) | [SLE12-SP4](https://openqa.suse.de/tests/4322704) | [SLE12-SP3](https://openqa.suse.de/tests/4322705) | [Tumbleweed](https://openqa.opensuse.org/tests/1292484) | [Leap 15.2](https://openqa.opensuse.org/tests/1292485)

### CODE REVIEW

**Comment by grisu48** [comment]
The checks fail, because `tests/console/docker_base_image.pm` has been moved to `tests/console/container_base_images.pm` and the test still checks for the nonexisting `docker_base_image` to be used:

    [make] Unused modules check called over modified/new files only. For a full run use make test-unused-modules-full
    tools/detect_unused_modules -m `git diff --name-only --diff-filter=d $(git merge-base master HEAD) | grep '^tests/*'`
    tools/detect_unused_modules -m `git diff --unified=0 $(git merge-base master HEAD) products/* | grep -oP "^-.*loadtest.*[\"']\K[^\"'].+(?=[\"'])"`
    tools/detect_unused_modules -m `git diff --unified=0 $(git merge-base master HEAD) schedule/* | grep -oP "^-\s+- [\"']?\K.*(?=[\"']?)" | grep -v '{{'`
    console/docker_base_images module is not used in any schedule

**Comment by okurz** [comment]
The problem you saw was likely introduced by 65786fae4 from @rwx788

**Comment by rwx788** [comment]
> The problem you saw was likely introduced by [65786fa](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/65786fae4819e6df84b88596508486e61d5a08e1) from @rwx788

Let me take a look. That's indeed sounds like a case which is not handled properly.

**Comment by grisu48** [comment]
> > The problem you saw was likely introduced by [65786fa](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/65786fae4819e6df84b88596508486e61d5a08e1) from @rwx788
> 
> Let me take a look. That's indeed sounds like a case which is not handled properly.

Looks to me like 

    tools/detect_unused_modules -m `git diff --name-only --diff-filter=d $(git merge-base master HEAD) | grep '^tests/*'`

Should be

    tools/detect_unused_modules -m `git diff --name-only --diff-filter=A $(git merge-base master HEAD) | grep '^tests/*'`

instead. (replace `--diff-filter=d` to `--diff-filter=A`) - We want to check for unused modules on the added ones, not the deleted ones, right?

**Comment by rwx788** [comment]
> > > The problem you saw was likely introduced by [65786fa](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/65786fae4819e6df84b88596508486e61d5a08e1) from @rwx788
> > 
> > 
> > Let me take a look. That's indeed sounds like a case which is not handled properly.
> 
> @rwx788 Looks to me like
> 
> ```
> tools/detect_unused_modules -m `git diff --name-only --diff-filter=d $(git merge-base master HEAD) | grep '^tests/*'`
> ```
> 
> Should be
> 
> ```
> tools/detect_unused_modules -m `git diff --name-only --diff-filter=A $(git merge-base master HEAD) | grep '^tests/*'`
> ```
> 
> instead. (replace `--diff-filter=d` to `--diff-filter=A`) - We want to check for unused modules on the added ones, not the deleted ones, right?
> 
> Addendum: Nope, that wasn't the problem

It's tricky here. If someone removes module from the schedule, we want to check that it's used anywhere else, as it might be it's last usage. So in your case it doesn't work because it was last usage, but the file got renamed.

So I would propose to proceed with merge of this PR ignoring travis faliure and I will provide patch not to check removed modules if they were renamed.

**Comment by grisu48** [comment]
Thanks @rwx788, yes that works perfectly fine

**Comment by rwx788** [comment]
> Thanks @rwx788, yes that works perfectly fine

No probs at all, and don't forget that I basically have caused initial issue =)

**Comment by grisu48** [comment]
No worries, I'm also very good at triggering annoying corner cases ;-)

**Pull request merged**
