### PR TITLE
Remove deprecated die_on_timeout from hacluster

### PR DESCRIPTION
**Pull request by mpagot**
The call `script_run(..., die_on_timeout => 0)` is deprecated and soon to be removed from os-autoinst. This commit replaces such call in hacluster with an alternative. In this case an alternative implementation using enter_cmd and wait_serial is used.

Change extracted from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19853 from @okurz 

- Related ticket: https://progress.opensuse.org/issues/164712

# Verification run:

Changed `ha_export_logs` is used in:
- `post_fail_hook` of `hacluster` but then `hacluster`  is not defined as baseclass
- `post_fail_hook` of `sles4sap`, only if `HA_CLUSTER` is defined. It is used as base by these test modules:
    - `sles4sap/ase_install`
    - `sles4sap/ase_test`
    - `sles4sap/desktop_icons`
    - `sles4sap/ensa/*.*`
    - `sles4sap/forkbomb`
    - `sles4sap/grafana_dashboards`
    - `sles4sap/hana_cluster`
    - `sles4sap/hana_install`
    - `sles4sap/hana_test`
    - `sles4sap/migrate_sles_to_sles4sap`
    - `sles4sap/monitoring_services`
    - `sles4sap/netweaver_*`
    - `sles4sap/patterns`
    - `sles4sap/reclaim_free_space_in_pv`
    - ...and many more ...
- `post_fail_hook` of `ha/ha_cluster_crash_test` test module
- `ha/check_logs` test module pasr of schedule of many HA tests

http://openqaworker15.qa.suse.cz/tests/293801 :green_circle:  but probably not relevant
4 jobs have been created:
 - sle-15-SP5-Server-DVD-HA-Incidents-x86_64-Build:35174:grub2-qam_2nodes_supportserver@64bit -> http://openqaworker15.qa.suse.cz/tests/293845
 - sle-15-SP5-Server-DVD-HA-Incidents-x86_64-Build:35174:grub2-qam_2nodes_01@64bit -> http://openqaworker15.qa.suse.cz/tests/293843 :green_circle:
 - sle-15-SP5-Server-DVD-HA-Incidents-x86_64-Build:35174:grub2-qam_2nodes_02@64bit -> http://openqaworker15.qa.suse.cz/tests/293842
 - sle-15-SP5-Server-DVD-HA-Incidents-x86_64-Build:35174:grub2-qam_2nodes_client@64bit -> http://openqaworker15.qa.suse.cz/tests/293844

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
Looks fine but I wonder what your intention is. Why not just approve or review https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19853 ? You didn't even reference the PR but you are aware of it, so … I don't know

**Comment by mpagot** [comment]
> Looks fine but I wonder what your intention is. Why not just approve or review #19853 ? You didn't even reference the PR but you are aware of it, so … I don't know

This particular file needs a specific set of VR, I'd like to take care of them. I also hope that this PR for one particular code area with a proper set of VR has more chance to be committed sooner.

**Comment by mpagot** [comment]
> You didn't even reference the PR

could you elaborate more on this?

**Comment by mpagot** [comment]
Why to use `Change request` if you do not need code change but only explanation about the procedure/workflow?

**Comment by okurz** [comment]
> > You didn't even reference the PR
> 
> could you elaborate more on this?

Ah right. That's an interesting part about github. If you just put a link to another PR like this https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19853 then there is a link but it does preview the current status but if you use `#<id>` and put that into a separate line like this
* #19853 

then it looks fancy :)

> Why to use `Change requested` comment if you do not need code change but only explanation about the procedure/workflow?

Just to make sure this point is not overlooked. And as you put your change into draft yet I could still set to approved later anyway :) But I can try to change to "just comment"

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Review by lpalovsky — APPROVED** [review]
LGTM

**Pull request merged**
