### PR TITLE
Increase robustness of pxe_boot

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
@dzedro

**Comment by Soulofdestiny** [comment]
updated, included utils

**Comment by okurz** [comment]
wait a second, this module again repeats all the parts from the other bootloader modules? not again… can you extract some methods or use existing helpers?
Also, keep in mind to use `type_string_slow` if you are in a bootloader prompt and `type_string_very_slow` only when you are already at the end of a prompt line which is scrolling to the side (single grub line)

**Comment by Soulofdestiny** [comment]
ok, didn't know that about `type_string_very_slow`

Will find a better solution then

**Comment by Soulofdestiny** [comment]
For now, I only used the helper method for the default params.
I would like to see this merged now as a workaround and encourage @psladek to have a look if he can simplify it more,

I don't know enough about the test and the different variables used to easily refactor this - and if something breaks we will probably have failing tests for at least one week.

verification run upcoming

**Comment by dzedro** [comment]
@Soulofdestiny I would leave it as it was, bootmenu_default_params is different a bit, maybe still OK maybe not. Refactoring/merging pxe_boot.pm with bootloader_setup has nothing to do with poo#18160

**Comment by Soulofdestiny** [comment]
@dzedro I agree actually, updated again
@okurz I'll create a new poo and assign it to @psladek for the refecatoring

**Pull request merged**
