### PR TITLE
Get rid of not helpful soft-fail on bsc#1063638 failing all over

### PR DESCRIPTION
**Pull request by okurz**
It is better to explicitly report about the bug in an appropriately named test
scenario but not pollute generic ones.

### CODE REVIEW

**Comment by okurz** [comment]
@coolo @lnussel

**Comment by coolo** [comment]
I leave it to you to find a good scenario where to set that variable

**Comment by coolo** [comment]
https://openqa.opensuse.org/tests/674409#step/force_cron_run/7 is not the record_soft_fail you patched but the one in settle_load

**Comment by okurz** [comment]
Come on, they are like 10 lines apart. Can't expect me to see that ;) -> https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/5032

**Pull request merged**
