### PR TITLE
Enhance SELinux case audit2allow: add "-R" testing

### PR DESCRIPTION
**Pull request by lilyeyes**
Enhance SELinux case audit2allow: add "-R" testing
All cases passed.

- Related ticket: https://progress.opensuse.org/issues/66571
- Needles: NA
- Verification run: https://openqa.nue.suse.com/tests/4212652#

### CODE REVIEW

**Comment by rfan1** [comment]
my @files = ("selinux-policy-20200219-3.6.noarch.rpm", "selinux-policy-minimum-20200219-3.6.noarch.rpm", "selinux-policy-devel-20200219-3.20.noarch.rpm");

The pkg names seems hard code here, so how can we handle it once the pkgs get new version?
Can we do some enhancement?

**Comment by rfan1** [comment]
validate_script_output(
        "audit2allow -R -i $audit_log",
        sub {
            m/
            .*require\ \{.*
            .*type\ .*;.*
            #=============.*==============.*
            .*allow.*;.*/sx
        });
If possible, can you please add some comments here? then we can get more clear info why we try to "grep" the output.  thanks

**Comment by lilyeyes** [comment]
> my @files = ("selinux-policy-20200219-3.6.noarch.rpm", "selinux-policy-minimum-20200219-3.6.noarch.rpm", "selinux-policy-devel-20200219-3.20.noarch.rpm");
> 
> The pkg names seems hard code here, so how can we handle it once the pkgs get new version?
> Can we do some enhancement?

Good question. I had considered it before. Please see my thoughts bellow.
The background of the pkgs:
First, the selinux-policiy* pkgs change often but will *NOT* be released with products.
Second, I just downloaded them from developer's private repos or obs or ibs and installed them to test selinux tools only.
So, I would like to keep the version part of file name (e.g., 20200219-3.6) to make it more clear when reading code or trouble shooting.
Yes we can change the name from "selinux-policy-devel-20200219-3.20.noarch.rpm"  to "selinux-policy-devel.noarch.rpm" for easier maintenance, also we can wget all of them an zypper  install all of them for a clean/dry code.
But the pkgs are special pkgs (e.g., *minimum*, *dev*, *mls* (not automated yet) ) and have special functions I would like keep the code style for  a good understanding.

**Comment by lilyeyes** [comment]
> validate_script_output(
> "audit2allow -R -i $audit_log",
> sub {
> m/
> ._require\ {._
> ._type\ ._;.*
> #=============._==============._
> ._allow._;.*/sx
> });
> If possible, can you please add some comments here? then we can get more clear info why we try to "grep" the output. thanks

Sure.

**Comment by rfan1** [comment]
> > my @files = ("selinux-policy-20200219-3.6.noarch.rpm", "selinux-policy-minimum-20200219-3.6.noarch.rpm", "selinux-policy-devel-20200219-3.20.noarch.rpm");
> > The pkg names seems hard code here, so how can we handle it once the pkgs get new version?
> > Can we do some enhancement?
> 
> Good question. I had considered it before. Please see my thoughts bellow.
> The background of the pkgs:
> First, the selinux-policiy* pkgs change often but will _NOT_ be released with products.
> Second, I just downloaded them from developer's private repos or obs or ibs and installed them to test selinux tools only.
> So, I would like to keep the version part of file name (e.g., 20200219-3.6) to make it more clear when reading code or trouble shooting.
> Yes we can change the name from "selinux-policy-devel-20200219-3.20.noarch.rpm" to "selinux-policy-devel.noarch.rpm" for easier maintenance, also we can wget all of them an zypper install all of them for a clean/dry code.
> But the pkgs are special pkgs (e.g., _minimum_, _dev_, _mls_ (not automated yet) ) and have special functions I would like keep the code style for a good understanding.

Sounds good to me

**Comment by lilyeyes** [comment]
> > validate_script_output(
> > "audit2allow -R -i $audit_log",
> > sub {
> > m/
> > ._require\ {._
> > ._type\ ._;.*
> > #=============._==============._
> > ._allow._;.*/sx
> > });
> > If possible, can you please add some comments here? then we can get more clear info why we try to "grep" the output. thanks
> 
> Sure.

Done!

**Comment by rfan1** [comment]
> > > validate_script_output(
> > > "audit2allow -R -i $audit_log",
> > > sub {
> > > m/
> > > ._require\ {._
> > > ._type\ ._;.*
> > > #=============._==============._
> > > ._allow._;.*/sx
> > > });
> > > If possible, can you please add some comments here? then we can get more clear info why we try to "grep" the output. thanks
> > 
> > 
> > Sure.
> 
> Done!

Thanks, it makes everything clear now.

**Comment by rfan1** [comment]
LGTM

**Comment by lemon-suse** [comment]
LGTM.

**Comment by DimStar77** [comment]
Results in https://progress.opensuse.org/issues/66892

Registering modules on openSUSE Tumbleweed does not work

**Comment by lilyeyes** [comment]
> Results in https://progress.opensuse.org/issues/66892
> 
> Registering modules on openSUSE Tumbleweed does not work

Got it, thanks for the info :)

**Pull request merged**
