### PR TITLE
Increase timeout for package install

### PR DESCRIPTION
**Pull request by asmorodskyi**
@okurz  please take a look

### CODE REVIEW

**Comment by okurz** [comment]
Please reference at least a failing test case which should be fixed by this one. Also it would be if you state why this bumping up the timeout should be ok.

**Comment by asmorodskyi** [comment]
https://openqa.suse.de/tests/685403

**Comment by dgutu-suse** [comment]
I'm not sure this is needed, latest builds are just fine. IMO the test failed because of performance issue on worker. Did you tried to restart the job?

**Comment by asmorodskyi** [comment]
@dgutu-suse restart of job looks like run away from a problem , we should have test which tolerant to performance issues on worker . But on other side I agree with you that increasing timeout is also not the best solution , this is why in parallel to this PR I also create a progress issue to take a look on this problem deeper (not during test review :) ) - https://progress.opensuse.org/issues/15614.

**Pull request merged**
