### PR TITLE
sle11 ncc and sle11 online migration

### PR DESCRIPTION
**Pull request by mitiao**
sle11 ncc test with bugs fixing after comments by richard and coolo 
and initial sle11 online migration test
please review it
thanks

### CODE REVIEW

**Comment by coolo** [comment]
boot_to_console and yast2_wagon don't appear very sle11 specific. So I would prefer if they lived somewhere else.

**Comment by sysrich** [comment]
@coolo I think yast2_wagon is SLE11 specific as everything I've heard implies that SLE12 will not have wagon

You're right about boot_to_console though

**Comment by mitiao** [comment]
So how to handle the boot_to_console? 
Do i need to call existing boot code or move it to somewhere else?

**Comment by coolo** [comment]
just move it to tests/boot and loadtest from there

**Pull request merged**
