### PR TITLE
Add yast2_ftp and yast2_http tests to opensuse extratests

### PR DESCRIPTION
**Pull request by sysrich**
Add new yast2_http and yast2_ftp tests to openSUSE Extratests

@Zaoliang - please feel free to do this in any future pull requests for the tests you're working on - it's always nice to have openSUSE's test coverage expand aligned with SLE's :)

### CODE REVIEW

**Comment by nilxam** [comment]
LGTM

**Comment by coolo** [comment]
we need to copy over the needles from SLE though

**Comment by nilxam** [comment]
well, but looks like these tests never passed on openqa.suse.de, do we already have the complete needles there?

**Comment by sysrich** [comment]
They didn't pass on openqa.suse.de yet because of the bloody systemd font issue.

The needles in os-autoinst-needles-sles right now have the CORRECT/openSUSE style terminal font

Therefore, you should be able to copy them even though we haven't got them working on openqa.suse.de yet ;)

**Comment by nilxam** [comment]
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/67

**Comment by Zaoliang** [comment]
yast2_http works fine, yast2_ftp test failed because of an issue which has been reported already: http://bugzilla.suse.com/show_bug.cgi?id=975538
Only check of ftp status failed. I'll change yast2_ftp test later if the issue got fixed (support  rsa only, no dsa in YaST)

**Comment by nilxam** [comment]
a question: is yast2 ftp-server and http-server module are default installed in SLE?

**Comment by Soulofdestiny** [comment]
@nilxam there is an assert_script_run for installing those packages
is that what you mean?

**Comment by nilxam** [comment]
Eg. it is trying to install vsftpd https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/console/yast2_ftp.pm#L21 , *but* it's assumed yast2-ftp-server is default installed, however it's NOT true for openSUSE(it's true for SLE indeed), so it needs install yast2-ftp-server too, otherwise `yast2 ftp-server` is useless. Same situation in yast2_http and yast2_proxy test.

**Comment by Soulofdestiny** [comment]
I see, @Zaoliang can you have a look? ;)

**Comment by Zaoliang** [comment]
@nilxam have a look at #1302

**Pull request merged**
