### PR TITLE
Fix base parameter error

### PR DESCRIPTION
**Pull request by RoyCai7**
- Related ticket: https://progress.opensuse.org/issues/163091
- Needles: n/a
- Verification run: http://openqa.qam.suse.cz/tests/overview?build=live_migrat_test_by_roy&distri=sle&version=15-SP5&groupid=167

### CODE REVIEW

**Review by alice-suse — APPROVED** [review]
LGTM

**Comment by martinsmarcelo** [comment]
LGTM

**Comment by guoxuguang** [comment]
LGTM

**Comment by RoyCai7** [comment]
```
[2024-07-04T04:09:09.680018+02:00] [debug] [pid:8683] <<< testapi::script_run(cmd="(set -x;unset migrate_postcopy;export migrate_postcopy=1; for i in `seq 87000`;do ;migrate_postcopy=\$?; if [ \$migrate_postcopy -eq 0 ];then set +x;break;fi; done; if [ \$migrate_postcopy -eq 0 ];then echo -e \"Migrate Postcopy Succeeded! \\n\";else echo -e \"Command not found\357\274\201 \\n\";fi)", output="", quiet=undef, die_on_timeout=1, timeout=300)
[2024-07-04T04:09:09.680153+02:00] [debug] [pid:8683] lib/parallel_guest_migration_base.pm:132 called parallel_guest_migration_source::run_test -> tests/virt_autotest/parallel_guest_migration_source.pm:75 called parallel_guest_migration_source::guest_migration_test -> tests/virt_autotest/parallel_guest_migration_source.pm:190 called parallel_guest_migration_source::do_guest_migration -> tests/virt_autotest/parallel_guest_migration_source.pm:252 called parallel_guest_migration_base::virsh_migrate_manual_postcopy -> lib/parallel_guest_migration_base.pm:1569 called testapi::script_run
[2024-07-04T04:09:09.680277+02:00] [debug] [pid:8683] <<< testapi::type_string(string="(set -x;unset migrate_postcopy;export migrate_postcopy=1; for i in `seq 87000`;do ;migrate_postcopy=\$?; if [ \$migrate_postcopy -eq 0 ];then set +x;break;fi; done; if [ \$migrate_postcopy -eq 0 ];then echo -e \"Migrate Postcopy Succeeded! \\n\";else echo -e \"Command not found\357\274\201 \\n\";fi)", max_interval=250, wait_screen_change=0, wait_still_screen=0, timeout=30, similarity_level=47)
```

Chinese Character issue, fixing.

**Comment by RoyCai7** [comment]
From code, I find that it is by designed.
`my @_command = split(/#/, $args{command});`

**Pull request closed without merging**
