### PR TITLE
Minor updates for journactl.pm

### PR DESCRIPTION
**Pull request by mloviska**
Check if systemd drop-in directory exists and remove printing of
**journactl** manpage.

- failure in [PC](https://openqa.suse.de/tests/6414937#step/journalctl/14)
- Related ticket: https://progress.opensuse.org/issues/91848

### CODE REVIEW

**Review by pdostal — APPROVED** [review]
We could implement `fail_message` parameter to `script_retry()`

**Comment by mloviska** [comment]
> We could implement `fail_message` parameter to `script_retry()`

Yup, later, let's check the test flags now in PC. But maybe that should be done on `consoletest` level

**Comment by mloviska** [comment]
https://openqa.suse.de/tests/6418160

**Comment by mloviska** [comment]
> > We could implement `fail_message` parameter to `script_retry()`
> 
> Yup, later, let's check the test flags now in PC. But maybe that should be done on `consoletest` level

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/12879

**Review by jlausuch — APPROVED** [review]
Agreed. That bug is pretty old and that check is just leftovers.

**Pull request merged**
