### PR TITLE
Public Cloud: Do not use load_extra_tests_prepare()

### PR DESCRIPTION
**Pull request by pdostal**
- Related ticket: [poo#102569](https://progress.opensuse.org/issues/102569)
- Verification run: TBD

### CODE REVIEW

**Comment by jlausuch** [comment]
VRs:
http://openqa.suse.de/t7772691
http://openqa.suse.de/t7772692
http://openqa.suse.de/t7772693

**Comment by jlausuch** [comment]
The VRs are failing due to [this fix](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13798) which I just merged. Can you please rebase on top of master and I re-run them again?

**Comment by pdostal** [comment]
Done.

**Comment by jlausuch** [comment]
VRs:
https://openqa.suse.de/tests/7772773
https://openqa.suse.de/tests/7772774
https://openqa.suse.de/tests/7772775
https://openqa.suse.de/tests/7772756
https://openqa.suse.de/tests/7772819
https://openqa.suse.de/tests/7772824
https://openqa.suse.de/tests/7772825

**Pull request merged**
