### PR TITLE
Fix s390x jobs stuck in shutdown until openQA job times out

### PR DESCRIPTION
**Pull request by okurz**
Whenever the SUT is expected to disappear we need to ensure the remote
connections are terminated in before to prevent the test to be stuck.

With this change also renaming `prepare_system_reboot` to
`prepare_system_shutdown` as that is a more generic term (reboot = shutdown +
boot). Also it helps with abstraction to call `prepare_system_shutdown`
unconditionally as the method takes care internally to call appropriate
actions which may be backend specific. For the normal qemu case the function
is a no-op anyway.

Verification run: http://lord.arch/tests/7905

Related progress issue: https://progress.opensuse.org/issues/26886

### CODE REVIEW

**Comment by okurz** [comment]
will test on s390x

**Comment by okurz** [comment]
@coolo, @Soulofdestiny that did not seem to work: http://lord.arch/tests/7903#live

I called kill and now it's stuck in/after

```
15:03:06.3036 27942 <<< backend::console_proxy::__ANON__(wrapped_call={
  'function' => 'kill_ssh',
  'args' => [],
  'console' => 'iucvconn'
})
```

still stuck. Is iucvconn the wrong one? It's a test on z/VM so that should have worked. Do I need to check any active network connections?

```
$ sudo netstat -tp | grep ssh
tcp      209      0 lord.arch.suse.de:58970 s390vsl157.suse.de:ssh  CLOSE_WAIT  27945/isotovideo: b 
tcp        0      0 lord.arch.suse.de:35148 10.162.0.23:ssh         ESTABLISHED 2323/ssh            
tcp        0      0 lord.arch.suse.de:43424 10.162.0.24:ssh         ESTABLISHED 6019/ssh            
tcp        0      0 lord.arch.suse.de:58972 s390vsl157.suse.de:ssh  CLOSE_WAIT  27945/isotovideo: b 
```

I assume one of the two "CLOSE_WAIT" connections could be problematic?

Killing the backend process released the openQA job of course.

**Comment by okurz** [comment]
fixed, see verification run in description

**Comment by Soulofdestiny** [comment]
Lgtm. But still we should disable publish_hdd for the zVM jobs, no?

**Comment by okurz** [comment]
We can not easily enable the PUBLISH_HDD_… variables per architecture *but* it seems it's just silently skipped on zVM so not a problem

**Pull request merged**
