### PR TITLE
Extend timeout for LLVM build

### PR DESCRIPTION
**Pull request by mnowaksuse**
poo#18692

### CODE REVIEW

**Comment by asmorodskyi** [comment]
IMO instead of endlessly increasing timeout we could try to change what we actually compiling and replace it with something smaller which would take 2-3 minutes and not 2 hours

**Comment by sysrich** [comment]
I agree - though 2-3 minutes might be too small

I want us to compile something that gives the GCC test a reasonable 'fair shake', something that is non-trivial, but not something that dominates precious worker space for multiple hours

Can we find something that is done in about 20-30 minutes, not 2 hours?

**Comment by mnowaksuse** [comment]
I don't see why 2-3 minutes is too small and 20-30 minutes is fine for toolchain module validation. The prime criteria in such reasoning seems to me HW resources used (a valid point on it's own), not feature coverage. Perhaps because, well, no one knows what to actually cover - I certainly don't.

I want to be clear, that I don't block anyone from replacing those two test by something else, I don't "own" them. The effort just did not earned my support.

The original question was whether we want the test to have more time to pass, or we keep it running on aarch64 for no purpose.

**Comment by okurz** [comment]
you are right and the change is right. It might help because the process takes longer than originally expected so bumping the timeout is correct and I will merge it. However, it should be clear that we don't want tests in our validation group which run for more than 2h in general so the progress ticket is not really fixed with this PR. I also got the point by @mnowaksuse that you don't own the test. I think we all do or we all should do.

**Pull request merged**
