### PR TITLE
Add support for icelake machine in mitigations function test

### PR DESCRIPTION
**Pull request by museQi**
Change the code of taa.pm and mitigations.pm to support the icelake machine in the mitigaitions function test.
- Verification run:  http://openqa.qa2.suse.asia/group_overview/44

### CODE REVIEW

**Comment by museQi** [comment]
@alice-suse please help me approve the workflow to check.
@XGWang0 please help me review the code.

**Comment by alice-suse** [comment]
LGTM

**Review by alice-suse — APPROVED** [review]

**Comment by XGWang0** [comment]
LGTM

**Comment by alice-suse** [comment]
Please fix the check failures before merge.

**Comment by museQi** [comment]
@alice-suse Please help me merge,after you review.

**Pull request merged**
