### PR TITLE
Cleanup of unused code

### PR DESCRIPTION
**Pull request by kravciak**
Module login/boot.pm depends on non-existent variable KEEPHDDS
Module linuxrc/system_boot.pm depends on non-existent variable LINUXRC

### CODE REVIEW

**Comment by kravciak** [comment]
Side effect of main.pm cleanup for CASP - I was looking into bootloaders.
I updated PR as I found another unused module.

**Comment by okurz** [comment]
good work, thank you!

**Comment by coolo** [comment]
aehm - https://progress.opensuse.org/issues/10654

**Comment by okurz** [comment]
ok, not good work ;-)

**Comment by coolo** [comment]
the same for KEEPHDDS. It's a debugging variable - and yes, we're not using it in production

**Comment by kravciak** [comment]
I missed KEEPHDDS check in qemu backend, thanks
linuxrc/system_boot.pm - looks like old WIP
Restored in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2082

**Pull request merged**
