### PR TITLE
svirt/Xen: Search for images on the svirt host

### PR DESCRIPTION
**Pull request by Martchus**
rather than on the worker which might not have NFS

* See https://progress.opensuse.org/issues/32281
* In addition, this makes it possible to use a different
  OPENQA_BASEDIR on the worker than on the svirt host.

---

requires https://github.com/os-autoinst/os-autoinst/pull/1050 (merged)

### CODE REVIEW

**Comment by Martchus** [comment]
For verification, I've just ran an svirt/Xen test and to be sure not to break other cases an svirt/Hyper-V test. The images were only available on the svirt host but not on the worker.

**Comment by Martchus** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1050 has been merged

**Comment by Martchus** [comment]
@okurz This depends on a fix in os-autoinst to work. But without that it shouldn't break anything, too.

**Comment by asmorodskyi** [comment]
LGTM . @mnowaksuse WDYT ?

**Pull request merged**
