### PR TITLE
Use offline media to do upgrade

### PR DESCRIPTION
**Pull request by waynechen55**
Offline media should be passed to:
1)test_virtualization-guest-upgrade-run
2)_generate_vh-update_test.sh

- Related ticket: https://openqa.suse.de/tests/3649103
                          https://openqa.suse.de/tests/3649104
- Needles: n/a
- Verification run: https://10.162.187.154/tests/4376

### CODE REVIEW

**Comment by Julie-CAO** [comment]
LGTM. It would be better if comments were added to tell why we do this trick.

**Comment by waynechen55** [comment]
> LGTM. It would be better if comments were added to tell why we do this trick.

Done

**Comment by waynechen55** [comment]
Please have a look if any problem @alice-suse @Julie-CAO

**Comment by Julie-CAO** [comment]
LGTM

**Comment by alice-suse** [comment]
LGTM

**Pull request merged**
