### PR TITLE
Update partition table creation in storage-ng

### PR DESCRIPTION
**Pull request by mloviska**
- Related ticket: [[sle][functional][y] Expert Partitioner UI upgrade - create partition table](https://progress.opensuse.org/issues/41903)
- Needles: [osd](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/952)
- Verification runs:
  * [sle-12-SP4-Server-DVD-x86_64-Build0405-btrfs+warnings@64bit](http://dhcp128.suse.cz/tests/6653#step/partitioning_warnings/1)
  * [sle-15-SP1-Installer-DVD-x86_64-Build56.1-btrfs+warnings@64bit](http://dhcp128.suse.cz/tests/6655#step/partitioning_warnings/1)
  * [sle-15-SP1-Installer-DVD-aarch64-Build58.1-btrfs+warnings@aarch64](http://dhcp128.suse.cz/tests/6661#step/partitioning_warnings/1)
  * [sle-12-SP4-Server-DVD-aarch64-Build0405-btrfs+warnings@aarch64](http://dhcp128.suse.cz/tests/6662#step/partitioning_warnings/1)
  * [opensuse-15.1-DVD-x86_64-Build307.2-btrfs+warnings@64bit](http://dhcp128.suse.cz/tests/6663)

### CODE REVIEW

**Comment by rwx788** [comment]
Is this code used anywhere on openSUSE?

**Comment by mloviska** [comment]
Not yet, the old one is still working and I am not really sure when this change is going to hit oS. Considering the current build issue of partitioner in Factory project, it might take some time. There is not a problem to include the old part and scope it for oS only. WDYT ?

**Comment by mloviska** [comment]
Sure, that sounds good. Should I do another commit within this PR or create a separate PR as well  ?

**Comment by mloviska** [comment]
Updated VRs

**Pull request merged**
