### PR TITLE
Make sure pax is installed

### PR DESCRIPTION
**Pull request by asmorodskyi**
Install star package which has pax executable
before using it.

### CODE REVIEW

**Comment by asmorodskyi** [comment]
http://kimball.arch.suse.de/tests/29#

**Comment by kravciak** [comment]
Can you share link to failing test please?

**Comment by coolo** [comment]
the star package has no pax

**Comment by okurz** [comment]
@kravciak https://openqa.opensuse.org/tests/321196#step/btrfs_send_receive/87

**Comment by asmorodskyi** [comment]
@coolo yeah this is the point here on latest Tumbleweed they moved it to "spax" package , but I point me to idea that I probably should try to install it only on Tumbleweeed and not unconditionally how it happens right now

**Comment by coolo** [comment]
whatever you do, don't mix spax and star. And yes, leap has no spax package

**Comment by foursixnine** [comment]
@asmorodskyi you could also check before if the binary exists, and then use cnf to locate the right package, then install (and perhaps in the way add it as an utility sub)

**Comment by coolo** [comment]
you don't need cnf: zypper_call('in -C /usr/bin/pax')

**Comment by asmorodskyi** [comment]
@coolo command that you suggest return "No provider of 'usr/bin/pax' found"  
http://kimball.arch.suse.de/tests/latest?distri=opensuse&flavor=DVD&test=extra_tests_on_textmode&arch=x86_64&machine=64bit&version=Tumbleweed#step/btrfs_send_receive/11

but I will try to find logic which works in both environments - where pax is inside star and where  pax is inside spax

**Comment by coolo** [comment]
Both packages provide pax, so you can install zypper in pax.

**Comment by coolo** [comment]
(with -C)

**Comment by asmorodskyi** [comment]
thanks for help @coolo  , now it's working http://kimball.arch.suse.de/tests/38#step/btrfs_send_receive/48 , verification on SLE on a way

**Pull request merged**
