### PR TITLE
Wrap curly braces in remaning yaml schedule

### PR DESCRIPTION
**Pull request by rwx788**
See [poo#66253](https://progress.opensuse.org/issues/66253).

[Verification run](https://openqa.suse.de/tests/4181778#).

### CODE REVIEW

**Comment by okurz** [comment]
seems we had a race condition in the revert merge and this one though, the revert is merged so if you bring the content from #10100 back as well then we can merge this together.

**Comment by rwx788** [comment]
> seems we had a race condition in the revert merge and this one though, the revert is merged so if you bring the content from #10100 back as well then we can merge this together.

This is correct yaml syntax, so let's have it. As for revert, we can take our time now. I guess I will resurrect my PR as I've used constructor there and not legacy interface which will allow us to use merge keys feature, for example.

**Comment by okurz** [comment]
cool

**Comment by asdil12** [comment]
I'm not sure if we already have it but it would make sence to check something like this via travis.

**Comment by rwx788** [comment]
> I'm not sure if we already have it but it would make sence to check something like this via travis.

This is already done, we have enabled yamllint for that. However, we run those checks on the scope of changed files and not the whole repo. That's the reason why we have missed some of those cases.

**Comment by perlpunk** [comment]
> That's the reason why we have missed some of those cases.

That's actually not the (only) reason.
`{{ }}` is alid YAML syntax. The existing tests only check if the YAML files and be loaded. So the test would have passed for all files.
We need to add a JSON schema to prevent this (and other mistakes that can lead to a wrong structure).

**Pull request merged**
