### PR TITLE
Fix x11 tests stuck in 'user-console' (regression in e0c76ad62)

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
Alternative to https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6987 to fix https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6792

```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6988 https://openqa.suse.de/tests/2520706
```

Created job #2526403: sle-15-SP1-Installer-DVD-Staging:B-x86_64-BuildB.203.2-gnome@64bit-staging -> https://openqa.suse.de/t2526403

**Comment by mloviska** [comment]
I would rather return to x11 than remove user-console. But anyway, we should turn off screen saver once after first boot instead of handling screen saver in each module.

**Comment by okurz** [comment]
@mloviska that would be https://progress.opensuse.org/issues/40094 and https://progress.opensuse.org/issues/40490 as well as https://progress.opensuse.org/issues/48110 :)

**Comment by okurz** [comment]
https://openqa.suse.de/tests/2526403#step/yast2_snapper/58 passed. I hope you are ok when I merge :)

**Comment by rwx788** [comment]
Thanks for handling this!

**Pull request merged**
