### PR TITLE
Move container related tests to a new directory

### PR DESCRIPTION
**Pull request by jlausuch**
The amount of container tests is increasing and more tests will be created.
It would be good to collect them in a separate directory to not fill up console tests directory.

### CODE REVIEW

**Comment by jlausuch** [comment]
@pdostal @grisu48

**Comment by grisu48** [comment]
Very good idea! Could we have a verification run to ensure nothing is breaking?

**Comment by jlausuch** [comment]
VRs:

- QA SLE: 
    # https://openqa.suse.de/tests/4339016 (failure not related to this PR)
    # https://openqa.suse.de/tests/4339015
    # https://openqa.suse.de/tests/4339014
- QAM: 
    # https://openqa.suse.de/tests/4339019

**Comment by jlausuch** [comment]
I can't clone jobs in O3 to insert CASEDIR. If someone with proper rights could do it for me it would be appreciated. Basically run this command for [Tumbleweed](https://openqa.opensuse.org/tests/1295763) job:

`/usr/share/openqa/script/clone_job.pl --within-instance openqa.opensuse.org --skip-chained-deps 1295763 CASEDIR=https://github.com/jlausuch/os-autoinst-distri-opensuse.git#move_container_tests`

**Comment by grisu48** [comment]
https://openqa.opensuse.org/tests/1296864

**Comment by pdostal** [comment]
I agree. There is similar `lib/containers/` so it matches 👍

**Pull request merged**
