### PR TITLE
Revert "containers: Add tests for volumes"

### PR DESCRIPTION
**Pull request by DimStar77**
Reverts os-autoinst/os-autoinst-distri-opensuse#17584

FWIW: as the test is also enabled in Staging, this blocks Staging / Tumbleweed from accepting new changes, thus blocking entirely.

### CODE REVIEW

**Review by pdostal — CHANGES_REQUESTED** [review]
Is this really needed? @ricardobranco777 is online, so he may be already work on a fix.

**Review by ricardobranco777 — COMMENTED** [review]
It's the `CONTAINER_RUNTIME` variable that is broken as it's set to `podman,docker`

**Comment by DimStar77** [comment]
> It's the `CONTAINER_RUNTIME` variable that is broken as it's set to `podman,docker`

disagreed

https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/variables.md



CONTAINER_RUNTIME | string |   | Container runtime to be used, e.g.  docker, podman, or both podman,docker. In addition, it is also used for other container tests, like  kubectl, helm, etc.
-- | -- | -- | --

**Comment by mloviska** [comment]
> It's the `CONTAINER_RUNTIME` variable that is broken as it's set to `podman,docker`

No, that is a standard for sle-micro,alp and others. It can be a list in fact and we have kinda missed this in the previous PR, sorry for that!

**Review by ricardobranco777 — CHANGES_REQUESTED** [review]
I will submit a proper fix.  No need to revert.

**Comment by ricardobranco777** [comment]
Fixing here:

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17598

**Comment by DimStar77** [comment]
> I will submit a proper fix. No need to revert.

With a fix incoming in reasonable timeframes, I am fully on board to not revert this.

**Pull request closed without merging**
