### PR TITLE
container: Use BETA variable only for know beta versions

### PR DESCRIPTION
**Pull request by cfconrad**
- Related ticket: https://progress.opensuse.org/issues/99750
- Verification run: https://openqa.suse.de/tests/7318680#step/buildah_podman/116

### CODE REVIEW

**Review by b10n1k — APPROVED** [review]
:LGTM

**Comment by jlausuch** [comment]
You need to do the same for buidah podman (and I really hate we have this code duplicity, but Yannis is working on it)

**Review by pdostal — APPROVED** [review]

**Review by jlausuch — CHANGES_REQUESTED** [review]
Requesting changes to prevent merge before updating buildah_podman too

**Review by jlausuch — APPROVED** [review]
LGTM

**Comment by cfconrad** [comment]
VR on x86_64 was successful, ready to merge.

**Pull request merged**
