### PR TITLE
publiccloud : switch to python39

### PR DESCRIPTION
**Pull request by asmorodskyi**
https://progress.opensuse.org/issues/116440

### CODE REVIEW

**Comment by asmorodskyi** [comment]
VRs : 
- image creation job http://autobot.qa.suse.de/tests/3316
usage of created image on Azure : 
- http://autobot.qa.suse.de/tests/3319
- http://autobot.qa.suse.de/tests/3321

**Review by pdostal — APPROVED** [review]

**Comment by grisu48** [comment]
I need a bit more context. Why do we need this? Is there a ticket for this?

Why do we switch to python 3.9 and not 3.10 (I guess because 3.10 is not yet available on 15-SP3?) What about the other python packages, that remain on 3.6, namely `python3-img-proof python3-img-proof-tests`?

**Comment by asmorodskyi** [comment]
> I need a bit more context. Why do we need this? Is there a ticket for this?

it is based on https://progress.opensuse.org/issues/115361 . But initial problem raised in ticket concluded as one-time issue so I rejected ticket, nevertheless I decided to get rid of this python 3.6 warnings

> Why do we switch to python 3.9 and not 3.10 (I guess because 3.10 is not yet available on 15-SP3?) 

I am not sure I haven't checked  , I just didn't want to switch to latest version due to stability concerns 


> What about the other python packages, that remain on 3.6, namely `python3-img-proof python3-img-proof-tests`?

they don't have any other version so we don't have much options here . Only thing which we can do is to drop packaging and switch to clone repos and make things work "manually". I think it will work but I keep it as last resort when we get something bigger than just warnings ...

**Review by ilausuch — APPROVED** [review]

**Comment by grisu48** [comment]
OK for now to get rid of the warning.

However this is getting messy. We are having now two different python versions, are using pip and virtual environments. The approach "it works for now" is unlikely to give us stability. As of now this looks like a hot potato that we just keep patching.

Perhaps it would be a good idea to switch to 15-SP4 and when doing so explore options to unify the workflow but that's beyond the scope of this PR.

**Review by grisu48 — APPROVED** [review]

**Pull request merged**
