### PR TITLE
Work around sporadic issue with send_key

### PR DESCRIPTION
**Pull request by Zaoliang**
see https://progress.opensuse.org/issues/81316
verification test:
http://10.162.23.47/tests/8702#step/gnome_music

### CODE REVIEW

**Comment by Zaoliang** [comment]
verified on OSD with this PR:

https://openqa.suse.de/tests/5273272#step/gnome_music/16

**Comment by Zaoliang** [comment]
https://openqa.suse.de/tests/5273272#next_previous

100 runs are successful, so this is stable now.

**Comment by Zaoliang** [comment]
verification test for TW:

http://10.162.23.47/tests/8810#step/gnome_music/15

**Review by asdil12 — APPROVED** [review]
LGTM

**Pull request merged**
