### PR TITLE
Edit optional Kernel params with YuiRestClient

### PR DESCRIPTION
**Pull request by jknphy**
Edit optional Kernel params with YuiRestClient

- Related ticket: 
  - [poo#102164](https://progress.opensuse.org/issues/102164)
  - [poo#98889](https://progress.opensuse.org/issues/98889)
- Verification run: [SLE](https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=jknphy%2Fos-autoinst-distri-opensuse%23disable_plymouth) | [openSUSE](https://openqa.opensuse.org/tests/overview?version=15.3&build=jknphy%2Fos-autoinst-distri-opensuse%23disable_plymouth&distri=opensuse)

### CODE REVIEW

**Review by ge0r — APPROVED** [review]
LGTM!

**Review by rakoenig — APPROVED** [review]
LGTM too. But cannot merge because I have no write permissions.

**Comment by jknphy** [comment]
thanks both for taking a look. Let's merge then.

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/2040470#step/yast2_system_settings/33

possibly related? Filed ticket https://progress.opensuse.org/issues/102557 for it

**Comment by rakoenig** [comment]
Yes, looks like we need to check all usages of tab select methods carefully. In this case https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/4dcc3efbb27c5dfc9fec6ddb37cc9b30a005cd82/lib/YaST/SystemSettings/SystemSettingsPage.pm#L38 needs to be fixed. But maybe there is more.

**Comment by rakoenig** [comment]
Created https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13703 for the bugfix.

**Pull request merged**
