### PR TITLE
Fixed poo#16434

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by plusky** [comment]
* preauthorization compression is being disabled due to security concerns via maintenance update that is currently in queue
* compression is still enabled by default even when `-C` is not issued
* `-C ` just forces compression all the time (and will cause failures)
* as for `-Y` its more resilient with `-X` you have some extra check byt you are more likely to recieve confusing errors (i.e. if session is open for too long and xauth cookie expires)

**Comment by okurz** [comment]
about the compression I am ok.

> as for -Y its more resilient with -X you have some extra check byt you are more likely to recieve confusing errors (i.e. if session is open for too long and xauth cookie expires)

I am not quite sure what you mean with "resilient" in this case. I would say "-Y" is more "sloppy" as it blindly trusts the remote client. And why should "-X" in our clean environment not work anymore?

**Comment by mimi1vx** [comment]
http://argus.suse.cz/tests/106#step/sshxterm/4

**Comment by msmeissn** [comment]
the error screen with infalte: -3 error is not good though

**Comment by coolo** [comment]
-XC should still work - so IMO this pull request is invalid.

**Comment by drpaneas** [comment]
In SUSE `-X` and `-Y` are treated as the same due to the configuration. See [my comment at the progress ticket](https://progress.opensuse.org/issues/16434#note-5). The error is due to the compression parameter. IMO I would try the `-XC` and if it fails I would flag it as soft-failed (pointing to the bug) and continue the test using either `-X` or `-Y` only. If the latter fails, then X forwarding is broken and mark the test as failed.

**Comment by coolo** [comment]
if you want to have tests testing individual options of ssh forward - do so, write them. This test will stay as it is. -XC are valid options and should result in a xterm forwarded from root.

**Pull request closed without merging**
