### PR TITLE
Containers: Include transactional case when installing docker

### PR DESCRIPTION
**Pull request by jlausuch**
https://progress.opensuse.org/issues/109121

[TW MicroOS](https://openqa.opensuse.org/tests/overview?version=Tumbleweed&distri=microos&build=jlausuch%2Fos-autoinst-distri-opensuse%23microos_docker)
[SLE Micro 5.2](https://openqa.suse.de/tests/overview?arch=&flavor=&machine=&test=slem_containers_docker%40jlausuch%2Fos-autoinst-distri-opensuse%23microos_docker&modules=&module_re=&build=94.2_6.9&distri=sle-micro&version=5.2#)

### CODE REVIEW

**Review by pdostal — APPROVED** [review]
This is awesome :rocket:

**Comment by jlausuch** [comment]
@Vogtinator: 2 questions about MicroOS Container-Host flavor:
1) Is it ok to run docker tests by default (as we do for podman) in the same job?
2) I kept docker coverage it as it was for podman in MicroOS (podman and podman_image tests only). Do we want to include all the other tests (e.g. podman_firewall, rootless_podman, docker_firewall, docker_runc) ?

**Comment by Vogtinator** [comment]
> @Vogtinator: 2 questions about MicroOS Container-Host flavor:
> 
> 1. Is it ok to run docker tests by default (as we do for podman) in the same job?

IMO yes

> 2. I kept docker coverage it as it was for podman in MicroOS (podman and podman_image tests only). Do we want to include all the other tests (e.g. podman_firewall, rootless_podman, docker_firewall, docker_runc) ?

If they don't take too long, sure

**Comment by jlausuch** [comment]
@Vogtinator Please take a look at the new VRs with latest code:
https://openqa.opensuse.org/tests/overview?version=Tumbleweed&distri=microos&build=jlausuch%2Fos-autoinst-distri-opensuse%23microos_docker

It really increases the coverage quite a lot in all container-host flavors. Execution time is 1h 20min on average for each job.

**Review by mloviska — APPROVED** [review]
LGTM, but let's wait for s390x

**Pull request merged**
