### PR TITLE
Decommission console/ssh_pubkey module

### PR DESCRIPTION
**Pull request by mloviska**
As there is significant overlap between modules described in below
ticket, it would be better to keep only `sshd` as it contains more test
objects.

- [[security] overlap in test objects of ssh_pubkey and sshd test cases](https://progress.opensuse.org/issues/96170)

### CODE REVIEW

**Comment by mloviska** [comment]
@jouyingbin, @lilyeyes could you please have a look ?

**Comment by okurz** [comment]
s/Decomminssion/Decommission/

**Comment by mloviska** [comment]
> s/Decomminssion/Decommission/

:bowing_man:

**Comment by lilyeyes** [comment]
Could you please offer the verification run?

**Comment by mloviska** [comment]
> Could you please offer the verification run?

here you go :)

* [tw-jeos-fips](http://kepler.suse.cz/tests/6466#)
* [sle-15-SP3-Online-x86_64-Build187.1-fips_env_mode_tests_crypt_core@64bit](http://kepler.suse.cz/tests/6467#)

**Comment by lilyeyes** [comment]
Generally looks good to me. But,
I would like to make sure the changes introduce no new failure:
For failure in http://kepler.suse.cz/tests/6467#step/test_repo_setup/16
Could you please fix the "SUSEConnect -r" error so test steps/modules can be proceeded?

For failure in http://kepler.suse.cz/tests/6466#step/openssl_fips_alglist/10
This is a known issue so it is OK. (@jouyingbin  said it is a know issue)

**Comment by jouyingbin** [comment]
I think it looks good to me.
Just I have 2 comments for your reference.
1. The PR upudate a softfail about testing sshd problem under FIPS mode. Looks like this PR doesn't affect your test in JEOS build, I am not sure why you did not meet it in JEOS build.
    - Softfail sshd service failure under FIPS (https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13086). 
2.  There is a bug record about it,
   - FIPS: Failed to start OpenSSH Daemon https://bugzilla.suse.com/show_bug.cgi?id=1189534

**Comment by mloviska** [comment]
> Generally looks good to me. But,
> I would like to make sure the changes introduce no new failure:
> For failure in http://kepler.suse.cz/tests/6467#step/test_repo_setup/16
> Could you please fix the "SUSEConnect -r" error so test steps/modules can be proceeded?
> 

Sorry my previous PR introduced a regression issue over [here](https://openqa.suse.de/tests/6888663#step/fips_setup/31).
It should be addressed in the other commit.
VRs:

* [sle-15-SP4-Online-x86_64-Build26.1-fips_env_mode_tests_crypt_core@64bit](http://kepler.suse.cz/tests/6508#)
* [sle-15-SP3-Online-x86_64-Build187.1-fips_env_mode_tests_crypt_core@64bit](http://kepler.suse.cz/tests/6509)

**Comment by mloviska** [comment]
> I think it looks good to me basically.
> Just I have 3 comments for your reference.
> 
>     1. The PR update a softfail fix in SLE15SP2 about testing sshd problem under FIPS mode. Looks like this PR doesn't affect your test in JEOS build, I am not sure why you did not meet it in JEOS build.
>        
>        * Softfail sshd service failure under FIPS ([Softfail sshd service failure under FIPS #13086](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13086))
> 
>     2. There is a bug record about it, Marcus mentioned it in the bug and could be a pattern base issue. Does it mean you don't need to install the related FIPS patterns for testing in JEOS?
>        
>        * FIPS: Failed to start OpenSSH Daemon (https://bugzilla.suse.com/show_bug.cgi?id=1189534)
> 
>     3. For `sle-15-SP3-Online-x86_64-Build187.1-fips_env_mode_tests_crypt_core@64bit`  test run, I suppose it could also introduce the bsc#1189534 if all test cases were run completely.
> 
> 
> Thank you. :)

JeOS does not have any specific patterns, it is the same as `sle` so patterns and packages are completely the same, although the kernel has been slimmed down. I am not able to reproduce the mentioned issue in my local runs, unfortunately (Maybe it has been fixed in newer version ? -- http://kepler.suse.cz/tests/6516#step/patch_and_reboot/155).
AFAICT, the process of enabling fips in JeOS should be completely the same, as JeOS is only deliverable/form factor of `sle`. 

* [sle-15-SP2-JeOS-for-kvm-and-xen-Updates-x86_64-Build20210824-1-jeos-fips@uefi-virtio-vga](http://kepler.suse.cz/tests/6516)

**Comment by jouyingbin** [comment]
> > I think it looks good to me basically.
> > Just I have 3 comments for your reference.
> > ```
> > 1. The PR update a softfail fix in SLE15SP2 about testing sshd problem under FIPS mode. Looks like this PR doesn't affect your test in JEOS build, I am not sure why you did not meet it in JEOS build.
> >    
> >    * Softfail sshd service failure under FIPS ([Softfail sshd service failure under FIPS #13086](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13086))
> > 
> > 2. There is a bug record about it, Marcus mentioned it in the bug and could be a pattern base issue. Does it mean you don't need to install the related FIPS patterns for testing in JEOS?
> >    
> >    * FIPS: Failed to start OpenSSH Daemon (https://bugzilla.suse.com/show_bug.cgi?id=1189534)
> > 
> > 3. For `sle-15-SP3-Online-x86_64-Build187.1-fips_env_mode_tests_crypt_core@64bit`  test run, I suppose it could also introduce the bsc#1189534 if all test cases were run completely.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you. :)
> 
> JeOS does not have any specific patterns, it is the same as `sle` so patterns and packages are completely the same, although the kernel has been slimmed down. I am not able to reproduce the mentioned issue in my local runs, unfortunately (Maybe it has been fixed in newer version ? -- http://kepler.suse.cz/tests/6516#step/patch_and_reboot/155).
> AFAICT, the process of enabling fips in JeOS should be completely the same, as JeOS is only deliverable/form factor of `sle`.
> 
>     * [sle-15-SP2-JeOS-for-kvm-and-xen-Updates-x86_64-Build20210824-1-jeos-fips@uefi-virtio-vga](http://kepler.suse.cz/tests/6516)

Thanks @mloviska for your information. sshd testing in 15 SP2 JeOS result looks better than SLE15 SP3/SP4. I will track it in SLE15 SP4 in the next build release.  But back into this PR is looking good to me without a problem.

**Review by jouyingbin — APPROVED** [review]
LGTM. thanks for the update.

**Comment by lilyeyes** [comment]
Thanks for the verification runs and the changes.
Checked the failed sshd, it is a know issue, see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13082#issuecomment-904493020 FYI.

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Pull request merged**
