### PR TITLE
Fix some perltidy complains

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
Still tidy doesn't pass ;)
+1 even though we already implicitly load strict by inheriting from basetest. Critic probably doesn't detect that.

**Comment by coolo** [comment]
yeah, I know. I would feel more nervous if we didn't :)

**Comment by okurz** [comment]
What mechanism is expected to call the new make target? Don't we want to enable it as part of "make test" so that also travis calls it?

**Comment by coolo** [comment]
once you fixed all the tests, we can enable regression testing - yes

**Pull request merged**
