### PR TITLE
mysql_odbc: fix test for Tumbleweed

### PR DESCRIPTION
**Pull request by ggardet**
- Related ticket: https://progress.opensuse.org/issues/71929
- Verification run: https://openqa.opensuse.org/t1460529

### CODE REVIEW

**Comment by Vogtinator** [comment]
Oh, I was about to file a PR with a similar change, but you were quicker.

I'm doing

```
+    if (is_sle('<15') || is_leap('<15.0')) {
+        assert_script_run 'echo Driver=$(rpm --eval "%_libdir")/libmyodbc5.so >> /etc/unixODBC/odbcinst.ini';
+    } else {
+        assert_script_run 'echo Driver=$(rpm -ql mariadb-connector-odbc | grep -E libmaodbc.so\$) >> /etc/unixODBC/odbcinst.ini';
+    }
```

instead which doesn't depend on `is_tumbleweed` (which doesn't match the next Leap) and I fixed

`assert_script_run 'echo Setup=$(rpm --eval "%_libdir")/unixODBC/libodbcmyS.so >> /etc/unixODBC/odbcinst.ini';`

as well, which had a wrong path.

**Comment by ggardet** [comment]
@Vogtinator I updated the PR with your suggestions and started a new verification run.  Thanks for the review!

**Comment by Vogtinator** [comment]
Some VRs with reduced schedule and using JeOS to avoid the installation:

15.2: https://openqa.opensuse.org/tests/1460530
TW: https://openqa.opensuse.org/tests/1460531

**Review by Vogtinator — APPROVED** [review]
VRs passed

**Pull request merged**
