### PR TITLE
Show more details on package updater failure

### PR DESCRIPTION
**Pull request by baierjan**
If the updater fails, make it possible to show more details.

- Related ticket: https://progress.opensuse.org/issues/37970
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/879
- Verification runs: 
    - http://panigale.suse.cz/tests/2402#step/updates_packagekit_gpk/27
    - http://panigale.suse.cz/tests/2404#step/updates_packagekit_gpk/13

### CODE REVIEW

**Comment by czerw** [comment]
What about needle fo openSUSE?

**Comment by baierjan** [comment]
The needle should be created through openQA GUI as the fail cannot be currently reproduced.

**Comment by dzedro** [comment]
the needle is not so critical it's just detail of the failure, will be created later

**Comment by czerw** [comment]
Needle was created on openqa.opensuse.org from this failure https://openqa.opensuse.org/tests/698089#step/updates_packagekit_gpk/18

**Pull request merged**
