### PR TITLE
Use linuxrc info file for installation repository

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
The repository URL is too long for the 72 line limit of IBM z/VM XEDIT

- Related ticket: https://progress.opensuse.org/issues/77116
- Verification run: (coming soon)

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by SergioAtSUSE** [comment]
@okurz, s.qa.suse.de is not available from the openSUSE network, which URL shortener would you recommend to use for openSUSE?

**Comment by okurz** [comment]
Hm, try v.gd . Don't know if it makes problems with the preview.

**Comment by SergioAtSUSE** [comment]
Found another way: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/107

**Pull request closed without merging**
