### PR TITLE
Ensure password prompt with blinking cursor is found

### PR DESCRIPTION
**Pull request by okurz**
Fixes https://openqa.opensuse.org/tests/370454#step/user_gui_login/9

Verification run: http://lord.arch.suse.de/tests/6077

### CODE REVIEW

**Comment by okurz** [comment]
waiting for verification run

**Comment by dzedro** [comment]
Still waiting ?

**Comment by okurz** [comment]
anyone can check. the link is there. http://lord.arch.suse.de/tests/6077 failed as "incomplete". Need to check in detail

**Comment by coolo** [comment]
the failure still appears in current TW

**Pull request merged**
