### PR TITLE
Add debug info for ssh on xen domu

### PR DESCRIPTION
**Pull request by museQi**
Enhance code for ssh connecting to guest, to make code can accurately diagnostic if the guest is running, crash or block
Dynamically adjust the timeout when ssh to guest which can reduce the running time when ssh failure.

- Related ticket:https://progress.opensuse.org/issues/73828?issue_count=126&issue_position=115&next_issue_id=73804&prev_issue_id=73840
- Verification run: http://10.67.129.7/tests/2101#downloads

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @zyuhu Please help me review.

**Comment by zyuhu** [comment]
LGTM

**Comment by XGWang0** [comment]
LGTM in code syntax

**Comment by museQi** [comment]
@alice-suse hello alice,please help me review and merge.

**Pull request merged**
