### PR TITLE
[AARCH64 Automation] Reset to boot from pxe for aarch64 after new installation

### PR DESCRIPTION
**Pull request by waynechen55**
Certain aarch64 machine, for example, centriq series will override itself's first boot option with newly installed system. This PR developed a new subroute called set_pxe_efiboot to reset first boot
option to pxe using efibootmgr just before system reboot. The current implementation has already taken centriq, huawei and thunderx machines into consideration. Other types of machine may be added later.

- Related ticket: aarch64 ipmi backend
- Needles: n/a
- Verification run: http://10.162.187.154/tests/265
   http://10.162.187.154/tests/666    huawei
   http://10.162.187.154/tests/677    thunderx11
   http://10.162.187.154/tests/862   centriq4
@alice-suse @XGWang0 @XGUO @Julie-CAO

### CODE REVIEW

**Comment by asdil12** [comment]
Please squash the `Tidy up code` commit into your other commits.

**Comment by waynechen55** [comment]
> Please squash the `Tidy up code` commit into your other commits.

Done.

**Comment by okurz** [comment]
LGTM, ready to be merged?

**Comment by waynechen55** [comment]
In the light of there are not too many other types of aarch64 platforms on orthos, I will extend compatibility besides centriq, huawei and thunderx. But additional verification run with thunderx and centriq is still necessary from my POV.

**Comment by waynechen55** [comment]
Do you know how to resolve this check failing ?   @okurz 
Use of my $_ is experimental at lib/ipmi_backend_utils.pm line 270.

**Comment by waynechen55** [comment]
Verification run and the latest fix are all done. Please help merge.

**Pull request merged**
