### PR TITLE
Fix for deprecated sapwmp package on SLE15SP5+

### PR DESCRIPTION
**Pull request by emiura**
Fixes PED-131

Failure:
https://openqa.suse.de/tests/10694295#step/wmp_setup/1

VR:
https://openqa.suse.de/tests/10702298#step/wmp_setup/1

### CODE REVIEW

**Review by bs-suse — APPROVED** [review]
LGTM

**Review by lpalovsky — APPROVED** [review]
LGTM

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by alvarocarvajald** [comment]
I suppose we can also remove the wmp modules from the schedule once 15-SP5 is done.

**Pull request merged**
