### PR TITLE
Adapt full medium to new welcome screen bsc#1192626

### PR DESCRIPTION
**Pull request by foursixnine**
https://build.suse.de/request/show/258526 changed the behavior for the full medium, so now there's no product selection for s390 at all

s390 Full: https://openqa.suse.de/tests/7861118#
x86 Full: https://openqa.suse.de/tests/7861139#

### CODE REVIEW

**Comment by foursixnine** [comment]
@jknphy This is what we were talking about yesterday, is there something I'm missing? I'm still curious on why s390 is behaving differently for full medium...

**Comment by jknphy** [comment]
> @jknphy This is what we were talking about yesterday, is there something I'm missing? I'm still curious on why s390 is behaving differently for full medium...

Confirmed that "SUSE Manager will come on the full media with the first Quaterly update." so for now it goes directly to that screen.
@foursixnine  Could you check the verification links? @OleksandrOrlov could you take a look?

**Comment by foursixnine** [comment]
> > @jknphy This is what we were talking about yesterday, is there something I'm missing? I'm still curious on why s390 is behaving differently for full medium...
> 
> Confirmed that "SUSE Manager will come on the full media with the first Quaterly update." so for now it goes directly to that screen. @foursixnine Could you check the verification links? @OleksandrOrlov could you take a look?

Links are fixed, so by the QU moment, we should plan already to move the jobs on functional to use libyui.

@tjyrinki can you take care of planning this beforehand, so that there are no surprises?

**Comment by OleksandrOrlov** [comment]
@foursixnine Thank you for adapting the module. LGTM. 

The only thing, I started VRs for current QR Job Group to check that it works there as well. Let's wait for the jobs to be passed through `welcome` test module before merging the PR.

Full: https://openqa.suse.de/t7865960
Online: https://openqa.suse.de/t7865961

**Comment by foursixnine** [comment]
> @foursixnine Thank you for adapting the module. LGTM.
> 
> The only thing, I started VRs for current QR Job Group to check that it works there as well. Let's wait for the jobs to be passed through `welcome` test module before merging the PR.
> 
> Full: https://openqa.suse.de/t7865960 Online: https://openqa.suse.de/t7865992

Looks like we should be good to go!

**Comment by tjyrinki** [comment]
I'm not sure if it's related but the 15-SP3 QU2 has already started largely failing for Full media in the last 1 week or a little more: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=196.3&groupid=373

I hope someone can shed a light on that one, and aside from that I think I'll need some more time to understand what's required to be planned for SP4 as such, and I don't have the bandwidth right now.

**Comment by jknphy** [comment]
> 

apparently the needles, seems that now there are `-` instead of spaces ` `. Wrong metadata for product name?

**Comment by foursixnine** [comment]
> and aside from that I think I'll need some more time to understand what's required to be planned for SP4 as such, and I don't have the bandwidth right now.

We need to adopt libyui in for product development and also for QU's where it is supported, so that we can really benefit from changes yast guys do for the installer. That's what needs to be planned.

**Comment by OleksandrOrlov** [comment]
> > and aside from that I think I'll need some more time to understand what's required to be planned for SP4 as such, and I don't have the bandwidth right now.
> 
> We need to adopt libyui in for product development and also for QU's where it is supported, so that we can really benefit from changes yast guys do for the installer. That's what needs to be planned.

@foursixnine We are glad to assist you in that part. This is in our plans as well (Please, see our roadmap, point 7: http://s.qa.suse.de/qe-yast-roadmap). For sure it will be more effective in collaboration between teams, rather then if we'll do it on our own;)

**Comment by foursixnine** [comment]
So in general, I'll proceed to merge this then

**Review by OleksandrOrlov — APPROVED** [review]

**Pull request merged**
