### PR TITLE
Create agama auto-installation selecting gnome pattern

### PR DESCRIPTION
**Pull request by hjluo**
##
### Create agama auto-installation selecting gnome pattern

- Related ticket: https://progress.opensuse.org/issues/167060
- Needles: N/A
- Verification run: 
   - [**agama_auto_gnome**](https://openqa.opensuse.org/tests/overview?arch=x86_64&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&version=agama-9.0&distri=opensuse&build=hjluo#)
   
##

### CODE REVIEW

**Comment by jknphy** [comment]
Please, do not forget to set up WIP in your PR.

**Comment by jknphy** [comment]
there are a lot of verification in your links above, could you filter the one related with this ticket or comment about the failures?

**Comment by hjluo** [comment]
> there are a lot of verification in your links above, could you filter the one related with this ticket or comment about the failures?

Done && thank you.

**Comment by jknphy** [comment]
why all of them are failing, could you include your conclusion here?

**Comment by hjluo** [comment]
> why all of them are failing, could you include your conclusion here?

cause they are hang there forever as we discussed last week :smile:

**Comment by jknphy** [comment]
I suspect it is connected with:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/await_install.pm#L120-L124
we cannot just wait for the needle to appear.
Let's do the following:
- Merge this PR
- Setup the test suite in the job group (failing on that, it is ok)
- Try to change that part of the code to have a "active wait".

**Comment by hjluo** [comment]
> I suspect it is connected with: [`master`/tests/installation/await_install.pm#L120-L124](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/await_install.pm?rgh-link-date=2024-10-07T12%3A03%3A46Z#L120-L124) we cannot just wait for the needle to appear. In this case the way to investigate this kind of failures is to check how is done in other products.
> 
> Let's do the following:
> 
> * Merge this PR
> * Setup the test suite in the job group (failing on that, it is ok)
> * Try to change that part of the code to have a "active wait".

OK, I'd add the tests and try to change that code to see if it works. Thanks.

**Comment by jknphy** [comment]
> > I suspect it is connected with: [`master`/tests/installation/await_install.pm#L120-L124](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/await_install.pm?rgh-link-date=2024-10-07T12%3A03%3A46Z#L120-L124) we cannot just wait for the needle to appear. In this case the way to investigate this kind of failures is to check how is done in other products.
> > Let's do the following:
> > 
> > * Merge this PR
> > * Setup the test suite in the job group (failing on that, it is ok)
> > * Try to change that part of the code to have a "active wait".
> 
> OK, I'd add the tests and try to change that code to see if it works. Thanks. PS: it's PASSED after triggering. https://openqa.opensuse.org/tests/4542435

but that job has too much RAM, 4GB should be enough.

**Comment by jknphy** [comment]
> > > > I suspect it is connected with: [`master`/tests/installation/await_install.pm#L120-L124](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/installation/await_install.pm?rgh-link-date=2024-10-08T08%3A20%3A56Z#L120-L124) we cannot just wait for the needle to appear. In this case the way to investigate this kind of failures is to check how is done in other products.
> > > > Let's do the following:
> > > > 
> > > > * Merge this PR
> > > > * Setup the test suite in the job group (failing on that, it is ok)
> > > > * Try to change that part of the code to have a "active wait".
> > > 
> > > 
> > > OK, I'd add the tests and try to change that code to see if it works. Thanks. PS: it's PASSED after triggering. [openqa.opensuse.org/tests/4542435](https://openqa.opensuse.org/tests/4542435)
> > 
> > 
> > but that job has too much RAM, 4GB should be enough. When you do the setup do all with default values.
> 
> now all with 4G RAM with mouse moving, [**all 20 cases**](https://openqa.opensuse.org/tests/overview?arch=x86_64&flavor=&machine=&test=&modules=&module_re=&group_glob=&not_group_glob=&comment=&build=hjluo&version=agama-9.0&distri=opensuse#) passed.

but they pass without the new code for the mouse moving and 4G? (I guess not, asking just in case was something sporadic you found)

**Pull request merged**
