### PR TITLE
Generate a uefi qcow image used by security tests

### PR DESCRIPTION
**Pull request by Amrysliu**
Our CC and FIPS tests should cover UEFI secure boot mode, so need to
generate a qcow file for these tests.

Related: https://progress.opensuse.org/issues/111389
Verify run: https://openqa.suse.de/tests/8830704# 
                 https://openqa.suse.de/tests/8830743#  (The job run base on the qcow2 published by the above job)

### CODE REVIEW

**Review by rfan1 — APPROVED** [review]
LGTM

**Comment by rfan1** [comment]
Let us wait for experts' comments from yast team before merge this PR

**Comment by rfan1** [comment]
@Amrysliu 
BTW, Can we use the same yaml_schedule file as existing ones?

**Review by rfan1 — COMMENTED** [review]
Please check if we can use the existing yaml_schedule file

**Comment by Amrysliu** [comment]
> Please check if we can use the existing yaml_schedule file

yes, I think Roy and I could use one yaml file.

**Comment by jknphy** [comment]
check comments from https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14938
and I would suggest to ensure with verification that children job run properly (AutoYaST also might have some bugs :) )

**Review by wangqianzou — APPROVED** [review]
LGTM

**Comment by jknphy** [comment]
LGTM

**Pull request merged**
