### PR TITLE
Remove KEEP_GRUB_TIMEOUT from wait_grub related test

### PR DESCRIPTION
**Pull request by asmorodskyi**
Remove KEEP_GRUB_TIMEOUT from wait_grub related test

code cleanup after merging #8142 .

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@okurz , @rwx788 , @alvarocarvajald , @SergioAtSUSE - WDYT ? Also I am not sure which tests I need to re-run to prove that this will work

**Comment by alvarocarvajald** [comment]
Testing `sles4sap_scc_gnome_sap_inst_wizard` over IPMI which uses **KEEP_GRUB_TIMEOUT**: https://openqa.suse.de/tests/3226009

**Comment by alvarocarvajald** [comment]
> Testing `sles4sap_scc_gnome_sap_inst_wizard` over IPMI which uses **KEEP_GRUB_TIMEOUT**: https://openqa.suse.de/tests/3226009

Still failing in `installation/first_boot` because SUT is already at `linux-login`. My guess is that the changes in `lib/opensusebasetest.pm` are not necessary at least for this case.

**Comment by asmorodskyi** [comment]
> > Testing `sles4sap_scc_gnome_sap_inst_wizard` over IPMI which uses **KEEP_GRUB_TIMEOUT**: https://openqa.suse.de/tests/3226009
> 
> Still failing in `installation/first_boot` because SUT is already at `linux-login`. My guess is that the changes in `lib/opensusebasetest.pm` are not necessary at least for this case.

this does not make sense to me , just before first_boot you have reconnect_mgmt_console which already did detect of PXE boot menu , why you need to do it again ?

**Comment by alvarocarvajald** [comment]
> this does not make sense to me , just before first_boot you have reconnect_mgmt_console which already did detect of PXE boot menu , why you need to do it again ?

Exactly! Same thing is happening with this SLE Functional test (no KEEP_GRUB_TIMEOUT related, but runs also over IPMI): https://openqa.suse.de/tests/3204203#step/first_boot/10.

AFAICS both `boot/reconnect_mgmt_console` and `installation/grub_test` are getting scheduled by `main_common::load_reboot_tests`  when `BACKEND=ipmi`, so with the `installation/first_boot` there seems to be at most 3 tests trying to assert a qa_net/grub screen before continuing.

**Comment by asmorodskyi** [comment]
Sorry I can't follow you . https://openqa.suse.de/tests/3204203#step/first_boot/10 -
1. Was happening 5 days ago and I merged #8142 3 hours ago 
2. Does not contain KEEP_GRUB_TIMEOUT 
So how this failure ( and probably https://openqa.suse.de/tests/3226009 too )  can be related to this PR or #8142 ?

**Comment by alvarocarvajald** [comment]
> Sorry I can't follow you . https://openqa.suse.de/tests/3204203#step/first_boot/10 -
> 
> 1. Was happening 5 days ago and I merged #8142 3 hours ago
> 2. Does not contain KEEP_GRUB_TIMEOUT
>    So how this failure ( and probably https://openqa.suse.de/tests/3226009 too )  can be related to this PR or #8142 ?

Yes, this is unrelated to #8142. I just thought that perhaps the removal of `installation/grub_test` when `KEEP_GRUB_TIMEOUT=1` would also help with `https://openqa.suse.de/tests/3226218#settings`.

Sorry for the noise.

**Pull request merged**
