### PR TITLE
[WIP] Add a sample hello world test in virt_autotest

### PR DESCRIPTION
**Pull request by sudarshannm**
This PR contains a very basic hello world test module added in the virt_autotest.  
And for speeding up the testing of this module, I have removed all other tests from the yaml file.  

- Related ticket: Not related to any ticket.
- Needles: No corresponding needles.
- Verification run: This modules is testes on my local openqa setup : 
  Pass Job : http://10.67.129.155/tests/75
  Fail Job : http://10.67.129.155/tests/72

Please Note : This PR is just for learning the PR process. And would be repaired back immediately. We are also committing these changes in a private branch.

### CODE REVIEW

**Comment by RoyCai7** [comment]
Some comments:

1. About title and description, please refer content and format in this PR.
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15801
[tips] Please keep the title's first word as verb.

2. The code cannot pass basic check, it is just a test.
3. This workflow requires approval from a maintainer. for this, maybe Alice has privilege.
4. Another question, I found you have 2 commits, Please combine them into one. 
Please refer doc: https://confluence.suse.com/pages/viewpage.action?pageId=1262452757

**Comment by RoyCai7** [comment]
[Important] This is just a test, please don't merge it.

**Comment by RoyCai7** [comment]
Please add tag ‘WIP’ or 'not ready' in title.
[WIP] or [not ready]

**Comment by sudarshannm** [comment]
Closing this PR as whatever I wanted to try is completed.

**Pull request closed without merging**
