### PR TITLE
s390x: Add ability to install from smb

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
Verification run: http://opeth.suse.de/tests/4717

**Comment by coolo** [comment]
I see no proof in there that it's really using smb :)

**Comment by coolo** [comment]
I guess once its down, we can check the yast logs

**Comment by Soulofdestiny** [comment]
http://opeth.suse.de/tests/4717#step/bootloader_s390/19 there you have at least a little proof

but yeah, a better check would be good, I guess

**Comment by Soulofdestiny** [comment]
@coolo you think about greping for something like this:
`'[Ruby] modules/InstURL.rb:160 Using install URL: smb://openqa/inst/SLE-12-SP3-Server-DVD-s390x-Build0239-Media1"`

?

**Comment by coolo** [comment]
No, I wouldn't rely on yast logs for a test. But to verify that the change works, it's good to see.

**Comment by okurz** [comment]
an extension could be to also install addon/module over smb from within the installer which most certainly will cover something smb specific, at least a checkbox selection, so that might be a more robust check.

**Comment by Soulofdestiny** [comment]
already done ;)

**Pull request merged**
