### PR TITLE
Btrfs send & receive snapshots

### PR DESCRIPTION
**Pull request by kravciak**
Should I add NUMDISKS=2 to extratests or create new test suite?
Local runs:
TW - http://dhcp91.suse.cz/tests/1783
SLES - http://dhcp91.suse.cz/tests/1787

### CODE REVIEW

**Comment by sysrich** [comment]
NUMDISKS=2 to extratests I guess, seems the most efficient solution

This should probably also be in the openSUSE main.pm for SLE 13

**Comment by kravciak** [comment]
Btrfs send & receive is present in Leap and TW, I think can add this to opensuse now..or?

**Comment by okurz** [comment]
Sure, that would be great. In general you can also try to develop tests on TW and then "backport" to SLE and Leap as everything on this layer should be in TW.

**Comment by kravciak** [comment]
Tested on TW, works fine (Leap 42.2 extra-tests are broken)

**Pull request merged**
