### PR TITLE
Update aytest repo setting for SLE 12 to SP4

### PR DESCRIPTION
**Pull request by rwx788**

### CODE REVIEW

**Comment by rwx788** [comment]
Unfortunately, my multi machine setup is broken, so cannot have it anytime soon.
Cloning on OSD fails with ``` backend::baseclass::die_handler('Set HDDMODEL to scsi-h and SCSICONTROLLER to virtio-scsi-pci ...') called at /usr/lib/os-autoinst/OpenQA/Qemu/Proc.pm line 96``` at the moment

**Comment by SergioAtSUSE** [comment]
Feel free to merge if you are confident enough ;)

**Comment by okurz** [comment]
LGTM

**Comment by rwx788** [comment]
@okurz as I've stated in my comment, problem is that package is cannot be built due to some issues in the ibs. My guess was that changes are submitted to another project, but they are not in any of those, so I keep it open until it's clear.

**Comment by rwx788** [comment]
See https://progress.opensuse.org/issues/40982

**Pull request closed without merging**
