### PR TITLE
Update wireshark.pm to fix poo#16638

### PR DESCRIPTION
**Pull request by chuchingkai**
Verification test: http://147.2.212.103/tests/557

see also: https://progress.opensuse.org/issues/16638#note-7

### CODE REVIEW

**Comment by plusky** [comment]
There is new version (major version bump) of wireshark coming up, so I would suggest waiting for it to be released as this fix might be not needed.

**Comment by chuchingkai** [comment]
@plusky OK, thanks for your information, so I will close this PR.

**Comment by chuchingkai** [comment]
As plusky commented, new wireshark is comming, currently wireshark failed at the last few steps which is not critical, and it is not reproducible every time, so I will close this PR.

**Comment by okurz** [comment]
I guess "new version coming" should not prevent us from fixing existing behaviour especially when not even a SR is open. Do we really expect a new version in SLED 12 SP3 still? Both the "wait_still_screen" look fine for me so please reopen the PR and we can merge it.

LGTM

**Pull request closed without merging**
