### PR TITLE
Add samba server test replacing mau-qa_userspace_samba

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/99645
Verification: http://kazhua.qa.suse.de/tests/17

### CODE REVIEW

**Comment by asdil12** [comment]
Meh - I fall for `set -o pipefail` every time.

**Comment by punkioudi** [comment]
Could you also add the VRs for sle maintenance?

**Comment by asdil12** [comment]
15sp2: http://kazhua.qa.suse.de/tests/31

**Review by punkioudi — APPROVED** [review]
Lgtm! If it verification runs are good for the sle versions that are not linked here in the PR, then I suppose it can be merged.

**Pull request merged**
