### PR TITLE
More strict perlcritic checks

### PR DESCRIPTION
**Pull request by okurz**
* Add missing 'use warnings' according to perlcritic checks
* sles4sap: Reuse 'pre_run_hook' from hacluster
* Disable 'use warnings' for lib/main_ltp.pm
* Adapt existings tests to adhere to 'use strict'
* Specify policy to exclude with ## no critic
* Enable check for "use strict" and "use warnings"

### CODE REVIEW

**Comment by okurz** [comment]
A fast review would be appreciated due to the high conflict risk :)

**Comment by b10n1k** [comment]
i have a question as newbie. 
As the base "opensusebasetest" includes the warnings module, do you have to define it in any child that inherits opensusebasetest?

**Comment by jknphy** [comment]
> i have a question as newbie.
> As the base "opensusebasetest" includes the warnings module, do you have to define it in any child that inherits opensusebasetest?

I think is related with [Perl::Critic::Policy::TestingAndDebugging::RequireUseWarnings](https://metacpan.org/pod/release/ELLIOTJS/Perl-Critic-1.107_001/lib/Perl/Critic/Policy/TestingAndDebugging/RequireUseWarnings.pm) because it is checked at the level of package, does it work like that @okurz ?

**Comment by alexandergraul** [comment]
`perlcritic` does static analysis on each module separately and will complain about any without both `use strict` and `use warnings` (unless the perl version is specified and recent enough). Then `test-compile` will fail if `use strict` is in a module but the module does something that is not allowed in strict-mode.

I am not sure if `use warnings` in opensusebastest would be enough, but if it is we'd need to split the  perlcritic check. Once for all modules (as it is already at the moment) and a second time only for opensusebasetest for the 'strict' check.

**Comment by okurz** [comment]
There are some rough rules of thumb, such as modules whose names are lowercase are "pragmas" and their effect is often (but not always!) lexically scoped (warnings and strict being the two most common). Meaning: `use warnings;` is part of the boiler-plate code we need to add to every file.

**Comment by okurz** [comment]
you are so brave ;)

**Pull request merged**
