### PR TITLE
LTP: Install debugging tools

### PR DESCRIPTION
**Pull request by pevik**
This helps debugging when on downloaded qcow2 image.

### CODE REVIEW

**Comment by pevik** [comment]
@richiejp @metan-ucw FYI

**Comment by pevik** [comment]
Looks like only `ltrace` was missing (`strace` and `gdb` is already installed, see http://quasar.suse.cz/tests/2128/file/serial_terminal.txt), but I'd keep installed ones as well in case the default setting change.

**Comment by metan-ucw** [comment]
@pevik Are you sure, I have build 188.1 booted here and neither strace nor gdb is present. I guess that SLE12 is different from SLE15 after all.

**Comment by pevik** [comment]
@metan-ucw: Agree, all 3 are needed on SLE15 (http://quasar.suse.cz/tests/2129/file/serial_terminal.txt), I was checking SLE12 only.

**Comment by richiejp** [comment]
These tools are all quite small right?

**Comment by pevik** [comment]
Yes: `gdb`: 3.7 MiB, others less than 1MiB
http://quasar.suse.cz/tests/2129/file/serial_terminal.txt

**Comment by pevik** [comment]
And I added it into separate method as a self documenting.

**Pull request merged**
