### PR TITLE
Add parameter to boot_from_pxe and ipmi_to_qemu for mitigation workaround

### PR DESCRIPTION
**Pull request by lansuse**
1.     Add parameter DIST_FOR_REPO to set repo url
    
    Generally, SLES repo is not ready before beta test. This parameter provide
    a way to set os-version to generate repo url.

2.     Add extra parameter in cmdline when needed
    
    Sometimes, we want to add a parameter in cmdline. Such as for a
    workaround.

- Related ticket: https://progress.opensuse.org/issues/78324
https://progress.opensuse.org/issues/78322
- Needles: N/A
- Verification run: http://10.67.134.217/tests/11791
http://10.67.134.217/tests/11803

### CODE REVIEW

**Comment by lansuse** [comment]
@alice-suse @Dawei-Pang @XGWang0 PTAL

**Comment by XGWang0** [comment]
LGTM except travis failure

**Comment by alice-suse** [comment]
Do you make them in 2 commits on purpose? If yes, I think it is ready to be merged.

**Comment by lansuse** [comment]
> Do you make them in 2 commits on purpose? If yes, I think it is ready to be merged.

Yes

**Pull request merged**
