### PR TITLE
[WIP] Enable svirt serial console also for XEN

### PR DESCRIPTION
**Pull request by pevik**
- Needles: none
- Verification run: TODO

### CODE REVIEW

**Comment by pevik** [comment]
@a-kpappas FYI: running verification run:
disabled svirt serial console (the default): https://openqa.suse.de/tests/3241270
enabled svirt serial console: https://openqa.suse.de/tests/3241274

**Comment by a-kpappas** [comment]
I also launched a verification run with your code but it starts. https://openqa.suse.de/tests/3241272

**Comment by pevik** [comment]
For enabling it's needed to add `SERIAL_CONSOLE=1` atm. Later, when merged, `SERIAL_CONSOLE=0` should be removed from medium setup instead.

**Comment by pevik** [comment]
My verification run:
https://openqa.suse.de/tests/3241276 (without serial console)
https://openqa.suse.de/tests/3241287 (*with* serial console)

**Comment by pevik** [comment]
New test runs for different backends/architectures:
sle-12-SP5-Server-DVD-x86_64-Build0261-extra_tests_in_textmode@svirt-xen-pv -> http://openqa.suse.de/t3241404
sle-12-SP5-Server-DVD-x86_64-Build0261-extra_tests_in_textmode@svirt-xen-hvm -> http://openqa.suse.de/t3241405
sle-12-SP5-Server-DVD-aarch64-Build0261-extra_tests_in_textmode@aarch64 -> http://openqa.suse.de/t3241406
sle-12-SP5-Server-DVD-x86_64-Build0261-extra_tests_in_textmode@64bit -> http://openqa.suse.de/t3241407

**Comment by pevik** [comment]
@a-kpappas Svirt console is not ready failed for XEN (svirt-xen-pv): 
https://openqa.suse.de/tests/3241404/file/autoinst-log.txt
`error: internal error: cannot find character device console1`

This should be fixed. But for a quick fix, just use select_console 'root-console' to fix gdb (poo#52886).

**Comment by a-kpappas** [comment]
Since there is little possibility that the serial console in xen will be fixed in the near future, and the test as designed requires it, I think it's best that it's disabled for xen. @foursixnine @okurz what do you think?

**Comment by okurz** [comment]
why not fix it? https://github.com/os-autoinst/os-autoinst/blob/master/backend/svirt.pm is probably the place

**Comment by pevik** [comment]
@okurz @a-kpappas not planning to play with it, but at least created a ticket https://progress.opensuse.org/issues/55985

**Pull request closed without merging**
