### PR TITLE
extra_tests_toolkit: qt4 removed from Tumbleweed

### PR DESCRIPTION
**Pull request by ggardet**
- Related ticket: https://progress.opensuse.org/issues/58628
- Verification run: 
  * https://openqa.opensuse.org/t1069290
  * https://openqa.opensuse.org/t1069291

### CODE REVIEW

**Comment by ggardet** [comment]
> Could you please state why we disable them, e.g. qt4 is deprecated in TW?

It is dropped!

**Comment by rwx788** [comment]
> > Could you please state why we disable them, e.g. qt4 is deprecated in TW?
> 
> It is dropped!

From your commit message I can only see that you want to drop test.

**Comment by ggardet** [comment]
Updated!

**Comment by rwx788** [comment]
> Updated!

Thanks. Sorry for nitpicking, but we try to have all the answers in git log and you had reference to the progress ticket. Will merge, once travis is done.

**Comment by ggardet** [comment]
> > Updated!
> 
> Thanks. Sorry for nitpicking, but we try to have all the answers in git log and you had reference to the progress ticket. Will merge, once travis is done.

No problem. It is a QA project after all! ;)

**Pull request merged**
