### PR TITLE
Do not evaluate distro release package

### PR DESCRIPTION
**Pull request by mloviska**
Fix for regression introduced #9263

- Related ticket: [test fails in orphaned_packages_check due to openSUSE-release-dvd](https://progress.opensuse.org/issues/62195)
- Verification runs: 
   * [Build20200115-kde@64bit](https://openqa.opensuse.org/tests/1146597)
   * [Build553.1-gnome@64bit-2G](https://openqa.opensuse.org/tests/1146598)
   * [Build20200115-gnome-live@USBboot_aarch64](https://openqa.opensuse.org/t1146602)
   * [Build21.6-jeos@64bit_virtio-2G](https://openqa.opensuse.org/t1146603)

### CODE REVIEW

**Comment by ggardet** [comment]
LGTM

**Comment by DimStar77** [comment]
Build20200115-kde@64bit failed (even though the orphan.log is empty)

**Comment by mloviska** [comment]
> Build20200115-kde@64bit failed (even though the orphan.log is empty)

yup, not sure why though...
https://openqa.opensuse.org/tests/1146597#step/orphaned_packages_check/9

**Comment by mloviska** [comment]
```
test -s ~/Downloads/orphaned_packages_check-orphaned.log; echo $?
1
```

It's really empty...

**Comment by mloviska** [comment]
**VR2** [Build20200115-kde@64bit](https://openqa.opensuse.org/tests/1147010#)

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/1146637#step/orphaned_packages_check/2

That 'fail' result does also look fishy (marking something as 'failed' just because the system does what we expect it to do?) - let alone that this is not an upgrade scenario - so the 'fail' marker seems worng

**Comment by mloviska** [comment]
> https://openqa.opensuse.org/tests/1146637#step/orphaned_packages_check/2
> 
> That 'fail' result does also look fishy (marking something as 'failed' just because the system does what we expect it to do?) - let alone that this is not an upgrade scenario - so the 'fail' marker seems worng

It is saying that SUT has not been upgraded. Not a fail :)

**Comment by mloviska** [comment]
> https://openqa.opensuse.org/tests/1146637#step/orphaned_packages_check/2
> 
> That 'fail' result does also look fishy (marking something as 'failed' just because the system does what we expect it to do?) - let alone that this is not an upgrade scenario - so the 'fail' marker seems worng

**Pull request merged**
