### PR TITLE
Sle11 slepos tests export

### PR DESCRIPTION
**Pull request by psladek**
Updated SLEPOS tests - image caching, test order update, various fixes

### CODE REVIEW

**Comment by okurz** [comment]
same comments as in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2002 apply about git commit subject lines. Also checks fail but for some weird reason about package installation which I do not yet understand. It might be necessary to update the cpanfile within the test distribution but I just restarted the test on travis to crosscheck if the error is reproducible.

**Comment by psladek** [comment]
travis seems to work now

**Comment by okurz** [comment]
yes, but please think about the git commit messages as stated in before.

**Comment by nadvornik** [comment]
This is port/rewrite of the old SLEPOS test script to openqa. The overall documentation is work in progress. The individual commit messages LGTM.

**Comment by okurz** [comment]
ok, as @nadvornik said

**Pull request merged**
