### PR TITLE
Change "save_and_upload_log" to be reusable from other classes

### PR DESCRIPTION
**Pull request by nicksinger**
This reverts commit 7f6fcda89405c67ecb16970af84d3fa329ed9672 where I made wrong assumptions on how this function gets used.
Next steps are: Change the baseclass of this test, change the function name of "save_and_upload_logs" (<- the trailing "s" makes a difference!) and provide a verification run.

### CODE REVIEW

**Comment by kravciak** [comment]
LGTM

**Comment by nicksinger** [comment]
Turns out that there were more changes needed than expected. The function "save_and_upload_log" from "opensusebasetest" was not correctly accessible because it did not expect $self (which automatically gets passed as first parameter if you call it by $self->save_and_upload_log).
Verification of that specific module (installation.pm) can be seen at my local test instance: http://monteverdi.arch.suse.de/t53
The failing "console" module is already known and addressed in bsc#1042554.

Since I also changed "opensusebasetest" I want to make sure I don't introduce any regressions, I still have to make a verification run of other tests which use "export_logs" (which heavily relies on "save_and_upload_log" inside the same class).
Also the renaming of "save_and_upload_logs" (the function inside installation.pm which confused me in the beginning) is still left open for this PR.

**Comment by okurz** [comment]
Waiting for another verification then

**Comment by nicksinger** [comment]
http://monteverdi.arch.suse.de/tests/62 is the verification that opensusebasetest.pm still works as expected (have a look at the logs and assets and see how "export_logs" collected several logs). I've forced an failure by adding a missing needle to consoletest_setup (Line 37) which is of course not part of the PR ;). 

I also rerun the autoyast_installation test here and everything looks like expected: http://monteverdi.arch.suse.de/tests/63 .

For now, this PR is ready to review.

**Comment by okurz** [comment]
good job!

**Pull request merged**
