### PR TITLE
power_action: Improve readability

### PR DESCRIPTION
**Pull request by pevik**
* else if = > elsif
* add spaces

Verification run:
shutdown
* http://quasar.suse.cz/tests/7607 (15-sp4 install_ltp)
* http://quasar.suse.cz/tests/7611 (Tumbleweed install_ltp)
* http://quasar.suse.cz/tests/7610 (15-sp4 yast2_firstboot@64bit)
* http://quasar.suse.cz/tests/7608 (15-sp4 gnome_http)
reboot
* http://quasar.suse.cz/tests/7612 (ima_appraisal)

### CODE REVIEW

**Comment by pevik** [comment]
Error unrelated:
https://github.com/os-autoinst/os-autoinst-distri-opensuse/runs/4080841465?check_suite_focus=true
```
Cloning into 'os-autoinst'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

**Comment by pevik** [comment]
PR for CI fix: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13582
(added also here to let CI pass, I'll rebase it after CI got fixed)

**Comment by czerw** [comment]
Could you please add verification run?

**Review by dzedro — APPROVED** [review]

**Comment by pevik** [comment]
Rebased and run some tests.

**Pull request merged**
