### PR TITLE
Increase MAX_JOB_TIME on arm

### PR DESCRIPTION
**Pull request by lpalovsky**
Due to slow workers on aarch64, HA migration tests usually take more 
than default 2H timeout. This PR increases this timeout to 3H by 
changing parameter MAX_JOB_TIME to '18000' on all offline migration 
tests.

- Related ticket: https://jira.suse.com/browse/TEAM-5200
- Verification run: https://mordor.suse.cz/tests/1852
-   https://mordor.suse.cz/tests/1850
- https://openqa.suse.de/tests/7772836#dependencies

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by lpalovsky** [comment]
Verification run on OSD was done by adding MAX_JOB_TIME=18000 variable to openqa-clone-job.

**Review by alvarocarvajald — APPROVED** [review]
This will change the MAX_JOB_TIME setting in all architectures, not only in ARM. To do the change only in ARM I guess the setting would need to be moved to YAML Job Group configuration.

I am however approving this as I do not see this harming the tests in the other architectures.

LGTM.

**Comment by lpalovsky** [comment]
> This will change the MAX_JOB_TIME setting in all architectures, not only in ARM. To do the change only in ARM I guess the setting would need to be moved to YAML Job Group configuration.
> 
> I am however approving this as I do not see this harming the tests in the other architectures.
> 
> LGTM.

Hmm.. you are right. Closing the PR, will move the settings to job group.  
Thanks for review!

**Pull request closed without merging**
