### PR TITLE
[WIP] Update ha autoyast profile to accept popup messages

### PR DESCRIPTION
**Pull request by chcao**
Update ha autoyast profile to accept popup messages by addding <report> to autoyast profile.

- Related ticket: https://progress.opensuse.org/issues/139034
- Needles: n/a
- Verification run: https://openqa.suse.de/tests/12815607#

### CODE REVIEW

**Comment by rfan1** [comment]
My question, your code changes are able to fix the random failure， correct?

**Comment by rakoenig** [comment]
If I understand your commit, then what it does is setting the timeout for all sort of popups to zero, thus practically preventing them from showing up. My big concern is that this way we're also disabling legit popups from showing up. 
My approach would have been to add a needle with the tag "autoyast-known-warning" for this popup, so it gets handled by `handle_warnings()` in the `installation` test module. Of course adding more needles to openQA doesn't make it better, but I fear the risk that we miss another important popup sooner or later.

**Comment by lemon-suse** [comment]
> If I understand your commit, then what it does is setting the timeout for all sort of popups to zero, thus practically preventing them from showing up. My big concern is that this way we're also disabling legit popups from showing up. My approach would have been to add a needle with the tag "autoyast-known-warning" for this popup, so it gets handled by `handle_warnings()` in the `installation` test module. Of course adding more needles to openQA doesn't make it better, but I fear the risk that we miss another important popup sooner or later.

Agree, we need deal with some warning popup and shouldn't disable them to popup.

**Comment by chcao** [comment]
Based on the comments above, I add a needle of autoyast-contacting-registration-server-20231127, the issue is resolved, VRs:
aarch64: https://openqa.suse.de/tests/12908111#
x86_64: http://openqa.suse.de/tests/12908119#

So I'll close this PR.

**Pull request closed without merging**
