### PR TITLE
Add reset_consoles because of multiple reboot in test

### PR DESCRIPTION
**Pull request by dzedro**
tested: http://10.100.98.90/tests/283

### CODE REVIEW

**Comment by okurz** [comment]
@dzedro PR 1000, congratulations! :100: * :100: :birthday: 

Change looks fine but I would prefer that you put the description why reset_consoles is called together with reboot in the source code, not (only) the commit message if you don't mind. Or maybe even better: Extract the "reset_consoles" call together with reboot into a helper method and put the comment as description there

**Comment by okurz** [comment]
can we make use of "wait_boot" from https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/utils.pm#L24 here? https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1002 adds a "reset_consoles" to "wait_boot" which seems to be the right approach

**Comment by dzedro** [comment]
haha thx :-)
wait_boot is not used here because it does just boot, selecting specific kernel is important here
maybe wait_boot could be extended to use parameters

**Comment by okurz** [comment]
yeah, well. nevermind :-)

**Pull request merged**
