### PR TITLE
JeOS: Leap15.4 & sle15sp4 confirm new config welcome screen

### PR DESCRIPTION
**Pull request by mloviska**
Follow up for
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14087

- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/761
- Verification runs:
  * [opensuse-15.4-JeOS-for-kvm-and-xen-x86_64-Build5.70-jeos-filesystem@64bit_virtio-2G](http://kepler.suse.cz/tests/10656#step/firstrun/1)
  * [opensuse-15.4-JeOS-for-kvm-and-xen-x86_64-Build5.70-jeos@64bit_virtio-2G](http://kepler.suse.cz/tests/10657#step/firstrun/1)

### CODE REVIEW

**Comment by Vogtinator** [comment]
If Leap has it, so does SLE, so you can adjust both.

**Comment by mloviska** [comment]
> If Leap has it, so does SLE, so you can adjust both.

Pushed, thanks!

**Review by jlausuch — APPROVED** [review]

**Review by Vogtinator — APPROVED** [review]
Code looks good, just the commit and PR subject is outdated now

**Comment by mloviska** [comment]
> Code looks good, just the commit and PR subject is outdated now

Updated

**Pull request merged**
