### PR TITLE
Do not test disk usage for SLE.

### PR DESCRIPTION
**Pull request by cwh42**
Related to my previous PR. Needed, since this was not fixed in SLE.

### CODE REVIEW

**Comment by okurz** [comment]
Is there a bug to fix this in SLE, too? I don't see why SLE and openSUSE should differ here but I certainly understand that this happens because libzypp is older than in Tumbleweed. I am sure we can fix this but silently ignoring this on SLE is probably not a good way.

what do others think about this?

**Comment by sysrich** [comment]
further to @okurz 's question, will this be fixed in SLE 12 SP2? If yes, this fix needs to be more nuanced.

**Comment by okurz** [comment]
@sysrich maybe you have a proposal how this could be solved? Or is this really the first feature new in tumbleweed and not (yet) in SLE?

**Comment by cwh42** [comment]
libzypp >= 15.21.0 fixes this.
I just asked Michael Andres. He told me this will make it into SP2. So we actually do not need this. 
However this test fails until the new libzyy gets merged.

**Pull request closed without merging**
