### PR TITLE
Longer GRUB timeout for sle-micro on VMware

### PR DESCRIPTION
**Pull request by tbaev**
- Related ticket: https://progress.opensuse.org/issues/174037
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/16185917

### CODE REVIEW

**Comment by nanzhg** [comment]
It is recommended to run more times to verify.

**Comment by alice-suse** [comment]
> It is recommended to run more times to verify.

Good point!

**Comment by tbaev** [comment]
Yes, I will run more VRs.

**Comment by tbaev** [comment]
https://openqa.suse.de/tests/16192366#step/esxi_open_vm_tools/59

This solution needs more workt, VMWare resolution is changing 

There is one older [poo#165923](https://progress.opensuse.org/issues/165923) ticket describing the same problem

I will do more tests and changes.

**Comment by tbaev** [comment]
@alice-suse @nanzhg 
From my finding setting GFXMODE and GFXPAYLOAD_LINUX to 1024x768x32 is causing instability. VMWare starts at 800x600 and it needs a few seconds to switch to 1024x768x32 and after a few seconds it resizes the output again and sometimes fails to do it ( exmple of GFXMODE=1024x768x32 [failure](https://openqa.suse.de/tests/16234866#step/esxi_open_vm_tools/106) ). 

The test is a lot more stable without  hard coded GFXMODE/GFXPAYLOAD_LINUX and increased GRUB_TIMEOUT. 
p.s. bsc#997263 is RESOLVED WONTFIX from 2016, I think with current version of VMWare this is more stable approach.

VR 6.0:
https://openqa.suse.de/tests/16236447
https://openqa.suse.de/tests/16236790
VR 6.1 
https://openqa.suse.de/tests/16238707
https://openqa.suse.de/tests/16238707
https://openqa.suse.de/tests/16239214
https://openqa.suse.de/tests/16239619

**Comment by alice-suse** [comment]
> @alice-suse @nanzhg From my finding setting GFXMODE and GFXPAYLOAD_LINUX to 1024x768x32 is causing instability. VMWare starts at 800x600 and it needs a few seconds to switch to 1024x768x32 and after a few seconds it resizes the output again and sometimes fails to do it ( exmple of GFXMODE=1024x768x32 [failure](https://openqa.suse.de/tests/16234866#step/esxi_open_vm_tools/106) ).
> 
> The test is a lot more stable without hard coded GFXMODE/GFXPAYLOAD_LINUX and increased GRUB_TIMEOUT. p.s. bsc#997263 is RESOLVED WONTFIX from 2016, I think with current version of VMWare this is more stable approach.
> 
> VR 6.0: https://openqa.suse.de/tests/16236447 https://openqa.suse.de/tests/16236790 VR 6.1 https://openqa.suse.de/tests/16238707 https://openqa.suse.de/tests/16238707 https://openqa.suse.de/tests/16239214 https://openqa.suse.de/tests/16239619

Thanks Teodor for the investigation and trying. Agree with picking more stable solution from my side :)

**Review by alice-suse — APPROVED** [review]

**Comment by nanzhg** [comment]
It's a good finding, you solved a major problem. :) Thank you, Teodor. 
LGTM.

**Pull request merged**
