### PR TITLE
Add autologin test for sle

### PR DESCRIPTION
**Pull request by jknphy**
Select Automatic Login in Local User screen and login without password through display manager.

- Related ticket: https://progress.opensuse.org/issues/44069
- Needles: [needles sle](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1158)
- Verification run:
  - [sle-15-SP1-autologin](http://rivera-workstation.suse.cz/tests/2811#step/first_boot/2)
  - [sle-12-SP5-autologin](http://rivera-workstation.suse.cz/tests/2810#step/first_boot/2)

Requires to create new test suite `autologin` with params below and assign to corresponding test suites in sle12 and sle15:
 ```
DESKTOP=gnome
YAML_SCHEDULE=schedule/autologin.yaml
NOAUTOLOGIN=0
```

### CODE REVIEW

**Comment by rwx788** [comment]
Please, set up the test suite and may I kindly ask you to update our test plan document: https://gitlab.suse.de/riafarov/qa-sle-functional-y/blob/master/SLES_Integration_Level_Testplan.md

**Comment by jknphy** [comment]
Thanks, I sent a [MR](https://gitlab.suse.de/riafarov/qa-sle-functional-y/merge_requests/4) to your repo due to I didn't see it fork it from some official one.

**Comment by rwx788** [comment]
> Thanks, I sent a [MR](https://gitlab.suse.de/riafarov/qa-sle-functional-y/merge_requests/4) to your repo due to I didn't see it fork it from some official one.

There is no official one, that's the reason I use private repo...

**Comment by ggardet** [comment]
This PR breaks Tumbleweed. See https://progress.opensuse.org/issues/52529

**Comment by jknphy** [comment]
> This PR breaks Tumbleweed. See https://progress.opensuse.org/issues/52529

Thanks, taking a look.

**Pull request merged**
