### PR TITLE
Update shutdown.pm

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Is there really no easier way to trigger a shutdown in GNOME? keyboard-shortcut? Would be poor usability...

**Comment by dzedro** [comment]
Unfortunately I didn't found default keyboard shortcut for shutdown/reboot dialog window, ctr-alt-delete will trigger only logout/switch off dialog window in sle 11, maybe easier way is to bind keyboard shortcut manualy and then use it.

**Comment by nilxam** [comment]
sounds it's time to separate shutdown test for different product ie. suffix with _sle11, IIRC the behavior of alt-f1 in GNOME3 is switching the overview and desktop, but I'm not GNOME user, so maybe I'm wrong...

**Comment by dzedro** [comment]
another option:
alt-f2
xdg-su -c '/sbin/shutdown -h now'

**Comment by dzedro** [comment]
What about variable for sle11 like NOSYSTEMD or SLE11, it would be usefull also in console/consoletest_finish.pm to avoid failing zypper tests in sle 11 because of running packagekit ?

e.g.

if (get_var("SLE11") {
    become_root;
    script_run("chmod 444 /usr/sbin/packagekitd");
    script_run("killall gpk-update-icon packagekitd");
    script_run "exit";
}
else {
    become_root;
    script_run "systemctl mask packagekit.service";
    script_run "systemctl stop packagekit.service";
    script_run "exit";
}

**Pull request closed without merging**
