### PR TITLE
use Ubuntu Trusty Tahr as base for test tests

### PR DESCRIPTION
**Pull request by aaannz**
- move Net::DBus installation up to avoid conflits with other packages

### CODE REVIEW

**Comment by sysrich** [comment]
LGTM

**Comment by coolo** [comment]
sudo required means we're no longer running in docker - which means we have a much lower chance of getting a travis spot ;(

**Comment by aaannz** [comment]
In none of our tests we are running in docker. I looked into it, we may change sudo apg-get by - apt section in travis.yml to install required packages. But I didn't try it yet.

**Comment by coolo** [comment]
but why not leave the sudo: required in then? You just confused me this way :)

**Comment by coolo** [comment]
anyway, https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/689 is my proposal

**Comment by aaannz** [comment]
Without Trusty (14.04) update, from what I saw Travis is based on Precise (12.04). It does not impact us very much I suppose, just want to point it out.
Drawback of this PR is that when Travis will upgrade their images we may start to some stuff.
But I'm happy either with this or #689

**Comment by coolo** [comment]
I merged 689 now - as I did very simliliar in os-autoinst

**Pull request closed without merging**
