### PR TITLE
Use --force-share to perform operations on vm image

### PR DESCRIPTION
**Pull request by waynechen55**
* **Image** operations may fail on running vm using qemu-img due to [can not obtain "write" lock](https://openqa.suse.de/tests/6279407#step/uefi_guest_installation/393)
* **Use** option --force-share with qemu-img can help solve the problem.
* **Verification run:**
  * [kvm verification run](https://openqa.suse.de/tests/6285569#step/uefi_guest_installation/401)
  * [xen verification run](https://openqa.suse.de/tests/6285562#step/uefi_guest_installation/523)

### CODE REVIEW

**Comment by waynechen55** [comment]
@alice-suse @Julie-CAO @guoxuguang @nanzhg

**Comment by nanzhg** [comment]
Seems the error was not happened on xen VR. I'm curious what process was using the image during kvm VR. In addition, looks like "qemu convert" was executed twice in kvm VR. If it's not necessary, just keep one command with "--force-share" option that is enough.

**Comment by waynechen55** [comment]
> Seems the error was not happened on xen VR. I'm curious what process was using the image during kvm VR. In addition, looks like "qemu convert" was executed twice in kvm VR. If it's not necessary, just keep one command with "--force-share" option that is enough.

This design takes all circumstances into consideration and covers all situations. "--force-share" is a new option, it does not exist for some SLESs, for example, 11-SP4.

**Comment by Julie-CAO** [comment]
How many times has the "fail to get shared 'write' lock" failure occurred in UEFI tests? Have you ever tried to find out why? I don't seem to have encountered this error before.

**Comment by waynechen55** [comment]
> How many times has the "fail to get shared 'write' lock" failure occurred in UEFI tests? Have you ever tried to find out why? I don't seem to have encountered this error before.

The only running process that is related to vm is the vm itself, so the vm may also perform "write" at that moment.

**Comment by Julie-CAO** [comment]
> > How many times has the "fail to get shared 'write' lock" failure occurred in UEFI tests? Have you ever tried to find out why? I don't seem to have encountered this error before.
> 
> The only running process that is related to vm is the vm itself, so the vm may also perform "write" at that moment.

Oh, I see, the vm is left as running state for consequent tests. It's ok to compress and upload the vm disk even the vm is running and may be 'writing'. LGTM.

**Comment by nanzhg** [comment]
> > Seems the error was not happened on xen VR. I'm curious what process was using the image during kvm VR. In addition, looks like "qemu convert" was executed twice in kvm VR. If it's not necessary, just keep one command with "--force-share" option that is enough.
> 
> This design takes all circumstances into consideration and covers all situations, and still concise. "--force-share" is a new option, it does not exist for some SLESs, for example, 11-SP4.

OK. LGTM

**Comment by guoxuguang** [comment]
LGTM

**Comment by alice-suse** [comment]
Can you give a more complete description about when this function is called for uefi GI?

>Image operations may fail on running vm using qemu-img due to can not obtain "write" lock
If for uefi, this function is called for successful installed guests and you want to upload its assets for potential reuse by other testsuites later, IMHO, it is reasonable behavior to raise the error to protect the disk writing operations of the " running" vm. You should only do disk related operations by qemu-img AFTER stopping the vm.

>Use option --force-share with qemu-img can help solve the problem.
This may lead to potential disk incomplete/etc issues if the running vm will continue further tests.

**Comment by waynechen55** [comment]
> Can you give a more complete description about when this function is called for uefi GI?
> 
> > Image operations may fail on running vm using qemu-img due to can not obtain "write" lock
> 
> If for uefi, this function is called for successful installed guests and you want to upload its assets for potential reuse by other testsuites later, IMHO, it is reasonable behavior to raise the error to protect the disk writing operations of the " running" vm. You should only do disk related operations by qemu-img AFTER stopping the vm.
> 
> > Use option --force-share with qemu-img can help solve the problem.
> 
> This may lead to potential disk incomplete/etc issues if the running vm will continue further tests.

There is no failure with the following vm feature tests if you refer to the verification runs. The disk is just being occupied by the vm. The option --force-share is just introduced to help solve the problem.

**Comment by alice-suse** [comment]
Glad to know that compression is read-only, then it is safer. But still, I'd recommend it as best practice to manipulate disk images when they are silent -- no running vm, no direct write or cache write , to avoid potential disk corruption for whatever reasons(eg tool bugs) and shorter/more stable disk convert/compress time.

Of course, just my suggestion. Up to you to decide and the consequeces.

**Comment by waynechen55** [comment]
> Glad to know that compression is read-only, then it is safer. But still, I'd recommend it as best practice to manipulate disk images when they are silent -- no running vm, no direct write or cache write , to avoid potential disk corruption for whatever reasons(eg tool bugs) and shorter/more stable disk convert/compress time.
> 
> Of course, just my suggestion. Up to you to decide and the consequeces.

This usage should be OK according to qemu-img manpage description. Actually "--force-share" is global option, it can also use with "qemu-img info" to just list disk info if fail to get "write" lock (I encountered such situation in which "qemu-img info" is not possible due to the same error. I do not think "guest in shutoff" is a prerequisite for "query info". So this option is useful.) as long as it is read-only operation. I will keep following up this change in the future. And additionally this has no negative effect on all other existing tests, so safe for merge if no other concerns from my POV.

**Pull request merged**
