### PR TITLE
microos: update update-test-trivial rpm's to be signed with the 4k openSUSE key

### PR DESCRIPTION
**Pull request by DimStar77**
- Related ticket: https://build.opensuse.org/request/show/1079731
- Needles: N/A
- Verification runs:
  - [Staging:H](https://openqa.opensuse.org/tests/3235678)
  - [TW0426](https://openqa.opensuse.org/tests/3248672#details)

### CODE REVIEW

**Comment by Vogtinator** [comment]
What about the other archs?

**Comment by DimStar77** [comment]
> What about the other archs?

Got them on my todo to verify / extract the binaries

**Comment by Vogtinator** [comment]
IIRC it's necessary for the packages in the repo to be newer than the packages here, so make sure to trigger a rebuild after creating the tarballs.

You should make a VR for a job outside of staging for verifying the upgrade code.

**Comment by DimStar77** [comment]
> IIRC it's necessary for the packages in the repo to be newer than the packages here, so make sure to trigger a rebuild after creating the tarballs.
> 
> You should make a VR for a job outside of staging for verifying the upgrade code.

https://openqa.opensuse.org/tests/3246182 - so yes, you remembered right. Glad you did!

I triggered a rebuild of this  in openSUSE:Factory/standard - can retest it with snapshot 0426

If this works out, I'll add the binaries from TW/aarch64 and ppc64le to the tarball (and trigger rebuilds)

**Comment by DimStar77** [comment]
[TW0426](https://openqa.opensuse.org/tests/3248672#details) VR passed after the rebuild trigger in the product.

* PR has been updated to also contain aarch64 and ppc64le utt binaries signed with the 4k key.
* Packages in :ARM and :PowerPC are rebuilt to have a higher release version than what is in the tarball

**Review by Vogtinator — APPROVED** [review]

**Comment by michaelgrifalconi** [comment]
Hello, this PR might have broken this Leap test: https://openqa.opensuse.org/tests/3249614#step/transactional_update/21
https://progress.opensuse.org/issues/129286

**Pull request merged**
