### PR TITLE
Fix "yast2 apparmor" performance issue

### PR DESCRIPTION
**Pull request by lilyeyes**
Fix "yast2 apparmor" performance issue:
There are some performance issues on all architectures, such as "yast2 apparmor" loading is very slow.
 "yast2" UI loads the "chose a program to generate a profile for" window is very slowly also.
Then increasing the time out value instead of default value (30). 

- Related ticket: 
  poo#81811 - [sle][security][sle15sp3] test fails in manually_add_profile about type_string missing and Needles mismatch
  poo#88145 - [sle][security][sle15sp3] test fails in settings_disable_enable_apparmor (needle mismach due to new desktop background?)
- Needles: invalid needle "manually_add_profile-AppArmor-Chose-a-program-to-generate-a-profile-20201124.json" was deleted via openQA.
- Verification run: passed on build 130.3
  https://openqa.suse.de/tests/5335877#step/manually_add_profile/28
  https://openqa.suse.de/tests/5341465#details
  https://openqa.suse.de/tests/5341356

### CODE REVIEW

**Comment by rfan1** [comment]
"yast2" UI loads an "chose a program to generate a profile for" window is very slowly also.
@lilyeyes maybe you need remove "an" here?

Others LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM.Thanks.

**Comment by lilyeyes** [comment]
> "yast2" UI loads an "chose a program to generate a profile for" window is very slowly also.
> @lilyeyes maybe you need remove "an" here?
> 
> Others LGTM

Aha, you are right.

**Comment by lemon-suse** [comment]
For such timing issue, please support proof in your tickets or PR description why need enlarge the timeout value to the value you set.

**Review by lemon-suse — APPROVED** [review]

**Comment by lemon-suse** [comment]
LGTM.

**Pull request merged**
