### PR TITLE
s390x: Add support for s390@suse-kvm

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
@okurz @coolo

**Comment by Soulofdestiny** [comment]
verification:
zKVM: http://opeth.suse.de/tests/5540
SUSE-KVM: http://opeth.suse.de/tests/5539

**Comment by okurz** [comment]
LGTM, please merge yourself when you ensured all necessary settings are on osd. I only found `NETDEV` on s390-kvm but not on zkvm so I'm not sure if you missed it there.

**Comment by Soulofdestiny** [comment]
sure, thanks

**Comment by Soulofdestiny** [comment]
Added NETDEV to corresponding zkvm machines

**Pull request merged**
