### PR TITLE
Combine all SCC+allmodules in one test_suite

### PR DESCRIPTION
**Pull request by DrMullings**
Set all architecture specific variables for SCC+allmodules in main.pm
instead of different test_suites
Delete SCC+allmodules_aarch64 and add aarch64 for SCC+allmodules

### CODE REVIEW

**Comment by DrMullings** [comment]
https://progress.opensuse.org/issues/23752

**Comment by okurz** [comment]
Verification run?

What you put into the description of the pull request or as an additional comment could also be in the commit message details.

I can recommend the tool "hub" (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

**Comment by DrMullings** [comment]
Verification run:
10.160.65.204/tests/50510.160.65.204
Commit message and PR Description are the same.

**Comment by okurz** [comment]
hm, you verified only that a job works when SCC_ADDONS are still explicitly specified. Also, next time please put progress ticket into the PR description. What I was thinking of is a simple workflow where with one single command you create a PR with all necessary information from the command line. I can show you sometime.

**Pull request merged**
