### PR TITLE
Fix adding /boot/zipl partition on s390x

### PR DESCRIPTION
**Pull request by rwx788**
Previously it worked with /boot due to suggested mounts, so correct
mount point was used in the end. It doesn't happen with storage-ng.

- Related ticket: [poo#28507](https://progress.opensuse.org/issues/28507).
- [Needles](https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/679)
- Verification runs: 
[separate boot](http://g226.suse.de/tests/635)
[no separate boot](http://g226.suse.de/tests/637)

### CODE REVIEW

**Comment by rwx788** [comment]
@Soulofdestiny, please, take a look.

**Comment by Soulofdestiny** [comment]
uhm in general, looks good - but your verification runs are actually not verifying that it can really boot :)

**Comment by rwx788** [comment]
I know, because it fails before. One of the runs is old behavior, so if it doesn't boot it's a bug. With separate boot, it should work also, as partitioning is according to the specs. ATM it's wrong partitioning.

**Comment by Soulofdestiny** [comment]
then let's conduct this experiment? or would it be another case of "merging too early"? ;)

**Comment by okurz** [comment]
> then let's conduct this experiment? or would it be another case of "merging too early"? ;)

no, because it's limited to s390x and only the special partitioning module :)

**Pull request merged**
