### PR TITLE
Refactor device existence check and add it for drbd and cluster_md

### PR DESCRIPTION
**Pull request by alvarocarvajald**
Sometimes in high performance virtual scenarios, it takes some seconds for the cluster_md device to be present in `/dev` while running the `test/ha/cluster_md` test module.

This PR adds the method `check_device_available` to `lib/hacluster` to use instead of the call to `assert_script_run("ls -la $clustermd_device")` in the `test/ha/cluster_md` module; this method will check for some configurable number of tries for the existence of the device before failing.

Also part of the PR is the inclusion of a call to the method in the `ha/drbd_passive` module to check for the `/dev/drbd_passive` device.

- Related ticket: N/A
- Needles: N/A
- Verification run: N/A
- Failed test: https://openqa.suse.de/tests/2495081#step/cluster_md/55
- Successful test: https://openqa.suse.de/tests/2495162 (same build, same test code)

### CODE REVIEW

**Comment by alvarocarvajald** [comment]
@ldevulder if you think we need more than 10 seconds, let me know to fix.

**Comment by alvarocarvajald** [comment]
> Looks good!
> 
> But as this may also happen for DRBD devices (for example), maybe adding it as a function in`lib/hacluster.pm` could be good, WDYT?
> 
> (Currently DRBD device presence is not checked - my bad! - maybe could it be also but in the future, not in this PR :-))

Good idea. Will check the drbd module and fix accordingly.

**Comment by ldevulder** [comment]
> @ldevulder if you think we need more than 10 seconds, let me know to fix.

As test can exit sooner if device is here, yes maybe you can increase the value to 20 or 30s to be sure, or wait for next run to test :-)

**Comment by juadk** [comment]
LGTM

**Comment by ldevulder** [comment]
https://openqa.suse.de/tests/2498986#step/cluster_md/40 is failing, function `check_device_available` is in fact not exported.

Sorry for not seeing this during the review :-(

**Pull request merged**
