### PR TITLE
Reduce yaml files for msdos

### PR DESCRIPTION
**Pull request by hjluo**
##
### Reduce yaml files for msdos

- Related ticket:
    - https://progress.opensuse.org/issues/163262
- Related MR:
    -  https://gitlab.suse.de/qe-yam/openqa-job-groups/-/merge_requests/291
- Needles: 
   - N/A
- Verification run: 
   -  [**reduce_msdos_15sp6**](https://openqa.suse.de/tests/overview?distri=sle&build=hjluo%2Fos-autoinst-distri-opensuse%23reduce_msdos&version=15-SP6)
   - [**yast_dev**](https://openqa.suse.de/tests/15018974)

##

### CODE REVIEW

**Comment by chcao** [comment]
LGTM, leave a comment to the related MR.

**Comment by lemon-suse** [comment]
In general, LGTM. I found there is a msdos case in development group, should be considered in this PR also. 

SLE_15_DEV/x86_64.yaml:59:          YAML_SCHEDULE: schedule/yast/msdos/msdos@svirt-hyperv.yaml

**Comment by hjluo** [comment]
> In general, LGTM. I found there is a msdos case in development group, should be considered in this PR also.
> 
> SLE_15_DEV/x86_64.yaml:59: YAML_SCHEDULE: schedule/yast/msdos/[msdos@svirt-hyperv.yaml](mailto:msdos@svirt-hyperv.yaml)

Yes, I've checked it and found it in dev and no resource by now to test it. so need I add a default for it like `schedule/yast/sle/flows/default_svirt-xen-pv.yaml` for default?

**Comment by lemon-suse** [comment]
> > In general, LGTM. I found there is a msdos case in development group, should be considered in this PR also.
> > SLE_15_DEV/x86_64.yaml:59: YAML_SCHEDULE: schedule/yast/msdos/[msdos@svirt-hyperv.yaml](mailto:msdos@svirt-hyperv.yaml)
> 
> Yes, I've checked it and found it in dev and no resource by now to test it. so need I add a default for it like `schedule/yast/sle/flows/default_svirt-xen-pv.yaml` for default?

What do you mean no resource, this is a job on svirt-hyperv : https://openqa.suse.de/tests/14610863#step/zypper_lifecycle/1

**Comment by hjluo** [comment]
@lemon-suse  I've added svirt-hyperv for development , and created a new default for svirt-hyperv . please take a look.

**Review by lemon-suse — APPROVED** [review]

**Pull request merged**
