### PR TITLE
Fix for jobs where alt-s triggers screen change

### PR DESCRIPTION
**Pull request by kravciak**
Local runs:
http://dhcp91.suse.cz/tests/6536#step/install_and_reboot/2
http://dhcp91.suse.cz/tests/6535#step/install_and_reboot/2

### CODE REVIEW

**Comment by okurz** [comment]
@StefanBruens

**Comment by okurz** [comment]
I'm sorry but I am not sure about this change without at least one verification run. #2929 improved stability a lot and I don't want to loose that. I am not feeling secure enough about this change, if it will introduce other problems, perl warnings in autoinst-log.txt or if it even compiles. Please also add a comment describing why the unusual `wait_screen_change undef`

**Comment by kravciak** [comment]
Verification run scheduled. Unusual "wait_screen_change undef" because I am expecting screen change without action from user side (countdown in this case)

**Comment by StefanBruens** [comment]
Maybe use an empty sub {} instead of the undef, makes the intention ("do nothing") more clear.

From a functional point of view, this makes the screen change trigger caused by the button release less likely, but still possible - even though the key has been released, the rendering may lag somewhat.

I think this is a slight improvement to the current scheme.

**Comment by kravciak** [comment]
Comment added

**Pull request merged**
