### PR TITLE
Modify check_kernel_config test cases to run on Tumbleweed

### PR DESCRIPTION
**Pull request by ShawnHa0**
According to Factory First, all test cases should run on Tumbleweed. So, we need to modify the test cases to make sure these cases can run and pass on Tumbleweed. Cases modified are under security_check_kernel_config, added version specification checking to fit Tumbleweed and SLE since there are some differentials in files and configurations between Tumbleweed and SLE.

- Related ticket: 
  https://progress.opensuse.org/issues/99102
  https://progress.opensuse.org/issues/99093
- Needles: N/A
- Verification run: 
  https://openqa.opensuse.org/tests/1942564
  https://openqa.suse.de/tests/7252012
  https://openqa.suse.de/tests/7252014

### CODE REVIEW

**Comment by rfan1** [comment]
Remove this line:
[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

**Comment by rfan1** [comment]
If possible, can you please also run the same tests on s390x and Power?

**Comment by ShawnHa0** [comment]
> If possible, can you please also run the same tests on s390x and Power?

It seems that there are no available job to run this case on s390x and Power. If we need to run on these two platforms, maybe it is mandatory to rerun the case on s390x and generate the qcow (referring to Xiaojing yesterday)

**Comment by rfan1** [comment]
> > If possible, can you please also run the same tests on s390x and Power?
> 
> It seems that there are no available job to run this case on s390x and Power. If we need to run on these two platforms, maybe it is mandatory to rerun the case on s390x and generate the qcow (referring to Xiaojing yesterday)

No need to run on O3, just run the tests on OSD should be fine :)

**Comment by ShawnHa0** [comment]
> > > If possible, can you please also run the same tests on s390x and Power?
> > 
> > 
> > It seems that there are no available job to run this case on s390x and Power. If we need to run on these two platforms, maybe it is mandatory to rerun the case on s390x and generate the qcow (referring to Xiaojing yesterday)
> 
> No need to run on O3, just run the tests on OSD should be fine :)

OK, I will consult Xiaojing about how to run these cases on s390x and Power.

**Comment by ShawnHa0** [comment]
Will close this one and open a new pull request with code change we discussed today.

**Pull request closed without merging**
