### PR TITLE
Added mysql/mariadb ODBC test poo#13170

### PR DESCRIPTION
**Pull request by emiura**
Added test script for mysql/mariadb ODBC test

### CODE REVIEW

**Comment by okurz** [comment]
How is the test related to e.g. tests/console/php5_mysql.pm?

The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. Please write subject line in present tense.

**Comment by emiura** [comment]
Sorry. this was my first commit attempt. I have already fixed the script headers, I just used php5-mysql as test template. Also, fixed the tab formatting as well.
I will try again with a better commit

**Comment by okurz** [comment]
Please rebase/squash commits. There should be no merge commits in your PR

**Comment by okurz** [comment]
no need to close the commit. Rebase and squash to make sure you have one commit on top of origin/master (if "origin" points to this repo here), e.g. look at `git log origin/master..` before pushing.

**Pull request closed without merging**
