### PR TITLE
Adaption for mitigations on xen hypervisor

### PR DESCRIPTION
**Pull request by museQi**
Adaption for mitigations on xen hypervisor change SLE15SP6

- Related ticket: https://progress.opensuse.org/issues/164201
- Verification run: skylake,cascadelake,icelake machines all have been tested.
-http://10.67.129.4/tests/72931 cascadelake machine
http://10.67.129.4/tests/72921  skylake
http://10.67.129.4/tests/72999  icelake

### CODE REVIEW

**Comment by museQi** [comment]
@XGWang0 @JoyceNa @zyuhu Please help me review.

**Comment by XGWang0** [comment]
LGTM

**Comment by zyuhu** [comment]
LGTM

**Comment by museQi** [comment]
@alice-suse Please help me merge.

**Pull request merged**
