### PR TITLE
Add 'copy-paste' detection as test

### PR DESCRIPTION
**Pull request by okurz**
Reducing the huge current duplication which is keeping the threshold up is
another issue. If we can not solve these we can also whitelist the current
failures and reduce the threshold.

### CODE REVIEW

**Comment by coolo** [comment]
No. We want tests not code that pleases rules you stick to personally. And I won't put the decision if the test is good enough - or too similiar to another one in the hands of a tool.

**Comment by coolo** [comment]
Especially tools as stupid as this one:

```
1 duplicate(s) found with a length of 5 (>= 5 lines) and 24 bytes reduced to complete lines:
1.  File: ./distribution.pm in lines 150..154 (bytes 4398..4421)
2.  File: ./basetest.pm in lines 591..595 (bytes 15273..15296)
1. =================
    }
    return;
}

1;
```

**Comment by sysrich** [comment]
Also, @okurz has 5 other open pull requests in various stages of incomplete or unmergable - I respectfully request that those PR's are resolved before I'm comfortable considering yet more PR's from Oli

**Comment by okurz** [comment]
> Especially tools as stupid as this one…

that's why I ignore that special part in the options. I don't see a problem with that.

> No. We want tests not code that pleases rules you stick to personally.

It's not just me. You are looking for copy-paste and to save us time I am trying to make the check automatic.

> And I won't put the decision if the test is good enough - or too similiar to another one in the hands of a tool.

The test is only giving a hint. You as a reviewer have the final say. You can merge regardless or update the threshold. I don't see a problem with that.

**Comment by okurz** [comment]
the commit "fencing_consoletest_setup: Get rid of biggest DRY sin" is an alternative to the symlinks in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1926
whatever you prefer

**Comment by okurz** [comment]
added a commit that shows how I used the CP detection to reduce duplication

**Comment by coolo** [comment]
I'm fine with the evolution one - but still not with the DRY one. Especially taken that we don't even have that module in Factory

**Comment by okurz** [comment]
see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2045 for DRY enhancement

**Pull request closed without merging**
