### PR TITLE
Upload relevant logs for feature test failure

### PR DESCRIPTION
**Pull request by waynechen55**
Upload relevant logs for feature test failure:
virt_utils::upload_supportconfig_log
virt_utils::upload_virt_logs

- Related ticket: Virtualization feature test
- Needles: https:
- Verification run:  [Here is verification run 1](http://10.67.133.40/tests/152)
                             [Here is verification run 2](http://10.67.133.40/tests/153)

### CODE REVIEW

**Comment by waynechen55** [comment]
Please have a look @alice-suse @guoxuguang @Julie-CAO

**Comment by waynechen55** [comment]
LGTM @alice-suse @guoxuguang @Julie-CAO

**Comment by waynechen55** [comment]
Please help merge if no other concerns.

**Comment by guoxuguang** [comment]
Awesome, LGTM.

**Pull request merged**
