### PR TITLE
Check case-sensitive "zypper search --provides"

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Related ticket: https://jira.suse.com/browse/SLE-16271
- Package to reproduce:
  - For openSUSE Tumbleweed: https://build.opensuse.org/package/show/devel:openSUSE:QA:Tumbleweed/MariaDB-server-JIRA-SLE-16271
  - For SLE15-SP3: https://build.suse.de/package/show/QA:Head/MariaDB-server-JIRA-SLE-16271
- Verification run:
  - Tumbleweed x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2840#step/zypper_extend/199
  - SLE15-SP3 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2841#step/zypper_extend/199
  - SLE15-SP3 aarch64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2845
  - SLE15-SP2 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2842
  - Leap 15.2 x86_64: http://openqa.slindomansilla-vm.qa.suse.de/tests/2843#

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
I forgot to submit the package to QA:Head

**Comment by foursixnine** [comment]
> I forgot to submit the package to QA:Head

Please link the package somewhere, so that it's explicitly referenced somewhere

**Comment by SergioAtSUSE** [comment]
This should be part of `zypper_se` module, which doesn't exist.

`zypper_se` should later be extended to cover expectations mentioned in [PRD](https://confluence.suse.com/display/SUSELinuxEnterpriseServer15SP3/[SLE+15+SP3]+PRD+all-in-one#id-[SLE15SP3]PRDall-in-one-Easeofuse%E2%80%93hassle-freeuseofmodules&extensions).

**Comment by foursixnine** [comment]
> `zypper_se`

Check the `zypper_extend` test  before going into the direction of creating a new module

**Review by foursixnine — APPROVED** [review]

**Comment by DimStar77** [comment]
Breaks on Tumbleweed/JeOS:

https://openqa.opensuse.org/tests/1416019#step/zypper_extend/192

Seems QA_HEAD_REPO variable has not been defined

**Comment by SergioAtSUSE** [comment]
looking

**Comment by SergioAtSUSE** [comment]
Preparing PR to not run that section on JeOS.

**Pull request merged**
