### PR TITLE
Replace reboot_gnome with more generic, svirt compatible, solution

### PR DESCRIPTION
**Pull request by mnowaksuse**
Xen restarts VM by shutting it down and starting it. In the process VNC & serial console connections get closed. For this to behave reliably, we can't just issue `script_run 'restart'`, we have to observe the process and touch it where necessary.

This set of PRs replace reboot_gnome.pm with more generic, svirt compatible, solution, which ought to work in both textmode and GUI environments.

Validation runs:
* http://assam.suse.cz/tests/6281
* http://assam.suse.cz/tests/6279
* http://assam.suse.cz/tests/6275
* http://assam.suse.cz/tests/6274
* http://assam.suse.cz/tests/6273
* http://assam.suse.cz/tests/6272
* http://assam.suse.cz/tests/6265
* http://assam.suse.cz/tests/6269
* http://assam.suse.cz/tests/6268
* http://assam.suse.cz/tests/6267
* http://assam.suse.cz/tests/6266
* http://assam.suse.cz/tests/6271
* http://assam.suse.cz/tests/6262

### CODE REVIEW

**Comment by sysrich** [comment]
I hate to nitpick, but this PR is WAY more than just "Svirt xen reboot gnome3"

For the sake of my sanity and future review if/when this changes behaviour across the board, can you amend the subject and description to something more accurate

Such as "Replace reboot_gnome with more generic (& svirt compatible) solution", with a line or two in the description as to why we need it?

**Comment by okurz** [comment]
Let's try again then :-) I will retrigger SLE tests now which failed trying to reconnect to VNC after reboot and you can take a look later today for obvious failures

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/420077#step/reboot_gnome/1 (and much more GNOME tests in snapshot 0612 showing the same issue)

**Comment by mnowaksuse** [comment]
Filed bug https://bugzilla.suse.com/show_bug.cgi?id=1044072 and PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3075 should workaround it.

**Pull request merged**
