### PR TITLE
Fix the test failure in zypper_releasever.pm

### PR DESCRIPTION
**Pull request by QingmingSu**
Replace some script_run with type_string since we want to check
the command output by wait_serial later. With script_run, the
output will be used to check whether the command is finished,
then later wait_serial will get nothing and raise test failure.

### CODE REVIEW

**Comment by coolo** [comment]
it's actually more appropriate to add a ,0 to the script_run to mark scripts run - the ,0 is documented to be used if you wait yourself

**Comment by QingmingSu** [comment]
Thanks for the suggestion. I have updated the commit to take script_run back with timeout set to 0. The test run showed that it worked well either.

**Comment by QingmingSu** [comment]
Hi coolo, 

Would you please help check the updated commit?

Thanks

**Comment by coolo** [comment]
yes. but due to Alpha3 in testing we do not merge PRs that aren't critical to Alpha3. Please understand

**Comment by QingmingSu** [comment]
Yeah, got it.

**Pull request merged**
