### PR TITLE
Fix version isn't numeric issue in ibmtss

### PR DESCRIPTION
**Pull request by rfan1**
- Related ticket: https://progress.opensuse.org/issues/104208
- Needles:n/a
- Verification run: http://openqa.suse.de/tests/7893462

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
lgtm.

**Review by Amrysliu — APPROVED** [review]
lgtm

**Comment by jouyingbin** [comment]
@rfan1 would you please add the module name in the subject and git commit message too?

**Comment by rfan1** [comment]
> @rfan1 would you please add the module name in the subject and git commit message too? Such as **Fix version isn't numeric issue in ibmtss** how do you think ?

Done

**Review by jouyingbin — APPROVED** [review]
lgtm

**Pull request merged**
