### PR TITLE
Make disk unselecting work for multiple disks

### PR DESCRIPTION
**Pull request by baierjan**
The test worked only in text mode or in 2 disks scenario. Test was slightly rewritten to work in graphical installation with 4 disks as well.

- Related ticket: https://progress.opensuse.org/issues/40631
- Verification run: http://panigale.suse.cz/tests/70#step/partitioning_firstdisk/5

### CODE REVIEW

**Comment by okurz** [comment]
@xlai I guess this could be very important for virtualization tests as I understood you rely on IPMI tests with differing disk configuration

**Comment by rwx788** [comment]
Do we need new needles for it or you've already created them?

**Comment by baierjan** [comment]
@rwx788: Current needles work, new ones are required only for systems with different disk configuration (like the mine in the verification).

**Comment by rwx788** [comment]
Great! Could you please run some jobs from virtualization job group, to play it safe: https://openqa.suse.de/tests/2163341#step/partitioning_firstdisk/1 and potentially create missing needles for them if any. I'm surprised that this PR got somehow lost, do not hesitate to ping people for the review, it's frustrating when nothing happens for a month.

**Comment by baierjan** [comment]
Will any on the following do it? It is from another (merged PR), but the code should be the same. My changes are not related to text installation, only to the graphical one and as it is an IPMI worker it is hard to test in different setup.

* http://panigale.suse.cz/tests/151
* http://panigale.suse.cz/tests/154
* http://panigale.suse.cz/tests/165

**Comment by baierjan** [comment]
I believe my PR does the same logic for the graphical installation (if we are talking about the code which creates hotkeys to press according to the matched needle).

**Comment by okurz** [comment]
If you trust your code I will trust you then :)

**Pull request merged**
