### PR TITLE
Check that xterm started before typing

### PR DESCRIPTION
**Pull request by kravciak**
Fix for: https://openqa.suse.de/tests/747424#step/sshxterm/8

### CODE REVIEW

**Comment by dzedro** [comment]
It will help, but it can still fail, I have been working on this, but had to revert my [PR](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2357/files) to fix and test it on openSUSE
I plan to finish it this week :-)

**Comment by okurz** [comment]
shouldn't that check be part of `x11_start_program`? There is the `valid => 1` option, maybe that helps.

**Comment by dzedro** [comment]
`valid` option is checking valid execution of command not if executed command e.g. xterm is ready for typing https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/susedistribution.pm#L117

**Comment by okurz** [comment]
Should we wait or merge?

**Comment by dzedro** [comment]
I don't mind, I will update/remove it in my PR

**Comment by kravciak** [comment]
I would keep it - at least as a reminder until you finish you PR. Test is still failing and many other test modules check xterm this way.

**Pull request merged**
