### PR TITLE
Add 'valgrind' test for sles12sp5 and all sle15 releases

### PR DESCRIPTION
**Pull request by rfan1**
https://progress.opensuse.org/issues/119278

- Related ticket: https://progress.opensuse.org/issues/119278
- Verification run: [VRs](https://openqa.suse.de/tests/overview?result=passed&result=softfailed&arch=&flavor=&machine=&test=&modules=&module_re=&distri=sle&build=rfan20221206#)

### CODE REVIEW

**Review by michaelgrifalconi — APPROVED** [review]

**Comment by rfan1** [comment]
@michaelgrifalconi could you please help merge?

**Comment by rfan1** [comment]
> > Please see comment
> > Thanks, let me do and run VRs

Seems the package is available from sle12sp5, 
https://openqa.suse.de/tests/overview?distri=sle&build=rfan20221206
Let me revise my code then

**Comment by rfan1** [comment]
@michaelgrifalconi well， VRs done!

**Review by michaelgrifalconi — APPROVED** [review]

**Comment by rfan1** [comment]
@foursixnine 
Could you please help review and merge?

**Pull request merged**
