### PR TITLE
Integate Atsec test 'Syscall thrasher' into openQA

### PR DESCRIPTION
**Pull request by Amrysliu**
Related: https://progress.opensuse.org/issues/109774

Verification run: https://openqa.suse.de/tests/8538345# (aarch64)
                          https://openqa.suse.de/tests/8538186# (x86_64)
                          https://openqa.suse.de/tests/8538470# (s390x)

### CODE REVIEW

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by lilyeyes** [comment]
BTW, the "assert_script_run('ls');" generally look good.

**Review by tinawang123 — APPROVED** [review]
LGTM

**Review by jouyingbin — APPROVED** [review]
LGTM

**Pull request merged**
