### PR TITLE
[HPC] Add xml results to the mpi module

### PR DESCRIPTION
**Pull request by b10n1k**
Generate XML file with test results.

- Related ticket: https://progress.opensuse.org/issues/119722
- Verification run: https://openqa.suse.de/tests/overview?build=b10n1k%2Fos-autoinst-distri-opensuse%2318082&distri=sle&version=15-SP6

### CODE REVIEW

**Review by schlad — CHANGES_REQUESTED** [review]
-2
let us simplify first mpi tests before we start adding some more logic. I will take care of my PR in this regards today.

**Comment by schlad** [comment]
side note and I really wish you answer: 
test_case('Test IMB', 'Basic performmance test', $rt);
What's the conditions under which this performance test fails?

**Comment by b10n1k** [comment]
> side note and I really wish you answer: test_case('Test IMB', 'Basic performmance test', $rt); What's the conditions under which this performance test fails?

PingPong benchmark measures the bandwidth of nodes communication. But we do not compare the results. I am saying this because the test wont fail due to its performance.
The most likely, it will fail when the nodes do not sending or receive messages among them.
does that answer your question?

**Comment by schlad** [comment]
> > side note and I really wish you answer: test_case('Test IMB', 'Basic performmance test', $rt); What's the conditions under which this performance test fails?
> 
> PingPong benchmark measures the bandwidth of nodes communication. But we do not compare the results. I am saying this because the test wont fail due to its performance. The most likely, it will fail when the nodes do not sending or receive messages among them. does that answer your question?

yeah it does answer my question. Thx! I will follow up with you as agreed.

**Pull request closed without merging**
