### PR TITLE
Containers: Use python3 dockerfile for openSUSE

### PR DESCRIPTION
**Pull request by jlausuch**
- Related ticket: https://progress.opensuse.org/issues/97430

- [on Leap 15.2](https://openqa.suse.de/tests/7068629)
- [on Leap 15.3](https://openqa.suse.de/tests/7068630)
- [on CentOS](https://openqa.suse.de/tests/7068632)
- [on SLE](https://openqa.suse.de/tests/7068631)

### CODE REVIEW

**Review by asmorodskyi — APPROVED** [review]
LGTM

**Review by b10n1k — APPROVED** [review]
+1

**Comment by Vogtinator** [comment]
This breaks tests where `REGISTRY` is not set, it tries to `FROM /python:3`:

https://openqa.opensuse.org/tests/1913262#step/docker_image/111

**Comment by jlausuch** [comment]
> This breaks tests where `REGISTRY` is not set, it tries to `FROM /python:3`:
> 
> https://openqa.opensuse.org/tests/1913262#step/docker_image/111

The problem is outside of this PR. There is a bug [here](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/containers/container_images.pm#L65). We are replacing a string in a file that doesn't exist.... On it

**Comment by jlausuch** [comment]
> This breaks tests where `REGISTRY` is not set, it tries to `FROM /python:3`:
> 
> https://openqa.opensuse.org/tests/1913262#step/docker_image/111

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13247

**Pull request merged**
