### PR TITLE
Enable 15-SP5 virtulization

### PR DESCRIPTION
**Pull request by tbaev**
Enable virtualization MU tests for 15-SP5 KVM/XEN/VMware/HyperV

- Related ticket: https://progress.opensuse.org/issues/128105
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1640
- Verification run:  
  15SP5 as host :
  [15SP5-XEN](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP5&groupid=168) [15SP5-KVM](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP5&groupid=167)

  15SP5 as guest on KVM hosts:
  [12SP3](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP3&groupid=143) [12SP4](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP4&groupid=142) [12SP5](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP5&groupid=149) [15SP1](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP1&groupid=147) [15SP2](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP2&groupid=152) [15SP3](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP3&groupid=154) [15SP4](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP4&groupid=164)

  15SP5 as guest on XEN hosts:
  [12SP3](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP3&groupid=162) [12SP4](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP4&groupid=161) [12SP5](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=12-SP5&groupid=160) [15SP1](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP1&groupid=158) [15SP2](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP2&groupid=157) [15SP3](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP3&groupid=156) [15SP4](http://openqa.qam.suse.cz/tests/overview?build=:teodor_test:&distri=sle&version=15-SP4&groupid=163)

guest on VMs on hyperV and VMware are created, waiting for SD-122162 to run tests.

### CODE REVIEW

**Comment by RoyCai7** [comment]
15SP5 as guest on KVM hosts sle15sp1 failed, maybe rerun will be ok.

**Review by RoyCai7 — COMMENTED** [review]
Add a line to filter vmware guest test.
`delete($guests{sles15sp5}) if (!is_sle('=15-SP5'));`

**Review by alice-suse — APPROVED** [review]
Looks good, thanks

**Comment by RoyCai7** [comment]
I checked vm: sles-15.5_openQA-virtualization-maintenance on win2k19.
need update current hostname dhcp227 to win2k19-sle15-sp5.

**Comment by tbaev** [comment]
@RoyCai7 
I have added the line for vmware, and a ticket is created to infra for creating domain win2k19-sle15-sp5 .

**Comment by RoyCai7** [comment]
Pending Hyper-v and VMware VR tess.

**Comment by alice-suse** [comment]
@RoyCai7  Would you please also give a review to the needle MR https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1640?

**Comment by tbaev** [comment]
> Pending Hyper-v and VMware VR tess.

VR [VMware](https://openqa.suse.de/tests/11182411#)  done, HyperV test is still waiting for infra.

**Comment by alice-suse** [comment]
Merge it since all comments resolved. Thank you.

**Review by tonyyuan1 — COMMENTED** [review]
lgtm

**Pull request merged**
