### PR TITLE
[WIP] Add extra results

### PR DESCRIPTION
**Pull request by richiejp**
Add LTP test results to the 'external results' tab.

### CODE REVIEW

**Comment by richiejp** [comment]
@Martchus I am not sure if the field names are correct for extra results. So can you check them and/or point me to the place in OpenQA where they are used?

See: https://progress.opensuse.org/issues/46559

**Comment by Martchus** [comment]
The 'External results' tab shows test details processed by openQA's parser framework (Perl modules within `OpenQA::Parser::` prefix). I don't know exactly what the parser framework accepts, though. I assume it didn't pick up the results in the way you added them?

I did a little bit reverse engineering. A result which is rendered in that tab looks like this: https://raw.githubusercontent.com/os-autoinst/openQA/master/t/testresults/00099/00099946-opensuse-13.1-DVD-i586-Build0091-textmode/details-logpackages.json  
The `"_source":"parser"` makes the difference here. This is produced in the line https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Parser/Result/OpenQA.pm#L34.

**Comment by richiejp** [comment]
@mudler Do you know/remember how this works?

**Comment by Martchus** [comment]
> The thing I understand least is what the UI does. I don't know where the code which produces that table is and whether it accesses the database or just looks for some files.

The database is not involved at all. It just reads the JSON which must be like the JSON file I've already linked. The relevant code for this is in `OpenQA::Utils::read_test_modules` and the template for rendering the table is `test/external.html.ep`.

**Comment by richiejp** [comment]
Ok, thanks

**Pull request closed without merging**
