### PR TITLE
Remove soft-fail of fixed bsc#1063844

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1063844

@coolo, is it ok when I removed you from the maintainer section?

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@okurz's idea

échale la culpa

http://www.reactiongifs.com/r/2013/09/it-was-him.gif

**Comment by okurz** [comment]
please make sure the bug is VERIFIED FIXED first

**Comment by coolo** [comment]
Do I want to stay maintainer?

**Comment by SergioAtSUSE** [comment]
@okurz, I did. I wanted to use the link of a verification run on OSD, but, status of bug changed.

**Pull request merged**
