### PR TITLE
Adopt openscap tests for qam testing

### PR DESCRIPTION
**Pull request by tonyyuan1**
Adopt openscap tests to QAM test repo tests.

- Related ticket: https://progress.opensuse.org/issues/58844
- Needles: no
- Verification run: 
- sles12sp4: http://10.67.17.201/tests/1252
- sles12sp5: http://10.67.17.201/tests/1246
- sles15: http://10.67.17.201/tests/1250
- sles15sp1: http://10.67.17.201/tests/1249
- sles15sp2: http://10.67.17.201/tests/1245

### CODE REVIEW

**Comment by tonyyuan1** [comment]
@lilyeyes @dzedro please review.

**Review by lilyeyes — APPROVED** [review]
LGTM ：）

**Review by dzedro — APPROVED** [review]
This tests should use serial console

**Comment by tonyyuan1** [comment]
> This tests should use serial console
Thanks for review!
yes. We can adopt it into our tests first and improve it in the future.

**Pull request merged**
