### PR TITLE
VLC: test video rendering

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/42773
Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/699
Verification: http://kazhua.qa.suse.de/tests/139

### CODE REVIEW

**Review by okurz — APPROVED** [review]
@DimStar77 WDYT?

**Review by foursixnine — APPROVED** [review]
Travis wants some love

**Comment by asdil12** [comment]
ran tidy

**Comment by DimStar77** [comment]
That send quite fragile, current tw snapshot Beth's tested has a couple fails on this new check

E.g https://openqa.opensuse.org/tests/1482978

**Comment by asdil12** [comment]
I guess the kde needle was missing

**Comment by asdil12** [comment]
needle created and job restarted

**Comment by DimStar77** [comment]
On gnome, 83% match only
https://openqa.opensuse.org/tests/1483027#step/vlc/29

IMHO, too unstable

**Comment by DimStar77** [comment]
I created an additional set of needles for GNOME/KDE; lte's see if we now have sufficient needles or if this varies day by day

**Comment by okurz** [comment]
If you don't do that already please consider a low match level, e.g. 80%

**Comment by DimStar77** [comment]
> If you don't do that already please consider a low match level, e.g. 80%

Good point; if I have to create another set, I'll think about that

**Comment by DimStar77** [comment]
Seen other test fails with 0% match, like
https://openqa.opensuse.org/tests/1483275

**Comment by asdil12** [comment]
I'm working on a stabilisation: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11477

**Comment by DimStar77** [comment]
Can we revert this here in the time being?

**Pull request merged**
