### PR TITLE
Remove snapper test from o3

### PR DESCRIPTION
**Pull request by asmorodskyi**
Short term fix for #poo16254 to not block Tumbleweed
while we trying to fix #poo16254

### CODE REVIEW

**Comment by asmorodskyi** [comment]
@okurz  , @DimStar77

**Comment by okurz** [comment]
In your commit messages (subject lines) please state why, not what

**Comment by okurz** [comment]
he already did: https://build.opensuse.org/package/view_file/openSUSE:Factory:Staging/dashboard/known_failures?expand=1

**Comment by asmorodskyi** [comment]
If @DimStar77 can just ignore it for a while I don't see the point of this commit at all. I did it because @okurz told me that this is blocking Tumbleweed release. If it's not true then we can revert this commit and concentrate on just fixing the issue. @DimStar77 , @sysrich , @okurz , agreed ?

**Comment by okurz** [comment]
I'm torn. Basically both https://build.opensuse.org/package/view_file/openSUSE:Factory:Staging/dashboard/known_failures?expand=1 as well as failing tests should be our "backlog". My personal preference is to exclude less (best none) over the "known_failures" and better explicitly within the test code as we can do it on the module or statement level. The "known_failures" file excludes the whole scenario -> we will miss all the wonderful bugs again because the other modules are also ignored

**Comment by DimStar77** [comment]
TW can ignore 'whole tests', but not to the detail of modules... currently it's set (again) to ignore this scenario - which also means any other failure within this scenario will just be ignored too and not raise any flags...

Both approaches are fine for me 'for a short period of time'

**Comment by okurz** [comment]
ok, let's remove from known failures then

**Pull request merged**
