### PR TITLE
Fix wrong network device name for aarrch64 on Tumbleweed

### PR DESCRIPTION
**Pull request by Zaoliang**
it seems that different device name is used for aarch64. 
see poo#131168

### CODE REVIEW

**Comment by Zaoliang** [comment]
to find out what is correct name on aarch64 at first: https://openqa.opensuse.org/tests/3380937

**Comment by Zaoliang** [comment]
https://openqa.opensuse.org/tests/3382570 fixed now

**Comment by rfan1** [comment]
s/devic/device/g

**Comment by Zaoliang** [comment]
> s/devic/device/g

yes, thanks!

**Pull request merged**
