### PR TITLE
Rstudio 1 3 fixes

### PR DESCRIPTION
**Pull request by dcermak**
- Related ticket: N/A
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/676
- Verification run: ~~https://openqa.opensuse.org/t1348915~~ https://openqa.opensuse.org/tests/1348916

### CODE REVIEW

**Comment by dcermak** [comment]
Unfortunately I am unable to clone the job properly :( This command always results in a failure on o3:
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10767 https://openqa.opensuse.org/tests/1348116 _SKIP_POST_FAIL_HOOKS=1 NEEDLES_DIR=https://github.com/dcermak/os-autoinst-needles-opensuse#99c060d2382c3954658765299ff2cc28500a6953
```

**Comment by foursixnine** [comment]
@dcermak could you provide a passing VR?

**Comment by dcermak** [comment]
> @dcermak could you provide a passing VR?

Unfortunately no, because the verification run needs new needles and I cannot get openqa to fetch the needles from git.

**Comment by dcermak** [comment]
Next try: https://openqa.opensuse.org/tests/1364089

**Comment by dcermak** [comment]
@foursixnine The last linked run succeeded. I can haz merge now ;-) ?

**Pull request merged**
