### PR TITLE
Update Security maintainer in test modules

### PR DESCRIPTION
**Pull request by lilyeyes**
Update Security maintainer in test modules.

- Related ticket: https://progress.opensuse.org/issues/60809
- Needles: NA
- Verification run: NA

### CODE REVIEW

**Comment by okurz** [comment]
thank you!

**Comment by lilyeyes** [comment]
> thank you!

Thank youuu :)

**Comment by jouyingbin** [comment]
Sorry for late. 
Would it be possible that we could keep the original maintainer to **Original Author**?

**Comment by okurz** [comment]
For this we have git, don't we? The maintainer should be always current. I don't see the use for an "author" in a comment field additionally

**Pull request merged**
