### PR TITLE
port vagrant jenkins pipeline to openQA

### PR DESCRIPTION
**Pull request by dcermak**
This is a work in progress pull request to move the currently hidden jenkins pipeline fully into openQA and test the Tumbleweed Vagrant box on openQA.

- Related ticket: NA
- Needles: not required
- Verification run: https://openqa.opensuse.org/tests/1481792

### CODE REVIEW

**Review by okurz — COMMENTED** [review]
I am very much interested in the concept. Would you mind to explain more about this in the git commit message? That would be great

**Comment by dcermak** [comment]
Oliver Kurz <notifications@github.com> writes:

> @okurz commented on this pull request.
>
> I am very much interested in the concept. Would you mind to explain more about this in the git commit message? That would be great

I have expanded the commit message and also managed a successful
verification run on o3 (link in the first comment).

**Comment by dcermak** [comment]
Works on aarch64 as well: https://openqa.opensuse.org/tests/1481814

cc @ggardet

**Review by okurz — APPROVED** [review]
Impressive. I like it :)

**Comment by dcermak** [comment]
> Impressive. I like it :)

Thanks! Shall we merge this then?

**Comment by okurz** [comment]
Well, you have merge rights just as well as me, right? I wasn't merging because I am neither an active current contributor nor maintainer nor test reviewer so I would appreciate if someone else can also approve or you just merge yourself as you are also part of said group. But as the grace period of 10 days passed and you are just waiting for merge I can of course press the button myself as well :)

**Pull request merged**
