### PR TITLE
grub_test: Work around the instmenu after last os-autoinst change

### PR DESCRIPTION
**Pull request by okurz**
Local verification run: http://lord.arch/tests/5448

Related issue: [poo#15178](https://progress.opensuse.org/issues/15178)

### CODE REVIEW

**Comment by okurz** [comment]
Let's wait if http://lord.arch/tests/5448 actually succeeds.

**Comment by okurz** [comment]
DONE: works, see http://lord.arch/tests/5448

**Comment by DimStar77** [comment]
https://openqa.opensuse.org/tests/316943#step/grub_test/1

On reboot after install, the system boots directly off HDD - so there is no 'From HDD' entry; do we have to create a new needle for this now again? (before the needle grub2-TW-20151222 matched 100%, see https://openqa.opensuse.org/tests/316943#step/grub_test/1 for the last run)

**Comment by coolo** [comment]
https://openqa.opensuse.org/tests/317076#step/grub_test/2 - Leap tests are broken too.

**Comment by okurz** [comment]
see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2202

**Comment by okurz** [comment]
I will take a closer look now

**Pull request merged**
