### PR TITLE
README and Makefile improvements

### LINKED ISSUE #845: Add README and LICENSE
os-autoinst-distri-opensuse should include some minor doc and information.

#### My proposal:
 * *README*: Could be very similar to or based on https://github.com/kobliha/openqa-yast/blob/master/README.md including a mini contribution note like last line from https://github.com/os-autoinst/os-autoinst/blob/master/README.asciidoc
 * *LICENSE* (or COPYING): A bit tough, ask all developers what LICENSE applies or should be applied. If everyone agrees use GPLv2 like openQA. Could also be permissive like MIT/BSD "2 clause" as it is only test cases anyway :-)
 * We might not want to apply the same for some tests, e.g. SLE in the corresponding branches. Then I would propose to actually separate them into individual github projects

##### proposal for contribution note, license
```
## How to contribute

Fork the repository and make some changes.
Once you're done with your changes send a pull request. Thanks!
If you have questions, visit us on irc.freenode.net in #opensuse-factory or ask on our mailing list opensuse-factory@opensuse.org


## License

Distributed under the XXX license.
```

What are your opinions?

### PR DESCRIPTION
**Pull request by okurz**
Fixes #845

### CODE REVIEW

**Comment by aaannz** [comment]
needs rebase, then LGTM

**Comment by okurz** [comment]
rebased

**Comment by sysrich** [comment]
Looks good, but I'd like to investigate the possibility putting the tests under a more permissive license than 'copyright SUSE' before merging this.

**Comment by coolo** [comment]
You can put them under GPL without any further complications. They moved out of os-autoinst

**Comment by okurz** [comment]
Are there any contributors which we would need to ask if *their* contribution is also ok to be licensed GPL, e.g. non-SUSE collaborators?

**Comment by coolo** [comment]
As I mentioned, they code has always been GPL - just not marked as is.

**Comment by okurz** [comment]
I don't understand what you mean. How does this relate to https://github.com/os-autoinst/os-autoinst-distri-opensuse/issues/845#issuecomment-160398105 ?
Anyway, I suggest @coolo and @sysrich decide about the license then and either cherry-pick, merge or you can tell me what I should write

**Comment by coolo** [comment]
my comment in #845 was about how the repo looks to contributors.

**Comment by okurz** [comment]
So I should rewrite the README to GPL and add a LICENSE file and you merge it or what?

**Comment by coolo** [comment]
See https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/918 for my version of events

**Comment by okurz** [comment]
fixed with / obsoleted by #918

**Pull request closed without merging**
