### PR TITLE
xfstests: Reorganize xfstests and fix a known issue

### PR DESCRIPTION
**Pull request by SeroSun**
As conclusion in discussion[1]. I revert PR#10101 and PR#10222. To reduce the risk during GMC, I revert those two PR before GMC. As we have GM now, let's re-revert it, and develop with this reorganized xfstests. It's looks the same as PR#10101 and PR#10222.

[1] https://confluence.suse.com/pages/viewpage.action?spaceKey=qasle&title=Filesystem+Test+Discussion

Besides those two commit, I add one more commit to fix known issue in previous 2 commits. In previous code, global parameter use export command to set, but if an unexpected reboot happens those global parameter will lose meaning. This commit will fix this by using local.config file to control all global parameters in xfstests.

- Related ticket: https://progress.opensuse.org/issues/66850
- Verify run:
[SLE-filesystem]
Installation: http://openqa.suse.de/tests/4405947
btrfs: http://openqa.suse.de/tests/4406079
xfs: http://openqa.suse.de/tests/4406080
s390x: http://openqa.suse.de/tests/4409915
ppc64le: http://openqa.suse.de/tests/4409916

[QAM xfstests]
Installation: http://openqa.suse.de/tests/4412863
qam-xfstests_xfs-generic+sle12-001-100: http://openqa.suse.de/tests/4412949

### CODE REVIEW

**Comment by SeroSun** [comment]
Verify run are all looks fine, this PR ready to merge

**Comment by czerw** [comment]
Maybe, if you could change also PR name to show description. Please avoid re-revert (it is in description anyway). Just to be sure before merge, were also QAM jobs verified?

**Comment by SeroSun** [comment]
> Maybe, if you could change also PR name to show description. Please avoid re-revert (it is in description anyway). Just to be sure before merge, were also QAM jobs verified?

OK, I changed PR name. And I can't find exist xfstests test in QAM job group, would you please show me a link, then I can trigger the verify run for QAM.

**Comment by SeroSun** [comment]
Never mind I find one link in https://openqa.nue.suse.com/tests/overview?distri=sle&version=12-SP4&build=20200701-2&groupid=218, I'll trigger a test in some old version to avoid influence their test.

**Comment by czerw** [comment]
> Never mind I find one link in https://openqa.nue.suse.com/tests/overview?distri=sle&version=12-SP4&build=20200701-2&groupid=218, I'll trigger a test in some old version to avoid influence their test.

Thank you. @dzedro could you please check as well?

**Comment by SeroSun** [comment]
Hi @dzedro, I try to retrigger create_hdd_xfstests in QAM jobgroup but always fail in download part. Any idea? http://openqa.suse.de/tests/4412859

I used following command:
openqa-clone-job --skip-download --skip-chained-deps --from openqa.suse.de  --host openqa.suse.de 4406445 DISTRI=sle _NOOBSOLETEBUILD=1 VERSION=12-SP4 FLAVOR=Server-DVD-Updates TEST=create_hdd_xfstests CASEDIR=https://github.com/SeroSun/os-autoinst-distri-opensuse.git#yosun/restore_pr_10101

**Comment by SeroSun** [comment]
Aha, I changed to use a new build then runs OK. Previous fail because of openQA removed qcow2 files.

VR:
[QAM xfstests]
Installation: http://openqa.suse.de/tests/4412863
qam-xfstests_xfs-generic+sle12-001-100: http://openqa.suse.de/tests/4412949

**Comment by okurz** [comment]
Something went really wrong on the PR description with "Reorganiaze" now :D

Also the word in the git commit message "globle" is likely wrong. Not sure, maybe you meant "global"?

**Comment by SeroSun** [comment]
> Something went really wrong on the PR description with "Reorganiaze" now :D
> 
> Also the word in the git commit message "globle" is likely wrong. Not sure, maybe you meant "global"?

I modify the typo of global. But I don't understand what's the "really wrong" in PR description...

**Comment by okurz** [comment]
yes, looks better now. There is still "globle parameter". I guess you mean "global"

**Comment by SeroSun** [comment]
> yes, looks better now. There is still "globle parameter". I guess you mean "global"

Ah, I forgot modify it in commit message. Modified.

**Pull request merged**
