### PR TITLE
Remove the softfail in ip_eb_tables

### PR DESCRIPTION
**Pull request by Amrysliu**
Related: https://progress.opensuse.org/issues/111222

Verify run:
       https://openqa.suse.de/tests/8864200# (s390x)
       https://openqa.suse.de/tests/8864201# (x86_64)

### CODE REVIEW

**Review by rfan1 — APPROVED** [review]
LGTM

**Review by tinawang123 — APPROVED** [review]
LGTM

**Comment by rfan1** [comment]
@Amrysliu 
One minor comment,
how can we record the bug in this test module?'bsc#1192324'
we can add it to 'SUMMAY" part，does it make sense?

**Review by wangqianzou — APPROVED** [review]
LGTM

**Comment by Amrysliu** [comment]
> @Amrysliu One minor comment, how can we record the bug in this test module?'bsc#1192324' we can add it to 'SUMMAY" part，does it make sense?

I can add the comments into MR: https://gitlab.suse.de/security/audit-test-sle15/-/merge_requests/57

**Review by jouyingbin — APPROVED** [review]
LGTM

**Pull request merged**
