### PR TITLE
Terraform retry in case of CSP internal error

### PR DESCRIPTION
**Pull request by mpagot**
Change deploy test module only for the qesap regression test (for the moment).
Run terraform for a second time in case of a terraform failure with a specific error message.

- Related ticket: https://jira.suse.com/browse/TEAM-9027

# Verification run:

#### sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_sapconf_test@64bit
- http://openqaworker15.qa.suse.cz/tests/275468 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275469 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275470 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275471 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275472 :green_circle: Terraform PASS at the first try

#### - sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit 
- http://openqaworker15.qa.suse.cz/tests/275473 job fails in Ansible for reboot timeout in http://openqaworker15.qa.suse.cz/tests/275473#step/deploy/47
- http://openqaworker15.qa.suse.cz/tests/275474 
- http://openqaworker15.qa.suse.cz/tests/275475 job fails in log collection, there was also an Ansible reboot timeout error http://openqaworker15.qa.suse.cz/tests/275475#step/deploy/47 and a second terraform/ansible retry.
- http://openqaworker15.qa.suse.cz/tests/275476 :green_circle: Terraform PASS at the first try
- http://openqaworker15.qa.suse.cz/tests/275477  :green_circle: Terraform PASS at the first try

### invalid QESAPDEPLOY_CLUSTER_OS_VER
Job triggered with intentionally invalid OS image, expected result is that new code to grep the terraform log is called but the string about the internal error is not found and the job failed without any retry
http://openqaworker15.qa.suse.cz/tests/275478

grep in the terraform log is here http://openqaworker15.qa.suse.cz/tests/275478#step/deploy/16 then no retry and died http://openqaworker15.qa.suse.cz/tests/275478#step/deploy/19

### Internal error string
The special string about the internal error is injected in the terraform log. The terraform execution is expected to fails, string search in the log, match and terraform retry, fails again and job give up
http://openqaworker15.qa.suse.cz/tests/275479

Internal error detected http://openqaworker15.qa.suse.cz/tests/275479#step/deploy/18 it triggers a Terraform re-execution http://openqaworker15.qa.suse.cz/tests/275479#step/deploy/24

### CODE REVIEW

**Review by lpalovsky — APPROVED** [review]
LGTM.

In the description the word 'test' is missing last 't'
`Change deploy tes module`

**Review by BillAnastasiadis — APPROVED** [review]
LGTM

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Review by a-kpappas — APPROVED** [review]

**Review by lilyeyes — COMMENTED** [review]
LGTM.

**Pull request merged**
