### PR TITLE
xfstests: Fix loop device number and increase HB timeout

### PR DESCRIPTION
**Pull request by dzedro**
- Related ticket: https://progress.opensuse.org/issues/81790
- Fail: https://openqa.suse.de/tests/5266872#step/run/404 inconsistent FS on test_dev after failed test
- Verification run:
http://dzedro.suse.cz/tests/17200
https://openqa.suse.de/tests/5270957 15
https://openqa.suse.de/tests/5271027 15
https://openqa.suse.de/tests/5261557 15-sp1 
https://openqa.suse.de/tests/5260952 15-sp1
https://openqa.suse.de/tests/5260953 15-sp2
https://openqa.suse.de/tests/5270917 15-sp2
https://openqa.suse.de/tests/5260954 12-sp5
https://openqa.suse.de/tests/5271052 12-sp5
https://openqa.suse.de/tests/5260955 15-sp3 x86_64
https://openqa.suse.de/tests/5260956 15-sp3 s390x
https://openqa.suse.de/tests/5260957 15-sp3 ppc64le
https://openqa.suse.de/tests/5260959 15-sp3 aarch64

### CODE REVIEW

**Comment by SeroSun** [comment]
1. Longer timeout is OK, it use to be larger than 200 in commit 5fd11dd8e1992b9b3365a126c5ebe95e78de39f1. But I forgot why we make it small. Let's see what happened
2. The path fix is great, it will fix the problem in https://openqa.suse.de/tests/5262571#step/run/912
3. The scratch_number need double check, because the name in  "reload_loop_device" need to match the name in partition.pm Line163. That $num start with 0. I think here need to also keep number start from 0
 $filename = "scratch_dev$num";

**Comment by dzedro** [comment]
1. 200 should be enough, 300 would be even safer.
2. Missing path is obvious.
3. This was broken always due to missing path and this failures have been just restarted.
    Easy to reproduce with too low timeout.
    with `my $scratch_num    = 1;` http://dzedro.suse.cz/tests/17244#step/run/54
    with `my $scratch_num    = 0;` http://dzedro.suse.cz/tests/17245#step/run/54

**Comment by lansuse** [comment]
`$scratch_num` should start with 0. If we got no such file error, I think we should rerun `create_loop_device_by_rootsize()` in partition.pm but not start with 1.

**Comment by lansuse** [comment]
> `$scratch_num` should start with 0. If we got no such file error, I think we should rerun `create_loop_device_by_rootsize()` in partition.pm but not start with 1.

I think another benefit of this is keep loop device name and path consistent in partition.pm and run.pm always.

**Comment by dzedro** [comment]
Why rerun `create_loop_device_by_rootsize`, scratch_dev is never starting with 0.

```
    set_var('XFSTESTS_TEST_DEV', '/dev/loop0');
    script_run("echo 'export TEST_DIR=/mnt/test' >> $CONFIG_FILE");
    script_run("echo 'export SCRATCH_MNT=/mnt/scratch' >> $CONFIG_FILE");
    if ($amount == 1) {
        script_run("echo 'export SCRATCH_DEV=/dev/loop1' >> $CONFIG_FILE");
        set_var('XFSTESTS_SCRATCH_DEV', '/dev/loop1');
    }
    else {
        script_run("echo 'export SCRATCH_DEV_POOL=\"/dev/loop1 /dev/loop2 /dev/loop3 /dev/loop4 /dev/loop5\"' >> $CONFIG_FILE");
        set_var('XFSTESTS_SCRATCH_DEV_POOL', '/dev/loop1 /dev/loop2 /dev/loop3 /dev/loop4 /dev/loop5');
```

**Comment by SeroSun** [comment]
I think Josef is right, when reboot happened the loop device need to reload, but the block file created by fallocate ($INST_DIR/$filename) not destroy, only need to losetup them.
And about scratch_num, I double check the partition.pm create_loop_device_by_rootsize function. In its while, the first loop num==0 and it goes into test filename not scratch filename. So the scratch filename start with num==1. His VR also prove this.
with my $scratch_num = 1; http://dzedro.suse.cz/tests/17244#step/run/54
with my $scratch_num = 0; http://dzedro.suse.cz/tests/17245#step/run/54

**Comment by lansuse** [comment]
I see, it's clear to me now. Loop0 is for TEST_DEV, so scratch_dev should start with 1.

**Comment by dzedro** [comment]
> I see, it's clear to me now. Loop0 is for TEST_DEV, so scratch_dev should start with 1.

Exactly, I guess it can't be different because xfstests do expect  test_dev being /dev/loop0

**Review by SeroSun — APPROVED** [review]
Then let's merge it :)

**Pull request merged**
