### PR TITLE
SLE11 firefox with KDE has to accept "default browser check"

### PR DESCRIPTION
**Pull request by dzedro**
tested on http://10.100.98.90/tests/302

### CODE REVIEW

**Comment by coolo** [comment]
I have my doubts you tested this. It's just not valid perl and indeed:
http://10.100.98.90/tests/302/modules/sle11_firefox/steps/5/src is a different sle11_firefox

**Comment by dzedro** [comment]
Updated code with Richards & Coolos help, testing on http://10.100.98.90/tests/318

**Comment by coolo** [comment]
please rebase

**Comment by coolo** [comment]
aehm, squash the commits - that's what I mean

**Comment by dzedro** [comment]
done

**Pull request merged**
