### PR TITLE
upgrade test

### PR DESCRIPTION
**Pull request by aaannz**
Mini how to:
- select test A (preferably one that install from scratch) and add STORE_ASSET variable to it. This will upload resulting HDD as job asset
- select (or create new) another test B and when at least one generated asset exists, set test B as chained parent to test A. This makes sure that test B use asset generated in previous run of test A
- set ZDUP or ZDUP_IN_X to test B to perform upgrade

- this use serial output and enhanced ( https://github.com/os-autoinst/os-autoinst/pull/250 ) wait_serial instead of plain needle matching

### CODE REVIEW

**Comment by coolo** [comment]
what's the value of STORE_ASSET? e.g. gnome-x86_64.qcow2?

**Comment by aaannz** [comment]
Yes, sorry, forgot to mention. It's the filename to be used for asset.

**Comment by coolo** [comment]
that much I gathered. My question was rather practical - what's your recommendation on the "filename to be used"

**Comment by aaannz** [comment]
Aha! In my tests I use 'desktop-gnome.qcow2' and 'desktop-kde.qcow2', but I'm testing only 64bit. So using %{desktop}-%{arch}.qcow2 seems good choice.
If we ever go to something like testing zdup from half year old TW, I would suggest some date reference e.g. %{desktop}-%{arch}-%{release}.qcow2

**Comment by coolo** [comment]
too bad we don't support %{desktop} in variables ;(

**Pull request merged**
