### PR TITLE
Clean audit.log before restart smbd

### PR DESCRIPTION
**Pull request by lilyeyes**
Clean audit.log before restarting smbd

poo#101710 - [sle][security][sle15sp4] test fails in usr_sbin_smbd discloses the "audit.log" should not be cleared after "restart smb"

- Related ticket: https://progress.opensuse.org/issues/101710
- Needles: NA
- Verification run:
  https://openqa.nue.suse.com/tests/8286859# (the new fail can be tracked by bug: https://bugzilla.suse.com/show_bug.cgi?id=1196850)

### CODE REVIEW

**Review by rfan1 — APPROVED** [review]

**Comment by rfan1** [comment]
Clean audit.log before doing restart smbd instead of after smbd restarted seems a little complex

Minot comment:
Clean audit.log before restarting smbd [imo]

**Review by jouyingbin — APPROVED** [review]
LGTM

**Review by Amrysliu — APPROVED** [review]

**Comment by dzedro** [comment]
This is breaking 15 SP3 https://openqa.suse.de/tests/8307131#step/usr_sbin_smbd/97 https://progress.opensuse.org/issues/108119

**Comment by lilyeyes** [comment]
> This is breaking 15 SP3 https://openqa.suse.de/tests/8307131#step/usr_sbin_smbd/97 https://progress.opensuse.org/issues/108119

@dzedro  It is as expected, this fail can be tracked by bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1196850

**Pull request merged**
