### PR TITLE
Need report failure when patterns conflict happen

### PR DESCRIPTION
**Pull request by lemon-suse**
We need report failure when patterns conflict happen, besides workaround for known bug we need deal with other patterns conflict and report failure. 

- Related ticket: https://progress.opensuse.org/issues/77794
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/4991588#step/patch_sle/133
                            http://openqa.nue.suse.com/tests/4991532#details  # verify it won't affect workaround for reported bug

### CODE REVIEW

**Comment by okurz** [comment]
Hi, the git commit message has a typo. Please take care of the quality of commit messages as well. We do care about quality, right? It's in our job title ;)

**Comment by lemon-suse** [comment]
> Hi, the git commit message has a typo. Please take care of the quality of commit messages as well. We do care about quality, right? It's in our job title ;)

Thanks, I knew it. NP, I just wait the PR check then update together.

**Review by tinawang123 — APPROVED** [review]
LGTM

**Comment by lemon-suse** [comment]
Hi Oliver, do you still have any comments?

**Comment by okurz** [comment]
Well, The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a ticket, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

But I guess I am repeating myself :)

**Comment by lemon-suse** [comment]
> Well, The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a ticket, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.
> 
> But I guess I am repeating myself :)

Updated the commit message. Thanks.

**Review by okurz — APPROVED** [review]

**Pull request merged**
