### PR TITLE
Add s390x Scenario to opensuse main.pm

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by okurz** [comment]
Verification run? 

Did you compare the code to the SLE main and can you extract common code into lib/main_common.pm?

**Comment by Soulofdestiny** [comment]
extracted common code in lib/main_common.pm
verification run needs some more time because of needleing

**Comment by okurz** [comment]
can you use single ticks always unless you want perl variable expansion?

**Comment by Soulofdestiny** [comment]
updated,
verification run (failing due to product bug atm, but scheduling works right): http://opeth.suse.de/tests/4675

please consider also merging needles with this one
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/152

**Pull request merged**
