### PR TITLE
Stop running failure_analysis in case of failure in failure_analysis

### PR DESCRIPTION
**Pull request by asmorodskyi**

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
I need a verification run ;)

**Comment by okurz** [comment]
LGTM

**Comment by okurz** [comment]
As this module is used basically everywhere and I don't fully trust @asmorodskyi and my perl competence I think I would also like to see a verification run

**Comment by asmorodskyi** [comment]
Sorry this PR fallout from my scope 
http://kimball.arch.suse.de/tests/548

**Comment by SergioAtSUSE** [comment]
@asmorodskyi, do you have a verification run with failing modules?

**Comment by okurz** [comment]
he ran one job covering that code, good enough for now

**Pull request merged**
