### PR TITLE
openssh: Support openssh package shipping default config in /usr/etc

### PR DESCRIPTION
**Pull request by DimStar77**
- Related ticket: https://progress.opensuse.org/issues/92617
- Needles: N/A
- Verification run: [TW](https://openqa.opensuse.org/t1767556)

### CODE REVIEW

**Review by pdostal — APPROVED** [review]
Thank you for the clarification in the ticket and sorry for blocking this.

**Comment by pdostal** [comment]
Give me please one more hour. I will do at least one verification run on SLE.

**Comment by DimStar77** [comment]
> Give me please one more hour. I will do at least one verification run on SLE.

No problem - I have that openssh change https://build.opensuse.org/request/show/888799 stage and it is not ready just yet for a test run anyway - will take a few more hours and if possible I'd want a VR with that package as well before we merge

**Comment by pdostal** [comment]
Verification run for [SLE 15-SP3](https://openqa.suse.de/tests/6202005#step/sshd/5)

**Review by OleksandrOrlov — APPROVED** [review]
[Verification Run](https://openqa.suse.de/tests/6202005#step/sshd/5) is passed on OSD. LGTM.

**Comment by DimStar77** [comment]
> [Verification Run](https://openqa.suse.de/tests/6202005#step/sshd/5) is passed on OSD. LGTM.

Great, so we know there is no regression. Let's just wait for the Staging project to become ready so we can run it against the new openssh package, and when confirmed working there too, merge

**Comment by DimStar77** [comment]
[Staging:N - openssh config in /usr/etc VR](https://openqa.opensuse.org/t1775349)

**Pull request merged**
