### PR TITLE
Enable yamllint for schedule and test_data and adjust yaml files accordingly

### PR DESCRIPTION
**Pull request by rwx788**
After detecting that '!include' is invalid tag, we decided that running yamllint would be beneficial to detect such issues in future. Running the tool on existing profiles has shown multiple issues which we have addressed in this PR. Modified yaml files belong to QSF-Y only.
CI check will validate only files being changed in the PR, meaning that other existing yaml files might contain issues and we leave it to responsible teams to act.

See [poo#64755](https://progress.opensuse.org/issues/64755).

### CODE REVIEW

**Comment by OleksandrOrlov** [comment]
Not sure if my assist will be helpful for you, but just in case here are the files with '{{' that seems like still require quotes:

- schedule/yast/btrfs/btrfs_sle_libstorage.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng.yaml
- schedule/yast/btrfs/btrfs_sle_libstorage-ng@hmc+ipmi.yaml
- schedule/yast/yast2_cmd.yaml
- schedule/yast/msdos.yaml

**Comment by rwx788** [comment]
> Not sure if my assist will be helpful for you, but just in case here are the files with '{{' that seems like still require quotes:
> 
>     * schedule/yast/btrfs/btrfs_sle_libstorage.yaml
> 
>     * schedule/yast/btrfs/btrfs_sle_libstorage-ng.yaml
> 
>     * schedule/yast/btrfs/btrfs_sle_libstorage-ng@hmc+ipmi.yaml
> 
>     * schedule/yast/yast2_cmd.yaml
> 
>     * schedule/yast/msdos.yaml

Good point. I've only fixed curly braces in the schedules where I had to fix something else (to have less files touched at this point in time). But I guess it makes sense to fix this in all. I will check if it's only these 5 files or we have more.

**Comment by rwx788** [comment]
> Perhaps we could add another commit to fix documentation i.e.: `'{{cond_sch}}'`

Ah, good point. I was about to do that and then forgot. Thanks!

**Comment by OleksandrOrlov** [comment]
LGTM

**Pull request merged**
