### PR TITLE
Solve missing files to curl_server error 

### PR DESCRIPTION
**Pull request by martinsmarcelo**
This files solve error on curl_server, test was failed missing this files to configure openldap when running - [poo#51536](https://progress.opensuse.org/issues/51536)

../data/ldap/slapd.conf
../data/ldap/test.ldif

I need change curl_cleint to reflect new ldif. And confirm working:
SLES 15 Sp1 - http://10.161.228.111/tests/1464#step/curl_client/21

### CODE REVIEW

**Comment by okurz** [comment]
Some observations regarding the git commit and PR, not the content:

1. Better leave out the dot at the end-of-line of the subject line
2. Be more specific than "solve issue"
3. Use full URLs instead of poo#51536 , IMHO it's ok to use markdown syntax though, e.g. [poo#51536](https://progress.opensuse.org/issues/51536)
4. Please put more details in the git commit message. Linking to a progress issue is good, describing in more detail what is fixed without needing to rely on an external system

**Comment by martinsmarcelo** [comment]
> Some observations regarding the git commit and PR, not the content:
> 
>     1. Better leave out the dot at the end-of-line of the subject line
> 
>     2. Be more specific than "solve issue"
> 
>     3. Use full URLs instead of poo#51536 , IMHO it's ok to use markdown syntax though, e.g. [poo#51536](https://progress.opensuse.org/issues/51536)
> 
>     4. Please put more details in the git commit message. Linking to a progress issue is good, describing in more detail what is fixed without needing to rely on an external system

Done. Thank you.

**Comment by okurz** [comment]
Ok, I can see that you updated the PR but I rather meant the git commit message, at best both :) Sorry about not being clear.

**Comment by martinsmarcelo** [comment]
> Ok, I can see that you updated the PR but I rather meant the git commit message, at best both :) Sorry about not being clear.

Humm, ok, dono. Sorry my mistake.

**Comment by okurz** [comment]
+1

**Comment by martinsmarcelo** [comment]
> Please replace the licensed, not needed test.ldif

I think done. Please, could you verify ?

**Comment by okurz** [comment]
There is now a conflict in tests/network/curl_client.pm

**Comment by martinsmarcelo** [comment]
> There is now a conflict in tests/network/curl_client.pm

Ok, I think this because file not in master yet, I need verify with Josef about this file tomorrow.

**Comment by martinsmarcelo** [comment]
So, finally I think solved all problems from my git locally. Solved conflicts. 
And checked, working fine:
http://10.161.228.111/tests/overview?distri=sle&version=15-SP1&build=15-SP1&groupid=141

**Pull request merged**
