### PR TITLE
NETFILTER_PKT test fix in ip_eb_tables

### PR DESCRIPTION
**Pull request by vtrubovics**
NETFILTER_PKT test fix in ip_eb_tables

    Related ticket: https://bugzilla.suse.com/show_bug.cgi?id=1188851, https://progress.opensuse.org/issues/97076
    Gitlab merge request https://gitlab.suse.de/security/audit-test-sle15/-/merge_requests/25
    Successfull test run: https://openqa.suse.de/tests/7030292#details

### CODE REVIEW

**Comment by vtrubovics** [comment]
By mistake closed PR https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13112, opened new.

**Comment by Amrysliu** [comment]
The code LGTM,  just one comment for the commit message, could you clean up the commits? I saw this pr includes 9 commits.

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by rfan1** [comment]
Can you please add your verification run results here?

**Comment by vtrubovics** [comment]
> The code LGTM, just one comment for the commit message, could you clean up the commits? I saw this pr includes 9 commits.

How to correctly do it?

**Comment by vtrubovics** [comment]
> 
> 
> Can you please add your verification run results here?

Link to the test run https://openqa.suse.de/tests/7030292#details
Also updated PR description?

**Comment by jouyingbin** [comment]
> > The code LGTM, just one comment for the commit message, could you clean up the commits? I saw this pr includes 9 commits.
> 
> How to correctly do it?

I always simply check out the latest code in $your_branch,
and `git add + git commit` your change, (generally we do not make too many commits in 1 PR)
and then rebase, `git pull upstream master --rebase`
and then push, `git push origin $your_branch`

Go back to GitHub and send the pull request again. 
Perhaps it will avoid too many commits in 1 PR.

But currently, I have no clue to combine 9 commits into 1, do you @Amrysliu  have some ideas ？ :-)

**Comment by Amrysliu** [comment]
> > The code LGTM, just one comment for the commit message, could you clean up the commits? I saw this pr includes 9 commits.
> 
> How to correctly do it?

I usually use `git rebase -i HEAD~9` to combine the commits.

**Comment by rfan1** [comment]
LGTM

**Review by rfan1 — APPROVED** [review]

**Comment by vtrubovics** [comment]
Will make clean commits and PR.

**Comment by vtrubovics** [comment]
New PR with one commit https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13203

**Pull request closed without merging**
