### PR TITLE
wicked: Enter into directory before switching the branch

### PR DESCRIPTION
**Pull request by asmorodskyi**
Enter into directory before switching the branch 

VRs : 
SUT , WICKED_SOURCES includes branch :  https://openqa.suse.de/tests/3666208
SUT , WICKED_SOURCES NOT includes branch : https://openqa.suse.de/tests/3666152

### CODE REVIEW

**Comment by schlad** [comment]
I am perhaps boring already with this... but since you asked for the review....

as always with such simple changes, I would prefer to see a commit message explaining 'why'.
For now  the 1-liner commit states the obvious. I would prefer you amend your commit message and explain the purpose of this simple change.

**Comment by asmorodskyi** [comment]
> I am perhaps boring already with this... but since you asked for the review....
> 
> as always with such simple changes, I would prefer to see a commit message explaining 'why'.
> For now the 1-liner commit states the obvious. I would prefer you amend your commit message and explain the purpose of this simple change.

hm let's see . I doing this to fix a test failure , so you want me to change it to "Fix a test failure " ? Or to "Avoid getting 'Not a git repo exception'" ?

**Comment by schlad** [comment]
> > I am perhaps boring already with this... but since you asked for the review....
> > as always with such simple changes, I would prefer to see a commit message explaining 'why'.
> > For now the 1-liner commit states the obvious. I would prefer you amend your commit message and explain the purpose of this simple change.
> 
> hm let's see . I doing this to fix a test failure , so you want me to change it to "Fix a test failure " ? Or to "Avoid getting 'Not a git repo exception'" ?

So that was never working?

**Comment by asmorodskyi** [comment]
> > > I am perhaps boring already with this... but since you asked for the review....
> > > as always with such simple changes, I would prefer to see a commit message explaining 'why'.
> > > For now the 1-liner commit states the obvious. I would prefer you amend your commit message and explain the purpose of this simple change.
> > 
> > 
> > hm let's see . I doing this to fix a test failure , so you want me to change it to "Fix a test failure " ? Or to "Avoid getting 'Not a git repo exception'" ?
> 
> So that was never working?

Yes this functionality was introduced by #8507  but was not properly tested for case when you providing git url with a branch , and current master is trying checkout branch without actually navigating to repository . This patch is change behavior to actually enter to directory before switching the branch . But if you ask me "Why ?" I would say "to fix  the failure"

**Comment by schlad** [comment]
obviously my point is minor but still you missing the point.
Most commits could be then written the way you suggest: "fix the failure"

I was sharing this before:
"In most cases, you can leave out details about how a change has been made. Code is generally self-explanatory in this regard (and if the code is so complex that it needs to be explained in prose, that’s what source comments are for). Just focus on making clear the reasons why you made the change in the first place—the way things worked before the change (and what was wrong with that), the way they work now, and why you decided to solve it the way you did."
please see: https://chris.beams.io/posts/git-commit/
point 7 specifically

**Comment by asmorodskyi** [comment]
> obviously my point is minor but still you missing the point.
> Most commits could be then written the way you suggest: "fix the failure"
> 
> I was sharing this before:
> "In most cases, you can leave out details about how a change has been made. Code is generally self-explanatory in this regard (and if the code is so complex that it needs to be explained in prose, that’s what source comments are for). Just focus on making clear the reasons why you made the change in the first place—the way things worked before the change (and what was wrong with that), the way they work now, and why you decided to solve it the way you did."
> please see: https://chris.beams.io/posts/git-commit/
> point 7 specifically

yeah sure I have seen this URL dozens of times :) It is defined on some wiki page I suppose. After re-reading 7th point **again** I still don't see better title for PR except current or I can switch to "Fix the bug" . But I updated commit message with some more detailed info about why I did the change. 
In case you still think I doing it wrong maybe you can suggest me some certain title for this commit ? The one which would answer question why ?

**Comment by schlad** [comment]
> I still don't see better title for PR except current

I did not say the title is not good.
There was no commit message.
Thx for amending the commit message. 
To me it looks really better!

**Pull request merged**
