### PR TITLE
Disable amarok test as it's unreliable (boo#1070899)

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
@DimStar77

**Comment by DimStar77** [comment]
Works for me - I'm rather afraid that it will stay disabled though (and amarok was one of the nice ones to catch mariadb issues, as strange as they might be every now and then)

**Comment by okurz** [comment]
-1

I think having disabled code around is not a good idea based on the same concerns @DimStar77 raised. 
What we can do though is having an early-return with record_soft_failure from the test module itself.

**Comment by coolo** [comment]
+1 to what @okurz said

**Comment by asmorodskyi** [comment]
softfailure instead ?

**Comment by okurz** [comment]
yes

**Pull request closed without merging**
