### PR TITLE
No '-p' parameter needed for SUSEConnect to activate base product on migrated system

### PR DESCRIPTION
**Pull request by lemon-suse**
- Related ticket: https://progress.opensuse.org/issues/153589
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/13262644

### CODE REVIEW

**Comment by hjluo** [comment]
LGTM

**Comment by tinawang123** [comment]
One question,  the registration with '-p' only failed at migrated system? 
For fresh  install system, we still need '-p' to register the system?
According the output information of 'SUSEConnect --list-extensions':  it need '-p' to do register:
Activate with: SUSEConnect -p sle-module-basesystem/15.6/x86_64

**Comment by lemon-suse** [comment]
> One question, the registration with '-p' only failed at migrated system? 
yes.

For fresh install system, we still need '-p' to register the system? 
yes

According the output information of 'SUSEConnect --list-extensions': it need '-p' to do register: Activate with: SUSEConnect -p sle-module-basesystem/15.6/x86_64

Please see developer's comments https://bugzilla.suse.com/show_bug.cgi?id=1217961#c8

**Review by rakoenig — APPROVED** [review]
LGTM.

**Pull request merged**
