### PR TITLE
Check dumps created via kdump with `crash` also on transactional systems

### PR DESCRIPTION
**Pull request by Martchus**
* Merge the basic check whether the `vmcore` file exists with the basic check that it is of non-zero size
* Invoke `crash` on transactional systems via `podman` using a Tumbleweed container (unless the installation of debuginfo was skipped because this seems to be required by `crash`)
* See https://progress.opensuse.org/issues/137891

---

VR: https://openqa.suse.de/tests/12576177

### CODE REVIEW

**Comment by Martchus** [comment]
The VR now fails to enable kdump (https://openqa.suse.de/tests/12576177#step/kdump/32). I actually saw this problem also sometimes locally but thought it was just a local problem; especially because it was not happening all the time. This failure is actually happening before the dump is checked and I also reproduced it locally before doing any changes to the test code. So it is unrelated to this PR but nevertheless something to look into.

**Review by okurz — APPROVED** [review]
I wonder if you have a ticket reference for further context

**Comment by Martchus** [comment]
I added the ticket reference to the commit message and PR description.

I was also able to conduct a successful VR after 2 retries: https://openqa.suse.de/tests/12597971

I also scheduled further test runs without my changes to cross-check. I could "unfortunately" not reproduce the failure anymore without my changes (but I could locally yesterday on my local machine). Since the failure is clearly happening before any of my changes come into place I'm still quite sure it is unrelated.

Interestingly, even on the good runs (without my changes) I saw a `kdump.service` related failure showing up in the boot logs while I was following the test closely in the live view, see https://openqa.suse.de/tests/12597965 (look for `Failed to start Load kdump kernel early on startup` and `Failed to start Load kdump kernel and initrd`). This is only not leading to a failure because at this point the test doesn't check the service's state anymore.

And just for the record, the failure this is about is:

grafik

**Comment by czerw** [comment]
Please do VR  on:
12-SP5: https://openqa.suse.de/tests/12584981
15-SP1: https://openqa.suse.de/tests/12565718
15-SP5: https://openqa.suse.de/tests/12566916
jeos: https://openqa.suse.de/tests/12584350

**Comment by Martchus** [comment]
See https://gitlab.suse.de/kernel-qa/kernelqa-openqa-yaml/-/merge_requests/393 for a fix of the mentioned failure.

---

VRs:

 - sle-12-SP5-Server-DVD-Updates-x86_64-Build20231019-1-mau-extratests-kdump@64bit -> https://openqa.suse.de/tests/12599995
 - sle-15-SP1-Server-DVD-Updates-x86_64-Build20231018-1-mau-extratests-kdump@64bit -> https://openqa.suse.de/tests/12599996
 - sle-15-SP5-Server-DVD-Updates-x86_64-Build20231018-1-mau-extratests-kdump@64bit -> https://openqa.suse.de/tests/12599997
 - sle-15-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20231019-1-jeos-kdump@uefi-virtio-vga -> https://openqa.suse.de/tests/12599998

**Pull request merged**
