### PR TITLE
DISA STIG test fix for BZ1194676

### PR DESCRIPTION
**Pull request by vtrubovics**
STIG test fix: error code fix and additional checks for number of passed/failed rules

- Related ticket: https://bugzilla.opensuse.org/show_bug.cgi?id=1194676
- Verification run: https://openqa.suse.de/tests/10312910

### CODE REVIEW

**Comment by paolostivanin** [comment]
Since stig is supposed to run also on aarch64 and s390x, could you please check that it works also on those archs?

Thanks Viktor!

**Review by paolostivanin — CHANGES_REQUESTED** [review]
I've executed stig on all archs using the code from your branch, but it fails on s390x and aarch64:

* https://openqa.suse.de/tests/10352680
* https://openqa.suse.de/tests/10352681

Could you please check and fix the issues? Thanks!

**Comment by vtrubovics** [comment]
> I've executed stig on all archs using the code from your branch, but it fails on s390x and aarch64:
> 
>     * https://openqa.suse.de/tests/10352680
> 
>     * https://openqa.suse.de/tests/10352681
> 
> 
> Could you please check and fix the issues? Thanks!

When I execute it on sle-15-SP5-Online-Build66.1-stig - tests are passing https://openqa.suse.de/tests/overview?distri=sle&version=15-SP5&build=66.1&groupid=268

https://openqa.suse.de/tests/10363949
https://openqa.suse.de/tests/10363951
https://openqa.suse.de/tests/10363954

The only issue I have is on ppc64le, but here it fails to boot to desktop:
https://openqa.suse.de/tests/10363953
I am running it using command:
openqa-clone-custom-git-refspec https://github.com/vtrubovics/os-autoinst-distri-opensuse/tree/Fix-BZ1194676 https://openqa.suse.de/tests/10340144 _SKIP_POST_FAIL_HOOKS=1 SCHEDULE=tests/installation/bootloader,tests/boot/boot_to_desktop,tests/security/stig/oscap_security_guide_setup,tests/security/stig/oscap_xccdf_eval,tests/security/stig/oscap_xccdf_remediate,tests/security/stig/oscap_xccdf_eval,tests/security/stig/baseline_comparison

Cow correctly to run it? 

Previously I also faced issue with apparmor rule failing when running qcow2 image from for example oscap test - looks apparmor service is disabled there during install.

**Comment by paolostivanin** [comment]
closing in favor of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16332

**Pull request closed without merging**
