### PR TITLE
Mu kubevirt test

### PR DESCRIPTION
**Pull request by tbaev**
This PR is related to gitlab [MR](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/228). It will enable the tests but there are some issues with the kubevirt part of the test that will need more attention. 

- Related ticket: https://progress.opensuse.org/issues/159516
- Needles: N/A
- Verification run:  done on gitlab [MR](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/228)

### CODE REVIEW

**Comment by tbaev** [comment]
@alice-suse after discussion with Nan we decided to split the scheduler file for 6.0 and 6.1. Changes are made in the [openqa-job-group-yaml](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/228/diffs?diff_id=289970&start_sha=c627c4645c336d1b73aafd4caf2cf2c3ff6a8e6e) PR too.

**Comment by nanzhg** [comment]
> @alice-suse after discussion with Nan we decided to split the scheduler file for 6.0 and 6.1. Changes are made in the [openqa-job-group-yaml](https://gitlab.suse.de/qa-testsuites/openqa-job-group-yaml/-/merge_requests/228/diffs?diff_id=289970&start_sha=c627c4645c336d1b73aafd4caf2cf2c3ff6a8e6e) PR too.

For slem6.0, should change back to usb boot in latest commit.

**Comment by nanzhg** [comment]
LGTM

**Comment by alice-suse** [comment]
Ok, looks good to me too. Thank you guys.

**Comment by alice-suse** [comment]
If no further comments from anyone, let's merge it by EOB today.

**Pull request merged**
