### PR TITLE
 Force test machine to boot to console mode 

### PR DESCRIPTION
**Pull request by qiangzhao**

### CODE REVIEW

**Comment by rwx788** [comment]
Here is description, problem is that in profile we don't define pattern for installation, whereas define target system as gnome. As a result we don't have x11 packages installed which leads to the [bsc#1046083](https://bugzilla.suse.com/show_bug.cgi?id=1046083). Once we have a warning message there we can implement a test which uses original profile and checks that warning is shown.

**Comment by okurz** [comment]
@rwx788 I don't get what you recommend. How should do what now?

**Comment by okurz** [comment]
@qiangzhao 
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. The subject line itself is too long and should not end with a dot

**Comment by rwx788** [comment]
@okurz There is still a discussion going on here: https://bugzilla.suse.com/show_bug.cgi?id=1046083
I suggest introducing this change and once warning message implemented to introduce another test which verifies that it is shown when profile has contradiction in selected patterns and target settings.

**Comment by qiangzhao** [comment]
@okurz 
Thanks for the advice. I have updated. 
Please re-review.

**Comment by okurz** [comment]
ok to me although I don't understand enough to approve it.

**Comment by rwx788** [comment]
@okurz The problem is that we don't define patterns for installation, hence base will be selected by default. But target system was gnome, which requires x11 to be installed, which is not there because of default patterns selection. This is a problem in profile. We agreed that warning has to be shown. See discussion in the [bsc#1046083](https://bugzilla.novell.com/show_bug.cgi?id=1046083)

**Comment by qiangzhao** [comment]
@rwx788 
I have re-checked this openQA case(https://openqa.suse.de/tests/1019958#step/first_boot/3),
And in my humble opinion, it doesn't involve any GUI function testing, So no-defined patterns installation without Xwindow or Gnome is fine for this.
I feel there's no problem with the pattern here. 
Regards.

**Comment by rwx788** [comment]
Test run on production: https://openqa.suse.de/tests/1074712

**Pull request merged**
