### PR TITLE
Disable parted prompts

### PR DESCRIPTION
**Pull request by rfan1**
- Related ticket:
 https://progress.opensuse.org/issues/112568 
 https://progress.opensuse.org/issues/112601
- Verification run: 
  http://openqa.suse.de/tests/8965344
  http://openqa.suse.de/tests/8970908
  http://openqa.suse.de/tests/8970909
  http://openqa.suse.de/tests/8970913

### CODE REVIEW

**Comment by rfan1** [comment]
@okurz @jknphy Please help review my PR, thanks much!

**Review by wangqianzou — APPROVED** [review]
LGTM

**Review by jknphy — APPROVED** [review]

**Review by jouyingbin — APPROVED** [review]

**Comment by rfan1** [comment]
> > Is there any plan to enhance this in other test cases instead of ONLY enhance current scenario?
> 
> ```
> tests/console/copy_iso_to_external_drive.pm:27:    assert_script_run "parted $disk mklabel gpt", 240;
> tests/console/copy_iso_to_external_drive.pm:28:    assert_script_run "parted -a opt $disk mkpart primary ext4 0% 50%", 240;
> tests/console/gpt_ptable.pm:18:    assert_script_run("parted -mls | grep '^/dev/.*:gpt:'", fail_message => 'no gpt partition table found');
> tests/console/validate_lvm.pm:95:                assert_script_run("parted $dev->{name} align-check optimal $i");
> ```

I would not change the codes within tests directory since it may have some risks :) thanks Wei!

**Review by okurz — APPROVED** [review]
I would appreciate if you can also fix the other calls of parted to be consistent

**Comment by rfan1** [comment]
> I would appreciate if you can also fix the other calls of parted to be consistent

Thanks Oliver, I will ping the maintainer of the test module offline and file a new ticket to track.

**Comment by rfan1** [comment]
@foursixnine 
Could you please help review this PR as well? since core team is using the test module as well.

**Review by coolgw — APPROVED** [review]

**Comment by okurz** [comment]
> Thanks Oliver, I will ping the maintainer of the test module offline and file a new ticket to track.

Well I meant you could simply prepare this yourself as it should be trivial changes and low risk of breaking. Test module maintainers can still be invited for the pull request review.

**Pull request merged**
