### PR TITLE
Move all mr_tests to use sec storage for SAP

### PR DESCRIPTION
**Pull request by mpagot**
Ticket TEAM-6943 TEAM-7142

Verification run:

* EC2 http://openqaworker15.qa.suse.cz/tests/135386   :  it is a clone of http://openqaworker15.qa.suse.cz/tests/135166 with manually changed HANA_ACCOUNT, HANA_CONTAINER,  HANA_TOKEN, HANA_CLIENT_SAR, HANA_SAPCAR and HANA_SAR
* GCE http://openqaworker15.qa.suse.cz/tests/135390 : it is a clone of https://openqa.suse.de/tests/10634612 with manually changed HANA_TOKEN HANA_CLIENT_SAR, HANA_SAPCAR and HANA_SAR
* AZ http://openqaworker15.qa.suse.cz/tests/135392 : it is a clone of http://openqaworker15.qa.suse.cz/tests/135260 with manually changed HANA_SAR,  HANA_SAPCAR, HANA_CLIENT_SAR and HANA_TOKEN

### CODE REVIEW

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by lilyeyes** [comment]
The code changes LGTM.

But I have concerns about adding these parameters may need to update some job groups' **Settings** accordingly too. 
Such as
1. Create MRs to add the following params to OSD repos:
**OSD maintenance job groups**: https://gitlab.suse.de/qa-css/openqa_ha_sap/-/tree/master/openQA/yaml_job_groups/maintenance
**OSD sles4sap 15sp5 job group**: https://gitlab.suse.de/qac/qac-openqa-yaml/-/blob/master/publiccloud/latest/ha_sap.yaml
2. Revise the job groups manually on OW15 (OW15 doesn't sync up code/metedata automatically)
**OW15 maintenance job groups**: https://openqaworker15.qa.suse.cz/group_overview/<21|22|23|24|28|29>
**OSD sles4sap 15sp5 job group**: https://openqaworker15.qa.suse.cz/group_overview/38

HANA_ACCOUN
HANA_CONTAINER
HANA_TOKEN
HANA_SAR
HANA_CLIENT_SAR
HANA_SAPCAR

And also we need to add the parameters manually for OW15 job groups

**Comment by lilyeyes** [comment]
The 2 MRs are ready too, and they should be merged at the same time with this PR:
MR (QAC OpenQA yaml): https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/1144
MR (openqa_ha_sap): https://gitlab.suse.de/qa-css/openqa_ha_sap/-/merge_requests/420

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by mpagot** [comment]
I just checked how/if this PR has meaningful code at version https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/48db2dcd766e394762b91f214777b961b9e4272f

I think it does:
```
% grep -rEL "apiver: 3" data/sles4sap/qe_sap_deployment

data/sles4sap/qe_sap_deployment/hanasr_azure.yaml
data/sles4sap/qe_sap_deployment/hanasr_ec2.yaml
data/sles4sap/qe_sap_deployment/hanasr_gcp.yaml
```


```
% grep -Lr az_sas_token data/sles4sap/qe_sap_deployment

data/sles4sap/qe_sap_deployment/hanasr_azure.yaml
data/sles4sap/qe_sap_deployment/hanasr_ec2.yaml
data/sles4sap/qe_sap_deployment/hanasr_gcp.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure.yaml
data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml
data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml
data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml
```

**Pull request closed without merging**
