### PR TITLE
Use pre-defined Alpine version instead of 'latest'

### PR DESCRIPTION
**Pull request by mnowaksuse**
`wget` from Alpine:3.6 ('latest' at the moment) fails to connect sites
on Hyper-V (likely a third party bug), so use version 3.5 which should
work everywhere. Also using pre-defined image makes the test more
predictable, than using latest and not immediately knowing which image
version was grabbed.

Once version 3.5 disappears from Docker store/hub, the version has to be
altered accordingly.

Used to faile here: https://openqa.suse.de/tests/1197043#step/docker/98
Verification run: http://assam.suse.cz/tests/602

@drpaneas @czerw Will gladly hear your opinions & reviews.

### CODE REVIEW

**Comment by okurz** [comment]
hm, kind of makes sense but then we have to update the version. Is there something like a "stable" version? If not, LGTM

**Comment by czerw** [comment]
@mnowaksuse I'm fine with suggested changes, if wget works with older versions.

**Comment by mnowaksuse** [comment]
@okurz `latest` is to my understanding supposed to be "stable"... There's also `edge` and firm versioned releases. I don't expect us to change te version often, oldest version in store is 3.1 which was released in 2014. Perhaps they keep the images there "indefinitely".
@czerw If you mean older versions of CaaSP or docker, it ought to.

**Comment by czerw** [comment]
@mnowaksuse  I meant older version of Alpine image, so all is fine.

**Comment by drpaneas** [comment]
Sorry for not replying earlier, I was on my way to Prague.

I would go with replace the `alpine` with `opensuse` container. In this way we could test `docker` and our docker opensuse `images` as well. In that case, if opensuse's `wget` fails, then I guess we can treat better than a 3rd party error.

`docker pull opensuse:tumbleweed`

what do you think?

**Comment by okurz** [comment]
the alpine image should be smaller, or not?

**Comment by mnowaksuse** [comment]
@okurz Yes, they are considerably bigger - just the download took me 2 minutes...
```
opensuse            tumbleweed          d91daea5a27f        2 weeks ago         101MB
opensuse            42.3                54ae12a89367        2 weeks ago         108MB
alpine              latest              7328f6f8b418        3 months ago        3.96MB
```
@drpaneas openSUSE images don't have `wget` nor `curl` included...
```
# docker run --rm opensuse:42.3  wget http://google.com
container_linux.go:247: starting container process caused "exec: \"wget\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"wget\": executable file not found in $PATH".
ERRO[0023] error getting events from daemon: context canceled 
```
But otherwise I find it a sensible idea to use our own dog food. Though anyway I would not use `opensuse:tumbleweed` as it probably is changing way to often (it should at least).

Strangely `alpine:3.6` is failing for me even on my Leap 42.3 desktop. `3.5` is just fine.
```
# docker run --rm alpine:3.6 wget http://google.com
Connecting to google.com (216.58.194.206:80)
wget: error getting response: Connection reset by peer
```
Can anyone confirm it? https://github.com/gliderlabs/docker-alpine/issues/344

**Comment by czerw** [comment]
This is strange, I tested  "docker run --rm alpine:3.6 wget http://google.com" on my:
* laptop with Tumbleweed: OK
* workstation in Prague with 12-SP2: fails as your example  with wget: error getting response: Connection reset by peer
* home desktop with Leap 42.3: OK as you can see bellow
```
phoenix:~ # docker run --rm alpine:3.6 wget http://google.com
Unable to find image 'alpine:3.6' locally
3.6: Pulling from library/alpine
88286f41530e: Pull complete 
Digest: sha256:f006ecbb824d87947d0b51ab8488634bf69fe4094959d935c0c103f4820a417d
Status: Downloaded newer image for alpine:3.6
Connecting to google.com (216.58.201.78:80)
Connecting to www.google.cz (172.217.18.99:80)
index.html           100% |*******************************| 11934   0:00:00 ETA

phoenix:~ # uname -a
Linux phoenix 4.4.87-25-default #1 SMP Wed Sep 13 07:19:13 UTC 2017 (3927ef5) x86_64 x86_64 x86_64 GNU/Linux
phoenix:~ # zypper info docker
Loading repository data...
Reading installed packages...


Information for package docker:
-------------------------------
Repository     : openSUSE-Leap-42.3-Update  
Name           : docker                     
Version        : 17.04.0_ce-33.11           
Arch           : x86_64                     
Vendor         : openSUSE                   
Installed Size : 40.6 MiB                   
Installed      : Yes                        
Status         : up-to-date                 
Source package : docker-17.04.0_ce-33.11.src
Summary        : The Linux container runtime
Description    :                            
    Docker complements LXC with a high-level API which operates at the process
    level. It runs unix processes with strong guarantees of isolation and
    repeatability across servers.

    Docker is a great building block for automating distributed systems: large-scale
    web deployments, database clusters, continuous deployment systems, private PaaS,
    service-oriented architectures, etc.
```

**Comment by vielmetti** [comment]
See https://git.busybox.net/busybox/commit/?id=a6f8651911716d1d1624712eb19e4f3608767c7e "wget: fix for brain-damaged HTTP servers. Closes 9471" which reports the underlying bug in busybox's wget.

**Pull request merged**
