### PR TITLE
podman_network_cni - change the image of container3 (fix on SLEM 5.1) and variable name $old_podman

### PR DESCRIPTION
**Pull request by mgrossu**
- Related ticket: https://progress.opensuse.org/issues/130507
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: https://openqa.suse.de/tests/11315729 (SLEM 5.1), https://openqa.suse.de/tests/11315734, https://openqa.suse.de/tests/11315787, https://openqa.suse.de/tests/11315767, https://openqa.suse.de/tests/11315769, https://openqa.opensuse.org/tests/3353042

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by pdostal — APPROVED** [review]

**Comment by grisu48** [comment]
Please test it in SLEM 5.1, where the issue that your are trying to fix is present. You can select a matching job from the [Maintenance: Test Repo/SLE Micro Maintenance Updates](https://openqa.suse.de/group_overview/420) job group on OSD. I'd recommend to use https://openqa.suse.de/tests/11305123

**Comment by mgrossu** [comment]
@grisu48 first VR: https://openqa.suse.de/tests/11315729 is for SLEM 5.1

**Comment by m-dati** [comment]
Please 2 kind questions only: 
why that variable rename supports_network in place of old_podman?
was the core change the nginx repo exclusion ?

**Comment by grisu48** [comment]
> why that variable rename supports_network in place of old_podman? 

Because that was asked by me in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16982#discussion_r1184937823 and probably got forgotten to be implemented there.

**Review by grisu48 — APPROVED** [review]

**Pull request merged**
