### PR TITLE
[WIP] Transactional server

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
**Important** Merge needles first!

- Related ticket: https://progress.opensuse.org/issues/42926
- **Needles**:
  - https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/987 (merged)
  - https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/994
- Verification run: http://slindomansilla-vm.qa.suse.de/tests/714

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
Relase notes also need changes

**Comment by SergioAtSUSE** [comment]
Ready to be reviewed

**Comment by okurz** [comment]
@sysrich I guess for Tumbleweed or Leap we do not need to handle the role selection differently because what @SergioAtSUSE adresses here is that within SLE based on the module selection the roles visible are differing. openSUSE has this all covered well already: https://openqa.opensuse.org/tests/791295#step/system_role/3

@SergioAtSUSE you don't have to come up with a special handling as alternative to the "default" screen. Compare to https://openqa.suse.de/tests/1772362#step/system_role/1 for the sles4sap which shows that we should accept whatever is selected as the "default" depending on the module selection.

needles merged

**Comment by SergioAtSUSE** [comment]
@sysrich, you can get here more context: https://progress.opensuse.org/issues/42107

I already verified that the test was already scheduled for openSUSE.

**Comment by SergioAtSUSE** [comment]
I will create another PR with the current test logic.
I will use this PR to make a proposal to check for specific expected system role (SAP, SLED, SLES + GNOME, Transactional Server, Textmode, Minimal, HA...)

**Comment by SergioAtSUSE** [comment]
When applying @okurz's proposal, I realized that the current logic also check that the expected system role is selected.

**Pull request closed without merging**
