### PR TITLE
Public Cloud: Fix terraform for Azure

### PR DESCRIPTION
**Pull request by pdostal**
After we updated terraform we have problems destroying Azure instances.

- Related ticket: [poo#108518](https://progress.opensuse.org/issues/108518)
- Failed job: [OSD](https://openqa.suse.de/tests/8340177)
- Verification run: [15-SP3](http://pdostal-server.suse.cz/tests/13865) [15-SP4](http://pdostal-server.suse.cz/tests/13866#)

### CODE REVIEW

**Review by asmorodskyi — CHANGES_REQUESTED** [review]
it is not gonna work for product runs , we not always using "offer" sometimes we use images manually uploaded and than we specifying image id

**Review by grisu48 — APPROVED** [review]
LGTM! But the VRs are still missing

**Comment by pdostal** [comment]
> it is not gonna work for product runs , we not always using "offer" sometimes we use images manually uploaded and than we specifying image id

```terraform
offer     = var.image_id != "" ? "" : var.offer
sku       = var.image_id != "" ? "" : var.sku
```
This will in my opinion be `""` for uploaded image.

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Pull request merged**
