### PR TITLE
data/journal_check/bug_refs.json: boo#1188270 also applies to 15.3

### PR DESCRIPTION
**Pull request by Vogtinator**
- Verification run: https://openqa.opensuse.org/tests/1847356

### CODE REVIEW

**Comment by ggardet** [comment]
The only issue I can see atm on RPi3 for 15.3 is https://openqa.opensuse.org/tests/1844021#step/journal_check/10 which is related to IRQ, not Ethernet.

**Comment by Vogtinator** [comment]
> The only issue I can see atm on RPi3 for 15.3 is https://openqa.opensuse.org/tests/1844021#step/journal_check/10 which is related to IRQ, not Ethernet.

That's 15.2, but should also get added to the list. Is that reported somewhere already?

**Comment by ggardet** [comment]
> > The only issue I can see atm on RPi3 for 15.3 is https://openqa.opensuse.org/tests/1844021#step/journal_check/10 which is related to IRQ, not Ethernet.
> 
> That's 15.2, but should also get added to the list. Is that reported somewhere already?

Ah yes, but your VR is with 15.2. 

I thought the IRQ issue was taken into account already, but I cannot find it atm.

**Review by ggardet — APPROVED** [review]

**Comment by Vogtinator** [comment]
> > > The only issue I can see atm on RPi3 for 15.3 is https://openqa.opensuse.org/tests/1844021#step/journal_check/10 which is related to IRQ, not Ethernet.
> > 
> > 
> > That's 15.2, but should also get added to the list. Is that reported somewhere already?
> 
> Ah yes, but your VR is with 15.2.

Indeed, I copied the wrong URL...

> I thought the IRQ issue was taken into account already, but I cannot find it atm.

If you can't find it, can you file a new report?

**Pull request merged**
