### PR TITLE
Fix container test on CentOS

### PR DESCRIPTION
**Pull request by Vogtinator**
Fix serial_terminal with older versions of bash:

Some older versions of bash don't take terminal geometry changes during runtime
into account. To work around that, re-exec the shell after adjusting the width.

This caused validation of typed commands to fail and such it ran into the 90s timeout for each, delaying the test progress significantly. Until now, the CentOS test took ~55min to complete!
With the recent change to `host_configuration` in #12507, it got even more confused and the test failed completely.
With this PR, the test works reliably and passes in less than 5min.

Also set test flags for `containers/host_configuration`.

Verification runs:
TW container on CentOS: http://10.160.67.86/tests/954 https://openqa.opensuse.org/tests/1736131
Container tests on 15.2: https://openqa.opensuse.org/tests/1736516

Touches serial_terminal, so probably needs more VRs. Any wishes?

### CODE REVIEW

**Comment by Vogtinator** [comment]
IMO `serial_output` should fail when any of the `testapi::wait_serial` calls inside fails, that would've made this failure more obvious.

**Comment by b10n1k** [comment]
i still wonder if the `host_configuration needs to have `disable_serial_getty` in case of an old kernel. the centos has `4.18`. for the perlpod the usage of this function is intended for `<4.20`. 
```Serial getty service pollutes serial output with login prompt, which                                                                                                                                                                                                           
interferes with the output, e.g. when calling C<script_output>.                                                                                                                                                                                                                
Login prompt messages on serial are used on some remote backend to                                                                                                                                                                                                             
identify that system has been booted, so do not mask on non-qemu backends.                                                                                                                                                                                                     
This is only necessary for Linux < 4.20.4 so skipped on more recent versions```
wdyt?

**Comment by Vogtinator** [comment]
I think that is actually only relevant for the case where you type commands over VNC and expect output over serial, i.e. `cat foobar >/dev/ttyS0`.
This uses serial_terminal for both and thus uses the login prompt on `hvc0`.

**Review by b10n1k — APPROVED** [review]
+1 and thanks

**Review by jlausuch — APPROVED** [review]

**Pull request merged**
