### PR TITLE
[WIP] Enable perlcritic tests as part of tests

### PR DESCRIPTION
**Pull request by okurz**
This change is [Reviewable](https://reviewable.io/reviews/os-autoinst/os-autoinst-distri-opensuse/1516)

### CODE REVIEW

**Comment by coolo** [comment]
you can snipe off perlcritic per line by adding a comment - we have the same in os-autoinst in places where we really want eval ""

**Comment by aaannz** [comment]
:+1:  as soon as travis passes.

**Comment by coolo** [comment]
Seeing the regressions in perlcritic, I think it's about time we act. Your approach outdated itself, so I suggest https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1904 as first aid

**Comment by okurz** [comment]
updated. Current left failures:

```
lib/susedistribution.pm: Hash key with quotes at line 110, column 14.  Avoid useless quotes.  (Severity: 4)
lib/x11regressiontest.pm: Package declaration must match filename at line 10, column 1.  Correct the filename or package statement.  (Severity: 5)
lib/x11test.pm: Package declaration must match filename at line 1, column 1.  Correct the filename or package statement.  (Severity: 5)
script/import-slenkins-testsuite.pl: Expression form of "eval" at line 108, column 26.  See page 161 of PBP.  (Severity: 5)
script/import-slenkins-testsuite.pl: Expression form of "eval" at line 114, column 22.  See page 161 of PBP.  (Severity: 5)
tests/slepos/run_posInitBranchserver.pm: Code before strictures are enabled at line 18, column 1.  See page 429 of PBP.  (Severity: 5)
tests/slepos/run_possyncimages.pm: Code before strictures are enabled at line 18, column 1.  See page 429 of PBP.  (Severity: 5)
tests/slepos/zypper_install_adminserver.pm: Code before strictures are enabled at line 18, column 1.  See page 429 of PBP.  (Severity: 5)
```

The first I don't understand. Line 110 of lib/susedistribution.pm says `send_key 'ret';` Why is perlcritic seeing this as hash key?

**Comment by coolo** [comment]
same with the next 2. IMO the package name *is* the filename.

**Comment by coolo** [comment]
ok, that one I debugged - the 11 in the package name splits the tokens and as such the test fails

**Comment by coolo** [comment]
and using send_key('ret'); will avoid the misparsing there

**Comment by coolo** [comment]
we should be green now - but if we add this we should remove what I did in 1904

**Comment by coolo** [comment]
(or we leave only 1904 - in favor of faster travis)

**Pull request closed without merging**
