### PR TITLE
Optimize Docker test for MicroOS worker

### PR DESCRIPTION
**Pull request by drpaneas**
The Docker test was assuming that it runs in a clean environment
where there are no docker containers running. This is not true
for CaaSP since there is a number of containers running
depending on the role of the node. As a result, this commit
replaces hardcoded numerical checks with actual verification
based on IDs and container names.

### CODE REVIEW

**Comment by drpaneas** [comment]
@sysrich pointed me into the [failure of Docker test](http://ibrokeit.suse.de/tests/59#) in respect of CaaSP worker. Hopefully, this commit fixes this issue.

* it passes in TW: http://ultron.suse.de/tests/627#step/docker/104
* it passes in CaaSP: http://ultron.suse.de/tests/625#step/docker/104

Since I changed nearly the whole test (the way of verification) I would like the maintainers @flavio @czerw to have also a look and review it if it's possible.

**Comment by czerw** [comment]
All looks fine, it can be merged.

**Comment by flavio** [comment]
LGTM

**Comment by mitiao** [comment]
Please fix the conflicts

**Comment by drpaneas** [comment]
Hmmm ... are you sure you _still_ want to merge my PR? If so, then may I ask why did you guys merge PR#3568 a few hours ago? This one fixes the test to work in CaaSP worker (_the same problem that this PR also deals with_) but it continues to use numerical comparisons while my solution uses another approach using verification based on IDs and container names.

Please decide which approach you want ... either revert the changes (conflicts) or close this PR. 

FYI: The previously merged PR also introduced a wrong behavior in terms on network testing ... containers can reach the outside world but outside world should not be able to reach them unless you say so in k8s (e.g. node-port).

**Comment by sysrich** [comment]
I want your version of the PR, yes, because I think it's a LOT more robust, especially in the context of Kubic

Images = 13 does not work in all cases for CaaSP, and does not work at all in Kubic.. if I had reviewed #3568 I would have veto'd it as it's broken all of my Kubic tests

@mnowaksuse can you please work with @drpaneas to untangle this mess?

**Comment by mnowaksuse** [comment]
@drpaneas I suggest you make revert of 453bc1eb7b3d60f4ee67c4d308d357979ad1eadc part of your PR (just the `tests/console/docker.pm` changes if possible).

**Comment by drpaneas** [comment]
@mnowaksuse ok I rebased it, it should be OK by now. Could you have a look?

Sadly, I can't provide a link because the test now breaks at [oci_password](http://ultron.suse.de/tests/632#step/oci_password/2). I will comment on your PR to have on a look on that.

**Pull request merged**
