### PR TITLE
kontact: Handle first-time dialog as optional (fixes regression from ab2acecc)

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by nilxam** [comment]
launch kontact before modify the configuration file seems strange to me.

**Comment by okurz** [comment]
yeah, that's wrong. let me recheck. But, what do you prefer: Disable the startup assistant or just try to handle it correctly as we already do for kontact5 since ever

**Comment by okurz** [comment]
fixed

**Comment by DimStar77** [comment]
LGTM

**Comment by nilxam** [comment]
> yeah, that's wrong. let me recheck. But, what do you prefer: Disable the startup assistant or just try to handle it correctly as we already do for kontact5 since ever

this PR looks good to me, I think https://github.com/os-autoinst/os-autoinst-distri-opensuse/issues/2818 is mainly to workaround boo#1036736, IMO it's fine that KDE team decided to not testing the first time assistant.

**Comment by nilxam** [comment]
Anyway we never ever test the functional of the first time assistant, instead just close the dialog. so let's merge this.

**Pull request merged**
