### PR TITLE
Replace flaky html5test.com with openSUSE internal ressource

### PR DESCRIPTION
**Pull request by okurz**
Verification run: http://lord.arch/tests/390

Related needle PR:
https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/310

Related progress issue: https://progress.opensuse.org/issues/14848

### CODE REVIEW

**Comment by okurz** [comment]
@dasantiago

**Comment by coolo** [comment]
https://html5test.opensuse.org/ not static.opensuse.org

**Comment by okurz** [comment]
updated with html5test.opensuse.org

**Comment by dasantiago** [comment]
LGTM

**Comment by coolo** [comment]
happy sle needling :)

**Pull request merged**
