### PR TITLE
Fix poo#20454: Run finger and telnet over systemd

### PR DESCRIPTION
**Pull request by pevik**
See https://progress.opensuse.org/issues/20454

I tested this patch in:
* Tumbleweed x86_64
* sle-12-SP3 x86_64
* Tumbleweed ppc64le

### CODE REVIEW

**Comment by pevik** [comment]
@richiejp Please merge this fix

**Comment by okurz** [comment]
checks failed, "qw should be used as function at […].  use qw(A B).". You can also run `make test` locally to check for this.

**Comment by pevik** [comment]
@okurz Fixed now. It was space before bracket ('qw ('. FYI I do run it each time on updated os-autoinst. But it didn't find it locally, I wonder what I do wrong.

**Comment by okurz** [comment]
+1

I don't know why it could not reproduced locally unless some differences in perl package versions?

**Comment by richiejp** [comment]
On Tumbleweed it is Perl version 5.24 while Travis is using 5.18. So possibly the parsing rules have been relaxed.

**Comment by pevik** [comment]
I'd be surprised if `perltidy` changed that much over releases (and I consider not finding space between function name and bracket as a bug), but yeh, it might be.

**Comment by pevik** [comment]
Thanks for merging.

**Pull request merged**
