### PR TITLE
Don't overly use become_root - just go to root-console

### PR DESCRIPTION
**Pull request by coolo**
This avoids permission problems and is a bit more what users
would do actually

### CODE REVIEW

**Comment by nilxam** [comment]
LGTM

**Comment by okurz** [comment]
What permission problems would this solve? I don't think this is more near to what users would do. I would stick with the "sudo" calls as it should be more obvious which part is actually done as root. If the root-console is selected then the test writer and reviewer has to follow when the block ends or when another console is selected again. Only if we would change the "select root console" to something enclosing with curly braces this would be better readable

**Comment by coolo** [comment]
take https://openqa.opensuse.org/tests/115924 as example. What user would login as user account to run 20 jobs with sudo each? Not me at least

**Comment by coolo** [comment]
and the permission problem is about /dev/ttyS0

**Comment by okurz** [comment]
fine by me. Please reference what it fixes about the permission problems in the commit message then

**Comment by okurz** [comment]
then auto-LGTM

**Comment by DimStar77** [comment]
I don't like that tests no longer 'end' in the state they started.

Example: zypper_add_repo old:
statred on user console (presumed.. no guarantee), elevated privileges, does it's thing, leaves privileged mode => status as was at the beginning

New:
* we switch to another tty
* do our thing
* stay where we are

so the follow up test, even if it wanted 'user' permissions - will have to ensure to switch to user permissions - it can't just assume it anymore (ok, assuming is a bad thing to start with in this case.. but we might have quite some strange things)

**Comment by coolo** [comment]
yes, we need to mark now in every test what console it expects - instead of assuming anything. Working on this

**Comment by DimStar77** [comment]
in this case :+1: it makes the tests even more robust and defined, as they no longer 'change' depending on test order in main.pm

**Comment by sysrich** [comment]
+1 given the caveats already discussed

**Comment by coolo** [comment]
@DimStar77  98a3bab

**Pull request merged**
