### PR TITLE
Comment inclusion of /etc/named.conf.include on /etc/named.conf

### PR DESCRIPTION
**Pull request by alvarocarvajald**
After f8f29e9267e67f251ecda4a8661f6add707fbf69, whenever the `support_server/setup` module runs on migration scenarios (where the support server itself was configured by a previous job), named fails to start because the file `/etc/named.d/openqa.zones` gets included twice into the configuration:

First by the existing `/etc/named.conf`, which has a line including the file `/etc/named.conf.include`, which eventually includes `/etc/named.d/openqa.zones`.

Second by the changes submitted in f8f29e9267e67f251ecda4a8661f6add707fbf69 which explicitly include `/etc/named.d/openqa.zones` into `/etc/named.conf`.

This commit adds a workaround for such cases, by commenting in `/etc/named.conf` the inclusion of `/etc/named.conf.include` when the module runs on a support server which was previously configured by the `support_server/setup` module.

- Related ticket: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17108 & https://jira.suse.com/browse/TEAM-8779
- Needles: N/A
- Verification runs:

1. HA Migrations on x86_64: [node1](https://openqa.suse.de/tests/12941839), [node2](https://openqa.suse.de/tests/12941840), [supportserver](https://openqa.suse.de/tests/12941841#step/setup/7)
2. HA Migrations on aarch64: [node1](https://openqa.suse.de/tests/12942029), [node2](https://openqa.suse.de/tests/12942024), [supportserver](https://openqa.suse.de/tests/12942027#step/setup/7)
3. HA Migrations on ppc64le: [node1](https://openqa.suse.de/tests/12942796), [node2](https://openqa.suse.de/tests/12942797), [supportserver](https://openqa.suse.de/tests/12942795#step/setup/7) (failure is unrelated to this PR)
4. HA non-Migration: [node1](https://openqaworker15.qa.suse.cz/tests/272045), [node2](https://openqaworker15.qa.suse.cz/tests/272048), [supportserver](https://openqaworker15.qa.suse.cz/tests/272047#step/setup/7)

### CODE REVIEW

**Review by mpagot — APPROVED** [review]
LGTM

**Review by b10n1k — COMMENTED** [review]
My opinion is to not apply this in `setup_dns_server`. 
one place for it would be the `pre_run_hook`.  There we could apply any cleanup or workaround, leaving the other function clean and tidy.
Also I am thinking that the setup_dns_server will run only if `SUPPORT_SERVER_ROLES` contains `dns`. isnt it more easy to modify the job variable of those tests?

**Review by czerw — APPROVED** [review]

**Comment by alvarocarvajald** [comment]
> My opinion is to not apply this in `setup_dns_server`. one place for it would be the `pre_run_hook`. There we could apply any cleanup or workaround, leaving the other function clean and tidy. Also I am thinking that the setup_dns_server will run only if `SUPPORT_SERVER_ROLES` contains `dns`. isnt it more easy to modify the job variable of those tests?

Well, I added it in `setup_dns_server()` as it's dealing with named configuration files, but during my manual tests both doing this before and after static network setup worked, so I have no problems with moving this to `pre_run_hook`. I'll apply your suggestion and add verification runs for migration and non-migration HA jobs. Let me know if I should add verification runs for something else.

**Comment by alvarocarvajald** [comment]
Removed WIP label and added verification runs.

**Comment by b10n1k** [comment]
> > My opinion is to not apply this in `setup_dns_server`. one place for it would be the `pre_run_hook`. There we could apply any cleanup or workaround, leaving the other function clean and tidy. Also I am thinking that the setup_dns_server will run only if `SUPPORT_SERVER_ROLES` contains `dns`. isnt it more easy to modify the job variable of those tests?
> 
> Well, I added it in `setup_dns_server()` as it's dealing with named configuration files, but during my manual tests both doing this before and after static network setup worked, so I have no problems with moving this to `pre_run_hook`. I'll apply your suggestion and add verification runs for migration and non-migration HA jobs. Let me know if I should add verification runs for something else.

**Pull request merged**
