### PR TITLE
save_y2logs - Don't use regexs in wait serial - no point checking for…

### PR DESCRIPTION
**Pull request by sysrich**
… errorcode if the echo is only sent on successful execute

### CODE REVIEW

**Comment by coolo** [comment]
I think the point is the die, no?

**Comment by coolo** [comment]
now you will try to upload a file that is not existant

**Comment by sysrich** [comment]
No I wont.. bash 101, because it's after && echo will only be executed if the save_y2logs returns zero exit status

Without the echo, the wait serial will fail, the test will die, the upload won't run..

**Comment by lnussel** [comment]
wait_serial doesn't die and the && leads to unnecessary timeouts in the error case. That kind of code is the reason why I came up with assert_script_run. What kind of issue did you have with the code? AFAICS it's correct.

**Comment by sysrich** [comment]
the s390 backend cannot handle the undefined \d+

https://openqa.suse.de/tests/94621/file/autoinst-log.txt

**Comment by coolo** [comment]
I don't know what exactly is deployed, but I wonder why it runs into the array dereferencing - susanne added extra code for BACKEND eq s390x

**Comment by sysrich** [comment]
I deployed the latest of everything late on Friday when the merge of the tests requiring the new test API was accepted

**Comment by coolo** [comment]
But the error is not about the regexp. The problem is that the expect_x3270 returns undef:

post_fail_hook failed: Can't use an undefined value as an ARRAY reference at /usr/lib/os-autoinst/bmwqemu.pm line 546.

**Comment by lnussel** [comment]
https://github.com/os-autoinst/os-autoinst/blob/master/bmwqemu.pm#L546 uses $r even in case of exception ie when $@ is set.

**Comment by lnussel** [comment]
closing. looks like this should be fixed in os-autoinst.

**Pull request closed without merging**
