### PR TITLE
Rewrite opensuse_welcome_applicable and return 0 for the TW aarch64 KDE Live

### PR DESCRIPTION
**Pull request by Vogtinator**
- Related ticket: https://progress.opensuse.org/issues/157174
- Verification run: https://openqa.opensuse.org/tests/4414961#live

### CODE REVIEW

**Comment by DimStar77** [comment]
Smells like being responsible for
https://openqa.opensuse.org/tests/4419666#investigation

opensuse-welcome is no longer being handled

**Comment by Vogtinator** [comment]
> Smells like being responsible for
> 
> * https://openqa.opensuse.org/tests/4419666#investigation
> * https://openqa.opensuse.org/tests/4419667#step/shutdown/1
> 
> opensuse-welcome is no longer being handled

Looks like that is because of DESKTOP=minimalx. How did that even work previously?

**Comment by Vogtinator** [comment]
Oh, I see - it's passing the new desktop as parameter:

```
        loadtest "x11/${de}_reconfigure_openqa";
        loadtest "x11/reboot_icewm";
        loadtest "installation/opensuse_welcome" if opensuse_welcome_applicable($de);
```

Maybe it could just do `set_var("DESKTOP", $de)`?

**Comment by Vogtinator** [comment]
> Oh, I see - it's passing the new desktop as parameter:
> 
> ```
>         loadtest "x11/${de}_reconfigure_openqa";
>         loadtest "x11/reboot_icewm";
>         loadtest "installation/opensuse_welcome" if opensuse_welcome_applicable($de);
> ```
> 
> Maybe it could just do `set_var("DESKTOP", $de)`?

It can! Needs some extra code for setting the desktop to the original one again before actually starting the test, so something for later. Until then: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20016

**Pull request merged**
