### PR TITLE
Use key press instead of asset_and_click

### PR DESCRIPTION
**Pull request by dzedro**
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/merge_requests/1179
- Verification run:
http://10.100.12.155/tests/12647#step/scc_registration/22 - textmode
http://10.100.12.155/tests/12646#step/scc_registration/121
https://openqa.suse.de/tests/3027052#step/scc_registration/22 - textmode s390x
https://openqa.suse.de/tests/3027044#step/scc_registration/20 - textmode ppc64le
- two addons
http://10.100.12.155/tests/12648#step/scc_registration/30
http://10.100.12.155/tests/12650#step/scc_registration/27
http://10.100.12.155/tests/12649#step/scc_registration/27 (changed order of previous addons)
http://10.100.12.155/tests/12465#step/patch_sle/107 - textmode
http://10.100.12.155/tests/12470#step/register_system/29 - textmode
- three addons
http://10.100.12.155/tests/12497#step/scc_registration/52
http://10.100.12.155/tests/12498#step/scc_registration/54 (changed order of previous addons)
http://10.100.12.155/tests/12460#step/scc_registration/51
http://10.100.12.155/tests/12464#step/register_system/32 - textmode
http://10.100.12.155/tests/12472#step/register_system/46 (changed order of previous addons)

### CODE REVIEW

**Comment by dzedro** [comment]
it does work, mostly is needed just one/two tab to get from next button to code field (sometimes over release notes) and the addons are in order as we have them defined in openQA

**Comment by rwx788** [comment]
Yeah, that's the thing, I cannot guarantee that we have correct order for all of them in openQA. Meaning that it might break some tests, where the list is not in order you expect.
So I don't understand motivation for it. You don't want to create new needles for new test? As your MR for needles doesn't clean it up to have just 2 needles which should be enough if we have single tag. One for ncurses and one for qt.

**Comment by dzedro** [comment]
To clarify list of registration codes is as we add them, order is set. Motivation are problems with assert_and_click, yesterday I was helping colleague working on SES and i had to spend some time to make it work, the problem was of course needle and I remember @mloviska working on RT and having the same issue which he fixed for RT but broke other registrations.
Having less needles, generic needles is better. I don't think that there can be any issue with generic needle for code field. I don't understand what do you mean with 'your MR for needles doesn't clean it up to have just 2 needles', more than 30 needles are replaced with 4.

**Comment by dzedro** [comment]
Updated & added test run with multiple addons

**Comment by rwx788** [comment]
> To clarify list of registration codes is as we add them, order is set. Motivation are problems with assert_and_click, yesterday I was helping colleague working on SES and i had to spend some time to make it work, the problem was of course needle and I remember @mloviska working on RT and having the same issue which he fixed for RT but broke other registrations.
> Having less needles, generic needles is better. I don't think that there can be any issue with generic needle for code field. I don't understand what do you mean with 'your MR for needles doesn't clean it up to have just 2 needles', more than 30 needles are replaced with 4.

My bad, I haven't scrolled longer for it.

The scenario I'm talking about: imagine, `@scc_addons` contains addons a,b,c,d.
But regcode fields are in different order (b,c,d,a). With your current code we then will enter wrong regcode to the textfield. This can be fixed by setting variable accordingly, but I'm not sure how many scenarios are affected (if at all).

**Comment by dzedro** [comment]
> > To clarify list of registration codes is as we add them, order is set. Motivation are problems with assert_and_click, yesterday I was helping colleague working on SES and i had to spend some time to make it work, the problem was of course needle and I remember @mloviska working on RT and having the same issue which he fixed for RT but broke other registrations.
> > Having less needles, generic needles is better. I don't think that there can be any issue with generic needle for code field. I don't understand what do you mean with 'your MR for needles doesn't clean it up to have just 2 needles', more than 30 needles are replaced with 4.
> 
> My bad, I haven't scrolled longer for it.
> 
> The scenario I'm talking about: imagine, `@scc_addons` contains addons a,b,c,d.
> But regcode fields are in different order (b,c,d,a). With your current code we then will enter wrong regcode to the textfield. This can be fixed by setting variable accordingly, but I'm not sure how many scenarios are affected (if at all).

As you can see in updated verification  runs, regcode fields will be not in different order, order is not random it's equal to order as the addons were added.

**Pull request closed without merging**
