### PR TITLE
install_windowmanager: Delete unused module after ac083e8

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by sysrich** [comment]
Failed Checks :(

**Comment by okurz** [comment]
yes, its the reason I pulled out this PR from the other changes. I assume the "check maintainer" test wants to see the maintainer and summary being "present" after the commit which can by definition not be the case when deleting a module. After #2022 we should probably just accept it and override the check.

**Comment by coolo** [comment]
the checks are fixed - but you need to rebase too

**Comment by okurz** [comment]
replaced by #2070

**Pull request closed without merging**
