### PR TITLE
Add data/microos/utt-opensuse-ppc64le.tgz poo#69445

### PR DESCRIPTION
**Pull request by michelmno**
tarball manually created:
```
===
$osc getbinaries openSUSE:Factory:PowerPC update-test-trivial standard ppc64le
$cd binaries; rm -rf _buildenv rpmlint.log _statistics update-test-32bit*rpm; cd ..
$mv binaries  update-test-trivial
$tar -czf utt-opensuse-ppc64le.tgz update-test-trivial
===
$tar -tzf utt-opensuse-ppc64le.tgz
update-test-trivial/
update-test-trivial/update-test-affects-package-manager-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-broken-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-feature-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-interactive-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-optional-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-reboot-needed-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-relogin-suggested-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-retracted-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-security-5.1-1.1.ppc64le.rpm
update-test-trivial/update-test-trivial-5.1-1.1.ppc64le.rpm
===
```

Need to update rpmver in lib/transactional.pm
to match rpms in utt-opensuse-ppc64le.tgz

- Related ticket: https://progress.opensuse.org/issues/69445
- Needles: none
- Verification run: TW 20200916 ppc64le https://openqa.opensuse.org/tests/1397014#step/transactional_update/8 (ignore zypper_ref failure that was another problem)

### CODE REVIEW

**Comment by michelmno** [comment]
I do not understand the cause of above travis failure:
"continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error"
There is no obvious reason in detailed log

**Comment by jknphy** [comment]
> I do not understand the cause of above travis failure:
> "continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error"
> There is no obvious reason in detailed log

Hi @michelmno, I restarted, it seems some temporal glitch in Travis (now and then happens).
Does it work with this tarball? do you have some verification run?

**Comment by michelmno** [comment]
> > I do not understand the cause of above travis failure:
> > "continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error"
> > There is no obvious reason in detailed log
> 
> Hi @michelmno, I restarted, it seems some temporal glitch in Travis (now and then happens).
> Does it work with this tarball? do you have some verification run?

I did a test 2 weeks ago with this tarball, but it was still failing.
Unfortunately I did not captured new data, So will have to setup my env to retry test, will try that before end of next week.

**Comment by michelmno** [comment]
@jknphy FYI  last changes verified with success.

**Comment by jknphy** [comment]
> @jknphy FYI last changes verified with success.

great!, do you have a link?

**Comment by michelmno** [comment]
> > @jknphy FYI last changes verified with success.
> 
> great!, do you have a link?

no link as local to IBM intranet, no SUSE.

**Comment by jknphy** [comment]
> > > @jknphy FYI last changes verified with success.
> > 
> > 
> > great!, do you have a link?
> 
> no link as local to IBM intranet, no SUSE.

But if you have the package then we can just use `openqa-clone-custom-git-refspec` to see result of the test suite in O3, right?
There we can know for sure if it works, wdyt? Maybe requires some setup of the test suite, but would be very similar than for aarch/x86_64 I guess. It could be added to development group at the beginning. wdyt?

**Comment by michelmno** [comment]
> But if you have the package then we can just use `openqa-clone-custom-git-refspec` to see result of the test suite in O3, right?
> There we can know for sure if it works, wdyt? Maybe requires some setup of the test suite, but would be very similar than for aarch/x86_64 I guess. It could be added to development group at the beginning. wdyt?

good point I will do the setup in o3, and will let you know.

**Comment by michelmno** [comment]
> > But if you have the package then we can just use `openqa-clone-custom-git-refspec` to see result of the test suite in O3, right?
> > There we can know for sure if it works, wdyt? Maybe requires some setup of the test suite, but would be very similar than for aarch/x86_64 I guess. It could be added to development group at the beginning. wdyt?
> 
> good point I will do the setup in o3, and will let you know.

clone_job.pl would partially work, but not sufficient as unable to download related iso to o3.

**Comment by michelmno** [comment]
On hold, 
waiting for changes to trigger related openqa test on o3  https://github.com/os-autoinst/openqa-trigger-from-obs/pull/94

**Comment by michelmno** [comment]
> On hold,
> waiting for changes to trigger related openqa test on o3 [os-autoinst/openqa-trigger-from-obs#94](https://github.com/os-autoinst/openqa-trigger-from-obs/pull/94)

That one was merged on 20200917.

now that scenario available on o3 https://openqa.opensuse.org/tests/1396936#step/transactional_update/9
pending validation at https://openqa.opensuse.org/tests/1397014#step/transactional_update/8
should ignore the zypper_ref failure that is another problem.

**Comment by jknphy** [comment]
LGTM, good job!

**Pull request merged**
