### PR TITLE
spec: Add Recommends for os-autoinst

### PR DESCRIPTION
**Pull request by okurz**
os-autoinst-distri-opensuse tests actually require os-autoinst to run so
it is correct to specify that requirement although there was no
immediate problem to fix.

### CODE REVIEW

**Comment by asdil12** [comment]
I am against this, as it might break development setups.
When having only `os-autoinsst-distri-opensuse` but not `os-autoinst` installed, because you are running `os-autoinst` from git, this would install the useless `os-autoinst` RPM which might even lead to conflicts.

**Comment by okurz** [comment]
That is in principle true for every dependency. I see the use case but do not see the conflicts or the difference to other packages. We can at least "recommend" it though. Should I do that instead?

**Comment by asdil12** [comment]
A recommend is fine as it doesn't force the developer to keep `os-autoinsst` installed.

**Comment by okurz** [comment]
ok, updated accordingly.

**Pull request merged**
