### PR TITLE
Workaround boo#1091353: fallback pkcon to zypper

### PR DESCRIPTION
**Pull request by asdil12**
Verification run: http://artemis.suse.de/tests/297

### CODE REVIEW

**Comment by kravciak** [comment]
For easier review please link verification run to specific needle / serial output (http://artemis.suse.de/tests/297#step/wine/17)?

Bug points to missing inkscape package, I don't see that in verification run
 - https://openqa.opensuse.org/tests/658802#step/inkscape/12

**Comment by asdil12** [comment]
The bug also appears in other modules.
The code change was only in the ensure_installed function that is used in all of this modules (eg. wine or steam).

**Comment by okurz** [comment]
s/pkgcon/pkcon/

**Comment by asdil12** [comment]
@okurz thanks, corrected.

**Comment by okurz** [comment]
did you try to verify that the workaround actually works? Your one verification run did not show the original problem

**Comment by asdil12** [comment]
That is the problem with sporadic issues... - I'll schedule a number of jobs...

**Comment by asdil12** [comment]
I scheduled job 305 - 324 on artemis.

**Comment by kravciak** [comment]
Maybe you can fake failure by changing code a bit (installing package that does not exist...)

**Comment by asdil12** [comment]
I patched the testcode a bit to force the error and got this nice verification run: http://artemis.suse.de/tests/330#step/wine/25

Essentially I tried to install `nonexistingpkg` using pkcon and then successfully installed `wine` using zypper.

**Comment by okurz** [comment]
Very nice, thx

**Pull request merged**
