### PR TITLE
Update expected output for 'docker search opensuse'

### PR DESCRIPTION
**Pull request by Vogtinator**
Fixes poo#47324

- Verification run: http://10.160.67.86/t310

### CODE REVIEW

**Comment by Vogtinator** [comment]
I put another fix on top - will provide link to verification run once ready.

**Comment by Vogtinator** [comment]
There, green: * Verification run: http://10.160.67.86/t311

**Comment by okurz** [comment]
+1

**Comment by pdostal** [comment]
@Vogtinator this is related to [poo#47414](https://progress.opensuse.org/issues/47414), right?

**Comment by Vogtinator** [comment]
> @Vogtinator this is related to [poo#47414](https://progress.opensuse.org/issues/47414), right?

Yes, that ticket is a dup.

**Pull request merged**
