### PR TITLE
Upload coredump file from field "Storage"

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
## Ticket

- [poo#20200](https://progress.opensuse.org/issues/20200)

## Verification run

- [poo#1378/file/yast2_samba-problem_detection_logs.tar.xz](http://copland.arch.suse.de/tests/1378/file/yast2_samba-problem_detection_logs.tar.xz)

### CODE REVIEW

**Comment by SergioAtSUSE** [comment]
@dasantiago could you please take a look at this?

**Comment by SergioAtSUSE** [comment]
@rwx788, yes, this PR is only the first part, to be able to provide the coredump files to the developers so they can fix the issue.

@Zaoliang was working on making this crash a soft-failure but he encountered problems, He can give you more details. He suggests to disable those test modules until the fix is done.

**Comment by foursixnine** [comment]
Two cents here: #3384 verification run was successful using the word `Coredumps` running SLE SP3, however on my system the word is Storage, this is the reason for this particular change... It would be nice to know which would be the actual default word (So that we can also detect a regression with this behavior in upcoming versions).

**Comment by SergioAtSUSE** [comment]
The verification run is not valid. It doesn't contain the coredump files.

But it is because of a misconfiguration of my worker. Thanks @foursixnine, working on that.

**Comment by SergioAtSUSE** [comment]
Description updated with proper verification run

**Pull request merged**
