### PR TITLE
Add support for 15-SP4 openqa virtualization test run

### PR DESCRIPTION
**Pull request by waynechen55**
* **Introduce** ENABLE_SNAPSHOT to enable snapshot feature tests switch on/off conveniently, especially for some tests that do not run snapshot tests, for example, oracle linux guest installation.
* **Add** support for oracle linux in set_config_as_glue.pm.
* **Add** sles 15-sp4 kvm/xen guest profiles to be used for 15-SP4 openqa test run.

* **Verification runs**:
  * [15sp4 kvm guest on 15sp4 host](http://10.67.129.106/tests/1672)
  * [15sp4 xen guest on 15sp4 host](http://10.67.129.106/tests/1673)
  * [oracle linux 6/7/8 on 15sp4 host](http://10.67.129.106/tests/1665)

### CODE REVIEW

**Comment by waynechen55** [comment]
@alice-suse @Julie-CAO @guoxuguang @nanzhg

**Comment by Julie-CAO** [comment]
LGTM.  Is guest version the only difference between sp4 and sp3 in guest param file so far?

**Comment by waynechen55** [comment]
> LGTM. Is guest version the only difference between sp4 and sp3 in guest param file so far?

sp4 also has more extra args to help debug.

**Comment by Julie-CAO** [comment]
> > LGTM. Is guest version the only difference between sp4 and sp3 in guest param file so far?
> 
> Also build. sp4 also has more extra args to help debug.

yeah, I see '#rd.debug#rd.memdebug=4#rd.udev.debug' in extra args. thanks.

**Pull request merged**
