### PR TITLE
Upload transactional-update log

### PR DESCRIPTION
**Pull request by kravciak**
Local run: http://dhcp91.suse.cz/tests/146

### CODE REVIEW

**Comment by kravciak** [comment]
I might missed something, but if anything fails on stack_* test on controller it should:
 - skip to post_fail_hook of parent - https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/caasp_controller.pm#L43
 - destroy all the mutexes and wait for log export (admin takes longet to export logs than other nodes, so we wait for ADMIN_LOGS_EXPORTED mutex)
 - all other running tests should be exporting logs now

If you see some hole in the logic please explain so I can find proper patch.

**Comment by drpaneas** [comment]
I see your point. I've missed the `post_fail_hook` of the parent. I wasn't aware of this actually. With that in mind, I also agree that's more elegant to do this in this way.

Can you enhance it so to have also the `supportconfig`? See https://progress.opensuse.org/issues/28618

**Comment by kravciak** [comment]
I added psuse_caasp supportconfig

**Comment by drpaneas** [comment]
awesome work. LGTM!

**Comment by kravciak** [comment]
I will merge after few tests

**Pull request merged**
