### PR TITLE
Update aws cli from v1 to v2 #1

### PR DESCRIPTION
**Pull request by pdostal**
- Related pull request: #17337
- Related ticket: [poo#126956](https://progress.opensuse.org/issues/126956)
- Verification run:

### CODE REVIEW

**Review by grisu48 — APPROVED** [review]

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Review by asmorodskyi — APPROVED** [review]
LGTM

**Comment by asmorodskyi** [comment]
but I am not gonna merge this one , someone else needs to do this  :stuck_out_tongue:

**Comment by grisu48** [comment]
Gonna merge this after a VR is passing.

**Comment by pdostal** [comment]
https://pdostal-server.suse.cz/tests/4724#

**Pull request merged**
