### PR TITLE
poo#101824 missing 'is_upgrade' subroutine

### PR DESCRIPTION
**Pull request by lpalovsky**
Module sles4sap/saptune.pm is failing because of missing import. This 
PR adds missing 'is_upgrade' subroutine to imports and addresses part 
of the poo#101824.

- Related ticket: https://progress.opensuse.org/issues/101824
- Verification run: https://mordor.suse.cz/tests/1501#step/saptune/14

### CODE REVIEW

**Comment by bs-suse** [comment]
LGTM

**Review by alvarocarvajald — APPROVED** [review]
LGTM, but verification run is still not passing.

**Review by pevik — APPROVED** [review]

**Comment by lpalovsky** [comment]
> LGTM, but verification run is still not passing.

Yes, I am aware. It is failing due to different issue, but it goes past the point of missing import. 
For the second issue I did temporarily force result to softfailed in OSD as it is not clear what is the expected behavior.

**Comment by pevik** [comment]
Besides that it's an obvious fix which is wanted to be merged CI passed last night when I merged it.

**Pull request merged**
