### PR TITLE
Use $self->select_serial_terminal everywhere

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/44843

### CODE REVIEW

**Comment by asdil12** [comment]
After testing this I'm not convinced anymore, that this is the right thing to do, as it will change the behaviour.

@pevik @okurz

**Comment by asdil12** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6392/files#diff-ed6ec834cefc0548ce79a868392cd727R37
This line cannot be executed via virtio console.

**Comment by asdil12** [comment]
Also I'm in general strongly against using the virtio console by default for all consoletests, as we would loose test coverage related to terminal rendering.
Eg. we cannot test vim using virtio.
Also the serial line would have different terminal settings (different `$TERM`, different terminal size, eg.
We wouldn't test anymore like a user would use the SUT.

**Comment by pevik** [comment]
@asdil12 Well, the name "serial terminal" suggest that this is for console tests => you cannot use assert_screen (needles).
`use_ssh_serial_console()` also set `SERIALDEV` variable to `root-ssh`. You removed it. So is this code needed? If yes, we should update `select_serial_terminal()` to reflect it.

**Comment by pevik** [comment]
@asdil12 ">_ icon": yes, this should be fixed. I personally like output, which is used on public cloud tests, it'd be great to implement something like this for virtio console.
https://openqa.suse.de/tests/2282638#step/abort01/1

FYI Richard Palethorpe created virtio terminal for LTP tests and the main improvements are
* speed (really much faster, which we need)
* test logs (LABS members will not look into screenshot of console test, we like it very much)

**Pull request closed without merging**
