### PR TITLE
Test Recommended dependency installation (FATE#318099)

### PR DESCRIPTION
**Pull request by mvidner**
A followup to #657, where the involved packages should be present in all tested distros: openSUSE, SLE, Ring 1.

### CODE REVIEW

**Comment by mvidner** [comment]
Based on the 23 test runs culminating in a success: http://yast-openqa.suse.cz/tests/98

**Comment by mvidner** [comment]
(Travis is unable to install Net::DBus. I ran the tests locally and they passed.)

**Comment by mvidner** [comment]
@dzedro updated, using variables now

**Comment by sysrich** [comment]
Doesn't this SR clash wit what's proposed in #657 ?

**Comment by mvidner** [comment]
@sysrich Yes, this one is meant to supersede it.

**Comment by dzedro** [comment]
@mvidner please squash commits

**Comment by mvidner** [comment]
@dzedro squashed, except to keep credit/blame accountable :)

**Pull request merged**
