### PR TITLE
Move keyboard selection to welcome

### PR DESCRIPTION
**Pull request by jknphy**
#6492 was merged but there was some mess with git and my code was reverted accidentally. Sending again PR:

Move keyboard selection code to welcome test module to have all the tests related to that screen in one place.

- Related ticket: https://progress.opensuse.org/issues/42932
- Verification run: 
  - [sle-15-SP1-switch_keyboard_gnome](http://rivera-workstation/tests/1028#step/welcome/7)

### CODE REVIEW

**Comment by rwx788** [comment]
That's really strange. No changes to file are even logged...

**Comment by dzedro** [comment]
No changes were made to the file, @jknphy was just missing commits

**Comment by rwx788** [comment]
@dzedro not sure what do you mean, there is a commit: 9893bc34008e449d88144b0bfff4e1b036b4d654 which doesn't exist anymore...

**Comment by dzedro** [comment]
@rwx788 sorry I was confused with closed commit, yes it is strange, I was checking also previous commits and there is no record

**Comment by jknphy** [comment]
There was a force-push with drop the commit. It is visible [here](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6502) although hard to find it.

**Pull request merged**
