### PR TITLE
Also update openSUSE postgres94->96

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@andreasstieger ?

**Comment by andreasstieger** [comment]
For Leap 42.2 we are also supplying postgresql96 via openSUSE:Maintenance:6934 / openSUSE:Maintenance:6935.

**Comment by okurz** [comment]
so as soon as you see maintenance openQA tests failing we can merge this then

**Comment by andreasstieger** [comment]
@msmeissn   FYI for postgresql96

**Comment by coolo** [comment]
rebase?

**Comment by okurz** [comment]
done

**Pull request merged**
