### PR TITLE
Add user login validation in PowerVM

### PR DESCRIPTION
**Pull request by jknphy**
- Related ticket: https://progress.opensuse.org/issues/68386
- Verification run: https://openqa.suse.de/tests/4405889

### CODE REVIEW

**Comment by b10n1k** [comment]
Hey. I guess `validate_user_login_textmode.pm` is enough for our purpose but to be honest i do not like it. We could reuse another validation module instead, or at least take the opportunity to extend the checks. For instance it could include a check for `whoami`, '`uid` and `autologin`.

**Comment by jknphy** [comment]
> Hey. I guess `validate_user_login_textmode.pm` is enough for our purpose but to be honest i have some objections for the simplicity of the module. We could reuse another validation module instead, or at least take the opportunity to extend the checks. For instance it could include a check for `whoami`, '`uid` and `autologin`.

I agreed with you somehow, but I don't know what else to add here, it is really dummy module. `whoami` does not give any more info that this [needle](https://openqa.suse.de/tests/4405889#step/validate_user_login_textmode/2), `id` is implicitly working and autologin is the default (unless we would change the the test to have some different values but it would complicate the login part). Let's see if there are more suggestion, the only goal of this ticket is to match the coverage with the other architectures which are not PowerVM, where we do login into desktop.

**Comment by b10n1k** [comment]
> > Hey. I guess `validate_user_login_textmode.pm` is enough for our purpose but to be honest i have some objections for the simplicity of the module. We could reuse another validation module instead, or at least take the opportunity to extend the checks. For instance it could include a check for `whoami`, '`uid` and `autologin`.
> 
> I agreed with you somehow, but I don't know what else to add here, it is really dummy module. `whoami` does not give any more info that this [needle](https://openqa.suse.de/tests/4405889#step/validate_user_login_textmode/2), `id` is implicitly working and autologin is the default (unless we would change the the test to have some different values but it would complicate the login part). Let's see if there are more suggestion, the only goal of this ticket is to match the coverage with the other architectures which are not PowerVM, where we do login into desktop.

Let s do it as you want. it was just an personal objection but not a request. what i propose (in case you want to consider it) is at least to assert the uid, gid and groups that we expect for the user. Plus the value of the autologin. you can take an idea from the feature itself[0] of what it does so we can say that we cover at least some logical part of it
[0] https://github.com/yast/yast-users/blob/master/src/lib/users/dialogs/inst_user_first.rb#L65

**Comment by rwx788** [comment]
> > > Hey. I guess `validate_user_login_textmode.pm` is enough for our purpose but to be honest i have some objections for the simplicity of the module. We could reuse another validation module instead, or at least take the opportunity to extend the checks. For instance it could include a check for `whoami`, '`uid` and `autologin`.
> > 
> > 
> > I agreed with you somehow, but I don't know what else to add here, it is really dummy module. `whoami` does not give any more info that this [needle](https://openqa.suse.de/tests/4405889#step/validate_user_login_textmode/2), `id` is implicitly working and autologin is the default (unless we would change the the test to have some different values but it would complicate the login part). Let's see if there are more suggestion, the only goal of this ticket is to match the coverage with the other architectures which are not PowerVM, where we do login into desktop.
> 
> Let s do it as you want. it was just an personal objection but not a request. what i propose (in case you want to consider it) is at least to assert the uid, gid and groups that we expect for the user. Plus the value of the autologin. you can take an idea from the feature itself[0] of what it does so we can say that we cover at least some logical part of it
> [0] https://github.com/yast/yast-users/blob/master/src/lib/users/dialogs/inst_user_first.rb#L65

I'm not sure if we can find requirements that uid has to match in the SUT. Same for group memberships, as we won't import those. So as of now, I would say that checking that user is created with correct password is good enough.

**Pull request merged**
