### PR TITLE
Get guest console output by matching non-empty content directly

### PR DESCRIPTION
**Pull request by waynechen55**
* **Actually** there is no need to do login and typing something inside guest console which may introduce unnecessary waste in terms of both time and log content
* **Constant** guest console output collection by matching non-empty output directly is enough to guarantee entirety and integrity
* **Modification** is limited to embedded expect script that is responsible for guest console connecting and output matching and collecting. So there will be no impact on original design structure
* **Related ticket:** n/a
* **Needles:** n/a
* **Verification run:**
  * [Manual verify guest_console_monitor.sh can resume console output collection even when fv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486598/sles-15-sp2-64-fv-def-net_console.log)
  * [Manual verify guest_console_monitor.sh can resume console output collection even when pv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486599/sles-15-sp2-64-pv-def-net_console.log)
  * [openQA test when test fails with guest log collection via ssh](http://10.67.129.106/tests/517/file/storage2%231-virt_logs_all.tar.gz)
  * [openQA test when test fails with guest log collection via guest console](http://10.67.129.106/tests/515/file/storage2%231-virt_logs_all.tar.gz)
  (Please use "cat path_to_guest_console_log" to view pretty  guest console output.)

### CODE REVIEW

**Comment by waynechen55** [comment]
@alice-suse @guoxuguang @Julie-CAO

**Comment by alice-suse** [comment]
>   * [Manual verify guest_console_monitor.sh can resume console output collection even when fv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486598/sles-15-sp2-64-fv-def-net_console.log)
>   * [Manual verify guest_console_monitor.sh can resume console output collection even when pv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486599/sles-15-sp2-64-pv-def-net_console.log)

Guest  console log is one of the key debug logs when guest boot hangs in the middle of the booting process. Thanks for the fix. 

I downloaded this pv guest console log, but it contains much less boot msg compared to the first fv guest log(not include a complete boot process log). Do you know why?


>   * [openQA test when test fails with guest log collection via ssh](http://10.67.129.106/tests/517/file/storage2%231-virt_logs_all.tar.gz)
>   * [openQA test when test fails with guest log collection via guest console](http://10.67.129.106/tests/515/file/storage2%231-virt_logs_all.tar.gz)

For the above two jobs links, I checked both fv and pv guest console log. Fv guest nearly has no boot log, I guess it is because there is no boot related actions on it. Reasonable! But for pv guest, both jobs seems to have done several rounds of reboot. But compared to earlier manual verification link logs, although a few more boot log lines, still it is not complete. Do you know why?

We should be able to collect complete guest console log for guest reboot, both fv and pv.

>     (Please use "cat path_to_guest_console_log" to view pretty  guest console output.)
This is very helpful! Would you please add a comment for it in code?

**Comment by alice-suse** [comment]
@guoxuguang Please also help to take a look.

**Comment by waynechen55** [comment]
> > * [Manual verify guest_console_monitor.sh can resume console output collection even when fv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486598/sles-15-sp2-64-fv-def-net_console.log)
> > * [Manual verify guest_console_monitor.sh can resume console output collection even when pv guest reboots, namely console connection is lost](https://github.com/os-autoinst/os-autoinst-distri-opensuse/files/5486599/sles-15-sp2-64-pv-def-net_console.log)
> 
> Guest console log is one of the key debug logs when guest boot hangs in the middle of the booting process. Thanks for the fix.
> 
> I downloaded this pv guest console log, but it contains much less boot msg compared to the first fv guest log(not include a complete boot process log). Do you know why?
> 
> > * [openQA test when test fails with guest log collection via ssh](http://10.67.129.106/tests/517/file/storage2%231-virt_logs_all.tar.gz)
> > * [openQA test when test fails with guest log collection via guest console](http://10.67.129.106/tests/515/file/storage2%231-virt_logs_all.tar.gz)
> 
> For the above two jobs links, I checked both fv and pv guest console log. Fv guest nearly has no boot log, I guess it is because there is no boot related actions on it. Reasonable! But for pv guest, both jobs seems to have done several rounds of reboot. But compared to earlier manual verification link logs, although a few more boot log lines, still it is not complete. Do you know why?
> 
> We should be able to collect complete guest console log for guest reboot, both fv and pv.
> 
> > ```
> > (Please use "cat path_to_guest_console_log" to view pretty  guest console output.)
> > ```
> 
> This is very helpful! Would you please add a comment for it in code?

I think I have to answer that what is to be printed out in guest console log is not determined by the "console log" itself, it can be affected by kernel settings or system settings or guest behavior. But the "console log" itself can capture all that is to be printed out in guest console, so that is it. Nothing to be worried about with this implementation.

**Comment by alice-suse** [comment]
> I think I have to answer that what is to be printed out in guest console log is not determined by the "console log" itself, it can be affected by kernel settings or system settings or guest behavior. 

This is the point. On our side, automation code should ensure that kernel settings or system settings , or anything related, should be correctly set so that FULL boot log can be captured. It is fine to be done in other PR, but this needs to be addressed.

**Comment by waynechen55** [comment]
> > I think I have to answer that what is to be printed out in guest console log is not determined by the "console log" itself, it can be affected by kernel settings or system settings or guest behavior.
> 
> This is the point. On our side, automation code should ensure that kernel settings or system settings , or anything related, should be correctly set so that FULL boot log can be captured. It is fine to be done in other PR, but this needs to be addressed. From POV of users that consume the guest console log, eg dev, they still do not get the console log yet, although it is there(but not complete enough for debug).


> > I think I have to answer that what is to be printed out in guest console log is not determined by the "console log" itself, it can be affected by kernel settings or system settings or guest behavior.
> 
> This is the point. On our side, automation code should ensure that kernel settings or system settings , or anything related, should be correctly set so that FULL boot log can be captured. It is fine to be done in other PR, but this needs to be addressed. From POV of users that consume the guest console log, eg dev, they still do not get the console log yet, although it is there(but not complete enough for debug).

It is not just fine. It is absolutely right. What you mentioned is far from what is going to be addressed in this pull request. And I am not providing a point for you, I explained that what is going to be addressed in this implementation fulfills its purpose instead of trying to solve other issues.

**Comment by alice-suse** [comment]
> 
> It is not just fine. It is absolutely right. What you mentioned is far from what is going to be addressed in this pull request. And I am not providing a point for you, I explained that what is going to be addressed in this implementation fulfills its purpose instead of trying to solve other issues.

Totally agree that this PR solves the original issue. But it also exposes new issue. There can be two ways to handle it, either fix it together in this PR, or fix it in another PR, but anyway it needs to be visible and solved. So I commented the issue here, and waited your reply. Now I get your point that you prefer the new issue be solved in a new PR. Totally fine with that. I will merge if no further comments from others, especially leon.

For the new issue -- incomplete boot log in guest console,  please do not just leave as it is. To be specific, please open a new card in trello for it, and plan into sprints whenever suitable.  Thanks! I hope you can also take it as a small example about how I wish the further log enhancement issues be handled(I explained also in last sprint meeting)  -- you and leon, as the main people, to OBSERVE log issues, open cards, and plan fixes. As PO, I  really do not have so much effort to look detailedly into every task. Again, just only different responsiblities.

**Comment by waynechen55** [comment]
> > It is not just fine. It is absolutely right. What you mentioned is far from what is going to be addressed in this pull request. And I am not providing a point for you, I explained that what is going to be addressed in this implementation fulfills its purpose instead of trying to solve other issues.
> 
> Totally agree that this PR solves the original issue. But it also exposes new issue. There can be two ways to handle it, either fix it together in this PR, or fix it in another PR, but anyway it needs to be visible and solved. So I commented the issue here, and waited your reply. Now I get your point that you prefer the new issue be solved in a new PR. Totally fine with that. I will merge if no further comments from others, especially leon.
> 
> For the new issue -- incomplete boot log in guest console, please do not just leave as it is. To be specific, please open a new card in trello for it, and plan into sprints whenever suitable. Thanks! I hope you can also take it as a small example about how I wish the further log enhancement issues be handled(I explained also in last sprint meeting) -- you and leon, as the main people, to OBSERVE log issues, open cards, and plan fixes. As PO, I really do not have so much effort to look detailedly into every task. Again, just only different responsiblities.

Yes. I will take responsibility with no doubt. And I also need time.

**Comment by alice-suse** [comment]
> Yes. I will take responsibility with no doubt. And I also need time.

Sure, take your time, no pushing here. Please share the trello link after creation!

@guoxuguang I will wait for your review before merging. No pushing, just a reminder! Thanks!

**Comment by guoxuguang** [comment]
> > Yes. I will take responsibility with no doubt. And I also need time.
> 
> Sure, take your time, no pushing here. Please share the trello link after creation!
> 
> @guoxuguang I will wait for your review before merging. No pushing, just a reminder! Thanks!

Sorry for the late reply. 
Sure, I am working it now. Will update my comments here.

**Comment by guoxuguang** [comment]
LGTM
@alice-suse , please help us merge this PR. 
Thanks so much for your great help

**Pull request merged**
