### PR TITLE
dolphin: Fix switch to documents folder taking longer

### PR DESCRIPTION
**Pull request by okurz**
See https://openqa.opensuse.org/tests/773745#step/dolphin/9

### CODE REVIEW

**Comment by okurz** [comment]
@Vogtinator

**Comment by Vogtinator** [comment]
Can you provide a test run?

IMO this really shouldn't be necessary. If opening that folder takes that long, it's a product bug.

**Comment by okurz** [comment]
@Vogtinator what should a test run show you when I just increase the default timeout from 30s to 60s? I am fine with calling that a product bug but I just expected that no one would pick it up anyway.

**Comment by Vogtinator** [comment]
> @Vogtinator what should a test run show you when I just increase the default timeout from 30s to 60s?

Hopefully that it works reliably.

**Comment by okurz** [comment]
So I would probably need 100 runs as proof. I do not think it is valuable to do it before merging the PR. So what do you suggest: Should we merge and monitor in production or you create a product bug and we just label the job failure with this? Then we can still use `assert_screen_with_soft_timeout` to reference the bug

**Comment by okurz** [comment]
So tell me the bugid :)

**Comment by Vogtinator** [comment]
Just created: 1112021

**Comment by okurz** [comment]
updated.

I am betting that this bug will never be fixed :) I will buy you a beer if I am wrong!

**Comment by Vogtinator** [comment]
> updated.

LGTM!

> I am betting that this bug will never be fixed :) I will buy you a beer if I am wrong!

There are two issues:
- If it's not reproducible, it might indeed not be easy to fix.
- I don't like beer

**Comment by okurz** [comment]
well, hot chocolate then maybe :)

**Pull request merged**
