### PR TITLE
Make the failure condition in update_install a little more expressive

### PR DESCRIPTION
**Pull request by coolo**
If the test knows what is missing, it should tell me and not let me dig it up from infos I don't have :)

### CODE REVIEW

**Comment by coolo** [comment]
having a die with "it might be" is a little strange though - because the actual error I was debugging is not exactly an error in the update. It's just IMO a very hard to grasp situation - both for humans and for tests.

**Comment by a-kpappas** [comment]
The failure should be considered in the larger workflow. When a member of the verification squad starts working on an update,  update_install results are checked, and if it has failed, the manual install workflow is initiated. I made it die to make sure that if something is weird, a person has to check it.

**Comment by coolo** [comment]
but this failure also blocks automatic qam-openqa approval. So it would be better for such situations if the test logged it as info and update squad is asked to check openqa results for such signals.

**Comment by dzedro** [comment]
I wouldn't do `die` if package related to updated package is not part of patch, that is rough and strict check causing lot of failures.

**Comment by dzedro** [comment]
The idea is nice, but it will need more sophisticated algorithm.

**Comment by coolo** [comment]
IMO it would be better if the bot scheduling calculates the expectations and the openqa test code only verifies.

**Comment by coolo** [comment]
Shall I remove the die?

**Comment by dzedro** [comment]
> Shall I remove the die?

Testers can still look for soft fails, I think except package checks there are no soft failures.

**Comment by coolo** [comment]
> > Shall I remove the die?
> 
> Testers and reviewers can still look for soft fails, I think except package checks there are no soft failures in qam-incidentinstall tests

Is that a yes? And if so, @a-kpappas do you agree?

**Comment by a-kpappas** [comment]
Sure. 
You should also remove the warning if a conflict was detected, since then it's guaranteed to trigger.

**Comment by coolo** [comment]
die is removed - if you need more or less recorded info, please followup

**Comment by dzedro** [comment]
I would do `record_soft_failure` now you have to check details of test to see the package failure
I tried the PR on wireshark update, no idea if libwscodecs2 should be in smelt

```
Defined in project:  SUSE:SLE-15:Update
  bugowner of libwscodecs1 : 
   ro@suse.de
```

https://openqa.suse.de/tests/5005673#step/update_install/261
https://openqa.suse.de/tests/5005674#step/update_install/131
https://openqa.suse.de/tests/5005675#step/update_install/261
https://openqa.suse.de/tests/5005706#step/update_install/261
https://openqa.suse.de/tests/5005677#step/update_install/261

**Comment by coolo** [comment]
So even without die the test is dying, that's what you say 😄

**Comment by dzedro** [comment]
> So even without die the test is dying, that's what you say smile

It would be too easy :smile:

**Comment by coolo** [comment]
So smelt is making up package names and the test breaks if it's bogus. I don't think we should test smelt on openqa, but incidents :(

The library name is not part of the patchinfo nor the channels

**Comment by dzedro** [comment]
Also openssl :unamused: https://openqa.suse.de/tests/5006140#step/update_install/179

**Comment by coolo** [comment]
well, that incident isn't even locked - so coord might prefer to get that feedback actually :)

**Comment by a-kpappas** [comment]
The reason I added the query to SMELT is so that I could know what to install. Should we just ignore that and parse the repos for the RPMs or accept some failures or ask Maintenance-Coordination to provide as way to get that list?

**Comment by coolo** [comment]
wireshark was actually fixed in smelt and passed. The openssl one looks more interesting and I might look into it, but IMO this PR should go in - as it unblocked mariadb.

**Review by a-kpappas — APPROVED** [review]

**Pull request merged**
