### PR TITLE
[AARCH64 Automation] Replacing daily build URL with specific ARCH included  as well

### PR DESCRIPTION
**Pull request by waynechen55**
Replacing daily build URL should take ARCH into consideration.

- Related ticket: http://10.162.187.154/tests/617
                          https://github.com/SUSE/qa-testsuites/pull/648
                          https://github.com/SUSE/qa-automation/pull/666
- Needles: n/a
- Verification run: 
https://10.67.17.5/tests/293#  x86_64
http://qadb2.suse.de/qadb/submission.php?submission_id=1582704
http://10.162.187.154/tests/743  aarch64

@alice-suse @guoxuguang @Julie-CAO

### CODE REVIEW

**Comment by waynechen55** [comment]
Will provide verification run based on the latest commit, which is currently hindered by unavailability of daily build on OSD repo.

**Comment by alice-suse** [comment]
Still WIP?

**Comment by waynechen55** [comment]
> Still WIP?

This can be merged into master together with 
                          https://github.com/SUSE/qa-testsuites/pull/648
                          https://github.com/SUSE/qa-automation/pull/666
if no other concerns.

**Comment by alice-suse** [comment]
LGTM.

Need to be merged after the aboved 2 given PRs merged, or openqa tests will be blocked.

**Comment by waynechen55** [comment]
Does anyone know how to fix this checking failure ?  I have not done nothing to os-autoinst/openQA.
image

**Comment by alice-suse** [comment]
Need  to wait PR https://github.com/SUSE/qa-automation/pull/666 merged.

**Comment by alice-suse** [comment]
All dependent PRs mreged.

**Pull request merged**
