### PR TITLE
Migrate create_hdd_multipath_textmode to AutoYaST

### PR DESCRIPTION
**Pull request by Avinesh**
Signed-off-by: Avinesh Kumar <akumar@suse.de>

Autoyast profiles generated with autoyast/clone.pm and yaml schedule for multipath enabled hdd creation job.

Related ticket: https://progress.opensuse.org/issues/113596

Verification runs:
Jobs which create the hdd images and dependency jobs -
x86_64: https://openqa.suse.de/tests/9475853  =>  https://openqa.suse.de/tests/9477406
aarch64: https://openqa.suse.de/tests/9475854  => https://openqa.suse.de/tests/9477407
ppc64le: https://openqa.suse.de/tests/9482537  => https://openqa.suse.de/tests/9482699

### CODE REVIEW

**Review by czerw — APPROVED** [review]
LGTM

**Comment by czerw** [comment]
@jknphy Could you please have look as well? (Just small review anyone from yast team).

**Review by ge0r — APPROVED** [review]
LGTM! Is there also a link for the related MR?

**Comment by ge0r** [comment]
> LGTM! Is there also a link for the related MR?

If you are not using CI for this just ignore my MR request!

**Comment by Avinesh** [comment]
> > LGTM! Is there also a link for the related MR?
> 
> If you are not using CI for this just ignore my MR request!

@ge0r , Thank you for the review.
and yes, test suites are maintained only in osd webui.

**Pull request merged**
