### PR TITLE
Fix dashboard broken issue in new version of grafana

### PR DESCRIPTION
**Pull request by badboywj**
the layout of dashboard has some changes on 15-SP6, this results in the case sles4sap_grafana_dashboards failed, this PR fixed the issue.

- Related ticket: https://jira.suse.com/browse/TEAM-8806
- Needles:
    https://openqa.suse.de/tests/13890881#step/grafana_dashboards/41
    https://openqa.suse.de/tests/13890881#step/grafana_dashboards/42
    https://openqa.suse.de/tests/13890881#step/grafana_dashboards/43
    https://openqa.suse.de/tests/13890881#step/grafana_dashboards/44
- Verification run: 
    https://openqa.suse.de/tests/13896909
    https://openqa.suse.de/tests/13896920
    https://openqa.suse.de/tests/13896925

### CODE REVIEW

**Review by mpagot — APPROVED** [review]
LGTM

**Review by lilyeyes — APPROVED** [review]
LGTM.

**Comment by lilyeyes** [comment]
Please check if qam job groups have grafana related jobs and make sure this PR will not break them.

**Comment by badboywj** [comment]
> Please check if qam job groups have grafana related jobs and make sure this PR will not break them.

@lilyeyes  thank you help to check qam jobs, and no jobs related to grafana

**Pull request merged**
