### PR TITLE
Update test data of modules for installer_extended

### PR DESCRIPTION
**Pull request by lemon-suse**
Quick PR.

- Related ticket: N/A
- Needles: N/A
- Verification run: 
http://openqa.suse.de/tests/15210694#step/verify_module_registration/1
http://openqa.suse.de/tests/15210706#step/verify_module_registration/1

### CODE REVIEW

**Comment by hjluo** [comment]
For those removed modules, do we really don't support them? do we have some doc to prove that?

**Comment by lemon-suse** [comment]
> For those removed modules, do we really don't support them? do we have some doc to prove that?

The list updated following the actual module list supported, about the PRD which is not ready yet. I think we can follow the actual list to update firstly, later update it if PRD is ready.

**Comment by hjluo** [comment]
LGTM

**Review by hjluo — APPROVED** [review]
LGTM

**Pull request merged**
