### PR TITLE
Add SLES-12-SP3-LTSS-TERADATA repository for 12-SP3 

### PR DESCRIPTION
**Pull request by DeepthiYV**
- Related ticket: https://progress.opensuse.org/issues/115910
- Needles: NO
- Verification run:
 https://openqa.suse.de/tests/9407189#step/patch_and_reboot/23
 https://openqa.suse.de/tests/9407629#step/patch_and_reboot/29

### CODE REVIEW

**Comment by DeepthiYV** [comment]
@foursixnine @ge0r @michaelgrifalconi  Please review.

**Review by michaelgrifalconi — APPROVED** [review]

**Review by ge0r — APPROVED** [review]
Try rebasing to updated master, this usually resolves the CI security fail

**Comment by foursixnine** [comment]
@DeepthiYV I guess those were all of the changes right? if so, please do a brief explanation on the ticket, as this will be for sure be useful on other situations in the future when enabling updates for a particular customer or codestream

**Comment by ge0r** [comment]
> @DeepthiYV I guess those were all of the changes right? if so, please do a brief explanation on the ticket, as this will be for sure be useful on other situations in the future when testing maintenance updates for a particular customer or codestream

Hey Santiago, I have added this change on my notes for the yet-to-be-written confluence page about what to do when a product is moved to maintenance LTSS.
I will probably have it ready within the following week(s).

**Comment by foursixnine** [comment]
Awesome George! if you don't mind, when creating the doc please add it under: https://confluence.suse.com/display/qasle/Test+configuration+setup

**Pull request merged**
