### PR TITLE
Make yast2_ui test flow easier to review by splitting into two flows

### PR DESCRIPTION
**Pull request by okurz**
The test scenario "yast2_ui" is infamous for showing a lot of valid product
bugs but because the yast modules are used for configuring so many different
product services the test is prone to fail often and therefore hard to review.
By splitting into the ncurses and the GUI tests the review should be made a
bit easier.

Verification runs:
* yast2 ncurses: http://lord.arch/tests/7499
* yast2 gui: http://lord.arch/tests/7498

This commit replaces the test control variable "Y2UITEST" with two variables:

* "Y2UITEST_NCURSES": Call ncurses based yast test modules
* "Y2UITEST_GUI": Call GUI based yast test modules using Qt/GTK framework

Related progress issue: https://progress.opensuse.org/issues/19922

### CODE REVIEW

**Comment by okurz** [comment]
@zluo can you execute the tests?

**Comment by Zaoliang** [comment]
@okurz sure, will update this file and give a try on my server.

**Comment by okurz** [comment]
Tested and provided verifcation runs.

**Comment by okurz** [comment]
@DimStar77 @nilxam @lnussel how would you like that?

**Comment by nilxam** [comment]
The idea works for me.

**Comment by DimStar77** [comment]
sounds reasonable

**Comment by okurz** [comment]
I created two new testsuites on openqa.opensuse.org as well as on openqa.suse.de "yast2_gui" and "yast2_ncurses" replacing the previous "yast2_ui" testsuite. Also I added these scenarios to the according job groups for scheduling.

**Pull request merged**
