### PR TITLE
LTP install runtime dependencies only for git instalation

### PR DESCRIPTION
**Pull request by pevik**

### CODE REVIEW

**Comment by pevik** [comment]
@czerw @mimi1vx FIY
Need to do some tests, that's why WIP.

**Comment by pevik** [comment]
This breaks 32bit build (waiting for @czerw to add `Recommends:` also for `ltp-32bit`. But there is workaround to install it from git `INSTALL_LTP=from_git`.
@mimi1vx this waits for your approval. I guess QAM does not use 32bit build.

**Comment by czerw** [comment]
LTP packages were fixed, they should contain proper recommends in 32bit vresions.

**Comment by pevik** [comment]
@czerw @richiejp @mimi1vx @mdoucha after some testing I'm for merging this.

BTW about merging install_ltp into each test: it takes ~2 mins, snapshoting another ~10 min (both depend on worker load). Therefore it still looks faster to snapshot, so I'll try to solve snapshotting problems on o3 (+ on VM it's nice to have ltp and other packages installed).
But for IPMI I'd use merged install_ltp (requires https://github.com/os-autoinst/openQA/pull/2302 and https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/8329).

**Pull request merged**
