### PR TITLE
Move chrome to extra tests

### PR DESCRIPTION
**Pull request by yxususe**
See https://progress.opensuse.org/issues/18690

### CODE REVIEW

**Comment by yxususe** [comment]
Test run available at f146.suse.de/tests/22

**Comment by coolo** [comment]
that test run is not really convincing

**Comment by okurz** [comment]
Please state commit message subject line in imperative mood and describe the reasoning or benefit of the commit, not the action what you are doing. Also see http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

**Comment by yxususe** [comment]
The test run failed because xorg directory was not created:
script_run(cmd='test -d /home/*/.local/share/xorg ; echo user-xlog-path-$? > /dev/ttyS0', wait=0)
It comes from the chrome test itself. What I did was, the chrome test being moved to the extra tests so it doesn't run on every installation.

**Comment by coolo** [comment]
no, the test run failed because you run the chrome test without being in the desktop and the test expects that.

**Comment by yxususe** [comment]
The test is run after the check any_desktop_is_applicable(), isn't is sufficient?

**Comment by okurz** [comment]
apparently not :-)

`any_desktop_is_applicable()` means that the test should be called. It does not means the test has all pre-requisites it needs.

There is the concept of "consoles" in openQA tests. Take a look for example in the module  tests/x11/vnc_two_passwords.pm which was previously the first one to be called after the `any_desktop_is_applicable()` call. It calls `select_console 'x11';` before it asserts anything on the desktop. Try to add the same in the `run` method of tests/x11/chrome.pm and see if that helps.

**Comment by okurz** [comment]
Also because you are moving the test from products/*opensuse*/main to lib/main_*common* you should add the module in the "check_var('DISTRI', 'opensuse')" branch to only call it for openSUSE tests.

**Comment by yxususe** [comment]
I tried the suggestion however it didn't help. From https://openqa.opensuse.org/tests/396181 we can see chrome test can also succeed without any issues. So it could also be issued from extra test itself. At the moment multi_users_dm is failing in extra_tests_on_gnome extra_tests_on_kde and extra_tests_on_xfce, which also makes it suspicious.

**Comment by okurz** [comment]
I suggest you just push your changes so that we can see what you have along with a URL to the failing test cases. Then we can try to help.

**Comment by okurz** [comment]
code looks fine. Does it work now? In any case please provide a URL to a local verification run.

**Comment by yxususe** [comment]
It works. Here is a restrun for example: http://f146.suse.de/tests/143

**Comment by yxususe** [comment]
You can ignore the kdump part. It is irrelevant.

**Comment by yxususe** [comment]
Here are recent test runs following the newest commit: [f146.suse.de/tests/218](url)  [f146.suse.de/tests/216](url)

**Comment by okurz** [comment]
great. Congratulations to your first PR on os-autoinst-distri-opensuse :-) Thank you for your contribution.

**Comment by yxususe** [comment]
Thanks, Oliver. :-)

**Pull request merged**
