### PR TITLE
wicked: use common wicked command

### PR DESCRIPTION
**Pull request by jlausuch**
The idea is to be compliant with the legacy suite by wicked using a common script to call wicked:
https://github.com/openSUSE/wicked-testsuite/blob/master/images-config/files-sut/wic.sh

- Related ticket: https://progress.opensuse.org/issues/42641
- Verification run: http://fromm.arch.suse.de/tests/2340

### CODE REVIEW

**Comment by jlausuch** [comment]
@asmorodskyi  What do you think about this?

**Comment by asmorodskyi** [comment]
LGTM , why it is still in WIP ? looks fine

**Comment by jlausuch** [comment]
> LGTM , why it is still in WIP ? looks fine

@asmorodskyi it was WIP cause I wanted you to have a look before merge.

**Comment by Soulofdestiny** [comment]
breaking all x86_64 tests

 Undefined subroutine &version_utils::is_server called at /var/lib/openqa/cache/tests/sle/lib/version_utils.pm line 320

**Pull request merged**
