### PR TITLE
Lengthen timeout and add y2log uploading for yast2 scc

### PR DESCRIPTION
**Pull request by mitiao**
poo#16364
https://progress.opensuse.org/issues/16364

Use log-console to upload log for console_yasttest, and upload y2log for register_system

### CODE REVIEW

**Comment by okurz** [comment]
90s is quite some time to wait if a human user would do it. You could report a bug and use assert_screen_with_soft_timeout

**Comment by dzedro** [comment]
Don't forget under what load are sometimes opneQA/workers.
I don't know if 'qemu IO stalling the entire system' is gone now.
Proxy SCC or network can also freak out (be slow) while n request maybe in same time are done.
At the end openQA doesn't test performance I would not mind 30 -> 90

**Comment by okurz** [comment]
> I don't know if 'qemu IO stalling the entire system' is gone now.

It is detected and dies the test when an assert_screen fails and a stall has been detected. So this is properly handled.

**Comment by coolo** [comment]
it would be good to have the yast logs of thie test, e.g. if it was a proper console_yasttest. If you file a bug, this will be the first they'll ask anyway

**Pull request merged**
