### PR TITLE
Improve script to find unused modules

### PR DESCRIPTION
**Pull request by asdil12**
- Account for YAML scheduling
- Account commented out modules and actual loadtest

Ticket: https://progress.opensuse.org/issues/60908

### CODE REVIEW

**Comment by okurz** [comment]
not sure how it's supposed to work. E.g. I see in https://travis-ci.org/os-autoinst/os-autoinst-distri-opensuse/jobs/627265370#L539 that "yast2_gui/yast2_users" is reported as unused – at least this is how I interpret the output – but `git grep 'yast2_users'` shows that it's used in schedule/yast/yast2_gui.yaml

**Comment by asdil12** [comment]
Finally found the issue. It should work now.

**Comment by okurz** [comment]
Now the exclusion with the follow-up grep does not work anymore. https://travis-ci.org/os-autoinst/os-autoinst-distri-opensuse/jobs/627661649#L465 reports zypper_moo, which should be excluded, same as more others

**Comment by asdil12** [comment]
Now I made this whitelist which was very crude a bit more explicit so that it should work with the new code.

**Pull request merged**
