### PR TITLE
publiccloud: change variable name to more accurate

### PR DESCRIPTION
**Pull request by asmorodskyi**
VR : https://openqa.suse.de/tests/7647992

### CODE REVIEW

**Review by b10n1k — COMMENTED** [review]
This require a change also in publiccloud/pctoolsimage.yaml:31

**Comment by asmorodskyi** [comment]
https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/512

**Comment by b10n1k** [comment]
would you mind to run a VR also for https://openqa.suse.de/tests/7241026?

**Comment by b10n1k** [comment]
> would you mind to run a VR also for https://openqa.suse.de/tests/7241026?

or not. i think it is save to ignore in a second look

**Review by b10n1k — APPROVED** [review]
LGTM and i think you can merge it even while the gitlab CI fails.

**Comment by asmorodskyi** [comment]
> > would you mind to run a VR also for https://openqa.suse.de/tests/7241026?
> 
> or not. i think it is save to ignore in a second look

yes it is not related , but on other side  `create_hdd_autoyast_pc` needs some changes just maybe outside of this PR which just trying to fix `upload_img`

**Pull request merged**
