### PR TITLE
openqa script for tc#1503849: switch gnome-classic/ sle-classic

### PR DESCRIPTION
**Pull request by xjinGitty**
Local test result:
http://147.2.212.232/tests/580/modules/gnome_classic_switch/steps/1

### CODE REVIEW

**Comment by sysrich** [comment]
If assert_and_click is not working the way we need it to, wouldn't it be better to patch assert_and_click rather than adding new functions into tests?

**Comment by xjinGitty** [comment]
Yes, patch assert_and_click is an alternative and better option, which I am considering how to implement.

And finally will use the patched assert_and_click API instead of use the new functions in the tests.

**Comment by coolo** [comment]
if I get this right, you can't move the mouse to where it was before because it triggers some UI actions, right?

If so, how about moving the mouse to a safer place before?

**Comment by xjinGitty** [comment]
You're right, the mouse was in the top-left before, where has special functionality in gnome-classic (launch gnome-mainmenu).

I agree with your suggestion, moving the mouse to a safer place before, then call the assert_and_click api should work. And if so modification of the assert_and_click API is required, also new function in the script is unnecessary.

I am going to update script accordingly.

**Comment by xjinGitty** [comment]
You're right, the mouse was in the top-left before, where has special
functionality in gnome-classic (launch gnome-main-menu).

I agree with your suggestion, moving the mouse to a safer place before, then
call the assert_and_click api should work. 
- while actually when I use mouse_set(1000, 30) to set the mouse before I call assert_and_click API, test still failed. 
- from log file seems the mouse_set will not affect below value in assert_and_click API:
313     my $old_mouse_coords = $bmwqemu::backend->get_last_mouse_set();
- my local running result for reference:
http://147.2.212.232/tests/575/file/autoinst-log.txt

So from testing result, use the mouse_set to move the mouse to a safer place not work well, could you give suggestion about any other solution to achieve this purpose?

**Comment by coolo** [comment]
the real fix should be in https://github.com/os-autoinst/os-autoinst/pull/480 - and one mouse_set in the test should be enough

**Comment by xjinGitty** [comment]
kept one mouse_set in the test, then test against os-autoinst/os-autoinst#480, test could complete with pass result which could be found in the Local Test Result.

**Pull request merged**
