### PR TITLE
Create /var/lib/machines

### PR DESCRIPTION
**Pull request by asdil12**
See poo#32596

### CODE REVIEW

**Comment by asdil12** [comment]
Local testrun succeded.

**Comment by asdil12** [comment]
[LGTM from anton]

**Comment by DimStar77** [comment]
This is actually not correct - /var/lib/machines should have been generated by systemd-container, but the post script for it is/was missing (Franck fixed in the devel branch already); so at best, we should record it as a softfail if the dir does not exist and only create it in this case.

**Comment by asdil12** [comment]
For the record: [obs-pr#584640](https://build.opensuse.org/request/show/584640)

**Pull request merged**
