### PR TITLE
Use text-login for user/password login prompt

### PR DESCRIPTION
**Pull request by waynechen55**
Change back to use text-login. This was accidentally modified by https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/674c4b5b579d6782dd97a49ddb240ac0ada153e6?_pjax=%23js-repo-pjax-container

- Related ticket: 
   - https://openqa.suse.de/tests/3866769#step/reboot_and_wait_up_normal/1
   - https://openqa.suse.de/tests/3866770#step/reboot_and_wait_up_normal/1
   - https://openqa.suse.de/tests/3866441#step/reboot_and_wait_up_normal/1
   - https://openqa.suse.de/tests/3866440#step/reboot_and_wait_up_normal/1
   and many more
- Needles: Should use 'text-login' for serial ssh login prompt
- Verification run: NO NEED

### CODE REVIEW

**Comment by okurz** [comment]
I recommend you ask the authors of https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9048 when you want to change it back. Also, I don't see why it's "accidentally modified". The according ticket is https://progress.opensuse.org/issues/34471 . How do you see it's wrong? The ticket https://progress.opensuse.org/issues/34471 is almost 2 years old. I did also not see any comment by you in the ticket stating where it's wrong so I assume you only mean the one single code location. Our goal was to remove the too generic needle tag "text-login" completely to prevent false matches on the wrong tty. What problems do you see with this approach?

**Comment by waynechen55** [comment]
> I recommend you ask the authors of #9048 when you want to change it back. Also, I don't see why it's "accidentally modified". The according ticket is https://progress.opensuse.org/issues/34471 . How do you see it's wrong? The ticket https://progress.opensuse.org/issues/34471 is almost 2 years old. I did also not see any comment by you in the ticket stating where it's wrong so I assume you only mean the one single code location. Our goal was to remove the too generic needle tag "text-login" completely to prevent false matches on the wrong tty. What problems do you see with this approach?

This is just my proposal. You can disagree and voice your opinion.

**Comment by okurz** [comment]
I agree that the other PR should not have been merged late during the European day and fallout left for you to handle. That can be done better.

I forgot to mention in before that I had the faulty PR already reverted with https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9519 earlier.

What I don't understand is what you mean with "not just replace them with something else not directly related". The idea was to further specify what specific console is expected and prevent persons being mislead when generating new needles for the tag "text-login". Originally I suggested "tty1-selected" but then I suggested the tag "first-tty-selected" but by now I understand that the actual problem is the very customized code in tests/virt_autotest/reboot_and_wait_up.pm which is introducing another way for login handling where I recommend to use the common approach as for other consoles instead. So if you want to suggest something more scalable I suggest to go that route.

**Comment by waynechen55** [comment]
> I agree that the other PR should not have been merged late during the European day and fallout left for you to handle. That can be done better.
> 
> I forgot to mention in before that I had the faulty PR already reverted with #9519 earlier.
> 
> What I don't understand is what you mean with "not just replace them with something else not directly related". The idea was to further specify what specific console is expected and prevent persons being mislead when generating new needles for the tag "text-login". Originally I suggested "tty1-selected" but then I suggested the tag "first-tty-selected" but by now I understand that the actual problem is the very customized code in tests/virt_autotest/reboot_and_wait_up.pm which is introducing another way for login handling where I recommend to use the common approach as for other consoles instead. So if you want to suggest something more scalable I suggest to go that route.

Because the mentioned reboot_and_wait_up module uses serial console for login. I do not think it is tty1 or tty7. It is ttySX. And the original "text-login" matches login prompt after system boot, even before inputing user name. Additionally, "text-login" can also captures "SUSE LINUX ENTREPRISE SERVER XXXX" on the screen. Seems lots of differences.

**Comment by waynechen55** [comment]
@okurz  I will double check whether your revert works for me. If yes, then I will close this one.

**Comment by waynechen55** [comment]
> @okurz I will double check whether your revert works for me. If yes, then I will close this one.

@okurz There are still many test suites failed on this "tty selected thing". I do not think reboot_and_wait_up should be involved in this refinement in regard to needle. Could you help change it back to "text-login" just as what has been composed in this pull request ?

**Comment by alice-suse** [comment]
@waynechen55 What about the needles? In the author's initial PR to change text-login to tty-selected, it removes text-login needles.

**Comment by waynechen55** [comment]
> @waynechen55 What about the needles? In the author's initial PR to change text-login to tty-selected, it removes text-login needles.



> @waynechen55 What about the needles? In the author's initial PR to change text-login to tty-selected, it removes text-login needles.

This is what I am planning to investigate. If all previous needles removed, then the best way to workaround failures is to fully revert or continue to adapt to creating new needles which surely costs some time.

**Comment by alice-suse** [comment]
Trigger a verification run on osd, need to care about this test result before merge.

Created job #3873031: sle-15-SP2-Online-x86_64-Build136.2-gi-guest_developing-on-host_sles12sp5-xen@64bit-ipmi -> https://openqa.suse.de/t3873031

**Comment by Julie-CAO** [comment]
I prefer to revert all the changes made originally in #9048 and adding back all the removal needles.

**Comment by alice-suse** [comment]
@okurz @Zaoliang @SergioAtSUSE FYI.

**Comment by alice-suse** [comment]
> I prefer to revert all the changes made originally in #9048 and adding back all the removal needles.

I agree. We need to do it to deliver full milestone report for public beta. As for now, to give acceptance report before EOB of today, what can we do now? I will trigger the 3 failing acceptance jobs against this PR on osd once the first one works. If not, will add missing text-login needle for 12sp5 first. Then retrigger until works.

**Comment by alice-suse** [comment]
The verification job https://openqa.suse.de/t3873031 passed, so reverting code at least works for 12sp5 host tests. So merge it now to let acceptance test continue.

**Pull request merged**
