### PR TITLE
Remove all function prototypes

### PR DESCRIPTION
**Pull request by coolo**
They were used really inconsistently and in most cases wrong

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
Validation test that it does not break completely: http://tortuga.suse.de/tests/2003

**Comment by kraih** [comment]
The few cases where it breaks something will prolly be unintended precedence changes, which are fixed easily by adding parentheses to the function call.

**Comment by okurz** [comment]
```
Use of ?PATTERN? without explicit operator is deprecated at tests/jeos/grub2_gfxmode.pm line 45.
Search pattern not terminated at tests/jeos/grub2_gfxmode.pm line 45.
make: *** [test-compile] Error 2
```

Is this what your *atom hammer* caused?

**Comment by kraih** [comment]
@okurz That one should work with `is_jeos()`. I know, it's a bit messy, but that's why the feature is deprecated in the first place. 😉

**Comment by coolo** [comment]
rebased now - the travis failure is about all the modules without maintainer registered. I will merge nonetheless

**Pull request merged**
