### PR TITLE
Use correct distro version for adding source repo

### PR DESCRIPTION
**Pull request by asdil12**
This will fix the `zypper_info` test for `SLE15-SP1`.

Verification: http://artemis.suse.de/tests/424#step/zypper_info/4

### CODE REVIEW

**Comment by asdil12** [comment]
Pending verification: http://artemis.suse.de/tests/414

**Comment by asdil12** [comment]
Added the function `get_repo_var_name`:

This takes something like `MODULE_BASESYSTEM_SOURCE` as parameter and returns  REPO_SLE15_SP1_MODULE_BASESYSTEM_SOURCE` when being called on `SLE15-SP1`.

**Comment by rwx788** [comment]
Sorry, was a bit too late ;)

**Comment by mloviska** [comment]
no worries, we got Anton! :D

**Pull request merged**
